window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 5-1']={
id:'V10-SS-G3-P5-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 5-1',level:'HOP',title:'The Original Story of Cacao',
sentences:['We listen to a speech about cacao.','The topic is the original use of cacao.','Some people regard cacao as medicine.','Europe is part of the story of cacao.','People can crush cacao to make a drink.','We look at a website about cacao.','The website has limited information.','We read the information carefully.','I write notes about the speech.','The original drink was not sweet.','The topic is interesting to our class.','I want to learn more about cacao.'],
fullTranslation:'「私たちはカカオについてのスピーチを聞きます。話題はカカオの本来の使われ方です。カカオを薬とみなした人々もいました。ヨーロッパはカカオの物語の一部です。人々はカカオを砕いて飲み物を作ることができます。私たちはカカオについてのウェブサイトを見ます。そのウェブサイトの情報は限られています。私たちはその情報を注意深く読みます。私はスピーチについてメモを書きます。本来の飲み物は甘くありませんでした。その話題は私たちのクラスにとって興味深いです。私はカカオについてもっと学びたいです。」',
slashRows:[{en:'We listen to / a speech / about cacao.',jp:'私たちは聞きます / スピーチを / カカオについての'},{en:'The topic is / the original use / of cacao.',jp:'その話題は〜です / 本来の使われ方 / カカオの'},{en:'Some people / regard cacao as / medicine.',jp:'人々の中には / カカオを〜とみなします / 薬だと'},{en:'Europe is / part of / the story of cacao.',jp:'ヨーロッパは〜です / 一部 / カカオの物語の'},{en:'People / can crush / cacao / to make a drink.',jp:'人々は / 砕くことができます / カカオを / 飲み物を作るために'},{en:'We look at / a website / about cacao.',jp:'私たちは見ます / ウェブサイトを / カカオについての'},{en:'The website has / limited information.',jp:'そのウェブサイトにはあります / 限られた情報が'},{en:'We read / the information / carefully.',jp:'私たちは読みます / その情報を / 注意深く'},{en:'I write / notes / about the speech.',jp:'私は書きます / メモを / スピーチについて'},{en:'The original drink was not / sweet.',jp:'本来の飲み物は〜ではありませんでした / 甘い'},{en:'The topic is / interesting / to our class.',jp:'その話題は〜です / 興味深い / 私たちのクラスにとって'},{en:'I want to learn / more / about cacao.',jp:'私は学びたいです / もっと / カカオについて'}],
questions:[{prompt:'1. 私たちは何についてのスピーチを聞きますか。本文から英語で答えなさい。',answer:'cacao',evidence:'We listen to a speech about cacao.',evidenceJp:'私たちはカカオについてのスピーチを聞きます。',reason:'about の後ろが cacao です。'},{prompt:'2. 話題はカカオの何についてですか。本文から英語で答えなさい。',answer:'the original use',evidence:'The topic is the original use of cacao.',evidenceJp:'話題はカカオの本来の使われ方です。',reason:'be動詞の後ろが the original use です。'},{prompt:'3. カカオは何とみなされることがありますか。本文から英語で答えなさい。',answer:'medicine',evidence:'Some people regard cacao as medicine.',evidenceJp:'カカオを薬とみなした人々もいました。',reason:'regard A as B のBが medicine です。'},{prompt:'4. 人々はカカオをどうすることができますか。本文から英語で1語抜き出しなさい。',answer:'crush',evidence:'People can crush cacao to make a drink.',evidenceJp:'人々はカカオを砕いて飲み物を作ることができます。',reason:'can の後ろの動詞が crush です。'},{prompt:'5. ウェブサイトの情報はどのようですか。本文から英語で1語抜き出しなさい。',answer:'limited',evidence:'The website has limited information.',evidenceJp:'そのウェブサイトの情報は限られています。',reason:'information を説明する語が limited です。'}],
allowedWords:[["regard A as B / speech / medicine / Europe / crush / original / website / limited / topic / cacao",'PROGRAM5 5-1: v7 canonical partition'],['part / story / people / can / make / drink / look at / information / read / carefully / write / note / sweet / interesting / class / want to / learn / more','G1-G2 and PROGRAM1-4 cumulative']],
auditNote:'最新v7正本PROGRAM5 5-1（ID3756-3765）を直接照合。regard A as B / speech / medicine / Europe / crush / original / website / limited / topic / cacaoを使用。5-2のbegin-began-begun以降、5-3のfair trade系語彙、PROGRAM6語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 5-2']={
id:'V10-SS-G3-P5-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 5-2',level:'HOP',title:'A Graph About Chocolate',
sentences:['We study a graph about chocolate.','The graph can show male and female data.','European people can consume chocolate.','British people are in the graph too.','Chocolate began as a drink in Europe.','Later, people made solid chocolate.','One century was a time of big change.','People can improve a product in many ways.','The graph can help us understand the change.','We compare male and female data.','I can see a difference in the graph.','We write about European chocolate history.'],
fullTranslation:'「私たちはチョコレートについてのグラフを調べます。そのグラフは男性と女性のデータを示すことができます。ヨーロッパの人々はチョコレートを消費します。イギリスの人々もそのグラフに入っています。チョコレートはヨーロッパでは飲み物として始まりました。その後、人々は固体のチョコレートを作りました。ある世紀は大きな変化の時代でした。人々は製品をさまざまな方法で改善できます。そのグラフは私たちが変化を理解する助けになります。私たちは男性と女性のデータを比べます。私はグラフの中に違いを見ることができます。私たちはヨーロッパのチョコレートの歴史について書きます。」',
slashRows:[{en:'We study / a graph / about chocolate.',jp:'私たちは調べます / グラフを / チョコレートについての'},{en:'The graph / can show / male and female data.',jp:'そのグラフは / 示すことができます / 男性と女性のデータを'},{en:'European people / can consume / chocolate.',jp:'ヨーロッパの人々は / 消費することができます / チョコレートを'},{en:'British people are / in the graph / too.',jp:'イギリスの人々もいます / グラフの中に'},{en:'Chocolate began / as a drink / in Europe.',jp:'チョコレートは始まりました / 飲み物として / ヨーロッパで'},{en:'Later, / people made / solid chocolate.',jp:'その後 / 人々は作りました / 固体のチョコレートを'},{en:'One century was / a time / of big change.',jp:'ある世紀は〜でした / 時代 / 大きな変化の'},{en:'People / can improve / a product / in many ways.',jp:'人々は / 改善できます / 製品を / さまざまな方法で'},{en:'The graph / can help / us understand / the change.',jp:'そのグラフは / 助けることができます / 私たちが理解するのを / その変化を'},{en:'We compare / male and female data.',jp:'私たちは比べます / 男性と女性のデータを'},{en:'I can see / a difference / in the graph.',jp:'私は見ることができます / 違いを / グラフの中に'},{en:'We write about / European chocolate history.',jp:'私たちは書きます / ヨーロッパのチョコレートの歴史について'}],
questions:[{prompt:'1. 私たちは何についてのグラフを調べますか。本文から英語で答えなさい。',answer:'chocolate',evidence:'We study a graph about chocolate.',evidenceJp:'私たちはチョコレートについてのグラフを調べます。',reason:'about の後ろが chocolate です。'},{prompt:'2. グラフにはどのようなデータがありますか。本文から英語で答えなさい。',answer:'male and female data',evidence:'The graph can show male and female data.',evidenceJp:'そのグラフは男性と女性のデータを示すことができます。',reason:'show の目的語が male and female data です。'},{prompt:'3. チョコレートはヨーロッパで何として始まりましたか。本文から英語で答えなさい。',answer:'a drink',evidence:'Chocolate began as a drink in Europe.',evidenceJp:'チョコレートはヨーロッパでは飲み物として始まりました。',reason:'as の後ろが a drink です。'},{prompt:'4. その後、人々はどのようなチョコレートを作りましたか。本文から英語で答えなさい。',answer:'solid chocolate',evidence:'Later, people made solid chocolate.',evidenceJp:'その後、人々は固体のチョコレートを作りました。',reason:'made の目的語が solid chocolate です。'},{prompt:'5. 人々は何をすることができますか。本文から英語で1語抜き出しなさい。',answer:'improve',evidence:'People can improve a product in many ways.',evidenceJp:'人々は製品をさまざまな方法で改善できます。',reason:'can の後ろの動詞が improve です。'}],
allowedWords:[["begin-began-begun / improve / male / consume / female / European / graph / century / solid / British",'PROGRAM5 5-2: v7 canonical partition used'],['neck / trunk / stripe','PROGRAM5 5-2: v7 canonical partition retained but not forced into this chocolate-history passage'],['chocolate / people / drink / Europe / later / make / time / change / product / many / ways / help / understand / compare / data / see / difference / write / history','PROGRAM5 5-1 and earlier cumulative']],
auditNote:'最新v7正本PROGRAM5 5-2（ID3766-3778）を直接照合。begin-began-begun（began）/ improve / male / consume / female / European / graph / century / solid / Britishを使用。neck / trunk / stripeは本文テーマを壊すため無理に消化せず、5-3語彙とPROGRAM6語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 5-3']={
id:'V10-SS-G3-P5-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 5-3',level:'HOP',title:'Looking for Fair Trade Chocolate',
sentences:['We look for a fair trade package at a store.','The package is perfect for a gift.','A magazine has an image of a cacao farm.','We can see a small yard in the image.','Fair trade is an important movement.','Some people can be forced to work for an unfair price.','We check the price on each package.','One dark chocolate has a strong flavor.','The combination of cacao and sugar is popular.','The store can serve hot chocolate.','We can see cacao powder on one side of a picture.','The scene in the magazine is dramatic.','The farm is important to the people there.','We talk about the fair trade movement.','I choose one package at the end.'],
fullTranslation:'「私たちは店でフェアトレードのパッケージを探します。そのパッケージは贈り物にぴったりです。雑誌にはカカオ農園の写真があります。私たちはその写真の中に小さな庭を見ることができます。フェアトレードは大切な運動です。人々の中には不公平な価格のために働かざるを得ない人もいます。私たちはそれぞれのパッケージの価格を確認します。あるダークチョコレートには強い風味があります。カカオと砂糖の組み合わせは人気があります。その店はホットチョコレートを出すことができます。私たちは絵の片側にカカオの粉を見ることができます。雑誌のその場面は劇的です。その農園はそこで暮らす人々にとって大切です。私たちはフェアトレード運動について話します。最後に私は1つのパッケージを選びます。」',
slashRows:[{en:'We look for / a fair trade package / at a store.',jp:'私たちは探します / フェアトレードのパッケージを / 店で'},{en:'The package is / perfect / for a gift.',jp:'そのパッケージは〜です / ぴったり / 贈り物に'},{en:'A magazine has / an image / of a cacao farm.',jp:'雑誌にはあります / 写真が / カカオ農園の'},{en:'We can see / a small yard / in the image.',jp:'私たちは見ることができます / 小さな庭を / その写真の中に'},{en:'Fair trade is / an important movement.',jp:'フェアトレードは〜です / 大切な運動'},{en:'Some people / can be forced to work / for an unfair price.',jp:'人々の中には / 働かざるを得ないことがあります / 不公平な価格のために'},{en:'We check / the price / on each package.',jp:'私たちは確認します / 価格を / それぞれのパッケージの'},{en:'One dark chocolate has / a strong flavor.',jp:'あるダークチョコレートにはあります / 強い風味が'},{en:'The combination / of cacao and sugar / is popular.',jp:'組み合わせは / カカオと砂糖の / 人気があります'},{en:'The store / can serve / hot chocolate.',jp:'その店は / 出すことができます / ホットチョコレートを'},{en:'We can see / cacao powder / on one side / of a picture.',jp:'私たちは見ることができます / カカオの粉を / 片側に / 絵の'},{en:'The scene / in the magazine / is / dramatic.',jp:'その場面は / 雑誌の中の / 〜です / 劇的な'},{en:'The farm is / important / to the people there.',jp:'その農園は〜です / 大切 / そこにいる人々にとって'},{en:'We talk about / the fair trade movement.',jp:'私たちは話します / フェアトレード運動について'},{en:'I choose / one package / at the end.',jp:'私は選びます / 1つのパッケージを / 最後に'}],
questions:[{prompt:'1. 私たちは何を探しますか。本文から英語で答えなさい。',answer:'a fair trade package',evidence:'We look for a fair trade package at a store.',evidenceJp:'私たちは店でフェアトレードのパッケージを探します。',reason:'look for の目的語が a fair trade package です。'},{prompt:'2. 雑誌には何の写真がありますか。本文から英語で答えなさい。',answer:'a cacao farm',evidence:'A magazine has an image of a cacao farm.',evidenceJp:'雑誌にはカカオ農園の写真があります。',reason:'image of の後ろが a cacao farm です。'},{prompt:'3. フェアトレードは何ですか。本文から英語で答えなさい。',answer:'an important movement',evidence:'Fair trade is an important movement.',evidenceJp:'フェアトレードは大切な運動です。',reason:'be動詞の後ろが an important movement です。'},{prompt:'4. 何をそれぞれのパッケージで確認しますか。本文から英語で答えなさい。',answer:'the price',evidence:'We check the price on each package.',evidenceJp:'私たちはそれぞれのパッケージの価格を確認します。',reason:'check の目的語が the price です。'},{prompt:'5. その店は何を出すことができますか。本文から英語で答えなさい。',answer:'hot chocolate',evidence:'The store can serve hot chocolate.',evidenceJp:'その店はホットチョコレートを出すことができます。',reason:'serve の目的語が hot chocolate です。'}],
allowedWords:[["perfect / package / look for ~ / movement / be forced to ~ / image / serve / farm / yard / fair trade / powder / magazine / flavor / scene / combination / dark / side / dramatic / price",'PROGRAM5 5-3: v7 canonical partition used'],['unfairly','PROGRAM5 5-3: v7 canonical partition retained but not forced'],['cacao / store / gift / small / important / people / work / unfair / each / chocolate / strong / sugar / popular / hot / picture / there / talk about / choose / one / at the end','PROGRAM5 5-1/5-2 and earlier cumulative']],
auditNote:'最新v7正本PROGRAM5 5-3（ID3779-3799）を直接照合。perfect / package / look for / movement / be forced to / image / serve / farm / yard / fair trade / powder / magazine / flavor / scene / combination / dark / side / dramatic / priceを使用。unfairlyは文脈を不自然にしないため無理に消化せず、PROGRAM6語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
