window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};
window.V10_PASSAGES_G2_SS['PROGRAM 5-2']={
 id:'V10-SS-G2-P5-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 5-2',level:'HOP',title:'Take Action in an Earthquake',
 sentences:['Today, we meet an architect at our school.','We learn about an earthquake.','A strong earthquake can be dangerous.','We must take action.','During an earthquake, the elevator can be dangerous.','In particular, we must not use the elevator.','We choose a safe place.','We decide to remember the safety rule.','We try to remember it.','We practice again and again.','While we practice, the architect can guide us.','Earthquake safety is especially important.','An international organization can help people.','We want to prevent trouble.','We decide to learn more.'],
 fullTranslation:'「今日、私たちは学校で建築家に会います。私たちは地震について学びます。強い地震は危険なことがあります。私たちは行動を起こさなければなりません。地震の間、エレベーターは危険なことがあります。特に、エレベーターを使ってはいけません。私たちは安全な場所を選びます。安全の規則を覚えることに決めます。それを覚えようとします。何度も練習します。練習している間、建築家が私たちを案内できます。地震の安全は特に重要です。国際的な組織は人々を助けることができます。私たちは問題を防ぎたいです。もっと学ぶことに決めます。」',
 slashRows:[{en:'Today, / we meet / an architect / at our school.',jp:'今日 / 私たちは会います / 建築家に / 私たちの学校で'},{en:'We learn about / an earthquake.',jp:'私たちは学びます / 地震について'},{en:'A strong earthquake can be / dangerous.',jp:'強い地震は〜なことがあります / 危険な'},{en:'We must take action.',jp:'私たちは行動を起こさなければなりません'},{en:'During an earthquake, / the elevator can be / dangerous.',jp:'地震の間 / エレベーターは〜なことがあります / 危険な'},{en:'In particular, / we must not use / the elevator.',jp:'特に / 私たちは使ってはいけません / エレベーターを'},{en:'We choose / a safe place.',jp:'私たちは選びます / 安全な場所を'},{en:'We decide to remember / the safety rule.',jp:'私たちは覚えることに決めます / 安全の規則を'},{en:'We try to remember / it.',jp:'私たちは覚えようとします / それを'},{en:'We practice / again and again.',jp:'私たちは練習します / 何度も'},{en:'While we practice, / the architect can guide / us.',jp:'私たちが練習している間 / 建築家は案内できます / 私たちを'},{en:'Earthquake safety is / especially important.',jp:'地震の安全は〜です / 特に重要な'},{en:'An international organization can help / people.',jp:'国際的な組織は助けられます / 人々を'},{en:'We want to prevent / trouble.',jp:'私たちは防ぎたいです / 問題を'},{en:'We decide to learn / more.',jp:'私たちは学ぶことに決めます / もっと'}],
 questions:[{prompt:'1. 今日、学校で誰に会いますか。本文から英語で答えなさい。',answer:'an architect',evidence:'Today, we meet an architect at our school.',evidenceJp:'今日、私たちは学校で建築家に会います。',reason:'meet の目的語が an architect です。'},{prompt:'2. 強い地震はどのようなものになりえますか。本文から英語で1語抜き出しなさい。',answer:'dangerous',evidence:'A strong earthquake can be dangerous.',evidenceJp:'強い地震は危険なことがあります。',reason:'dangerous が earthquake を説明しています。'},{prompt:'3. 地震のとき、何を使ってはいけませんか。本文から英語で答えなさい。',answer:'the elevator',evidence:'In particular, we must not use the elevator.',evidenceJp:'特に、エレベーターを使ってはいけません。',reason:'use の目的語が the elevator です。'},{prompt:'4. 何度くらい練習しますか。本文から英語で答えなさい。',answer:'again and again',evidence:'We practice again and again.',evidenceJp:'何度も練習します。',reason:'again and again が反復を表しています。'},{prompt:'5. 何を防ぎたいですか。本文から英語で答えなさい。',answer:'trouble',evidence:'We want to prevent trouble.',evidenceJp:'私たちは問題を防ぎたいです。',reason:'prevent の目的語が trouble です。'}],
 allowedWords:[['architect / especially / choose / prevent / earthquake / decide to ~ / take action / certain / while / during / elevator / strong / dangerous / almost / in particular / again and again / international organization / try to ~','PROGRAM 5-2: canonical Sheet IDs 3124-3141'],['must / rule / guide / trouble','PROGRAM 4 cumulative'],['school / meet / learn / safe / place / remember / practice / important / help / people / want to / more / use','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 5-2をID3124〜3141まで直接照合。初稿のarchitect visitsという未登録三単現を人手ゲートで検出し、we meet an architectへ修正。take action / during / in particular / decide to / try to / while / again and again / international organizationを地震時の行動という1場面に統合。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
