// Human-reviewed vocabulary/slash final audit overrides for passages 071-080.
(function(){
  const ss2=window.V10_PASSAGES_G2_SS||{};
  function setAudit(section,rows){const p=ss2[section];if(!p)throw new Error('Missing '+section);if(rows.length!==p.sentences.length)throw new Error('Slash mismatch '+section);p.slashRows=rows;p.slashHumanAudit='PASS_MODEL_ALIGNED';p.vocabFinalAudit=p.vocabFinalAudit||'PASS_REVIEWED_GATE_RECHECK_NOTES_0';}

  setAudit('PROGRAM 1-2',[
    {en:'Tomorrow, / I will leave this town.',jp:'明日 / 私はこの町を出ます'},{en:'I am a bit worried.',jp:'私は少し心配です。'},{en:'My friend and I are at the local park.',jp:'友達と私は地元の公園にいます。'},{en:'This park is special to us.',jp:'この公園は私たちにとって特別です。'},{en:'We often talked here / after school.',jp:'私たちはよくここで話しました / 放課後に'},{en:'“Take care.”',jp:'「気をつけてね。」'},{en:'“Thank you.”',jp:'「ありがとう。」'},{en:'I won’t forget my friends.',jp:'私は友達を忘れません。'},{en:'I won’t forget this town, either.',jp:'私はこの町も忘れません。'},{en:'“I’ll text you.”',jp:'「メールするね。」'},{en:'“You can text me, too.”',jp:'「あなたも私にメールしてね。」'},{en:'We will keep in touch.',jp:'私たちは連絡を取り続けます。'},{en:'I hope / my friend will be fine.',jp:'私は願っています / 友達が元気でいることを'},{en:'I will visit this park / again someday.',jp:'私はこの公園を訪れます / いつかまた'}
  ]);
  setAudit('PROGRAM 1-3',[
    {en:'I am overseas / now.',jp:'私は海外にいます / 今'},{en:'Today is my first day / at my new school.',jp:'今日は私の初日です / 新しい学校での'},{en:'My class has a short quiz.',jp:'私のクラスでは短い小テストがあります。'},{en:'I am a bit worried.',jp:'私は少し心配です。'},{en:'“Why don’t you take a short break?”',jp:'「少し休憩したらどう？」'},{en:'A student near me smiles.',jp:'近くの生徒がほほえみます。'},{en:'“Sounds nice. Thank you.”',jp:'「いいね。ありがとう。」'},{en:'We read our books / during the break.',jp:'私たちは本を読みます / 休憩中に'},{en:'We talk about the quiz.',jp:'私たちは小テストについて話します。'},{en:'The student helps me.',jp:'その生徒は私を助けてくれます。'},{en:'Maybe, / I can make a new friend.',jp:'もしかすると / 新しい友達ができるかもしれません'},{en:'I won’t cry.',jp:'私は泣きません。'},{en:'I’ll do my best.',jp:'できるだけ頑張ります。'}
  ]);
  setAudit('PROGRAM 2-1',[
    {en:'I heard about a baseball project / in Africa.',jp:'私は野球プロジェクトについて聞きました / アフリカの'},{en:'The project promotes baseball / for children in a city.',jp:'そのプロジェクトは野球を広めています / ある町の子どもたちのために'},{en:'A coach is very passionate about the project.',jp:'あるコーチはそのプロジェクトにとても情熱を持っています。'},{en:'The coach teaches baseball / after school.',jp:'そのコーチは野球を教えます / 放課後に'},{en:'Children practice together.',jp:'子どもたちはいっしょに練習します。'},{en:'Games take place / around the city.',jp:'試合が行われます / 町のあちこちで'},{en:'The work is not easy.',jp:'その活動は簡単ではありません。'},{en:'Some days are difficult.',jp:'大変な日もあります。'},{en:'Many people root for the children.',jp:'多くの人が子どもたちを応援しています。'},{en:'I am interested in the project.',jp:'私はそのプロジェクトに興味があります。'},{en:'I hope / the project will be successful.',jp:'私は願っています / そのプロジェクトが成功することを'}
  ]);
  setAudit('PROGRAM 2-2',[
    {en:'Today, / I visit a university.',jp:'今日 / 私は大学を訪れます'},{en:'I meet a baseball coach / there.',jp:'私は野球のコーチに会います / そこで'},{en:'The coach works / in a national program.',jp:'そのコーチは活動しています / 全国的なプログラムで'},{en:'The program is about baseball and peace.',jp:'そのプログラムは野球と平和についてのものです。'},{en:'The coach tells me about the program.',jp:'コーチはそのプログラムについて私に話してくれます。'},{en:'People play baseball together / in the program.',jp:'人々はいっしょに野球をします / そのプログラムで'},{en:'When people play together, / they can be friends.',jp:'人々がいっしょにプレーすると / 友達になることができます'},{en:'The coach believes / sport can create peace.',jp:'コーチは信じています / スポーツが平和を生み出せると'},{en:'I am interested in the program.',jp:'私はそのプログラムに興味があります。'},{en:'We talk about baseball and peace.',jp:'私たちは野球と平和について話します。'},{en:'I want to join the program / someday.',jp:'私はそのプログラムに参加したいです / いつか'},{en:'I hope / many people will be interested in it.',jp:'私は願っています / 多くの人がそれに興味を持つことを'}
  ]);
  setAudit('PROGRAM 2-3',[
    {en:'Our baseball project has a game / today.',jp:'私たちの野球プロジェクトでは試合があります / 今日'},{en:'Our goal is to play together / and learn from the game.',jp:'私たちの目標はいっしょにプレーすることです / そして試合から学ぶことです'},{en:'The game is difficult.',jp:'その試合は難しいです。'},{en:'One player has trouble.',jp:'1人の選手が困っています。'},{en:'We help each other.',jp:'私たちは助け合います。'},{en:'A player hits a home run.',jp:'ある選手がホームランを打ちます。'},{en:'Everyone is happy.',jp:'みんなうれしいです。'},{en:'After the game, / we talk together.',jp:'試合のあと / 私たちはいっしょに話します'},{en:'We learn / through the game.',jp:'私たちは学びます / その試合を通して'},{en:'In fact, / sport can have a positive effect.',jp:'実際 / スポーツにはよい効果があります'},{en:'Sport can foster peace.',jp:'スポーツは平和を育むことができます。'},{en:'We believe in the power of sport.',jp:'私たちはスポーツの力を信じています。'},{en:'I want to remember this idea.',jp:'私はこの考えを覚えておきたいです。'}
  ]);
  setAudit('PROGRAM 3-1',[
    {en:'Today, / I am at an American festival.',jp:'今日 / 私はアメリカの祭りにいます'},{en:'I wait for my friend.',jp:'私は友達を待ちます。'},{en:'Many people are at the festival.',jp:'祭りにはたくさんの人がいます。'},{en:'My friend is here / now.',jp:'友達がここにいます / 今'},{en:'We eat a light meal / together.',jp:'私たちは軽い食事をします / いっしょに'},{en:'The taste is very good.',jp:'その味はとてもよいです。'},{en:'We listen to music.',jp:'私たちは音楽を聞きます。'},{en:'We talk about the festival.',jp:'私たちは祭りについて話します。'},{en:'I am interested in American culture.',jp:'私はアメリカの文化に興味があります。'},{en:'The festival is very exciting.',jp:'その祭りはとてもわくわくします。'},{en:'I want to visit the festival / again.',jp:'私はその祭りを訪れたいです / また'},{en:'It is a special day / for me.',jp:'それは特別な一日です / 私にとって'}
  ]);
  setAudit('PROGRAM 3-2',[
    {en:'Today, / we sell handmade cards / at the festival.',jp:'今日 / 私たちは手作りのカードを売ります / 祭りで'},{en:'The cards are for our project.',jp:'そのカードは私たちのプロジェクトのためのものです。'},{en:'Some children make the cards / themselves.',jp:'何人かの子どもたちはそのカードを作ります / 自分たちで'},{en:'Here is a thin card.',jp:'ここに薄いカードがあります。'},{en:'It is light and beautiful.',jp:'それは軽くてきれいです。'},{en:'I make a card, too.',jp:'私もカードを作ります。'},{en:'Many people buy the cards.',jp:'多くの人がそのカードを買います。'},{en:'We earn money / for our project.',jp:'私たちはお金を得ます / 私たちのプロジェクトのために'},{en:'I like the children’s work.',jp:'私は子どもたちの作品が好きです。'},{en:'The festival is special for me.',jp:'その祭りは私にとって特別です。'},{en:'I look forward to visiting the festival / again.',jp:'私はその祭りを訪れるのを楽しみにしています / また'}
  ]);
  setAudit('PROGRAM 3-3',[
    {en:'At the festival, / I meet a Dutch student.',jp:'祭りで / 私はオランダ人の生徒に会います'},{en:'The student is from the Netherlands.',jp:'その生徒はオランダ出身です。'},{en:'The student has a job / at a charity stall.',jp:'その生徒は仕事をしています / 慈善活動の屋台で'},{en:'“Can you show me this bowl?”',jp:'「このおわんを見せてもらえますか。」'},{en:'“Sure.”',jp:'「もちろん。」'},{en:'The bowl is handmade.',jp:'そのおわんは手作りです。'},{en:'Each bowl is light.',jp:'どのおわんも軽いです。'},{en:'I can carry it / easily.',jp:'私はそれを運べます / 簡単に'},{en:'People buy the handmade bowls.',jp:'人々は手作りのおわんを買います。'},{en:'The stall earns money.',jp:'その屋台はお金を得ます。'},{en:'At the end, / the students donate the money.',jp:'最後に / 生徒たちはそのお金を寄付します'},{en:'I like their work.',jp:'私は彼らの活動が好きです。'},{en:'I want to visit this festival / again.',jp:'私はその祭りを訪れたいです / また'}
  ]);
  setAudit('PROGRAM 4-1',[
    {en:'Today, / the sky is clear.',jp:'今日 / 空は晴れています'},{en:'My friend and I go hiking.',jp:'友達と私はハイキングに行きます。'},{en:'My friend can guide me.',jp:'友達は私を案内できます。'},{en:'We walk / in a forest.',jp:'私たちは歩きます / 森の中を'},{en:'I see a footprint.',jp:'私は足跡を見つけます。'},{en:'“Is it a deer footprint?”',jp:'「鹿の足跡ですか。」'},{en:'“Yes, it is.”',jp:'「はい、そうです。」'},{en:'Actually, / we see a deer / near us.',jp:'実際 / 私たちは鹿を見つけます / 私たちの近くに'},{en:'I am glad to see it.',jp:'それを見ることができてうれしいです。'},{en:'We watch the deer / for a short time.',jp:'私たちはその鹿を見ます / 少しの間'},{en:'After the hike, / we talk about the footprint and the deer.',jp:'ハイキングのあと / 私たちは足跡と鹿について話します'},{en:'I want to go hiking / again.',jp:'私はハイキングに行きたいです / また'}
  ]);
  setAudit('PROGRAM 4-2',[
    {en:'We are in a forest / today.',jp:'私たちは森にいます / 今日'},{en:'Our guide tells us an important rule.',jp:'ガイドが私たちに大切なルールを教えてくれます。'},{en:'First of all, / we must protect the forest.',jp:'まず何より / 私たちは森を守らなければなりません'},{en:'We must not leave garbage.',jp:'ごみを残してはいけません。'},{en:'We must keep the forest clean.',jp:'森をきれいに保たなければなりません。'},{en:'We must help each other.',jp:'私たちは助け合わなければなりません。'},{en:'If we have trouble, / we should talk to our guide.',jp:'困ったことがあれば / ガイドに話すべきです'},{en:'The forest is quiet.',jp:'森は静かです。'},{en:'We should walk carefully / and enjoy it.',jp:'注意して歩くべきです / そして森を楽しむべきです'},{en:'This rule helps us protect the forest.',jp:'このルールは私たちが森を守るのに役立ちます。'},{en:'I am glad to learn the rule.',jp:'そのルールを学べてうれしいです。'}
  ]);
  window.V10_VOCAB_SLASH_FINAL_071_080={range:'071-080',vocabAudited:10,slashAudited:10,rewritten:0,notes:0};
})();