// Reference/minimum-rule slash audit passages 081-090.
(function(){
 const PASS='PASS_REFERENCE_20260820';
 function setAudit(data,section,rows,n){const p=data&&data[section];if(!p)throw new Error('Missing reference passage '+n+': '+section);if(rows.length!==(p.sentences||[]).length)throw new Error('Row mismatch '+n);for(let i=0;i<rows.length;i++){const e=String(rows[i].en||'').replace(/\s*\/\s*/g,' ').replace(/\s+/g,' ').trim(),s=String(p.sentences[i]||'').replace(/\s+/g,' ').trim();if(e!==s)throw new Error('English mismatch '+n+'#'+(i+1)+': '+e+' <> '+s);const ec=String(rows[i].en||'').split(/\s*\/\s*/).filter(Boolean).length,jc=String(rows[i].jp||'').split(/\s*\/\s*/).filter(Boolean).length;if(ec!==jc)throw new Error('EN/JP chunks '+n+'#'+(i+1)+' '+ec+'/'+jc)}p.slashRows=rows;p.slashReadingVersion='reference-book-minimum-rules-20260820';p.slashReferenceAudit=PASS;p.slashReferencePassageNo=n}
 const d=window.V10_PASSAGES_G2_SS||{};
 setAudit(d,'PROGRAM 4-3',[
  {en:'Tomorrow, / we have a school trip.',jp:'明日 / 私たちは修学旅行があります'},{en:'I check our list tonight.',jp:'今夜、私は私たちのリストを確認します。'},{en:'First of all, / we must be / on time.',jp:'まず何より / 私たちは〜でなければなりません / 時間どおり'},{en:'We must come / to school / by seven.',jp:'私たちは来なければなりません / 学校へ / 7時までに'},{en:'We visit a dam / in the morning.',jp:'私たちはダムを訪れます / 午前中に'},{en:'An engineer can guide us there.',jp:'そこでエンジニアが私たちを案内してくれます。'},{en:'We must listen / to the engineer.',jp:'私たちは聞かなければなりません / エンジニアの話を'},{en:'We mustn’t make loud noise / at the dam.',jp:'私たちは大きな音を立ててはいけません / ダムで'},{en:'We can have a snack / at noon.',jp:'私たちは軽食をとれます / 正午に'},{en:'At night, / we go / to bed / by ten.',jp:'夜 / 私たちは行きます / 寝床へ / 10時までに'},{en:'I check the list again.',jp:'私はもう一度リストを確認します。'},{en:'Now I am ready / for the school trip.',jp:'今、私は準備ができています / 修学旅行の'}
 ],81);
 setAudit(d,'PROGRAM 5-1',[
  {en:'Today is my first day / at a bookshop.',jp:'今日は私の初日です / 本屋での'},{en:'The director tells me what / to do.',jp:'店長は私に何かを教えます / すればよいことを'},{en:'First, / I learn where / to put a book.',jp:'まず / 私はどこかを学びます / 本を置く場所を'},{en:'There are shelves / by the wall.',jp:'棚があります / 壁のそばに'},{en:'I put a book / on this shelf / by mistake.',jp:'私は本を置きます / この棚に / まちがって'},{en:'The director helps me.',jp:'店長が助けてくれます。'},{en:'The director shows me another shelf.',jp:'店長は別の棚を見せてくれます。'},{en:'Now I know what / to do.',jp:'今、私は何か分かります / すればよいことを'},{en:'At noon, / I take a short break.',jp:'正午に / 私は短い休憩を取ります'},{en:'I buy water / at a vending machine / near the shop.',jp:'私は水を買います / 自動販売機で / 店の近くの'},{en:'After the break, / I put more books / on the shelves.',jp:'休憩のあと / 私はさらに本を置きます / 棚に'},{en:'I enjoy the work.',jp:'私はその仕事を楽しみます。'},{en:'I want / to work here again.',jp:'私は望んでいます / またここで働くことを'}
 ],82);
 setAudit(d,'PROGRAM 5-2',[
  {en:'Today, / we meet an architect / at our school.',jp:'今日 / 私たちは建築家に会います / 学校で'},{en:'We learn / about earthquake safety.',jp:'私たちは学びます / 地震の安全について'},{en:'A strong earthquake can be dangerous.',jp:'強い地震は危険なことがあります。'},{en:'We must take action quickly.',jp:'私たちはすばやく行動しなければなりません。'},{en:'In particular, / we must not use the elevator.',jp:'特に / 私たちはエレベーターを使ってはいけません'},{en:'We choose a safe place.',jp:'私たちは安全な場所を選びます。'},{en:'The architect tells us what / to do.',jp:'建築家は私たちに何かを教えます / すればよいことを'},{en:'Then we practice the safety rule.',jp:'それから安全のルールを練習します。'},{en:'While we practice, / the architect guides us.',jp:'私たちが練習している間 / 建築家が私たちを案内します'},{en:'We practice again / and again.',jp:'私たちは練習します / 何度も'},{en:'After the drill, / we talk / about the rule.',jp:'訓練のあと / 私たちは話します / そのルールについて'},{en:'We decide / to remember it.',jp:'私たちは決めます / それを覚えることに'},{en:'Earthquake safety is especially important.',jp:'地震の安全は特に重要です。'}
 ],83);
 setAudit(d,'PROGRAM 5-3',[
  {en:'Yesterday, / my friend lent me a book.',jp:'昨日 / 友達が私に本を貸してくれました'},{en:'The book was / about a U.N. worker / and a volunteer.',jp:'その本は〜でした / 国連で働く人について / そしてボランティアについて'},{en:'My friend gave me good advice / for my project, / too.',jp:'友達は私によい助言をくれました / 私のプロジェクトのために / 〜もまた'},{en:'I thanked my friend.',jp:'私は友達にお礼を言いました。'},{en:'Today, / I read the book again.',jp:'今日 / 私はその本をもう一度読みます'},{en:'I make use / of the book / for my project.',jp:'私は活用します / その本を / プロジェクトのために'},{en:'I make use / of the advice, / too.',jp:'私は活用します / その助言を / 〜もまた'},{en:'The book gives me a good idea.',jp:'その本は私によい考えを与えてくれます。'},{en:'After a while, / I finish my work.',jp:'しばらくして / 私は作業を終えます'},{en:'I send a message / to my friend.',jp:'私はメッセージを送ります / 友達に'},{en:'“Thanks / for your help.”',jp:'「ありがとう / 手伝ってくれて」'},{en:'I want / to lend the book / to another friend someday.',jp:'私は望んでいます / その本を貸すことを / いつか別の友達に'}
 ],84);
 setAudit(d,'PROGRAM 6-1',[
  {en:'Today, / we learn / about a high-tech idea / from a leaf.',jp:'今日 / 私たちは学びます / ハイテクの考えについて / 葉から生まれた'},{en:'First, / we look / at one wet leaf.',jp:'まず / 私たちは見ます / ぬれた葉を1枚'},{en:'Water can stick / to this leaf.',jp:'水はくっつくことがあります / この葉に'},{en:'Then, / we look / at another leaf.',jp:'次に / 私たちは見ます / 別の葉を'},{en:'Water does not stick / to the second leaf.',jp:'水はくっつきません / 2枚目の葉に'},{en:'For this idea, / the second leaf is better / than the first leaf.',jp:'この考えには / 2枚目の葉のほうがよいです / 最初の葉より'},{en:'We look / at the two leaves together.',jp:'私たちは見ます / 2枚の葉をいっしょに'},{en:'We think / about a bag / in the rain.',jp:'私たちは考えます / かばんについて / 雨の中の'},{en:'A bag can get wet / in the rain.',jp:'かばんはぬれることがあります / 雨の中で'},{en:'This leaf can give us an idea / for a better bag.',jp:'この葉は私たちに考えを与えてくれます / よりよいかばんのための'},{en:'The idea can help keep the bag dry.',jp:'その考えはかばんを乾いた状態に保つのに役立ちます。'},{en:'A leaf can teach us a lot.',jp:'葉は私たちに多くのことを教えてくれます。'},{en:'I want / to learn / about another high-tech idea.',jp:'私は望んでいます / 学ぶことを / 別のハイテクの考えについて'}
 ],85);
 setAudit(d,'PROGRAM 6-2',[
  {en:'One day, / I sail / on a boat.',jp:'ある日 / 私は航海します / 船で'},{en:'The deck is wet.',jp:'甲板はぬれています。'},{en:'I can slip / on the wet deck.',jp:'私はすべることがあります / ぬれた甲板で'},{en:'My pet can walk there / without trouble.',jp:'私のペットはそこで歩けます / 困ることなく'},{en:'I look / at my pet’s paw.',jp:'私は見ます / ペットの足を'},{en:'The paw does not slip / on the wet deck.',jp:'その足はすべりません / ぬれた甲板で'},{en:'I get inspiration / from the paw.',jp:'私はひらめきを得ます / その足から'},{en:'I decide / to develop a better shoe.',jp:'私は決めます / もっとよい靴を開発することに'},{en:'I make a boat shoe.',jp:'私はデッキシューズを作ります。'},{en:'With the shoe, / I can walk / on the wet deck.',jp:'その靴があれば / 私は歩くことができます / ぬれた甲板を'},{en:'The invention is useful / on a boat.',jp:'その発明は役に立ちます / 船の上で'},{en:'I think it is my best idea.',jp:'私はそれが自分の最高の考えだと思います。'},{en:'Nature can give people a good idea.',jp:'自然は人々によい考えを与えることができます。'}
 ],86);
 setAudit(d,'PROGRAM 6-3',[
  {en:'Today, / we start an eco-friendly effort / at school.',jp:'今日 / 私たちは環境にやさしい取り組みを始めます / 学校で'},{en:'We want / to save energy / in our classroom.',jp:'私たちは望んでいます / エネルギーを節約することを / 教室で'},{en:'First, / we turn off the light / when we do not need it.',jp:'まず / 私たちは明かりを消します / 必要でないとき'},{en:'We can use less electricity this way.',jp:'このようにして、より少ない電気を使うことができます。'},{en:'We also turn off other things / when we do not use them.',jp:'使わないとき / 私たちはほかのものも消します'},{en:'We check the classroom / before we leave.',jp:'私たちは教室を確認します / 出る前に'},{en:'We are able / to save energy every day.',jp:'私たちはできます / 毎日エネルギーを節約することが'},{en:'We continue this effort together.',jp:'私たちはこの取り組みをいっしょに続けます。'},{en:'A small effort can help our school.',jp:'小さな取り組みでも学校の役に立つことができます。'},{en:'We search / for another eco-friendly idea.',jp:'私たちは探します / 別の環境にやさしい考えを'},{en:'Tomorrow, / we want / to use less energy again.',jp:'明日 / 私たちは望んでいます / またより少ないエネルギーを使うことを'}
 ],87);
 setAudit(d,'PROGRAM 7-1',[
  {en:'Today, / we get information / about a penguin.',jp:'今日 / 私たちは情報を得ます / ペンギンについての'},{en:'A penguin can breathe air.',jp:'ペンギンは空気を呼吸できます。'},{en:'It can swim / in cold water.',jp:'それは泳げます / 冷たい水の中を'},{en:'It can go somewhere far / for food.',jp:'それは遠くへ行けます / 食べ物を求めて'},{en:'After swimming, / it can leave the water.',jp:'泳いだあと / それは水から出ることができます'},{en:'Then it can warm up its body.',jp:'それから体を温めます。'},{en:'It does this / in order / to keep warm.',jp:'それはこうします / その目的で / 温かく保つために'},{en:'A penguin is not a mammal.',jp:'ペンギンはほ乳類ではありません。'},{en:'You cannot see fur / on a penguin.',jp:'あなたは毛皮を見ることができません / ペンギンに'},{en:'My friend / and I read the information together.',jp:'私の友達 / そして私はその情報をいっしょに読みます'},{en:'We agree / that these facts are quite surprising.',jp:'私たちは意見が一致します / これらの事実はとても驚くべきものだと'},{en:'We write the new information / in our notebook.',jp:'私たちは新しい情報を書きます / ノートに'},{en:'I want / to know more / about this animal.',jp:'私は望んでいます / もっと知ることを / この動物について'}
 ],88);
 setAudit(d,'PROGRAM 7-2',[
  {en:'At a pet shop, / I see a hamster.',jp:'ペットショップで / 私はハムスターを見ます'},{en:'It is quite adorable.',jp:'とてもかわいいです。'},{en:'A hamster can put food / in its cheek.',jp:'ハムスターは食べ物を入れることができます / ほおに'},{en:'Its cheek can get big.',jp:'そのほおは大きくなることがあります。'},{en:'The hamster can keep food there.',jp:'ハムスターはそこに食べ物を入れておけます。'},{en:'My friend asks, / “How much food can it keep?”',jp:'友達がたずねます / 「どのくらい食べ物を入れておけるの？」'},{en:'I say, / “I have no idea.”',jp:'私は言います / 「わかりません」'},{en:'We get information / about the hamster.',jp:'私たちは情報を得ます / ハムスターについての'},{en:'We learn / that it can keep a lot / of food / in its cheek.',jp:'私たちは学びます / それがたくさん入れておけると / 食べ物を / ほおに'},{en:'I think this is quite surprising.',jp:'私はこれはとても驚くべきことだと思います。'},{en:'My friend agrees / with me.',jp:'友達は同意します / 私に'},{en:'We read more information together.',jp:'私たちはいっしょにさらに情報を読みます。'},{en:'I want / to see the hamster again.',jp:'私は望んでいます / またそのハムスターを見ることを'}
 ],89);
 setAudit(d,'PROGRAM 7-3',[
  {en:'A hamster is lovely.',jp:'ハムスターは愛らしいです。'},{en:'Though it is small, / it can move quickly.',jp:'小さいけれど / すばやく動くことができます'},{en:'It is not always awake / in the daytime.',jp:'それはいつも目を覚ましているとは限りません / 昼間に'},{en:'In the daytime, / it can sleep / in a safe place.',jp:'昼間は / それは眠れます / 安全な場所で'},{en:'At nighttime, / it can be awake / and look / for food.',jp:'夜間には / それは目を覚ましていられます / そして探せます / 食べ物を'},{en:'It can find a seed.',jp:'それは種を見つけられます。'},{en:'It can carry the seed.',jp:'それはその種を運べます。'},{en:'It can also eat grass.',jp:'それは草を食べることもできます。'},{en:'An enemy can be / near the hamster.',jp:'敵がいることがあります / ハムスターの近くに'},{en:'The hamster can hide / in the grass.',jp:'ハムスターは隠れられます / 草の中に'},{en:'Though an enemy is near, / it can stay safe there.',jp:'敵が近くにいても / そこで安全でいることができます'},{en:'Daytime / and nighttime are very different / for the hamster.',jp:'昼間 / そして夜間はとても異なります / ハムスターにとって'},{en:'Its activity is different / in the daytime / and at nighttime.',jp:'その活動は異なります / 昼間に / そして夜間に'}
 ],90);
 window.V10_REFERENCE_SLASH_AUDIT={version:'2026-08-20',passagesAudited:90,total:168,lastCompleted:90,minimumRuleImageConfirmed:true};
})();