(()=>{
const D=window.V10_PASSAGES_G2_NH;
let m=D['Unit 0'];
m.sentences=['During spring vacation, I had a new experience.','I ate ramen with my friend.','We ate the same ramen.','The noodle was very good.','Actually, it was instant ramen.','I did not know that at first.','Now, I know about instant ramen.','I like ramen very much.','My friend and I like ramen.','By the way, we want to eat ramen again.','The experience was interesting.','Spring vacation was fun.'];
m.fullTranslation='「春休みに、私は新しい経験をしました。友達とラーメンを食べました。私たちは同じラーメンを食べました。めんはとてもおいしかったです。実は、それは即席ラーメンでした。私は最初そのことを知りませんでした。今は即席ラーメンについて知っています。私はラーメンがとても好きです。友達と私の両方がラーメンを好きです。ところで、私たちはまたラーメンを食べたいです。その経験はおもしろかったです。春休みは楽しかったです。」';
m.slashRows=[{en:'During spring vacation, / I had / a new experience.',jp:'春休みに / 私はしました / 新しい経験を'},{en:'I ate / ramen / with my friend.',jp:'私は食べました / ラーメンを / 友達と'},{en:'We ate / the same ramen.',jp:'私たちは食べました / 同じラーメンを'},{en:'The noodle was / very good.',jp:'そのめんは〜でした / とてもおいしい'},{en:'Actually, / it was / instant ramen.',jp:'実は / それは〜でした / 即席ラーメン'},{en:'I did not know / that / at first.',jp:'私は知りませんでした / そのことを / 最初は'},{en:'Now, / I know / about instant ramen.',jp:'今は / 私は知っています / 即席ラーメンについて'},{en:'I like / ramen / very much.',jp:'私は好きです / ラーメンが / とても'},{en:'My friend and I / like / ramen.',jp:'友達と私は / 好きです / ラーメンが'},{en:'By the way, / we want to eat / ramen again.',jp:'ところで / 私たちは食べたいです / ラーメンをまた'},{en:'The experience was / interesting.',jp:'その経験は〜でした / おもしろい'},{en:'Spring vacation was / fun.',jp:'春休みは〜でした / 楽しい'}];
m.auditNote+=' 人手語形監査でlikes / told / talkedを削除し、I/we＋原形と中1既習表層形だけへ修正。';

m=D['Unit 1-2'];
m.sentences[11]='“You’ll have a good evening.”';
m.slashRows[11]={en:'“You’ll have / a good evening.”',jp:'「あなたは過ごすでしょう / よい夜を」'};
m.fullTranslation='「私たちの便は午後に到着するでしょう。私はまず友達に会います。私たちはレストランへ行くでしょう。私はそこでシーフードを食べます。友達はシーフードを食べません。私たちは違う食べ物を食べます。私は予約をします。そのレストランは空港から遠くありません。私は夕食を楽しみにしています。友達もわくわくしています。私は『夕食後に電話するよ』と言います。『よい夜になるよ。』」';
m.auditNote+=' 人手語形監査で未登録の三単現saysを削除し、正本明示のyou’llを直接発話で使用。';

m=D['Unit 1-3'];
m.sentences=['Yesterday, we went to a shop.','I found a small card there.','The card had two languages.','One language was English.','The other language was Chinese.','We can communicate with the shop staff.','For example, I can use a short English question.','My friend can use a different word.','The card was one dollar.','It was about one meter from a large sign.','The sign was one meter tall.','We did not know how much the sign can weigh.','We found a good way to communicate.','Shopping was an interesting experience.'];
m.fullTranslation='「昨日、私たちは店へ行きました。私はそこで小さなカードを見つけました。そのカードには2つの言語がありました。1つは英語でした。もう1つは中国語でした。私たちは店員と意思を伝え合うことができます。例えば、私は短い英語の質問を使うことができます。友達は違う単語を使うことができます。そのカードは1ドルでした。それは大きな看板から約1メートルのところにありました。その看板は高さ1メートルでした。私たちはその看板の重さがどのくらいになり得るか知りませんでした。私たちは意思を伝え合うよい方法を見つけました。買い物はおもしろい経験でした。」';
m.slashRows=[{en:'Yesterday, / we went / to a shop.',jp:'昨日 / 私たちは行きました / 店へ'},{en:'I found / a small card / there.',jp:'私は見つけました / 小さなカードを / そこで'},{en:'The card had / two languages.',jp:'そのカードにはありました / 2つの言語が'},{en:'One language was / English.',jp:'1つの言語は〜でした / 英語'},{en:'The other language was / Chinese.',jp:'もう1つの言語は〜でした / 中国語'},{en:'We can communicate / with the shop staff.',jp:'私たちは意思を伝え合うことができます / 店員と'},{en:'For example, / I can use / a short English question.',jp:'例えば / 私は使うことができます / 短い英語の質問を'},{en:'My friend can use / a different word.',jp:'友達は使うことができます / 違う単語を'},{en:'The card was / one dollar.',jp:'そのカードは〜でした / 1ドル'},{en:'It was / about one meter / from a large sign.',jp:'それはありました / 約1メートル / 大きな看板から'},{en:'The sign was / one meter tall.',jp:'その看板は〜でした / 高さ1メートル'},{en:'We did not know / how much / the sign can weigh.',jp:'私たちは知りませんでした / どのくらいか / 看板の重さがあり得るか'},{en:'We found / a good way / to communicate.',jp:'私たちは見つけました / よい方法を / 意思を伝え合うための'},{en:'Shopping was / an interesting experience.',jp:'買い物は〜でした / おもしろい経験'}];
m.questions[3]={prompt:'4. 看板はどのくらいの高さでしたか。本文から英語で答えなさい。',answer:'one meter tall',evidence:'The sign was one meter tall.',evidenceJp:'その看板は高さ1メートルでした。',reason:'one meter tall が高さです。'};
m.auditNote+=' 人手語形監査でtried / usedと自動複数形metersを削除し、can＋原形と正本明示のfind-found / meter / ~tall / weighだけへ修正。';

m=D['Unit 1-4'];
m.sentences=['We are in a special area in Singapore.','We see a large wall there.','A painting is on the wall.','The painting is about a culture from India.','I am surprised by the painting.','My friend is surprised, too.','We talk about the area.','We also see a mosque near the wall.','The mosque is very beautiful.','We learn about a different culture.','The area is quiet in the morning.','We take a picture of the wall.','I want to visit the area again.','The trip is a new experience.'];
m.fullTranslation='「私たちはシンガポールの特別な地域にいます。そこに大きな壁が見えます。その壁に絵があります。その絵はインドの文化についてのものです。私はその絵に驚いています。友達も驚いています。私たちはその地域について話します。壁の近くにモスクも見えます。そのモスクはとても美しいです。私たちは異なる文化について学びます。その地域は朝は静かです。私たちは壁の写真を撮ります。私はまたその地域を訪れたいです。その旅行は新しい経験です。」';
m.slashRows=[{en:'We are / in a special area / in Singapore.',jp:'私たちはいます / 特別な地域に / シンガポールの'},{en:'We see / a large wall / there.',jp:'私たちは見ます / 大きな壁を / そこで'},{en:'A painting is / on the wall.',jp:'1枚の絵があります / 壁に'},{en:'The painting is / about a culture / from India.',jp:'その絵は〜です / 文化についての / インドの'},{en:'I am / surprised / by the painting.',jp:'私は〜です / 驚いて / その絵に'},{en:'My friend is / surprised, too.',jp:'友達も〜です / 驚いて'},{en:'We talk about / the area.',jp:'私たちは話します / その地域について'},{en:'We also see / a mosque / near the wall.',jp:'私たちはまた見ます / モスクを / 壁の近くに'},{en:'The mosque is / very beautiful.',jp:'そのモスクは〜です / とても美しい'},{en:'We learn about / a different culture.',jp:'私たちは学びます / 異なる文化について'},{en:'The area is / quiet / in the morning.',jp:'その地域は〜です / 静か / 朝に'},{en:'We take / a picture / of the wall.',jp:'私たちは撮ります / 写真を / 壁の'},{en:'I want to visit / the area / again.',jp:'私は訪れたいです / その地域を / また'},{en:'The trip is / a new experience.',jp:'その旅行は〜です / 新しい経験'}];
m.questions=[{prompt:'1. 今どこにいますか。本文から英語で答えなさい。',answer:'a special area in Singapore',evidence:'We are in a special area in Singapore.',evidenceJp:'私たちはシンガポールの特別な地域にいます。',reason:'in の後ろの a special area in Singapore が場所です。'},{prompt:'2. 壁には何がありますか。本文から英語で答えなさい。',answer:'a painting',evidence:'A painting is on the wall.',evidenceJp:'その壁に絵があります。',reason:'主語 A painting が壁にあるものです。'},{prompt:'3. その絵はどこの文化についてのものですか。本文から英語で答えなさい。',answer:'India',evidence:'The painting is about a culture from India.',evidenceJp:'その絵はインドの文化についてのものです。',reason:'from の後ろが India です。'},{prompt:'4. 話し手は絵を見てどう感じていますか。本文から英語で1語抜き出しなさい。',answer:'surprised',evidence:'I am surprised by the painting.',evidenceJp:'私はその絵に驚いています。',reason:'surprised が気持ちです。'},{prompt:'5. 壁の近くには何がありますか。本文から英語で答えなさい。',answer:'a mosque',evidence:'We also see a mosque near the wall.',evidenceJp:'壁の近くにモスクも見えます。',reason:'see の目的語が a mosque です。'}];
m.auditNote+=' 語形再監査でvisited / showed / learnedを削除。gaveはv7では後続Let’s Read 1初出と確認したため使用せず、Unit1時点で確実な原形中心へ修正。';
})();