window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 3-1']={
id:'V10-NH-G3-U3-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 3-1',level:'HOP',title:'An Animal in Danger',
sentences:['An endangered animal can be in danger of extinction.','Extinction is a serious problem.','Human activity can make a change.','That change can be trouble for an animal.','This is a challenge for us.','An endangered animal may need help.','The animal must survive.','We must help it, or it may not survive.','Human activity is one part of the problem.','We study the change carefully.','We think about how to help the animal.','I want to learn more about endangered animals.'],
fullTranslation:'「絶滅の危機にある動物は、絶滅の危険にさらされていることがあります。絶滅は深刻な問題です。人間の活動は変化を生むことがあります。その変化は動物にとって困難になることがあります。これは私たちにとって難問です。絶滅の危機にある動物には助けが必要なことがあります。その動物は生き残らなければなりません。私たちはそれを助けなければなりません。そうしなければ、生き残れないかもしれません。人間の活動は問題の一部です。私たちはその変化を注意深く調べます。動物をどのように助けるか考えます。私は絶滅の危機にある動物についてもっと学びたいです。」',
slashRows:[{en:'An endangered animal / can be in danger of / extinction.',jp:'絶滅の危機にある動物は / 危険にさらされることがあります / 絶滅の'},{en:'Extinction is / a serious problem.',jp:'絶滅は〜です / 深刻な問題'},{en:'Human activity / can make / a change.',jp:'人間の活動は / 生むことがあります / 変化を'},{en:'That change / can be / trouble / for an animal.',jp:'その変化は / 〜になることがあります / 困難に / 動物にとって'},{en:'This is / a challenge / for us.',jp:'これは〜です / 難問 / 私たちにとって'},{en:'An endangered animal / may need / help.',jp:'絶滅の危機にある動物は / 必要かもしれません / 助けが'},{en:'The animal / must survive.',jp:'その動物は / 生き残らなければなりません'},{en:'We must help / it, / or / it may not survive.',jp:'私たちは助けなければなりません / それを / そうしなければ / 生き残れないかもしれません'},{en:'Human activity is / one part / of the problem.',jp:'人間の活動は〜です / 一部 / 問題の'},{en:'We study / the change / carefully.',jp:'私たちは調べます / その変化を / 注意深く'},{en:'We think about / how to help / the animal.',jp:'私たちは考えます / どのように助けるか / その動物を'},{en:'I want to learn / more / about endangered animals.',jp:'私は学びたいです / もっと / 絶滅の危機にある動物について'}],
questions:[{prompt:'1. 絶滅の危機にある動物は何の危険にさらされることがありますか。本文から英語で答えなさい。',answer:'extinction',evidence:'An endangered animal can be in danger of extinction.',evidenceJp:'絶滅の危機にある動物は絶滅の危険にさらされていることがあります。',reason:'be in danger of の後ろが extinction です。'},{prompt:'2. 人間の活動は何を生むことがありますか。本文から英語で答えなさい。',answer:'a change',evidence:'Human activity can make a change.',evidenceJp:'人間の活動は変化を生むことがあります。',reason:'make の目的語が a change です。'},{prompt:'3. これは私たちにとって何ですか。本文から英語で答えなさい。',answer:'a challenge',evidence:'This is a challenge for us.',evidenceJp:'これは私たちにとって難問です。',reason:'be動詞の後ろが a challenge です。'},{prompt:'4. 動物は何をしなければなりませんか。本文から英語で1語抜き出しなさい。',answer:'survive',evidence:'The animal must survive.',evidenceJp:'その動物は生き残らなければなりません。',reason:'must の後ろの動詞が survive です。'},{prompt:'5. 何が問題の一部ですか。本文から英語で答えなさい。',answer:'human activity',evidence:'Human activity is one part of the problem.',evidenceJp:'人間の活動は問題の一部です。',reason:'主語が Human activity です。'}],
allowedWords:[['trouble / change / human / challenge / be in danger of ~ / endangered / survive / or / extinction','Unit 3 Part1: v7 canonical Sheet IDs 1756-1764'],['animal / serious / problem / activity / make / may / need / help / must / part / study / carefully / think about / how to / want to / learn / more','Unit0-2/G1-G2 cumulative']],
auditNote:'最新v7正本Unit3 Part1（Sheet ID1756〜1764）を直接照合。trouble / change / human / challenge / be in danger of / endangered / survive / or / extinctionを絶滅危惧動物の導入文に統合。Part2のwant A to B / article / ask A to B / hear of等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 3-2']={
id:'V10-NH-G3-U3-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 3-2',level:'HOP',title:'An Article about an Endangered Animal',
sentences:['I read an article about an endangered animal.','I want my friend to read the article.','I ask my friend to look at a list.','The list is in the article.','I have heard of this animal.','My friend has not heard of it.','I tell my friend to read the article.','We ask our class to read the list.','I want our class to know about the problem.','Have you heard of this animal?','The article is easy to understand.','We talk about the animal after class.'],
fullTranslation:'「私は絶滅の危機にある動物についての記事を読みます。私は友達にその記事を読んでほしいです。友達にリストを見るように頼みます。そのリストは記事の中にあります。私はこの動物について聞いたことがあります。友達はそれについて聞いたことがありません。私は友達にその記事を読むように言います。私たちはクラスのみんなにそのリストを読むように頼みます。私はクラスのみんなにその問題について知ってほしいです。あなたはこの動物について聞いたことがありますか。その記事は理解しやすいです。私たちは授業後にその動物について話します。」',
slashRows:[{en:'I read / an article / about an endangered animal.',jp:'私は読みます / 記事を / 絶滅の危機にある動物についての'},{en:'I want / my friend / to read the article.',jp:'私は望みます / 友達に / その記事を読んでほしいと'},{en:'I ask / my friend / to look at a list.',jp:'私は頼みます / 友達に / リストを見るように'},{en:'The list is / in the article.',jp:'そのリストはあります / 記事の中に'},{en:'I have heard of / this animal.',jp:'私は聞いたことがあります / この動物について'},{en:'My friend has not heard of / it.',jp:'私の友達は聞いたことがありません / それについて'},{en:'I tell / my friend / to read the article.',jp:'私は言います / 友達に / その記事を読むように'},{en:'We ask / our class / to read the list.',jp:'私たちは頼みます / クラスのみんなに / リストを読むように'},{en:'I want / our class / to know about the problem.',jp:'私は望みます / クラスのみんなに / その問題について知ってほしいと'},{en:'Have you heard of / this animal?',jp:'聞いたことがありますか / この動物について'},{en:'The article is / easy to understand.',jp:'その記事は〜です / 理解しやすい'},{en:'We talk about / the animal / after class.',jp:'私たちは話します / その動物について / 授業後に'}],
questions:[{prompt:'1. 何についての記事を読みますか。本文から英語で答えなさい。',answer:'an endangered animal',evidence:'I read an article about an endangered animal.',evidenceJp:'私は絶滅の危機にある動物についての記事を読みます。',reason:'about の後ろが an endangered animal です。'},{prompt:'2. 誰に記事を読んでほしいですか。本文から英語で答えなさい。',answer:'my friend',evidence:'I want my friend to read the article.',evidenceJp:'私は友達にその記事を読んでほしいです。',reason:'want A to B の A が my friend です。'},{prompt:'3. 友達に何を見るように頼みますか。本文から英語で答えなさい。',answer:'a list',evidence:'I ask my friend to look at a list.',evidenceJp:'友達にリストを見るように頼みます。',reason:'look at の目的語が a list です。'},{prompt:'4. 話し手はこの動物について聞いたことがありますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I have heard of this animal.',evidenceJp:'私はこの動物について聞いたことがあります。',reason:'have heard of とあるので Yes です。'},{prompt:'5. 友達はこの動物について聞いたことがありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'My friend has not heard of it.',evidenceJp:'友達はそれについて聞いたことがありません。',reason:'has not heard of とあるので No です。'}],
allowedWords:[['want A to B / article / ask A to B / hear of ~ / tell A to B / list / hear-heard-heard','Unit 3 Part2: v7 canonical Sheet IDs 1765-1771'],['read / endangered / animal / friend / look at / class / know / problem / easy to understand / talk about / after class','Unit0-3-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit3 Part2（Sheet ID1765〜1771）を直接照合。want A to B / article / ask A to B / hear of / tell A to B / list / heardを、絶滅危惧動物の記事を友達と読む場面に統合。Read and Thinkのlet / rapidly / research / ecosystem等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 3-3']={
id:'V10-NH-G3-U3-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 3-3',level:'HOP',title:'Research and Action for Animals',
sentences:['We read research about an animal problem.','The problem can increase rapidly.','As a result, an animal can be in danger.','A traffic accident can shock people.','Another problem is a chemical spill.','Research can relate human activity to animal trouble.','We categorize each problem.','Then we decide to take action.','This action can help an animal.','We let a student read the research.','The student can see how each problem is different.','We want to end the problem.'],
fullTranslation:'「私たちは動物の問題についての研究を読みます。その問題は急速に増えることがあります。その結果、動物が危険にさらされることがあります。交通事故は人々に衝撃を与えることがあります。別の問題は化学物質の流出です。研究は人間の活動と動物の困難を関係づけることができます。私たちはそれぞれの問題を分類します。それから行動を起こすことを決めます。この行動は動物を助けることができます。私たちは生徒にその研究を読ませます。その生徒はそれぞれの問題がどのように違うかを見ることができます。私たちはその問題を終わらせたいです。」',
slashRows:[{en:'We read / research / about an animal problem.',jp:'私たちは読みます / 研究を / 動物の問題についての'},{en:'The problem / can increase / rapidly.',jp:'その問題は / 増えることがあります / 急速に'},{en:'As a result, / an animal / can be in danger.',jp:'その結果 / 動物は / 危険にさらされることがあります'},{en:'A traffic accident / can shock / people.',jp:'交通事故は / 衝撃を与えることがあります / 人々に'},{en:'Another problem is / a chemical spill.',jp:'別の問題は〜です / 化学物質の流出'},{en:'Research can relate / human activity / to animal trouble.',jp:'研究は関係づけることができます / 人間の活動を / 動物の困難に'},{en:'We categorize / each problem.',jp:'私たちは分類します / それぞれの問題を'},{en:'Then / we decide to take / action.',jp:'それから / 私たちは起こすことを決めます / 行動を'},{en:'This action / can help / an animal.',jp:'この行動は / 助けることができます / 動物を'},{en:'We let / a student / read the research.',jp:'私たちは〜させます / 生徒に / その研究を読ませ'},{en:'The student can see / how each problem is different.',jp:'その生徒は見ることができます / それぞれの問題がどう違うか'},{en:'We want to end / the problem.',jp:'私たちは終わらせたいです / その問題を'}],
questions:[{prompt:'1. 問題はどのように増えることがありますか。本文から英語で1語抜き出しなさい。',answer:'rapidly',evidence:'The problem can increase rapidly.',evidenceJp:'その問題は急速に増えることがあります。',reason:'increase の仕方を表す語が rapidly です。'},{prompt:'2. 何が人々に衝撃を与えることがありますか。本文から英語で答えなさい。',answer:'a traffic accident',evidence:'A traffic accident can shock people.',evidenceJp:'交通事故は人々に衝撃を与えることがあります。',reason:'can shock の主語が A traffic accident です。'},{prompt:'3. 別の問題は何ですか。本文から英語で答えなさい。',answer:'a chemical spill',evidence:'Another problem is a chemical spill.',evidenceJp:'別の問題は化学物質の流出です。',reason:'be動詞の後ろが a chemical spill です。'},{prompt:'4. 私たちはそれぞれの問題をどうしますか。本文から英語で1語抜き出しなさい。',answer:'categorize',evidence:'We categorize each problem.',evidenceJp:'私たちはそれぞれの問題を分類します。',reason:'動詞が categorize です。'},{prompt:'5. 何を起こすことを決めますか。本文から英語で答えなさい。',answer:'action',evidence:'Then we decide to take action.',evidenceJp:'それから行動を起こすことを決めます。',reason:'take の目的語が action です。'}],
allowedWords:[['let / rapidly / as a result / research / decide to ~ / action / shock / relate / increase / categorize / end / traffic accident / spill','Unit 3 Read and Think1,2 shared pool first half: v7 canonical Sheet IDs 1772-1784'],['animal / problem / be in danger / people / another / chemical / human / activity / trouble / each / then / take / help / student / read / see / how / different / want to','Unit0-3-2 cumulative']],
auditNote:'最新v7正本Unit3 Read and Think1,2共通プール（Sheet ID1772〜1796）の前半ID1772〜1784をUnit3-3へ割り当て。let / rapidly / as a result / research / decide to / action / shock / relate / increase / categorize / end / traffic accident / spillを原因分析と行動の説明に統合。後半のecosystem / population / oil / hunting / critically等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 3-4']={
id:'V10-NH-G3-U3-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 3-4',level:'HOP',title:'The Sea Otter and Its Ecosystem',
sentences:['The sea otter is a native animal.','At the beginning of a century, a population can be small.','Hunting can make the population decrease.','Oil in the sea can be trouble for an ecosystem.','An oil spill can make the problem bigger.','A citizen can learn about the ecosystem.','Research can show a change in the population.','Some research can categorize an animal as critically endangered.','People can help the sea otter live safely.','A native animal is an important part of an ecosystem.','We should think about hunting and oil.','I want the sea otter to survive.'],
fullTranslation:'「ラッコは固有の動物です。ある世紀の初めには、個体数が少ないことがあります。狩りは個体数を減少させることがあります。海の石油は生態系にとって困難になることがあります。石油の流出は問題をより大きくすることがあります。市民は生態系について学ぶことができます。研究は個体数の変化を示すことができます。研究によって、動物を『絶滅の危機が非常に高い』と分類できることがあります。人々はラッコが安全に生きるのを助けることができます。固有の動物は生態系の大切な一部です。私たちは狩りと石油について考えるべきです。私はラッコに生き残ってほしいです。」',
slashRows:[{en:'The sea otter is / a native animal.',jp:'ラッコは〜です / 固有の動物'},{en:'At the beginning / of a century, / a population can be / small.',jp:'初めには / ある世紀の / 個体数が〜のことがあります / 少ない'},{en:'Hunting can make / the population / decrease.',jp:'狩りは〜させることがあります / 個体数を / 減少させ'},{en:'Oil in the sea / can be / trouble / for an ecosystem.',jp:'海の石油は / 〜になることがあります / 困難に / 生態系にとって'},{en:'An oil spill / can make / the problem / bigger.',jp:'石油の流出は / 〜にすることがあります / 問題を / より大きく'},{en:'A citizen / can learn about / the ecosystem.',jp:'市民は / 学ぶことができます / 生態系について'},{en:'Research can show / a change / in the population.',jp:'研究は示すことができます / 変化を / 個体数の'},{en:'Some research / can categorize / an animal / as critically endangered.',jp:'研究によって / 分類できます / 動物を / 絶滅の危機が非常に高いものとして'},{en:'People can help / the sea otter / live safely.',jp:'人々は助けることができます / ラッコが / 安全に生きるのを'},{en:'A native animal is / an important part / of an ecosystem.',jp:'固有の動物は〜です / 大切な一部 / 生態系の'},{en:'We should think about / hunting and oil.',jp:'私たちは考えるべきです / 狩りと石油について'},{en:'I want / the sea otter / to survive.',jp:'私は望みます / ラッコに / 生き残ってほしいと'}],
questions:[{prompt:'1. ラッコはどのような動物ですか。本文から英語で1語抜き出しなさい。',answer:'native',evidence:'The sea otter is a native animal.',evidenceJp:'ラッコは固有の動物です。',reason:'animal を説明する語が native です。'},{prompt:'2. 狩りは個体数をどうすることがありますか。本文から英語で1語抜き出しなさい。',answer:'decrease',evidence:'Hunting can make the population decrease.',evidenceJp:'狩りは個体数を減少させることがあります。',reason:'make A B の B が decrease です。'},{prompt:'3. 何が生態系にとって困難になることがありますか。本文から英語で答えなさい。',answer:'oil in the sea',evidence:'Oil in the sea can be trouble for an ecosystem.',evidenceJp:'海の石油は生態系にとって困難になることがあります。',reason:'主語が Oil in the sea です。'},{prompt:'4. 誰が生態系について学ぶことができますか。本文から英語で答えなさい。',answer:'a citizen',evidence:'A citizen can learn about the ecosystem.',evidenceJp:'市民は生態系について学ぶことができます。',reason:'can learn の主語が A citizen です。'},{prompt:'5. 人々はラッコがどのように生きるのを助けることができますか。本文から英語で1語抜き出しなさい。',answer:'safely',evidence:'People can help the sea otter live safely.',evidenceJp:'人々はラッコが安全に生きるのを助けることができます。',reason:'live の仕方を表す語が safely です。'}],
allowedWords:[['ecosystem / population / decrease / oil / citizen / hunting / small / century / native / beginning / critically / safely','Unit 3 Read and Think1,2 shared pool second half: v7 canonical Sheet IDs 1785-1796'],['sea otter','Unit3 textbook-body canonical Sheet ID1797'],['animal / at / can / make A B / spill / problem / bigger / learn about / research / show / change / categorize / endangered / people / help / live / important / part / should / think about / want A to B / survive','Unit0-3-3 cumulative']],
auditNote:'最新v7正本Unit3 Read and Think1,2共通プール後半（Sheet ID1785〜1796）と教科書本文語sea otter（Sheet ID1797）を直接照合。ecosystem / population / decrease / oil / citizen / hunting / small / century / native / beginning / critically / safelyをラッコと生態系の説明に統合。Unit4のstore / disaster / shelter / emergency等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
