window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 9-1'] = {
 id:'V10-NH-G1-U9-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 9-1',level:'HOP',title:'During Vacation',
 sentences:['Do you like snowboarding?','Yes, I do.','Do you like ice hockey?','Yes, I do.','During vacation, I went to a mountain.','I met my friend there.','We went snowboarding.','Really?','Yes.','I went back home.','At home, I saw my family.','Great!'],
 fullTranslation:'「スノーボードは好きですか。」「はい、好きです。」「アイスホッケーは好きですか。」「はい、好きです。」「休みの間に山へ行きました。」「そこで友達に会いました。」「私たちはスノーボードをしに行きました。」「本当？」「うん。」「家へ戻りました。」「家で家族に会いました。」「いいね！」',
 slashRows:[{en:'Do you like / snowboarding?',jp:'あなたは好きですか / スノーボードが'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'Do you like / ice hockey?',jp:'あなたは好きですか / アイスホッケーが'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'During vacation, / I went / to a mountain.',jp:'休みの間に / 私は行きました / 山へ'},{en:'I met / my friend / there.',jp:'私は会いました / 友達に / そこで'},{en:'We went / snowboarding.',jp:'私たちは行きました / スノーボードをしに'},{en:'Really?',jp:'本当？'},{en:'Yes.',jp:'うん。'},{en:'I went back / home.',jp:'私は戻りました / 家へ'},{en:'At home, / I saw / my family.',jp:'家で / 私は会いました / 家族に'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. 話し手はスノーボードが好きですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Do you like snowboarding? / Yes, I do.',evidenceJp:'スノーボードは好きですか。／はい、好きです。',reason:'snowboarding が好きかという質問に Yes, I do. と答えています。'},{prompt:'2. 話し手は休みの間にどこへ行きましたか。本文から英語で答えなさい。',answer:'a mountain',evidence:'During vacation, I went to a mountain.',evidenceJp:'休みの間に山へ行きました。',reason:'went to の後ろの a mountain が行った場所です。'},{prompt:'3. 話し手はそこで誰に会いましたか。本文から英語で答えなさい。',answer:'my friend',evidence:'I met my friend there.',evidenceJp:'そこで友達に会いました。',reason:'met の目的語 my friend が会った相手です。'},{prompt:'4. 話し手と友達は何をしましたか。本文から英語で答えなさい。',answer:'went snowboarding',evidence:'We went snowboarding.',evidenceJp:'私たちはスノーボードをしに行きました。',reason:'went snowboarding が2人のしたことを表しています。'},{prompt:'5. 話し手は家で誰に会いましたか。本文から英語で答えなさい。',answer:'my family',evidence:'At home, I saw my family.',evidenceJp:'家で家族に会いました。',reason:'saw の目的語 my family が家で会った相手です。'}],
 allowedWords:[['snowboarding','Unit 9-1'],['ice hockey','Unit 9-1'],['during','Unit 9-1'],['vacation','Unit 9-1'],['mountain','Unit 9-1'],['met','Unit 9-1 explicit past of meet'],['went','Unit 9-1 explicit past of go'],['saw','Unit 9-1 explicit past of see'],['back','Unit 9-1'],['at home','Unit 9-1 phrase'],['friend','Unit 1-2 cumulative'],['there','Unit 5-2 cumulative'],['family','Unit 3-1 cumulative'],['really / great','cumulative'],['do / you / like / yes / I / to / a / my / we / home','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 9-1をid2475〜2488まで照合し、id2489からUnit 9-2へ切り替わることを確認。snowboarding / Christmas Day / ice hockey / stay / relax / back / during / vacation / mountain / met / went / saw / go back / at home が登録されている。met / went / saw は過去形そのものが正本登録されているため使用。stayed / relaxedのような未登録の規則過去形は生成しない。went back は正本登録済みwentとbackをそのまま組み合わせており、新しい活用形は作っていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 9-2'] = {
 id:'V10-NH-G1-U9-2-001',textbook:'ニューホライズン',grade:'1',section:'Unit 9-2',level:'HOP',title:'A New Year Card',
 sentences:['This is a special New Year card.','Did you write this card?','Yes, I did.','Did you write it for your friend?','No, I didn’t.','I wrote it for my grandparent.','I ate a rice cake, too.','Is the rice cake traditional?','Yes, it is.','Really?','Yes.','Good for you!','Thank you.'],
 fullTranslation:'「これは特別な新年のカードです。」「このカードを書きましたか。」「はい、書きました。」「友達のために書いたのですか。」「いいえ、違います。」「祖父母のために書きました。」「もちも食べました。」「そのもちは伝統的なものですか。」「はい、そうです。」「本当？」「うん。」「よくやったね！」「ありがとう。」',
 slashRows:[{en:'This is / a special New Year card.',jp:'これは〜です / 特別な新年のカード'},{en:'Did you write / this card?',jp:'あなたは書きましたか / このカードを'},{en:'Yes, / I did.',jp:'はい / 書きました'},{en:'Did you write / it / for your friend?',jp:'あなたは書きましたか / それを / あなたの友達のために'},{en:'No, / I didn’t.',jp:'いいえ / 書きませんでした'},{en:'I wrote / it / for my grandparent.',jp:'私は書きました / それを / 私の祖父母のために'},{en:'I ate / a rice cake, too.',jp:'私は食べました / もちも'},{en:'Is the rice cake / traditional?',jp:'そのもちは〜ですか / 伝統的なもの'},{en:'Yes, / it is.',jp:'はい / そうです'},{en:'Really?',jp:'本当？'},{en:'Yes.',jp:'うん。'},{en:'Good for you!',jp:'よくやったね！'},{en:'Thank you.',jp:'ありがとう。'}],
 questions:[{prompt:'1. 最初に示されているものは何ですか。本文から英語で答えなさい。',answer:'a special New Year card',evidence:'This is a special New Year card.',evidenceJp:'これは特別な新年のカードです。',reason:'最初の文でカードの種類まで含めて示されています。'},{prompt:'2. 話し手はそのカードを書きましたか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Did you write this card? / Yes, I did.',evidenceJp:'このカードを書きましたか。／はい、書きました。',reason:'Did you ...? の質問に Yes, I did. と答えています。'},{prompt:'3. カードは友達のために書いたものですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Did you write it for your friend? / No, I didn’t.',evidenceJp:'友達のために書きましたか。／いいえ、書きませんでした。',reason:'過去の疑問文に No, I didn’t. と答えています。'},{prompt:'4. 実際には誰のためにカードを書きましたか。本文から英語で答えなさい。',answer:'my grandparent',evidence:'I wrote it for my grandparent.',evidenceJp:'私は祖父母のためにそれを書きました。',reason:'for の後ろの my grandparent がカードの相手です。'},{prompt:'5. 話し手は何を食べましたか。本文から英語で答えなさい。',answer:'a rice cake',evidence:'I ate a rice cake, too.',evidenceJp:'私はもちも食べました。',reason:'ate の目的語 a rice cake が食べたものです。'}],
 allowedWords:[['New Year','Unit 9-2'],['grandparent','Unit 9-2'],['traditional','Unit 9-2'],['special','Unit 9-2'],['card','Unit 9-2'],['did','Unit 9-2 explicit past of do / past-question grammar'],['wrote','Unit 9-2 explicit past of write'],['ate','Unit 9-2 explicit past of eat'],['didn’t','Unit 9-2 explicit did not contraction'],['rice cake','Unit 9-2 phrase'],['Good for you!','Unit 9-2 phrase'],['write','Unit 5-1 cumulative'],['friend','Unit 1-2 cumulative'],['really / too / Thank you.','cumulative'],['this / is / a / you / yes / I / it / for / your / no / my / the','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 9-2をid2489〜2500まで照合し、id2501からUnit 9-3へ切り替わることを確認。New Year / grandparent / traditional / special / card / New Year’s Eve / did / wrote / ate / didn’t / rice cake / Good for you! が登録されている。did / wrote / ate / didn’t は正本に過去形・過去否定として明示されるため、この単元からDid you ...? / No, I didn’t.を解禁。New Year’s Eve は本文の流れに不要なので新出語消化のためだけには入れていない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 9-3'] = {
 id:'V10-NH-G1-U9-3-001',textbook:'ニューホライズン',grade:'1',section:'Unit 9-3',level:'HOP',title:'A Fortune Slip and a Charm',
 sentences:['Did you get a fortune slip?','Yes, I did.','I got a fortune slip.','Is it bad?','No, it is not.','I bought a charm, too.','Did you spend time with your grandparent?','Yes, I did.','I spent New Year’s Day with my grandparent.','Did you have a good time?','Yes, I did.','I had a good time.','Great!'],
 fullTranslation:'「おみくじを引きましたか。」「はい、引きました。」「おみくじを引きました。」「悪い内容ですか。」「いいえ、悪くありません。」「お守りも買いました。」「祖父母と時間を過ごしましたか。」「はい、過ごしました。」「元日は祖父母と過ごしました。」「楽しい時間を過ごしましたか。」「はい。」「楽しい時間を過ごしました。」「いいね！」',
 slashRows:[{en:'Did you get / a fortune slip?',jp:'あなたは手に入れましたか / おみくじを'},{en:'Yes, / I did.',jp:'はい / そうしました'},{en:'I got / a fortune slip.',jp:'私は手に入れました / おみくじを'},{en:'Is it / bad?',jp:'それは〜ですか / 悪い'},{en:'No, / it is not.',jp:'いいえ / 悪くありません'},{en:'I bought / a charm, too.',jp:'私は買いました / お守りも'},{en:'Did you spend / time / with your grandparent?',jp:'あなたは過ごしましたか / 時間を / 祖父母と'},{en:'Yes, / I did.',jp:'はい / 過ごしました'},{en:'I spent / New Year’s Day / with my grandparent.',jp:'私は過ごしました / 元日を / 祖父母と'},{en:'Did you have / a good time?',jp:'あなたは過ごしましたか / 楽しい時間を'},{en:'Yes, / I did.',jp:'はい / 過ごしました'},{en:'I had / a good time.',jp:'私は過ごしました / 楽しい時間を'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. 話し手は何を引きましたか。本文から英語で答えなさい。',answer:'a fortune slip',evidence:'I got a fortune slip.',evidenceJp:'私はおみくじを引きました。',reason:'got の目的語 a fortune slip が手に入れたものです。'},{prompt:'2. おみくじは悪い内容ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Is it bad? / No, it is not.',evidenceJp:'それは悪いですか。／いいえ、悪くありません。',reason:'bad かどうかの質問に No, it is not. と答えています。'},{prompt:'3. 話し手は何も買いましたか。本文から英語で答えなさい。',answer:'a charm',evidence:'I bought a charm, too.',evidenceJp:'私はお守りも買いました。',reason:'bought の目的語 a charm が買ったものです。'},{prompt:'4. 話し手は元日を誰と過ごしましたか。本文から英語で答えなさい。',answer:'my grandparent',evidence:'I spent New Year’s Day with my grandparent.',evidenceJp:'私は元日を祖父母と過ごしました。',reason:'with my grandparent がいっしょに過ごした相手です。'},{prompt:'5. 話し手は楽しい時間を過ごしましたか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Did you have a good time? / Yes, I did.',evidenceJp:'楽しい時間を過ごしましたか。／はい、過ごしました。',reason:'have a ... time を使った過去の質問に Yes, I did. と答えています。'}],
 allowedWords:[['fortune slip','Unit 9-3'],['charm','Unit 9-3'],['spend','Unit 9-3'],['New Year’s Day','Unit 9-3'],['bad','Unit 9-3'],['bought','Unit 9-3 explicit past of buy'],['got','Unit 9-3 explicit past of get'],['spent','Unit 9-3 explicit past of spend'],['had','Unit 9-3 explicit past of have'],['have a ... time','Unit 9-3 phrase'],['did','Unit 9-2 cumulative past-question grammar'],['grandparent','Unit 9-2 cumulative'],['get','Unit 8-3 cumulative'],['great / too','cumulative'],['you / a / yes / I / is / it / no / not / with / your / my / good / time','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 9-3をid2501〜2518まで照合し、id2519からReal Life English 5へ切り替わることを確認。wish / board game / fortune slip / charm / spend / wooden / future / New Year’s Day / tablet / bad / came / bought / said / got / spent / read / had / have a ... time が登録されている。本文ではbought / got / spent / hadだけを使用し、came / said / readは新出語消化のためだけには詰め込まない。過去形は正本に明示登録された形だけを使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};