window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 3-1']={
id:'V10-NH-G2-U3-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 3-1',level:'HOP',title:'Career Day at a Nursery School',
sentences:['Today is Career Day.','I want information about a career.','I chose a nursery school.','This is my own choice.','I go to the nursery school in the morning.','I play there.','I make a note about the work.','I get useful information.','The career is interesting to me.','How about an international career?','I think about my own career.','Career Day is a good experience.'],
fullTranslation:'「今日は職業体験日です。私は職業についての情報がほしいです。私は保育園を選びました。これは自分自身で選んだものです。朝、保育園へ行きます。そこで遊びます。仕事についてメモを作ります。役立つ情報を得ます。その職業は私にとって興味深いです。国際的な職業はどうでしょうか。私は自分自身の職業について考えます。職業体験日はよい経験です。」',
slashRows:[{en:'Today is / Career Day.',jp:'今日は〜です / 職業体験日'},{en:'I want / information / about a career.',jp:'私はほしいです / 情報が / 職業についての'},{en:'I chose / a nursery school.',jp:'私は選びました / 保育園を'},{en:'This is / my own choice.',jp:'これは〜です / 自分自身の選択'},{en:'I go / to the nursery school / in the morning.',jp:'私は行きます / 保育園へ / 朝に'},{en:'I play / there.',jp:'私は遊びます / そこで'},{en:'I make / a note / about the work.',jp:'私は作ります / メモを / 仕事についての'},{en:'I get / useful information.',jp:'私は得ます / 役立つ情報を'},{en:'The career is / interesting / to me.',jp:'その職業は〜です / 興味深い / 私にとって'},{en:'How about / an international career?',jp:'〜はどうですか / 国際的な職業'},{en:'I think about / my own career.',jp:'私は考えます / 自分自身の職業について'},{en:'Career Day is / a good experience.',jp:'職業体験日は〜です / よい経験'}],
questions:[{prompt:'1. 今日は何の日ですか。本文から英語で答えなさい。',answer:'Career Day',evidence:'Today is Career Day.',evidenceJp:'今日は職業体験日です。',reason:'Today is の後ろが Career Day です。'},{prompt:'2. 何を選びましたか。本文から英語で答えなさい。',answer:'a nursery school',evidence:'I chose a nursery school.',evidenceJp:'私は保育園を選びました。',reason:'chose の目的語が a nursery school です。'},{prompt:'3. そこで何をしますか。本文から英語で1語抜き出しなさい。',answer:'play',evidence:'I play there.',evidenceJp:'そこで遊びます。',reason:'play が行動です。'},{prompt:'4. 仕事について何を作りますか。本文から英語で答えなさい。',answer:'a note',evidence:'I make a note about the work.',evidenceJp:'仕事についてメモを作ります。',reason:'make の目的語が a note です。'},{prompt:'5. 最後に職業体験日をどのように評価していますか。本文から英語で答えなさい。',answer:'a good experience',evidence:'Career Day is a good experience.',evidenceJp:'職業体験日はよい経験です。',reason:'be動詞の後ろが評価です。'}],
allowedWords:[['information / career / own / Career Day / international / nursery school / play / choose-chose / park / How about ~? / tag / illustration / note / colorful / chopsticks','Unit 3-1,2 shared v7 canonical Sheet IDs 1054-1068'],['today / want / choice / morning / make / work / useful / interesting / think about / good / experience','G1/Unit0-2 cumulative']],
auditNote:'最新v7正本ではUnit3 Part1,2が共通語彙プール（Sheet ID1054〜1068）。Unit3-1はCareer Day / career / information / choose-chose / nursery school / own / play / note / internationalを職業体験の1場面にまとめた。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 3-2']={
id:'V10-NH-G2-U3-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 3-2',level:'HOP',title:'A Colorful Tag for Career Day',
sentences:['Today is Career Day.','I chose work at a shop.','I make a colorful tag.','I draw an illustration on the tag.','I write a short note on the tag.','The tag is for chopsticks.','I like my own illustration.','This work can be international.','I get information about this career.','How about this career?','I think it is interesting.','I want to learn more about the work.'],
fullTranslation:'「今日は職業体験日です。私は店での仕事を選びました。色彩豊かなタグを作ります。タグにイラストをかきます。タグに短いメモを書きます。そのタグははし用です。私は自分自身のイラストが好きです。この仕事は国際的なものにもなりえます。私はこの職業について情報を得ます。この職業はどうでしょうか。私はおもしろいと思います。その仕事についてもっと学びたいです。」',
slashRows:[{en:'Today is / Career Day.',jp:'今日は〜です / 職業体験日'},{en:'I chose / work / at a shop.',jp:'私は選びました / 仕事を / 店での'},{en:'I make / a colorful tag.',jp:'私は作ります / 色彩豊かなタグを'},{en:'I draw / an illustration / on the tag.',jp:'私はかきます / イラストを / タグに'},{en:'I write / a short note / on the tag.',jp:'私は書きます / 短いメモを / タグに'},{en:'The tag is / for chopsticks.',jp:'そのタグは〜です / はし用'},{en:'I like / my own illustration.',jp:'私は好きです / 自分自身のイラストが'},{en:'This work can be / international.',jp:'この仕事は〜になりえます / 国際的なもの'},{en:'I get / information / about this career.',jp:'私は得ます / 情報を / この職業についての'},{en:'How about / this career?',jp:'〜はどうですか / この職業'},{en:'I think / it is / interesting.',jp:'私は思います / それは〜だと / おもしろい'},{en:'I want to learn / more / about the work.',jp:'私は学びたいです / もっと / 仕事について'}],
questions:[{prompt:'1. どこでの仕事を選びましたか。本文から英語で答えなさい。',answer:'at a shop',evidence:'I chose work at a shop.',evidenceJp:'私は店での仕事を選びました。',reason:'at a shop が場所です。'},{prompt:'2. 何を作りますか。本文から英語で答えなさい。',answer:'a colorful tag',evidence:'I make a colorful tag.',evidenceJp:'色彩豊かなタグを作ります。',reason:'make の目的語が a colorful tag です。'},{prompt:'3. タグに何をかきますか。本文から英語で答えなさい。',answer:'an illustration',evidence:'I draw an illustration on the tag.',evidenceJp:'タグにイラストをかきます。',reason:'draw の目的語が an illustration です。'},{prompt:'4. タグは何のためのものですか。本文から英語で答えなさい。',answer:'chopsticks',evidence:'The tag is for chopsticks.',evidenceJp:'そのタグははし用です。',reason:'for の後ろが chopsticks です。'},{prompt:'5. 話し手はこの職業をどう思っていますか。本文から英語で1語抜き出しなさい。',answer:'interesting',evidence:'I think it is interesting.',evidenceJp:'私はおもしろいと思います。',reason:'interesting が評価です。'}],
allowedWords:[['information / career / own / Career Day / international / nursery school / play / choose-chose / park / How about ~? / tag / illustration / note / colorful / chopsticks','Unit 3-1,2 shared v7 canonical Sheet IDs 1054-1068'],['today / work / shop / make / draw / write / short / like / can / get / think / interesting / want to / learn / more','G1/Unit0-2 cumulative']],
auditNote:'Unit3-2も最新v7共通プール（1054〜1068）を使用し、Unit3-1とは別の「商品タグを作る職業体験」へ分離。tag / illustration / colorful / note / chopsticks / own / careerを中心にし、後続Read and Think語は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 3-3']={
id:'V10-NH-G2-U3-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 3-3',level:'HOP',title:'A Tiny Caterpillar in a Picture Book',
sentences:['Yesterday, our teacher taught us with a picture book.','We start the book with a tiny caterpillar.','The caterpillar is on a leaf.','We see the moon come up.','The light is important in the picture.','The caterpillar can come out of a small place.','We see a pear and a plum.','The picture is pretty.','A leaf can lie near the pear.','Yesterday, the book lay on my desk.','I like the tiny caterpillar.','The picture book is interesting.','We look at the book again.'],
fullTranslation:'「昨日、先生は絵本を使って私たちに教えました。私たちは小さなイモムシからその本を読み始めます。そのイモムシは葉の上にいます。私たちは月がのぼるのを見ます。絵の中では光が大切です。イモムシは小さな場所から出てくることができます。西洋ナシとプラムが見えます。その絵はきれいです。葉は西洋ナシの近くにあることができます。昨日、その本は私の机の上にありました。私はその小さなイモムシが好きです。その絵本はおもしろいです。私たちはもう一度その本を見ます。」',
slashRows:[{en:'Yesterday, / our teacher taught / us / with a picture book.',jp:'昨日 / 先生は教えました / 私たちに / 絵本を使って'},{en:'We start / the book / with a tiny caterpillar.',jp:'私たちは始めます / その本を / 小さなイモムシから'},{en:'The caterpillar is / on a leaf.',jp:'そのイモムシはいます / 葉の上に'},{en:'We see / the moon / come up.',jp:'私たちは見ます / 月が / のぼるのを'},{en:'The light is / important / in the picture.',jp:'光は〜です / 大切 / 絵の中で'},{en:'The caterpillar can come out of / a small place.',jp:'そのイモムシは出てくることができます / 小さな場所から'},{en:'We see / a pear and a plum.',jp:'私たちは見ます / 西洋ナシとプラムを'},{en:'The picture is / pretty.',jp:'その絵は〜です / きれい'},{en:'A leaf can lie / near the pear.',jp:'葉は位置することができます / 西洋ナシの近くに'},{en:'Yesterday, / the book lay / on my desk.',jp:'昨日 / その本はありました / 私の机の上に'},{en:'I like / the tiny caterpillar.',jp:'私は好きです / その小さなイモムシが'},{en:'The picture book is / interesting.',jp:'その絵本は〜です / おもしろい'},{en:'We look at / the book / again.',jp:'私たちは見ます / その本を / もう一度'}],
questions:[{prompt:'1. 先生は何を使って教えましたか。本文から英語で答えなさい。',answer:'a picture book',evidence:'Yesterday, our teacher taught us with a picture book.',evidenceJp:'昨日、先生は絵本を使って私たちに教えました。',reason:'with の後ろが a picture book です。'},{prompt:'2. イモムシはどこにいますか。本文から英語で答えなさい。',answer:'on a leaf',evidence:'The caterpillar is on a leaf.',evidenceJp:'そのイモムシは葉の上にいます。',reason:'on a leaf が場所です。'},{prompt:'3. 何がのぼるのを見ますか。本文から英語で答えなさい。',answer:'the moon',evidence:'We see the moon come up.',evidenceJp:'私たちは月がのぼるのを見ます。',reason:'see の目的語が the moon です。'},{prompt:'4. 絵の中で何が大切ですか。本文から英語で答えなさい。',answer:'The light',evidence:'The light is important in the picture.',evidenceJp:'絵の中では光が大切です。',reason:'主語 The light が大切なものです。'},{prompt:'5. 昨日、本はどこにありましたか。本文から英語で答えなさい。',answer:'on my desk',evidence:'Yesterday, the book lay on my desk.',evidenceJp:'昨日、その本は私の机の上にありました。',reason:'on my desk が場所です。'}],
allowedWords:[['taught / pear / start / moon / important / light / come out of ~ / leaf / come up / caterpillar / lie-lay / tiny / plum / pretty','Unit 3-3: v7 canonical Sheet IDs 1069-1082'],['picture book','Unit 3 textbook body: v7 canonical Sheet ID1101'],['yesterday / teacher / book / see / small / place / picture / near / desk / like / interesting / look at / again','G1/Unit0-3 cumulative']],
auditNote:'最新v7正本Unit3 Read and Think1（Sheet ID1069〜1082）を直接照合し、同Unit教科書本文のpicture bookを使用。taught / come up / come out of / lie-layなど正本明示形だけで絵本の1場面を構成。後続Read and Think2のstory等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 3-4']={
id:'V10-NH-G2-U3-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 3-4',level:'HOP',title:'Thank You for the Reading Lesson',
sentences:['Dear Ms. Brown,','Thank you for your lesson.','I understand the story now.','I learn how to read clearly.','I adjust my speed when a sentence is difficult.','I read the sentence again and again.','I can read loud and clearly.','This practice is necessary for me.','I am glad.','My friend and I clap after the lesson.','We smile.','From now on, I will practice every day.','Thank you for the story.','Sincerely yours,','Ken'],
fullTranslation:'「ブラウン先生へ。授業をありがとうございました。私は今、その話を理解しています。はっきり読む方法を学びます。文が難しいときは速さを調節します。その文を何度も読みます。大きな声ではっきり読むことができます。この練習は私に必要です。私はうれしいです。授業のあと、友達と私は拍手します。私たちはほほえみます。これからは毎日練習します。その話をありがとうございました。敬具。ケン」',
slashRows:[{en:'Dear Ms. Brown,',jp:'ブラウン先生へ'},{en:'Thank you for / your lesson.',jp:'〜をありがとう / あなたの授業'},{en:'I understand / the story / now.',jp:'私は理解しています / その話を / 今'},{en:'I learn / how to read / clearly.',jp:'私は学びます / 読む方法を / はっきりと'},{en:'I adjust / my speed / when a sentence is difficult.',jp:'私は調節します / 私の速さを / 文が難しいとき'},{en:'I read / the sentence / again and again.',jp:'私は読みます / その文を / 何度も何度も'},{en:'I can read / loud and clearly.',jp:'私は読むことができます / 大きな声ではっきりと'},{en:'This practice is / necessary / for me.',jp:'この練習は〜です / 必要 / 私に'},{en:'I am / glad.',jp:'私は〜です / うれしい'},{en:'My friend and I / clap / after the lesson.',jp:'友達と私は / 拍手します / 授業のあと'},{en:'We smile.',jp:'私たちはほほえみます'},{en:'From now on, / I will practice / every day.',jp:'これからは / 私は練習します / 毎日'},{en:'Thank you for / the story.',jp:'〜をありがとう / その話'},{en:'Sincerely yours,',jp:'敬具'},{en:'Ken',jp:'ケン'}],
questions:[{prompt:'1. 何を理解していますか。本文から英語で答えなさい。',answer:'the story',evidence:'I understand the story now.',evidenceJp:'私は今、その話を理解しています。',reason:'understand の目的語が the story です。'},{prompt:'2. 文が難しいとき、何を調節しますか。本文から英語で答えなさい。',answer:'my speed',evidence:'I adjust my speed when a sentence is difficult.',evidenceJp:'文が難しいときは速さを調節します。',reason:'adjust の目的語が my speed です。'},{prompt:'3. その文をどのように読みますか。本文から英語で答えなさい。',answer:'again and again',evidence:'I read the sentence again and again.',evidenceJp:'その文を何度も読みます。',reason:'again and again が読み方の繰り返しを表します。'},{prompt:'4. 話し手はどんな気持ちですか。本文から英語で1語抜き出しなさい。',answer:'glad',evidence:'I am glad.',evidenceJp:'私はうれしいです。',reason:'glad が気持ちです。'},{prompt:'5. これからどうすると書いていますか。本文から英語で答えなさい。',answer:'practice every day',evidence:'From now on, I will practice every day.',evidenceJp:'これからは毎日練習します。',reason:'will の後ろが practice every day です。'}],
allowedWords:[['understand / clap / learn / adjust / story / speed / necessary / sentence / glad / loud / difficult / clearly / Thank you for ~. / Sincerely(yours) / from now on / again and again / smile','Unit 3-4: v7 canonical Sheet IDs 1083-1099'],['Dear / Ms. / lesson / read / practice / friend / after / will / every day','G1/Unit0-3 cumulative']],
auditNote:'最新v7正本Unit3 Read and Think2（Sheet ID1083〜1099）を直接照合。understand / adjust / speed / sentence / clearly / again and again / glad / clap / smile / from now on / Thank you for / Sincerely yoursを、読み方を教わった後の手紙として自然に統合。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};