window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 2-1']={
id:'V10-NH-G2-U2-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 2-1',level:'HOP',title:'Ramen at a Local Restaurant',
sentences:['Today, we are at a local restaurant.','When I eat ramen, I like soy sauce.','I can order ramen here.','I can order it with soy sauce.','I do not need salt.','The flavor is strong.','I especially like this flavor.','Egg is my favorite topping.','My friend and I like corn as a topping.','We order ramen together.','Local food is interesting.','When we eat it, we talk about the flavor.'],
fullTranslation:'「今日、私たちは地元のレストランにいます。ラーメンを食べるとき、私はしょうゆが好きです。ここでラーメンを注文できます。しょうゆ入りで注文できます。塩は必要ありません。風味は強いです。私は特にこの風味が好きです。卵は私のお気に入りのトッピングです。友達と私はトッピングとしてコーンが好きです。私たちはいっしょにラーメンを注文します。地元の食べ物はおもしろいです。それを食べるとき、風味について話します。」',
slashRows:[{en:'Today, / we are / at a local restaurant.',jp:'今日 / 私たちはいます / 地元のレストランに'},{en:'When I eat ramen, / I like / soy sauce.',jp:'ラーメンを食べるとき / 私は好きです / しょうゆが'},{en:'I can order / ramen / here.',jp:'私は注文できます / ラーメンを / ここで'},{en:'I can order / it / with soy sauce.',jp:'私は注文できます / それを / しょうゆ入りで'},{en:'I do not need / salt.',jp:'私は必要としません / 塩を'},{en:'The flavor is / strong.',jp:'その風味は〜です / 強い'},{en:'I especially like / this flavor.',jp:'私は特に好きです / この風味が'},{en:'Egg is / my favorite topping.',jp:'卵は〜です / 私のお気に入りのトッピング'},{en:'My friend and I / like / corn as a topping.',jp:'友達と私は / 好きです / トッピングとしてコーンが'},{en:'We order / ramen / together.',jp:'私たちは注文します / ラーメンを / いっしょに'},{en:'Local food is / interesting.',jp:'地元の食べ物は〜です / おもしろい'},{en:'When we eat it, / we talk about / the flavor.',jp:'私たちがそれを食べるとき / 私たちは話します / 風味について'}],
questions:[{prompt:'1. ラーメンを食べるとき、何が好きですか。本文から英語で答えなさい。',answer:'soy sauce',evidence:'When I eat ramen, I like soy sauce.',evidenceJp:'ラーメンを食べるとき、私はしょうゆが好きです。',reason:'like の目的語が soy sauce です。'},{prompt:'2. 塩は必要ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I do not need salt.',evidenceJp:'塩は必要ありません。',reason:'do not need と否定されています。'},{prompt:'3. 風味はどのようですか。本文から英語で1語抜き出しなさい。',answer:'strong',evidence:'The flavor is strong.',evidenceJp:'風味は強いです。',reason:'strong が風味を説明しています。'},{prompt:'4. お気に入りのトッピングは何ですか。本文から英語で答えなさい。',answer:'Egg',evidence:'Egg is my favorite topping.',evidenceJp:'卵は私のお気に入りのトッピングです。',reason:'主語 Egg が好きなトッピングです。'},{prompt:'5. 2人はいっしょに何を注文しますか。本文から英語で答えなさい。',answer:'ramen',evidence:'We order ramen together.',evidenceJp:'私たちはいっしょにラーメンを注文します。',reason:'order の目的語が ramen です。'}],
allowedWords:[['when ~ / soy sauce / order / salt / various / flavor / ~and so on / so / topping / especially','Unit 2-1: v7 canonical Sheet IDs 1001-1010'],['ramen / restaurant / can / need / strong / egg / favorite / friend / corn / together / local food / interesting / talk about','G1/Unit0-1 cumulative']],
auditNote:'最新v7正本Unit2 Part1（Sheet ID1001〜1010）を直接照合。when / soy sauce / order / salt / flavor / topping / especiallyを地元ラーメンの1場面に統合。後続Partのadd / because / sauce等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 2-2']={
id:'V10-NH-G2-U2-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 2-2',level:'HOP',title:'A Short Speech about Local Food',
sentences:['At school, I give a short speech about local food.','If you visit my town, you can try ramen.','You can order it with soy sauce.','If you like butter, you can add butter.','You can add corn, too.','I would love to eat it sometime.','“I would love to try it, too.”','We can make a reservation before dinner.','If you are hungry, you can order ramen.','Seafood is good, too.','Local food has a special flavor.','The speech is short and easy.','I like this speech.'],
fullTranslation:'「学校で、私は地元の食べ物について短いスピーチをします。もし私の町を訪れたら、ラーメンを食べてみることができます。しょうゆ入りで注文してもよいです。もしバターが好きなら、バターを加えてもよいです。コーンも加えてよいです。私はいつかそれを食べてみたいです。『私も食べてみたいです。』夕食前に予約をすることができます。もしおなかがすいているなら、ラーメンを注文できます。シーフードもおいしいです。地元の食べ物には特別な風味があります。そのスピーチは短くて分かりやすいです。私はこのスピーチが好きです。」',
slashRows:[{en:'At school, / I give / a short speech / about local food.',jp:'学校で / 私はします / 短いスピーチを / 地元の食べ物について'},{en:'If you visit my town, / you can try / ramen.',jp:'もし私の町を訪れたら / あなたは試せます / ラーメンを'},{en:'You can order / it / with soy sauce.',jp:'あなたは注文してもよいです / それを / しょうゆ入りで'},{en:'If you like butter, / you can add / butter.',jp:'もしバターが好きなら / あなたは加えてもよいです / バターを'},{en:'You can add / corn, too.',jp:'あなたは加えてもよいです / コーンも'},{en:'I would love to eat / it / sometime.',jp:'私は食べてみたいです / それを / いつか'},{en:'“I would love to try / it, too.”',jp:'「私も試してみたいです / それを」'},{en:'We can make / a reservation / before dinner.',jp:'私たちはできます / 予約を / 夕食前に'},{en:'If you are hungry, / you can order / ramen.',jp:'もしおなかがすいているなら / あなたは注文できます / ラーメンを'},{en:'Seafood is / good, too.',jp:'シーフードも〜です / おいしい'},{en:'Local food has / a special flavor.',jp:'地元の食べ物にはあります / 特別な風味が'},{en:'The speech is / short and easy.',jp:'そのスピーチは〜です / 短くて分かりやすい'},{en:'I like / this speech.',jp:'私は好きです / このスピーチが'}],
questions:[{prompt:'1. 何についてスピーチをしますか。本文から英語で答えなさい。',answer:'local food',evidence:'At school, I give a short speech about local food.',evidenceJp:'学校で、私は地元の食べ物について短いスピーチをします。',reason:'about の後ろが local food です。'},{prompt:'2. バターが好きなら何を加えてもよいですか。本文から英語で答えなさい。',answer:'butter',evidence:'If you like butter, you can add butter.',evidenceJp:'もしバターが好きなら、バターを加えてもよいです。',reason:'add の目的語が butter です。'},{prompt:'3. 話し手はいつ食べてみたいですか。本文から英語で1語抜き出しなさい。',answer:'sometime',evidence:'I would love to eat it sometime.',evidenceJp:'私はいつかそれを食べてみたいです。',reason:'sometime が時を表します。'},{prompt:'4. いつ予約できますか。本文から英語で答えなさい。',answer:'before dinner',evidence:'We can make a reservation before dinner.',evidenceJp:'夕食前に予約をすることができます。',reason:'before dinner が時です。'},{prompt:'5. 地元の食べ物には何がありますか。本文から英語で答えなさい。',answer:'a special flavor',evidence:'Local food has a special flavor.',evidenceJp:'地元の食べ物には特別な風味があります。',reason:'has の目的語が a special flavor です。'}],
allowedWords:[['if ~ / can / speech / butter / sometime / would love to ~ / add','Unit 2-2: v7 canonical Sheet IDs 1011-1017'],['local food / visit / town / try / ramen / order / soy sauce / corn / reservation / dinner / hungry / seafood / good / special / flavor / short / easy / like','G1/Unit1/Unit2-1 cumulative']],
auditNote:'最新v7正本Unit2 Part2（Sheet ID1011〜1017）を直接照合。if / can（許可）/ speech / butter / sometime / would love to / addを短いスピーチに統合。後続Partのbecause / recommended等は使っていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 2-3']={
id:'V10-NH-G2-U2-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 2-3',level:'HOP',title:'A Recommended Local Soup',
sentences:['Today, I am interested in local food.','I go to a recommended restaurant early.','Why do you go early?','Because the soup is popular.','The soup is thick.','It is soy sauce-based.','This is one kind of local food.','I want to stay here for lunch.','I do not forget this flavor.','My friend is interested in the soup, too.','We eat early because the restaurant is popular.','The food is recommended.','We talk about local food.','This local food is interesting.'],
fullTranslation:'「今日、私は地元の食べ物に興味があります。私は早い時間におすすめのレストランへ行きます。『なぜ早く行くのですか。』『そのスープが人気だからです。』そのスープは濃いです。それはしょうゆをベースにしています。これは地元の食べ物の一種です。私は昼食までここにいたいです。私はこの風味を忘れません。友達もそのスープに興味があります。レストランが人気なので、私たちは早く食べます。その食べ物はおすすめです。私たちは地元の食べ物について話します。この地元の食べ物はおもしろいです。」',
slashRows:[{en:'Today, / I am interested in / local food.',jp:'今日 / 私は興味があります / 地元の食べ物に'},{en:'I go / to a recommended restaurant / early.',jp:'私は行きます / おすすめのレストランへ / 早く'},{en:'Why do you go / early?',jp:'なぜ行くのですか / 早く'},{en:'Because / the soup is / popular.',jp:'なぜなら / そのスープは〜だからです / 人気の'},{en:'The soup is / thick.',jp:'そのスープは〜です / 濃い'},{en:'It is / soy sauce-based.',jp:'それは〜です / しょうゆをベースにした'},{en:'This is / one kind of / local food.',jp:'これは〜です / 1種類の / 地元の食べ物'},{en:'I want to stay / here / for lunch.',jp:'私はいたいです / ここに / 昼食まで'},{en:'I do not forget / this flavor.',jp:'私は忘れません / この風味を'},{en:'My friend is interested in / the soup, too.',jp:'友達も興味があります / そのスープに'},{en:'We eat early / because / the restaurant is popular.',jp:'私たちは早く食べます / なぜなら / レストランが人気だから'},{en:'The food is / recommended.',jp:'その食べ物は〜です / おすすめの'},{en:'We talk about / local food.',jp:'私たちは話します / 地元の食べ物について'},{en:'This local food is / interesting.',jp:'この地元の食べ物は〜です / おもしろい'}],
questions:[{prompt:'1. 話し手は何に興味がありますか。本文から英語で答えなさい。',answer:'local food',evidence:'Today, I am interested in local food.',evidenceJp:'今日、私は地元の食べ物に興味があります。',reason:'be interested in の後ろが local food です。'},{prompt:'2. なぜ早く行きますか。本文から英語で答えなさい。',answer:'the soup is popular',evidence:'Because the soup is popular.',evidenceJp:'そのスープが人気だからです。',reason:'Because の後ろが理由です。'},{prompt:'3. スープはどのようですか。本文から英語で1語抜き出しなさい。',answer:'thick',evidence:'The soup is thick.',evidenceJp:'そのスープは濃いです。',reason:'thick がスープの状態です。'},{prompt:'4. スープは何をベースにしていますか。本文から英語で答えなさい。',answer:'soy sauce',evidence:'It is soy sauce-based.',evidenceJp:'それはしょうゆをベースにしています。',reason:'-based の前が soy sauce です。'},{prompt:'5. 話し手は何を忘れないと言っていますか。本文から英語で答えなさい。',answer:'this flavor',evidence:'I do not forget this flavor.',evidenceJp:'私はこの風味を忘れません。',reason:'forget の目的語が this flavor です。'}],
allowedWords:[['because ~ / stay / forget / thick / early / recommended / A kind(s) of ~ / ~based / be interested in ~','Unit 2-3: v7 canonical Sheet IDs 1018-1026'],['local food / restaurant / why / soup / popular / soy sauce / one / want to / lunch / flavor / friend / too / eat / talk about / interesting','G1/Unit1/Unit2 cumulative']],
auditNote:'最新v7正本Unit2 Read and Think1（Sheet ID1018〜1026）を直接照合。because / stay / forget / thick / early / recommended / kind of / -based / be interested inを1つのおすすめ料理説明に統合。Unit2-4語は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 2-4']={
id:'V10-NH-G2-U2-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 2-4',level:'HOP',title:'Food, Climate, and Creativity',
sentences:['Local food can change with the climate.','Food can reflect the climate.','Here is a new sauce.','A chef can create this sauce.','The chef is from a foreign country.','A variation can have a different flavor.','We name the sauce after the city.','Creativity is important for new food.','Food can change our lives.','This sauce is local.','Another sauce is foreign.','My friend and I come from Japan.','We are interested in food from a foreign country.','Here is another variation.'],
fullTranslation:'「地元の食べ物は気候によって変わることがあります。食べ物は気候を反映することがあります。ここに新しいソースがあります。シェフはこのソースを作り出すことができます。そのシェフは外国の出身です。1つの変化形は違う風味を持つことがあります。私たちはその街にちなんでソースに名前を付けます。新しい食べ物には創造力が大切です。食べ物は私たちの生活を変えることがあります。このソースは地元のものです。別のソースは外国のものです。友達と私は日本出身です。私たちは外国の食べ物に興味があります。ここに別の変化形があります。」',
slashRows:[{en:'Local food can change / with the climate.',jp:'地元の食べ物は変わることがあります / 気候によって'},{en:'Food can reflect / the climate.',jp:'食べ物は反映できます / 気候を'},{en:'Here is / a new sauce.',jp:'ここにあります / 新しいソースが'},{en:'A chef can create / this sauce.',jp:'シェフは作り出せます / このソースを'},{en:'The chef is / from a foreign country.',jp:'そのシェフは〜です / 外国の出身'},{en:'A variation can have / a different flavor.',jp:'1つの変化形は持つことがあります / 違う風味を'},{en:'We name / the sauce / after the city.',jp:'私たちは名づけます / そのソースを / 街にちなんで'},{en:'Creativity is / important / for new food.',jp:'創造力は〜です / 大切 / 新しい食べ物に'},{en:'Food can change / our lives.',jp:'食べ物は変えることがあります / 私たちの生活を'},{en:'This sauce is / local.',jp:'このソースは〜です / 地元の'},{en:'Another sauce is / foreign.',jp:'別のソースは〜です / 外国の'},{en:'My friend and I / come from / Japan.',jp:'友達と私は / 〜出身です / 日本'},{en:'We are interested in / food / from a foreign country.',jp:'私たちは興味があります / 食べ物に / 外国の'},{en:'Here is / another variation.',jp:'ここにあります / 別の変化形が'}],
questions:[{prompt:'1. 地元の食べ物は何によって変わることがありますか。本文から英語で答えなさい。',answer:'the climate',evidence:'Local food can change with the climate.',evidenceJp:'地元の食べ物は気候によって変わることがあります。',reason:'with の後ろが the climate です。'},{prompt:'2. 食べ物は何を反映することがありますか。本文から英語で答えなさい。',answer:'the climate',evidence:'Food can reflect the climate.',evidenceJp:'食べ物は気候を反映することがあります。',reason:'reflect の目的語が the climate です。'},{prompt:'3. 誰が新しいソースを作り出せますか。本文から英語で答えなさい。',answer:'a chef',evidence:'A chef can create this sauce.',evidenceJp:'シェフはこのソースを作り出すことができます。',reason:'主語 A chef が作る人です。'},{prompt:'4. 何にちなんでソースに名前を付けますか。本文から英語で答えなさい。',answer:'the city',evidence:'We name the sauce after the city.',evidenceJp:'私たちはその街にちなんでソースに名前を付けます。',reason:'after の後ろが the city です。'},{prompt:'5. 食べ物は何を変えることがありますか。本文から英語で答えなさい。',answer:'our lives',evidence:'Food can change our lives.',evidenceJp:'食べ物は私たちの生活を変えることがあります。',reason:'change の目的語が our lives です。'}],
allowedWords:[['change / reflect / climate / variation / foreign / sauce / name A after B / creativity / Here is[are]~. / chef / come from ~ / lives / create','Unit 2-4: v7 canonical Sheet IDs 1027-1039'],['local food / can / different / flavor / city / important / new / friend / Japan / be interested in / country','G1/Unit1/Unit2 cumulative']],
auditNote:'最新v7正本Unit2 Read and Think2（Sheet ID1027〜1039）を直接照合。change / reflect / climate / variation / foreign / sauce / name A after B / creativity / Here is / chef / come from / lives / createを、食文化と気候の説明に統合。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};