(function installV10PassageLocalNotesBatch14(){
  const defs=[
    {book:'サンシャイン',grade:'3',section:'PROGRAM 4-2',english:'enter',japanese:'入る・参加する',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-2',english:'essential',japanese:'不可欠な・非常に重要な',basis:'Not licensed by same-textbook v7 chronology at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 10-1',english:'evening',japanese:'夕方・晩',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 10-2',english:'evening',japanese:'夕方・晩',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'Get Ready 4',english:'exciting',japanese:'わくわくする・興奮させるような',basis:'Not registered in canonical v7; retained only here with gloss.'},
    {book:'サンシャイン',grade:'2',section:'PROGRAM 8-3',english:'fold',japanese:'折る',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 7-3',english:'goal',japanese:'目標・ゴール',basis:'Not licensed by same-textbook v7 chronology at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-3',english:'gorgeous',japanese:'見事な・すばらしい',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 4-3',english:'hand',japanese:'手',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-4',english:'historical',japanese:'歴史的な・歴史上の',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 2-3',english:'hotel',japanese:'ホテル',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-1',english:'hungry',japanese:'空腹の・おなかがすいた',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-4',english:'immediate',japanese:'すぐの・即座の',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-4',english:'immediately',japanese:'すぐに・直ちに',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-4',english:'interdependence',japanese:'相互依存',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-1',english:'interesting',japanese:'興味深い・おもしろい',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-2',english:'issue',japanese:'問題・課題',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 3-2',english:'job',japanese:'仕事',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'2',section:'PROGRAM 2-2',english:'join',japanese:'参加する・加わる',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 1-1',english:'junior',japanese:'年下の・下級の',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-3',english:'message',japanese:'メッセージ・伝言',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-4',english:'modern',japanese:'現代の・近代の',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 1-3',english:'movies',japanese:'映画',basis:'Surface token is not licensed by canonical v7 chronology here; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 1-1',english:'music',japanese:'音楽',basis:'Not licensed by canonical v7 chronology at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 4-1',english:'myself',japanese:'私自身・自分自身',basis:'Not licensed by canonical v7 chronology at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 3-3',english:'nutritional',japanese:'栄養の・栄養に関する',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-3',english:'police',japanese:'警察',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 3-1',english:'population',japanese:'人口',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-1',english:'pork',japanese:'豚肉',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-3',english:'pressure',japanese:'圧力・プレッシャー',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-2',english:'purpose',japanese:'目的',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 4-3',english:'rail',japanese:'レール・鉄道',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 7-3',english:'relationships',japanese:'関係・人間関係',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-4',english:'relief',japanese:'救援・安堵',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 7-2',english:'replace',japanese:'取り替える・置き換える',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-4',english:'sale',japanese:'販売・売却',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-1',english:'sandwich',japanese:'サンドイッチ',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 3-2',english:'shade',japanese:'日陰・陰',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 3-4',english:'sharply',japanese:'急激に・鋭く',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'Get Ready 4',english:'shoot',japanese:'撃つ・シュートする',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 5-3',english:'sick',japanese:'病気の・気分が悪い',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 7-1',english:'steak',japanese:'ステーキ',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 2-1',english:'strong',japanese:'強い',basis:'Not licensed by canonical v7 chronology at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 3-3',english:'suggest',japanese:'提案する・示唆する',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 3-2',english:'sunburn',japanese:'日焼け',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'1',section:'Unit 5-2',english:'surf',japanese:'サーフィンをする',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 3-4',english:'survival',japanese:'生存・生き残ること',basis:'Future-v7 lexical item at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 10-1',english:'tired',japanese:'疲れた',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'Get Ready 4',english:'together',japanese:'一緒に',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 1-1',english:'trumpet',japanese:'トランペット',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'ニューホライズン',grade:'1',section:'Unit 1-1',english:'twelve',japanese:'12・12の',basis:'Not licensed by canonical v7 chronology at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'2',section:'PROGRAM 5-3',english:'volunteer',japanese:'ボランティア',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'2',section:'PROGRAM 5-1',english:'wall',japanese:'壁',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 4-3',english:'yellow',japanese:'黄色・黄色の',basis:'Not registered in canonical v7 at this passage; passage-local note only.'},
    {book:'サンシャイン',grade:'1',section:'Get Ready 5',english:'zoo',japanese:'動物園',basis:'Not registered in canonical v7 at this passage; passage-local note only.'}
  ];
  function pools(){return [window.V10_SUNSHINE_G1,window.V10_NEWHORIZON_G1,window.V10_PASSAGES_G2_SS,window.V10_PASSAGES_G2_NH,window.V10_PASSAGES_G3_SS,window.V10_PASSAGES_G3_NH].filter(Boolean);}
  function apply(){let added=0,seen=0;for(const d of defs){for(const pool of pools())for(const m of Object.values(pool||{})){if(!m||String(m.textbook)!==d.book||String(m.grade)!==d.grade||String(m.section)!==d.section)continue;seen++;m.notes=Array.isArray(m.notes)?m.notes:[];if(!m.notes.some(n=>n&&String(n.english||'').toLowerCase()===d.english.toLowerCase())){m.notes.push({english:d.english,japanese:d.japanese,basis:d.basis});added++;}}}window.V10_PASSAGE_LOCAL_NOTES_BATCH14={seen,added,definitions:defs.length};return {seen,added};}
  apply();window.V10_APPLY_PASSAGE_LOCAL_NOTES_BATCH14=apply;
})();
