window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 7-1']={
id:'V10-NH-G2-U7-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 7-1',level:'HOP',title:'How UNESCO Selects World Heritage Sites',
sentences:['Today our class studies World Heritage sites.','We know UNESCO has a selection process.','People decide what standard to use.','UNESCO can select a natural site.','A natural site can have an important species.','A region can also be a World Heritage site.','There is more than one standard.','We find a site on a world map.','The selection is not easy.','I want to know why each site is important.','Our class talks about the standard.','I write one question about the selection.'],
fullTranslation:'「今日、私たちのクラスは世界遺産について学びます。私たちはユネスコに選定の仕組みがあることを知っています。人々はどの基準を使うかを決めます。ユネスコは自然の遺産を選ぶことができます。自然の遺産には重要な生物の種がいることがあります。地域そのものが世界遺産になることもあります。基準は1つだけではありません。私たちは世界地図で1つの遺産を見つけます。その選定は簡単ではありません。私はそれぞれの遺産がなぜ大切なのか知りたいです。クラスでその基準について話します。私は選定について1つ質問を書きます。」',
slashRows:[{en:'Today / our class studies / World Heritage sites.',jp:'今日 / 私たちのクラスは学びます / 世界遺産について'},{en:'We know / UNESCO has / a selection process.',jp:'私たちは知っています / ユネスコにはあります / 選定の仕組みが'},{en:'People decide / what standard / to use.',jp:'人々は決めます / どの基準を / 使うか'},{en:'UNESCO can select / a natural site.',jp:'ユネスコは選ぶことができます / 自然の遺産を'},{en:'A natural site can have / an important species.',jp:'自然の遺産にはいることがあります / 重要な生物の種が'},{en:'A region can also be / a World Heritage site.',jp:'ある地域も〜になれます / 世界遺産に'},{en:'There is / more than one standard.',jp:'あります / 1つより多くの基準が'},{en:'We find / a site / on a world map.',jp:'私たちは見つけます / 1つの遺産を / 世界地図で'},{en:'The selection is / not easy.',jp:'その選定は〜です / 簡単ではない'},{en:'I want to know / why each site is important.',jp:'私は知りたいです / なぜそれぞれの遺産が大切なのか'},{en:'Our class talks about / the standard.',jp:'私たちのクラスは話します / その基準について'},{en:'I write / one question / about the selection.',jp:'私は書きます / 1つ質問を / 選定について'}],
questions:[{prompt:'1. 何について学びますか。本文から英語で答えなさい。',answer:'World Heritage sites',evidence:'Today our class studies World Heritage sites.',evidenceJp:'今日、私たちのクラスは世界遺産について学びます。',reason:'studies の目的語が World Heritage sites です。'},{prompt:'2. 誰が自然の遺産を選ぶことができますか。本文から英語で答えなさい。',answer:'UNESCO',evidence:'UNESCO can select a natural site.',evidenceJp:'ユネスコは自然の遺産を選ぶことができます。',reason:'can select の主語が UNESCO です。'},{prompt:'3. 自然の遺産には何がいることがありますか。本文から英語で答えなさい。',answer:'an important species',evidence:'A natural site can have an important species.',evidenceJp:'自然の遺産には重要な生物の種がいることがあります。',reason:'have の目的語が an important species です。'},{prompt:'4. 基準はいくつありますか。本文から英語で答えなさい。',answer:'more than one',evidence:'There is more than one standard.',evidenceJp:'基準は1つだけではありません。',reason:'standard の数を表す部分が more than one です。'},{prompt:'5. 話し手は何について質問を書きますか。本文から英語で答えなさい。',answer:'the selection',evidence:'I write one question about the selection.',evidenceJp:'私は選定について1つ質問を書きます。',reason:'about の後ろが the selection です。'}],
allowedWords:[['decide / know-knew-known / natural / find-found-found / select / more than ~ / standard / species / site / region / selection','Unit 7 Part1,2 shared pool first half: v7 canonical Sheet IDs 1361-1371'],['World Heritage sites / UNESCO','Unit7 textbook-body canonical Sheet IDs 1414,1416'],['today / class / study / people / use / can / important / there is / one / easy / want to / why / each / talk about / write / question','Unit0-6 cumulative']],
auditNote:'最新v7正本Unit7 Part1,2共通プール（Sheet ID1361〜1381）の前半ID1361〜1371と教科書本文補助語World Heritage sites / UNESCOを直接照合。decide / know / natural / find / select / more than / standard / species / site / region / selectionを世界遺産の選定説明に統合。後半のplant / heritage / diversity / mixed / floral / cultural等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 7-2']={
id:'V10-NH-G2-U7-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 7-2',level:'HOP',title:'The Cape Floral Region',
sentences:['The Cape Floral Region is a World Heritage site.','It is a natural heritage site.','The region has a great diversity of plant life.','Its floral world is fantastic.','UNESCO talks about natural and cultural heritage.','Some World Heritage sites are mixed sites.','A mixed site has both natural and cultural value.','At a conference, people talk about heritage.','I think about a place in my hometown.','My hometown has an important cultural place.','In general, heritage tells us about people and nature.','I want to learn more about the Cape Floral Region.'],
fullTranslation:'「ケープ植物区は世界遺産です。それは自然遺産です。その地域には植物の大きな多様性があります。その花の世界はすばらしいです。ユネスコは自然遺産と文化遺産について扱います。世界遺産の中には複合遺産もあります。複合遺産には自然と文化の両方の価値があります。会議では、人々が遺産について話します。私は自分の故郷の場所について考えます。私の故郷には大切な文化的な場所があります。一般的に、遺産は人々と自然について私たちに教えてくれます。私はケープ植物区についてもっと学びたいです。」',
slashRows:[{en:'The Cape Floral Region is / a World Heritage site.',jp:'ケープ植物区は〜です / 世界遺産'},{en:'It is / a natural heritage site.',jp:'それは〜です / 自然遺産'},{en:'The region has / a great diversity / of plant life.',jp:'その地域にはあります / 大きな多様性が / 植物の'},{en:'Its floral world is / fantastic.',jp:'その花の世界は〜です / すばらしい'},{en:'UNESCO talks about / natural and cultural heritage.',jp:'ユネスコは扱います / 自然遺産と文化遺産について'},{en:'Some World Heritage sites are / mixed sites.',jp:'いくつかの世界遺産は〜です / 複合遺産'},{en:'A mixed site has / both natural and cultural value.',jp:'複合遺産にはあります / 自然と文化の両方の価値が'},{en:'At a conference, / people talk about / heritage.',jp:'会議では / 人々は話します / 遺産について'},{en:'I think about / a place / in my hometown.',jp:'私は考えます / ある場所について / 私の故郷の'},{en:'My hometown has / an important cultural place.',jp:'私の故郷にはあります / 大切な文化的な場所が'},{en:'In general, / heritage tells us / about people and nature.',jp:'一般的に / 遺産は私たちに伝えます / 人々と自然について'},{en:'I want to learn / more / about the Cape Floral Region.',jp:'私は学びたいです / もっと / ケープ植物区について'}],
questions:[{prompt:'1. ケープ植物区は何ですか。本文から英語で答えなさい。',answer:'a World Heritage site',evidence:'The Cape Floral Region is a World Heritage site.',evidenceJp:'ケープ植物区は世界遺産です。',reason:'be動詞の後ろが a World Heritage site です。'},{prompt:'2. その地域には何の多様性がありますか。本文から英語で答えなさい。',answer:'plant life',evidence:'The region has a great diversity of plant life.',evidenceJp:'その地域には植物の大きな多様性があります。',reason:'of の後ろが plant life です。'},{prompt:'3. 花の世界はどうですか。本文から英語で1語抜き出しなさい。',answer:'fantastic',evidence:'Its floral world is fantastic.',evidenceJp:'その花の世界はすばらしいです。',reason:'状態を表す語が fantastic です。'},{prompt:'4. 複合遺産には何の価値がありますか。本文から英語で答えなさい。',answer:'both natural and cultural value',evidence:'A mixed site has both natural and cultural value.',evidenceJp:'複合遺産には自然と文化の両方の価値があります。',reason:'has の目的語が both natural and cultural value です。'},{prompt:'5. 話し手はもっと何について学びたいですか。本文から英語で答えなさい。',answer:'the Cape Floral Region',evidence:'I want to learn more about the Cape Floral Region.',evidenceJp:'私はケープ植物区についてもっと学びたいです。',reason:'about の後ろが the Cape Floral Region です。'}],
allowedWords:[['plant / heritage / hometown / conference / diversity / mixed / floral / general / fantastic / cultural','Unit 7 Part1,2 shared pool second half: v7 canonical Sheet IDs 1372-1381'],['the Cape Floral Region / World Heritage sites / UNESCO','Unit7 textbook-body canonical Sheet IDs 1414,1416,1418'],['natural / region / site / great / life / world / talk about / some / both A and B / value / people / think about / place / important / nature / want to / learn / more','Unit0-7-1 cumulative']],
auditNote:'最新v7正本Unit7 Part1,2共通プール後半（Sheet ID1372〜1381）と教科書本文補助語the Cape Floral Region / World Heritage sites / UNESCOを直接照合。plant / heritage / hometown / conference / diversity / mixed / floral / general / fantastic / culturalを自然遺産・文化遺産・複合遺産の説明に統合。Read and Think1のprotect / marble / pollution等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 7-3']={
id:'V10-NH-G2-U7-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 7-3',level:'HOP',title:'The Taj Mahal and Its Problem',
sentences:['The Taj Mahal is a World Heritage site.','Emperor Shah Jahan built it in memory of his wife.','Its main material is white marble.','Its architecture looks like a jewel from far away.','People want to protect the Taj Mahal.','Today pollution is a serious problem.','Because of pollution, the white marble can turn dark.','The Taj Mahal must face this problem.','The government works to protect the site.','People study the material carefully.','They want the marble to stay beautiful.','I think we should protect this cultural heritage.'],
fullTranslation:'「タージ・マハルは世界遺産です。皇帝シャー・ジャハーンは妻を記念してそれを建てました。主な材料は白い大理石です。その建築は遠くから見ると宝石のように見えます。人々はタージ・マハルを守りたいと思っています。今日、汚染は深刻な問題です。汚染のため、白い大理石は黒ずむことがあります。タージ・マハルはこの問題に直面しなければなりません。政府はその遺産を守るために取り組んでいます。人々は材料を注意深く調べます。彼らは大理石を美しいままにしたいと考えています。私はこの文化遺産を守るべきだと思います。」',
slashRows:[{en:'The Taj Mahal is / a World Heritage site.',jp:'タージ・マハルは〜です / 世界遺産'},{en:'Emperor Shah Jahan built / it / in memory of his wife.',jp:'皇帝シャー・ジャハーンは建てました / それを / 妻を記念して'},{en:'Its main material is / white marble.',jp:'主な材料は〜です / 白い大理石'},{en:'Its architecture looks like / a jewel / from far away.',jp:'その建築は〜のように見えます / 宝石 / 遠くから'},{en:'People want to protect / the Taj Mahal.',jp:'人々は守りたいです / タージ・マハルを'},{en:'Today / pollution is / a serious problem.',jp:'今日 / 汚染は〜です / 深刻な問題'},{en:'Because of pollution, / the white marble can turn / dark.',jp:'汚染のため / 白い大理石は変わることがあります / 黒く'},{en:'The Taj Mahal / must face / this problem.',jp:'タージ・マハルは / 直面しなければなりません / この問題に'},{en:'The government works / to protect / the site.',jp:'政府は取り組みます / 守るために / その遺産を'},{en:'People study / the material / carefully.',jp:'人々は調べます / 材料を / 注意深く'},{en:'They want / the marble / to stay beautiful.',jp:'彼らは望みます / 大理石が / 美しいままでいることを'},{en:'I think / we should protect / this cultural heritage.',jp:'私は思います / 私たちは守るべきだと / この文化遺産を'}],
questions:[{prompt:'1. 誰がタージ・マハルを建てましたか。本文から英語で答えなさい。',answer:'Emperor Shah Jahan',evidence:'Emperor Shah Jahan built it in memory of his wife.',evidenceJp:'皇帝シャー・ジャハーンは妻を記念してそれを建てました。',reason:'built の主語が Emperor Shah Jahan です。'},{prompt:'2. 主な材料は何ですか。本文から英語で答えなさい。',answer:'white marble',evidence:'Its main material is white marble.',evidenceJp:'主な材料は白い大理石です。',reason:'material の説明が white marble です。'},{prompt:'3. 遠くから見ると何のように見えますか。本文から英語で答えなさい。',answer:'a jewel',evidence:'Its architecture looks like a jewel from far away.',evidenceJp:'その建築は遠くから見ると宝石のように見えます。',reason:'looks like の後ろが a jewel です。'},{prompt:'4. 何のために白い大理石が黒ずむことがありますか。本文から英語で答えなさい。',answer:'pollution',evidence:'Because of pollution, the white marble can turn dark.',evidenceJp:'汚染のため、白い大理石は黒ずむことがあります。',reason:'Because of の後ろが pollution です。'},{prompt:'5. 誰がその遺産を守るために取り組んでいますか。本文から英語で答えなさい。',answer:'the government',evidence:'The government works to protect the site.',evidenceJp:'政府はその遺産を守るために取り組んでいます。',reason:'works の主語が the government です。'}],
allowedWords:[['protect / material / cover / marble / build-built-built / jewel / because of ~ / government / turn / emperor / face / architecture / wife / in memory of ~ / pollution / from far away','Unit 7 Read and Think1: v7 canonical Sheet IDs 1382-1397'],['the Taj Mahal / Emperor Shah Jahan / World Heritage sites','Unit7 textbook-body canonical Sheet IDs 1414,1417,1419'],['main / white / look like / people / want to / today / serious / problem / can / dark / must / work / study / carefully / stay / beautiful / think / should / cultural heritage','Unit0-7-2 cumulative']],
auditNote:'最新v7正本Unit7 Read and Think1（Sheet ID1382〜1397）と教科書本文補助語the Taj Mahal / Emperor Shah Jahanを直接照合。protect / material / marble / built / jewel / because of / government / turn / face / architecture / wife / in memory of / pollution / from far awayをタージ・マハルの保全問題に統合。Read and Think2のsunrise / crater / cleanup / tourist等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 7-4']={
id:'V10-NH-G2-U7-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 7-4',level:'HOP',title:'Protecting a Mountain Heritage Site',
sentences:['Recently I saw a beautiful sunrise at a World Heritage site.','A cloud was over the mountain.','I left early and started to climb.','Near the crater, I saw a tourist on the trail.','More and more people visit the site.','Sometimes they leave a large amount of trash.','A cleanup campaign can help the mountain.','People list the problems before the cleanup.','The trail must stay safe and clean.','A bath near the mountain also needs clean water.','We want to protect this site forever.','I hope every tourist can enjoy the mountain.'],
fullTranslation:'「最近、私は世界遺産で美しい日の出を見ました。山の上には雲がありました。私は早く出発して登り始めました。噴火口の近くで、小道にいる観光客を見ました。ますます多くの人がその遺産を訪れます。時にはたくさんの量のごみを残していきます。大そうじのキャンペーンは山を助けることができます。人々は大そうじの前に問題をリストにします。小道は安全で清潔なままでなければなりません。山の近くの浴室にもきれいな水が必要です。私たちはこの遺産を永遠に守りたいです。すべての観光客が山を楽しめることを願います。」',
slashRows:[{en:'Recently / I saw / a beautiful sunrise / at a World Heritage site.',jp:'最近 / 私は見ました / 美しい日の出を / 世界遺産で'},{en:'A cloud was / over the mountain.',jp:'雲がありました / 山の上に'},{en:'I left / early / and started to climb.',jp:'私は出発しました / 早く / そして登り始めました'},{en:'Near the crater, / I saw / a tourist / on the trail.',jp:'噴火口の近くで / 私は見ました / 観光客を / 小道で'},{en:'More and more people / visit / the site.',jp:'ますます多くの人が / 訪れます / その遺産を'},{en:'Sometimes / they leave / a large amount of trash.',jp:'時には / 彼らは残します / たくさんの量のごみを'},{en:'A cleanup campaign / can help / the mountain.',jp:'大そうじのキャンペーンは / 助けることができます / 山を'},{en:'People list / the problems / before the cleanup.',jp:'人々はリストにします / 問題を / 大そうじの前に'},{en:'The trail must stay / safe and clean.',jp:'小道は保たれなければなりません / 安全で清潔に'},{en:'A bath / near the mountain / also needs / clean water.',jp:'浴室も / 山の近くの / 必要とします / きれいな水を'},{en:'We want to protect / this site / forever.',jp:'私たちは守りたいです / この遺産を / 永遠に'},{en:'I hope / every tourist can enjoy / the mountain.',jp:'私は願います / すべての観光客が楽しめることを / 山を'}],
questions:[{prompt:'1. 最近、何を見ましたか。本文から英語で答えなさい。',answer:'a beautiful sunrise',evidence:'Recently I saw a beautiful sunrise at a World Heritage site.',evidenceJp:'最近、私は世界遺産で美しい日の出を見ました。',reason:'saw の目的語が a beautiful sunrise です。'},{prompt:'2. どこで観光客を見ましたか。本文から英語で答えなさい。',answer:'on the trail',evidence:'Near the crater, I saw a tourist on the trail.',evidenceJp:'噴火口の近くで、小道にいる観光客を見ました。',reason:'tourist の場所を表す部分が on the trail です。'},{prompt:'3. 人々は時に何を残しますか。本文から英語で答えなさい。',answer:'a large amount of trash',evidence:'Sometimes they leave a large amount of trash.',evidenceJp:'時にはたくさんの量のごみを残していきます。',reason:'leave の目的語が a large amount of trash です。'},{prompt:'4. 何が山を助けることができますか。本文から英語で答えなさい。',answer:'a cleanup campaign',evidence:'A cleanup campaign can help the mountain.',evidenceJp:'大そうじのキャンペーンは山を助けることができます。',reason:'can help の主語が A cleanup campaign です。'},{prompt:'5. いつまでこの遺産を守りたいですか。本文から英語で1語抜き出しなさい。',answer:'forever',evidence:'We want to protect this site forever.',evidenceJp:'私たちはこの遺産を永遠に守りたいです。',reason:'時を表す語が forever です。'}],
allowedWords:[['see-saw-seen / sunrise / crater / leave-left-left / cloud / climb / campaign / a large amount of ~ / bath / more and more / cleanup / list / recently / trail / forever / tourist','Unit 7 Read and Think2: v7 canonical Sheet IDs 1398-1413'],['World Heritage sites','Unit7 textbook-body canonical Sheet ID1414'],['beautiful / mountain / early / start to / near / visit / sometimes / trash / can / help / people / problem / before / must / stay / safe / clean / also / need / water / want to / protect / hope / every / enjoy','Unit0-7-3 cumulative']],
auditNote:'最新v7正本Unit7 Read and Think2（Sheet ID1398〜1413）と教科書本文補助語World Heritage sitesを直接照合。saw / sunrise / crater / left / cloud / climb / campaign / a large amount of / bath / more and more / cleanup / list / recently / trail / forever / touristを、山の世界遺産と清掃活動の説明に統合。Real Life English 7・Stage Activity 3・Let’s Read 3の語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
