window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 2-1']={
 id:'V10-SS-G2-P2-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 2-1',level:'HOP',title:'A Baseball Project in Africa',
 sentences:['I heard about a baseball project in Africa.','I am interested in the project.','The project should promote baseball.','It has a long history.','Many people are interested in it.','One person is very passionate.','The work is not easy.','Some days are difficult.','Games take place around the city.','I root for my friend.','We should root for the project, too.','I hope the project will be successful.','Baseball can bring people together.'],
 fullTranslation:'「私はアフリカの野球プロジェクトについて聞きました。私はそのプロジェクトに興味があります。そのプロジェクトは野球を広めるべきです。長い歴史があります。多くの人がそれに興味を持っています。ある人はとても情熱的です。その活動は簡単ではありません。難しい日もあります。試合は街のあちこちで行われます。私は友達を応援します。私たちもそのプロジェクトを応援すべきです。そのプロジェクトが成功するといいと思います。野球は人々を結びつけることができます。」',
 slashRows:[{en:'I heard about / a baseball project / in Africa.',jp:'私は聞きました / 野球プロジェクトについて / アフリカの'},{en:'I am interested in / the project.',jp:'私は興味があります / そのプロジェクトに'},{en:'The project should promote / baseball.',jp:'そのプロジェクトは広めるべきです / 野球を'},{en:'It has / a long history.',jp:'それにはあります / 長い歴史が'},{en:'Many people are interested in / it.',jp:'多くの人が興味を持っています / それに'},{en:'One person is / very passionate.',jp:'ある人は〜です / とても情熱的な'},{en:'The work is / not easy.',jp:'その活動は〜ではありません / 簡単な'},{en:'Some days are / difficult.',jp:'いくつかの日は〜です / 難しい'},{en:'Games take place / around the city.',jp:'試合は行われます / 街のあちこちで'},{en:'I root for / my friend.',jp:'私は応援します / 友達を'},{en:'We should root for / the project, too.',jp:'私たちも応援すべきです / そのプロジェクトを'},{en:'I hope / the project will be successful.',jp:'私は願います / そのプロジェクトが成功することを'},{en:'Baseball can bring / people / together.',jp:'野球は結びつけられます / 人々を / いっしょに'}],
 questions:[{prompt:'1. 話し手は何について聞きましたか。本文から英語で答えなさい。',answer:'a baseball project in Africa',evidence:'I heard about a baseball project in Africa.',evidenceJp:'私はアフリカの野球プロジェクトについて聞きました。',reason:'heard about の後ろが聞いた内容です。'},{prompt:'2. 話し手はそのプロジェクトに興味がありますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I am interested in the project.',evidenceJp:'私はそのプロジェクトに興味があります。',reason:'am interested in と明示されているので Yes です。'},{prompt:'3. プロジェクトは何を広めるべきですか。本文から英語で答えなさい。',answer:'baseball',evidence:'The project should promote baseball.',evidenceJp:'そのプロジェクトは野球を広めるべきです。',reason:'promote の目的語が baseball です。'},{prompt:'4. 活動はいつも簡単ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'The work is not easy.',evidenceJp:'その活動は簡単ではありません。',reason:'not easy と否定されているので No です。'},{prompt:'5. 試合はどこで行われますか。本文から英語で答えなさい。',answer:'around the city',evidence:'Games take place around the city.',evidenceJp:'試合は街のあちこちで行われます。',reason:'around the city が場所を表しています。'}],
 allowedWords:[['hear-heard / be interested in ~ / should / promote / person / project / history / Africa / free / successful / easy / passionate / difficult / around / take place / root for ~','PROGRAM 2-1: canonical Sheet IDs 2881-2896'],['hope / will','PROGRAM 1 cumulative'],['baseball / people / city / friend / together / many / long / work / game','G1 cumulative / elementary']],
 auditNote:'Google Sheet正本でSunshine中2 PROGRAM 2-1をID2881〜2896まで直接照合。heardはhear-heardとして表層形が明示登録済み。take placeは複数主語Gamesと組み合わせ、未登録の三単現形takesを生成していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 2-2']={
 id:'V10-SS-G2-P2-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 2-2',level:'HOP',title:'Baseball and Peace',
 sentences:['Today, I visit a university.','I meet a baseball coach there.','The coach is in a national program.','The program is about baseball and peace.','I am interested in the program.','When people play together, they can be friends.','I believe sport can create peace.','The coach has the same idea.','We talk about the program.','I want to join the program someday.','We should create a good program together.','The national program is important.','I hope many people will be interested in it.'],
 fullTranslation:'「今日、私は大学を訪れます。そこで野球のコーチに会います。そのコーチは国のプログラムに参加しています。そのプログラムは野球と平和についてのものです。私はそのプログラムに興味があります。人々はいっしょにプレーすると、友達になることができます。私はスポーツが平和を生み出せると信じています。コーチも同じ考えです。私たちはそのプログラムについて話します。私はいつかそのプログラムに参加したいです。私たちはいっしょによいプログラムを作るべきです。その国のプログラムは重要です。多くの人が興味を持ってくれるといいと思います。」',
 slashRows:[{en:'Today, / I visit / a university.',jp:'今日 / 私は訪れます / 大学を'},{en:'I meet / a baseball coach / there.',jp:'私は会います / 野球のコーチに / そこで'},{en:'The coach is / in a national program.',jp:'そのコーチはいます / 国のプログラムに'},{en:'The program is / about baseball and peace.',jp:'そのプログラムは〜です / 野球と平和についての'},{en:'I am interested in / the program.',jp:'私は興味があります / そのプログラムに'},{en:'When people play / together, / they can be friends.',jp:'人々がプレーするとき / いっしょに / 友達になることができます'},{en:'I believe / sport can create / peace.',jp:'私は信じています / スポーツが生み出せると / 平和を'},{en:'The coach has / the same idea.',jp:'そのコーチにはあります / 同じ考えが'},{en:'We talk about / the program.',jp:'私たちは話します / そのプログラムについて'},{en:'I want to join / the program / someday.',jp:'私は参加したいです / そのプログラムに / いつか'},{en:'We should create / a good program / together.',jp:'私たちは作るべきです / よいプログラムを / いっしょに'},{en:'The national program is / important.',jp:'その国のプログラムは〜です / 重要な'},{en:'I hope / many people will be interested in / it.',jp:'私は願います / 多くの人が興味を持つことを / それに'}],
 questions:[{prompt:'1. 話し手はどこを訪れますか。本文から英語で答えなさい。',answer:'a university',evidence:'Today, I visit a university.',evidenceJp:'今日、私は大学を訪れます。',reason:'visit の目的語が a university です。'},{prompt:'2. 大学で誰に会いますか。本文から英語で答えなさい。',answer:'a baseball coach',evidence:'I meet a baseball coach there.',evidenceJp:'そこで野球のコーチに会います。',reason:'meet の目的語が a baseball coach です。'},{prompt:'3. プログラムは何についてのものですか。本文から英語で2つ答えなさい。',answer:'baseball and peace',evidence:'The program is about baseball and peace.',evidenceJp:'そのプログラムは野球と平和についてのものです。',reason:'about の後ろに baseball and peace が並んでいます。'},{prompt:'4. 話し手はスポーツが何を生み出せると考えていますか。本文から英語で答えなさい。',answer:'peace',evidence:'I believe sport can create peace.',evidenceJp:'私はスポーツが平和を生み出せると信じています。',reason:'create の目的語が peace です。'},{prompt:'5. 話し手はいつか何をしたいですか。本文から英語で答えなさい。',answer:'join the program',evidence:'I want to join the program someday.',evidenceJp:'私はいつかそのプログラムに参加したいです。',reason:'want to の後ろが join the program です。'}],
 allowedWords:[['when / coach / believe / university / peace / program / create / national','PROGRAM 2-2: canonical Sheet IDs 2897-2904'],['be interested in ~ / should / project','PROGRAM 2-1 cumulative'],['today / visit / meet / baseball / people / play / together / friend / sport / idea / talk about / join / someday / important / hope / will / many','G1/P1 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 2-2をID2897〜2904まで直接照合。when節・believe・create・nationalを中心に、大学での野球と平和のプログラムという1場面に統一。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 2-3']={
 id:'V10-SS-G2-P2-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 2-3',level:'HOP',title:'Sport as a Tool',
 sentences:['Sport can be a tool for people.','We use baseball as a tool.','Our goal is peace.','We learn through the project.','We remember our goal every day.','Sport has power.','The project has a positive effect.','In fact, sport can foster peace.','One home run can make people happy.','If the game is difficult, we help each other.','We should learn from the game.','We believe in the power of sport.','The project can create a positive future.','I want to remember this idea.'],
 fullTranslation:'「スポーツは人々のための道具になれます。私たちは野球を道具として使います。私たちの目標は平和です。私たちはそのプロジェクトを通じて学びます。毎日、目標を覚えています。スポーツには力があります。そのプロジェクトにはよい効果があります。実際、スポーツは平和を育むことができます。1本のホームランが人々を幸せにすることもあります。もし試合が難しければ、私たちは助け合います。私たちは試合から学ぶべきです。スポーツの力を信じています。そのプロジェクトは明るい未来を生み出すことができます。私はこの考えを覚えていたいです。」',
 slashRows:[{en:'Sport can be / a tool / for people.',jp:'スポーツは〜になれます / 道具に / 人々のための'},{en:'We use / baseball / as a tool.',jp:'私たちは使います / 野球を / 道具として'},{en:'Our goal is / peace.',jp:'私たちの目標は〜です / 平和'},{en:'We learn / through the project.',jp:'私たちは学びます / そのプロジェクトを通じて'},{en:'We remember / our goal / every day.',jp:'私たちは覚えています / 目標を / 毎日'},{en:'Sport has / power.',jp:'スポーツにはあります / 力が'},{en:'The project has / a positive effect.',jp:'そのプロジェクトにはあります / よい効果が'},{en:'In fact, / sport can foster / peace.',jp:'実際 / スポーツは育むことができます / 平和を'},{en:'One home run can make / people / happy.',jp:'1本のホームランができます / 人々を / 幸せにすることが'},{en:'If the game is difficult, / we help / each other.',jp:'もし試合が難しければ / 私たちは助けます / お互いを'},{en:'We should learn / from the game.',jp:'私たちは学ぶべきです / その試合から'},{en:'We believe in / the power of sport.',jp:'私たちは信じています / スポーツの力を'},{en:'The project can create / a positive future.',jp:'そのプロジェクトは生み出せます / 明るい未来を'},{en:'I want to remember / this idea.',jp:'私は覚えていたいです / この考えを'}],
 questions:[{prompt:'1. 野球を何として使いますか。本文から英語で答えなさい。',answer:'as a tool',evidence:'We use baseball as a tool.',evidenceJp:'私たちは野球を道具として使います。',reason:'as a tool が野球の役割を表しています。'},{prompt:'2. 目標は何ですか。本文から英語で答えなさい。',answer:'peace',evidence:'Our goal is peace.',evidenceJp:'私たちの目標は平和です。',reason:'goal の内容が peace です。'},{prompt:'3. 何を通じて学びますか。本文から英語で答えなさい。',answer:'the project',evidence:'We learn through the project.',evidenceJp:'私たちはそのプロジェクトを通じて学びます。',reason:'through の後ろが the project です。'},{prompt:'4. プロジェクトにはどのような効果がありますか。本文から英語で2語答えなさい。',answer:'positive effect',evidence:'The project has a positive effect.',evidenceJp:'そのプロジェクトにはよい効果があります。',reason:'positive effect が効果の内容です。'},{prompt:'5. 試合が難しいとき、何をしますか。本文から英語で答えなさい。',answer:'help each other',evidence:'If the game is difficult, we help each other.',evidenceJp:'もし試合が難しければ、私たちは助け合います。',reason:'if節の後ろの行動が help each other です。'}],
 allowedWords:[['if / tool / remember / power / learn / manner / through / goal / as / effect / in fact / home run / foster / positive / rain / go cycling','PROGRAM 2-3: canonical Sheet IDs 2905-2920'],['should / difficult / project / believe / peace / create','PROGRAM 2 cumulative'],['sport / people / baseball / use / every day / happy / game / help / each other / future / idea / want to','G1/P1 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 2-3をID2905〜2920まで直接照合。if / as / through / goal / effect / in fact / home run / foster / positiveを、スポーツを平和のための道具として考える説明文に統合。manner / rain / go cycling は不自然な詰め込みを避け未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
