(function installV10PassageLocalNotesBatch17(){
  const raw=`ニューホライズン	3	Unit 6-3	across	～を横切って・～を越えて	U
ニューホライズン	3	Unit 3-2	act	行動する	U
ニューホライズン	3	Unit 0	acting	演技・演じること	U
ニューホライズン	3	Unit 1-3	action	行動	F
ニューホライズン	3	Unit 5-1	affected	影響を受けた	U
ニューホライズン	2	Unit 7-3	air	空気・空中	F
ニューホライズン	1	Unit 10-2	album	アルバム	F
ニューホライズン	3	Unit 2-4	alternate	交互の・代わりの	U
サンシャイン	3	PROGRAM 5-3	article	記事	U
サンシャイン	3	PROGRAM 3-2	attracted	引きつけられた	U
ニューホライズン	2	Unit 2-4	background	背景	U
サンシャイン	1	PROGRAM 10-4	bang	ドンという音	U
サンシャイン	3	PROGRAM 2-1	bedtime	就寝時刻	U
サンシャイン	3	PROGRAM 1-1	bench	ベンチ	U
サンシャイン	3	PROGRAM 3-1	board	板・掲示板	U
サンシャイン	2	PROGRAM 7-1	body	体	U
サンシャイン	2	PROGRAM 5-1	bookshop	書店	U
ニューホライズン	3	Unit 2-4	carelessly	不注意に	U
ニューホライズン	3	Unit 6-4	chain	鎖・連鎖	U
サンシャイン	3	PROGRAM 5-3	choice	選択	F
サンシャイン	3	PROGRAM 2-2	clearly	はっきりと	F
ニューホライズン	3	Unit 1-2	closely	注意深く・密接に	U
ニューホライズン	3	Unit 2-1	clothing	衣類	F
ニューホライズン	3	Unit 3-4	coast	海岸	U
ニューホライズン	3	Unit 3-4	coastal	沿岸の	U
サンシャイン	3	PROGRAM 6-2	collection	コレクション	U
サンシャイン	3	PROGRAM 1-1	colors	色・色彩	U
ニューホライズン	3	Unit 6-4	concrete	コンクリート	U
サンシャイン	3	PROGRAM 7-1	connect	つなぐ・結びつける	F
サンシャイン	3	PROGRAM 4-1	counter	カウンター	U
ニューホライズン	3	Unit 5-3	defend	守る	U
ニューホライズン	3	Unit 4-4	delivered	届けられた・配達された	U
サンシャイン	3	PROGRAM 5-2	describe	説明する・描写する	U
ニューホライズン	3	Unit 2-1	described	説明した・描写した	U
ニューホライズン	3	Unit 2-2	describes	説明する・描写する	U
ニューホライズン	2	Unit 7-4	dirty	汚れた	U
サンシャイン	3	PROGRAM 3-1	dove	ハト	U
サンシャイン	2	PROGRAM 6-1	dry	乾いた・乾燥した／乾かす	F
ニューホライズン	3	Unit 2-2	duration	期間	U
ニューホライズン	1	Unit 4-3	enjoy	楽しむ	F
ニューホライズン	3	Unit 2-3	environmental	環境の・環境保護の	U
ニューホライズン	3	Unit 5-3	equal	等しい	U
ニューホライズン	3	Unit 4-3	erase	消す	U
ニューホライズン	3	Unit 3-4	everywhere	いたるところに	U
サンシャイン	3	PROGRAM 3-2	expected	予想された・期待された	U
ニューホライズン	2	Unit 7-3	experts	専門家たち	U
ニューホライズン	3	Unit 1-3	expressive	表現力のある	U
ニューホライズン	3	Unit 4-3	fear	恐れ	U
サンシャイン	3	PROGRAM 4-3	features	特徴	U
ニューホライズン	2	Unit 4-1	feel	感じる	F
サンシャイン	3	PROGRAM 3-1	fits	合う・適合する	U
サンシャイン	3	PROGRAM 6-1	float	浮く	U
ニューホライズン	3	Unit 3-3	focuses	焦点を当てる	U
サンシャイン	3	PROGRAM 1-3	foods	食べ物・食品	F
サンシャイン	3	PROGRAM 1-1	fun	楽しいこと	U
ニューホライズン	3	Unit 3-1	further	さらに	U
サンシャイン	1	PROGRAM 1-1	goodbye	さようなら	U
サンシャイン	3	PROGRAM 5-2	group	グループ・集団	F
サンシャイン	3	PROGRAM 5-2	groups	グループ・集団	F
ニューホライズン	3	Unit 6-3	guess	推測する	U
ニューホライズン	3	Unit 2-4	harm	害・傷つけること	U
サンシャイン	1	PROGRAM 1-2	hello	こんにちは・もしもし	U
ニューホライズン	1	Unit 1-1	hello	こんにちは・もしもし	F
ニューホライズン	1	Unit 10-2	hey	やあ・ねえ	F
サンシャイン	3	PROGRAM 3-2	himself	彼自身	U
ニューホライズン	2	Unit 7-4	hope	望む・希望する	U
サンシャイン	3	PROGRAM 3-2	huge	巨大な	F
サンシャイン	3	PROGRAM 6-1	hurt	傷つける・痛む	F
ニューホライズン	2	Unit 2-4	ideas	考え・アイデア	F
ニューホライズン	1	Unit 10-2	important	重要な・大切な	F
サンシャイン	3	PROGRAM 3-3	improve	改善する	F
ニューホライズン	3	Unit 4-3	infrastructure	インフラ・社会基盤	U
サンシャイン	1	PROGRAM 7-3	koala	コアラ	F
ニューホライズン	3	Unit 5-3	legal	法律上の・合法の	U
ニューホライズン	3	Unit 4-1	location	場所・位置	U
ニューホライズン	3	Unit 3-3	locations	場所・位置	U
ニューホライズン	3	Unit 4-3	loss	損失・喪失	U
ニューホライズン	3	Unit 5-1	major	主要な	U
ニューホライズン	3	Unit 2-2	meaningful	意味のある	U
ニューホライズン	3	Unit 4-4	narrow	狭い	U
サンシャイン	2	PROGRAM 6-2	nature	自然	U
ニューホライズン	3	Unit 5-4	opposed	反対した・反対の	U
ニューホライズン	3	Unit 2-2	otherwise	そうでなければ	U
サンシャイン	1	PROGRAM 8-1	peach	モモ	U
ニューホライズン	3	Unit 4-4	period	期間・時期	U
サンシャイン	1	PROGRAM 8-1	persimmon	カキ（果物）	F
サンシャイン	3	PROGRAM 2-3	phones	電話・スマートフォン	F
サンシャイン	3	PROGRAM 2-3	preparation	準備	U
サンシャイン	3	PROGRAM 5-3	produce	生産する・作る	U
ニューホライズン	3	Unit 2-4	produced	生産された・作られた	F
ニューホライズン	3	Unit 6-2	rather	むしろ	U
サンシャイン	3	PROGRAM 6-2	real	本当の・本物の	U
ニューホライズン	3	Unit 3-3	realistic	現実的な	U
サンシャイン	1	Get Ready 2	really	本当に	U
サンシャイン	3	PROGRAM 3-2	recent	最近の	U
サンシャイン	3	PROGRAM 7-2	recognize	認識する・見分ける	U
ニューホライズン	3	Unit 3-4	recover	回復する	U
ニューホライズン	3	Unit 4-4	recovery	回復・復旧	U
ニューホライズン	3	Unit 2-1	recycling	リサイクル・再生利用	F
サンシャイン	3	PROGRAM 6-3	reduction	削減・減少	U
ニューホライズン	3	Unit 4-2	reliable	信頼できる	U
ニューホライズン	2	Unit 7-3	remain	残る	U
サンシャイン	3	PROGRAM 7-1	remote	遠隔の・離れた	U
サンシャイン	3	PROGRAM 4-3	remove	取り除く	F
ニューホライズン	3	Unit 3-3	report	報告・レポート／報告する	F
ニューホライズン	3	Unit 4-4	reported	報告された・報告した	F
ニューホライズン	3	Unit 6-3	request	要請・依頼	U
ニューホライズン	3	Unit 6-2	respectfully	丁重に・敬意をもって	U
サンシャイン	3	PROGRAM 7-3	respond	応答する・返答する	U
サンシャイン	1	PROGRAM 7-1	restaurant	レストラン	U
サンシャイン	3	PROGRAM 6-3	reusable	再利用できる	U
ニューホライズン	3	Unit 2-3	reuse	再利用する	U
ニューホライズン	3	Unit 2-3	reusing	再利用すること・再利用している	U
サンシャイン	3	PROGRAM 7-2	role	役・役割	U
ニューホライズン	3	Unit 3-3	routes	経路・ルート	U
サンシャイン	3	PROGRAM 4-3	safely	安全に	U
ニューホライズン	3	Unit 1-4	series	一連・シリーズ	U
ニューホライズン	2	Unit 7-3	serious	深刻な・重大な	U
サンシャイン	3	PROGRAM 4-2	shown	示された	U
ニューホライズン	2	Unit 5-2	side	側・面	F
ニューホライズン	3	Unit 4-4	simply	単に・簡単に	U
サンシャイン	3	PROGRAM 3-3	slow	遅い	U
ニューホライズン	3	Unit 5-3	social	社会の・社会的な	U
ニューホライズン	3	Unit 3-1	space	空間・場所	U
サンシャイン	1	PROGRAM 10-4	started	始めた・始まった	U
ニューホライズン	3	Unit 1-4	storytelling	物語を語ること	U
ニューホライズン	3	Unit 6-3	suitable	適した	U
ニューホライズン	3	Unit 4-3	support	支援する・支える	F
サンシャイン	3	PROGRAM 7-3	technology	（科学）技術	U
サンシャイン	3	PROGRAM 6-2	teenager	10代の若者	U
サンシャイン	3	PROGRAM 2-2	test	テスト・試験	U
サンシャイン	2	PROGRAM 5-3	thanked	感謝した	F
ニューホライズン	3	Unit 2-2	thrown	投げられた	U
ニューホライズン	3	Unit 6-4	transport	交通・輸送	U
サンシャイン	2	PROGRAM 2-3	trouble	困難・問題	F
ニューホライズン	3	Unit 6-2	unknown	未知の・知られていない	U
ニューホライズン	2	Unit 7-4	unsafe	安全でない	U
ニューホライズン	3	Unit 3-3	usual	いつもの・通常の	U
ニューホライズン	3	Unit 1-3	viewers	視聴者	U
ニューホライズン	3	Unit 1-2	visitor	訪問者	U
ニューホライズン	3	Unit 1-4	visual	視覚の・視覚的な	U
サンシャイン	3	PROGRAM 2-2	wake	目を覚ます・起こす	F
ニューホライズン	2	Unit 5-1	weak	弱い	F
サンシャイン	3	PROGRAM 3-2	weather	天気	U
ニューホライズン	3	Unit 4-2	web	ウェブ	U
ニューホライズン	3	Unit 3-1	wildlife	野生生物	U
サンシャイン	1	Step 6 / Our Project 3 / Power-Up 6	wishes	願い・願う	F
ニューホライズン	3	Unit 2-1	workers	働く人々・労働者	F
サンシャイン	3	PROGRAM 7-1	world	世界	U
ニューホライズン	3	Unit 3-2	worse	より悪い	U
サンシャイン	1	PROGRAM 2-3	wow	うわあ	U
サンシャイン	1	PROGRAM 4-1	zebra	シマウマ	F`;
  const defs=raw.trim().split(/\n/).map(line=>{const [book,grade,section,english,japanese,kind]=line.split('\t');return {book,grade,section,english,japanese,basis:kind==='F'?'Future-v7 lexical item at this passage; passage-local note only.':'Not licensed by same-textbook v7 chronology at this passage; passage-local note only.'};});
  function pools(){return [window.V10_SUNSHINE_G1,window.V10_NEWHORIZON_G1,window.V10_PASSAGES_G2_SS,window.V10_PASSAGES_G2_NH,window.V10_PASSAGES_G3_SS,window.V10_PASSAGES_G3_NH].filter(Boolean);}
  function apply(){let added=0,seen=0;for(const d of defs){for(const pool of pools())for(const m of Object.values(pool||{})){if(!m||String(m.textbook)!==d.book||String(m.grade)!==d.grade||String(m.section)!==d.section)continue;seen++;m.notes=Array.isArray(m.notes)?m.notes:[];if(!m.notes.some(n=>n&&String(n.english||'').toLowerCase()===d.english.toLowerCase())){m.notes.push({english:d.english,japanese:d.japanese,basis:d.basis});added++;}}}window.V10_PASSAGE_LOCAL_NOTES_BATCH17={seen,added,definitions:defs.length};return {seen,added};}
  apply();window.V10_APPLY_PASSAGE_LOCAL_NOTES_BATCH17=apply;
})();
