window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 3-1']={
 id:'V10-SS-G2-P3-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 3-1',level:'HOP',title:'An American Festival',
 sentences:['Today, I am at an American festival.','I wait for my friend.','I am interested in American culture.','Many people are at the festival.','I eat a light meal there.','The taste is very good.','My friend is here now.','We eat together.','We listen to music.','We talk about the festival.','The festival is very exciting.','I want to visit it again.','I like this culture very much.'],
 fullTranslation:'「今日、私はアメリカの祭りに来ています。友達を待っています。私はアメリカ文化に興味があります。祭りには多くの人がいます。そこで軽い食事をします。味はとてもよいです。友達も今ここにいます。私たちはいっしょに食べます。音楽を聞きます。祭りについて話します。その祭りはとてもわくわくします。また訪れたいです。私はこの文化がとても好きです。」',
 slashRows:[{en:'Today, / I am at / an American festival.',jp:'今日 / 私はいます / アメリカの祭りに'},{en:'I wait for / my friend.',jp:'私は待ちます / 友達を'},{en:'I am interested in / American culture.',jp:'私は興味があります / アメリカ文化に'},{en:'Many people are / at the festival.',jp:'多くの人がいます / その祭りに'},{en:'I eat / a light meal / there.',jp:'私は食べます / 軽い食事を / そこで'},{en:'The taste is / very good.',jp:'味は〜です / とてもよい'},{en:'My friend is / here / now.',jp:'私の友達はいます / ここに / 今'},{en:'We eat / together.',jp:'私たちは食べます / いっしょに'},{en:'We listen to / music.',jp:'私たちは聞きます / 音楽を'},{en:'We talk about / the festival.',jp:'私たちは話します / その祭りについて'},{en:'The festival is / very exciting.',jp:'その祭りは〜です / とてもわくわくする'},{en:'I want to visit / it / again.',jp:'私は訪れたいです / それを / また'},{en:'I like / this culture / very much.',jp:'私は好きです / この文化が / とても'}],
 questions:[{prompt:'1. 話し手はどこにいますか。本文から英語で答えなさい。',answer:'at an American festival',evidence:'Today, I am at an American festival.',evidenceJp:'今日、私はアメリカの祭りに来ています。',reason:'at の後ろが an American festival です。'},{prompt:'2. 誰を待っていますか。本文から英語で答えなさい。',answer:'my friend',evidence:'I wait for my friend.',evidenceJp:'友達を待っています。',reason:'wait for の後ろが my friend です。'},{prompt:'3. 何に興味がありますか。本文から英語で答えなさい。',answer:'American culture',evidence:'I am interested in American culture.',evidenceJp:'私はアメリカ文化に興味があります。',reason:'interested in の後ろが American culture です。'},{prompt:'4. 食事はどのようなものですか。本文から英語で1語抜き出しなさい。',answer:'light',evidence:'I eat a light meal there.',evidenceJp:'そこで軽い食事をします。',reason:'light が meal を説明しています。'},{prompt:'5. 味はどうですか。本文から英語で2語抜き出しなさい。',answer:'very good',evidence:'The taste is very good.',evidenceJp:'味はとてもよいです。',reason:'very good が味への評価です。'}],
 allowedWords:[['wait / taste / culture / American / festival / light','PROGRAM 3-1: canonical Sheet IDs 2950-2955'],['be interested in ~','PROGRAM 2 cumulative'],['today / friend / many / people / meal / good / here / now / together / listen to / music / talk about / exciting / want to / visit / again / very much','G1/P1-P2 cumulative']],
 auditNote:'Google Sheet正本でSunshine中2 PROGRAM 3-1をID2950〜2955まで直接照合。American festivalという1場面に限定し、wait / taste / culture / lightを自然な文脈で使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 3-2']={
 id:'V10-SS-G2-P3-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 3-2',level:'HOP',title:'A Card at the Festival',
 sentences:['Today, I visit the festival for the first time.','Here is a thin card.','We sell this card at the festival.','We earn money for our project.','Then we buy food.','Some children make the cards themselves.','I like their work.','The card is light and beautiful.','I want to make one, too.','I look forward to visiting the festival again.','I want to come back sometime soon.','We talk about the festival after school.','The day is special for me.'],
 fullTranslation:'「今日、私は初めてその祭りを訪れます。これが薄いカードです。私たちは祭りでこのカードを売ります。プロジェクトのためにお金を得ます。それから食べ物を買います。子どもたちの中には、そのカードを自分たちで作る人もいます。私はその活動が好きです。カードは軽くてきれいです。私も1枚作りたいです。またその祭りを訪れるのを楽しみにしています。そのうちすぐにまた来たいです。放課後、私たちはその祭りについて話します。その日は私にとって特別です。」',
 slashRows:[{en:'Today, / I visit / the festival / for the first time.',jp:'今日 / 私は訪れます / その祭りを / 初めて'},{en:'Here is / a thin card.',jp:'これが〜です / 薄いカード'},{en:'We sell / this card / at the festival.',jp:'私たちは売ります / このカードを / その祭りで'},{en:'We earn / money / for our project.',jp:'私たちは得ます / お金を / 私たちのプロジェクトのために'},{en:'Then / we buy / food.',jp:'それから / 私たちは買います / 食べ物を'},{en:'Some children make / the cards / themselves.',jp:'子どもたちの中には作る人もいます / そのカードを / 自分たちで'},{en:'I like / their work.',jp:'私は好きです / その活動が'},{en:'The card is / light and beautiful.',jp:'そのカードは〜です / 軽くて美しい'},{en:'I want to make / one, too.',jp:'私は作りたいです / 1つを / 私も'},{en:'I look forward to visiting / the festival / again.',jp:'私は訪れるのを楽しみにしています / その祭りを / また'},{en:'I want to come back / sometime soon.',jp:'私は戻って来たいです / そのうちすぐに'},{en:'We talk about / the festival / after school.',jp:'私たちは話します / その祭りについて / 放課後に'},{en:'The day is / special / for me.',jp:'その日は〜です / 特別な / 私にとって'}],
 questions:[{prompt:'1. 話し手はその祭りを何回目に訪れますか。本文から英語で答えなさい。',answer:'for the first time',evidence:'Today, I visit the festival for the first time.',evidenceJp:'今日、私は初めてその祭りを訪れます。',reason:'for the first time が初めてであることを表しています。'},{prompt:'2. 最初に示されるカードはどのようなものですか。本文から英語で1語抜き出しなさい。',answer:'thin',evidence:'Here is a thin card.',evidenceJp:'これが薄いカードです。',reason:'thin が card を説明しています。'},{prompt:'3. カードを売って何を得ますか。本文から英語で答えなさい。',answer:'money',evidence:'We earn money for our project.',evidenceJp:'プロジェクトのためにお金を得ます。',reason:'earn の目的語が money です。'},{prompt:'4. 誰がカードを自分たちで作りますか。本文から英語で答えなさい。',answer:'Some children',evidence:'Some children make the cards themselves.',evidenceJp:'子どもたちの中には、そのカードを自分たちで作る人もいます。',reason:'文の主語 Some children が作る人です。'},{prompt:'5. 話し手は何を楽しみにしていますか。本文から英語で答えなさい。',answer:'visiting the festival again',evidence:'I look forward to visiting the festival again.',evidenceJp:'またその祭りを訪れるのを楽しみにしています。',reason:'look forward to の後ろが visiting the festival again です。'}],
 allowedWords:[['sell / then / look forward to ~ing / themselves / for the first time / sometime soon / earn / Here is ~. / thin','PROGRAM 3-2: canonical Sheet IDs 2956-2964'],['festival / light','PROGRAM 3-1 cumulative'],['card / money / project / buy / food / children / make / work / beautiful / want to / come back / talk about / after school / special','G1/P1-P2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 3-2をID2956〜2964まで直接照合。look forward to ~ing の登録構造に従って visiting を使用し、一般的な-ing自動解禁にはしていない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 3-3']={
 id:'V10-SS-G2-P3-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 3-3',level:'HOP',title:'A Dutch Corner at the Festival',
 sentences:['At the festival, I meet a Dutch student.','The student is from the Netherlands.','The student has a job at the festival.','Can you show me this bowl?','Sure.','The bowl is handmade.','Each bowl is light.','I can carry it easily.','The smell of the food is nice.','Some people buy food.','Others buy a handmade bowl.','At the end, we donate money.','Good job.','I want to visit this festival again.'],
 fullTranslation:'「祭りで、私はオランダ人の生徒に会います。その生徒はオランダ出身です。その生徒には祭りでの仕事があります。」「このどんぶりを見せてくれますか。」「もちろん。」そのどんぶりは手作りです。それぞれのどんぶりは軽いです。私は簡単に持ち運べます。食べ物のにおいはよいです。食べ物を買う人もいれば、手作りのどんぶりを買う人もいます。最後に、私たちはお金を寄付します。よくやったね。私はまたこの祭りを訪れたいです。」',
 slashRows:[{en:'At the festival, / I meet / a Dutch student.',jp:'祭りで / 私は会います / オランダ人の生徒に'},{en:'The student is from / the Netherlands.',jp:'その生徒は〜出身です / オランダ'},{en:'The student has / a job / at the festival.',jp:'その生徒にはあります / 仕事が / その祭りで'},{en:'Can you show / me / this bowl?',jp:'見せてくれますか / 私に / このどんぶりを'},{en:'Sure.',jp:'もちろん。'},{en:'The bowl is / handmade.',jp:'そのどんぶりは〜です / 手作りの'},{en:'Each bowl is / light.',jp:'それぞれのどんぶりは〜です / 軽い'},{en:'I can carry / it / easily.',jp:'私は運べます / それを / 簡単に'},{en:'The smell of the food is / nice.',jp:'食べ物のにおいは〜です / よい'},{en:'Some people buy / food.',jp:'食べ物を買う人もいます'},{en:'Others buy / a handmade bowl.',jp:'手作りのどんぶりを買う人もいます'},{en:'At the end, / we donate / money.',jp:'最後に / 私たちは寄付します / お金を'},{en:'Good job.',jp:'よくやったね。'},{en:'I want to visit / this festival / again.',jp:'私は訪れたいです / この祭りを / また'}],
 questions:[{prompt:'1. 話し手が会う生徒はどこの人ですか。本文から英語で答えなさい。',answer:'Dutch',evidence:'At the festival, I meet a Dutch student.',evidenceJp:'祭りで、私はオランダ人の生徒に会います。',reason:'Dutch が student を説明しています。'},{prompt:'2. その生徒はどこの出身ですか。本文から英語で答えなさい。',answer:'the Netherlands',evidence:'The student is from the Netherlands.',evidenceJp:'その生徒はオランダ出身です。',reason:'from の後ろが the Netherlands です。'},{prompt:'3. どんぶりはどのようなものですか。本文から英語で1語抜き出しなさい。',answer:'handmade',evidence:'The bowl is handmade.',evidenceJp:'そのどんぶりは手作りです。',reason:'handmade が bowl を説明しています。'},{prompt:'4. どんぶりをどのように運べますか。本文から英語で1語抜き出しなさい。',answer:'easily',evidence:'I can carry it easily.',evidenceJp:'私は簡単に持ち運べます。',reason:'easily が carry のしかたを表しています。'},{prompt:'5. 最後に何を寄付しますか。本文から英語で答えなさい。',answer:'money',evidence:'At the end, we donate money.',evidenceJp:'最後に、私たちはお金を寄付します。',reason:'donate の目的語が money です。'}],
 allowedWords:[['show / the Netherlands / job / smell / each / bowl / easily / handmade / Some A. Others B. / Dutch / donate / Good job. / catch','PROGRAM 3-3: canonical Sheet IDs 2965-2977'],['festival / light / sell','PROGRAM 3 cumulative'],['student / carry / food / people / buy / money / Sure. / want to / visit / again / at the end','G1/P1-P2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 3-3をID2965〜2977まで直接照合。Dutch / the Netherlands / handmade bowl / donateを同じ文化祭の場面に統合。catch は不自然な詰め込みを避け未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
