window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 4-1']={
id:'V10-NH-G3-U4-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 4-1',level:'HOP',title:'Getting Prepared for a Disaster',
sentences:['We store water in case of a disaster.','We store food too.','In case of fire, we use an extinguisher.','I circle the extinguisher on a map.','I circle the shelter too.','The shelter is near our school.','Our family is prepared.','I ask, “How much water do we need?”','We write the number for the shelter in a notebook.','The number is easy to see.','We talk about what to do in a disaster.','I want our family to stay prepared.'],
fullTranslation:'「私たちは災害の場合に備えて水を蓄えます。食べ物も蓄えます。火事の場合には消火器を使います。私は地図上の消火器を丸で囲みます。避難所も丸で囲みます。その避難所は私たちの学校の近くにあります。私たちの家族は準備ができています。私は『どれくらいの水が必要ですか』とたずねます。私たちは避難所の番号をノートに書きます。その番号は見やすいです。災害のときに何をするかについて話します。私は家族に準備ができた状態でいてほしいです。」',
slashRows:[{en:'We store / water / in case of a disaster.',jp:'私たちは蓄えます / 水を / 災害の場合に備えて'},{en:'We store / food / too.',jp:'私たちは蓄えます / 食べ物を / も'},{en:'In case of fire, / we use / an extinguisher.',jp:'火事の場合には / 私たちは使います / 消火器を'},{en:'I circle / the extinguisher / on a map.',jp:'私は丸で囲みます / 消火器を / 地図上で'},{en:'I circle / the shelter / too.',jp:'私は丸で囲みます / 避難所を / も'},{en:'The shelter is / near our school.',jp:'その避難所はあります / 私たちの学校の近くに'},{en:'Our family is / prepared.',jp:'私たちの家族は〜です / 準備ができている'},{en:'I ask, / “How much water / do we need?”',jp:'私はたずねます / 「どれくらいの水が / 必要ですか」'},{en:'We write / the number / for the shelter / in a notebook.',jp:'私たちは書きます / 番号を / 避難所の / ノートに'},{en:'The number is / easy to see.',jp:'その番号は〜です / 見やすい'},{en:'We talk about / what to do / in a disaster.',jp:'私たちは話します / 何をするかについて / 災害のときに'},{en:'I want / our family / to stay prepared.',jp:'私は望みます / 家族に / 準備ができた状態でいてほしいと'}],
questions:[{prompt:'1. 災害の場合に備えて何を蓄えますか。本文から英語で答えなさい。',answer:'water',evidence:'We store water in case of a disaster.',evidenceJp:'私たちは災害の場合に備えて水を蓄えます。',reason:'store の目的語が water です。'},{prompt:'2. 火事の場合には何を使いますか。本文から英語で答えなさい。',answer:'an extinguisher',evidence:'In case of fire, we use an extinguisher.',evidenceJp:'火事の場合には消火器を使います。',reason:'use の目的語が an extinguisher です。'},{prompt:'3. 消火器のほかに何を丸で囲みますか。本文から英語で答えなさい。',answer:'the shelter',evidence:'I circle the shelter too.',evidenceJp:'避難所も丸で囲みます。',reason:'circle の目的語が the shelter です。'},{prompt:'4. 家族はどのような状態ですか。本文から英語で1語抜き出しなさい。',answer:'prepared',evidence:'Our family is prepared.',evidenceJp:'私たちの家族は準備ができています。',reason:'family の状態を表す語が prepared です。'},{prompt:'5. 何の番号をノートに書きますか。本文から英語で答えなさい。',answer:'the shelter',evidence:'We write the number for the shelter in a notebook.',evidenceJp:'私たちは避難所の番号をノートに書きます。',reason:'for の後ろが the shelter です。'}],
allowedWords:[['store / disaster / in case of ~ / fire / circle / extinguisher / shelter / prepared / number / How much ~?','Unit 4 Part1: v7 canonical Sheet IDs 1873-1882'],['water / food / use / map / near / school / family / ask / need / write / notebook / easy to see / talk about / what to do / want A to B / stay','Unit0-3/G1-G2 cumulative']],
auditNote:'最新v7正本Unit4 Part1（Sheet ID1873〜1882）を直接照合。store / disaster / in case of / fire / circle / extinguisher / shelter / prepared / number / How muchを災害準備のチェックという自然な流れに統合。Part2のprepare / emergency / earthquake / kit等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 4-2']={
id:'V10-NH-G3-U4-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 4-2',level:'HOP',title:'Our Emergency Kit',
sentences:["We've prepared an emergency kit.",'We prepare water and food for an earthquake.','We have done this before.','The kit is near the door.','I recommend a small kit.','A big kit is hard to carry.','I read a link about an emergency.','The link has a list for an earthquake.','My friend hasn’t prepared a kit yet.','I recommend water first.','In an emergency, we use the kit.','We want to be prepared before an earthquake.'],
fullTranslation:'「私たちは緊急用の道具一式を準備しました。地震に備えて水と食べ物を準備します。私たちは以前にもこれをしたことがあります。その道具一式はドアの近くにあります。私は小さな道具一式をすすめます。大きな道具一式は持ち運ぶのが大変です。私は緊急事態についてのリンクを読みます。そのリンクには地震のためのリストがあります。友達はまだ道具一式を準備していません。私はまず水をすすめます。緊急事態ではその道具一式を使います。私たちは地震の前に準備ができていたいです。」',
slashRows:[{en:"We've prepared / an emergency kit.",jp:'私たちは準備しました / 緊急用の道具一式を'},{en:'We prepare / water and food / for an earthquake.',jp:'私たちは準備します / 水と食べ物を / 地震に備えて'},{en:'We have done / this / before.',jp:'私たちはしました / これを / 前にも'},{en:'The kit is / near the door.',jp:'その道具一式はあります / ドアの近くに'},{en:'I recommend / a small kit.',jp:'私はすすめます / 小さな道具一式を'},{en:'A big kit is / hard / to carry.',jp:'大きな道具一式は〜です / 困難 / 持ち運ぶのが'},{en:'I read / a link / about an emergency.',jp:'私は読みます / リンクを / 緊急事態についての'},{en:'The link has / a list / for an earthquake.',jp:'そのリンクにはあります / リストが / 地震のための'},{en:'My friend hasn’t prepared / a kit / yet.',jp:'私の友達は準備していません / 道具一式を / まだ'},{en:'I recommend / water / first.',jp:'私はすすめます / 水を / まず'},{en:'In an emergency, / we use / the kit.',jp:'緊急事態では / 私たちは使います / その道具一式を'},{en:'We want to be / prepared / before an earthquake.',jp:'私たちは〜でいたいです / 準備ができた状態 / 地震の前に'}],
questions:[{prompt:'1. 何を準備しましたか。本文から英語で答えなさい。',answer:'an emergency kit',evidence:"We've prepared an emergency kit.",evidenceJp:'私たちは緊急用の道具一式を準備しました。',reason:'prepared の目的語が an emergency kit です。'},{prompt:'2. 何に備えて水と食べ物を準備しますか。本文から英語で答えなさい。',answer:'an earthquake',evidence:'We prepare water and food for an earthquake.',evidenceJp:'地震に備えて水と食べ物を準備します。',reason:'for の後ろが an earthquake です。'},{prompt:'3. 大きな道具一式はどうですか。本文から英語で1語抜き出しなさい。',answer:'hard',evidence:'A big kit is hard to carry.',evidenceJp:'大きな道具一式は持ち運ぶのが大変です。',reason:'kit の状態を表す語が hard です。'},{prompt:'4. 友達はもう道具一式を準備しましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'My friend hasn’t prepared a kit yet.',evidenceJp:'友達はまだ道具一式を準備していません。',reason:'hasn’t ... yet とあるので No です。'},{prompt:'5. 緊急事態では何を使いますか。本文から英語で答えなさい。',answer:'the kit',evidence:'In an emergency, we use the kit.',evidenceJp:'緊急事態ではその道具一式を使います。',reason:'use の目的語が the kit です。'}],
allowedWords:[["prepare / emergency / done / earthquake / recommend / hard / link / we've / kit / hasn't",'Unit 4 Part2: v7 canonical Sheet IDs 1883-1892'],['prepared / water / food / before / near / door / small / big / carry / read / list / friend / yet / first / use / want to be','Unit0-4-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit4 Part2（Sheet ID1883〜1892）を直接照合。prepare / emergency / done / earthquake / recommend / hard / link / we’ve / kit / hasn’tを緊急用キットの準備に統合。Read and Think1のbridge / comfort / several / safe / encourage等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 4-3']={
id:'V10-NH-G3-U4-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 4-3',level:'HOP',title:'A Bridge between People after a Disaster',
sentences:['A disaster hit our town.','Several people went to a shelter.','A bridge is between our town and the shelter.','The bridge is safe.','An energetic student can encourage people.','The student can comfort a friend.','People help each other all the time.','Some people were killed in the disaster.','We remember them and help each other.','The bridge can be a bridge between people too.','We want the shelter to stay safe.','I think encouragement can help people after a disaster.'],
fullTranslation:'「災害が私たちの町を襲いました。何人かの人が避難所へ行きました。橋は私たちの町と避難所の間にあります。その橋は安全です。元気な生徒は人々を励ますことができます。その生徒は友達を慰めることができます。人々はいつもお互いに助け合います。その災害で亡くなった人もいました。私たちはその人たちを覚え、お互いに助け合います。その橋は人と人とのかけ橋にもなれます。私たちは避難所に安全な状態であってほしいです。私は励ますことが災害後の人々を助けることができると思います。」',
slashRows:[{en:'A disaster hit / our town.',jp:'災害が襲いました / 私たちの町を'},{en:'Several people went to / a shelter.',jp:'何人かの人が行きました / 避難所へ'},{en:'A bridge is / between our town and the shelter.',jp:'橋はあります / 私たちの町と避難所の間に'},{en:'The bridge is / safe.',jp:'その橋は〜です / 安全'},{en:'An energetic student / can encourage / people.',jp:'元気な生徒は / 励ますことができます / 人々を'},{en:'The student / can comfort / a friend.',jp:'その生徒は / 慰めることができます / 友達を'},{en:'People help / each other / all the time.',jp:'人々は助け合います / お互いに / いつも'},{en:'Some people / were killed in / the disaster.',jp:'何人かの人は / 亡くなりました / その災害で'},{en:'We remember / them / and help each other.',jp:'私たちは覚えます / その人たちを / そしてお互いに助けます'},{en:'The bridge can be / a bridge / between people / too.',jp:'その橋は〜にもなれます / かけ橋 / 人々の間の / も'},{en:'We want / the shelter / to stay safe.',jp:'私たちは望みます / 避難所に / 安全な状態であってほしいと'},{en:'I think / encouragement can help / people / after a disaster.',jp:'私は思います / 励ますことは助けられると / 人々を / 災害のあとに'}],
questions:[{prompt:'1. 何が町を襲いましたか。本文から英語で答えなさい。',answer:'a disaster',evidence:'A disaster hit our town.',evidenceJp:'災害が私たちの町を襲いました。',reason:'hit の主語が A disaster です。'},{prompt:'2. 何人かの人はどこへ行きましたか。本文から英語で答えなさい。',answer:'a shelter',evidence:'Several people went to a shelter.',evidenceJp:'何人かの人が避難所へ行きました。',reason:'went to の後ろが a shelter です。'},{prompt:'3. 橋はどこにありますか。本文から英語で答えなさい。',answer:'between our town and the shelter',evidence:'A bridge is between our town and the shelter.',evidenceJp:'橋は私たちの町と避難所の間にあります。',reason:'between A and B の部分が場所を示しています。'},{prompt:'4. 元気な生徒は人々をどうすることができますか。本文から英語で1語抜き出しなさい。',answer:'encourage',evidence:'An energetic student can encourage people.',evidenceJp:'元気な生徒は人々を励ますことができます。',reason:'can の後ろの動詞が encourage です。'},{prompt:'5. 生徒は友達をどうすることができますか。本文から英語で1語抜き出しなさい。',answer:'comfort',evidence:'The student can comfort a friend.',evidenceJp:'その生徒は友達を慰めることができます。',reason:'can の後ろの動詞が comfort です。'}],
allowedWords:[['bridge / comfort / between A and B / several / all the time / safe / energetic / hit-hit-hit / be killed in ~ / encourage','Unit 4 Read and Think1: v7 canonical Sheet IDs 1893-1902'],['disaster / town / people / go-went / shelter / student / can / friend / help / each other / some / remember / want A to B / stay / think / after','Unit0-4-2/G1-G2 cumulative']],
auditNote:'最新v7正本Unit4 Read and Think1（Sheet ID1893〜1902）を直接照合。bridge / comfort / between A and B / several / all the time / safe / energetic / hit / be killed in / encourageを、災害後に人々が支え合う説明文に統合。Read and Think2のsupport / exchange / crisis / bicycle / program / no longer等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 4-4']={
id:'V10-NH-G3-U4-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 4-4',level:'HOP',title:'A Support Program after a Crisis',
sentences:['We hear sudden news about a crisis.','An ordinary person can support other people.','One student rode a bicycle to the shelter.','During the crisis, I caught a child.','Shortly, we started a support program.','People exchange news at the shelter.','We work to support people.','The program can bring people together.','A bicycle can be useful in a crisis.','The crisis is no longer a problem for our town.','We continue the exchange program.','I think ordinary people can bring a town together.'],
fullTranslation:'「私たちは危機について突然の知らせを聞きます。普通の人でもほかの人々を支援できます。1人の生徒は自転車に乗って避難所へ行きました。危機の間、私は子どもを受け止めました。まもなく、私たちは支援プログラムを始めました。人々は避難所で知らせを交換します。私たちは人々を支えるために取り組みます。そのプログラムは人々を団結させることができます。自転車は危機のときに役立つことがあります。その危機はもはや私たちの町の問題ではありません。私たちは交流プログラムを続けます。普通の人々が町を団結させることができると私は思います。」',
slashRows:[{en:'We hear / sudden news / about a crisis.',jp:'私たちは聞きます / 突然の知らせを / 危機についての'},{en:'An ordinary person / can support / other people.',jp:'普通の人は / 支援できます / ほかの人々を'},{en:'One student / rode / a bicycle / to the shelter.',jp:'1人の生徒は / 乗りました / 自転車に / 避難所へ'},{en:'During the crisis, / I caught / a child.',jp:'危機の間 / 私は受け止めました / 子どもを'},{en:'Shortly, / we started / a support program.',jp:'まもなく / 私たちは始めました / 支援プログラムを'},{en:'People exchange / news / at the shelter.',jp:'人々は交換します / 知らせを / 避難所で'},{en:'We work / to support / people.',jp:'私たちは取り組みます / 支援するために / 人々を'},{en:'The program / can bring / people / together.',jp:'そのプログラムは / 団結させることができます / 人々を / いっしょに'},{en:'A bicycle can be / useful / in a crisis.',jp:'自転車は〜のことがあります / 役に立つ / 危機のときに'},{en:'The crisis is / no longer / a problem / for our town.',jp:'その危機は〜ではありません / もはや / 問題 / 私たちの町にとって'},{en:'We continue / the exchange program.',jp:'私たちは続けます / 交流プログラムを'},{en:'I think / ordinary people can bring / a town / together.',jp:'私は思います / 普通の人々が団結させられると / 町を / いっしょに'}],
questions:[{prompt:'1. 何について突然の知らせを聞きますか。本文から英語で答えなさい。',answer:'a crisis',evidence:'We hear sudden news about a crisis.',evidenceJp:'私たちは危機について突然の知らせを聞きます。',reason:'about の後ろが a crisis です。'},{prompt:'2. 生徒は何に乗って避難所へ行きましたか。本文から英語で答えなさい。',answer:'a bicycle',evidence:'One student rode a bicycle to the shelter.',evidenceJp:'1人の生徒は自転車に乗って避難所へ行きました。',reason:'rode の目的語が a bicycle です。'},{prompt:'3. 危機の間、誰を受け止めましたか。本文から英語で答えなさい。',answer:'a child',evidence:'During the crisis, I caught a child.',evidenceJp:'危機の間、私は子どもを受け止めました。',reason:'caught の目的語が a child です。'},{prompt:'4. プログラムは人々をどうすることができますか。本文から英語で答えなさい。',answer:'bring people together',evidence:'The program can bring people together.',evidenceJp:'そのプログラムは人々を団結させることができます。',reason:'can の後ろが bring people together です。'},{prompt:'5. 何がもはや町の問題ではありませんか。本文から英語で答えなさい。',answer:'the crisis',evidence:'The crisis is no longer a problem for our town.',evidenceJp:'その危機はもはや私たちの町の問題ではありません。',reason:'no longer a problem の主語が The crisis です。'}],
allowedWords:[['support / exchange / ride-rode / crisis / bicycle / catch-caught-caught / sudden / news / ordinary / be caught in ~ / shortly / work / bring A together / program / no longer ~','Unit 4 Read and Think2: v7 canonical Sheet IDs 1903-1917'],['hear / person / can / other / people / student / shelter / during / child / start-started / at / useful / problem / town / continue / think / together','Unit0-4-3/G1-G2 cumulative']],
auditNote:'最新v7正本Unit4 Read and Think2（Sheet ID1903〜1917）を直接照合。support / exchange / rode / crisis / bicycle / caught / sudden / news / ordinary / shortly / work / bring A together / program / no longerを、危機後の支援プログラムに統合。Unit5のbe born / leader / non-violence / human rights等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
