'use strict';
const fs=require('fs');
const vocab=JSON.parse(fs.readFileSync('V11_BATCH10_VOCAB_CHRONOLOGY_REPORT.json','utf8'));
const grammar=JSON.parse(fs.readFileSync('V11_BATCH10_GRAMMAR_CHRONOLOGY_REPORT.json','utf8'));
function countWords(rows){const m=new Map();for(const r of rows||[]){const w=String(r.word||'').toLowerCase();if(!w)continue;const k=[w,r.book||r.textbook||'',r.grade||'',r.section||''].join('|');const x=m.get(k)||{word:w,book:r.book||r.textbook||'',grade:String(r.grade||''),section:r.section||'',occurrences:0,samples:[]};x.occurrences++;if(x.samples.length<3)x.samples.push({id:r.id,where:r.where});m.set(k,x)}return [...m.values()].sort((a,b)=>b.occurrences-a.occurrences||a.word.localeCompare(b.word));}
function uniqueWordSummary(rows){const m=new Map();for(const r of rows||[]){const w=String(r.word||'').toLowerCase();if(!w)continue;const x=m.get(w)||{word:w,occurrences:0,contexts:new Set(),intros:new Set()};x.occurrences++;x.contexts.add(`${r.book||r.textbook||''}|${r.grade||''}|${r.section||''}`);if(r.intro)x.intros.add(JSON.stringify(r.intro));m.set(w,x)}return [...m.values()].map(x=>({word:x.word,occurrences:x.occurrences,contexts:[...x.contexts],intros:[...x.intros].map(s=>JSON.parse(s))})).sort((a,b)=>b.occurrences-a.occurrences||a.word.localeCompare(b.word));}
const unresolved=Array.isArray(vocab.unresolved)?vocab.unresolved:[];
const future=Array.isArray(vocab.future)?vocab.future:[];
const gu=Array.isArray(grammar.unresolved)?grammar.unresolved:[];
const grammarByFeature={};for(const r of gu){const k=r.feature||'UNKNOWN';const x=grammarByFeature[k]||(grammarByFeature[k]={feature:k,occurrences:0,contexts:[],sampleMatches:[]});x.occurrences+=Number(r.occurrences||0);x.contexts.push({textbook:r.textbook,grade:r.grade,section:r.section,occurrences:r.occurrences,evidenceStatus:r.evidenceStatus});for(const s of r.samples||[])if(x.sampleMatches.length<8)x.sampleMatches.push(s.match||s.text)}
const out={generatedAt:new Date().toISOString(),vocab:{unregisteredOccurrences:vocab.unregisteredOccurrences,unregisteredUniqueWords:uniqueWordSummary(unresolved).length,futureOccurrences:vocab.futureVocabLeakOccurrences,futureUniqueWords:uniqueWordSummary(future).length,unregisteredTop:uniqueWordSummary(unresolved).slice(0,500),futureTop:uniqueWordSummary(future).slice(0,500),unregisteredBySectionTop:countWords(unresolved).slice(0,800),futureBySectionTop:countWords(future).slice(0,800)},grammar:{unresolvedOccurrences:grammar.unresolvedOccurrences,unresolvedGroups:gu.length,byFeature:Object.values(grammarByFeature).sort((a,b)=>b.occurrences-a.occurrences),groups:gu}};
fs.writeFileSync('V11_BATCH10_CHRONOLOGY_DIAGNOSTIC.json',JSON.stringify(out,null,2)+'\n');
console.log(`B10 diagnostic vocab unregistered ${out.vocab.unregisteredOccurrences} / unique ${out.vocab.unregisteredUniqueWords}; future ${out.vocab.futureOccurrences} / unique ${out.vocab.futureUniqueWords}; grammar ${out.grammar.unresolvedOccurrences} in ${out.grammar.unresolvedGroups} groups`);
