(function buildV11Batch09G1Drafts(){
'use strict';
const BATCH='V11-B09-G1-DRAFT-20260829',SS='サンシャイン',NH='ニューホライズン';
function words(s){return (String(s||'').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]);}
function q(type,prompt,answer,evidence,evidenceJp,reason){return {questionType:type,prompt,answer,evidence,evidenceJp,reason};}
function build(o){
 const sentences=o.rows.map(r=>r[0]),slashRows=o.rows.map(r=>({en:r[0],jp:r[1]})),fullTranslation=o.rows.map(r=>r[1]).join('');
 const wc=words(sentences.join(' ')).length,n=sentences.length,ix=x=>Math.max(0,Math.min(n-1,x)),ev=i=>sentences[ix(i)],jp=i=>slashRows[ix(i)].jp;
 const questions=[q('GIST',`「${o.title}」で最初に問題になったことは何ですか。`,jp(0),ev(0),jp(0),'冒頭に中心となる状況が示されています。'),q('DETAIL','問題を確かめるために行ったことを答えなさい。',jp(3),ev(3),jp(3),'本文中の確認行動が根拠です。'),q('REASON','最初の考えをそのまま使わなかったのはなぜですか。',jp(4),ev(4),jp(4),'判断を見直す理由が示されています。'),q('CONTENT_MATCH','その後に取った行動として本文に合う内容を答えなさい。',jp(6),ev(6),jp(6),'解決へ向けた行動が直接書かれています。'),q('GIST','最後に分かったことを答えなさい。',jp(n-1),ev(n-1),jp(n-1),'最後の文が学びをまとめています。')];
 const questionSetB=[q('INFERENCE','本文全体から、判断するときに大切だと分かることは何ですか。',jp(n-2),ev(n-2),jp(n-2),'終盤の判断から読み取れます。'),q('SUMMARY_FILL','出来事の流れをまとめるとき、見直しの後に続く中心的な行動を答えなさい。',jp(5),ev(5),jp(5),'解決に向けた転換点です。'),q('DETAIL','新しく得られた手がかりを答えなさい。',jp(2),ev(2),jp(2),'本文中の具体的な手がかりです。'),q('CONTENT_MATCH','最終的な決定や変更として本文に合う内容を答えなさい。',jp(n-2),ev(n-2),jp(n-2),'終盤の決定に一致します。'),q('GIST',`「${o.title}」の最も大切な学びを答えなさい。`,jp(n-1),ev(n-1),jp(n-1),'結末が文章全体の学びを示しています。')];
 return Object.assign({grade:'1',genre:'reading',batch:BATCH,level:'STANDARD',targetWordBand:[90,125],wordCount:wc,sentences,fullTranslation,slashRows,questions,questionSetB,registered:false,questionStage:'BATCH09_DRAFT_HUMAN_BASE',authorReview:{reviewed:true,timelineCoherent:true,actorPerspectiveClear:true,causalLogicCoherent:true,translationNatural:true}},o,{rows:undefined});
}
const passages=[],add=o=>passages.push(build(o));
add({id:'V11-B09-G1-001',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Class Plant with Two Watering Notes',rows:[
['On Monday, Aya saw two notes beside the class plant.','月曜日、彩は教室の植物のそばに二枚のメモを見つけました。'],['One note said, “Water it every morning,” but the other said, “Do not water today.”','一枚には「毎朝水をやる」とあり、もう一枚には「今日は水をやらない」とありました。'],['Aya noticed that the second note had Monday’s date.','彩は二枚目のメモに月曜日の日付があることに気づきました。'],['She asked the student who cared for the plant on Friday.','彩は金曜日に植物の世話をした生徒に尋ねました。'],['He explained that the soil was still very wet after extra water on Sunday.','その生徒は、日曜日に多めに水をやったため土がまだとても湿っていると説明しました。'],['Aya touched only the top of the soil and saw that it was dark and wet.','彩は土の表面だけに触れ、色が濃く湿っていることを確かめました。'],['She followed the dated note and did not add water that morning.','彩は日付のあるメモに従い、その朝は水を足しませんでした。'],['After school, the class wrote a new note with both the date and the next watering time.','放課後、クラスは日付と次に水をやる時刻の両方を書いた新しいメモを作りました。'],['They learned that a newer note can change an old daily rule when the condition changes.','状況が変わったときは、新しいメモが以前の毎日の決まりを変えることがあると学びました。']
]});
add({id:'V11-B09-G1-002',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'A Lunch Box Left on the Wrong Shelf',rows:[
['After lunch, Ren found a blue lunch box on the sports shelf.','昼食後、蓮は運動用品の棚に青い弁当箱があるのを見つけました。'],['The shelf was not used for food, so he thought someone had moved it.','その棚は食べ物には使わないため、誰かが移したのだと思いました。'],['A white name sticker was hidden under a cloth band.','白い名前シールが布の帯の下に隠れていました。'],['Ren did not pull off the band and instead asked who had used the nearby table.','蓮は帯を外さず、近くの机を使った人を尋ねました。'],['Mao said she had put her lunch box there before carrying balls outside.','真央は、外へボールを運ぶ前にその場所へ弁当箱を置いたと言いました。'],['She described a blue box with a small star beside the handle.','真央は取っ手のそばに小さな星がある青い箱だと説明しました。'],['Ren checked the outside and found the same star.','蓮が外側を確認すると、同じ星が見つかりました。'],['He returned the box to Mao and moved a sign so food would not be placed on that shelf again.','蓮は真央に箱を返し、同じ棚に食べ物が置かれないよう表示を動かしました。'],['They solved the problem by using order and visible clues instead of opening the box.','二人は箱を開けず、出来事の順序と見える手がかりを使って問題を解決しました。']
]});
add({id:'V11-B09-G1-003',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Rainy-Day Walking Route',rows:[
['The class planned to walk from school to the community center on Friday.','クラスは金曜日に学校から地域センターまで歩く予定でした。'],['Their usual route crossed a small park near the river.','いつもの道は川の近くの小さな公園を通っていました。'],['On Friday morning, heavy rain made the park path muddy.','金曜日の朝、大雨で公園の道がぬかるみました。'],['Yuna checked the simple map and found a second route along the main street.','優奈は簡単な地図を確認し、大通りに沿う別の道を見つけました。'],['That route was a little longer, but it had a roof over part of the sidewalk.','その道は少し長いですが、歩道の一部に屋根がありました。'],['The teacher also checked that there was a safe crossing with a light.','先生は信号のある安全な横断場所があることも確認しました。'],['The class chose the main-street route and arrived without walking through deep water.','クラスは大通りの道を選び、深い水たまりを通らずに到着しました。'],['They marked the rainy-day route on the map for the next class.','次のクラスのために、雨の日の道を地図に印しました。'],['They learned that the best route can change with weather and road conditions.','天候や道路の状態によって最もよい道は変わると学びました。']
]});
add({id:'V11-B09-G1-004',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'Three Photos from the Same Club Day',rows:[
['Kenta had three photos from the same science club day, but their order was mixed.','健太は同じ科学部の日の写真を三枚持っていましたが、順番が混ざっていました。'],['One photo showed an empty table, one showed a model on the table, and one showed students cleaning.','一枚は空の机、一枚は机の上の模型、一枚は掃除する生徒を写していました。'],['At first, Kenta put the cleaning photo first because it was the brightest.','最初、健太は最も明るいという理由で掃除の写真を最初に置きました。'],['Then Emi noticed that the model box was still closed in the empty-table photo.','すると恵美は、空の机の写真では模型の箱がまだ閉じていることに気づきました。'],['In the second photo, the box was open and the finished model stood beside it.','二枚目では箱が開いており、完成した模型がその横に立っていました。'],['The cleaning photo showed the model already back inside the box.','掃除の写真では模型はすでに箱の中に戻されていました。'],['They used these changes to put the photos in a clear time order.','二人はこれらの変化を使って写真を明確な時間順に並べました。'],['Kenta wrote short captions explaining before, during, and after the activity.','健太は活動の前・途中・後を説明する短い文を書きました。'],['They learned that objects in a picture can show time order better than brightness or color.','写真の物の状態は、明るさや色より時間の順序をよく示すことがあると学びました。']
]});
add({id:'V11-B09-G1-005',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Library Book with Two Return Dates',rows:[
['Mina borrowed a library book and saw two return dates.','美奈は図書館の本を借り、二つの返却日を見つけました。'],['A card inside the book said May 12, but her new receipt said May 19.','本の中のカードには5月12日、新しいレシートには5月19日とありました。'],['She worried that she might return the book late.','美奈は返却が遅れるかもしれないと心配しました。'],['She checked the card and saw several old names and dates above May 12.','カードを見ると、5月12日の上にいくつもの古い名前と日付がありました。'],['The librarian explained that the card showed the previous reader’s return date.','司書は、そのカードは前に借りた人の返却日を示していると説明しました。'],['The receipt was printed when Mina borrowed the book that morning.','レシートは美奈がその朝に本を借りたとき印刷されたものでした。'],['Mina wrote May 19 in her school planner and kept the receipt.','美奈は学校の予定帳に5月19日と書き、レシートを保管しました。'],['The library later added a label telling readers to use the newest receipt date.','図書館は後で、最新のレシートの日付を使うよう示すラベルを付けました。'],['Mina learned to check when information was made before choosing between two dates.','二つの日付から選ぶときは、その情報がいつ作られたか確かめることを学びました。']
]});
add({id:'V11-B09-G1-006',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'A New Student and the Bus Stop Sign',rows:[
['A new student named Leo wanted to take the bus after school.','新しく来たレオは放課後にバスへ乗りたいと思っていました。'],['He found a sign near the gate, but two arrows pointed in different directions.','門の近くに表示を見つけましたが、二つの矢印が違う方向を指していました。'],['One arrow was for the city bus and the other was for the school bus.','一つは市バス、もう一つはスクールバス用でした。'],['Leo first followed the larger arrow without reading the small words.','レオは最初、小さな文字を読まずに大きい矢印をたどりました。'],['He reached the school-bus area, but his bus number was not there.','スクールバスの場所に着きましたが、自分のバス番号はありませんでした。'],['Aki showed him the words under each arrow and asked which bus he needed.','亜希は各矢印の下の文字を見せ、どのバスが必要か尋ねました。'],['Leo chose the city-bus arrow and found the correct stop across the street.','レオは市バスの矢印を選び、道路の向かいに正しい停留所を見つけました。'],['The class later added simple bus pictures beside both arrows.','クラスは後で両方の矢印のそばに簡単なバスの絵を加えました。'],['Leo learned that a direction is useful only when you know what the sign is directing you to.','案内は何を示しているか分かって初めて役立つとレオは学びました。']
]});
add({id:'V11-B09-G1-007',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Sports Bag Checklist',rows:[
['Before a soccer game, Saki checked the team bag with a short list.','サッカーの試合前、咲は短いリストでチームのかばんを確認しました。'],['The list had balls, towels, water, and a first-aid box.','リストにはボール、タオル、水、救急箱がありました。'],['Everything seemed ready until the coach asked for the pump.','コーチが空気入れを求めるまでは、すべて準備できているように見えました。'],['The pump was not on the list, so no one had checked for it.','空気入れはリストになかったため、誰も確認していませんでした。'],['Saki remembered using it beside the equipment shelf the day before.','咲は前日に用具棚のそばで使ったことを思い出しました。'],['She went back with another student and found it behind a box of cones.','別の生徒と戻り、コーンの箱の後ろに空気入れを見つけました。'],['They reached the field before the game started and filled the soft ball.','試合開始前にグラウンドへ戻り、空気の少ないボールに空気を入れました。'],['After the game, Saki added “pump” to the team checklist.','試合後、咲はチームの確認表に「空気入れ」を加えました。'],['The team learned that a checklist improves when a real problem shows what is missing.','実際の問題で足りない物が分かると、確認表をよりよくできるとチームは学びました。']
]});
add({id:'V11-B09-G1-008',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'Morning Announcements after a Room Change',rows:[
['The morning announcement said the music club would meet in Room 3.','朝の放送では音楽部は3号室に集まると言っていました。'],['Ten minutes later, a teacher moved the meeting because Room 3 had a broken light.','10分後、3号室の照明が壊れていたため先生が集会場所を変更しました。'],['A paper on the club board now said Room 5.','部活の掲示板の紙には今は5号室と書かれていました。'],['Some students had heard only the morning announcement and walked toward Room 3.','朝の放送だけを聞いた生徒たちは3号室へ向かいました。'],['Nana saw the new paper and checked the time written at the bottom.','奈々は新しい紙を見て、下に書かれた時刻を確認しました。'],['It had been posted after the announcement, so she knew it was the update.','それは放送の後に掲示されていたため、最新情報だと分かりました。'],['She told the students in the hall and sent them to Room 5.','奈々は廊下の生徒に知らせ、5号室へ案内しました。'],['The club added “updated” and the time to later room-change notices.','部活はその後の場所変更のお知らせに「変更」と時刻を加えることにしました。'],['They learned to check the newest message when plans change during the day.','一日の途中で予定が変わるときは最新の知らせを確認すると学びました。']
]});
add({id:'V11-B09-G1-009',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Pet Care Chart for a Weekend',rows:[
['The animal club made a weekend chart for feeding its rabbit.','飼育部はウサギのえさやりの週末表を作りました。'],['Ken was listed for Saturday morning, and Riku was listed for Sunday morning.','健は土曜の朝、陸は日曜の朝の担当でした。'],['On Saturday afternoon, Ken saw a second check mark beside Sunday.','土曜の午後、健は日曜の欄に二つ目の印があるのを見つけました。'],['He did not know whether someone had changed the plan or simply marked the wrong box.','誰かが予定を変えたのか、ただ違う欄に印を付けたのか分かりませんでした。'],['Ken called Riku before adding any more food.','健は追加のえさを入れる前に陸へ連絡しました。'],['Riku said he had visited early because his family would leave town on Sunday.','陸は日曜に家族で出かけるため早めに来たと言いました。'],['The two students wrote the real feeding time beside each check mark.','二人は各印のそばに実際のえさやり時刻を書きました。'],['They also asked another member to check the rabbit on Sunday morning without feeding it again.','日曜の朝は別の部員に、再びえさをやらずウサギの様子だけ見るよう頼みました。'],['They learned that a schedule is clearer when changes include both a name and a time.','変更に名前と時刻の両方があると予定表が分かりやすいと学びました。']
]});
add({id:'V11-B09-G1-010',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'A School Map with One Closed Stairway',rows:[
['Visitors used a school map to walk from the entrance to the library.','来校者は入口から図書室へ行くため学校の地図を使いました。'],['The shortest route used the east stairway.','最短の道は東階段を使うものでした。'],['On Tuesday, workers closed that stairway for repair.','火曜日、修理のため作業員がその階段を閉鎖しました。'],['The old map still showed the east stairway as the main route.','古い地図はまだ東階段を主な道として示していました。'],['Haru checked another stairway near the gym and walked the whole route once.','陽は体育館近くの別の階段を確認し、道を一度全部歩きました。'],['The second route took two more minutes but stayed inside the open area.','二つ目の道は2分多くかかりましたが、開いている場所だけを通れました。'],['He drew a temporary blue line on a copy of the map.','陽は地図の写しに一時的な青い線を描きました。'],['The office placed the new map beside the entrance until the repair ended.','事務室は修理が終わるまで新しい地図を入口に置きました。'],['Haru learned that a useful map must show current conditions, not only the shortest path.','役立つ地図は最短経路だけでなく現在の状況も示す必要があると陽は学びました。']
]});
add({id:'V11-B09-G1-011',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Club Poster Missing a Start Time',rows:[
['The art club made a bright poster for its Saturday workshop.','美術部は土曜日の体験会のため明るいポスターを作りました。'],['The poster showed the date, room, and things to bring.','ポスターには日付、部屋、持ち物が書かれていました。'],['After it was posted, two students asked what time the workshop would begin.','掲示後、二人の生徒が体験会は何時に始まるのか尋ねました。'],['The club members looked again and noticed that the start time was missing.','部員たちは見直し、開始時刻が抜けていることに気づきました。'],['One member remembered “ten,” but another remembered “ten thirty.”','一人は「10時」と覚え、別の一人は「10時半」と覚えていました。'],['They checked the teacher’s booking sheet before changing the poster.','ポスターを直す前に先生の予約表を確認しました。'],['The room was booked from ten thirty, so they added “10:30 a.m.” in large letters.','部屋は10時半から予約されていたため、大きな字で「午前10時30分」と加えました。'],['They also checked every other line against the booking sheet.','ほかのすべての項目も予約表と照らして確認しました。'],['The club learned that an attractive poster is not useful when one necessary fact is missing.','必要な情報が一つ欠けていると、魅力的なポスターでも役立たないと学びました。']
]});
add({id:'V11-B09-G1-012',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'Two Teams Sharing One Practice Space',rows:[
['The basketball team and dance team both needed the small gym on Wednesday.','バスケットボール部とダンス部はどちらも水曜日に小体育館が必要でした。'],['An old schedule gave the whole afternoon to basketball.','古い予定表では午後全部がバスケットボール部になっていました。'],['However, the dance team had a performance on Thursday and needed one final practice.','しかしダンス部は木曜日に発表があり、最後の練習が必要でした。'],['The two captains checked when each group really needed the full floor.','二人の部長は、それぞれが本当に全面を必要とする時刻を確認しました。'],['Basketball needed the baskets only after four, while dance could finish by four.','バスケットボールは4時以降だけゴールが必要で、ダンスは4時までに終えられました。'],['They divided the afternoon instead of arguing about the old schedule.','二人は古い予定表について争う代わりに午後を分けました。'],['Dance practiced first, and basketball started when the dancers left.','最初にダンス部が練習し、ダンス部が出た後にバスケットボール部が始めました。'],['Both teams finished the work they had planned.','両方のチームが予定していた練習を終えました。'],['They learned that sharing works better when people compare actual needs, not only old reservations.','以前の予約だけでなく実際の必要を比べると、よりよく共有できると学びました。']
]});
add({id:'V11-B09-G1-013',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Lost Umbrella Color Record',rows:[
['After a rainy morning, five umbrellas remained near the classroom door.','雨の朝の後、教室のドアの近くに五本の傘が残っていました。'],['Tomo was looking for a dark blue umbrella.','智は濃い青色の傘を探していました。'],['Two of the umbrellas looked dark blue under the hall light.','廊下の照明では二本が濃い青に見えました。'],['Instead of taking one quickly, Tomo checked the class lost-item record.','智はすぐ一本を取らず、クラスの落とし物記録を確認しました。'],['The record said his umbrella had a white handle and a small red thread on the strap.','記録には、智の傘は白い持ち手で、留めひもに小さな赤い糸があると書かれていました。'],['Only one of the two blue umbrellas had both details.','青い二本のうち両方の特徴があるのは一本だけでした。'],['Tomo asked the teacher to check the record with him before he took it.','智は持っていく前に先生にも一緒に記録を確認してもらいました。'],['The other umbrella stayed in the lost-item area for its owner.','もう一本は持ち主のため落とし物置き場に残しました。'],['Tomo learned that color alone may not be enough when several items look similar.','似た物がいくつかあるときは色だけでは十分でないことがあると学びました。']
]});
add({id:'V11-B09-G1-014',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'A Recipe Card for Six Instead of Three',rows:[
['The cooking group found a recipe card for three people.','調理グループは三人分のレシピカードを見つけました。'],['Six students wanted to eat the dish, so the card was too small for their group.','六人で料理を食べたかったため、そのカードの分量では足りませんでした。'],['The card used two eggs, one cup of milk, and one small onion.','カードには卵二個、牛乳一カップ、小さな玉ねぎ一個とありました。'],['At first, one student doubled only the eggs because they were listed first.','最初、一人の生徒は最初に書かれているという理由で卵だけを二倍にしました。'],['Miu pointed out that every main amount had to change for six people.','美羽は六人分にするには主な量をすべて変える必要があると指摘しました。'],['They wrote a second column with four eggs, two cups of milk, and two onions.','四個の卵、二カップの牛乳、二個の玉ねぎを二列目に書きました。'],['The group checked each line before they started cooking.','グループは料理を始める前に各行を確認しました。'],['There was enough food for all six students with no missing ingredient.','足りない材料もなく六人全員に十分な料理ができました。'],['They learned that changing a recipe means changing all related amounts in the same way.','レシピを変えるときは関係する量を同じように変える必要があると学びました。']
]});
add({id:'V11-B09-G1-015',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Classroom Window Seat Survey',rows:[
['The class wanted to know whether students liked seats near the windows.','クラスは窓の近くの席が好まれているか知りたいと思いました。'],['Yui first asked only the six students already sitting by the windows.','結衣は最初、すでに窓側に座っている六人だけに尋ねました。'],['Five of them said they liked those seats.','そのうち五人がその席を好きだと言いました。'],['Yui was ready to say that almost everyone preferred the windows.','結衣はほとんど全員が窓側を好むと言おうとしました。'],['Then Koki said the survey had not included students from the center or door side.','すると光希が、その調査には中央やドア側の生徒が入っていないと言いました。'],['They asked students from every part of the room using the same question.','二人は教室の各場所の生徒に同じ質問をしました。'],['The second survey showed many different reasons for choosing seats.','二回目の調査では席を選ぶ理由がさまざまだと分かりました。'],['The class used the wider results when discussing the next seating plan.','クラスは次の席決めを話し合うとき、より広い結果を使いました。'],['Yui learned that a fair survey should not ask only the people most likely to agree.','公平な調査では賛成しそうな人だけに尋ねるべきではないと結衣は学びました。']
]});
add({id:'V11-B09-G1-016',textbook:NH,section:'Unit 10-2',sourceSectionBaselineId:'V10-NH-G1-U10-2-001',title:'A Message Sent before the Plan Changed',rows:[
['At noon, Ko sent his friend a message saying club practice would end at five.','正午、航は友達に部活が5時に終わるというメッセージを送りました。'],['At three, the teacher shortened practice because a storm was coming.','3時、嵐が近づいていたため先生は練習を短くしました。'],['The new ending time was four thirty.','新しい終了時刻は4時30分でした。'],['Ko’s friend read only the noon message and planned to meet him at five.','航の友達は正午のメッセージだけを読み、5時に会う予定を立てました。'],['Ko noticed that his first message was now old information.','航は最初のメッセージがもう古い情報だと気づきました。'],['He sent a second message beginning with “Plan changed” and wrote the new time.','航は「予定変更」と最初に書き、新しい時刻を記した二通目を送りました。'],['His friend saw the update before leaving home.','友達は家を出る前にその変更を見ました。'],['They met at four thirty without waiting outside in the storm.','二人は嵐の中で外に待つことなく4時30分に会えました。'],['Ko learned that a changed plan needs a clear new message, not silence after an old one.','予定が変わったら古い連絡の後に黙るのではなく明確な新しい連絡が必要だと航は学びました。']
]});
add({id:'V11-B09-G1-017',textbook:SS,section:'PROGRAM 10-2',sourceSectionBaselineId:'V10-SS-G1-P10-2-001',title:'The Music Practice Record with One Empty Day',rows:[
['Rina kept a seven-day record of her piano practice.','里奈は七日間のピアノ練習記録を付けていました。'],['Six boxes had times, but Wednesday’s box was empty.','六つの欄には時刻がありましたが、水曜日の欄だけ空いていました。'],['She first thought she had forgotten to practice that day.','里奈は最初、その日は練習を忘れたと思いました。'],['Then she remembered taking her music notebook to her grandmother’s house on Wednesday.','その後、水曜日に音楽ノートを祖母の家へ持って行ったことを思い出しました。'],['A small note on the next page said, “Wednesday, twenty minutes at Grandma’s.”','次のページの小さなメモには「水曜日、祖母の家で20分」とありました。'],['Rina had practiced, but she had written the time in the wrong place.','里奈は練習していましたが、時刻を違う場所に書いていたのです。'],['She moved the information into Wednesday’s box and added the place beside it.','その情報を水曜日の欄へ移し、場所も横に加えました。'],['Her weekly total then matched the time in her lesson notebook.','すると一週間の合計がレッスンノートの時間と一致しました。'],['Rina learned that an empty record can mean missing information, not always a missing action.','記録の空欄は、行動がなかったのではなく情報が抜けている場合もあると学びました。']
]});
window.V11_BATCH09_G1_DRAFTS=passages;
window.V11_BATCH09_G1_DRAFT_SUMMARY={batch:BATCH,count:passages.length,registered:false,minWords:Math.min(...passages.map(p=>p.wordCount)),maxWords:Math.max(...passages.map(p=>p.wordCount))};
})();