'use strict';
const fs=require('fs');
const {chromium,webkit}=require('playwright');
const URL=process.env.V11_PREVIEW_URL||'https://yo666ha-boop.github.io/reading-app/v11-preview/';
const EXPECTED=process.env.EXPECTED_SOURCE_SHA||'';
const cases=[
 {textbook:'サンシャイン',grade:'3',major:'PROGRAM 7',section:'PROGRAM 7-3',words:'150-199',min:10},
 {textbook:'ニューホライズン',grade:'3',major:'Unit 6',section:'Unit 6-4',words:'200-249',min:8},
 {textbook:'サンシャイン',grade:'2',major:'PROGRAM 8',section:'PROGRAM 8-3',words:'100-149',min:5},
 {textbook:'ニューホライズン',grade:'1',major:'Unit 10',section:'Unit 10-2',words:'100-149',min:5}
];
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
async function waitSource(request){const end=Date.now()+240000;let last='';while(Date.now()<end){try{const r=await request.get(URL+'PREVIEW_SOURCE.txt?ts='+Date.now(),{timeout:15000});if(r.ok()){last=await r.text();if(!EXPECTED||last.includes('source_sha='+EXPECTED))return last}}catch(_){}await new Promise(r=>setTimeout(r,4000))}throw Error('preview source timeout '+EXPECTED+' last='+last)}
async function setLabel(page,id,label){await page.selectOption('#'+id,{label}).catch(()=>page.selectOption('#'+id,label));await page.waitForTimeout(140)}
async function settle(page){await page.waitForFunction(()=>window.V11_MULTI_PASSAGE_STATE&&window.V11_MULTI_PASSAGE_STATE.extraPassages>=650&&document.getElementById('v11PassageVariant')&&document.getElementById('v11WordCountFilter')&&document.getElementById('v11NextPassageBtn'),null,{timeout:120000});await page.waitForTimeout(300)}
async function snap(page){return page.evaluate(()=>{const p=window.choose&&window.choose();const sel=document.getElementById('v11PassageVariant');const meta=(window.metaFor&&p)?window.metaFor(p.section):{};return{id:p&&p.id,section:p&&p.section,first:p&&p.sentences&&p.sentences[0],translation:p&&p.fullTranslation,words:window.V11_MULTI_PASSAGE_UI_STATE&&window.V11_MULTI_PASSAGE_UI_STATE.selectedWords,optionCount:sel?sel.options.length:0,value:sel&&sel.value,labels:sel?Array.from(sel.options).map(o=>o.textContent):[],body:document.getElementById('passage')&&document.getElementById('passage').textContent,slash:document.getElementById('slash')&&document.getElementById('slash').textContent,a:p&&p.questions||[],b:p&&Array.isArray(p.questionSetB)?p.questionSetB:(meta&&meta.questionSetB)||[]}})}
function inBand(n,b){if(b==='100-149')return n>=100&&n<=149;if(b==='150-199')return n>=150&&n<=199;if(b==='200-249')return n>=200&&n<=249;return true}
async function engine(type,name){const browser=await type.launch();const page=await browser.newPage({viewport:name==='webkit'?{width:390,height:844}:{width:1440,height:1000}});const failures=[],results=[];page.on('pageerror',e=>failures.push(name+' pageerror '+e));await page.goto(URL+'?audit='+Date.now(),{waitUntil:'domcontentloaded',timeout:120000});await settle(page);
 for(const c of cases){await setLabel(page,'textbook',c.textbook);await setLabel(page,'grade',c.grade);await setLabel(page,'major',c.major);await setLabel(page,'section',c.section);await page.selectOption('#pattern','all');await page.selectOption('#v11WordCountFilter',c.words);await page.waitForTimeout(300);let a=await snap(page);if(a.optionCount<c.min)failures.push(`${name} ${c.section} ${c.words}: candidates=${a.optionCount}<${c.min}`);if(!a.labels.every(x=>/words｜/.test(x)))failures.push(`${name} ${c.section}: word count missing from labels`);if(!inBand(a.words,c.words))failures.push(`${name} ${c.section}: ${a.words} outside ${c.words}`);if(!a.first||!norm(a.body).includes(norm(a.first)))failures.push(`${name} ${c.section}: selected body not rendered`);const first=a;
  if(a.optionCount>1){await page.click('#v11NextPassageBtn');await page.waitForTimeout(220);a=await snap(page);if(a.id===first.id)failures.push(`${name} ${c.section}: Next did not change id`);if(norm(a.body)===norm(first.body))failures.push(`${name} ${c.section}: Next did not change body`);if(a.value===first.value)failures.push(`${name} ${c.section}: selector did not move with Next`)}
  const options=await page.locator('#v11PassageVariant option').evaluateAll(os=>os.map(o=>({value:o.value,label:o.textContent})));const extra=options.find(o=>/^追加(?:\d+)?\s*｜/.test(o.label));if(extra){await page.selectOption('#v11PassageVariant',extra.value);await page.waitForTimeout(220);const e=await snap(page);if(e.id!==extra.value)failures.push(`${name} ${c.section}: direct selection failed`);if(e.a.length!==5)failures.push(`${name} ${extra.value}: A=${e.a.length}`);if(e.b.length!==5)failures.push(`${name} ${extra.value}: B=${e.b.length}`);if(!norm(e.body).includes(norm(e.translation)))failures.push(`${name} ${extra.value}: translation not synchronized`);if(!e.slash)failures.push(`${name} ${extra.value}: slash missing`)}
  results.push({...c,firstId:first.id,nextId:a.id,optionCount:a.optionCount,selectedWords:a.words});
 }
 await setLabel(page,'textbook','サンシャイン');await setLabel(page,'grade','3');await setLabel(page,'major','PROGRAM 7');await setLabel(page,'section','PROGRAM 7-3');await page.selectOption('#v11WordCountFilter','all');await page.waitForTimeout(250);const labels=await page.locator('#v11PassageVariant option').allTextContents();const sections=[...new Set(labels.map(x=>(x.split('｜')[1]||'').trim()).filter(Boolean))];if(!(sections.length===1&&sections[0]==='PROGRAM 7-3'))failures.push(name+' exact-section candidates leaked: '+sections.join(','));if(await page.locator('#v11WordSupportBtn').count()!==1)failures.push(name+' word support button missing');const state=await page.evaluate(()=>({multi:window.V11_MULTI_PASSAGE_STATE,ui:window.V11_MULTI_PASSAGE_UI_STATE}));await browser.close();return{name,results,rangeSections:sections,state,failures,pass:failures.length===0}}
(async()=>{const b=await chromium.launch();const ctx=await b.newContext();const src=await waitSource(ctx.request);await b.close();const cr=await engine(chromium,'chromium');const wk=await engine(webkit,'webkit');const report={previewUrl:URL,expectedSourceSha:EXPECTED,previewSource:src.trim(),chromium:cr,webkit:wk,finalPass:cr.pass&&wk.pass,createdAt:new Date().toISOString()};fs.writeFileSync('V11_PREVIEW_MULTI_PASSAGE_UI_AUDIT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.finalPass)process.exit(1)})().catch(e=>{const r={previewUrl:URL,expectedSourceSha:EXPECTED,fatal:String(e&&e.stack||e),finalPass:false,createdAt:new Date().toISOString()};fs.writeFileSync('V11_PREVIEW_MULTI_PASSAGE_UI_AUDIT.json',JSON.stringify(r,null,2));console.error(r.fatal);process.exit(1)});
