'use strict';
const fs=require('fs');
const files=['v11_batch15_g1_body_draft.json','v11_batch15_g2_body_draft.json','v11_batch15_g3_body_draft.json'];
const G={
used:'使った',using:'使うこと',track:'走路',robotics:'ロボット工学',market:'市場',customers:'客',customer:'客',planetarium:'プラネタリウム',delivery:'配達',departure:'出発',pair:'組',stall:'屋台',stalls:'屋台',plates:'皿',refrigerator:'冷蔵庫',seventy:'70',sink:'流し台',cart:'ワゴン',clip:'クリップ',concentration:'集中',digital:'デジタルの',direct:'直接の',leader:'リーダー',learned:'学んだ',math:'数学',pond:'池',preferred:'好まれた',seaside:'海辺',shuttle:'送迎車',someone:'だれか',sorting:'分類',tab:'タブ',tide:'潮',tomatoes:'トマト',tomato:'トマト',workshop:'作業場',average:'平均',baker:'パン職人',beach:'海辺',boxes:'箱',column:'欄',craft:'工作',crop:'作物',directions:'道順',easy:'簡単な',examined:'調べた',exhibition:'展示',inland:'内陸の',interactive:'対話型の',lab:'実験室',lighthouse:'灯台',mobility:'移動しやすさ',orange:'オレンジ色の',pantry:'食品庫',photo:'写真',players:'選手たち',produced:'作った',reminder:'注意書き',reusable:'再利用できる',sale:'販売',seating:'座席',solved:'解決した',stream:'小川',talk:'話',tent:'テント',tray:'トレー',weekday:'平日',acceptable:'許容できる',additional:'追加の',air:'空気',answer:'答え',arrive:'到着する',board:'掲示板',caught:'捕まえた',cans:'缶',cheerful:'明るい',cleaners:'清掃員',clear:'明確な',clues:'手がかり',eggs:'卵',environmental:'環境の',festival:'祭り',fresh:'新鮮な',guessing:'推測',indoor:'屋内の',letter:'手紙',message:'伝言',mixed:'混ぜた',past:'過去の',rabbit:'ウサギ',reach:'届く',realize:'気づく',redesign:'設計し直す',sheets:'用紙',signal:'合図',smoothly:'円滑に',steadily:'着実に',switch:'スイッチ',tape:'テープ',target:'目標',tickets:'券',try:'試す',unchanged:'変わらない',unanswered:'未回答の',unclear:'不明確な',dangerous:'危険な',range:'範囲',existing:'既存の',comfortably:'快適に',margin:'余白',orientation:'案内',independently:'自力で',familiar:'なじみのある',soon:'まもなく',searching:'探すこと',keep:'保つ',calling:'呼ぶこと',joke:'冗談',lunchtime:'昼食時間',chosen:'選ばれた',crowding:'混雑',two:'2',blinks:'点滅',rehearsal:'リハーサル',pairs:'組',cleaner:'清掃員',ticket:'券',sheet:'用紙',plate:'皿',direction:'方向',player:'選手',box:'箱',tomato:'トマト',crop:'作物',craft:'工作',workshops:'作業場',photos:'写真',markets:'市場',streams:'小川',tents:'テント',trays:'トレー',tabs:'タブ',sinks:'流し台',carts:'ワゴン',clips:'クリップ',signals:'合図',messages:'伝言',answers:'答え',festivals:'祭り',targets:'目標',ranges:'範囲',departures:'出発',deliveries:'配達',weekdays:'平日',lighthouses:'灯台',ponds:'池',beaches:'海辺',columns:'欄',labs:'実験室',exhibitions:'展示',averages:'平均',leaders:'リーダー',customers:'客',
aoi:'アオイ（人名）',yuki:'ユキ（人名）',ken:'ケン（人名）',maya:'マヤ（人名）',emi:'エミ（人名）',hina:'ヒナ（人名）',miku:'ミク（人名）',rina:'リナ（人名）',yuma:'ユウマ（人名）',haruto:'ハルト（人名）',mei:'メイ（人名）',kenta:'ケンタ（人名）',daiki:'ダイキ（人名）',akari:'アカリ（人名）'
};
function norm(s){return String(s||'').trim().toLowerCase()}
let added=0;const byWord={};
for(const file of files){const j=JSON.parse(fs.readFileSync(file,'utf8'));for(const p of j.passages||[]){p.notes=p.notes||[];const have=new Set(p.notes.filter(n=>n&&n.kind==='unlearned_local_required').map(n=>norm(n.english)));const words=new Set((String(p.body||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(norm));for(const w of words){if(!G[w]||have.has(w))continue;p.notes.push({kind:'unlearned_local_required',english:w,japanese:G[w],scope:'passage-only-unlearned',basis:'Batch15 chronology R5: explicit human-curated Japanese gloss for a remaining necessary passage-local word; not an English-as-Japanese placeholder.'});have.add(w);added++;byWord[w]=(byWord[w]||0)+1;}}j.status=String(j.status||'').replace(/_CURATED_GLOSS_R5$/,'')+'_CURATED_GLOSS_R5';fs.writeFileSync(file,JSON.stringify(j,null,2)+'\n');}
fs.writeFileSync('V11_BATCH15_CURATED_GLOSS_R5_REPORT.json',JSON.stringify({generatedAt:new Date().toISOString(),dictionaryWords:Object.keys(G).length,notesAdded:added,passageWordAdds:byWord},null,2)+'\n');
console.log(`Batch15 curated R5 dictionary=${Object.keys(G).length} notesAdded=${added}`);
