const fs=require('fs');
const path=require('path');
const {chromium,webkit,devices}=require('playwright');
function assert(c,m){if(!c)throw Error(m)}
const norm=s=>String(s||'').normalize('NFKC').replace(/[『』]/g,m=>m==='『'?'「':'」').replace(/[“”]/g,'"').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
async function open(type){
  const browser=type==='chromium'?await chromium.launch({headless:true}):await webkit.launch({headless:true});
  const context=type==='chromium'?await browser.newContext({viewport:{width:1366,height:900}}):await browser.newContext({...devices['iPhone 13']});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push('pageerror:'+String(e)));page.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});
  const r=await page.goto('http://127.0.0.1:8000/index.html?b12candidate='+type+'-'+Date.now(),{waitUntil:'domcontentloaded',timeout:90000});assert(r&&r.ok(),type+' HTTP');
  await page.waitForFunction(()=>window.V10_RUNTIME_LOAD_PROGRESS==='complete',{timeout:120000});
  await page.waitForFunction(()=>window.V11_BATCH11_LOADED===true,{timeout:120000});
  const before=await page.evaluate(()=>({extra:Object.values(window.V11_EXTRA_PASSAGES||{}).flat().length,b11:window.V11_BATCH11_STATE}));
  assert(before.extra===550&&before.b11&&before.b11.registered===true&&before.b11.totalWithBaseline===718,type+' persistent before '+JSON.stringify(before));
  await page.addScriptTag({path:path.resolve('v11_batch12_runtime_bundle.js')});
  await page.addScriptTag({path:path.resolve('v11_batch12_register.js')});
  await page.waitForFunction(()=>window.V11_BATCH12_LOADED===true,{timeout:30000});
  const st=await page.evaluate(()=>({state:window.V11_BATCH12_STATE,extra:Object.values(window.V11_EXTRA_PASSAGES||{}).flat().length,b12:(window.V11_BATCH12_PASSAGES||[]).length}));
  assert(st.extra===600&&st.b12===50&&st.state&&st.state.registered===true&&st.state.totalWithBaseline===768,type+' candidate totals '+JSON.stringify(st));
  return{browser,context,page,errors,before,st};
}
async function setPassage(page,id){
  const x=await page.evaluate(id=>window.V11_BATCH12_PASSAGES.find(p=>p.id===id),id);assert(x,id+' missing');
  await page.selectOption('#textbook',x.textbook);await page.selectOption('#grade',String(x.grade));await page.waitForTimeout(20);
  const majors=await page.locator('#major option').evaluateAll(os=>os.map(o=>o.value));let found=false;
  for(const m of majors){await page.selectOption('#major',m);await page.waitForTimeout(10);const secs=await page.locator('#section option').evaluateAll(os=>os.map(o=>o.value));if(secs.includes(x.section)){found=true;break}}
  assert(found,id+' section '+x.section);await page.selectOption('#section',x.section);await page.waitForTimeout(10);
  const idx=await page.evaluate(id=>{const p=window.V11_BATCH12_PASSAGES.find(p=>p.id===id),key=[p.textbook,String(p.grade),p.section].join('|'),a=window.V11_EXTRA_PASSAGES[key]||[],j=a.findIndex(y=>y.id===id);return j<0?-1:j+1},id);assert(idx>=1,id+' variant');
  await page.selectOption('#v11PassageVariant',String(idx));await page.evaluate(()=>window.render());await page.waitForTimeout(10);assert((await page.evaluate(()=>window.choose().id))===id,id+' choose');
}
async function engine(type){const c=await open(type);try{const{page,errors}=c,ids=await page.evaluate(()=>window.V11_BATCH12_PASSAGES.map(x=>x.id));let overflow=0,normalNotes=0,supportNotes=0;for(const id of ids){await setPassage(page,id);assert((await page.locator('#questions .q').count())===5,id+' A');const b=page.locator('#altSetBtn');if(await b.count()){await b.click();await page.waitForTimeout(5);assert((await page.locator('#questions .q').count())===5,id+' B')}
    const ok=await page.evaluate(()=>{const p=window.choose(),qs=[...(p.questions||[]),...(p.questionSetB||[])],req=p.notes||[],sup=p.supportNotes||[];const n=s=>String(s||'').normalize('NFKC').replace(/[『』]/g,m=>m==='『'?'「':'」').replace(/[“”]/g,'"').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();const body=String(p.body||((p.sentences||[]).join(' '))),jp=String(p.fullTranslation||'');const has=(h,x)=>n(h).includes(n(x));const ev=q=>{const es=Array.isArray(q.evidence)?q.evidence:[q.evidence],js=Array.isArray(q.evidenceJp)?q.evidenceJp:[q.evidenceJp];return es.length===js.length&&es.length>0&&es.every((e,i)=>has(body,e)&&(has(jp,js[i])||(p.slashRows||[]).some(r=>has(r.jp,js[i]))))};const r=new Set(req.map(x=>n(x&&x.english).toLowerCase()));return{q:qs.length===10&&qs.every(q=>q.prompt&&q.answer!=null&&q.reason&&ev(q)),tr:(p.slashRows||[]).every(row=>has(jp,row.jp)),notes:req.every(x=>x&&x.english&&x.japanese&&!/placeholder|temporary|最終注整理対象/i.test(String(x.japanese))),support:sup.length>=4&&sup.length<=16&&sup.every(x=>x&&x.english&&x.japanese&&!r.has(n(x.english).toLowerCase())),nc:req.length,sc:sup.length};});
    assert(ok.q&&ok.tr&&ok.notes&&ok.support,id+' content '+JSON.stringify(ok));normalNotes+=ok.nc;supportNotes+=ok.sc;if(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+2))overflow++}
  assert(overflow===0,type+' overflow');assert(errors.length===0,type+' errors '+errors.join('|'));return{passages:ids.length,overflow,errors:errors.length,normalNotes,supportNotes,total:c.st.state.totalWithBaseline}}finally{await c.context.close();await c.browser.close()}}
async function cross(){const c=await open('chromium');try{return await c.page.evaluate(()=>{const all=Object.values(window.V11_EXTRA_PASSAGES||{}).flat(),b12=window.V11_BATCH12_PASSAGES||[],ids=new Set(),dupIds=[],dupBodies=[],near=[],body=new Map();for(const p of all){if(ids.has(p.id))dupIds.push(p.id);ids.add(p.id);const t=String(p.body||((p.sentences||[]).join('\n')));if(body.has(t))dupBodies.push([body.get(t),p.id]);else body.set(t,p.id)}function j(a,b){a=new Set(a);b=new Set(b);let n=0;for(const x of a)if(b.has(x))n++;return n/(a.size+b.size-n||1)}for(const a of b12)for(const b of all){if(a.id===b.id||String(b.id).startsWith('V11-B12-'))continue;if(a.textbook!==b.textbook||String(a.grade)!==String(b.grade)||a.section!==b.section)continue;const sa=(a.slashRows||[]).map(x=>x.en),sb=(b.slashRows||[]).map(x=>x.en);const s=j(sa,sb);if(s>=.85)near.push({a:a.id,b:b.id,score:s})}return{extra:all.length,b12:b12.length,dupIds,dupBodies,near,pass:all.length===600&&!dupIds.length&&!dupBodies.length&&!near.length}})}finally{await c.context.close();await c.browser.close()}}
async function print(){const c=await open('chromium');try{const{page}=c,reps=await page.evaluate(()=>{const s=new Set(),o=[];for(const p of window.V11_BATCH12_PASSAGES){const k=p.textbook+'|'+p.grade+'|'+p.section;if(!s.has(k)){s.add(k);o.push(p.id)}}return o});fs.mkdirSync('/tmp/v11-b12-candidate-a4',{recursive:true});let files=0;for(const id of reps){await setPassage(page,id);await page.emulateMedia({media:'print'});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+3)),id+' print overflow');for(const kind of ['teacher','student']){if(kind==='student')await page.evaluate(()=>{const st=document.createElement('style');st.id='studentPrint';st.textContent='@media print{#answers,#audit{display:none!important}}';document.head.appendChild(st)});const f='/tmp/v11-b12-candidate-a4/'+id+'-'+kind+'.pdf';await page.pdf({path:f,format:'A4',printBackground:true});assert(fs.statSync(f).size>5000,id+' '+kind+' small');files++;if(kind==='student')await page.evaluate(()=>document.getElementById('studentPrint')?.remove())}await page.emulateMedia({media:'screen'})}return{representativeSections:reps.length,files}}finally{await c.context.close();await c.browser.close()}}
(async()=>{const pc=await engine('chromium'),iphone=await engine('webkit'),cr=await cross();assert(cr.pass,'cross '+JSON.stringify(cr));const a4=await print();const out={generatedAt:new Date().toISOString(),persistentBefore:718,candidateTotal:768,registered:false,candidateOnly:true,pc,iphone,cross:cr,a4,finalPass:true};fs.writeFileSync('V11_BATCH12_CANDIDATE_RUNTIME_AUDIT.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));console.log('V11_BATCH12_CANDIDATE_768_PASS')})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
