'use strict';
const fs=require('fs');
const {loadCanonicalV7}=require('./v10_v7_lexicon_loader');
const elementary=JSON.parse(fs.readFileSync('v10_elementary_vocab_allowlist.json','utf8'));
const ELEMENTARY=new Set((elementary.words||[]).map(x=>String(x).toLowerCase()));
const FUNCTION=new Set(`a an the i me my mine you your yours he him his she her hers it its we us our ours they them their theirs this that these those who whose whom which what when where why how am is are was were be been being do does did doing have has had having can cannot could may might must shall should will would not no yes and or but so if because as than to of in on at by for from with about into over under before after during while through up down out off again then there here also too very more most less least some any many much few little each every all both either neither another other same own one two first second third`.split(/\s+/));
const CONTRACTIONS=new Set(["i'm","you're","he's","she's","it's","we're","they're","let's","isn't","aren't","wasn't","weren't","don't","doesn't","didn't","can't","couldn't","won't","wouldn't","shouldn't","mustn't","i've","you've","we've","they've","hasn't","haven't","hadn't","i'll","you'll","he'll","she'll","we'll","they'll","i'd","you'd","he'd","she'd","we'd","they'd"]);
const IRREG=new Map(Object.entries({went:'go',gone:'go',came:'come',seen:'see',saw:'see',made:'make',took:'take',taken:'take',gave:'give',given:'give',wrote:'write',written:'write',read:'read',bought:'buy',brought:'bring',thought:'think',found:'find',knew:'know',known:'know',told:'tell',said:'say',spoke:'speak',spoken:'speak',ate:'eat',eaten:'eat',drank:'drink',drunk:'drink',ran:'run',swam:'swim',swum:'swim',became:'become',began:'begin',begun:'begin',left:'leave',felt:'feel',kept:'keep',met:'meet',sent:'send',built:'build',held:'hold',heard:'hear',lost:'lose',paid:'pay',put:'put',stood:'stand',understood:'understand',lying:'lie',dying:'die',tying:'tie'}));
const tok=s=>(String(s||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(x=>x.toLowerCase());
const uniq=a=>[...new Set(a.filter(Boolean))];
function bases(w){const o=[];if(w.endsWith("'s")&&w.length>3)o.push(w.slice(0,-2));if(w.endsWith('ies')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ied')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ves')&&w.length>4)o.push(w.slice(0,-3)+'f',w.slice(0,-3)+'fe');if(w.endsWith('es')&&w.length>3)o.push(w.slice(0,-2),w.slice(0,-1));if(w.endsWith('s')&&w.length>3)o.push(w.slice(0,-1));for(const suf of ['ing','ed','er','est']){if(w.endsWith(suf)&&w.length>suf.length+2){const b=w.slice(0,-suf.length);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y');if(b.length>2&&b.at(-1)===b.at(-2))o.push(b.slice(0,-1));}}return uniq(o)}
function parseAnchor(p){const a=String(p.anchor||'');let m=a.match(/^Sunshine\s+(PROGRAM\s*\d+-\d+)$/i);if(m)return{book:'サンシャイン',section:m[1]};m=a.match(/^NH\s+(Unit\s*\d+-\d+)$/i);if(m)return{book:'ニューホライズン',section:m[1]};throw new Error(`anchor ${p.id}: ${a}`)}
function code(book){return book==='ニューホライズン'?'NH':book==='サンシャイン'?'SS':(()=>{throw new Error('book '+book)})()}
function cutoff(v7,book,grade,section){const c=code(book),g=Number(grade),u=v7.units[`${c}|${g}`]||{};const at=(fu,sr)=>{const pdf=Number(u[fu]);if(!pdf)throw new Error(`mapping ${c}|${g}|${section}|${fu}`);return{code:c,grade:g,pdf,subrank:Number(sr)}};let m;if(c==='SS'){m=String(section).match(/^PROGRAM\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r=k;if(g===1&&n===10&&k>=4)r=8;if(g===2&&n===8&&k>=2)r=3;if(g===3&&n===7&&k===1)r=2;return at(`P${n}`,r)}}else{m=String(section).match(/^Unit\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r;if(g===1)r=k<=2?k:(n<=4?3:6);else{r=k===1?1:k===2?2:k===3?4:5;if(g===2&&n===7&&k===1)r=2}return at(`U${n}`,r)}}throw new Error(`no cutoff ${book}|${grade}|${section}`)}
function allowed(intro,cut){if(!intro)return false;const[g,p,s]=intro;if(+g<cut.grade)return true;if(+g>cut.grade)return false;return +p<cut.pdf||(+p===cut.pdf&&+s<=cut.subrank)}
function classify(v7,w,cut){if(CONTRACTIONS.has(w)||FUNCTION.has(w)||w==='whether')return'GRAMMAR_ROUTED';const bs=uniq([IRREG.get(w),...bases(w)]);for(const b of bs)if(ELEMENTARY.has(b))return'GRAMMAR_ROUTED';if(ELEMENTARY.has(w))return'ELEMENTARY';for(const b of bs){const i=v7.lex[`${cut.code}|${b}`];if(i&&allowed(i,cut))return'GRAMMAR_ROUTED'}const d=v7.lex[`${cut.code}|${w}`];if(d)return allowed(d,cut)?'V7_ALLOWED':'FUTURE_V7';for(const b of bs){const i=v7.lex[`${cut.code}|${b}`];if(i&&!allowed(i,cut))return'FUTURE_V7'}return'UNREGISTERED'}
const files=['v11_batch15_g1_body_draft.json','v11_batch15_g2_body_draft.json','v11_batch15_g3_body_draft.json'];
const v7=loadCanonicalV7();if(Number(v7.source&&v7.source[2])!==3975)throw new Error('v7 source count mismatch');
const passages=[];for(const file of files){const j=JSON.parse(fs.readFileSync(file,'utf8'));for(const p of j.passages||[]){const a=parseAnchor(p);passages.push({...p,grade:Number(j.grade),textbook:a.book,section:a.section})}}
if(passages.length!==50)throw new Error(`passages=${passages.length}`);
let tokens=0,noteCovered=0;const unresolved=[],future=[];
for(const p of passages){const cut=cutoff(v7,p.textbook,p.grade,p.section);const notes=new Set();for(const n of p.notes||[]){if(n&&n.kind==='unlearned_local_required'){for(const w of tok(n.english))notes.add(w)}}for(const w of tok(p.body)){tokens++;if(notes.has(w)){noteCovered++;continue}const c=classify(v7,w,cut);if(c==='UNREGISTERED')unresolved.push({id:p.id,grade:p.grade,book:p.textbook,section:p.section,word:w});else if(c==='FUTURE_V7')future.push({id:p.id,grade:p.grade,book:p.textbook,section:p.section,word:w})}}
const by=new Map();for(const x of [...unresolved.map(y=>({...y,kind:'UNREGISTERED'})),...future.map(y=>({...y,kind:'FUTURE_V7'}))]){const k=x.kind+'|'+x.word;const z=by.get(k)||{kind:x.kind,word:x.word,occurrences:0,passages:new Set()};z.occurrences++;z.passages.add(x.id);by.set(k,z)}
const residual=[...by.values()].map(z=>({...z,passages:[...z.passages]})).sort((a,b)=>b.occurrences-a.occurrences||a.word.localeCompare(b.word));
const out={generatedAt:new Date().toISOString(),sourceHead:process.env.GITHUB_SHA||null,passages:passages.length,v7Records:v7.source[2],tokensScanned:tokens,requiredNoteCoveredOccurrences:noteCovered,unregisteredOccurrences:unresolved.length,futureVocabLeakOccurrences:future.length,uniqueResidualWords:residual.length,finalPass:unresolved.length===0&&future.length===0,unresolved,future,residual};
fs.writeFileSync('V11_BATCH15_VOCAB_GATE_R6_REPORT.json',JSON.stringify(out,null,2)+'\n');
fs.writeFileSync('V11_BATCH15_VOCAB_GATE_R6_STATUS.txt',[`batch15_passages=${out.passages}/50`,`official_total=868`,`registered=false`,`v7_records=${out.v7Records}`,`tokens_scanned=${tokens}`,`required_note_covered=${noteCovered}`,`unregistered=${unresolved.length}`,`future_vocab=${future.length}`,`unique_residual_words=${residual.length}`,`vocab_gate=${out.finalPass?'PASS':'FAIL'}`].join('\n')+'\n');
fs.writeFileSync('V11_BATCH15_VOCAB_GATE_R6_RESIDUAL.txt',residual.map(r=>`${r.kind}\t${r.word}\tocc=${r.occurrences}\tpassages=${r.passages.join(',')}`).join('\n')+'\n');
console.log(fs.readFileSync('V11_BATCH15_VOCAB_GATE_R6_STATUS.txt','utf8'));
if(!out.finalPass)process.exitCode=1;
