'use strict';
const fs=require('fs');
const files=['v11_batch15_g1_body_draft.json','v11_batch15_g2_body_draft.json','v11_batch15_g3_body_draft.json'];
const G={
attend:'参加する',background:'背景',cashier:'レジ係',clue:'手がかり',confuse:'混同する',courtyard:'中庭',dance:'ダンス',dessert:'デザート',disappeared:'なくなった',echo:'反響',harvest:'収穫',ice:'氷',leafy:'葉の多い',magnets:'磁石',moon:'月',pause:'間を置くこと',pauses:'間',plan:'計画',proof:'証拠',relay:'リレー',stable:'安定した',sticker:'シール',sunlight:'日光',taichi:'タイチ（人名）',textbooks:'教科書',volume:'音量',
accusation:'非難',acting:'行動すること',adjusted:'調整した',adult:'大人',allowing:'可能にすること',appearance:'見た目',approach:'方法',arrange:'整える',assignments:'課題',attractive:'魅力的な',balanced:'バランスの取れた',briefly:'短時間',budget:'予算',button:'ボタン',careless:'不注意な',cast:'日陰を作った',category:'分類',checkout:'会計',completion:'完了',concern:'懸念',conclusions:'結論',confusion:'混乱',consistently:'一貫して',contact:'連絡する',containers:'容器',correction:'修正',cover:'カバー',crops:'作物',crowd:'人混み',delivered:'配達された',depend:'～による',despite:'～にもかかわらず',difficulty:'難しさ',dish:'料理',disorganized:'整理されていない',disruptions:'中断や混乱',distant:'遠い',donated:'寄付した',donating:'寄付すること',done:'終わった',doorway:'出入口',editor:'編集者',effectively:'効果的に',elsewhere:'別の場所で',everywhere:'あらゆる場所で',extending:'延長すること',fifty:'50',finish:'終える',fire:'火',flexible:'柔軟な',force:'力',format:'形式',fruit:'果物',ground:'地面',hide:'隠す',icy:'凍った',ignored:'無視した',impression:'印象',improvement:'改善',inconclusive:'結論が出ない',increasing:'増えている',indicator:'指標',injured:'けがをした',intended:'意図された',interpret:'解釈する',interruptions:'中断',lack:'不足',lid:'ふた',liquid:'液体',loss:'損失',machine:'機械',mechanical:'機械の',melted:'溶けた',mention:'言及する',milk:'牛乳',nothing:'何も～ない',obtain:'得る',organizing:'整理すること',pace:'速さ',particular:'特定の',percentage:'割合',production:'生産',progress:'進み具合',property:'落とし物',protective:'保護用の',puddles:'水たまり',radar:'雨雲レーダー',rainwater:'雨水',rank:'順位',refrigerators:'冷蔵庫',registered:'登録した',remember:'覚えている',revealing:'明らかにすること',rewrite:'書き直す',riders:'利用者',rolling:'移動式の',rotations:'交代',rust:'さび',sakura:'サクラ（人名）',serving:'提供すること',shortage:'不足',smelling:'においのする',snowfall:'降雪',softer:'より柔らかい',sort:'分類する',stated:'述べた',storybook:'物語の本',strengths:'強み',stricter:'より厳しい',string:'ひも',suited:'適した',support:'支援する',suspected:'疑った',"taichi's":'タイチの',technician:'技術者',themselves:'彼ら自身',thin:'薄い',tired:'疲れた',translators:'翻訳者',travel:'移動する',unmanaged:'管理されていない',unreturned:'返却されていない',unsafe:'危険な',unsupported:'裏付けのない',versus:'～対～',violate:'違反する',vocabulary:'語彙',washing:'洗うこと',tweak:'微調整',
// inflection/derivative variants observed by the gate
attended:'参加した',backgrounds:'背景',cashiers:'レジ係',clues:'手がかり',confused:'混乱した',dancing:'踊ること',desserts:'デザート',echoes:'反響',harvests:'収穫',magnet:'磁石',plans:'計画',proofs:'証拠',relays:'リレー',stickers:'シール',volumes:'音量',arranged:'整えた',assignment:'課題',categories:'分類',conclusion:'結論',container:'容器',corrections:'修正',delivering:'配達すること',dishes:'料理',disruption:'中断や混乱',formats:'形式',indicators:'指標',interpretation:'解釈',interrupting:'中断すること',machines:'機械',mentions:'言及',percentages:'割合',productions:'生産',properties:'落とし物',rider:'利用者',shortages:'不足',technicians:'技術者',translator:'翻訳者'
};
const norm=s=>String(s||'').trim().toLowerCase();
let added=0;const byWord={};
for(const file of files){const j=JSON.parse(fs.readFileSync(file,'utf8'));for(const p of j.passages||[]){p.notes=p.notes||[];const have=new Set(p.notes.filter(n=>n&&n.kind==='unlearned_local_required').flatMap(n=>(String(n.english||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(norm)));const words=new Set((String(p.body||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(norm));for(const w of words){if(!G[w]||have.has(w))continue;p.notes.push({kind:'unlearned_local_required',english:w,japanese:G[w],scope:'passage-only-unlearned',basis:'Batch15 chronology R7: explicit context-checked Japanese gloss for a remaining R6 vocabulary violation; no English-as-Japanese placeholder.'});have.add(w);added++;byWord[w]=(byWord[w]||0)+1;}}j.status=String(j.status||'').replace(/_CURATED_GLOSS_R7$/,'')+'_CURATED_GLOSS_R7';fs.writeFileSync(file,JSON.stringify(j,null,2)+'\n');}
fs.writeFileSync('V11_BATCH15_CURATED_GLOSS_R7_REPORT.json',JSON.stringify({generatedAt:new Date().toISOString(),dictionaryWords:Object.keys(G).length,notesAdded:added,passageWordAdds:byWord},null,2)+'\n');
console.log(`Batch15 R7 dictionary=${Object.keys(G).length} notesAdded=${added}`);
