(function buildV11Batch07G2Drafts(){
'use strict';
const BATCH='V11-B07-G2-DRAFT-20260829',SS='サンシャイン',NH='ニューホライズン';
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function q(type,prompt,answer,evidence,evidenceJp,reason,extra){return Object.assign({questionType:type,prompt,answer,evidence,evidenceJp,reason},extra||{});}
function build(o){return Object.assign({grade:'2',level:'STANDARD',genre:'reading',batch:BATCH,targetWordBand:[115,155],wordCount:wc(o.rows),sentences:o.rows.map(r=>r[0]),fullTranslation:o.rows.map(r=>r[1]).join(''),slashRows:o.rows.map(r=>({en:r[0],jp:r[1]})),registered:false,semanticRewrite:'BATCH07_G2_ORIGINAL_20260829'},o,{rows:undefined});}
const passages=[];
function add(o,i){const r=o.rows,e=n=>r[n][0],j=n=>r[n][1];o.questions=[q('GIST','本文の中心内容を答えなさい。',i.gist,e(i.gi),j(i.gi),i.gr),q('DETAIL',i.dq,i.da,e(i.di),j(i.di),'本文に直接示されています。'),q('REASON',i.rq,i.ra,e(i.ri),j(i.ri),'本文の理由から答えられます。'),q('CONTENT_MATCH','本文の内容に合うものを答えなさい。',i.ca,e(i.ci),j(i.ci),'本文の記述と一致します。'),q('DETAIL',i.dq2,i.da2,e(i.di2),j(i.di2),'本文に直接示されています。')];o.questionSetB=[q('INFERENCE',i.iq,i.ia,e(i.ii),j(i.ii),'本文の出来事から推論できます。'),q('SENTENCE_INSERTION',i.insq,i.insa,e(i.insi),j(i.insi),i.insr,{insertAfterSentence:i.insi+1}),q('CONTEXT_WORD',i.cwq,i.cwa,e(i.cwi),j(i.cwi),'文脈と本文の語から判断できます。'),q('SUMMARY_FILL',i.sfq,i.sfa,e(i.sfi),j(i.sfi),'本文の要点を表す語です。'),q('CONTENT_MATCH',i.cq2,i.ca2,e(i.ci2),j(i.ci2),'本文の内容から判断できます。')];o.semanticHumanReview={reviewed:true,timelineCoherent:true,actorPerspectiveClear:true,causalLogicCoherent:true,translationNatural:true,questionAnswerLogical:true,insertionNatural:true,note:'Read as one complete story; problem, evidence, decision, result, translation, and question scope checked.'};passages.push(build(o));}

add({id:'V11-B07-G2-001',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Survey with Two Meanings',rows:[
['Our student council asked, “Do you often use the school library after class?”','生徒会は「放課後、学校図書館をよく利用しますか」とたずねました。'],['Thirty students answered yes, but their comments did not match.','三十人が「はい」と答えましたが、コメントの内容は一致しませんでした。'],['Some students meant four days a week, while others meant twice a month.','週四日を「よく」と考える生徒もいれば、月二回をそう考える生徒もいました。'],['The council realized that the word “often” had two very different meanings.','生徒会は「often」という語が人によって大きく違う意味になると気づきました。'],['They changed the question before using the results for a library plan.','図書館の計画に結果を使う前に質問を変えました。'],['The new form asked, “How many days did you use the library last week?”','新しい用紙では「先週、何日図書館を利用しましたか」とたずねました。'],['Students chose zero, one, two, three, four, or five days.','生徒は0日から5日までの中から選びました。'],['The new answers showed that most users came one or two days, not four or five.','新しい回答では、利用者の多くは四、五日ではなく一、二日来ていると分かりました。'],['The first survey was not useless, but it was too unclear for counting exact use.','最初の調査も無意味ではありませんが、正確な利用回数を数えるには曖昧すぎました。'],['The council learned to ask for a number when a number was important to the decision.','生徒会は、判断に数が重要なときは数で答えられる質問をするべきだと学びました。']
]}, {gist:'曖昧な「often」を具体的な日数に変え、図書館利用を正確に調べたこと。',gi:9,gr:'最後の文が質問改善の学びをまとめています。',dq:'最初の調査でyesと答えたのは何人ですか。',da:'30',di:1,rq:'質問を変えたのはなぜですか。',ra:'oftenの意味が生徒によって違ったから。',ri:3,ca:'The new question asked about days used last week.',ci:5,dq2:'多くの利用者は週何日来ていましたか。',da2:'one or two days',di2:7,iq:'最初の結果だけで利用頻度を正確に比べられない理由は何ですか。',ia:'同じoftenでも人ごとに想定する回数が違ったから。',ii:2,insq:'“They needed a question with the same meaning for every student.” を入れるならどこが自然ですか。',insa:'oftenの意味が違うと気づいた文の直後。',insi:3,insr:'曖昧さを受け、次の質問変更へ自然につながります。',cwq:'“The first question was too _____ for exact counting.” の空所を答えなさい。',cwa:'unclear',cwi:8,sfq:'まとめの空所: “When a number matters, ask for a _____.”',sfa:'number',sfi:9,cq2:'最初の調査は完全に無意味だったと本文は述べていますか。',ca2:'No.',ci2:8});

add({id:'V11-B07-G2-002',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Refill Station Record',rows:[
['Our school had two water refill stations, one near the gym and one near the library.','学校には給水場所が二つあり、体育館近くと図書館近くにありました。'],['The eco club wanted more students to refill bottles instead of buying new plastic bottles.','環境部は新しいペットボトルを買わず、水筒へ補充する生徒を増やしたいと考えました。'],['They first put reminder signs beside both stations.','最初は両方の給水場所の横に案内表示を置きました。'],['For one week, they counted each use at three times of day.','一週間、一日の三つの時間帯で利用回数を数えました。'],['The gym station was busiest after sports practice, but the library station had little use.','体育館側は部活動後に最も多く使われましたが、図書館側は利用が少ないままでした。'],['Students said they usually decided what drink to get before reaching the library hall.','生徒たちは、図書館の廊下へ着く前に何を飲むか決めていると話しました。'],['The club moved one reminder sign to the stairs that students used after lunch.','部は一つの表示を昼食後に生徒が使う階段へ移しました。'],['The station itself did not move.','給水場所そのものは動かしませんでした。'],['During the next week, library-station use increased at lunch time.','翌週、昼休みの図書館側の利用が増えました。'],['The club learned that a reminder can work better before a decision than beside the final place.','案内は最終場所の横より、決める前の場所にある方が効果的なことがあると学びました。']
]}, {gist:'利用記録と生徒の行動を見て、給水場所ではなく案内表示の位置を変えたこと。',gi:9,gr:'最後の文が場所変更の意味をまとめています。',dq:'給水場所はいくつありましたか。',da:'two',di:0,rq:'表示を階段へ移したのはなぜですか。',ra:'生徒が図書館側へ着く前に飲み物を決めていたから。',ri:5,ca:'The refill station itself did not move.',ci:7,dq2:'翌週、どの時間帯の利用が増えましたか。',da2:'lunch time',di2:8,iq:'体育館側が部活動後に多いことから何が分かりますか。',ia:'利用のタイミングは生徒の行動場所と関係している。',ii:4,insq:'“The sign was arriving too late in the decision.” を入れるならどこが自然ですか。',insa:'飲み物を事前に決めていると述べた文の直後。',insi:5,insr:'その事実を受け、次の表示移動へつながります。',cwq:'“The club moved one reminder _____.” の空所を答えなさい。',cwa:'sign',cwi:6,sfq:'まとめの空所: “They changed the sign’s _____, not the station.”',sfa:'place',sfi:7,cq2:'図書館側の給水場所そのものを移しましたか。',ca2:'No.',ci2:7});

add({id:'V11-B07-G2-003',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Article with an Old Fact',rows:[
['Mika wrote a school newspaper article about a local sports center.','美香は地域のスポーツセンターについて学校新聞の記事を書きました。'],['She found an old town page saying the center opened at 8:00 every morning.','古い町のページに、センターは毎朝8時に開くと書かれていました。'],['Before publication, her editor asked when that page had been updated.','掲載前、編集担当がそのページの更新時期をたずねました。'],['The page was four years old.','そのページは四年前のものでした。'],['Mika checked the center’s current page and called the information desk.','美香は現在の公式ページを確認し、案内窓口にも電話しました。'],['Both said weekday opening time was now 9:00.','どちらも、平日の開館時刻は現在9時だと示しました。'],['Weekend opening time was still 8:00.','週末は今も8時開館でした。'],['Mika changed one sentence and added the date she checked the information.','美香は一文を直し、情報を確認した日付も加えました。'],['The old page had once been correct, but it was no longer a safe source for a current schedule.','古いページも以前は正しかったのですが、現在の予定を示す資料としては安全ではありませんでした。'],['The class learned that a fact can become wrong when the world changes around it.','事実も周りの状況が変われば、現在については誤りになることがあると学びました。']
]}, {gist:'古い情報をそのまま使わず、現在の公式情報で開館時刻を確認して記事を直したこと。',gi:9,gr:'最後の文が古い事実の扱いをまとめています。',dq:'古いページでは何時開館とありましたか。',da:'8:00',di:1,rq:'美香が別の資料を確認したのはなぜですか。',ra:'元のページが四年前のものだったから。',ri:3,ca:'Weekday opening time was 9:00 now.',ci:5,dq2:'週末の開館時刻は何時ですか。',da2:'8:00',di2:6,iq:'確認日を記事に加える利点は何ですか。',ia:'その情報がいつ確認されたか読者に分かる。',ii:7,insq:'“That made the time information worth checking again.” を入れるならどこが自然ですか。',insa:'ページが四年前のものだと述べた文の直後。',insi:3,insr:'古さを受けて現在情報の確認へつながります。',cwq:'“Mika called the information _____.” の空所を答えなさい。',cwa:'desk',cwi:4,sfq:'まとめの空所: “An old fact may not describe the _____ schedule.”',sfa:'current',sfi:8,cq2:'古いページは最初から誤っていたと本文は述べていますか。',ca2:'No.',ci2:8});

add({id:'V11-B07-G2-004',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Route with Fewer Stairs',rows:[
['Our class welcomed a visitor who walked slowly with a cane.','クラスは杖を使ってゆっくり歩く来校者を迎えました。'],['The shortest route from the gate to the art room used two staircases.','門から美術室までの最短経路には階段が二か所ありました。'],['A longer route followed a flat hall to an elevator and then crossed one wide corridor.','少し長い道は平らな廊下を進み、エレベーターを使って広い廊下を一つ通りました。'],['The map showed the first route was about sixty meters shorter.','地図では最初の道が約六十メートル短いと分かりました。'],['However, the visitor said stairs were much harder than extra walking on a flat floor.','しかし来校者は、平らな場所を少し多く歩くより階段の方がずっと大変だと話しました。'],['Two students walked both routes while carrying a heavy box.','二人の生徒が重い箱を持って両方の道を歩きました。'],['They also found the elevator route easier and safer.','二人もエレベーターの道の方が楽で安全だと感じました。'],['The class marked that route on the visitor guide even though it was not the shortest.','クラスは最短ではないその道を来校者案内に示しました。'],['They added a note saying, “Step-free route.”','さらに「段差のない経路」と説明を付けました。'],['The class learned that “best route” depends on what makes travel difficult for the person using it.','「最もよい道」は、その人にとって何が移動を難しくするかで変わると学びました。']
]}, {gist:'距離だけでなく利用者にとっての歩きやすさを比べ、段差の少ない道を案内したこと。',gi:9,gr:'最後の文が判断基準をまとめています。',dq:'最短経路には階段がいくつありましたか。',da:'two',di:1,rq:'長い道を選んだのはなぜですか。',ra:'来校者にとって階段より平らな道を多く歩く方が楽だったから。',ri:4,ca:'Students also tested both routes.',ci:5,dq2:'最短経路は約何メートル短かったですか。',da2:'60 meters',di2:3,iq:'重い箱を持って歩いた試験の意味は何ですか。',ia:'距離だけでなく実際の移動しやすさを自分たちでも確かめるため。',ii:6,insq:'“So distance alone did not answer their question.” を入れるならどこが自然ですか。',insa:'来校者が階段の方が大変だと述べた文の直後。',insi:4,insr:'利用者の条件を受け、実際の試行へつながります。',cwq:'“They used an _____ on the longer route.” の空所を答えなさい。',cwa:'elevator',cwi:2,sfq:'まとめの空所: “The chosen route was not the _____ one.”',sfa:'shortest',sfi:7,cq2:'案内にはどんな説明を加えましたか。',ca2:'Step-free route.',ci2:8});

add({id:'V11-B07-G2-005',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Practice Schedule Conflict',rows:[
['The brass band and drama club both reserved the hall from 4:00 to 5:30 on Friday.','吹奏楽部と演劇部が金曜日の4時から5時30分まで同じホールを予約していました。'],['The mistake was found two days before both practices.','間違いは両方の練習の二日前に見つかりました。'],['At first, each club asked the other to move its whole practice.','最初は両方の部が相手に練習全部を移してほしいと求めました。'],['Then the leaders listed which parts really needed the hall.','そこで部長たちは、本当にホールが必要な練習部分を挙げました。'],['The band needed the stage from 4:00 to 4:40 for a full-group sound check.','吹奏楽部は全体の音響確認のため4時から4時40分まで舞台が必要でした。'],['The drama club needed the stage after 4:50 for a scene with the full set.','演劇部はセット全体を使う場面のため4時50分以降に舞台が必要でした。'],['The band could practice small groups in music rooms after 4:40.','吹奏楽部は4時40分以降、小グループなら音楽室で練習できました。'],['The drama club could rehearse lines in a classroom before 4:50.','演劇部は4時50分より前なら教室で台詞練習ができました。'],['They made one shared schedule instead of moving either club to another day.','どちらかを別日に移すのではなく、一つの共同予定を作りました。'],['Both clubs completed the practice they actually needed.','両方の部が本当に必要な練習を終えられました。']
]}, {gist:'予約の重なりを、各部が本当にホールを必要とする時間を比べて解決したこと。',gi:9,gr:'最後の文が共同予定の結果を示します。',dq:'吹奏楽部が舞台を必要としたのは何時までですか。',da:'4:40',di:4,rq:'全練習を別日に移さなくてよかったのはなぜですか。',ra:'両部がホールを必要とする時間が完全には重なっていなかったから。',ri:5,ca:'The drama club could rehearse lines in a classroom before 4:50.',ci:7,dq2:'演劇部が舞台を必要としたのは何時からですか。',da2:'after 4:50',di2:5,iq:'最初の「どちらかが全部動く」案より共同予定がよかった点は何ですか。',ia:'必要な時間だけ調整して両方が同じ日に重要な練習をできた。',ii:8,insq:'“The conflict was smaller when they looked at the exact times.” を入れるならどこが自然ですか。',insa:'二つの必要時間を説明した後。',insi:5,insr:'具体的な時間差を受け、代替場所の説明へつながります。',cwq:'“They made one shared _____.” の空所を答えなさい。',cwa:'schedule',cwi:8,sfq:'まとめの空所: “They compared the time each club really _____ the hall.”',sfa:'needed',sfi:3,cq2:'吹奏楽部は4:40以降どこで練習できましたか。',ca2:'music rooms',ci2:6});

add({id:'V11-B07-G2-006',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Book Review Without a Spoiler',rows:[
['Our library club posted short book reviews for younger students.','図書委員会は下級生向けに短い書評を掲示していました。'],['One review explained the final surprise in a mystery story.','ある書評がミステリーの最後の驚きを説明してしまいました。'],['Several readers said they no longer wanted to read the book.','何人かの読者が、その本を読みたくなくなったと言いました。'],['The club first considered a rule saying reviews could never mention events from the second half.','部は最初、後半の出来事を一切書かないという規則を考えました。'],['A student pointed out that some useful reviews needed to mention the main problem that appeared later.','しかし、後半に出る主な問題に触れないと役立つ書評にならない場合もあると生徒が指摘しました。'],['The club wrote a different rule: explain the setting, main character, and kind of problem, but do not reveal the ending or solution.','そこで、舞台・主人公・問題の種類は説明してよいが、結末や解決は明かさないという規則にしました。'],['Reviewers also added a “spoiler warning” before any detail that went beyond that rule.','規則を超える詳細を書く場合は「ネタバレ注意」も付けることにしました。'],['They tested the rule on three old reviews and found they could still say why each book was interesting.','三つの古い書評で試すと、どの本がなぜ面白いかは十分書けました。'],['The goal was not to make reviews empty; it was to protect the reader’s chance to discover important moments.','目的は書評を中身のないものにすることではなく、読者が重要な場面を自分で知る機会を守ることでした。'],['The club learned that a useful limit should protect something without removing the purpose of the writing.','役に立つ制限は、文章の目的を消さずに大切なものを守るべきだと学びました。']
]}, {gist:'書評の役立つ情報を残しながら、結末や解決を明かさない規則を作ったこと。',gi:9,gr:'最後の文が制限の考え方をまとめています。',dq:'問題になった最初の書評は何を明かしましたか。',da:'the final surprise',di:1,rq:'後半を一切書かない規則にしなかったのはなぜですか。',ra:'後半に出る主な問題の説明が書評に必要な場合もあるから。',ri:4,ca:'The final rule allowed setting and main character information.',ci:5,dq2:'規則を何件の古い書評で試しましたか。',da2:'three',di2:7,iq:'spoiler warning の役割は何ですか。',ia:'通常の規則を超える内容があることを読む前に知らせる。',ii:6,insq:'“That rule would protect surprises, but it could also hide useful information.” を入れるならどこが自然ですか。',insa:'後半を一切書かない案の直後。',insi:3,insr:'最初の案の長所と弱点を示し、次の指摘へつながります。',cwq:'“Do not reveal the ending or _____.” の空所を答えなさい。',cwa:'solution',cwi:5,sfq:'まとめの空所: “A useful limit should keep the writing’s _____.”',sfa:'purpose',sfi:9,cq2:'新しい規則で本が面白い理由は書けましたか。',ca2:'Yes.',ci2:7});

add({id:'V11-B07-G2-007',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Temperature Near the Window',rows:[
['A science group measured classroom temperature at 1:00 every afternoon.','理科班は毎日午後1時に教室の温度を測りました。'],['One thermometer near the sunny window often showed two degrees more than another near the back wall.','日当たりのよい窓際の温度計は、後ろの壁近くより二度ほど高いことがよくありました。'],['The group first thought one thermometer was broken.','班は最初、一つの温度計が壊れていると思いました。'],['They put both thermometers side by side overnight.','そこで夜の間、二つを同じ場所に並べました。'],['In the morning, both showed the same temperature.','朝には両方が同じ温度を示しました。'],['The students then switched the two thermometers between the window and wall positions.','次に二つの温度計の窓側と壁側の位置を入れ替えました。'],['The thermometer at the window again showed the higher reading.','すると窓際に置いた方が再び高い温度を示しました。'],['The difference came from location, not from one broken instrument.','違いは壊れた器具ではなく、置く場所から生まれていました。'],['The group began recording both temperature and measurement position.','班は温度だけでなく測定位置も記録するようにしました。'],['They learned that where a measurement is taken can be part of the result.','測定する場所そのものが結果の一部になることがあると学びました。']
]}, {gist:'温度計自体ではなく測定位置が温度差を生んでいると比較実験で確かめたこと。',gi:9,gr:'最後の文が測定条件の学びをまとめています。',dq:'窓際は約何度高くなりましたか。',da:'two degrees',di:1,rq:'二つを夜に同じ場所へ置いたのはなぜですか。',ra:'温度計自体に差があるか確かめるため。',ri:2,ca:'Both thermometers showed the same temperature in the morning.',ci:4,dq2:'位置を入れ替えた後、どちらが高くなりましたか。',da2:'the thermometer at the window',di2:6,iq:'位置を入れ替える試験で分かったことは何ですか。',ia:'高い値は特定の温度計ではなく窓際という場所に伴っていた。',ii:7,insq:'“That result made a broken thermometer less likely.” を入れるならどこが自然ですか。',insa:'朝に両方が同じ温度だった文の直後。',insi:4,insr:'同条件で一致した結果を受け、位置入れ替えへ進みます。',cwq:'“They recorded the measurement _____.” の空所を答えなさい。',cwa:'position',cwi:8,sfq:'まとめの空所: “The difference came from _____.”',sfa:'location',sfi:7,cq2:'最後に記録項目として追加したものは何ですか。',ca2:'measurement position',ci2:8});

add({id:'V11-B07-G2-008',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Museum Map Test',rows:[
['A local museum asked students to test a new visitor map.','地域の博物館が新しい来館者地図を生徒に試してもらいました。'],['The design team had used a blue circle for elevators and a blue square for stairs.','制作班はエレベーターを青い丸、階段を青い四角で表していました。'],['The symbols looked clear to the students who made the map.','地図を作った生徒には記号が分かりやすく見えました。'],['Five first-time visitors were asked to find the second-floor gallery without help.','初めて来た五人に、助けなしで二階展示室を探してもらいました。'],['Three visitors followed the square symbol and reached the stairs even though they wanted the elevator.','三人は四角い記号をたどり、エレベーターを探していたのに階段へ着きました。'],['They said the two blue symbols were too similar when seen quickly.','急いで見ると二つの青い記号が似すぎていると話しました。'],['The team changed the elevator symbol to a simple picture of elevator doors and kept the stair symbol.','班はエレベーターを扉の絵に変え、階段の記号は残しました。'],['A second group of visitors tested the new map.','別の来館者グループが新しい地図を試しました。'],['All five found the elevator without asking a question.','五人全員が質問せずエレベーターを見つけました。'],['The students learned that a map is clear only if new users can understand it, not only its makers.','地図は作った人だけでなく初めて使う人にも理解できて初めて分かりやすいと学びました。']
]}, {gist:'作成者には分かる記号でも初めての利用者には紛らわしいと分かり、地図記号を改善したこと。',gi:9,gr:'最後の文が利用者テストの意味をまとめています。',dq:'最初のテストには何人いましたか。',da:'five',di:3,rq:'エレベーター記号を変えたのはなぜですか。',ra:'二つの青い記号が急いで見ると似すぎていたから。',ri:5,ca:'The stair symbol was kept.',ci:6,dq2:'二回目のテストで何人が質問せずエレベーターを見つけましたか。',da2:'all five',di2:8,iq:'作成者だけで地図を評価すると問題が残る理由は何ですか。',ia:'作成者は記号の意味をすでに知っていて、初めて見る人の混乱に気づきにくいから。',ii:2,insq:'“Knowing the key in advance had hidden the problem from the makers.” を入れるならどこが自然ですか。',insa:'作成者には分かりやすかったと述べた文の直後。',insi:2,insr:'作成者と初見利用者の違いを説明し、次のテストへつながります。',cwq:'“They changed the elevator _____.” の空所を答えなさい。',cwa:'symbol',cwi:6,sfq:'まとめの空所: “A map must be clear to new _____.”',sfa:'users',sfi:9,cq2:'二回目のテストでは質問が必要でしたか。',ca2:'No.',ci2:8});

add({id:'V11-B07-G2-009',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Headline That Sounded Too Strong',rows:[
['The school newspaper studied a survey about students walking to school.','学校新聞は徒歩通学についてのアンケートを調べました。'],['Fifty students answered, and thirty said they walked at least once a week.','五十人が回答し、そのうち三十人が週一回以上歩くと答えました。'],['A reporter wrote the headline, “Most Students Now Walk to School.”','記者は「今ではほとんどの生徒が徒歩通学」という見出しを書きました。'],['An editor asked whether the survey really proved that statement.','編集者は、その調査が本当にその主張を証明しているかたずねました。'],['The survey included only fifty volunteers, not every student.','調査は全校生徒ではなく、回答した五十人だけでした。'],['It also asked whether they walked at least once a week, not how they traveled every day.','さらに、毎日の通学方法ではなく週一回以上歩くかを聞いただけでした。'],['The team changed the headline to “Thirty of Fifty Surveyed Students Walk at Least Once a Week.”','班は見出しを「調査した五十人中三十人が週一回以上徒歩」に変えました。'],['The new headline was longer, but it matched exactly what the survey measured.','新しい見出しは長くなりましたが、調査した内容と正確に一致しました。'],['The article could still discuss walking as a popular choice without claiming more than the data showed.','記事は、データ以上のことを断定せずに徒歩を人気の選択肢として扱えました。'],['The editors learned that a strong headline should not be stronger than its evidence.','編集者たちは、強い見出しでも根拠以上に強くしてはいけないと学びました。']
]}, {gist:'アンケートが実際に示す範囲より強すぎた見出しを、回答者と質問内容に合う表現へ直したこと。',gi:9,gr:'最後の文が見出しと証拠の関係をまとめています。',dq:'回答者は何人でしたか。',da:'50',di:1,rq:'最初の見出しが強すぎたのはなぜですか。',ra:'全校生徒を調べたわけでも、毎日の通学方法を調べたわけでもなかったから。',ri:5,ca:'Thirty respondents said they walked at least once a week.',ci:1,dq2:'新しい見出しは何人中何人と示しましたか。',da2:'30 of 50',di2:6,iq:'「Most Students Now Walk to School」がデータ以上の主張になる理由は何ですか。',ia:'回答した一部の生徒について週一回以上歩くかを調べただけなのに、全生徒の通常の通学方法のように聞こえるから。',ii:4,insq:'“Those were two important limits on the result.” を入れるならどこが自然ですか。',insa:'回答者の範囲と質問内容を説明した二文の直後。',insi:5,insr:'Those は直前の二つの制限を指し、次の見出し修正へつながります。',cwq:'“The headline should match the _____.” の空所に入る語を答えなさい。',cwa:'evidence',cwi:9,sfq:'まとめの空所: “Do not claim more than the _____ showed.”',sfa:'data',sfi:8,cq2:'新しい見出しは短くなりましたか。',ca2:'No.',ci2:7});

add({id:'V11-B07-G2-010',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Lunch Line Timing Test',rows:[
['Our cafeteria had two lunch lines.','食堂には昼食の列が二つありました。'],['Line A often looked shorter, so many students joined it first.','A列は短く見えることが多く、多くの生徒が最初にそこへ並びました。'],['A math class timed both lines for three days.','数学の授業で三日間、両方の列の時間を測りました。'],['Line A usually had one worker serving several choices.','A列は一人の係が複数の料理を出していました。'],['Line B was longer but had two workers and fewer choices.','B列は長めでしたが係が二人いて、料理の種類も少なめでした。'],['At noon on Tuesday, twelve students in Line A took eight minutes to finish.','火曜日の正午、A列の十二人が終わるまで八分かかりました。'],['Eighteen students in Line B finished in six minutes.','B列の十八人は六分で終わりました。'],['The class repeated the test at other times and found the same general pattern.','別の時間にも試し、同じような傾向を確認しました。'],['They posted average waiting times instead of telling students which line was shorter.','どちらが短いかではなく、平均待ち時間を掲示しました。'],['Students learned that the number of people in a line is only one part of how fast it moves.','列の人数は進む速さを決める一つの要素にすぎないと学びました。']
]}, {gist:'列の長さだけでなく実際の待ち時間を測り、長い列でも速い場合があると確かめたこと。',gi:9,gr:'最後の文が測定結果をまとめています。',dq:'火曜日のA列は何分かかりましたか。',da:'eight minutes',di:5,rq:'B列が長くても速かった理由として本文にある違いは何ですか。',ra:'係が二人いて料理の種類が少なかったこと。',ri:4,ca:'Eighteen students in Line B finished in six minutes.',ci:6,dq2:'測定は何日間行いましたか。',da2:'three days',di2:2,iq:'平均待ち時間を掲示する方が列の見た目より役立つ理由は何ですか。',ia:'実際にどれくらい速く進むかを示せるから。',ii:8,insq:'“The shorter-looking line was not always the faster one.” を入れるならどこが自然ですか。',insa:'A列とB列の火曜日の時間を比べた文の直後。',insi:6,insr:'実測比較をまとめ、次の繰り返しテストへつながります。',cwq:'“They posted average waiting _____.” の空所を答えなさい。',cwa:'times',cwi:8,sfq:'まとめの空所: “Line length is only one _____.”',sfa:'part',sfi:9,cq2:'B列の方が火曜日は人数が少なかったですか。',ca2:'No.',ci2:6});

add({id:'V11-B07-G2-011',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Helmet Reminder Plan',rows:[
['The safety committee wanted more bicycle riders to remember helmets.','安全委員会は自転車利用者がヘルメットを忘れないようにしたいと考えました。'],['Their first idea was a large poster inside the school entrance.','最初の案は校舎入口の内側に大きなポスターを貼ることでした。'],['Students said they usually saw that poster after parking their bicycles.','生徒たちは、そのポスターを見るのは自転車を止めた後だと話しました。'],['The committee tried three smaller reminder places for one week.','委員会は一週間、三つの小さな案内場所を試しました。'],['A sign near the bicycle gate was seen by most riders before they left the school grounds.','自転車門近くの表示は、多くの利用者が校地を出る前に見ていました。'],['A message on the class board was noticed in the morning but often forgotten by afternoon.','教室の掲示は朝には見られましたが、午後には忘れられることが多くありました。'],['A sticker on bicycle racks was too low for some students to notice.','駐輪場のステッカーは低すぎて気づかない生徒もいました。'],['The committee chose the bicycle-gate sign and made the helmet picture larger.','委員会は自転車門の表示を選び、ヘルメットの絵を大きくしました。'],['Teachers did not need to give a long safety speech every day.','先生が毎日長い安全説明をする必要もありませんでした。'],['The group learned that a reminder works best when people see it close to the moment they need to act.','案内は行動が必要な時に近い場所で見ると最も役立つと学びました。']
]}, {gist:'ヘルメットを使う直前に見える場所を比べ、自転車門の表示を選んだこと。',gi:9,gr:'最後の文が案内のタイミングをまとめています。',dq:'最初のポスターはどこにありましたか。',da:'inside the school entrance',di:1,rq:'最初のポスターが遅すぎたのはなぜですか。',ra:'生徒が自転車を止めた後に見ることが多かったから。',ri:2,ca:'The rack sticker was too low for some students.',ci:6,dq2:'最終的にどの場所を選びましたか。',da2:'the bicycle gate',di2:7,iq:'朝の教室掲示だけでは弱かった理由を答えなさい。',ia:'実際に帰る午後までに忘れられることが多かったから。',ii:5,insq:'“The message needed to appear closer to riding time.” を入れるならどこが自然ですか。',insa:'最初のポスターを見る時期を説明した文の直後。',insi:2,insr:'遅いタイミングを受け、次の三場所テストへつながります。',cwq:'“The committee chose the bicycle-gate _____.” の空所を答えなさい。',cwa:'sign',cwi:7,sfq:'まとめの空所: “A reminder should be close to the moment of _____.”',sfa:'action',sfi:9,cq2:'毎日長い安全説明をする必要がありましたか。',ca2:'No.',ci2:8});

add({id:'V11-B07-G2-012',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Presentation with One Clear Graph',rows:[
['Ryo prepared a presentation about electricity used in school classrooms.','涼は学校の教室で使う電気について発表を準備しました。'],['His first version had eight slides filled with small numbers.','最初の版は八枚のスライドに小さな数字がたくさん入っていました。'],['During practice, classmates could not tell which result was most important.','練習では、どの結果が最も重要か友達に伝わりませんでした。'],['Ryo’s main point was that electricity use rose sharply after 3:00 on club days.','涼が最も伝えたいのは、部活動のある日は3時以降に電気使用が大きく増えることでした。'],['He put the hourly numbers into one line graph.','そこで時間ごとの数値を一つの折れ線グラフにしました。'],['The change after 3:00 became easy to see.','3時以降の変化が見やすくなりました。'],['He moved detailed tables to a final reference slide for people who wanted them.','詳しい表は、必要な人のため最後の参考スライドへ移しました。'],['In the second practice, classmates could state his main point after one viewing.','二回目の練習では、一度見ただけで友達が主な内容を言えました。'],['Ryo did not remove the data; he changed which part the audience saw first.','涼はデータを消したのではなく、聞き手が最初に見る部分を変えました。'],['He learned that a clear graph can guide attention while detailed evidence remains available.','詳しい根拠を残しながら、分かりやすいグラフで注目する点を示せると学びました。']
]}, {gist:'細かい数字を全部前面に出さず、主な変化を一つのグラフで見せて詳しい表は参考に残したこと。',gi:9,gr:'最後の文がグラフと詳細データの役割をまとめています。',dq:'最初の版は何枚のスライドでしたか。',da:'eight',di:1,rq:'一つのグラフにしたのはなぜですか。',ra:'3時以降の重要な増加を分かりやすく見せるため。',ri:3,ca:'Detailed tables were kept on a reference slide.',ci:6,dq2:'主な変化は何時以降でしたか。',da2:'after 3:00',di2:3,iq:'「データを消したのではない」と書いた意味は何ですか。',ia:'主な結果を先に見せても、詳細な根拠は必要な人が確認できるよう残した。',ii:8,insq:'“The problem was not a lack of information but too much information at once.” を入れるならどこが自然ですか。',insa:'重要な結果が分からなかったと述べた文の直後。',insi:2,insr:'情報量の問題を示し、次に主な点を明確にします。',cwq:'“He made one line _____.” の空所を答えなさい。',cwa:'graph',cwi:4,sfq:'まとめの空所: “The detailed tables stayed as _____.”',sfa:'reference',sfi:6,cq2:'二回目の練習で友達は主な点を理解できましたか。',ca2:'Yes.',ci2:7});

add({id:'V11-B07-G2-013',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Notice with a Difficult Word',rows:[
['A community center posted a notice about a temporary entrance change.','地域センターが一時的な入口変更について案内を掲示しました。'],['The notice said, “Please use the alternative access point during maintenance.”','案内には「整備中はalternative access pointを使用してください」とありました。'],['Several visitors stopped and asked staff where to enter.','何人もの来館者が立ち止まり、職員にどこから入るのかたずねました。'],['The staff first added a larger arrow but kept the same sentence.','職員は最初、大きな矢印を追加しましたが文はそのままでした。'],['Questions continued because some visitors did not understand “alternative access point.”','「alternative access point」の意味が分からない人がいて、質問は続きました。'],['A student volunteer suggested writing the action in common words.','生徒ボランティアが、することを普通の語で書くよう提案しました。'],['The new sign said, “Front door closed. Please enter through the side door,” with an arrow.','新しい表示は「正面入口閉鎖。横の入口から入ってください」と矢印付きで書きました。'],['Staff watched for an hour and received no questions about the entrance.','職員が一時間様子を見ると、入口についての質問はありませんでした。'],['The information itself had not changed; only the words used to give it had changed.','情報そのものは変わらず、伝えるための言葉だけが変わりました。'],['The center learned that accurate words are not useful if the reader cannot quickly understand the action.','正確な言葉でも、読む人がすぐ行動を理解できなければ役立たないと学びました。']
]}, {gist:'難しい表現を大きくするだけでなく、来館者がすぐ行動できる普通の言葉へ直したこと。',gi:9,gr:'最後の文が分かりやすさの目的をまとめています。',dq:'最初に追加したものは何ですか。',da:'a larger arrow',di:3,rq:'矢印だけでは問題が解決しなかったのはなぜですか。',ra:'難しい表現そのものが理解されていなかったから。',ri:4,ca:'The new sign told visitors to use the side door.',ci:6,dq2:'新しい表示を何時間観察しましたか。',da2:'one hour',di2:7,iq:'「情報そのものは変わっていない」とあることから何が分かりますか。',ia:'問題は案内内容ではなく、読み手に伝わる表現方法だった。',ii:8,insq:'“Making the sign bigger had not made the message clearer.” を入れるならどこが自然ですか。',insa:'質問が続いたと述べた文の直後。',insi:4,insr:'矢印追加の失敗をまとめ、次の言い換えへつながります。',cwq:'“Please enter through the side _____.” の空所を答えなさい。',cwa:'door',cwi:6,sfq:'まとめの空所: “The center changed the _____, not the information.”',sfa:'words',sfi:8,cq2:'新しい表示の後、入口について質問はありましたか。',ca2:'No.',ci2:7});

add({id:'V11-B07-G2-014',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Rehearsal That Started Late',rows:[
['Our drama club planned rehearsals to begin at 4:00, but acting often started near 4:20.','演劇部は4時開始の予定でしたが、演技は4時20分ごろ始まることがよくありました。'],['Members blamed late arrivals, so the leader recorded the first twenty minutes for four days.','部員は遅刻が原因だと考え、部長が四日間、最初の二十分を記録しました。'],['Most members were actually in the room by 4:00.','実際にはほとんどの部員が4時までに部屋にいました。'],['The delay came from moving chairs, finding costumes, and connecting the speaker after everyone arrived.','遅れは全員到着後にいすを動かし、衣装を探し、スピーカーをつなぐ作業から生まれていました。'],['The club changed the order of those jobs.','部はそれらの作業順を変えました。'],['Two students set chairs after lunch, costumes were placed on one rack before school ended, and the speaker was tested at 3:50.','二人が昼休み後にいすを準備し、衣装は放課前に一つの棚へ置き、スピーカーは3時50分に試しました。'],['Actors still arrived at about the same times as before.','演者の到着時刻は以前とほぼ同じでした。'],['However, the next three rehearsals began acting by 4:05.','しかし次の三回は4時5分までに演技を始められました。'],['The club learned that a late start can come from the order of preparation, not only from late people.','開始の遅れは人の遅刻だけでなく準備の順番から起こることもあると学びました。'],['Recording what happened before the start helped them fix the real delay.','開始前に何が起きているか記録したことで、本当の遅れを直せました。']
]}, {gist:'遅刻だと思っていた原因を記録で確認し、準備作業を早めて練習開始を改善したこと。',gi:9,gr:'最後の文が記録の役割をまとめています。',dq:'以前、演技は何時ごろ始まっていましたか。',da:'around 4:20',di:0,rq:'準備順を変えたのはなぜですか。',ra:'多くの部員は4時にいたが、到着後の準備が遅れを生んでいたから。',ri:3,ca:'The speaker was tested at 3:50.',ci:5,dq2:'改善後、演技は何時までに始まりましたか。',da2:'by 4:05',di2:7,iq:'到着時刻がほぼ同じなのに開始が早まったことから何が分かりますか。',ia:'改善の主因は遅刻減少ではなく準備方法の変更だった。',ii:6,insq:'“Their first explanation did not match the record.” を入れるならどこが自然ですか。',insa:'ほとんどの部員が4時までにいたと述べた文の直後。',insi:2,insr:'最初の仮説と記録の違いを受け、真の原因説明へつながります。',cwq:'“The club changed the order of _____.” の空所を答えなさい。',cwa:'preparation',cwi:8,sfq:'まとめの空所: “They recorded what happened before the _____.”',sfa:'start',sfi:9,cq2:'改善後、部員の到着時刻は大きく変わりましたか。',ca2:'No.',ci2:6});

add({id:'V11-B07-G2-015',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Charity Sale Price List',rows:[
['Our class prepared a charity sale with books, cups, and handmade cards.','クラスは本、カップ、手作りカードのチャリティー販売を準備しました。'],['Three groups made price signs separately.','三つの班が別々に値札を作りました。'],['During setup, Yuta found the same book marked 200 yen on one sign and 300 yen on another.','準備中、悠太は同じ本が一つでは200円、別の表示では300円になっているのを見つけました。'],['Two cup prices were also different between the table list and cash desk list.','カップもテーブルの一覧と会計一覧で二つの価格が違っていました。'],['The class did not choose a price by guessing which sign looked newer.','クラスは新しく見える方を推測で選びませんでした。'],['They returned to the original planning sheet approved by the teacher.','先生が確認した元の計画表へ戻りました。'],['One student read each item aloud while another checked both sale lists.','一人が品物を読み上げ、別の生徒が二つの販売一覧を確認しました。'],['A third student placed a check mark only after both lists matched the planning sheet.','三人目は二つの一覧が計画表と一致した時だけチェックを付けました。'],['They found four mismatched prices before the doors opened.','開場前に四つの価格不一致を見つけました。'],['The class learned that one shared source and a simple checking method can prevent small price errors from reaching customers.','一つの共通資料と簡単な確認方法で、小さな価格ミスが客に届くのを防げると学びました。']
]}, {gist:'別々に作った価格表を共通の元資料と役割分担で照合し、販売前に不一致を直したこと。',gi:9,gr:'最後の文が確認方法をまとめています。',dq:'同じ本に付いていた二つの価格は何円ですか。',da:'200 yen and 300 yen',di:2,rq:'新しく見える値札をそのまま採用しなかったのはなぜですか。',ra:'正しい価格を推測ではなく承認済みの元資料で確認するため。',ri:4,ca:'The teacher-approved planning sheet was the shared source.',ci:5,dq2:'開場前に不一致はいくつ見つかりましたか。',da2:'four',di2:8,iq:'三人で役割を分けた利点は何ですか。',ia:'読み上げ、二つの一覧確認、最終チェックを分けて見落としを減らせる。',ii:7,insq:'“They needed one source that all three groups could trust.” を入れるならどこが自然ですか。',insa:'推測で価格を選ばないと述べた文の直後。',insi:4,insr:'推測を避ける理由を示し、元の計画表へ戻る流れです。',cwq:'“They returned to the original planning _____.” の空所を答えなさい。',cwa:'sheet',cwi:5,sfq:'まとめの空所: “They checked both lists against one shared _____.”',sfa:'source',sfi:9,cq2:'チェックマークはいつ付けましたか。',ca2:'After both lists matched the planning sheet.',ci2:7});

add({id:'V11-B07-G2-016',textbook:NH,section:'Unit 7-4',sourceSectionBaselineId:'V10-NH-G2-U7-4-001',title:'The Playground Use Record',rows:[
['A student group wanted to know who used the town playground most.','生徒グループは町の遊び場を誰が最も利用しているか調べたいと考えました。'],['They observed for thirty minutes at 4:00 on one Tuesday.','ある火曜日の4時に三十分観察しました。'],['Most people there were elementary school children, so the group first wrote, “The playground is mainly for young children.”','その時は小学生が最も多く、グループは最初「遊び場は主に小さい子どものため」と書きました。'],['Their teacher asked whether one time could represent the whole week.','先生は一つの時間帯だけで一週間全体を表せるかたずねました。'],['The students returned on a weekday morning, after school, and Saturday afternoon.','生徒たちは平日の朝、放課後、土曜日の午後に再び観察しました。'],['In the morning, several older adults walked there; after school, children were common; on Saturday, many families stayed together.','朝は年配の人が歩き、放課後は子どもが多く、土曜日は家族連れが多くいました。'],['The playground had different users at different times.','遊び場は時間によって異なる人に使われていました。'],['The group changed its report to show the time of every observation.','グループは各観察時刻を示すよう報告を直しました。'],['They also stopped using the first half hour as a description of all users.','最初の三十分だけで全利用者を説明するのをやめました。'],['They learned that an observation can be correct and still be too narrow for a broad conclusion.','観察自体は正しくても、広い結論を出すには範囲が狭すぎることがあると学びました。']
]}, {gist:'一つの時間帯だけの観察から広い結論を出さず、複数の時間で利用者を確認したこと。',gi:9,gr:'最後の文が狭い観察と広い結論の違いをまとめています。',dq:'最初の観察は何曜日でしたか。',da:'Tuesday',di:1,rq:'追加観察をしたのはなぜですか。',ra:'一つの時間帯だけでは一週間全体の利用者を表せない可能性があるから。',ri:3,ca:'Families were common on Saturday afternoon.',ci:5,dq2:'最初の観察時間は何分でしたか。',da2:'30 minutes',di2:1,iq:'最初の「主に小さい子ども向け」という結論の問題は何ですか。',ia:'火曜4時の短い観察を全時間帯の利用者へ広げていたこと。',ii:8,insq:'“The first observation was true, but it was only one small window.” を入れるならどこが自然ですか。',insa:'先生が一つの時間で全週を表せるか問う文の直後。',insi:3,insr:'最初の観察の限界をまとめ、追加観察へつながります。',cwq:'“The playground had different _____ at different times.” の空所を答えなさい。',cwa:'users',cwi:6,sfq:'まとめの空所: “A broad conclusion needs more than one observation _____.”',sfa:'time',sfi:7,cq2:'最初の観察そのものが間違いだったと本文は述べていますか。',ca2:'No.',ci2:9});

add({id:'V11-B07-G2-017',textbook:SS,section:'PROGRAM 8-3',sourceSectionBaselineId:'V10-SS-G2-P8-3-001',title:'The Instruction with a Missing Step',rows:[
['The technology club wrote instructions for using a small school printer.','技術部は学校の小型プリンターの使い方を書きました。'],['Experienced members followed the instructions without trouble.','経験のある部員は問題なく手順を進められました。'],['The club then asked three first-time users to test the page without help.','そこで初めて使う三人に、助けなしで手順書を試してもらいました。'],['All three stopped after loading the paper.','三人とも紙を入れた後で止まりました。'],['The next written step said, “Choose Print on the computer.”','次の説明は「コンピューターでPrintを選ぶ」でした。'],['However, the printer stayed asleep until a small power button was pressed once.','しかし、小さな電源ボタンを一度押すまでプリンターは休止状態のままでした。'],['Experienced members pressed that button automatically and had forgotten to write it down.','経験者は無意識にそのボタンを押していたため、書くのを忘れていました。'],['The club added, “Press the power button once and wait for the green light.”','部は「電源ボタンを一度押し、緑のランプを待つ」と追加しました。'],['A second group completed the printing without help.','二つ目のグループは助けなしで印刷を完了しました。'],['The club learned that testing instructions with a new user can reveal steps that experts no longer notice.','初めての人に手順を試してもらうと、経験者が意識しなくなった手順を見つけられると学びました。']
]}, {gist:'経験者が無意識にしていた電源操作を、初めての利用者のテストで見つけて手順に追加したこと。',gi:9,gr:'最後の文が初見テストの意味をまとめています。',dq:'最初のテストには何人いましたか。',da:'three',di:2,rq:'三人とも紙を入れた後で止まったのはなぜですか。',ra:'電源ボタンを押す手順が書かれていなかったから。',ri:5,ca:'Experienced members pressed the power button automatically.',ci:6,dq2:'追加した手順では何色のランプを待ちますか。',da2:'green',di2:7,iq:'経験者だけでは欠けた手順に気づきにくかった理由は何ですか。',ia:'その操作を考えず自動的に行っていたから。',ii:6,insq:'“The missing action was obvious only to people who already knew it.” を入れるならどこが自然ですか。',insa:'経験者が無意識に押していたと述べた文の直後。',insi:6,insr:'経験者の習慣をまとめ、次の手順追加へつながります。',cwq:'“Wait for the green _____.” の空所を答えなさい。',cwa:'light',cwi:7,sfq:'まとめの空所: “New users can reveal a missing _____.”',sfa:'step',sfi:9,cq2:'二回目のグループは助けが必要でしたか。',ca2:'No.',ci2:8});

window.V11_BATCH07_G2_DRAFTS=passages;window.V11_BATCH07_G2_DRAFT_STATE={batch:BATCH,count:passages.length,ids:passages.map(p=>p.id),wordCounts:Object.fromEntries(passages.map(p=>[p.id,p.wordCount])),registered:false};
})();
