(function buildV11Batch05Grade3Draft(){
'use strict';
const BATCH='V11-B05-G3-DRAFT-20260828';
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while|although)\b/gi,'/ $1');}
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function build(id,textbook,section,baseline,title,rows,long,notes){const qs=rows.slice(0,10).map((r,i)=>({prompt:`${i+1}. 本文の第${i+1}文の内容に合う英文を本文から一文答えなさい。`,answer:r[0],evidence:r[0],evidenceJp:r[1],reason:`第${i+1}文が直接の根拠です。`}));return {id,textbook,grade:'3',section,level:'STEP',title,genre:'story',batch:BATCH,sourceSectionBaselineId:baseline,targetWordBand:long?[210,270]:[140,185],wordCount:wc(rows),sentences:rows.map(r=>r[0]),fullTranslation:rows.map(r=>r[1]).join(''),slashRows:rows.map(r=>({en:slash(r[0]),jp:r[1]})),questions:qs.slice(0,5),questionSetB:qs.slice(5,10),notes:(notes||[]).map(n=>({english:n[0],japanese:n[1],kind:'unlearned_local_required',source:'v11 Batch05 G3 story-specific required note seed'})),semanticRewrite:'BATCH05_G3_STORY_SPECIFIC_20260828',registered:false,auditNote:'Batch05 G3 non-runtime authoring draft. Story-specific passage; chronology, length, question diversity, notes, cross-batch, PC/iPhone and A4 gates still required.'};}
const SS='サンシャイン',NH='ニューホライズン',ssBase='V10-SS-G3-P7-3-001',nhBase='V10-NH-G3-U6-4-001';
const all=[
build('V11-SS-G3-P7-3-035',SS,'PROGRAM 7-3',ssBase,'The Source Behind the Number',[
['Our debate team found a website saying that most teenagers preferred one type of transportation.','私たちのディベート班は、10代の多くがある交通手段を好むと書かれたウェブサイトを見つけました。'],
['The number looked useful because it seemed to support our main argument.','その数字は私たちの主張を支えるように見えたので、役立ちそうでした。'],
['One member copied the percentage onto a slide before checking where it came from.','一人のメンバーは出典を確認する前に、その割合をスライドへ写しました。'],
['During practice, another member asked who had collected the original information.','練習中、別のメンバーが元の情報をだれが集めたのかたずねました。'],
['The website only repeated the number and linked to an older article.','そのウェブサイトは数字を繰り返しているだけで、古い記事へリンクしていました。'],
['We opened that article and found a link to the actual survey report.','その記事を開き、実際の調査報告へのリンクを見つけました。'],
['The report explained that only students from one city had answered the survey.','報告には、一つの市の生徒だけがアンケートに答えたと説明されていました。'],
['It was also several years older than we had expected.','さらに、私たちが思っていたより数年古いものでした。'],
['We decided not to describe the result as a fact about all teenagers.','その結果をすべての10代についての事実として述べないことにしました。'],
['Instead, we used the number as one limited example and wrote the survey place and year beside it.','代わりに限定的な一例として使い、調査場所と年を横に書きました。'],
['We also searched for a newer source that covered a wider group of students.','さらに、もっと広い生徒を対象にした新しい資料も探しました。'],
['Following the number back to its source made our argument more careful and accurate.','数字を出典までたどることで、私たちの主張はより慎重で正確になりました。']
],false,[['source','出典'],['percentage','割合'],['survey report','調査報告'],['accurate','正確な']]),
build('V11-SS-G3-P7-3-036',SS,'PROGRAM 7-3',ssBase,'One Sign-In Line Is Too Slow',[
['Our school held a community event, and our class helped at the entrance.','学校で地域行事があり、私たちのクラスは入口を手伝いました。'],
['At first, every visitor stood in one line to write a name and receive a program.','最初は、全来場者が一列に並び、名前を書いて案内を受け取りました。'],
['The line quickly became long because writing names took more time than handing out programs.','名前を書くほうが案内を渡すより時間がかかり、列はすぐ長くなりました。'],
['Some visitors had already registered online and did not need to write anything.','来場者の中にはオンライン登録済みで、何も書く必要がない人もいました。'],
['We did not want to create two separate records that might later disagree.','あとで食い違う可能性のある二つの別記録は作りたくありませんでした。'],
['A teacher suggested keeping one record table but separating the simple tasks around it.','先生は記録表は一つのまま、周りの簡単な作業を分けるよう提案しました。'],
['One volunteer checked whether a visitor had registered before the person reached the table.','一人の係が、来場者が机に着く前に登録済みか確認しました。'],
['Another volunteer prepared programs and name stickers beside the table.','別の係が机の横で案内と名前シールを準備しました。'],
['Only visitors who needed to add information stopped to write on the main record.','情報追加が必要な人だけが主記録に書くため立ち止まりました。'],
['Everyone still appeared on the same final list, but the line moved much faster.','全員が同じ最終一覧に載りながら、列はずっと速く進みました。'],
['We watched the entrance for ten minutes and saw that the waiting area stayed clear.','十分間入口を見て、待つ場所が混雑しないことを確認しました。'],
['Separating tasks without separating the record solved the slow-line problem.','記録を分けずに作業を分けることで、遅い列の問題を解決できました。']
],false,[['sign-in','受付記入'],['registered','登録済みの'],['record table','記録表'],['waiting area','待機場所']]),
build('V11-SS-G3-P7-3-037',SS,'PROGRAM 7-3',ssBase,'The Cheaper Route with a Long Wait',[
['Our group compared two train routes for a weekend field trip.','私たちの班は週末の校外学習のため二つの電車経路を比べました。'],
['Route A cost less, so several students wanted to choose it immediately.','A経路のほうが安かったので、何人かはすぐそれを選びたがりました。'],
['When we checked the timetable, however, Route A required a forty-minute wait at one station.','しかし時刻表を確認すると、A経路では一つの駅で四十分待つ必要がありました。'],
['Route B cost a little more but had only a ten-minute transfer.','B経路は少し高いものの、乗り換えは十分だけでした。'],
['The field trip had a fixed meeting time that could not be changed.','校外学習には変更できない集合時刻がありました。'],
['We calculated both the total cost and the total travel time for each route.','それぞれの総費用と総移動時間を計算しました。'],
['Then we considered what would happen if the first train was a few minutes late.','さらに最初の電車が数分遅れた場合も考えました。'],
['Route A had a long wait but still arrived close to our meeting time.','A経路は長く待つのに、到着は集合時刻に近いものでした。'],
['Route B gave us more time before the meeting and needed only one simple transfer.','B経路は集合前の余裕があり、乗り換えも一回だけでした。'],
['The difference in price was small enough for our trip budget.','料金差は校外学習の予算内に収まる小さなものでした。'],
['We chose Route B and wrote both cost and time in our plan so everyone understood the reason.','B経路を選び、理由が分かるよう計画に費用と時間の両方を書きました。'],
['Comparing more than the ticket price gave us a route that fit the whole trip better.','切符の値段だけでなく比較することで、旅行全体に合う経路を選べました。']
],false,[['field trip','校外学習'],['transfer','乗り換え'],['trip budget','旅行予算']]),
build('V11-SS-G3-P7-3-038',SS,'PROGRAM 7-3',ssBase,'The Graph Starts Too High',[
['I made a graph showing changes in the number of library visitors during one month.','私は一か月の図書館利用者数の変化を示すグラフを作りました。'],
['The numbers changed from about ninety students to a little over one hundred.','数字は約九十人から百人を少し超える程度まで変化していました。'],
['My first graph started its vertical scale at eighty-five instead of zero.','最初のグラフは縦軸をゼロではなく八十五から始めていました。'],
['Because of that choice, a small increase looked like a very large jump.','そのため、小さな増加がとても大きな急増のように見えました。'],
['During practice, a classmate said the picture felt more dramatic than the data.','練習中、クラスメートがデータより図が大げさに見えると言いました。'],
['We checked every value and confirmed that the numbers themselves were correct.','すべての数値を確認し、数字自体は正しいと確かめました。'],
['The problem was the way I had chosen and labeled the scale.','問題は私が目盛りを選び、表示した方法でした。'],
['I rebuilt the graph with a wider scale and clearly marked each interval.','より広い目盛りでグラフを作り直し、各間隔をはっきり示しました。'],
['The increase was still visible, but it no longer looked ten times larger than it really was.','増加は見えましたが、実際より十倍も大きいようには見えなくなりました。'],
['I added a short note explaining the exact starting and ending values.','正確な開始値と終了値を説明する短い注も加えました。'],
['The revised graph made it easier for the audience to judge the change fairly.','修正版のグラフで、聞き手が変化を公平に判断しやすくなりました。'],
['A correct number can still mislead people if the graph around it is not designed carefully.','正しい数字でも、周りのグラフ設計が慎重でなければ人を誤解させることがあります。']
],false,[['vertical scale','縦軸の目盛り'],['interval','間隔'],['mislead','誤解させる']]),
build('V11-SS-G3-P7-3-039',SS,'PROGRAM 7-3',ssBase,'The Interview Answer Needs an Example',[
['For a class project, I interviewed a local volunteer about helping children after school.','授業の活動で、放課後に子どもを支援する地域ボランティアへインタビューしました。'],
['I asked why the work was important, and she said it helped the community.','なぜその活動が大切かたずねると、地域の役に立つからだと答えました。'],
['The answer sounded reasonable, but it was too general for the report I was writing.','その答えはもっともでしたが、私のレポートには一般的すぎました。'],
['Instead of moving to my next prepared question, I asked for one example.','用意した次の質問へ進まず、一つ具体例をたずねました。'],
['She told me about a child who had been afraid to read aloud at first.','彼女は、最初は音読を怖がっていた子どもの話をしてくれました。'],
['Volunteers practiced short pages with that child every week for several months.','ボランティアは数か月間、毎週その子と短いページを練習しました。'],
['Later, the child read a whole story to a younger student without stopping.','その後、その子は年下の生徒へ一つの物語を止まらず読みました。'],
['That story showed what the volunteer meant by helping the community.','その話で、地域を助けるという言葉の意味が具体的に分かりました。'],
['I asked how the volunteers knew when to give help and when to let children try alone.','さらに、いつ助け、いつ子どもだけで挑戦させるかどう判断するのかもたずねました。'],
['Her answer gave me another detail that connected the example to the group’s methods.','その答えから、具体例と活動方法をつなぐもう一つの細部を得られました。'],
['In my report, I used the example after the general statement rather than replacing it.','レポートでは一般的な説明を消さず、そのあとに具体例を置きました。'],
['One focused follow-up question turned a broad answer into evidence readers could understand.','一つの焦点を絞った追加質問で、広い答えが読者に伝わる根拠になりました。']
],false,[['volunteer','ボランティア'],['general','一般的な'],['follow-up question','追加質問']]),
build('V11-SS-G3-P7-3-040',SS,'PROGRAM 7-3',ssBase,'The Two Deadline Notices',[
['Our school club received two notices about the deadline for a poster contest.','学校の部活動でポスターコンテストの締切について二つのお知らせを受け取りました。'],
['The first paper said entries were due on September tenth.','最初の紙には応募締切は九月十日とありました。'],
['A message posted online later said September twelfth, but it did not explain the change.','あとでオンラインに出たメッセージには九月十二日とありましたが、変更理由は書かれていませんでした。'],
['Some members wanted to trust the later date simply because the message was newer.','何人かは新しいメッセージだからというだけで、遅い日付を信じようとしました。'],
['Others worried that the online date might contain a typing mistake.','ほかのメンバーはオンラインの日付が入力ミスかもしれないと心配しました。'],
['We checked the contest page, but it still showed the earlier deadline.','コンテストのページを確認しましたが、まだ早い締切が表示されていました。'],
['Instead of guessing, our club leader asked the teacher responsible for the contest.','推測せず、部長がコンテスト担当の先生へ確認しました。'],
['The teacher explained that the deadline had officially moved to September twelfth that morning.','先生はその朝、締切が正式に九月十二日へ変更されたと説明しました。'],
['She also updated the contest page so every class would see the same information.','さらに全クラスが同じ情報を見るようコンテストページも更新しました。'],
['We wrote the confirmed date on our club calendar with a note saying who had verified it.','確認済みの日付を、だれが確認したかというメモとともに部の予定表へ書きました。'],
['Our group still planned to finish one day early so a small problem would not make us late.','小さな問題で遅れないよう、班では一日前に完成する計画を残しました。'],
['Confirming the change gave us a reliable deadline instead of two competing guesses.','変更を確認することで、二つの推測ではなく信頼できる締切を得られました。']
],false,[['deadline','締切'],['entry','応募作品'],['officially','正式に'],['verified','確認した']]),
build('V11-SS-G3-P7-3-041',SS,'PROGRAM 7-3',ssBase,'The Best-Rated Choice Is Too Far',[
['Our group needed a place to hold a short weekend study meeting.','私たちの班は週末の短い勉強会を開く場所が必要でした。'],
['One student found a café with the highest online rating in our area.','一人が地域で最も高いオンライン評価のカフェを見つけました。'],
['Everyone liked the photos, and the rating made it seem like an easy choice.','全員が写真を気に入り、高い評価で簡単に決められそうに見えました。'],
['Then we checked the map and saw that the café was far from every student’s usual train line.','しかし地図を見ると、そのカフェは全員の普段の電車路線から遠い場所でした。'],
['Getting there would take more time than the meeting itself for two members.','二人のメンバーは、会議時間より移動時間のほうが長くなります。'],
['We wrote down what we actually needed: quiet tables, a low cost, and easy access.','本当に必要な条件として、静かな机、低い費用、行きやすさを書きました。'],
['A smaller library meeting room had fewer online reviews but met all three needs.','小さな図書館の会議室は口コミが少なかったものの、三条件すべてを満たしました。'],
['It was near a station used by every member and could be reserved for free.','全員が使う駅の近くで、無料予約もできました。'],
['We checked the opening hours and confirmed that talking quietly was allowed in that room.','開館時間を調べ、その部屋では静かな会話が許可されていることも確認しました。'],
['The group chose the library even though its online rating was not part of our comparison.','オンライン評価は比較条件にしませんでしたが、班は図書館を選びました。'],
['All members arrived on time, and nobody had to buy food to stay there.','全員時間どおりに着き、滞在のため食べ物を買う必要もありませんでした。'],
['Choosing by our real needs worked better than following the most popular score.','人気の点数に従うより、実際の必要条件で選ぶほうがうまくいきました。']
],false,[['rating','評価'],['access','行きやすさ'],['reserve','予約する']]),
build('V11-SS-G3-P7-3-042',SS,'PROGRAM 7-3',ssBase,'The Community Map Needs a Rest Point',[
['Our class created a walking map for visitors to a neighborhood history event.','私たちのクラスは地域の歴史行事を訪れる人向けに散策地図を作りました。'],
['The first version showed six old buildings and the shortest path between them.','最初の版には六つの古い建物と、それらを結ぶ最短経路を示しました。'],
['During a test walk, we invited two older community members to follow the route with us.','試し歩きでは、地域の年配の方二人に一緒に経路を歩いてもらいました。'],
['After the fourth stop, one person asked whether there was a place to sit nearby.','四つ目の場所のあと、一人が近くに座れる場所があるかたずねました。'],
['Our map showed buildings and roads but no benches or rest areas.','地図には建物と道はありましたが、ベンチや休憩場所はありませんでした。'],
['We realized that a short route was not the only thing visitors might need.','短い経路だけが来場者に必要なものではないと気づきました。'],
['A small public garden with benches stood only one block from the route.','ベンチのある小さな公共庭園が経路から一ブロックだけ離れた場所にありました。'],
['We added the garden to the map with a chair symbol and a short note.','その庭園をいすの記号と短い注とともに地図へ加えました。'],
['We also marked a public restroom near the final stop after checking its opening hours.','開いている時間を確認し、最終地点近くの公衆トイレも記しました。'],
['The revised route became slightly longer if visitors chose the rest point.','休憩場所を選ぶと修正版の経路は少し長くなりました。'],
['However, people could now decide when to continue and when to take a break.','しかし、いつ進み、いつ休むかを自分で選べるようになりました。'],
['Testing the map with real users helped us design for comfort as well as distance.','実際の利用者と地図を試すことで、距離だけでなく快適さも考えて作れました。']
],false,[['rest point','休憩場所'],['bench','ベンチ'],['public restroom','公衆トイレ'],['comfort','快適さ']]),
build('V11-NH-G3-U6-4-035',NH,'Unit 6-4',nhBase,'The Email Needs a Clear Request',[
['Our international exchange group wrote an email to a partner school about an online meeting.','国際交流班はオンライン会議について交流校へメールを書きました。'],
['The first draft was polite and explained why we were excited to meet them.','最初の下書きは丁寧で、会えることを楽しみにしている理由も説明していました。'],
['However, the last paragraph only said that we hoped they could help with the schedule.','しかし最後の段落には、予定について協力してほしいとだけ書いていました。'],
['A classmate asked what action the reader was actually supposed to take.','クラスメートが、読み手は実際に何をすればよいのかたずねました。'],
['We saw that the message was friendly but not specific enough.','メッセージは親しみやすいものの、十分具体的ではないと気づきました。'],
['We added three possible meeting dates and asked them to choose one by Friday.','候補日を三つ加え、金曜日までに一つ選んでもらうよう頼みました。'],
['We also asked them to tell us if none of the dates worked in their time zone.','どの日も相手の時間帯で難しい場合は知らせてもらうよう書きました。'],
['The request now appeared in one short paragraph near the end of the email.','依頼内容はメールの終わり近くの短い一段落にまとまりました。'],
['Before sending, we checked that the dates and day names matched correctly.','送る前に、日付と曜日が正しく一致しているか確認しました。'],
['The partner school replied the next morning and selected the second date.','交流校は翌朝返信し、二つ目の日を選びました。'],
['Their quick answer showed that the task was easy to understand.','素早い返信から、依頼内容が理解しやすかったと分かりました。'],
['Politeness mattered, but a clear action made the polite email useful.','丁寧さも大切でしたが、明確な行動を示すことで丁寧なメールが役立つものになりました。']
],false,[['partner school','交流校'],['specific','具体的な'],['time zone','時間帯']]),
build('V11-NH-G3-U6-4-036',NH,'Unit 6-4',nhBase,'The Temperature Jump',[
['Our science group measured outdoor temperatures at the same place for one week.','私たちの科学班は一週間、同じ場所で屋外気温を測りました。'],
['Most afternoon readings were between eighteen and twenty-one degrees.','午後の測定値の多くは十八度から二十一度の間でした。'],
['One Thursday reading suddenly showed twenty-eight degrees.','木曜日の一つの測定値だけ突然二十八度を示しました。'],
['The number was possible, but it was much higher than every other result.','あり得る数字ではありましたが、ほかの結果よりかなり高いものでした。'],
['Instead of deleting it or using it immediately, we checked our observation notes.','削除したりすぐ使ったりせず、観察メモを確認しました。'],
['The note said that the thermometer had been moved closer to a sunny wall that day.','その日の温度計は日当たりのよい壁の近くへ移動していたとメモにありました。'],
['We also saw that the reading had been taken thirty minutes later than usual.','さらに、普段より三十分遅く測っていたことも分かりました。'],
['Both changes could have affected the unusual number.','その二つの変更が異常な数字に影響した可能性がありました。'],
['The next day, we returned the thermometer to the original shaded position and used the usual time.','翌日、温度計を元の日陰の位置に戻し、普段の時刻に測りました。'],
['The reading returned to the same range as the earlier days.','測定値は前の日々と同じ範囲へ戻りました。'],
['In our report, we kept Thursday’s number but explained the different conditions beside it.','レポートでは木曜日の数字を残しましたが、横に違う条件を説明しました。'],
['Checking how the data was collected helped us understand the strange result instead of hiding it.','データの集め方を確認することで、変な結果を隠さず理解できました。']
],false,[['reading','測定値'],['thermometer','温度計'],['shaded','日陰の'],['condition','条件']]),
build('V11-NH-G3-U6-4-037',NH,'Unit 6-4',nhBase,'The Joke That Did Not Travel',[
['I exchanged emails with a student in another country for an English project.','英語の活動で、別の国の生徒とメール交換をしました。'],
['In one message, I used a joke that my friends at school often understood immediately.','あるメッセージで、学校の友達ならすぐ分かる冗談を使いました。'],
['The other student replied politely but asked what the sentence actually meant.','相手は丁寧に返信しましたが、その文が実際どういう意味かたずねました。'],
['I realized the joke depended on a phrase that was common only among my friends.','その冗談は友達の間だけでよく使う表現に頼っていると気づきました。'],
['Explaining the joke in another long message would make the conversation harder, not easier.','長い別メールで冗談を説明すると、会話は簡単になるどころか難しくなります。'],
['I rewrote the idea in direct words and said what had really happened at school.','その内容を直接的な言葉で書き直し、学校で実際に何があったか伝えました。'],
['I also told the student that the first sentence had been an informal joke.','最初の文はくだけた冗談だったとも伝えました。'],
['The next reply showed that the story was now easy to understand.','次の返信から、話が理解しやすくなったことが分かりました。'],
['Later, I asked the student about expressions that were common among friends in that country.','あとで、その国の友達の間でよく使う表現についてもたずねました。'],
['We compared a few examples and learned that familiar expressions do not always cross cultures clearly.','いくつかの例を比べ、慣れた表現が文化を越えると必ずしも伝わらないと学びました。'],
['After that, I used plain wording first and added local expressions only when I could explain them.','それからはまず平易な言葉を使い、説明できる場合だけ地域的な表現を加えました。'],
['Replacing one confusing joke improved both the message and our later conversations.','分かりにくい冗談を一つ置き換えることで、メッセージもその後の会話もよくなりました。']
],false,[['informal','くだけた'],['expression','表現'],['plain wording','平易な言葉'],['culture','文化']]),
build('V11-NH-G3-U6-4-038',NH,'Unit 6-4',nhBase,'The Poster Translation Needs Context',[
['Our class translated a short festival poster for visitors who read English.','私たちのクラスは英語を読む来場者向けに文化祭の短いポスターを翻訳しました。'],
['One Japanese phrase was translated word for word into a very short English sentence.','ある日本語表現を一語ずつ直訳し、とても短い英語の文にしました。'],
['The grammar was not wrong, but two exchange students said they could not tell what the event was for.','文法は間違っていませんでしたが、交換留学生二人は行事の目的が分からないと言いました。'],
['The original Japanese made sense because local students already knew the school tradition.','元の日本語は、地元の生徒が学校の伝統を知っているので意味が通じました。'],
['Visitors did not have that background knowledge.','来場者にはその背景知識がありませんでした。'],
['We added one simple sentence explaining that the event invited families to see student projects.','家族を招き、生徒の活動を見る行事だと説明する簡単な一文を加えました。'],
['Then we changed the short translated phrase so it sounded like an invitation rather than a label.','さらに短い直訳文を、ラベルではなく案内のように聞こえる表現へ変えました。'],
['We kept the date, place, and entrance information exactly the same.','日付、場所、入口情報はまったく同じに保ちました。'],
['The exchange students read the revised poster without receiving any extra explanation.','交換留学生に追加説明なしで修正版ポスターを読んでもらいました。'],
['They could now describe both what would happen and why visitors might want to come.','今度は何が行われ、なぜ来場したいと思うのかの両方を説明できました。'],
['We used their feedback to check the other translated signs around the school.','その意見を使い、校内のほかの翻訳案内も確認しました。'],
['Good translation required enough context for the actual reader, not just matching each original word.','よい翻訳には、元の語を合わせるだけでなく実際の読み手に十分な背景が必要でした。']
],false,[['word for word','一語ずつの直訳'],['background knowledge','背景知識'],['invitation','案内・招待'],['context','背景情報']]),
build('V11-NH-G3-U6-4-039',NH,'Unit 6-4',nhBase,'The Survey Missed One Group',[
['Our student council surveyed opinions about a new lunchtime activity.','生徒会は新しい昼休み活動について意見をアンケートで集めました。'],
['We collected many answers quickly by asking students near the gym after sports practice.','運動部練習後に体育館近くの生徒へたずね、多くの回答をすぐ集めました。'],
['The first results strongly supported adding more sports equipment at lunch.','最初の結果は、昼休みにスポーツ用具を増やすことを強く支持していました。'],
['Before writing our conclusion, one member checked where the respondents had been found.','結論を書く前に、一人が回答者をどこで見つけたか確認しました。'],
['Almost everyone in our sample had just finished a sports activity.','標本のほとんど全員がちょうど運動活動を終えた生徒でした。'],
['Students who spent lunch in the library or music rooms were barely represented.','図書室や音楽室で昼休みを過ごす生徒はほとんど含まれていませんでした。'],
['We realized that our survey did not show the opinion of the whole school.','私たちのアンケートは学校全体の意見を示していないと気づきました。'],
['Instead of hiding that problem, we wrote it as a limitation under the first graph.','その問題を隠さず、最初のグラフの下に限界として書きました。'],
['We then collected a smaller second set of answers from three different school areas.','その後、校内の三つの異なる場所で少数の二回目回答を集めました。'],
['The new results included more support for quiet activities as well as sports.','新しい結果ではスポーツだけでなく静かな活動への支持も増えました。'],
['Our final proposal suggested several choices instead of presenting one activity as everyone’s favorite.','最終提案では、一つの活動を全員のお気に入りとせず、複数の選択肢を提案しました。'],
['Saying what our first survey could not prove made the final report more trustworthy.','最初のアンケートで証明できないことを明示し、最終報告がより信頼できるものになりました。']
],false,[['respondent','回答者'],['sample','標本・調査対象'],['limitation','限界'],['trustworthy','信頼できる']]),
build('V11-NH-G3-U6-4-040',NH,'Unit 6-4',nhBase,'The Lost Item Description Is Too General',[
['I lost a small bag somewhere between the library and the school entrance.','私は図書室と学校入口の間のどこかで小さな袋をなくしました。'],
['At the office, I first reported only that the bag was dark and contained school things.','職員室では最初、袋は暗い色で学校の物が入っているとだけ伝えました。'],
['The staff member explained that several lost bags could match that description.','職員の方は、その説明に合う落とし物の袋がいくつもあるかもしれないと言いました。'],
['She asked me to remember the last time and place where I had definitely seen it.','最後に確実に見た時刻と場所を思い出すようたずねられました。'],
['I had used the bag at a library table just before lunch.','私は昼食直前、図書室の机でその袋を使っていました。'],
['I then described its size, the green zipper, and a small white mark on one corner.','次に大きさ、緑のファスナー、角の小さな白い印を説明しました。'],
['I also listed two objects inside that would help identify it.','さらに中に入っている、確認に役立つ二つの物も伝えました。'],
['The staff member checked a newly received item from the hallway near the library.','職員の方は図書室近くの廊下から届いたばかりの品を確認しました。'],
['Its color, zipper, corner mark, and contents all matched my report.','色、ファスナー、角の印、中身がすべて私の報告と一致しました。'],
['After confirming my name, she returned the bag to me.','名前を確認したあと、その袋を返してくれました。'],
['I wrote the same details on a label inside the bag when I got home.','帰宅後、同じ特徴を袋の内側のラベルにも書きました。'],
['Specific details turned a vague lost-item report into information the office could actually use.','具体的な特徴で、あいまいな落とし物報告が職員室で実際に使える情報になりました。']
],false,[['zipper','ファスナー'],['identify','見分ける'],['vague','あいまいな']]),
build('V11-NH-G3-U6-4-041',NH,'Unit 6-4',nhBase,'The Bright Route after the Event',[
['Three friends and I left a school event after sunset in winter.','冬の日没後、友達三人と学校行事を終えて帰りました。'],
['The shortest walking route to the station used a narrow road behind several buildings.','駅までの最短徒歩経路は、いくつかの建物の裏の細い道を通ります。'],
['We had used that road in daylight, but none of us knew how well it was lit at night.','昼間は使ったことがありましたが、夜どのくらい明るいかだれも知りませんでした。'],
['A second route followed a busier street and took about seven minutes longer.','二つ目の経路は人通りの多い道で、約七分長くかかりました。'],
['We checked the map and saw that the second street had shops and larger intersections along the way.','地図を見ると、二つ目の道には店や大きな交差点が続いていました。'],
['From the school gate, we could also see streetlights covering most of that route.','学校の正門から、その経路の大部分に街灯があることも見えました。'],
['Nobody had a reason to reach the station at the earliest possible minute.','だれも一分でも早く駅へ着く必要はありませんでした。'],
['We chose the brighter route and stayed together instead of splitting up.','明るい経路を選び、別れずいっしょに歩きました。'],
['The shops were still open, and other people were walking on the same street.','店はまだ開いており、同じ道をほかの人も歩いていました。'],
['We reached the station with enough time for our train.','電車に十分間に合う時刻に駅へ着きました。'],
['Later, we added that route to the event information for students leaving after dark.','あとで、暗くなってから帰る生徒向け行事案内にその経路を加えました。'],
['A slightly longer walk was a reasonable choice when visibility and surroundings mattered more than speed.','見通しや周囲の環境が速さより大切なとき、少し長い徒歩は妥当な選択でした。']
],false,[['sunset','日没'],['streetlight','街灯'],['visibility','見通し'],['surroundings','周囲の環境']]),
build('V11-NH-G3-U6-4-042',NH,'Unit 6-4',nhBase,'The Advice List before a Decision',[
['I was deciding whether to join an advanced weekend music course.','私は週末の上級音楽講座へ参加するか決めようとしていました。'],
['My music teacher encouraged me to join because the course could improve my performance skills.','音楽の先生は演奏力を伸ばせるとして参加を勧めました。'],
['My homeroom teacher was more careful because the course would use several hours every Saturday.','担任の先生は毎週土曜日に数時間必要なので、より慎重な意見でした。'],
['Both adults knew me well, but their advice focused on different parts of my life.','二人とも私をよく知っていますが、助言は生活の違う部分に注目していました。'],
['I first felt that I had to decide which teacher was right.','最初はどちらの先生が正しいか決めなければならないと思いました。'],
['Instead, I wrote the main reason behind each piece of advice in two columns.','代わりに、二つの欄へそれぞれの助言の主な理由を書きました。'],
['One side included challenge, practice, and future music goals.','一方には挑戦、練習、将来の音楽目標を書きました。'],
['The other included study time, rest, and the travel needed every weekend.','もう一方には勉強時間、休息、毎週の移動を書きました。'],
['Then I added my own goal of keeping one free Saturday each month.','さらに月に一回は土曜日を空けたいという自分の目標を加えました。'],
['I contacted the course and learned that students could miss one session each month with advance notice.','講座へ確認すると、事前連絡で月一回休めると分かりました。'],
['That information let me make a plan that answered both teachers’ concerns and my own goals.','その情報で、両先生の心配と自分の目標の両方に対応する計画を作れました。'],
['Comparing the reasons behind different advice helped me make an independent decision rather than simply choosing a side.','異なる助言の理由を比べることで、片方を選ぶだけでなく自分で判断できました。']
],false,[['advanced','上級の'],['encouraged','勧めた'],['concern','心配事'],['independent decision','自分で考えた決定']])
];
window.V11_BATCH05_G3_PASSAGES=all;
window.V11_BATCH05_G3_META={batch:BATCH,count:all.length,registered:false,grade3:16};
})();
