'use strict';
const fs=require('fs');
const {chromium,webkit}=require('playwright');
const URL=process.env.V11_PREVIEW_URL||'https://yo666ha-boop.github.io/reading-app/v11-preview/';
const EXPECTED=process.env.EXPECTED_SOURCE_SHA||'';
const cases=[
 {textbook:'サンシャイン',grade:'1',major:'PROGRAM 10',section:'PROGRAM 10-2'},
 {textbook:'ニューホライズン',grade:'1',major:'Unit 10',section:'Unit 10-2'},
 {textbook:'サンシャイン',grade:'2',major:'PROGRAM 8',section:'PROGRAM 8-3'},
 {textbook:'ニューホライズン',grade:'2',major:'Unit 7',section:'Unit 7-4'},
 {textbook:'サンシャイン',grade:'3',major:'PROGRAM 7',section:'PROGRAM 7-3'},
 {textbook:'ニューホライズン',grade:'3',major:'Unit 6',section:'Unit 6-4'}
];
const norm=s=>String(s==null?'':s).replace(/\s+/g,' ').trim();
const qtext=s=>norm(String(s||'').replace(/^\d+\.\s*/,''));
const need=(c,m,f)=>{if(!c)f.push(m)};
async function waitSource(request){const end=Date.now()+240000;let last='';while(Date.now()<end){try{const r=await request.get(URL+'PREVIEW_SOURCE.txt?ts='+Date.now(),{timeout:15000});if(r.ok()){last=await r.text();if(!EXPECTED||last.includes('source_sha='+EXPECTED))return last}}catch(_){}await new Promise(r=>setTimeout(r,4000))}throw Error('preview source timeout '+EXPECTED+' last='+last)}
async function setLabel(page,id,label){await page.selectOption('#'+id,{label}).catch(()=>page.selectOption('#'+id,label));await page.waitForTimeout(140)}
async function settle(page){await page.waitForFunction(()=>window.V11_MULTI_PASSAGE_STATE&&window.V11_MULTI_PASSAGE_STATE.extraPassages>=650&&typeof window.V11_SYNC_PASSAGE_VARIANT_UI==='function'&&document.getElementById('v11PassageVariant')&&document.getElementById('v11WordSupportBtn'),null,{timeout:120000});await page.evaluate(()=>window.V11_SYNC_PASSAGE_VARIANT_UI({preserveSelection:false,source:'multi-sync-audit'}));await page.waitForTimeout(300)}
async function snap(page){return page.evaluate(()=>{const p=window.choose&&window.choose();const meta=(window.metaFor&&p)?window.metaFor(p.section):{};const sel=document.getElementById('v11PassageVariant');const panel=document.getElementById('passage');const qs=document.getElementById('questions');const ans=document.getElementById('answers');const slash=document.getElementById('slash');return{id:p&&p.id,section:p&&p.section,title:p&&p.title,sentences:p&&p.sentences||[],translation:p&&p.fullTranslation||'',slashRows:p&&p.slashRows||[],a:p&&p.questions||[],b:p&&Array.isArray(p.questionSetB)?p.questionSetB:(meta&&meta.questionSetB)||[],notes:p&&p.notes||[],supportNotes:p&&p.supportNotes||[],optionCount:sel?sel.options.length:0,value:sel&&sel.value,labels:sel?Array.from(sel.options).map(o=>o.textContent):[],body:panel&&panel.textContent||'',questionsDom:qs&&qs.textContent||'',answersDom:ans&&ans.textContent||'',slashDom:slash&&slash.textContent||'',supportState:window.V11_EASY_SUPPORT_LAST_RENDER||null,supportButton:(document.getElementById('v11WordSupportBtn')||{}).textContent||'',supportChecked:(document.getElementById('v11WordSupportBtn')||{}).getAttribute&&document.getElementById('v11WordSupportBtn').getAttribute('aria-checked')};})}
function verifyQuestionSet(prefix,arr,p,failures){need(Array.isArray(arr)&&arr.length===5,`${prefix}: count=${arr&&arr.length}`,failures);for(let i=0;i<(arr||[]).length;i++){const q=arr[i]||{};need(!!q.prompt,`${prefix}[${i}]: prompt missing`,failures);need(q.answer!=null&&String(q.answer).length>0,`${prefix}[${i}]: answer missing`,failures);need(!!q.evidence,`${prefix}[${i}]: evidence missing`,failures);need(!!q.evidenceJp,`${prefix}[${i}]: evidenceJp missing`,failures);need(!!q.reason,`${prefix}[${i}]: reason missing`,failures);need(norm((p.sentences||[]).join(' ')).includes(norm(q.evidence)),`${prefix}[${i}]: evidence not in selected passage`,failures);need(norm(p.translation).includes(norm(q.evidenceJp)),`${prefix}[${i}]: evidenceJp not in selected translation`,failures)}}
async function verifySelected(page,name,c,kind,expectedId,failures){await page.waitForTimeout(180);const p=await snap(page);const prefix=`${name} ${c.section} ${kind} ${p.id||'NO-ID'}`;need(p.id===expectedId,`${prefix}: selected id mismatch expected=${expectedId}`,failures);need(p.section===c.section,`${prefix}: section=${p.section}`,failures);need(p.sentences.length>0&&norm(p.body).includes(norm(p.sentences[0])),`${prefix}: passage body not synchronized`,failures);need(!!p.translation&&norm(p.body).includes(norm(p.translation)),`${prefix}: full translation not synchronized`,failures);need(p.slashRows.length>0,`${prefix}: slashRows missing`,failures);if(p.slashRows[0]){need(norm(p.slashDom).includes(norm(p.slashRows[0].en)),`${prefix}: slash EN not rendered`,failures);need(norm(p.slashDom).includes(norm(p.slashRows[0].jp)),`${prefix}: slash JP not rendered`,failures)}verifyQuestionSet(prefix+' A',p.a,p,failures);verifyQuestionSet(prefix+' B',p.b,p,failures);
 if(p.a[0]){need(norm(p.questionsDom).includes(qtext(p.a[0].prompt)),`${prefix}: A prompt not rendered`,failures);need(norm(p.answersDom).includes(norm(p.a[0].evidence)),`${prefix}: A evidence not rendered`,failures);need(norm(p.answersDom).includes(norm(p.a[0].evidenceJp)),`${prefix}: A evidenceJp not rendered`,failures);need(norm(p.answersDom).includes(norm(p.a[0].reason)),`${prefix}: A reason not rendered`,failures)}
 const btn=page.locator('#v11WordSupportBtn');if((await btn.getAttribute('aria-checked'))!=='true'){await btn.click();await page.waitForTimeout(150)}const on=await snap(page);need(on.supportChecked==='true',`${prefix}: support switch did not turn ON`,failures);need(on.supportState&&on.supportState.passageId===p.id,`${prefix}: support state passageId=${on.supportState&&on.supportState.passageId}`,failures);need(norm(on.body).includes('単語サポート（多め）')||((on.notes||[]).length===0&&(on.supportNotes||[]).length===0),`${prefix}: support panel not synchronized`,failures);return on}
async function engine(type,name){const browser=await type.launch();const page=await browser.newPage({viewport:name==='webkit'?{width:390,height:844}:{width:1440,height:1000}});const failures=[],results=[],pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e)));await page.goto(URL+'?audit='+Date.now(),{waitUntil:'domcontentloaded',timeout:120000});await settle(page);
 for(const c of cases){await setLabel(page,'textbook',c.textbook);await setLabel(page,'grade',c.grade);await setLabel(page,'major',c.major);await setLabel(page,'section',c.section);await page.selectOption('#pattern','all');await page.selectOption('#v11WordCountFilter','all');await page.evaluate(()=>window.V11_SYNC_PASSAGE_VARIANT_UI({preserveSelection:false,source:'six-case'}));await page.waitForTimeout(220);const first=await snap(page);const sections=[...new Set(first.labels.map(x=>(x.split('｜')[1]||'').trim()).filter(Boolean))];const baseOpt=Array.from(await page.locator('#v11PassageVariant option').evaluateAll(os=>os.map(o=>({value:o.value,label:o.textContent})))).find(o=>/^基本\s*｜/.test(o.label));const extraOpt=Array.from(await page.locator('#v11PassageVariant option').evaluateAll(os=>os.map(o=>({value:o.value,label:o.textContent})))).find(o=>/^追加(?:\d+)?\s*｜/.test(o.label));need(first.optionCount>1,`${name} ${c.section}: passage candidates=${first.optionCount}`,failures);need(!!baseOpt,`${name} ${c.section}: base option missing`,failures);need(!!extraOpt,`${name} ${c.section}: extra option missing`,failures);need(sections.length===1&&sections[0]===c.section,`${name} ${c.section}: exact-section leaked ${sections.join(',')}`,failures);if(baseOpt){await page.selectOption('#v11PassageVariant',baseOpt.value);await verifySelected(page,name,c,'basic',baseOpt.value,failures)}let extraSnap=null;if(extraOpt){await page.selectOption('#v11PassageVariant',extraOpt.value);extraSnap=await verifySelected(page,name,c,'extra',extraOpt.value,failures)}if(baseOpt&&extraOpt){need(baseOpt.value!==extraOpt.value,`${name} ${c.section}: base/extra ids equal`,failures);if(extraSnap){await page.selectOption('#v11PassageVariant',baseOpt.value);await page.waitForTimeout(150);const back=await snap(page);need(back.id===baseOpt.value,`${name} ${c.section}: switching back to basic failed`,failures);need(norm(back.body)!==norm(extraSnap.body),`${name} ${c.section}: body did not change between basic/extra`,failures)}}results.push({...c,optionCount:first.optionCount,baseId:baseOpt&&baseOpt.value,extraId:extraOpt&&extraOpt.value,sections});}
 const runtime=await page.evaluate(()=>({multi:window.V11_MULTI_PASSAGE_STATE||null,ui:window.V11_MULTI_PASSAGE_UI_STATE||null,easy:window.V11_EASY_SUPPORT_NOTES_STATE||null}));need(runtime.multi&&runtime.multi.extraPassages>=650,`${name}: extras=${runtime.multi&&runtime.multi.extraPassages}`,failures);need(pageErrors.length===0,`${name}: page errors ${pageErrors.join(' | ')}`,failures);await browser.close();return{name,results,runtime,pageErrors,failures,pass:failures.length===0}}
(async()=>{const b=await chromium.launch();const ctx=await b.newContext();const src=await waitSource(ctx.request);await b.close();const cr=await engine(chromium,'chromium');const wk=await engine(webkit,'webkit');const report={previewUrl:URL,expectedSourceSha:EXPECTED,previewSource:src.trim(),cases,chromium:cr,webkit:wk,finalPass:cr.pass&&wk.pass,createdAt:new Date().toISOString()};fs.writeFileSync('V11_PREVIEW_MULTI_PASSAGE_UI_AUDIT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.finalPass)process.exit(1)})().catch(e=>{const r={previewUrl:URL,expectedSourceSha:EXPECTED,fatal:String(e&&e.stack||e),finalPass:false,createdAt:new Date().toISOString()};fs.writeFileSync('V11_PREVIEW_MULTI_PASSAGE_UI_AUDIT.json',JSON.stringify(r,null,2));console.error(r.fatal);process.exit(1)});
