(function buildV11Batch10G3Drafts(){
'use strict';
const BATCH='V11-B10-G3-DRAFT-20260829',SS='サンシャイン',NH='ニューホライズン';
function words(s){return (String(s||'').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]);}
function q(type,prompt,answer,evidence,evidenceJp,reason){return {questionType:type,prompt,answer,evidence,evidenceJp,reason};}
function band(level){return level==='STANDARD'?[150,230]:level==='LONG'?[240,330]:[330,450];}
function build(o){const sentences=o.rows.map(r=>r[0]),slashRows=o.rows.map(r=>({en:r[0],jp:r[1]})),fullTranslation=o.rows.map(r=>r[1]).join(''),wc=words(sentences.join(' ')).length,n=sentences.length,at=x=>Math.max(0,Math.min(n-1,x)),ev=i=>sentences[at(i)],jp=i=>slashRows[at(i)].jp;let questions=[q('GIST',`「${o.title}」で中心となった問題を答えなさい。`,jp(1),ev(1),jp(1),'冒頭の問題設定が根拠です。'),q('DETAIL','最初の資料・記録から分かったことを答えなさい。',jp(3),ev(3),jp(3),'本文中の初期情報です。'),q('REASON','最初の判断をそのまま採用しなかった理由を答えなさい。',jp(5),ev(5),jp(5),'見直しが必要になった理由です。'),q('INFERENCE','追加確認からどのようなことが分かりますか。',jp(Math.floor(n/2)),ev(Math.floor(n/2)),jp(Math.floor(n/2)),'本文中盤の追加確認から推論できます。'),q('CONTENT_MATCH','最終的な対応として本文に合うものを答えなさい。',jp(n-2),ev(n-2),jp(n-2),'終盤の対応が根拠です。')];let questionSetB=[q('SUMMARY_FILL','問題を見直した後に行った重要な確認を答えなさい。',jp(Math.min(7,n-1)),ev(Math.min(7,n-1)),jp(Math.min(7,n-1)),'解決の転換点です。'),q('DETAIL','判断を変える決め手になった情報を答えなさい。',jp(Math.max(8,Math.floor(n*0.6))),ev(Math.max(8,Math.floor(n*0.6))),jp(Math.max(8,Math.floor(n*0.6))),'後半の具体情報が根拠です。'),q('REASON','最終案が最初の案よりよかった理由を答えなさい。',jp(n-3),ev(n-3),jp(n-3),'最終判断の理由が述べられています。'),q('CONTENT_MATCH','本文全体の流れに合う結論を答えなさい。',jp(n-2),ev(n-2),jp(n-2),'結論部と一致します。'),q('GIST',`「${o.title}」から得られる学びを答えなさい。`,jp(n-1),ev(n-1),jp(n-1),'最後の文が全体をまとめています。')];if(o.level==='YAMAGUCHI_EXAM'){questions[3]=q('MATERIAL_LINK','本文と資料を合わせて判断すると、計画で最も重要な条件は何ですか。',jp(Math.floor(n/2)),ev(Math.floor(n/2)),jp(Math.floor(n/2)),'本文と資料を結びつける条件です。');questionSetB[0]=q('SUMMARY_FILL','資料を使って計画を修正した内容を答えなさい。',jp(n-4),ev(n-4),jp(n-4),'資料を用いた修正部分です。');if(o.id.endsWith('016'))questionSetB[4]=q('FREE_WRITE_20_30','本文と資料を参考に、冬の行事を安全に運営するための提案を英語20〜30語で書きなさい。','Check the newest snow forecast, use indoor venues within bus capacity, and send each group a clear departure time before the event.',ev(n-1),jp(n-1),'本文の結論を使い、20〜30語で具体的に提案します。');}
return Object.assign({grade:'3',genre:'reading',batch:BATCH,targetWordBand:band(o.level),wordCount:wc,sentences,fullTranslation,slashRows,questions,questionSetB,registered:false,questionStage:'BATCH10_DRAFT_HUMAN_BASE',authorReview:{reviewed:true,timelineCoherent:true,actorPerspectiveClear:true,causalLogicCoherent:true,translationNatural:true}},o,{rows:undefined});}
const passages=[],add=o=>passages.push(build(o));
add({id:'V11-B10-G3-001',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The School Newspaper Correction after a Misquoted Interview',rows:[
['The school newspaper published an article about a new study room in the library.','学校新聞は図書館の新しい自習室について記事を掲載しました。'],
['The article quoted a student as saying that the room was “always silent and perfect for everyone.”','記事では、生徒がその部屋を「いつも静かで誰にとっても完璧だ」と言ったと引用しました。'],
['After publication, the student told the editor that she had actually said the room was quiet only before club activities began.','掲載後、その生徒は「部活動が始まる前は静かだ」と言ったのであり、引用が違うと編集者へ伝えました。'],
['The reporter checked the audio recording and heard the missing time condition clearly.','記者が録音を確認すると、抜けていた時間の条件がはっきり聞こえました。'],
['A shorter note in the reporter’s notebook had left out that phrase.','記者の短いメモでは、その言葉が抜けていました。'],
['The editors realized that the published sentence changed an observation into a much broader claim.','編集部は、掲載文が一つの観察をずっと広い主張に変えてしまったと気づきました。'],
['They did not quietly replace the online article because printed copies had already been distributed.','印刷版がすでに配られていたため、オンライン記事だけを黙って差し替えることはしませんでした。'],
['Instead, the next issue included a correction naming the sentence and giving the accurate wording.','代わりに次号で該当文を示し、正しい内容を載せた訂正文を出しました。'],
['The online version was also updated with a note showing when and why it had changed.','オンライン版も、いつなぜ修正したか分かる注記付きで更新しました。'],
['Before the correction ran, the quoted student checked the new wording against what she meant.','訂正掲載前には、引用された生徒が新しい文が自分の意味と合うか確認しました。'],
['The newspaper then required reporters to check important direct quotations against recordings whenever possible.','新聞部はその後、大切な直接引用は可能な限り録音と照合することにしました。'],
['Readers could see both the mistake and the steps taken to correct it.','読者は間違いだけでなく、それをどう直したかも確認できました。'],
['The editors learned that public trust is protected by visible correction, not by pretending an error never happened.','編集部は、間違いがなかったふりをするのでなく、分かる形で訂正することが信頼を守ると学びました。']
]});
add({id:'V11-B10-G3-002',level:'LONG',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Empty Shop Reused as a Teen Study Space',rows:[
['An empty shop near the station had been unused for more than a year.','駅近くの空き店舗は一年以上使われていませんでした。'],
['A group of high school students proposed turning it into an evening study space for teenagers.','高校生のグループは、そこを十代向けの夜の自習場所に変える案を出しました。'],
['Their first proposal asked for desks, strong Wi-Fi, and opening hours until nine every night.','最初の案では机、安定したWi-Fi、毎晩九時までの開館を求めました。'],
['At a community meeting, nearby residents supported a study room but worried about noise when students left late.','地域会議では自習室には賛成する住民も、遅い時間の退室時の音を心配しました。'],
['A local shop owner also said the space should sometimes be available for small daytime meetings.','近くの店主は、昼間は小さな会合にも使えるようにしてほしいと述べました。'],
['The students realized that calling the building “unused” did not mean the neighborhood had no other needs for it.','生徒たちは「使われていない建物」だからといって地域にほかの必要がないわけではないと気づきました。'],
['They counted how many students used the public library after school for two weeks.','二週間、放課後に公共図書館を使う生徒数を数えました。'],
['The number was highest from five to seven, while only a few students remained after eight.','利用者は五時から七時が最も多く、八時以降は少数でした。'],
['They also asked seventy students what prevented them from studying at home.','さらに七十人の生徒へ家で勉強しにくい理由を尋ねました。'],
['Many mentioned shared rooms or poor internet, but only six said they needed a place after eight thirty.','多くは共有の部屋や弱いネット環境を挙げましたが、八時半以降の場所が必要という人は六人だけでした。'],
['Using this evidence, the group revised the plan to open from four thirty to eight on weekdays.','この情報を使い、平日は四時半から八時まで開く案に直しました。'],
['They proposed quiet departure signs and asked volunteers to stand outside for the first month.','静かに帰る表示を置き、最初の一か月はボランティアが外に立つ案も出しました。'],
['The desks were chosen so they could be folded and moved against the wall.','机は折りたたみ式で壁際へ動かせる物を選びました。'],
['That allowed two daytime community meetings each week without removing the study equipment.','そのため自習設備をなくさず、週二回は昼の地域会議に使えるようになりました。'],
['The city agreed to a three-month trial instead of approving the arrangement permanently.','市は永久的に認めるのでなく、三か月の試行に同意しました。'],
['During the trial, users signed in anonymously by age group and time so demand could be measured without collecting names.','試行中は名前を集めず、年代と時刻だけで利用記録を残しました。'],
['Residents received a phone number for reporting repeated noise, and only two early complaints were recorded.','住民には繰り返す騒音を連絡する番号を知らせ、初期に二件の苦情だけが記録されました。'],
['After volunteers reminded users about the departure rule, no further complaints came in the final six weeks.','退室ルールを利用者へ再確認すると、最後の六週間は新しい苦情がありませんでした。'],
['Attendance was strongest before seven thirty, supporting the shorter hours chosen in the revised plan.','利用者は七時半前が最も多く、修正版の短い開館時間を支持する結果になりました。'],
['The final agreement kept the study space while reserving weekday mornings for community use.','最終合意では自習室を残し、平日の午前は地域利用に確保しました。'],
['The students learned that a strong community proposal responds to competing needs with evidence and a testable compromise.','生徒たちは、よい地域提案は異なる必要に情報と試せる妥協案で応えるものだと学びました。']
]});
add({id:'V11-B10-G3-003',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The Tree-Planting Project That Chose One Species',rows:[
['A science class planned to plant thirty young trees along a school path.','理科のクラスは学校の道沿いに若い木を三十本植える計画を立てました。'],
['The first plan used only one fast-growing species because it was cheap and easy to order.','最初は安く注文しやすい成長の速い一種類だけを使う予定でした。'],
['A local gardener asked what would happen if one disease affected that species.','地域の園芸家が、その種類だけに病気が広がったらどうなるかと尋ねました。'],
['The students researched the tree and learned that several nearby streets had already planted the same kind.','生徒たちが調べると、近くの通りにも同じ種類が多く植えられていました。'],
['They also found that different native trees provided food at different seasons for birds and insects.','また、異なる在来種は季節ごとに鳥や昆虫へ違う食べ物を与えると分かりました。'],
['The class realized that low price was only one part of a long-term planting decision.','クラスは、安さは長期的な植樹判断の一部分にすぎないと気づきました。'],
['They asked the gardener to suggest species that fit the same soil and available space.','同じ土と空間に合う種類を園芸家へ尋ねました。'],
['The revised plan used three native species in groups of ten.','修正版では三種類の在来種を十本ずつ使いました。'],
['The total cost was slightly higher, so the class reduced decorative signs rather than the number of trees.','費用は少し上がったため、木の本数でなく飾りの看板を減らしました。'],
['Students recorded where each species was planted so future classes could compare survival and growth.','将来のクラスが生存率と成長を比べられるよう、各種類の植えた場所も記録しました。'],
['A year later, all three kinds had surviving trees even though one type had lost several branches in a storm.','一年後、一種類は嵐で枝を何本か失いましたが、三種類すべてに生き残った木がありました。'],
['The project had become both a planting activity and a long-term observation.','その活動は植樹だけでなく長期観察にもなりました。'],
['The class learned that diversity can reduce one shared risk while supporting different forms of life.','クラスは、多様性が一つの共通リスクを減らし、さまざまな生き物を支えられると学びました。']
]});
add({id:'V11-B10-G3-004',level:'YAMAGUCHI_EXAM',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Art Festival, Workshop Timetable, Shuttle Map, and Ticket Rules',materialData:{workshops:[['Printmaking','10:20','50 min'],['Clay','11:10','60 min'],['Poster Design','13:20','45 min']],shuttles:[['Station','Festival Gate','09:35','09:55'],['Festival Gate','Station','15:10','15:30']],walkingMinutes:{gateToHall:8,hallToStudio:12,studioToGallery:6},ticketRules:['One workshop ticket per visitor before noon','Reserved workshop check-in closes 10 minutes before start','Gallery entry is free after 12:30']},rows:[
['A group of four students planned a Saturday visit to a city art festival.','四人の生徒が土曜日に市の芸術祭へ行く計画を立てました。'],
['They wanted to join one workshop, see a student gallery, and return to the station by three thirty.','一つの体験講座に参加し、生徒ギャラリーを見て、三時半までに駅へ戻りたいと考えました。'],
['Their first choice was the clay workshop because all four students had never tried it.','四人とも未経験だったため、最初は粘土講座を選びました。'],
['The workshop table showed that clay began at eleven ten and lasted sixty minutes.','講座表では粘土は十一時十分開始で六十分間でした。'],
['The ticket rule said a reserved visitor had to check in ten minutes before a workshop began.','チケット規則では予約者は開始十分前までに受付を済ませる必要がありました。'],
['The group’s shuttle reached the festival gate at nine fifty-five, so that seemed to leave plenty of time.','グループのシャトルは九時五十五分に会場入口へ着くため、時間は十分に見えました。'],
['However, the map placed the ticket hall eight minutes from the gate and the clay studio twelve more minutes from the hall.','しかし地図では、チケット会場は入口から徒歩八分、粘土教室はさらに十二分でした。'],
['One student first suggested visiting the gallery before checking in for the workshop.','一人の生徒は講座の受付前にギャラリーを見ることを提案しました。'],
['The gallery was six minutes beyond the studio, so that plan added another twelve minutes for going there and back.','ギャラリーは教室からさらに六分なので、往復で十二分余計にかかります。'],
['The group decided not to use a schedule that depended on every walk taking exactly the minimum time.','グループは、すべての移動が最短時間どおりであることに頼る予定は使わないと決めました。'],
['They also noticed a rule allowing only one workshop ticket per visitor before noon.','さらに正午前は一人一枚の講座チケットだけという規則にも気づきました。'],
['That meant they could reserve clay without worrying about keeping time for a second morning workshop.','そのため、午前に二つ目の講座を入れる時間を考えず粘土講座一つに集中できました。'],
['They planned to go directly from the gate to the ticket hall, then to the clay studio.','入口から直接チケット会場へ行き、その後粘土教室へ向かうことにしました。'],
['Even if those walks took five extra minutes in total, they would still reach the studio before the eleven o’clock check-in limit.','二つの移動が合計五分余計にかかっても、十一時の受付締切より前に教室へ着けます。'],
['Clay would finish at about twelve ten.','粘土講座は十二時十分ごろ終わります。'],
['The gallery rule said entry became free after twelve thirty, so waiting twenty minutes would save the group’s gallery fee.','ギャラリーは十二時半以降無料になるため、二十分待てば入場料を節約できます。'],
['They used that time for lunch near the studio instead of crossing the grounds twice.','その時間を、会場を二度横切るのでなく教室近くで昼食に使いました。'],
['At twelve thirty, they walked six minutes to the gallery and spent just over an hour there.','十二時半にギャラリーへ六分歩き、一時間余り見学しました。'],
['Their return shuttle left the festival gate at three ten.','帰りのシャトルは会場入口を三時十分に出ます。'],
['The students set a two forty-five meeting time at the ticket hall so they could walk to the gate without rushing.','急がず入口へ歩けるよう、二時四十五分にチケット会場で集合することにしました。'],
['They also wrote the shuttle number and the gate location on each person’s paper schedule.','各自の紙の予定表にシャトル番号と入口の場所も書きました。'],
['On the festival day, a crowded path slowed them for several minutes, but the extra time in the plan absorbed the delay.','当日は混雑した道で数分遅れましたが、予定に余裕があり対応できました。'],
['They completed the clay workshop, visited the gallery, and boarded the three ten shuttle.','四人は粘土講座とギャラリー見学を終え、三時十分のシャトルに乗りました。'],
['The shuttle reached the station at three thirty, exactly meeting their final deadline.','シャトルは三時半に駅へ着き、最終の時間条件を満たしました。'],
['The group learned that a workable itinerary must combine start times, rules, walking time, and a small safety margin.','グループは、実行できる予定には開始時刻、規則、徒歩時間、少しの余裕を組み合わせる必要があると学びました。']
]});
add({id:'V11-B10-G3-005',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The Oral History Recording with Two Memories of One Day',rows:[
['A history club interviewed two residents about a flood that had happened thirty years earlier.','歴史部は三十年前に起きた洪水について二人の住民へ聞き取りをしました。'],
['One resident remembered the river reaching the school gate before noon.','一人は正午前に川の水が学校の門まで来たと覚えていました。'],
['The other remembered seeing students leave school before the water reached the main road.','もう一人は水が大通りへ来る前に生徒が学校を出たと覚えていました。'],
['At first, club members tried to decide which person had the correct order.','最初、部員はどちらの順番が正しいか決めようとしました。'],
['They then found an old newspaper saying the school closed at eleven forty but giving no exact time for the river level.','その後、古い新聞に学校は十一時四十分に閉まったとありましたが、川の水位時刻は書かれていませんでした。'],
['The students realized that memory and the written source answered different parts of the question.','生徒たちは、記憶と文書資料が質問の別々の部分に答えていると気づきました。'],
['They checked a city report and found hourly water measurements from a bridge farther downstream.','市の報告書も調べ、下流の橋で一時間ごとの水位記録を見つけました。'],
['Those numbers showed a rapid rise around noon but could not prove the exact minute water reached the school gate.','数字は正午ごろ急上昇を示しましたが、学校門へ到達した正確な時刻までは証明できませんでした。'],
['The exhibit therefore did not choose one memory as the winner.','そこで展示は一方の記憶だけを正しいものとして選びませんでした。'],
['It presented both recollections, the school closing time, and the measured river trend separately.','二つの記憶、学校の閉校時刻、測定された川の変化を分けて示しました。'],
['A note explained which details were memories and which came from documents.','どの内容が記憶でどれが文書によるものか注記しました。'],
['Visitors could compare the sources without being told that uncertainty had disappeared.','来場者は不確かさが消えたとされることなく資料を比べられました。'],
['The club learned that careful history can preserve different memories while marking what evidence can and cannot confirm.','歴史部は、丁寧な歴史記述は異なる記憶を残しつつ証拠で確認できる範囲を示すものだと学びました。']
]});
add({id:'V11-B10-G3-006',level:'LONG',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The School Uniform Repair Project and the Question of Waste',rows:[
['The environmental committee noticed that many usable school uniform items were discarded after graduation.','環境委員会は卒業後にまだ使える制服が多く捨てられていることに気づきました。'],
['Its first idea was a free exchange where families could leave any old item and take another one.','最初は家族が古い制服を自由に置き、別の物を無料で持ち帰る交換会を考えました。'],
['A teacher asked what would happen to shirts with broken buttons or skirts with small tears.','先生は、ボタンが取れたシャツや小さく破れたスカートをどうするのか尋ねました。'],
['Students had assumed that every donated item would be ready to wear.','生徒たちは寄付された物はすべてすぐ着られると思い込んでいました。'],
['They inspected eighty stored items and found that twenty-three needed a simple repair.','保管されていた八十着を確認すると、二十三着は簡単な修理が必要でした。'],
['Only four were too damaged to be safely reused as clothing.','衣服として安全に再利用できないほど傷んでいたのは四着だけでした。'],
['The committee asked a local sewing group what repairs students could learn to do safely.','委員会は地域の裁縫グループに、生徒が安全に学べる修理を尋ねました。'],
['The volunteers suggested buttons, loose hems, and small straight tears, while difficult repairs should be handled by adults.','ボタン、ほどけた裾、小さな直線の破れは可能で、難しい修理は大人が行うべきだと提案されました。'],
['The group also estimated material costs and found that thread, buttons, and patches for one term would cost less than buying five new shirts.','糸、ボタン、当て布の一学期分は新品シャツ五枚を買うより安いと見積もれました。'],
['However, not every family wanted secondhand clothing, and the committee did not want participation to feel compulsory.','ただし、すべての家庭が中古制服を望むわけではなく、参加を強制のようにしたくありませんでした。'],
['The revised project therefore separated donation, repair, and selection into three optional steps.','修正版では寄付、修理、選択を三つの任意の段階に分けました。'],
['Families could donate without taking anything, and students could attend a repair lesson without donating clothing.','家族は受け取らず寄付だけでき、生徒は制服を寄付せず修理教室だけ参加できました。'],
['Clean repaired items were displayed by size without showing the previous owner’s name.','洗って修理した制服は前の持ち主の名前を見せず、サイズ別に並べました。'],
['The four unusable items were cut into practice cloth after identifying parts that could still be used.','使えない四着は、まだ使える部分を確認して練習用の布にしました。'],
['During the first term, thirty-one uniform pieces found new users.','最初の学期には三十一着の制服が新しい利用者へ渡りました。'],
['Students repaired nineteen items themselves under adult supervision, and six more were repaired by volunteers.','生徒は大人の監督下で十九着を直し、さらに六着をボランティアが修理しました。'],
['A short survey showed that families valued lower cost, but several also liked learning how to repair ordinary clothes.','短いアンケートでは費用の安さが評価され、普段の服を直す学びを好む家庭もありました。'],
['The committee reported both reuse numbers and the limits of what student repair could safely handle.','委員会は再利用数だけでなく、生徒が安全に直せる範囲の限界も報告しました。'],
['The program continued as a voluntary service rather than being treated as the only correct way to obtain a uniform.','その活動は制服を手に入れる唯一の正解とはせず、任意のサービスとして続きました。'],
['The students learned that reducing waste can involve repair skills, choice, cost, and safety at the same time.','生徒たちは、ごみ削減には修理技術、選択、費用、安全を同時に考えられると学びました。']
]});
add({id:'V11-B10-G3-007',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The AI Translation Used in a Friendship Letter',rows:[
['Nao wrote a short Japanese letter to a partner school and used an AI tool to make an English draft.','奈緒は交流校へ短い日本語の手紙を書き、AIツールで英語の下書きを作りました。'],
['The Japanese sentence thanked her partner for “taking care of me during the visit.”','日本語の文は「訪問中にお世話になりました」と感謝していました。'],
['The English draft used a phrase that sounded like the partner had been responsible for a sick person.','英語の下書きは、相手が病人の世話をしたように聞こえる表現になっていました。'],
['Nao understood every word separately, so at first she thought the translation was accurate.','奈緒は単語一つ一つは分かったため、最初は正確だと思いました。'],
['Her teacher explained that matching dictionary meanings does not always preserve tone or social meaning.','先生は、辞書的な意味が合っても語調や社会的な意味が保たれるとは限らないと説明しました。'],
['Nao reread the visit notes and wrote what she really meant: gratitude for kindness, guidance, and time together.','奈緒は訪問記録を読み返し、本当に伝えたいのは親切、案内、一緒に過ごした時間への感謝だと整理しました。'],
['She changed the English to thank her partner for welcoming her and helping her during the visit.','英語を、訪問中に歓迎し助けてくれたことへ感謝する文に変えました。'],
['A classmate read the English without seeing the Japanese and explained the meaning back to Nao.','クラスメートが日本語を見ず英語だけを読み、その意味を奈緒へ説明し返しました。'],
['The explanation now matched Nao’s intention without adding illness or duty.','説明は病気や義務の意味を加えず、奈緒の意図と合っていました。'],
['She kept the AI draft in her notes so she could compare it with the revised sentence.','奈緒は修正文と比べられるようAIの下書きも記録に残しました。'],
['The final letter sounded natural to the reader and still expressed the original gratitude.','最終の手紙は読み手に自然で、元の感謝も表していました。'],
['Nao learned to treat automatic translation as a draft whose meaning and tone still require human review.','奈緒は、自動翻訳は意味と語調を人が確認すべき下書きとして扱うと学びました。']
]});
add({id:'V11-B10-G3-008',level:'YAMAGUCHI_EXAM',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Coastal Cleanup, Tide Chart, Bus Schedule, and Collection Zones',materialData:{tides:[['Low','08:40'],['High','14:25']],buses:[['School','Harbor','07:50','08:20'],['Harbor','School','12:45','13:15'],['Harbor','School','15:20','15:50']],zones:[['A','near harbor','08:30-12:00'],['B','rocky shore','low tide only'],['C','dune path','09:00-14:00']]},rows:[
['A science club planned a coastal cleanup with twenty-four students and four teachers.','科学部は生徒二十四人と先生四人で海岸清掃を計画しました。'],
['They wanted every team to collect litter while avoiding the rocky shore when the tide was high.','各班がごみを集めつつ、満潮時の岩場を避けたいと考えました。'],
['The tide chart showed low tide at eight forty and high tide at two twenty-five.','潮位表では干潮が八時四十分、満潮が二時二十五分でした。'],
['Their bus from school would reach the harbor at eight twenty.','学校からのバスは八時二十分に港へ着きます。'],
['The map divided the coast into Zone A near the harbor, Zone B on the rocky shore, and Zone C along a dune path.','地図は海岸を港近くのA、岩場のB、砂丘道沿いのCに分けていました。'],
['A note beside Zone B said that volunteers should enter it only around low tide.','Bの注記には、干潮の前後だけ入るべきだとありました。'],
['At first, the club planned to visit A, then C, and leave B until after lunch.','最初、A、Cの順に行き、Bは昼食後に残す計画でした。'],
['One teacher pointed out that this order ignored the changing tide even though B was the only tide-dependent zone.','先生の一人が、潮に左右される唯一のBを後回しにするのは潮の変化を無視していると指摘しました。'],
['The group compared the arrival time with the low-tide time and saw a useful opportunity.','到着時刻と干潮時刻を比べると、よい時間帯を使えると分かりました。'],
['After a ten-minute safety talk at the harbor, a supervised team could reach Zone B while the tide was still near its low point.','港で十分の安全説明後、監督付き班は潮がまだ低いうちにBへ行けます。'],
['The club changed the order so two teams handled Zone B first while the other teams began in Zone A.','そこで二班が最初にBを担当し、ほかの班はAから始める順序に変えました。'],
['Teachers carried a phone and a first-aid bag with each rocky-shore team.','岩場へ行く各班には先生が携帯電話と救急袋を持って同行しました。'],
['Students were told not to climb wet rocks even if they could see litter beyond the marked line.','印の先にごみが見えても濡れた岩を登らないよう生徒へ伝えました。'],
['By ten thirty, the Zone B teams had returned to the harbor and no new group entered the rocks.','十時半までにB班は港へ戻り、その後は新しい班を岩場へ入れませんでした。'],
['The teams then rotated through Zone A and the dune path in Zone C.','その後、各班はAとCの砂丘道を交代で担当しました。'],
['Zone C was open from nine to two, so it did not require the same early start as Zone B.','Cは九時から二時まで開いているため、Bほど早く始める必要はありませんでした。'],
['The bus schedule offered a twelve forty-five return and a later three twenty return.','帰りのバスは十二時四十五分と、より遅い三時二十分がありました。'],
['The group chose the twelve forty-five bus because all planned zones could be completed before noon.','予定した区域は正午前に終えられるため、十二時四十五分のバスを選びました。'],
['Using the later bus would add time near the coast as the tide continued to rise without adding a necessary task.','遅いバスでは必要な作業を増やさず、潮が上がる海岸での滞在時間だけが増えます。'],
['At eleven forty-five, everyone met at the harbor for a count of students, bags, and collected litter.','十一時四十五分、全員が港へ集まり、生徒、袋、集めたごみを数えました。'],
['The teachers kept fifteen minutes free before walking to the bus stop in case a team returned late.','班の帰りが遅い場合に備え、バス停へ向かう前に十五分の余裕を残しました。'],
['All teams were present on time, and the group left the coast well before high tide.','全班が時間どおりそろい、満潮よりかなり前に海岸を離れました。'],
['Their report later explained that the route order came from tide limits rather than from which zone was closest.','後の報告では、区域の近さではなく潮の条件から順序を決めたと説明しました。'],
['The cleanup collected litter from all three zones without treating the schedule as if the coast stayed unchanged all day.','海岸が一日中同じ状態だと考えず、三区域すべてからごみを集められました。'],
['The club learned that safe fieldwork combines environmental timing, transport, zones, supervision, and extra time for unexpected delay.','科学部は、安全な野外活動には自然の時刻、交通、区域、監督、予想外の遅れへの余裕を組み合わせる必要があると学びました。']
]});
add({id:'V11-B10-G3-009',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The Debate Team That Changed Its Claim after Reading the Source',rows:[
['A debate team prepared to argue that students learned better whenever homework was reduced.','討論チームは、宿題を減らせば必ず生徒の学習が良くなると主張する準備をしていました。'],
['One member found a report showing higher test scores in a class that had shortened its weekly homework.','一人が、週の宿題を短くしたクラスでテスト点が上がったという報告を見つけました。'],
['The team first planned to use that result as proof of its broad claim.','チームは最初、その結果を広い主張の証明として使う予定でした。'],
['When they read the full report, they learned that the class had also added daily review time at school.','報告全体を読むと、そのクラスは学校で毎日の復習時間も追加していたと分かりました。'],
['The study included only two classes and lasted one term.','調査は二クラスだけで一学期間のものでした。'],
['The students realized that the source supported a possible approach, not a rule that applied everywhere.','生徒たちは、その資料は一つの可能な方法を支持しても、どこでも通用する規則を証明してはいないと気づきました。'],
['They changed their claim to say that carefully designed shorter homework can work when useful review is preserved.','そこで「大切な復習を保てば、よく設計された短い宿題は有効な場合がある」と主張を変えました。'],
['They also prepared to explain the small sample and the added review period.','少ない対象数と追加された復習時間も説明できるようにしました。'],
['A second source about student sleep gave another reason to test shorter assignments but did not measure test scores.','睡眠についての別資料は宿題短縮を試す別の理由を示しましたが、テスト点は測っていませんでした。'],
['The team used each source only for the point it actually measured.','チームは各資料を実際に測った点についてだけ使いました。'],
['Their final argument sounded less absolute but was easier to defend under questions.','最終主張は断定的ではなくなりましたが、質問を受けても説明しやすくなりました。'],
['The judges praised the team for acknowledging limits instead of hiding them.','審査員は限界を隠さず認めたことを評価しました。'],
['The students learned that responsible argument may require changing a claim when evidence is narrower than expected.','生徒たちは、証拠が予想より限定的なら責任ある議論では主張を変える必要があると学びました。']
]});
add({id:'V11-B10-G3-010',level:'LONG',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Community Language Map and Names That Residents Preferred',rows:[
['A youth council wanted to make a language map showing words used for places in a multicultural neighborhood.','青少年会議は、多文化地域で場所を呼ぶ言葉を示す言語地図を作ろうとしました。'],
['Its first draft used official street names and one translated name for every public building.','最初の案では公式の通り名と、各公共施設につき一つの翻訳名を使いました。'],
['During a review, residents pointed out that several places were known by different names in different families.','確認会では、いくつかの場所が家庭によって違う名前で呼ばれていると住民が指摘しました。'],
['One market had an official Japanese name, an older Korean nickname, and a newer English name used by young visitors.','ある市場には日本語の公式名、古い韓国語の愛称、若い来訪者が使う新しい英語名がありました。'],
['The council had planned to choose whichever translated name appeared most often in an online search.','会議はオンライン検索で最も多く出る翻訳名を選ぶ予定でした。'],
['Residents warned that search frequency might reflect tourists or websites rather than people who actually lived nearby.','住民は、検索の多さが地域住民ではなく観光客やウェブサイトを反映する可能性を指摘しました。'],
['The council therefore designed a short survey asking which name people used, which language they preferred, and whether another name should also appear.','そこで、使う名前、希望言語、別名も載せるべきかを尋ねる短い調査を作りました。'],
['Paper copies were available at the library and market, while an online version used the same questions.','紙版を図書館と市場に置き、オンライン版も同じ質問にしました。'],
['Respondents could skip questions about identity and did not have to give their names.','回答者は個人情報に関する質問を飛ばせ、名前も書く必要がありませんでした。'],
['The results showed that no single label was preferred by everyone.','結果では、全員が好む一つの表示はありませんでした。'],
['Older residents often used the Korean nickname, many official documents used the Japanese name, and younger visitors recognized the English form.','高齢住民は韓国語の愛称をよく使い、公式文書は日本語名が多く、若い来訪者は英語形を認識していました。'],
['Instead of ranking the names from best to worst, the council showed the official name first and added locally used alternatives where space allowed.','最良から順に順位付けせず、公式名を最初に示し、スペースがあれば地域で使う別名も加えました。'],
['A note explained that the alternatives came from resident responses rather than being exact translations.','別名は正確な翻訳ではなく住民回答に基づくと注記しました。'],
['For a small map symbol with little space, the printed version used a number linked to a longer name list on the side.','小さな地図記号で余白がない所は、番号を使って横の詳しい名前一覧につなげました。'],
['Three residents reviewed the final spellings before printing.','印刷前に住民三人が最終のつづりを確認しました。'],
['One spelling was changed because the council had copied a form used by an outside travel site rather than the local association.','一つのつづりは、地域団体でなく外部旅行サイトの形を写していたため修正されました。'],
['The map also included a web form where residents could suggest future corrections.','地図には今後の訂正を提案できるウェブフォームも付けました。'],
['When the map was displayed, visitors said multiple names helped them connect official signs with words they heard in conversation.','展示後、来訪者は複数の名前が公式表示と会話で聞く言葉を結びつけるのに役立つと話しました。'],
['Residents did not all agree on preferred labels, but the map no longer treated one group’s wording as the only natural choice.','住民の好みは完全には一致しませんでしたが、一つの集団の呼び方だけを当然の選択とはしなくなりました。'],
['The council learned that respectful labeling requires asking whose usage a name represents and showing uncertainty when preferences differ.','青少年会議は、敬意ある表示には名前が誰の使い方を表すか確かめ、好みが違うときはその違いを示す必要があると学びました。']
]});
add({id:'V11-B10-G3-011',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The School Garden Camera That Missed Night Visitors',rows:[
['Students placed a motion camera beside the school garden to learn which animals visited the vegetables.','生徒たちは野菜を訪れる動物を調べるため学校菜園のそばに動作カメラを置きました。'],
['After one week, the camera showed sparrows, two cats, and many daytime insects.','一週間で、スズメ、二匹の猫、多くの昼の昆虫が写りました。'],
['The first report said that no animals visited the garden at night.','最初の報告は夜に動物は来ないと書きました。'],
['A teacher asked whether the camera had actually been able to record through the entire night.','先生は、そのカメラが本当に夜通し録画できていたか尋ねました。'],
['The battery log showed that power often fell too low around eleven thirty.','電池記録を見ると、午後十一時半ごろ電力不足になることが多いと分かりました。'],
['The students realized that missing night pictures could mean missing observation time rather than missing animals.','生徒たちは、夜の写真がないのは動物がいないのでなく観察時間が欠けている可能性があると気づきました。'],
['They replaced the batteries and lowered the number of unnecessary daytime triggers caused by moving leaves.','電池を替え、動く葉による不要な昼の反応を減らしました。'],
['For the second week, the camera remained active until morning on six of seven nights.','二週目は七夜のうち六夜で朝までカメラが動きました。'],
['It recorded a raccoon dog twice and a small animal that students could not identify clearly.','タヌキが二回と、生徒がはっきり特定できない小動物が写りました。'],
['The revised report listed both the observed species and the one night when recording still failed.','修正版は観察した種類と、録画に失敗した一夜の両方を記しました。'],
['It did not claim that the camera had found every possible visitor.','カメラがすべての来訪動物を見つけたとは主張しませんでした。'],
['Future groups could now separate “not recorded” from “not present.”','今後の班は「記録されなかった」と「いなかった」を分けられるようになりました。'],
['The students learned that an observation limit is part of the evidence and must be reported with the result.','生徒たちは、観察の限界も証拠の一部であり結果と一緒に報告すべきだと学びました。']
]});
add({id:'V11-B10-G3-012',level:'YAMAGUCHI_EXAM',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Library Event, Room Capacities, Sign-Up Table, and Walking Times',materialData:{events:[['Author Talk','Hall A','13:00','40 min'],['Book Repair','Room C','14:00','50 min'],['Story Lab','Room B','15:10','45 min']],capacity:{'Hall A':80,'Room B':24,'Room C':16},signup:{'Author Talk':68,'Book Repair':16,'Story Lab':20},walkingMinutes:{'Hall A-Room C':9,'Room C-Room B':7,'entrance-Hall A':5}},rows:[
['A group of students volunteered at a city library event with three afternoon programs.','生徒グループが市立図書館の三つの午後行事でボランティアをしました。'],
['They needed to guide registered visitors while keeping every room within its safe capacity.','登録した来場者を案内しつつ、各部屋を安全定員以内に保つ必要がありました。'],
['The schedule listed an author talk in Hall A at one, book repair in Room C at two, and a story lab in Room B at three ten.','予定表では一時にAホールで作家講演、二時にC室で本の修理、三時十分にB室で物語教室でした。'],
['The capacity table showed eighty seats in Hall A, sixteen in Room C, and twenty-four in Room B.','定員表ではAホール八十人、C室十六人、B室二十四人でした。'],
['The sign-up list already had sixty-eight names for the talk, sixteen for repair, and twenty for the story lab.','申込表には講演六十八人、修理十六人、物語教室二十人が登録されていました。'],
['At first, the volunteers planned to tell walk-in visitors that every program still had space because no list had reached the building’s total capacity.','最初、建物全体の定員には達していないのでどの行事も当日参加できると案内する予定でした。'],
['A librarian explained that capacity applied separately to each room, not to the building as one large space.','司書は、定員は建物全体ではなく各部屋ごとに適用されると説明しました。'],
['That meant the repair workshop was already full even though Hall A still had twelve seats.','そのためAホールには十二席あっても、修理教室はすでに満員でした。'],
['The volunteers marked book repair as “registration full” before doors opened.','ボランティアは開場前に本の修理を「受付終了」と表示しました。'],
['They kept a waiting list rather than promising that unused seats in another room could be transferred.','別の部屋の空席を移せると約束せず、キャンセル待ち名簿を作りました。'],
['The walking-time map also showed nine minutes from Hall A to Room C and seven minutes from Room C to Room B.','移動時間図ではAホールからC室九分、C室からB室七分でした。'],
['One student wanted to volunteer at the talk until one forty and then guide the repair group at two.','一人の生徒は一時四十分まで講演を手伝い、二時から修理班を案内したいと考えました。'],
['Because the talk lasted forty minutes, leaving exactly at one forty would give only eleven minutes before the repair workshop.','講演は四十分なので、一時四十分ちょうどに出れば修理開始まで十一分しかありません。'],
['A nine-minute walk would leave almost no time for a delayed ending, crowded hallway, or checking the waiting list.','九分歩くと、終了の遅れ、混雑、キャンセル待ち確認の余裕がほとんどありません。'],
['The team assigned a different volunteer who was already near Room C to handle repair check-in.','そこでC室の近くにいる別のボランティアを修理受付に割り当てました。'],
['The student at Hall A stayed through the end and then helped direct general visitors instead of rushing across the library.','Aホールの生徒は最後まで残り、図書館内を急ぐのでなく一般来場者の案内をしました。'],
['At one fifty-five, one registered repair visitor canceled by phone.','一時五十五分、修理の予約者一人が電話でキャンセルしました。'],
['The first person on the waiting list was nearby and could reach Room C before two, so that place was offered to her.','キャンセル待ち一番の人は近くにいて二時前にC室へ着けるため、その席を案内しました。'],
['The story lab still had four open places, and walk-in visitors could register for those without affecting the full repair room.','物語教室には四席あり、当日参加者は満員の修理教室に影響せず登録できました。'],
['After repair ended at two fifty, the seven-minute walk to Room B left enough time before the story lab at three ten.','修理は二時五十分に終わり、B室まで七分なので三時十分の物語教室まで十分時間がありました。'],
['Two volunteers moved together with the repair group members who had also registered for the story lab.','修理参加者で物語教室にも登録した人とボランティア二人が一緒に移動しました。'],
['They arrived before three, leaving time for the librarian to confirm the new room count.','三時前に到着し、司書が新しい部屋の人数を確認する時間もありました。'],
['No room exceeded its capacity, and no visitor was told that space in one program guaranteed space in another.','どの部屋も定員を超えず、一つの行事の空席が別行事の席を保証すると案内されることもありませんでした。'],
['The final volunteer notes listed capacity, sign-up status, and walking time beside each program.','最終の案内メモには各行事の定員、申込状況、移動時間を並べて書きました。'],
['The students learned that safe event guidance requires linking room-specific limits with actual travel time and current registration.','生徒たちは、安全な行事案内には部屋ごとの定員、実際の移動時間、現在の申込状況を結びつける必要があると学びました。']
]});
add({id:'V11-B10-G3-013',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The Science Exhibit That Used a Model without Showing Its Scale',rows:[
['A science class built a model of the solar system for a school exhibition.','理科のクラスは学校展示のため太陽系模型を作りました。'],
['The planets were arranged in the correct order, and larger planets were shown with larger balls.','惑星は正しい順番で、大きい惑星は大きい球で表しました。'],
['A visitor asked whether the spaces between the balls were also in the same scale as their sizes.','来場者が、球同士の間隔も大きさと同じ縮尺なのか尋ねました。'],
['The students realized that they had shortened the distances greatly so the model would fit in one classroom.','生徒たちは、一教室に収めるため距離を大幅に縮めていたと気づきました。'],
['Nothing on the display explained that the size scale and distance scale were different.','展示には大きさの縮尺と距離の縮尺が違うことが何も説明されていませんでした。'],
['A neat model could therefore create a false picture even when every planet name and order was correct.','そのため、惑星名と順番が正しくても整った模型が誤ったイメージを作る可能性がありました。'],
['The class measured the display and wrote a short label describing what the model represented accurately.','クラスは展示を測り、模型が正しく表している部分を説明する短い表示を作りました。'],
['A second label said clearly that the spaces between planets were compressed and were not to scale.','二つ目の表示には、惑星間の距離は縮められており縮尺どおりではないと明記しました。'],
['They added a long hallway strip showing several relative distances with a different scale.','さらに別の縮尺でいくつかの相対距離を示す長い廊下表示を加えました。'],
['Visitors could now use the classroom model for order and relative size, then the strip for distance.','来場者は教室模型で順番と大きさの関係を、廊下表示で距離を学べました。'],
['The class did not claim that either display showed every property at once.','クラスはどちらの展示もすべての性質を一度に表すとは主張しませんでした。'],
['The exhibit became clearer because its limits were visible instead of hidden.','模型の限界を隠さず見せることで展示はより分かりやすくなりました。'],
['The students learned that a model needs an explanation of scale whenever viewers might assume more than it actually represents.','生徒たちは、見る人が模型以上のことを正確だと思う可能性があるとき縮尺説明が必要だと学びました。']
]});
add({id:'V11-B10-G3-014',level:'LONG',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Youth Council Proposal for a Phone-Free Community Hour',rows:[
['A youth council proposed a “phone-free community hour” in a public square on Sunday afternoons.','青少年会議は日曜午後の公共広場で「スマホなし地域時間」を行う提案をしました。'],
['The first idea asked everyone in the square to avoid phones from two to three so people would talk face to face.','最初の案は、人々が直接話せるよう二時から三時まで広場の全員にスマホを使わないよう求めるものでした。'],
['Some students liked the idea, but a parent said she needed her phone to receive messages from a child with a medical condition.','賛成する生徒もいましたが、ある保護者は持病のある子どもから連絡を受けるため携帯が必要だと話しました。'],
['A food seller used a phone for cashless payments, and a volunteer used one to translate for visitors.','食品販売者はキャッシュレス決済に携帯を使い、ボランティアは来訪者の翻訳に使っていました。'],
['The council realized that “no phones” treated very different uses as if they had the same purpose.','会議は「スマホなし」が目的の違う利用をすべて同じものとして扱っていると気づきました。'],
['Instead of abandoning the goal, members asked what behavior they actually wanted to encourage.','目標そのものをやめず、実際に促したい行動は何かを考えました。'],
['They agreed that the main aim was to create opportunities for voluntary conversation and shared activities.','中心の目的は、自発的な会話と共同活動の機会を作ることだと一致しました。'],
['A short survey of square users found support for board games, drawing tables, and guided walks.','広場利用者への短い調査では、ボードゲーム、絵の机、案内付き散歩への支持がありました。'],
['Only a minority supported a rule telling every visitor to put a phone away.','すべての来訪者へ携帯をしまう規則を支持したのは少数でした。'],
['The council redesigned the plan as a one-month trial called “Connect Hour.”','会議は計画を「つながる時間」という一か月の試行に作り直しました。'],
['A marked area offered phone-free games and conversation tables, but joining was optional.','印を付けた区域ではスマホなしのゲームや会話机を用意しましたが、参加は任意でした。'],
['People could keep phones for safety, payment, accessibility, work, or any other reason without explaining themselves.','安全、支払い、利用しやすさ、仕事、その他の理由で説明せず携帯を持ち続けられました。'],
['Signs described the activity positively rather than warning people that phones were forbidden.','表示は携帯禁止と警告するのでなく、活動内容を前向きに説明しました。'],
['Volunteers counted participants and asked them one optional question when they left: whether the activity helped them interact with someone.','ボランティアは参加者数を数え、退出時に活動が誰かとの交流に役立ったか任意で一問尋ねました。'],
['The first Sunday attracted forty-six participants, but some tables were crowded while the guided walk had only four people.','最初の日曜は四十六人参加しましたが、一部の机は混み、案内散歩は四人だけでした。'],
['For the second week, volunteers added another game table and reduced the number of scheduled walks.','二週目はゲーム机を一つ増やし、予定散歩の回数を減らしました。'],
['By the fourth week, most participants reported at least one new conversation, though many still carried phones in pockets or bags.','四週目までに多くの参加者が少なくとも一つ新しい会話があったと答えましたが、携帯をポケットやかばんに持つ人も多くいました。'],
['The council concluded that the desired social behavior did not require enforcing a complete device ban.','会議は、望む交流行動には完全な機器禁止を強制する必要はないと結論づけました。'],
['Its final proposal kept the voluntary activity zone and removed the language of a universal phone-free rule.','最終案では任意参加区域を残し、全員へのスマホなし規則という表現を削除しました。'],
['The council learned that policy design improves when a broad restriction is tested against real purposes, exceptions, and stakeholder needs.','青少年会議は、広い制限を本当の目的、例外、関係者の必要に照らして試すと政策設計が良くなると学びました。']
]});
add({id:'V11-B10-G3-015',level:'STANDARD',textbook:SS,section:'PROGRAM 7-3',sourceSectionBaselineId:'V10-SS-G3-P7-3-001',title:'The Weather Photograph That Made the River Look Higher',rows:[
['A geography class compared photographs of a river taken before and after heavy rain.','地理のクラスは大雨の前後に撮られた川の写真を比べました。'],
['In the second photograph, the water seemed to reach much closer to the top of the river wall.','二枚目では、水面が川の壁の上端へずっと近く見えました。'],
['Several students wanted to estimate the rise by measuring the water line directly on the two pictures.','何人かは二枚の写真上で水面の位置を直接測り、上昇量を見積もろうとしました。'],
['Then they noticed that the first picture had been taken from a bridge while the second was taken from the bank below.','すると一枚目は橋の上、二枚目は下の岸から撮られていると気づきました。'],
['The different camera height changed how the wall and water lined up in the image.','カメラの高さが違うため、写真内で壁と水面が重なる位置も変わっていました。'],
['The class realized that photograph position made direct visual measurement unreliable.','クラスは、撮影位置が違うと写真からの直接測定は信頼できないと分かりました。'],
['They checked a nearby gauge that recorded water height every thirty minutes.','近くの水位計が三十分ごとに記録したデータを確認しました。'],
['The gauge showed a real rise of sixty-two centimeters during the storm.','水位計では嵐の間に実際に六十二センチ上昇していました。'],
['Students kept both photographs because they still showed weather conditions and visible change.','写真は天候の様子と見た目の変化を示すため、二枚とも残しました。'],
['They removed the attempted centimeter estimate from the images and used the gauge for the numerical claim.','写真から出そうとしたセンチ単位の推定は削り、数値の主張には水位計を使いました。'],
['The display noted the different camera positions beside each photograph.','展示では各写真の横に撮影位置が違うことも記しました。'],
['Visitors could see that an image was useful evidence without being treated as a measuring instrument it was not designed to be.','来場者は写真を有用な証拠として見つつ、本来の測定器のようには扱わずに済みました。'],
['The class learned that perspective must be checked before using pictures to compare size or height.','クラスは、写真で大きさや高さを比べる前に遠近や撮影位置を確認すべきだと学びました。']
]});
add({id:'V11-B10-G3-016',level:'YAMAGUCHI_EXAM',textbook:NH,section:'Unit 6-4',sourceSectionBaselineId:'V10-NH-G3-U6-4-001',title:'The Winter Event, Snow Forecast, Indoor Venues, and Bus Capacity',materialData:{forecast:[['09:00','light snow'],['12:00','heavy snow possible'],['15:00','strong wind and snow']],venues:[['Civic Hall',120,'08:30-14:30'],['Sports Center',80,'09:00-17:00'],['Library Room',35,'10:00-16:00']],buses:[['Bus A',45],['Bus B',45]],groups:[['Students',72],['Teachers',8],['Guests',18]]},rows:[
['A junior high school planned a winter community event for seventy-two students, eight teachers, and eighteen guests.','中学校は生徒七十二人、先生八人、来賓十八人の冬の地域行事を計画しました。'],
['The original plan used an outdoor plaza from ten in the morning until three in the afternoon.','元の計画では午前十時から午後三時まで屋外広場を使う予定でした。'],
['Two days before the event, the weather forecast changed.','行事の二日前、天気予報が変わりました。'],
['It showed light snow at nine, possible heavy snow at noon, and stronger wind with snow by three.','九時は小雪、正午は大雪の可能性、三時には強い風と雪と予報されました。'],
['The organizers agreed that simply giving everyone an umbrella would not solve travel and exposure risks.','主催者は、全員に傘を渡すだけでは移動や寒さへの危険を解決できないと判断しました。'],
['They looked at three possible indoor venues instead of canceling immediately.','すぐ中止せず、三つの屋内会場を検討しました。'],
['The Civic Hall held one hundred twenty people but was available only until two thirty.','市民ホールは百二十人入れますが、利用できるのは二時半まででした。'],
['The Sports Center held eighty and stayed open until five.','スポーツセンターは八十人で五時まで開いていました。'],
['The Library Room held only thirty-five, although it was open through the afternoon.','図書館の部屋は午後も使えましたが、定員は三十五人だけでした。'],
['The total event group was ninety-eight people, so no plan could place everyone in the Sports Center or Library Room at the same time.','行事全体は九十八人なので、全員を同時にスポーツセンターや図書館へ入れることはできません。'],
['The Civic Hall was the only single room large enough for the whole group.','全員を一つの部屋へ入れられるのは市民ホールだけでした。'],
['However, the first draft of the indoor plan kept the outdoor schedule until three, which would continue after the hall closed.','しかし最初の屋内案は元の三時までの予定を残し、市民ホールの終了時刻を越えていました。'],
['The organizers shortened the main program so all shared activities would finish at one forty-five.','主催者は全体活動を一時四十五分までに終えるよう主なプログラムを短縮しました。'],
['That left forty-five minutes before the hall closed for coats, attendance checks, and organized departure.','これでホール終了まで四十五分あり、上着、人数確認、順序ある退場に使えます。'],
['Transport created another problem.','交通にも別の問題がありました。'],
['The school had two buses, each with forty-five seats, for a total of ninety seats.','学校には四十五席のバスが二台あり、合計九十席でした。'],
['The ninety-eight participants could not all ride those buses at once.','九十八人全員は一度にその二台へ乗れません。'],
['At first, someone suggested asking eight guests to drive separately, but several guests had already said they did not have cars.','最初は来賓八人に別の車で来てもらう案が出ましたが、何人かは車がないとすでに伝えていました。'],
['The organizers checked the registration forms instead of assuming which people could arrange private transport.','主催者は誰が自家用車を使えるか推測せず、申込書を確認しました。'],
['They found that twelve students lived within a short, safe walk of the Civic Hall and had guardian permission to meet there directly in normal weather.','十二人の生徒は市民ホールから安全な徒歩圏内に住み、通常天候なら保護者許可で現地集合できると分かりました。'],
['Because the forecast now included snow, the school contacted those families again rather than relying on the old permission.','今回は雪予報なので、古い許可だけに頼らずその家庭へ再確認しました。'],
['Seven families preferred to bring students directly, while five asked for bus transportation because roads near their homes might become slippery.','七家庭は現地送迎を希望し、五家庭は家の近くの道が滑りそうなのでバスを希望しました。'],
['With seven students arriving directly, ninety-one people still needed seats, one more than the two buses could carry.','七人が現地集合しても九十一人がバスを必要とし、二台の定員より一人多い状態でした。'],
['One teacher then noticed that a school van with eight passenger seats was approved for staff travel and was available that morning.','そこで先生一人が、職員移動用に認められた八人乗り学校車がその朝空いていると気づきました。'],
['The transport office confirmed that a licensed staff driver could use the van and that it had winter tires.','交通担当は、資格のある職員が運転でき冬用タイヤもあると確認しました。'],
['The final transport plan used both buses plus the van, with assigned passenger lists rather than first-come seating.','最終交通案は二台のバスと学校車を使い、先着順でなく乗車名簿を決めました。'],
['Families received departure times, vehicle assignments, and a morning contact number in one message.','家庭には出発時刻、乗る車、当日朝の連絡先を一つの案内で送りました。'],
['The school also set a six thirty weather check and stated that severe road warnings would cancel the trip even though an indoor venue was ready.','屋内会場があっても道路に重大な警報が出れば中止することを示し、朝六時半に天候確認を設定しました。'],
['On the event day, snow remained light in the morning, so the group traveled according to the revised plan and finished before conditions worsened.','当日朝は小雪のままだったため修正案で移動し、天候悪化前に行事を終えました。'],
['The organizers learned that moving indoors is only one part of winter safety; capacity, opening hours, transport seats, updated permission, and a cancellation rule must also fit together.','主催者は、屋内化だけが冬の安全対策ではなく、定員、開館時間、交通座席、更新した許可、中止基準も組み合わせる必要があると学びました。']
]});
window.V11_BATCH10_G3_DRAFTS=passages;
window.V11_BATCH10_G3_DRAFT_STATE={count:passages.length,registered:false,version:'20260829-author-r1'};
})();
