const fs=require('fs'),{chromium,webkit,devices}=require('playwright');
function ok(c,m){if(!c)throw Error(m)}
const raw=JSON.parse(fs.readFileSync('v11_batch14_assembled_draft.json','utf8'));
const plan=JSON.parse(fs.readFileSync('v11_batch14_authoring_plan.json','utf8'));
const by=new Map(plan.passages.map(p=>[p.id,p]));
const candidate=raw.passages.map(p=>{const q=by.get(p.id),x=JSON.parse(JSON.stringify(p));x.textbook=String(q.anchor).startsWith('Sunshine ')?'サンシャイン':'ニューホライズン';x.grade=String(q.grade);x.section=String(q.anchor).replace(/^Sunshine\s+|^NH\s+/,'');x.sentences=(x.slashRows||[]).map(r=>r.english||r.en);ok(x.sentences.length>0&&x.sentences.every(Boolean),p.id+' sentences source');x.slashRows=(x.slashRows||[]).map(r=>({en:r.english||r.en,jp:r.japanese||r.jp}));x.registered=false;x.batch='V11-B14';return x});
async function open(kind){const browser=kind==='chromium'?await chromium.launch({headless:true}):await webkit.launch({headless:true});const context=kind==='chromium'?await browser.newContext({viewport:{width:1366,height:900}}):await browser.newContext({...devices['iPhone 13']});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const r=await page.goto('http://127.0.0.1:8000/index.html?b14candidate='+kind+'-'+Date.now(),{waitUntil:'domcontentloaded',timeout:90000});ok(r&&r.ok(),kind+' HTTP');await page.waitForFunction(()=>window.V11_BATCH13_LOADED===true&&window.V11_BATCH13_STATE&&window.V11_BATCH13_STATE.totalWithBaseline===818&&Object.values(window.V11_EXTRA_PASSAGES||{}).flat().length===650,null,{timeout:180000,polling:250});return{browser,context,page,errors}}
async function inject(page){const x=await page.evaluate(ps=>{window.V11_BATCH14_PASSAGES=ps;const st=window.V11_REGISTER_PASSAGES(ps);if(typeof window.V11_APPLY_EASY_SUPPORT_NOTES==='function')window.V11_APPLY_EASY_SUPPORT_NOTES();return{extra:Object.values(window.V11_EXTRA_PASSAGES||{}).flat().length,st}},candidate);ok(x.extra===700,'candidate extra '+JSON.stringify(x));await page.waitForTimeout(25)}
async function select(page,p){await page.selectOption('#textbook',p.textbook);await page.selectOption('#grade',String(p.grade));let found=false;for(const m of await page.locator('#major option').evaluateAll(os=>os.map(o=>o.value))){await page.selectOption('#major',m);await page.waitForTimeout(25);if((await page.locator('#section option').evaluateAll(os=>os.map(o=>o.value))).includes(p.section)){found=true;break}}ok(found,p.id+' section '+p.section);await page.selectOption('#section',p.section);await page.waitForFunction(id=>Array.from(document.querySelectorAll('#v11PassageVariant option')).some(o=>o.value===id),p.id,{timeout:30000,polling:50});await page.selectOption('#v11PassageVariant',p.id);await page.evaluate(()=>window.render());ok((await page.evaluate(()=>window.choose().id))===p.id,p.id+' choose')}
async function engine(kind){const c=await open(kind);try{await inject(c.page);let overflow=0,support=0;const bad=[];for(const p of candidate){await select(c.page,p);ok((await c.page.locator('#questions .q').count())===5,p.id+' A');const b=c.page.locator('#altSetBtn');if(await b.count()){await b.click();ok((await c.page.locator('#questions .q').count())===5,p.id+' B')}const n=await c.page.evaluate(id=>{const p=window.V11_BATCH14_PASSAGES.find(x=>x.id===id);return{n:(p.notes||[]).map(x=>String(x.english||'').toLowerCase()),s:p.supportNotes||[]}},p.id);support+=n.s.length;const set=new Set(n.n);if(n.s.length<4||n.s.length>16||n.s.some(x=>!x||!x.english||!x.japanese||set.has(String(x.english).toLowerCase())))bad.push({id:p.id,count:n.s.length});if(await c.page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+2))overflow++}ok(!bad.length,kind+' support '+JSON.stringify(bad));ok(!overflow,kind+' overflow');ok(!c.errors.length,kind+' errors '+c.errors.join('|'));return{passages:50,supportNotes:support,overflow,errors:c.errors.length}}finally{await Promise.allSettled([c.context.close(),c.browser.close()])}}
async function cross(){const c=await open('chromium');try{await inject(c.page);return await c.page.evaluate(()=>{const all=Object.values(window.V11_EXTRA_PASSAGES||{}).flat(),cur=window.V11_BATCH14_PASSAGES||[],prior=all.filter(p=>!String(p.id||'').startsWith('V11-B14-')),ids=new Set(),dupIds=[],dupBodies=[],near=[],bm=new Map(),norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();for(const p of all){if(ids.has(p.id))dupIds.push(p.id);ids.add(p.id);const b=norm(p.body||'');if(bm.has(b))dupBodies.push([bm.get(b),p.id]);else bm.set(b,p.id)}const rows=p=>(p.slashRows||[]).map(r=>norm(r.en||r.english));const j=(a,b)=>{a=new Set(a);b=new Set(b);let n=0;for(const x of a)if(b.has(x))n++;return n/(a.size+b.size-n||1)};for(const a of cur)for(const b of prior){if(a.textbook!==b.textbook||String(a.grade)!==String(b.grade)||a.section!==b.section)continue;const s=j(rows(a),rows(b));if(s>=.85)near.push({a:a.id,b:b.id,score:s})}return{all:all.length,prior:prior.length,current:cur.length,dupIds,dupBodies,near,pass:all.length===700&&prior.length===650&&!dupIds.length&&!dupBodies.length&&!near.length}})}finally{await Promise.allSettled([c.context.close(),c.browser.close()])}}
async function a4(){const c=await open('chromium');try{await inject(c.page);const reps=[],seen=new Set();for(const p of candidate){const k=p.textbook+'|'+p.grade+'|'+p.section;if(!seen.has(k)){seen.add(k);reps.push(p)}}let files=0;fs.mkdirSync('/tmp/v11-b14-a4',{recursive:true});for(const p of reps){await select(c.page,p);await c.page.emulateMedia({media:'print'});ok(!(await c.page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+3)),p.id+' print overflow');for(const kind of ['teacher','student']){if(kind==='student')await c.page.evaluate(()=>{const s=document.createElement('style');s.id='b14student';s.textContent='@media print{#answers,#audit{display:none!important}}';document.head.appendChild(s)});const f='/tmp/v11-b14-a4/'+p.id+'-'+kind+'.pdf';await c.page.pdf({path:f,format:'A4',printBackground:true});ok(fs.statSync(f).size>5000,p.id+' '+kind);files++;if(kind==='student')await c.page.evaluate(()=>document.getElementById('b14student')?.remove())}await c.page.emulateMedia({media:'screen'})}return{representativeSections:reps.length,files}}finally{await Promise.allSettled([c.context.close(),c.browser.close()])}}
(async()=>{const pc=await engine('chromium'),iphone=await engine('webkit'),cr=await cross();ok(cr.pass,'cross '+JSON.stringify(cr));const print=await a4();const out={batch:'V11-B14',candidateTotal:868,registered:false,pc,iphone,cross:cr,a4:print,finalPass:true};console.log('B14_CANDIDATE_RESULT='+JSON.stringify(out));console.log('V11_BATCH14_CANDIDATE_868_PASS')})().catch(e=>{console.error(e.stack||e);process.exit(1)});
