(function buildV11Batch05Grade2Draft(){
'use strict';
const BATCH='V11-B05-G2-DRAFT-20260828';
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while)\b/gi,'/ $1');}
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function build(id,textbook,section,baseline,title,rows,long,notes){const qs=rows.slice(0,10).map((r,i)=>({prompt:`${i+1}. 本文の第${i+1}文の内容に合う英文を本文から一文答えなさい。`,answer:r[0],evidence:r[0],evidenceJp:r[1],reason:`第${i+1}文が直接の根拠です。`}));return {id,textbook,grade:'2',section,level:'STEP',title,genre:'story',batch:BATCH,sourceSectionBaselineId:baseline,targetWordBand:long?[170,210]:[115,155],wordCount:wc(rows),sentences:rows.map(r=>r[0]),fullTranslation:rows.map(r=>r[1]).join(''),slashRows:rows.map(r=>({en:slash(r[0]),jp:r[1]})),questions:qs.slice(0,5),questionSetB:qs.slice(5,10),notes:(notes||[]).map(n=>({english:n[0],japanese:n[1],kind:'unlearned_local_required',source:'v11 Batch05 G2 story-specific required note seed'})),semanticRewrite:'BATCH05_G2_STORY_SPECIFIC_20260828',registered:false,auditNote:'Batch05 G2 non-runtime authoring draft. Story-specific passage; chronology, length, question diversity, notes, cross-batch, PC/iPhone and A4 gates still required.'};}
const SS='サンシャイン',NH='ニューホライズン',ssBase='V10-SS-G2-P8-3-001',nhBase='V10-NH-G2-U7-4-001';
const all=[
build('V11-SS-G2-P8-3-034',SS,'PROGRAM 8-3',ssBase,'The Shorter Presentation Order',[
['Our history group had six ideas for a five-minute presentation.','私たちの歴史班には、五分間の発表で話したいことが六つありました。'],
['During practice, we reached the time limit before our last two points.','練習では、最後の二点を話す前に制限時間になりました。'],
['At first, everyone wanted to speak faster and keep every detail.','最初は、全員が速く話して細かい内容も全部残そうとしました。'],
['Our teacher said the audience needed the main idea more than extra information.','先生は、聞き手には追加情報より中心となる考えが必要だと言いました。'],
['We wrote all six points on separate cards and placed them on a desk.','六つの要点を別々のカードに書き、机に並べました。'],
['Then we chose the three points that directly answered our topic question.','それから、テーマの問いに直接答える三点を選びました。'],
['We moved those cards to the beginning of the presentation.','そのカードを発表の最初へ移しました。'],
['Two smaller examples became short notes under the main points.','二つの小さな例は主要点の下の短いメモにしました。'],
['We removed one detail that repeated information from an earlier slide.','前のスライドと同じ内容を繰り返す細部を一つ削りました。'],
['Our second practice ended with twenty seconds still left.','二回目の練習は二十秒を残して終わりました。'],
['Everyone could speak at a natural speed and look at the audience.','全員が自然な速さで話し、聞き手を見ることができました。'],
['Putting the important ideas first made the short presentation clearer.','重要な考えを先に置くことで、短い発表がより分かりやすくなりました。']
],false,[['time limit','制限時間'],['audience','聞き手'],['detail','細部']]),
build('V11-SS-G2-P8-3-035',SS,'PROGRAM 8-3',ssBase,'One Broken Display Stand',[
['Our class was preparing a small display for the school festival.','私たちのクラスは文化祭の小さな展示を準備していました。'],
['We planned to put three posters on separate cardboard stands.','三枚のポスターを別々の厚紙の台に置く予定でした。'],
['The night before opening, one stand bent and could not stay upright.','開場前日の夜、一つの台が曲がり、立たなくなりました。'],
['There was no extra cardboard large enough to make a new one.','新しく作れるほど大きな予備の厚紙はありませんでした。'],
['One student wanted to put the third poster flat on a table.','一人の生徒は三枚目を机に平らに置こうとしました。'],
['Another student noticed an empty part of the wall behind our table.','別の生徒が机の後ろの壁に空いた場所があると気づきました。'],
['We asked a teacher whether we could use that wall safely.','その壁を安全に使えるか先生に確認しました。'],
['After getting permission, we moved the lightest poster to the wall.','許可を得て、一番軽いポスターを壁へ移しました。'],
['The other two posters stayed on the good stands beside it.','ほかの二枚はその横の使える台に残しました。'],
['We stepped back and checked whether all three could be read easily.','後ろへ下がり、三枚とも読みやすいか確認しました。'],
['The new layout looked balanced and kept the main message visible.','新しい配置はバランスがよく、中心メッセージも見やすいままでした。'],
['Changing the layout solved the problem without hiding any information.','配置を変えることで、情報を隠さず問題を解決できました。']
],false,[['display stand','展示台'],['upright','まっすぐ立った'],['permission','許可'],['layout','配置']]),
build('V11-SS-G2-P8-3-036',SS,'PROGRAM 8-3',ssBase,'The Wrong File Name',[
['Our science team used one computer to write a group report.','私たちの科学班は一台のコンピューターで班のレポートを書きました。'],
['By Thursday, the folder contained two files named almost the same thing.','木曜日までに、フォルダにはほぼ同じ名前のファイルが二つありました。'],
['One was from Tuesday, and the other included our newest graph.','一つは火曜日のもので、もう一つには最新のグラフが入っていました。'],
['A member opened the older file because its name looked more complete.','あるメンバーは名前がより完成版らしく見えたため、古いファイルを開きました。'],
['We noticed the mistake when the graph was missing from the last page.','最後のページにグラフがなかったので、間違いに気づきました。'],
['Instead of depending on names, we checked the saved date of each file.','名前に頼らず、それぞれの保存日を確認しました。'],
['The newer file had been saved after our Wednesday meeting.','新しいファイルは水曜日の話し合い後に保存されていました。'],
['We opened it and confirmed that every recent change was there.','それを開き、最近の修正がすべて入っていることを確認しました。'],
['Then we renamed both files with the month and day at the front.','それから両方のファイル名の最初に月日を付けました。'],
['We also moved the older copy into a folder called Old Versions.','古いほうは「Old Versions」というフォルダへ移しました。'],
['The final report was easy to identify when we sent it the next day.','次の日に送るとき、最終レポートを簡単に見分けられました。'],
['Clear file names saved our group from repeating the same mistake.','分かりやすいファイル名で、同じ間違いを繰り返さずにすみました。']
],false,[['saved date','保存日'],['version','版'],['identify','見分ける']]),
build('V11-SS-G2-P8-3-037',SS,'PROGRAM 8-3',ssBase,'The Indoor Practice Plan',[
['Our soccer team planned a short outdoor practice after school.','サッカー部は放課後に短い屋外練習をする予定でした。'],
['Strong wind began before practice and kept moving the small training cones.','練習前に強い風が吹き始め、小さな練習用コーンが動いてしまいました。'],
['The coach said running the usual drills outside was not a good idea.','コーチはいつもの練習を外でするのはよくないと言いました。'],
['Canceling everything would leave us without practice before Saturday’s game.','全部中止すると、土曜日の試合前に練習できなくなります。'],
['We checked which parts of our plan could be done in the gym.','計画のどの部分なら体育館でできるか確認しました。'],
['Passing in small groups needed little space and no heavy equipment.','少人数のパス練習は場所も重い道具もほとんど必要ありませんでした。'],
['We also practiced footwork along marked lines on the gym floor.','体育館の床の線に沿って足の動きも練習しました。'],
['The goalkeepers worked on hand movements without kicking long balls.','ゴールキーパーは長いボールを蹴らず、手の動きを練習しました。'],
['Everyone stayed away from the doors where the wind was strongest.','全員、風が最も強いドアの近くを避けました。'],
['The practice was different, but each activity still matched our game goals.','練習は違う内容でしたが、どの活動も試合の目標につながっていました。'],
['We wrote down the outdoor drills that still needed to be done later.','あとで必要な屋外練習も書き留めました。'],
['Changing the place let us practice safely instead of losing the whole day.','場所を変えることで、一日全部を失わず安全に練習できました。']
],false,[['training cone','練習用コーン'],['drill','練習メニュー'],['footwork','足の動き']]),
build('V11-SS-G2-P8-3-038',SS,'PROGRAM 8-3',ssBase,'The Missing Survey Page',[
['Our class collected paper surveys about favorite school lunch menus.','私たちのクラスは好きな給食メニューについて紙のアンケートを集めました。'],
['Each group was supposed to receive ten completed sheets.','各班は記入済みの用紙を十枚受け取る予定でした。'],
['When our group began entering answers, we found only nine sheets.','回答を入力し始めると、私たちの班には九枚しかありませんでした。'],
['One student thought someone had forgotten to answer the survey.','一人の生徒は、だれかがアンケートに答え忘れたと思いました。'],
['Before changing the total, we counted the papers from the other groups.','合計を変える前に、ほかの班の用紙も数えました。'],
['The next group had eleven sheets instead of ten.','隣の班には十枚ではなく十一枚ありました。'],
['We checked the small group number printed at the top of each page.','各ページの上に印刷された小さな班番号を確認しました。'],
['One of our sheets had been placed in their pile by mistake.','私たちの用紙一枚が間違って隣の山に入っていました。'],
['We returned it to our group and counted all papers again.','それを自分たちの班に戻し、全部の紙をもう一度数えました。'],
['Both groups now had ten sheets and could enter the correct totals.','両方の班が十枚になり、正しい合計を入力できました。'],
['We added a counting step before entering any more survey results.','それ以降の結果を入力する前に、数を確認する手順を加えました。'],
['A simple count found the missing page before it changed our data.','簡単に数えることで、データが変わる前に足りないページを見つけられました。']
],false,[['survey','アンケート'],['sheet','用紙'],['pile','紙の山'],['data','データ']]),
build('V11-SS-G2-P8-3-039',SS,'PROGRAM 8-3',ssBase,'The Crowded Bicycle Rack',[
['I usually leave my bicycle in the rack closest to the school gate.','私は普段、正門に一番近い自転車置き場に自転車を置きます。'],
['One morning, every space there was already filled when I arrived.','ある朝、到着したときそこはすでに全部埋まっていました。'],
['Several students had begun leaving bicycles beside the walking path.','何人かの生徒は通路のそばに自転車を置き始めていました。'],
['I knew that area needed to stay open for people entering school.','そこは登校する人のため空けておく必要があると知っていました。'],
['A school map near the gate showed two other bicycle areas.','正門近くの校内図には、ほかに二つの自転車置き場がありました。'],
['The second one was behind the gym and only a short walk away.','二つ目は体育館の後ろで、歩いてもすぐでした。'],
['I rode there and found several empty spaces under the roof.','そこまで行くと、屋根の下に空きがいくつかありました。'],
['Two friends who arrived after me followed me to the same rack.','あとから来た二人の友達も同じ置き場までついてきました。'],
['We locked our bicycles without blocking any path.','通路をふさがず、自転車に鍵をかけました。'],
['At lunch, we told our classmates where the second rack was.','昼休みに、二つ目の置き場の場所をクラスメートに伝えました。'],
['More students used it during the rest of the week.','その週の残りの日は、さらに多くの生徒がそこを使いました。'],
['Checking the school map gave us a better choice than crowding the entrance.','校内図を確認すると、入口を混雑させるよりよい選択が見つかりました。']
],false,[['bicycle rack','自転車置き場'],['walking path','通路'],['blocking','ふさいでいる']]),
build('V11-SS-G2-P8-3-040',SS,'PROGRAM 8-3',ssBase,'The Shared Reference Book',[
['Two groups in our class needed the same reference book for reports.','クラスの二つの班がレポートのため同じ参考書を必要としていました。'],
['There was only one copy in the classroom, and both groups wanted it first.','教室には一冊しかなく、両方の班が先に使いたがりました。'],
['Waiting until the other group finished could waste most of our work time.','相手の班が終わるまで待つと、作業時間の多くを失うかもしれませんでした。'],
['We asked what pages each group actually needed to read.','それぞれの班が実際に何ページを読む必要があるか確認しました。'],
['Our group needed two short sections, while the other group needed one chapter.','私たちの班は短い二節、相手の班は一章が必要でした。'],
['We agreed to use the book for fifteen minutes before lunch.','昼食前の十五分を私たちが使うことにしました。'],
['The other group would use it during the first twenty minutes after lunch.','相手の班は昼食後の最初の二十分を使うことになりました。'],
['We wrote those times on a note and placed it inside the front cover.','その時刻をメモに書き、表紙の内側に入れました。'],
['Each group copied only the notes it needed during its turn.','それぞれの班が順番の間に必要なメモだけ取りました。'],
['The book moved between us exactly when the note said it should.','本はメモどおりの時刻に正確に班の間を移りました。'],
['Both groups finished their research without arguing or waiting for long.','両方の班が言い争ったり長く待ったりせず調べ学習を終えました。'],
['A small time schedule made one book enough for two groups.','小さな時間予定表で、一冊の本を二つの班で使えました。']
],false,[['reference book','参考書'],['chapter','章'],['schedule','予定表']]),
build('V11-SS-G2-P8-3-041',SS,'PROGRAM 8-3',ssBase,'The Festival Sign from Far Away',[
['Our festival group made a sign for a game room on the second floor.','文化祭の班で二階のゲーム室の案内を作りました。'],
['The sign looked clear while we were standing beside the table.','机のそばで見ると、その案内は分かりやすく見えました。'],
['The room name was large, but the time and arrow were much smaller.','部屋名は大きかったのですが、時刻と矢印はかなり小さくなっていました。'],
['One student suggested checking it from the entrance of the hallway.','一人の生徒が廊下の入口から確認しようと提案しました。'],
['From that distance, we could read the room name but not the arrow.','その距離では部屋名は読めましたが、矢印は読めませんでした。'],
['Visitors might know the event name and still walk the wrong way.','来場者は行事名が分かっても、違う方向へ歩くかもしれません。'],
['We returned to the table and made the arrow thicker and longer.','机へ戻り、矢印を太く長くしました。'],
['We also moved the starting time under the room name and enlarged it.','開始時刻も部屋名の下へ移し、大きくしました。'],
['Then we tested the new sign from the hallway entrance again.','それから新しい案内を廊下の入口からもう一度確認しました。'],
['This time, every important part could be seen without walking closer.','今度は、近づかなくても大切な部分が全部見えました。'],
['Several visitors later followed the sign directly to our room.','その後、何人もの来場者が案内にしたがって直接私たちの部屋へ来ました。'],
['Testing the sign from far away showed us what visitors really needed.','遠くから案内を試すことで、来場者に本当に必要なものが分かりました。']
],false,[['hallway','廊下'],['distance','距離'],['enlarged','大きくした']]),
build('V11-NH-G2-U7-4-037',NH,'Unit 7-4',nhBase,'The Bus Stop Moved',[
['Our class visited a local museum on a rainy morning.','私たちのクラスは雨の朝、地元の博物館を訪れました。'],
['We planned to take the city bus from our usual stop after the visit.','見学後、いつものバス停から市バスに乗る予定でした。'],
['When we returned, construction fences covered the area near that stop.','戻ると、工事の柵がそのバス停の近くを囲んでいました。'],
['A small sign said buses were using a temporary stop that day.','小さな案内には、その日は臨時のバス停を使うと書かれていました。'],
['Some students started walking toward another stop they remembered.','何人かの生徒は覚えていた別のバス停へ歩き始めました。'],
['Our teacher asked us to read the temporary sign carefully first.','先生はまず臨時案内をよく読むよう言いました。'],
['It showed an arrow pointing around the corner beside a bank.','そこには銀行の角を曲がる方向へ矢印がありました。'],
['We followed the arrow together and found a yellow temporary marker.','みんなで矢印にしたがい、黄色い臨時の目印を見つけました。'],
['The bus number on that marker matched the bus we needed.','その目印のバス番号は、必要なバスと一致しました。'],
['We waited there instead of splitting into different directions.','別々の方向へ分かれず、そこで待ちました。'],
['Our bus arrived a few minutes later and took us back to school.','数分後にバスが来て、学校へ戻りました。'],
['Reading the temporary information kept the whole class together.','臨時情報を読むことで、クラス全員がいっしょに行動できました。']
],false,[['construction','工事'],['temporary stop','臨時バス停'],['marker','目印']]),
build('V11-NH-G2-U7-4-038',NH,'Unit 7-4',nhBase,'The Too-Wide Survey Choice',[
['Our class designed a survey about after-school activities.','私たちのクラスは放課後の活動についてアンケートを作りました。'],
['One question asked students whether they liked sports or other things.','一つの質問は、スポーツと「その他」のどちらが好きかをたずねるものでした。'],
['During a test, several classmates said “other things” was too broad.','試しに答えてもらうと、何人かが「その他」は広すぎると言いました。'],
['A student who liked music and art did not know which answer to choose.','音楽と美術が好きな生徒は、どの答えを選べばよいか分かりませんでした。'],
['We realized the choices would not give us useful information.','その選択肢では役立つ情報が得られないと気づきました。'],
['Instead of starting the full survey, we rewrote the answer list.','本番のアンケートを始めず、回答一覧を書き直しました。'],
['We added sports, music, art, reading, and a final open choice.','スポーツ、音楽、美術、読書、最後に自由記入の選択肢を加えました。'],
['We also allowed students to choose two activities if necessary.','必要なら活動を二つ選べるようにもしました。'],
['A second test showed that students understood the new choices quickly.','二回目の試しでは、生徒が新しい選択肢をすぐ理解できました。'],
['Their answers were easier to compare because the categories were clearer.','分類が明確になったので、回答を比べやすくなりました。'],
['We used the revised question in the real survey the next day.','次の日、本番のアンケートで修正版の質問を使いました。'],
['Testing one question first helped us collect information we could actually use.','一つの質問を先に試したことで、実際に使える情報を集められました。']
],false,[['broad','範囲が広い'],['category','分類'],['revised','修正した']]),
build('V11-NH-G2-U7-4-039',NH,'Unit 7-4',nhBase,'The Quiet Museum Corner',[
['Our group visited a museum to prepare a report for social studies.','私たちの班は社会科のレポート準備のため博物館を訪れました。'],
['After looking at one exhibit, we began discussing what we had learned.','一つの展示を見たあと、学んだことを話し合い始めました。'],
['We were standing in a narrow room where other visitors were reading quietly.','私たちは、ほかの来場者が静かに読んでいる狭い部屋に立っていました。'],
['Our voices became louder as we compared different ideas.','違う考えを比べるうちに、私たちの声は大きくなりました。'],
['A member noticed a sign asking people to keep that room quiet.','一人が、その部屋では静かにするよう求める案内に気づきました。'],
['We stopped the discussion instead of trying to whisper around the exhibit.','展示の周りで小声を続けるのではなく、話し合いを止めました。'],
['The museum map showed a rest area where group conversation was allowed.','館内図にはグループで会話できる休憩場所が示されていました。'],
['We walked there and sat at a table away from the exhibit rooms.','そこへ移動し、展示室から離れた机に座りました。'],
['Each student then shared one note without disturbing other visitors.','それから各自が、ほかの来場者を邪魔せず一つずつメモを共有しました。'],
['We chose three points for our report and returned to the exhibits quietly.','レポート用に三点を選び、静かに展示へ戻りました。'],
['The new place gave us enough freedom to talk at a normal volume.','新しい場所では普通の声量で話すことができました。'],
['Moving the discussion respected both our work and the other visitors.','話し合う場所を移すことで、自分たちの学習とほかの来場者の両方を大切にできました。']
],false,[['exhibit','展示'],['whisper','ささやく'],['volume','声量']]),
build('V11-NH-G2-U7-4-040',NH,'Unit 7-4',nhBase,'The Science Table Is Wet',[
['Our science class was recording plant measurements at a long table.','理科の授業で、長い机を使って植物の測定結果を記録していました。'],
['A cup of water stood near several notebooks and printed data sheets.','水の入ったコップが、何冊かのノートと印刷したデータ用紙の近くにありました。'],
['Someone moved a box, and the cup fell onto its side.','だれかが箱を動かし、コップが横に倒れました。'],
['Water began spreading toward the papers before anyone reached a towel.','だれかがタオルを取る前に、水が紙のほうへ広がり始めました。'],
['I lifted the notebooks while my partner moved the printed sheets.','私はノートを持ち上げ、相手は印刷用紙を移しました。'],
['We placed all the papers on a dry desk across the room.','すべての紙を部屋の反対側の乾いた机へ置きました。'],
['Only then did we use towels to wipe the wet science table.','そのあとでタオルを使い、ぬれた理科の机を拭きました。'],
['Our teacher checked the floor so nobody would slip nearby.','先生は近くでだれも滑らないよう床を確認しました。'],
['Most of the written data stayed dry because we moved it first.','最初に移したので、書いたデータのほとんどは乾いたままでした。'],
['We copied one wet corner of a sheet before the writing became unclear.','文字が読みにくくなる前に、ぬれた用紙の角の内容を写しました。'],
['After class, we changed the table setup and kept drinks farther away.','授業後、机の配置を変え、飲み物をもっと離して置くことにしました。'],
['Protecting the records first saved work that could not be replaced easily.','記録を先に守ることで、簡単には取り戻せない作業を残せました。']
],false,[['measurement','測定結果'],['data sheet','データ用紙'],['slip','滑る']]),
build('V11-NH-G2-U7-4-041',NH,'Unit 7-4',nhBase,'The Attachment Name Check',[
['Our group needed to email three files to a teacher before dinner.','私たちの班は夕食前に三つのファイルを先生へメールで送る必要がありました。'],
['The folder contained photos, an old outline, and the final report.','フォルダには写真、古い構成案、最終レポートが入っていました。'],
['Several file names began with the same project word and looked similar.','いくつかのファイル名が同じプロジェクト名で始まり、よく似ていました。'],
['I attached three files quickly and was ready to press send.','私は急いで三つを添付し、送信しようとしました。'],
['Another member asked me to read every attachment name aloud first.','別のメンバーが、まず添付名を全部声に出して読むよう言いました。'],
['The second attachment was the old outline instead of the final graph.','二つ目の添付は最終グラフではなく古い構成案でした。'],
['We removed it and searched for the file with the correct date.','それを外し、正しい日付のファイルを探しました。'],
['Before attaching the replacement, we opened it and checked the first page.','差し替えを添付する前に、それを開いて一ページ目を確認しました。'],
['The graph title and group name were both correct.','グラフの題名と班名はどちらも正しくなっていました。'],
['We checked the other two attachments in the same way.','ほかの二つの添付も同じ方法で確認しました。'],
['Only after that final check did we send the email.','その最後の確認のあとで初めてメールを送りました。'],
['Reading file names before sending prevented an avoidable mistake.','送る前にファイル名を読むことで、防げるミスを避けられました。']
],false,[['attachment','添付ファイル'],['outline','構成案'],['replacement','差し替え']]),
build('V11-NH-G2-U7-4-042',NH,'Unit 7-4',nhBase,'The Different Locker Number',[
['My sports locker number was printed on a small school card.','私の体育用ロッカー番号は小さな学校カードに印刷されていました。'],
['After practice, I walked to locker 316 because I remembered that number.','練習後、316番だと思ってそのロッカーへ行きました。'],
['My key would not turn, even after I tried it twice.','二回試しても鍵が回りませんでした。'],
['I started to think the lock might be broken and looked for a teacher.','鍵が壊れたのかと思い、先生を探そうとしました。'],
['Before asking for help, my friend suggested checking the school card.','助けを求める前に、友達が学校カードを確認しようと言いました。'],
['The card actually showed 319, and the last digit looked similar from far away.','カードは実際には319で、最後の数字は遠くから似て見えました。'],
['I moved three lockers to the right and found number 319.','右へ三つ移動し、319番を見つけました。'],
['My key opened that locker normally on the first try.','私の鍵は一回で普通にそのロッカーを開けました。'],
['Nothing was wrong with the key or the lock after all.','結局、鍵にもロッカーにも問題はありませんでした。'],
['I put the school card in an easy-to-reach pocket afterward.','そのあと学校カードを取り出しやすいポケットへ入れました。'],
['The next time, I checked the number instead of trusting my memory.','次からは記憶に頼らず番号を確認しました。'],
['One digit check saved us from reporting a problem that did not exist.','数字一つの確認で、存在しない問題を報告せずにすみました。']
],false,[['locker','ロッカー'],['digit','数字'],['lock','錠']]),
build('V11-NH-G2-U7-4-043',NH,'Unit 7-4',nhBase,'The Interview in a Noisy Hall',[
['Our class interviewed students about the school festival for a video project.','私たちのクラスは動画制作のため、文化祭について生徒へインタビューしました。'],
['We first stood in the main hall because many students passed through it.','多くの生徒が通るので、最初は中央ホールに立ちました。'],
['The place made it easy to find people, but music was playing nearby.','人は見つけやすかったのですが、近くで音楽が流れていました。'],
['Our first recorded answer sounded clear while we were speaking face to face.','最初の回答は、向かい合って話しているときははっきり聞こえました。'],
['When we played the recording, the music covered several important words.','録音を再生すると、音楽がいくつかの大切な言葉を消していました。'],
['We did not want to ask every person to repeat long answers.','全員に長い回答をもう一度頼みたくありませんでした。'],
['A teacher showed us a quieter area near an unused classroom.','先生が使っていない教室近くの静かな場所を教えてくれました。'],
['We placed a small interview sign there and invited students one at a time.','そこに小さなインタビュー案内を置き、一人ずつ呼びました。'],
['Before each full interview, we recorded one test sentence.','各インタビューの前に一つ試しの文を録音しました。'],
['The voices were clear, and we could hear every answer afterward.','声が明確で、あとでどの回答も聞き取れました。'],
['We still found participants in the busy hall but recorded them in the quiet area.','人はにぎやかなホールで探し、録音は静かな場所で行いました。'],
['Separating those two tasks improved our video without slowing the project.','二つの作業を分けることで、制作を遅らせず動画の質を上げられました。']
],false,[['interview','インタビュー'],['recording','録音'],['participant','参加者']]),
build('V11-NH-G2-U7-4-044',NH,'Unit 7-4',nhBase,'The Spare Sports Shirt',[
['It rained hard while I walked to school before morning practice.','朝練前に学校へ歩いていると、強い雨が降りました。'],
['My jacket kept me mostly dry, but water reached part of my sports bag.','上着でほとんどぬれませんでしたが、体育バッグの一部に水が入りました。'],
['After first period, I opened the bag and found my practice shirt damp.','一時間目のあとバッグを開けると、練習用シャツが湿っていました。'],
['Wearing it for afternoon practice would be uncomfortable and cold.','午後の練習で着ると、不快で寒くなりそうでした。'],
['I remembered that I kept a clean spare shirt in my classroom locker.','教室のロッカーに清潔な予備シャツを置いていたことを思い出しました。'],
['During lunch, I took out the spare and put the wet shirt in a separate bag.','昼休みに予備を取り出し、ぬれたシャツは別の袋へ入れました。'],
['I left the bag open in a safe place so the wet cloth could begin drying.','ぬれた布が乾き始めるよう、安全な場所で袋を開けておきました。'],
['The clean shirt was ready when practice started after school.','放課後の練習開始時には清潔なシャツを使えました。'],
['I could move comfortably without wearing cold wet clothes.','冷たくぬれた服を着ず、快適に動けました。'],
['At home, I washed both shirts and dried the sports bag completely.','家で両方のシャツを洗い、体育バッグも完全に乾かしました。'],
['The next morning, I put another clean spare back in the locker.','次の朝、新しい清潔な予備をまたロッカーへ入れました。'],
['Keeping one spare item turned a wet-bag problem into a small change.','予備を一つ置いていたことで、ぬれたバッグの問題を小さな変更で済ませられました。']
],false,[['spare','予備の'],['damp','湿った'],['cloth','布']]),
build('V11-NH-G2-U7-4-045',NH,'Unit 7-4',nhBase,'The Exchange Student Map Note',[
['An exchange student joined our class and received a detailed school map.','交換留学生が私たちのクラスに加わり、詳しい校内図を受け取りました。'],
['The map showed every classroom, office, stairway, and special room.','地図にはすべての教室、職員室、階段、特別教室が載っていました。'],
['He said the information was useful but difficult to read all at once.','情報は役立つが、一度に全部読むのは難しいと言いました。'],
['For his first day, he only needed five places before going home.','初日は帰宅までに五つの場所だけ必要でした。'],
['We asked him which classes and activities were on his schedule.','どの授業と活動が予定にあるかたずねました。'],
['Then I circled his classroom, the gym, the library, the lunch room, and the front gate.','それから教室、体育館、図書室、昼食場所、正門を丸で囲みました。'],
['A friend drew a simple line showing the order he would visit them.','友達が訪れる順番を示す簡単な線を描きました。'],
['We left the other map labels unchanged in case he needed them later.','あとで必要になる場合に備え、ほかの表示はそのまま残しました。'],
['He folded the map so the marked center stayed easy to see.','印を付けた中心部分が見やすいよう地図を折りました。'],
['During the day, he checked the circles instead of searching the whole map.','その日は地図全体を探さず、丸印を確認しました。'],
['He reached every place on time and asked fewer direction questions.','すべての場所に時間どおり着き、道をたずねる回数も減りました。'],
['Marking only the first-day places made a detailed map easier to use.','初日に必要な場所だけ印を付けることで、詳しい地図が使いやすくなりました。']
],false,[['detailed','詳しい'],['stairway','階段'],['circled','丸で囲んだ']])
];
window.V11_BATCH05_G2_PASSAGES=all;
window.V11_BATCH05_G2_META={batch:BATCH,count:all.length,registered:false,grade2:17};
})();
