window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 10-1']={
 id:'V10-SS-G1-P10-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-1',level:'HOP',title:'Homework with Grandma',
 sentences:['Yesterday, I was tired.','My grandma was at home with me.','I had homework.','I was sleepy, too.','My grandma had an idea.','It was an awesome idea.','We finished my homework together.','Then we talked about my school.','We were at home after that.','My grandma was fine.','I was fine, too.','We were happy.','It was a great evening.'],
 fullTranslation:'「昨日、私は疲れていました。祖母が家で私といっしょにいました。私は宿題がありました。私は眠くもありました。祖母には考えがありました。それはとてもよい考えでした。私たちはいっしょに私の宿題を終えました。それから学校について話しました。そのあとも、私たちは家にいました。祖母は元気でした。私も元気でした。私たちはうれしかったです。すばらしい夕方でした。」',
 slashRows:[{en:'Yesterday, / I was / tired.',jp:'昨日 / 私は〜でした / 疲れて'},{en:'My grandma was / at home / with me.',jp:'私の祖母はいました / 家に / 私といっしょに'},{en:'I had / homework.',jp:'私は持っていました / 宿題を'},{en:'I was / sleepy, too.',jp:'私は〜でもありました / 眠い'},{en:'My grandma had / an idea.',jp:'私の祖母にはありました / 1つの考えが'},{en:'It was / an awesome idea.',jp:'それは〜でした / とてもよい考え'},{en:'We finished / my homework / together.',jp:'私たちは終えました / 私の宿題を / いっしょに'},{en:'Then / we talked about / my school.',jp:'それから / 私たちは話しました / 私の学校について'},{en:'We were / at home / after that.',jp:'私たちはいました / 家に / そのあとも'},{en:'My grandma was / fine.',jp:'私の祖母は〜でした / 元気な'},{en:'I was / fine, too.',jp:'私も〜でした / 元気な'},{en:'We were / happy.',jp:'私たちは〜でした / うれしい'},{en:'It was / a great evening.',jp:'それは〜でした / すばらしい夕方'}],
 questions:[{prompt:'1. 昨日、話し手はどのような状態でしたか。本文から英語で1語抜き出しなさい。',answer:'tired',evidence:'Yesterday, I was tired.',evidenceJp:'昨日、私は疲れていました。',reason:'tired が昨日の話し手の状態を表しています。'},{prompt:'2. 誰が話し手と家にいましたか。本文から英語で答えなさい。',answer:'My grandma',evidence:'My grandma was at home with me.',evidenceJp:'祖母が家で私といっしょにいました。',reason:'文の主語 My grandma がいっしょにいた人です。'},{prompt:'3. 話し手には何がありましたか。本文から英語で答えなさい。',answer:'homework',evidence:'I had homework.',evidenceJp:'私は宿題がありました。',reason:'had の目的語 homework があったものです。'},{prompt:'4. 祖母には何がありましたか。本文から英語で答えなさい。',answer:'an idea',evidence:'My grandma had an idea.',evidenceJp:'祖母には1つの考えがありました。',reason:'had の目的語 an idea が祖母の考えです。'},{prompt:'5. 2人は何をいっしょに終えましたか。本文から英語で答えなさい。',answer:'my homework',evidence:'We finished my homework together.',evidenceJp:'私たちはいっしょに私の宿題を終えました。',reason:'finished の目的語 my homework が終えたものです。'}],
 allowedWords:[['grandma / warming / finish / awesome / idea / homework / fine / tired / sleepy / were / was','PROGRAM 10-1: id697-707'],['finished / talked','PROGRAM 9-1以降で解禁済みの規則過去形'],['had','Get Ready 6で表層形登録済み'],['yesterday / home / with / me / then / school / after / happy / evening / together / my / I / at / too / an / it / we / a / great','cumulative / elementary']],
 auditNote:'正本VOCABでPROGRAM 10-1はid697〜707。id706 were、id707 wasが明示登録され、このPartからbe動詞過去形を使用。finishは同Part新出で、過去文法はPROGRAM 9-1から解禁済みのため規則過去finishedを使用。初稿のkitchenは正本上中2初出だったため削除し、既習確定のat homeへ置換。warmingは自然な本文に無理に入れず未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};