window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 10-1']={
 id:'V10-SS-G1-P10-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-1',level:'HOP',title:'Homework with Grandma',
 sentences:['Yesterday, I was tired.','My grandma was at home with me.','I had homework.','I was sleepy, too.','My grandma had an idea.','It was an awesome idea.','We finished my homework together.','Then we talked about my school.','We were at home after that.','My grandma was fine.','I was fine, too.','We were happy.','It was a great evening.'],
 fullTranslation:'「昨日、私は疲れていました。祖母が家で私といっしょにいました。私は宿題がありました。私は眠くもありました。祖母には考えがありました。それはとてもよい考えでした。私たちはいっしょに私の宿題を終えました。それから学校について話しました。そのあとも、私たちは家にいました。祖母は元気でした。私も元気でした。私たちはうれしかったです。すばらしい夕方でした。」',
 slashRows:[{en:'Yesterday, / I was / tired.',jp:'昨日 / 私は〜でした / 疲れて'},{en:'My grandma was / at home / with me.',jp:'私の祖母はいました / 家に / 私といっしょに'},{en:'I had / homework.',jp:'私は持っていました / 宿題を'},{en:'I was / sleepy, too.',jp:'私は〜でもありました / 眠い'},{en:'My grandma had / an idea.',jp:'私の祖母にはありました / 1つの考えが'},{en:'It was / an awesome idea.',jp:'それは〜でした / とてもよい考え'},{en:'We finished / my homework / together.',jp:'私たちは終えました / 私の宿題を / いっしょに'},{en:'Then / we talked about / my school.',jp:'それから / 私たちは話しました / 私の学校について'},{en:'We were / at home / after that.',jp:'私たちはいました / 家に / そのあとも'},{en:'My grandma was / fine.',jp:'私の祖母は〜でした / 元気な'},{en:'I was / fine, too.',jp:'私も〜でした / 元気な'},{en:'We were / happy.',jp:'私たちは〜でした / うれしい'},{en:'It was / a great evening.',jp:'それは〜でした / すばらしい夕方'}],
 questions:[{prompt:'1. 昨日、話し手はどのような状態でしたか。本文から英語で1語抜き出しなさい。',answer:'tired',evidence:'Yesterday, I was tired.',evidenceJp:'昨日、私は疲れていました。',reason:'tired が昨日の話し手の状態を表しています。'},{prompt:'2. 誰が話し手と家にいましたか。本文から英語で答えなさい。',answer:'My grandma',evidence:'My grandma was at home with me.',evidenceJp:'祖母が家で私といっしょにいました。',reason:'文の主語 My grandma がいっしょにいた人です。'},{prompt:'3. 話し手には何がありましたか。本文から英語で答えなさい。',answer:'homework',evidence:'I had homework.',evidenceJp:'私は宿題がありました。',reason:'had の目的語 homework があったものです。'},{prompt:'4. 祖母には何がありましたか。本文から英語で答えなさい。',answer:'an idea',evidence:'My grandma had an idea.',evidenceJp:'祖母には1つの考えがありました。',reason:'had の目的語 an idea が祖母の考えです。'},{prompt:'5. 2人は何をいっしょに終えましたか。本文から英語で答えなさい。',answer:'my homework',evidence:'We finished my homework together.',evidenceJp:'私たちはいっしょに私の宿題を終えました。',reason:'finished の目的語 my homework が終えたものです。'}],
 allowedWords:[['grandma / warming / finish / awesome / idea / homework / fine / tired / sleepy / were / was','PROGRAM 10-1: id697-707'],['finished / talked','PROGRAM 9-1以降で解禁済みの規則過去形'],['had','Get Ready 6で表層形登録済み'],['yesterday / home / with / me / then / school / after / happy / evening / together / my / I / at / too / an / it / we / a / great','cumulative / elementary']],
 auditNote:'正本VOCABでPROGRAM 10-1はid697〜707。id706 were、id707 wasが明示登録され、このPartからbe動詞過去形を使用。finishは同Part新出で、過去文法はPROGRAM 9-1から解禁済みのため規則過去finishedを使用。初稿のkitchenは正本上中2初出だったため削除し、既習確定のat homeへ置換。warmingは自然な本文に無理に入れず未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES['Step 6 / Our Project 3 / Power-Up 6']={
 id:'V10-SS-G1-STEP6-001',textbook:'サンシャイン',grade:'1',section:'Step 6 / Our Project 3 / Power-Up 6',level:'HOP',title:'A Card to My Friend',
 sentences:['Dear Anna,','In February, I went to a school performance.','It was my first performance.','I was nervous.','My friend was nervous, too.','The performance was creative and exciting.','After the performance, we took a shot.','We went to a famous street.','The view was beautiful.','I have a card from the street.','The card is under my book now.','My hobby is music.','I miss you.','It was a great day.','Best wishes,'],
 fullTranslation:'「親愛なるアンナへ。2月に、私は学校の発表会へ行きました。それは私にとって初めての発表会でした。私は緊張していました。友達も緊張していました。その発表会は創造的で、わくわくするものでした。発表会のあと、私たちは写真を1枚撮りました。私たちは有名な通りへ行きました。景色はきれいでした。私はその通りでもらったカードを持っています。そのカードは今、私の本の下にあります。私の趣味は音楽です。あなたがいなくてさびしいです。すばらしい一日でした。幸運を祈ります。」',
 slashRows:[{en:'Dear Anna,',jp:'親愛なるアンナへ'},{en:'In February, / I went to / a school performance.',jp:'2月に / 私は行きました / 学校の発表会へ'},{en:'It was / my first performance.',jp:'それは〜でした / 私の初めての発表会'},{en:'I was / nervous.',jp:'私は〜でした / 緊張して'},{en:'My friend was / nervous, too.',jp:'私の友達も〜でした / 緊張して'},{en:'The performance was / creative and exciting.',jp:'その発表会は〜でした / 創造的でわくわくする'},{en:'After the performance, / we took / a shot.',jp:'発表会のあと / 私たちは撮りました / 1枚の写真を'},{en:'We went to / a famous street.',jp:'私たちは行きました / 有名な通りへ'},{en:'The view was / beautiful.',jp:'景色は〜でした / 美しい'},{en:'I have / a card / from the street.',jp:'私は持っています / 1枚のカードを / その通りからの'},{en:'The card is / under my book / now.',jp:'そのカードはあります / 私の本の下に / 今'},{en:'My hobby is / music.',jp:'私の趣味は〜です / 音楽'},{en:'I miss / you.',jp:'私はさびしく思います / あなたがいなくて'},{en:'It was / a great day.',jp:'それは〜でした / すばらしい一日'},{en:'Best wishes,',jp:'幸運を祈ります'}],
 questions:[{prompt:'1. 話し手が発表会へ行ったのは何月ですか。本文から英語で答えなさい。',answer:'February',evidence:'In February, I went to a school performance.',evidenceJp:'2月に、私は学校の発表会へ行きました。',reason:'文頭の In February が発表会へ行った月を表しています。'},{prompt:'2. その発表会は話し手にとって何回目でしたか。本文から英語で答えなさい。',answer:'first',evidence:'It was my first performance.',evidenceJp:'それは私にとって初めての発表会でした。',reason:'first が「初めての」を表しています。'},{prompt:'3. 発表会の前後で話し手はどんな気持ちでしたか。本文から英語で1語抜き出しなさい。',answer:'nervous',evidence:'I was nervous.',evidenceJp:'私は緊張していました。',reason:'nervous が話し手の状態を表しています。'},{prompt:'4. 発表会のあと、何を撮りましたか。本文から英語で答えなさい。',answer:'a shot',evidence:'After the performance, we took a shot.',evidenceJp:'発表会のあと、私たちは写真を1枚撮りました。',reason:'took の目的語 a shot が撮ったものです。'},{prompt:'5. カードは今どこにありますか。本文から英語で答えなさい。',answer:'under my book',evidence:'The card is under my book now.',evidenceJp:'そのカードは今、私の本の下にあります。',reason:'under my book がカードの場所を示しています。'}],
 allowedWords:[['under / hobby / performance / shot / nervous / creative / first / wish / view / St. / dear / miss / February / card / street / Best wishes,','Step 6 / Our Project 3 / Power-Up 6: id757-772'],['went','PROGRAM 9-3で表層形登録済み'],['took','PROGRAM 9-2で表層形登録済み'],['was','PROGRAM 10-1で表層形登録済み'],['friend / exciting / after / famous / beautiful / book / now / music / day / have / from / the / my / I / in / to / a / we / you / great / too / and / is','cumulative / elementary']],
 auditNote:'正本VOCABで中1最終区分はid757〜772のStep 6 / Our Project 3 / Power-Up 6。id773から中2PROGRAM 1-1へ切り替わることを確認。最終到達単元を選べるよう、手紙・カード形式の1場面として作成。went / took / wasはそれぞれPROGRAM 9-3 / 9-2 / 10-1で明示登録済みの過去形のみ使用し、新しい活用形は生成していない。St. / wish は無理な消化を避け未使用、Dear / Best wishes, は書式として使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};