window.V10_PASSAGES=window.V10_PASSAGES||{};

window.V10_PASSAGES['PROGRAM 10-1']={
 id:'V10-SS-G1-P10-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-1',level:'HOP',title:'Homework with Grandma',
 sentences:['Yesterday, I was tired.','My grandma was at home with me.','I had homework.','I was sleepy, too.','My grandma had an idea.','It was an awesome idea.','We finished my homework together.','Then we talked about my school.','We were in the kitchen after that.','My grandma was fine.','I was fine, too.','We were happy.','It was a great evening.'],
 fullTranslation:'「昨日、私は疲れていました。祖母が家で私といっしょにいました。私は宿題がありました。私は眠くもありました。祖母には考えがありました。それはとてもよい考えでした。私たちはいっしょに私の宿題を終えました。それから学校について話しました。そのあと、私たちは台所にいました。祖母は元気でした。私も元気でした。私たちはうれしかったです。すばらしい夕方でした。」',
 slashRows:[{en:'Yesterday, / I was / tired.',jp:'昨日 / 私は〜でした / 疲れて'},{en:'My grandma was / at home / with me.',jp:'私の祖母はいました / 家に / 私といっしょに'},{en:'I had / homework.',jp:'私は持っていました / 宿題を'},{en:'I was / sleepy, too.',jp:'私は〜でもありました / 眠い'},{en:'My grandma had / an idea.',jp:'私の祖母にはありました / 1つの考えが'},{en:'It was / an awesome idea.',jp:'それは〜でした / とてもよい考え'},{en:'We finished / my homework / together.',jp:'私たちは終えました / 私の宿題を / いっしょに'},{en:'Then / we talked about / my school.',jp:'それから / 私たちは話しました / 私の学校について'},{en:'We were / in the kitchen / after that.',jp:'私たちはいました / 台所に / そのあと'},{en:'My grandma was / fine.',jp:'私の祖母は〜でした / 元気な'},{en:'I was / fine, too.',jp:'私も〜でした / 元気な'},{en:'We were / happy.',jp:'私たちは〜でした / うれしい'},{en:'It was / a great evening.',jp:'それは〜でした / すばらしい夕方'}],
 questions:[{prompt:'1. 昨日、話し手はどのような状態でしたか。本文から英語で1語抜き出しなさい。',answer:'tired',evidence:'Yesterday, I was tired.',evidenceJp:'昨日、私は疲れていました。',reason:'tired が昨日の話し手の状態を表しています。'},{prompt:'2. 誰が話し手と家にいましたか。本文から英語で答えなさい。',answer:'My grandma',evidence:'My grandma was at home with me.',evidenceJp:'祖母が家で私といっしょにいました。',reason:'文の主語 My grandma がいっしょにいた人です。'},{prompt:'3. 話し手には何がありましたか。本文から英語で答えなさい。',answer:'homework',evidence:'I had homework.',evidenceJp:'私は宿題がありました。',reason:'had の目的語 homework があったものです。'},{prompt:'4. 祖母には何がありましたか。本文から英語で答えなさい。',answer:'an idea',evidence:'My grandma had an idea.',evidenceJp:'祖母には1つの考えがありました。',reason:'had の目的語 an idea が祖母の考えです。'},{prompt:'5. 2人は何をいっしょに終えましたか。本文から英語で答えなさい。',answer:'my homework',evidence:'We finished my homework together.',evidenceJp:'私たちはいっしょに私の宿題を終えました。',reason:'finished の目的語 my homework が終えたものです。'}],
 allowedWords:[['grandma / warming / finish / awesome / idea / homework / fine / tired / sleepy / were / was','PROGRAM 10-1: id697-707'],['finished / talked','PROGRAM 9-1以降で解禁済みの規則過去形'],['had','Get Ready 6で表層形登録済み'],['yesterday / home / with / me / then / school / kitchen / after / happy / evening / together / my / I / at / too / an / it / we / in / a / great','cumulative / elementary']],
 auditNote:'正本VOCABでPROGRAM 10-1はid697〜707。id706 were、id707 wasが明示登録され、このPartからbe動詞過去形を使用。finishは同Part新出で、過去文法はPROGRAM 9-1から解禁済みのため規則過去finishedを使用。warmingは自然な本文に無理に入れず未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES['PROGRAM 10-2']={
 id:'V10-SS-G1-P10-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-2',level:'HOP',title:'Yesterday at the Theater',
 sentences:['Yesterday, my friend and I were at the theater.','The theater wasn’t busy.','It was quiet.','We watched a movie.','The movie was interesting.','I wasn’t tired.','My friend wasn’t sleepy.','We had a good time.','After the movie, we talked about the movie.','We went home together.','My house wasn’t far from the theater.','I was happy.','The theater was great.'],
 fullTranslation:'「昨日、友達と私は劇場にいました。劇場は忙しくありませんでした。静かでした。私たちは映画を見ました。その映画はおもしろかったです。私は疲れていませんでした。友達も眠くありませんでした。私たちは楽しい時間を過ごしました。映画のあと、その映画について話しました。私たちはいっしょに家へ帰りました。私の家は劇場から遠くありませんでした。私はうれしかったです。劇場はすばらしかったです。」',
 slashRows:[{en:'Yesterday, / my friend and I / were at the theater.',jp:'昨日 / 友達と私は / 劇場にいました'},{en:'The theater wasn’t / busy.',jp:'その劇場は〜ではありませんでした / 忙しい'},{en:'It was / quiet.',jp:'それは〜でした / 静かな'},{en:'We watched / a movie.',jp:'私たちは見ました / 映画を'},{en:'The movie was / interesting.',jp:'その映画は〜でした / おもしろい'},{en:'I wasn’t / tired.',jp:'私は〜ではありませんでした / 疲れて'},{en:'My friend wasn’t / sleepy.',jp:'私の友達は〜ではありませんでした / 眠い'},{en:'We had / a good time.',jp:'私たちは過ごしました / 楽しい時間を'},{en:'After the movie, / we talked about / the movie.',jp:'映画のあと / 私たちは話しました / その映画について'},{en:'We went home / together.',jp:'私たちは家へ帰りました / いっしょに'},{en:'My house wasn’t / far from the theater.',jp:'私の家は〜ではありませんでした / 劇場から遠い'},{en:'I was / happy.',jp:'私は〜でした / うれしい'},{en:'The theater was / great.',jp:'その劇場は〜でした / すばらしい'}],
 questions:[{prompt:'1. 2人は昨日どこにいましたか。本文から英語で答えなさい。',answer:'the theater',evidence:'Yesterday, my friend and I were at the theater.',evidenceJp:'昨日、友達と私は劇場にいました。',reason:'at the theater が2人のいた場所です。'},{prompt:'2. 劇場は忙しかったですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'The theater wasn’t busy.',evidenceJp:'劇場は忙しくありませんでした。',reason:'wasn’t busy と否定しているので No です。'},{prompt:'3. 2人は何を見ましたか。本文から英語で答えなさい。',answer:'a movie',evidence:'We watched a movie.',evidenceJp:'私たちは映画を見ました。',reason:'watched の目的語 a movie が見たものです。'},{prompt:'4. 話し手は疲れていましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I wasn’t tired.',evidenceJp:'私は疲れていませんでした。',reason:'wasn’t tired と否定しています。'},{prompt:'5. 2人は映画のあと何をしましたか。本文から英語で答えなさい。',answer:'talked about the movie',evidence:'After the movie, we talked about the movie.',evidenceJp:'映画のあと、その映画について話しました。',reason:'talked about the movie が映画のあとの行動です。'}],
 allowedWords:[['theater / wasn’t','PROGRAM 10-2: id708-709'],['were / was / tired / sleepy','PROGRAM 10-1 cumulative'],['watched / talked','PROGRAM 9-1以降で解禁済みの規則過去形'],['went','PROGRAM 9-3で表層形登録済み'],['had','Get Ready 6で表層形登録済み'],['busy / quiet / movie / interesting / home / house / far / happy / together / yesterday / friend / my / I / at / the / it / we / a / good / time / after / about / from / great','cumulative / elementary']],
 auditNote:'PROGRAM 10-2はid708 theater、id709 wasn’tの2語。was/wereは10-1で解禁済み、wasn’tはこのPartで表層形が明示登録されるため使用。未登録のweren’tは使用していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES['PROGRAM 10-3']={
 id:'V10-SS-G1-P10-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-3',level:'HOP',title:'A Comic Story at Seven',
 sentences:['Last night, I was at home.','I read a comic story.','The story was about a detective.','At seven, my friend called me.','I was surprised.','We talked about the comic story.','Then I surfed the internet.','I read my English textbook, too.','My textbook was on my desk.','I called my friend again.','We talked about homework.','I wasn’t tired.','It was a good night.'],
 fullTranslation:'「昨夜、私は家にいました。マンガの物語を読みました。その物語は探偵についてのものでした。7時に友達が私に電話をしました。私は驚きました。私たちはそのマンガの物語について話しました。それから私はインターネットを見て回りました。英語の教科書も読みました。教科書は机の上にありました。私はもう一度友達に電話をしました。私たちは宿題について話しました。私は疲れていませんでした。よい夜でした。」',
 slashRows:[{en:'Last night, / I was / at home.',jp:'昨夜 / 私はいました / 家に'},{en:'I read / a comic story.',jp:'私は読みました / マンガの物語を'},{en:'The story was / about a detective.',jp:'その物語は〜でした / 探偵についての'},{en:'At seven, / my friend called / me.',jp:'7時に / 私の友達が電話しました / 私に'},{en:'I was / surprised.',jp:'私は〜でした / 驚いた'},{en:'We talked about / the comic story.',jp:'私たちは話しました / そのマンガの物語について'},{en:'Then / I surfed / the internet.',jp:'それから / 私は見て回りました / インターネットを'},{en:'I read / my English textbook, too.',jp:'私は読みました / 私の英語の教科書も'},{en:'My textbook was / on my desk.',jp:'私の教科書はありました / 私の机の上に'},{en:'I called / my friend / again.',jp:'私は電話しました / 私の友達に / もう一度'},{en:'We talked about / homework.',jp:'私たちは話しました / 宿題について'},{en:'I wasn’t / tired.',jp:'私は〜ではありませんでした / 疲れて'},{en:'It was / a good night.',jp:'それは〜でした / よい夜'}],
 questions:[{prompt:'1. 話し手は昨夜、何を読みましたか。本文から英語で答えなさい。',answer:'a comic story',evidence:'I read a comic story.',evidenceJp:'私はマンガの物語を読みました。',reason:'read の目的語 a comic story が読んだものです。'},{prompt:'2. その物語は何についてのものでしたか。本文から英語で答えなさい。',answer:'a detective',evidence:'The story was about a detective.',evidenceJp:'その物語は探偵についてのものでした。',reason:'about の後ろの a detective が物語の内容です。'},{prompt:'3. 友達は何時に電話しましたか。本文から英語で答えなさい。',answer:'seven',evidence:'At seven, my friend called me.',evidenceJp:'7時に友達が私に電話をしました。',reason:'At seven が電話の時刻です。'},{prompt:'4. 電話が来たとき、話し手はどんな気持ちでしたか。本文から英語で1語抜き出しなさい。',answer:'surprised',evidence:'I was surprised.',evidenceJp:'私は驚きました。',reason:'surprised が話し手の状態を表しています。'},{prompt:'5. 話し手は英語の何を読みましたか。本文から英語で答えなさい。',answer:'my English textbook',evidence:'I read my English textbook, too.',evidenceJp:'私は英語の教科書も読みました。',reason:'read の目的語 my English textbook が読んだものです。'}],
 allowedWords:[['story / call / surf / surprised / seven / textbook / comic','PROGRAM 10-3: id710-716'],['called / surfed / talked','PROGRAM 9-1以降で解禁済みの規則過去形'],['was / wasn’t','PROGRAM 10-1〜10-2 cumulative'],['read','PROGRAM 9-2で過去用法の表層形登録済み'],['detective / internet / English / desk / homework / tired / last night / home / friend / me / then / again / my / I / at / the / about / a / we / too / on / good / it','cumulative / elementary']],
 auditNote:'PROGRAM 10-3はid710〜716。story / call / surf / surprised / seven / textbook / comicを、夜の読書と電話の1場面に統合。call / surfは過去文法が既に解禁されているため規則過去called / surfedを使用。新しい不規則過去形は生成していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES['PROGRAM 10-4']={
 id:'V10-SS-G1-P10-4-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 10-4',level:'HOP',title:'A Broken Sleigh',
 sentences:['Last winter, my family and I were in a snowy town.','We got on a sleigh.','We started on a hill.','The sleigh went down a slope.','The speed increased.','Bang!','The sleigh broke.','It was terrible.','We walked to a small house.','We reached the house.','A raccoon dog was near the house.','A warm quilt was in a closet.','The quilt was fluffy.','We had hot water.','Finally, we were warm and safe.'],
 fullTranslation:'「この前の冬、家族と私は雪の多い町にいました。私たちはそりに乗りました。丘から出発しました。そりは坂を下りました。スピードが増しました。バン！ そりが壊れました。ひどい状態でした。私たちは小さな家まで歩きました。その家に着きました。家の近くにはタヌキがいました。押入れには暖かいキルトがありました。そのキルトはふわふわでした。私たちは熱いお湯を飲みました。ついに、私たちは暖まり、安全になりました。」',
 slashRows:[{en:'Last winter, / my family and I / were in a snowy town.',jp:'この前の冬 / 家族と私は / 雪の多い町にいました'},{en:'We got on / a sleigh.',jp:'私たちは乗りました / そりに'},{en:'We started / on a hill.',jp:'私たちは出発しました / 丘で'},{en:'The sleigh went down / a slope.',jp:'そのそりは下りました / 坂を'},{en:'The speed increased.',jp:'スピードが増しました'},{en:'Bang!',jp:'バン！'},{en:'The sleigh broke.',jp:'そのそりは壊れました'},{en:'It was / terrible.',jp:'それは〜でした / ひどい'},{en:'We walked / to a small house.',jp:'私たちは歩きました / 小さな家まで'},{en:'We reached / the house.',jp:'私たちは着きました / その家に'},{en:'A raccoon dog was / near the house.',jp:'タヌキがいました / その家の近くに'},{en:'A warm quilt was / in a closet.',jp:'暖かいキルトがありました / 押入れに'},{en:'The quilt was / fluffy.',jp:'そのキルトは〜でした / ふわふわの'},{en:'We had / hot water.',jp:'私たちは飲みました / 熱いお湯を'},{en:'Finally, / we were / warm and safe.',jp:'ついに / 私たちは〜でした / 暖かく安全な'}],
 questions:[{prompt:'1. 家族は何に乗りましたか。本文から英語で答えなさい。',answer:'a sleigh',evidence:'We got on a sleigh.',evidenceJp:'私たちはそりに乗りました。',reason:'got on の後ろの a sleigh が乗ったものです。'},{prompt:'2. そりはどこを下りましたか。本文から英語で答えなさい。',answer:'a slope',evidence:'The sleigh went down a slope.',evidenceJp:'そりは坂を下りました。',reason:'went down の後ろの a slope が下った場所です。'},{prompt:'3. 途中でそりに何が起こりましたか。本文から英語で答えなさい。',answer:'The sleigh broke.',evidence:'The sleigh broke.',evidenceJp:'そりが壊れました。',reason:'broke がそりに起きた出来事を示しています。'},{prompt:'4. 家の近くには何がいましたか。本文から英語で答えなさい。',answer:'a raccoon dog',evidence:'A raccoon dog was near the house.',evidenceJp:'家の近くにはタヌキがいました。',reason:'文の主語 a raccoon dog が家の近くにいた動物です。'},{prompt:'5. キルトはどのようだと書かれていますか。本文から英語で1語抜き出しなさい。',answer:'fluffy',evidence:'The quilt was fluffy.',evidenceJp:'そのキルトはふわふわでした。',reason:'fluffy がキルトの様子を表しています。'}],
 allowedWords:[['matter / bedroom / trampoline / follow / young / freezing / bed / snowy / What’s the matter? / sound / sleigh / hill / slope / speed / hold / increase / bad / terrible / enough / bang / leg / start / off / broke / cut ～ off / get on ～ / hold on to ～ / end / raccoon dog / closet / quilt / yourself / yourselves / reach / warm / pull / steam / fluffy / finally / hot','PROGRAM 10-4: id717-756'],['got','PROGRAM 4-3で表層形登録済み'],['went / went down','PROGRAM 9-3〜9-4 cumulative'],['started / increased / walked / reached','PROGRAM 9-1以降のpast文法下で用いる規則過去形'],['was / were','PROGRAM 10-1 cumulative'],['had','Get Ready 6で表層形登録済み'],['family / winter / town / small / house / near / water / safe / last / my / I / in / we / on / a / the / it / to / and','cumulative / elementary']],
 auditNote:'PROGRAM 10-4はid717〜756、id757からStep 6 / Our Project 3 / Power-Up 6。brokeはこのPartで表層形が明示登録されるため使用。get on ～は同Part登録で、過去のgotは既にPROGRAM 4-3で表層形登録済み。start / increase / reachは過去文法解禁後の規則過去形として使用。未登録のheld等は生成していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};