window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 1-1']={
id:'V10-SS-G1-P1-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-1',level:'HOP',title:'A Junior High School Student',
sentences:['Hi.','I’m a junior high school student.','I’m not shy.','I’m friendly.','My teacher is kind.','I like my teacher.','I like music.','I play the trumpet.','I practice every Wednesday.','I like my school.','I play basketball, too.','School is really great.','Goodbye.'],
fullTranslation:'「こんにちは。私は中学生です。私は恥ずかしがりではありません。人なつっこいです。私の先生は親切です。私は先生が好きです。音楽が好きです。トランペットを演奏します。毎週水曜日に練習します。学校が好きです。バスケットボールもします。学校は本当にすばらしいです。さようなら。」',
slashRows:[{en:'Hi.',jp:'こんにちは。'},{en:'I’m / a junior high school student.',jp:'私は〜です / 中学生'},{en:'I’m not / shy.',jp:'私は〜ではありません / 恥ずかしがり'},{en:'I’m / friendly.',jp:'私は〜です / 人なつっこい'},{en:'My teacher is / kind.',jp:'私の先生は〜です / 親切な'},{en:'I like / my teacher.',jp:'私は好きです / 私の先生が'},{en:'I like / music.',jp:'私は好きです / 音楽が'},{en:'I play / the trumpet.',jp:'私は演奏します / トランペットを'},{en:'I practice / every Wednesday.',jp:'私は練習します / 毎週水曜日に'},{en:'I like / my school.',jp:'私は好きです / 私の学校が'},{en:'I play / basketball, too.',jp:'私はします / バスケットボールも'},{en:'School is / really great.',jp:'学校は〜です / 本当にすばらしい'},{en:'Goodbye.',jp:'さようなら。'}],
questions:[{prompt:'1. 話し手はどんな生徒ですか。本文から英語で答えなさい。',answer:'a junior high school student',evidence:'I’m a junior high school student.',evidenceJp:'私は中学生です。',reason:'be動詞の後ろの a junior high school student が話し手の立場を表しています。'},{prompt:'2. 話し手は恥ずかしがりですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I’m not shy.',evidenceJp:'私は恥ずかしがりではありません。',reason:'not shy と否定しているので No です。'},{prompt:'3. 先生はどのような人ですか。本文から英語で1語抜き出しなさい。',answer:'kind',evidence:'My teacher is kind.',evidenceJp:'私の先生は親切です。',reason:'kind が先生の性格を表しています。'},{prompt:'4. 話し手は何を演奏しますか。本文から英語で答えなさい。',answer:'the trumpet',evidence:'I play the trumpet.',evidenceJp:'私はトランペットを演奏します。',reason:'play の目的語 the trumpet が演奏する楽器です。'},{prompt:'5. 話し手はバスケットボールもしますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I play basketball, too.',evidenceJp:'私はバスケットボールもします。',reason:'too が「〜も」を表し、basketball もすることが示されています。'}],
allowedWords:[['shy / teacher / student / kind / junior / friendly / not / hi / goodbye / I’m / junior high school','PROGRAM 1-1: id129-147'],['music / trumpet / practice / every / Wednesday / school / basketball','Get Ready 4 cumulative'],['really / great / too','Get Ready 2 cumulative'],['I / my / is / like / play / the / a','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-1をid129〜147まで照合し、id148からPROGRAM 1-2へ切り替わることを確認。自己紹介として不自然さが残ったI’m at a junior high school.は使わず、正本登録のjunior high school＋studentを組み合わせたI’m a junior high school student.へ修正。未確認の三単現・過去形・進行形は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 1-2']={
id:'V10-SS-G1-P1-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-2',level:'HOP',title:'From Australia',
sentences:['Hello.','I’m a student.','I’m from Australia.','I’m not from Japan.','I’m not from the U.S.','Australia is really great.','My teacher is from Japan.','My teacher is kind.','I like Japan.','I like Australia, too.','I’m friendly.','School is great.','Goodbye.'],
fullTranslation:'「こんにちは。私は生徒です。オーストラリア出身です。日本出身ではありません。アメリカ合衆国出身でもありません。オーストラリアは本当にすばらしいです。私の先生は日本出身です。先生は親切です。私は日本が好きです。オーストラリアも好きです。私は人なつっこいです。学校はすばらしいです。さようなら。」',
slashRows:[{en:'Hello.',jp:'こんにちは。'},{en:'I’m / a student.',jp:'私は〜です / 生徒'},{en:'I’m from / Australia.',jp:'私は〜出身です / オーストラリア'},{en:'I’m not from / Japan.',jp:'私は〜出身ではありません / 日本'},{en:'I’m not from / the U.S.',jp:'私は〜出身ではありません / アメリカ合衆国'},{en:'Australia is / really great.',jp:'オーストラリアは〜です / 本当にすばらしい'},{en:'My teacher is from / Japan.',jp:'私の先生は〜出身です / 日本'},{en:'My teacher is / kind.',jp:'私の先生は〜です / 親切な'},{en:'I like / Japan.',jp:'私は好きです / 日本が'},{en:'I like / Australia, too.',jp:'私は好きです / オーストラリアも'},{en:'I’m / friendly.',jp:'私は〜です / 人なつっこい'},{en:'School is / great.',jp:'学校は〜です / すばらしい'},{en:'Goodbye.',jp:'さようなら。'}],
questions:[{prompt:'1. 話し手はどこの出身ですか。本文から英語で答えなさい。',answer:'Australia',evidence:'I’m from Australia.',evidenceJp:'私はオーストラリア出身です。',reason:'from の後ろの Australia が出身地を示しています。'},{prompt:'2. 話し手は日本出身ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I’m not from Japan.',evidenceJp:'私は日本出身ではありません。',reason:'not from Japan と否定しているので No です。'},{prompt:'3. 話し手はアメリカ合衆国出身ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I’m not from the U.S.',evidenceJp:'私はアメリカ合衆国出身ではありません。',reason:'not from the U.S. と否定しています。'},{prompt:'4. 先生はどこの出身ですか。本文から英語で答えなさい。',answer:'Japan',evidence:'My teacher is from Japan.',evidenceJp:'私の先生は日本出身です。',reason:'teacher に続く is from Japan が先生の出身地を示しています。'},{prompt:'5. 話し手は日本が好きですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I like Japan.',evidenceJp:'私は日本が好きです。',reason:'I like Japan. と明示されています。'}],
allowedWords:[['the U.S. / Australia / Japan / no / yes / hello / be from ～ / I’m sorry. / Pardon me?','PROGRAM 1-2: id148-158'],['I’m / not / student / teacher / kind / friendly / goodbye','PROGRAM 1-1 cumulative'],['really / great / too','Get Ready 2 cumulative'],['school','Get Ready 4 cumulative'],['I / my / is / like / from / the','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-2をid148〜158まで照合し、id159からPROGRAM 1-3へ切り替わることを確認。初稿は話者ラベルなしでAustraliaとBrazilが同一Iに見える曖昧さがあったため破棄。オーストラリア出身の1人の自己紹介へ統一し、be from ～と国名を明確に読める本文へ差し替えた。Pardon me?等は新出語消化だけを目的に無理に入れていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 1-3']={
id:'V10-SS-G1-P1-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-3',level:'HOP',title:'A New Student in This City',
sentences:['This city is nice.','I’m a new student.','This is my new class.','Nice to meet you.','I’m quiet.','I’m cheerful, too.','I like math.','I’m good at math.','I like science, too.','I’m good at science, too.','I like Japanese.','I’m a fan of movies.','My teacher is kind.','I want to be friendly.','School is really great.'],
fullTranslation:'「この街はすてきです。私は新しい生徒です。ここが私の新しいクラスです。はじめまして。私はおとなしいです。それに、明るい性格でもあります。数学が好きです。数学が得意です。理科も好きです。理科も得意です。国語も好きです。映画のファンです。私の先生は親切です。人なつっこくなりたいです。学校は本当にすばらしいです。」',
slashRows:[{en:'This city is / nice.',jp:'この街は〜です / すてきな'},{en:'I’m / a new student.',jp:'私は〜です / 新しい生徒'},{en:'This is / my new class.',jp:'これは〜です / 私の新しいクラス'},{en:'Nice to meet you.',jp:'はじめまして。'},{en:'I’m / quiet.',jp:'私は〜です / おとなしい'},{en:'I’m / cheerful, too.',jp:'私は〜でもあります / 明るい'},{en:'I like / math.',jp:'私は好きです / 数学が'},{en:'I’m good at / math.',jp:'私は得意です / 数学が'},{en:'I like / science, too.',jp:'私は好きです / 理科も'},{en:'I’m good at / science, too.',jp:'私は得意です / 理科も'},{en:'I like / Japanese.',jp:'私は好きです / 国語が'},{en:'I’m / a fan of movies.',jp:'私は〜です / 映画のファン'},{en:'My teacher is / kind.',jp:'私の先生は〜です / 親切な'},{en:'I want to be / friendly.',jp:'私は〜になりたいです / 人なつっこい'},{en:'School is / really great.',jp:'学校は〜です / 本当にすばらしい'}],
questions:[{prompt:'1. 話し手はどんな立場の人ですか。本文から英語で答えなさい。',answer:'a new student',evidence:'I’m a new student.',evidenceJp:'私は新しい生徒です。',reason:'a new student が話し手の立場を表しています。'},{prompt:'2. 話し手はどんな性格ですか。本文から英語で2語答えなさい。',answer:'quiet, cheerful',evidence:'I’m quiet. / I’m cheerful, too.',evidenceJp:'私はおとなしいです。／明るい性格でもあります。',reason:'quiet と cheerful の2つで性格を説明しています。'},{prompt:'3. 話し手が得意な教科を2つ、本文から英語で答えなさい。',answer:'math, science',evidence:'I’m good at math. / I’m good at science, too.',evidenceJp:'数学が得意です。／理科も得意です。',reason:'be good at ～ の後ろに math と science が置かれています。'},{prompt:'4. 話し手は何のファンですか。本文から英語で答えなさい。',answer:'movies',evidence:'I’m a fan of movies.',evidenceJp:'私は映画のファンです。',reason:'a fan of の後ろの movies が好きな対象です。'},{prompt:'5. 話し手はどのようになりたいですか。本文から英語で答えなさい。',answer:'friendly',evidence:'I want to be friendly.',evidenceJp:'私は人なつっこくなりたいです。',reason:'want to be の後ろの friendly がなりたい状態です。'}],
allowedWords:[['city / just / nice / this / Nice to meet you. / problem / class / go / new / want to ～ / No problem. / social studies / quiet / careful / polite / cheerful / honest / of / fan / movie / math / P.E. / Japanese / science / be good at ～','PROGRAM 1-3: id159-184'],['student / I’m / teacher / kind / friendly','PROGRAM 1-1 cumulative'],['school','Get Ready 4 cumulative'],['really / great / too','Get Ready 2 cumulative'],['I / my / is / like / a / be / want / to','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-3をid159〜184まで照合し、id185からPROGRAM 2-1へ切り替わることを確認。city / new / class / Nice to meet you. / quiet / cheerful / fan / movie / math / Japanese / science / be good at ～を中心に、新しいクラスでの自己紹介1場面に限定。cityの訳は正本語義「市、都市」を踏まえ、文脈上自然な「街」とした。未確認の比較級・三単現・過去形等は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};