window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 7-1']={
 id:'V10-SS-G2-P7-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 7-1',level:'HOP',title:'Learning about a Penguin',
 sentences:['Today, we get information about a penguin.','A penguin can breathe air.','It can swim in cold water.','It can go somewhere far for food.','At the zoo, we can watch it three times a day.','It can leave the water and warm up its body.','It can warm up its body in order to keep warm.','A penguin is not a mammal.','You cannot see fur on a penguin.','My friend and I read the information together.','We agree about one thing.','The information is quite surprising.','I want to know more about this animal.','We write the new information in our notebook.'],
 fullTranslation:'「今日、私たちはペンギンについての情報を得ます。ペンギンは空気を呼吸することができます。冷たい水の中を泳ぐことができます。食べ物を求めて遠くのどこかへ行くこともできます。動物園では1日に3回見ることができます。水から出たあと、体を温めることができます。体を温かく保つためにそうします。ペンギンはほ乳類ではありません。ペンギンに毛皮を見ることはできません。友達と私はその情報をいっしょに読みます。私たちは1つのことに同意します。その情報はとても驚くべきものです。私はこの動物についてもっと知りたいです。新しい情報をノートに書きます。」',
 slashRows:[{en:'Today, / we get / information / about a penguin.',jp:'今日 / 私たちは得ます / 情報を / ペンギンについての'},{en:'A penguin can breathe / air.',jp:'ペンギンは呼吸することができます / 空気を'},{en:'It can swim / in cold water.',jp:'それは泳ぐことができます / 冷たい水の中を'},{en:'It can go / somewhere far / for food.',jp:'それは行くことができます / 遠くのどこかへ / 食べ物を求めて'},{en:'At the zoo, / we can watch / it / three times a day.',jp:'動物園では / 私たちは見ることができます / それを / 1日に3回'},{en:'It can leave / the water / and warm up its body.',jp:'それは出ることができます / 水から / そして体を温めることができます'},{en:'It can warm up / its body / in order to keep warm.',jp:'それは温めることができます / 体を / 温かく保つために'},{en:'A penguin is not / a mammal.',jp:'ペンギンは〜ではありません / ほ乳類'},{en:'You cannot see / fur / on a penguin.',jp:'あなたは見ることができません / 毛皮を / ペンギンに'},{en:'My friend and I read / the information / together.',jp:'友達と私は読みます / その情報を / いっしょに'},{en:'We agree / about one thing.',jp:'私たちは同意します / 1つのことについて'},{en:'The information is / quite surprising.',jp:'その情報は〜です / とても驚くべきもの'},{en:'I want to know / more / about this animal.',jp:'私は知りたいです / もっと / この動物について'},{en:'We write / the new information / in our notebook.',jp:'私たちは書きます / 新しい情報を / ノートに'}],
 questions:[{prompt:'1. 今日、何についての情報を得ますか。本文から英語で答えなさい。',answer:'a penguin',evidence:'Today, we get information about a penguin.',evidenceJp:'今日、私たちはペンギンについての情報を得ます。',reason:'about の後ろの a penguin が情報の対象です。'},{prompt:'2. ペンギンは何をすることができますか。本文から英語で1語抜き出しなさい。',answer:'breathe',evidence:'A penguin can breathe air.',evidenceJp:'ペンギンは空気を呼吸することができます。',reason:'can の後ろの breathe が動作です。'},{prompt:'3. 動物園では1日に何回見ることができますか。本文から英語で答えなさい。',answer:'three times a day',evidence:'At the zoo, we can watch it three times a day.',evidenceJp:'動物園では1日に3回見ることができます。',reason:'three times a day が回数を表しています。'},{prompt:'4. 何のために体を温めますか。本文から英語で答えなさい。',answer:'in order to keep warm',evidence:'It can warm up its body in order to keep warm.',evidenceJp:'体を温かく保つために体を温めます。',reason:'in order to が目的を表しています。'},{prompt:'5. ペンギンはほ乳類ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'A penguin is not a mammal.',evidenceJp:'ペンギンはほ乳類ではありません。',reason:'is not a mammal とあるので No です。'}],
 allowedWords:[['somewhere / agree / warm up ~ / half / ~times a day / breathe / in order to ~ / mammal / information / ticket / fur / penguin / cheek / surprising / fireworks / smart / cherry blossom / awake / thick / quite / adorable / I have no idea. / all over ~','PROGRAM 7-1,2 combined canonical Sheet IDs 3294-3316'],['today / get / air / swim / cold / water / go / far / food / zoo / watch / three / leave / body / keep / warm / see / friend / read / together / one / thing / want to / know / animal / write / new / notebook','G1/G2 cumulative']],
 auditNote:'Google Sheet正本ではPROGRAM 7-1と7-2の語彙が1つのまとまり（ID3294〜3316）として登録され、個々の語の7-1/7-2帰属は分離されていない。そのため本アプリではこの正本プールを超えない範囲で7-1用本文を編集し、7-3初出のthough / not always等は先取りしていない。~times a day / in order to ~を文法・表現軸にし、未使用語を無理に詰め込んでいない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 7-2']={
 id:'V10-SS-G2-P7-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 7-2',level:'HOP',title:'A Smart Hamster',
 sentences:['At a pet shop, I see a hamster.','It is quite adorable.','A hamster can put food in its cheek.','Its cheek can get big.','The hamster can keep food there.','My friend and I ask, “How much food can it keep?”','I say, “I have no idea.”','We get information about the hamster.','Its fur is thick.','It can be awake for a long time.','I think the hamster is smart.','My friend and I agree that this is surprising.','We read more information together.','I want to see the hamster again.'],
 fullTranslation:'「ペットショップで、私はハムスターを見ます。とてもかわいいです。ハムスターはほおに食べ物を入れることができます。ほおは大きくなることがあります。ハムスターはそこに食べ物を入れておくことができます。友達と私は『どのくらい食べ物を入れておけるの？』とたずねます。私は『わかりません』と言います。私たちはハムスターについての情報を得ます。毛は厚いです。長い時間、目を覚ましていることができます。私はそのハムスターはかしこいと思います。友達と私は、これは驚くべきことだと意見が一致します。いっしょにさらに情報を読みます。私はまたそのハムスターを見たいです。」',
 slashRows:[{en:'At a pet shop, / I see / a hamster.',jp:'ペットショップで / 私は見ます / ハムスターを'},{en:'It is / quite adorable.',jp:'それは〜です / とてもかわいい'},{en:'A hamster can put / food / in its cheek.',jp:'ハムスターは入れることができます / 食べ物を / ほおに'},{en:'Its cheek can get / big.',jp:'そのほおはなることがあります / 大きく'},{en:'The hamster can keep / food / there.',jp:'そのハムスターは入れておくことができます / 食べ物を / そこに'},{en:'My friend and I ask, / “How much food can it keep?”',jp:'友達と私はたずねます / 「どのくらい食べ物を入れておけるの？」と'},{en:'I say, / “I have no idea.”',jp:'私は言います / 「わかりません」と'},{en:'We get / information / about the hamster.',jp:'私たちは得ます / 情報を / ハムスターについての'},{en:'Its fur is / thick.',jp:'その毛は〜です / 厚い'},{en:'It can be / awake / for a long time.',jp:'それは〜でいることができます / 目がさめて / 長い時間'},{en:'I think / the hamster is / smart.',jp:'私は思います / そのハムスターは〜だと / かしこい'},{en:'My friend and I agree / that this is / surprising.',jp:'友達と私は意見が一致します / これは〜だと / 驚くべきこと'},{en:'We read / more information / together.',jp:'私たちは読みます / さらに情報を / いっしょに'},{en:'I want to see / the hamster / again.',jp:'私は見たいです / そのハムスターを / また'}],
 questions:[{prompt:'1. どこでハムスターを見ますか。本文から英語で答えなさい。',answer:'At a pet shop',evidence:'At a pet shop, I see a hamster.',evidenceJp:'ペットショップで、私はハムスターを見ます。',reason:'At a pet shop が場所を表しています。'},{prompt:'2. ハムスターはどこに食べ物を入れることができますか。本文から英語で答えなさい。',answer:'in its cheek',evidence:'A hamster can put food in its cheek.',evidenceJp:'ハムスターはほおに食べ物を入れることができます。',reason:'in its cheek が場所を表しています。'},{prompt:'3. 話し手は質問にどう答えますか。本文から英語で答えなさい。',answer:'I have no idea.',evidence:'I say, “I have no idea.”',evidenceJp:'私は「わかりません」と言います。',reason:'引用部分 I have no idea. が話し手の答えです。'},{prompt:'4. ハムスターの毛はどのようですか。本文から英語で1語抜き出しなさい。',answer:'thick',evidence:'Its fur is thick.',evidenceJp:'毛は厚いです。',reason:'thick が fur の様子を表しています。'},{prompt:'5. 話し手はハムスターをどのようだと思っていますか。本文から英語で1語抜き出しなさい。',answer:'smart',evidence:'I think the hamster is smart.',evidenceJp:'私はそのハムスターはかしこいと思います。',reason:'smart が hamster の様子です。'}],
 allowedWords:[['somewhere / agree / warm up ~ / half / ~times a day / breathe / in order to ~ / mammal / information / ticket / fur / penguin / cheek / surprising / fireworks / smart / cherry blossom / awake / thick / quite / adorable / I have no idea. / all over ~','PROGRAM 7-1,2 combined canonical Sheet IDs 3294-3316'],['hamster','PROGRAM 7 textbook text: canonical Sheet ID 3327'],['pet shop / see / food / put / get / big / keep / ask / how much / friend / say / long time / think / read / more / together / want to / again','G1/G2 cumulative']],
 auditNote:'PROGRAM 7-1/7-2はGoogle Sheet正本上でID3294〜3316の共通プールのため、7-2でも同じ正本範囲からcheek / I have no idea. / information / fur / thick / awake / smart / agree / surprising等を使用した。hamsterは同PROGRAM教科書本文ID3327で直接照合。7-3初出語は使わず、fireworks / cherry blossom / all over等は文脈を壊すため未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 7-3']={
 id:'V10-SS-G2-P7-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 7-3',level:'HOP',title:'A Hamster in the Day and Night',
 sentences:['A hamster is lovely.','Though it is small, it can move quickly.','It is not always awake in the daytime.','It can be awake at nighttime.','In the daytime, it can sleep in a safe place.','At nighttime, it can look for food.','It can find a seed.','It can carry the seed.','It can also eat grass.','An enemy can look for the hamster.','The hamster can hide in the grass.','Though there is an enemy, it can stay safe.','Daytime and nighttime are very different for the hamster.','A lovely animal is not always easy to understand.'],
 fullTranslation:'「ハムスターは愛らしいです。小さいけれど、すばやく動くことができます。昼間にいつも目を覚ましているとは限りません。夜間には目を覚ましていることがあります。昼間は安全な場所で眠ることができます。夜間には食べ物を探すことができます。種を見つけることができます。その種を運ぶこともできます。草を食べることもできます。敵がハムスターを探すことがあります。ハムスターは草の中に隠れることができます。敵がいても、安全でいることができます。昼間と夜間ではハムスターの様子は大きく違います。愛らしい動物でも、いつも簡単に理解できるとは限りません。」',
 slashRows:[{en:'A hamster is / lovely.',jp:'ハムスターは〜です / 愛らしい'},{en:'Though it is small, / it can move / quickly.',jp:'それは小さいけれど / 動くことができます / すばやく'},{en:'It is not always / awake / in the daytime.',jp:'それはいつも〜とは限りません / 目がさめて / 昼間に'},{en:'It can be / awake / at nighttime.',jp:'それは〜でいることがあります / 目がさめて / 夜間に'},{en:'In the daytime, / it can sleep / in a safe place.',jp:'昼間に / それは眠ることができます / 安全な場所で'},{en:'At nighttime, / it can look for / food.',jp:'夜間に / それは探すことができます / 食べ物を'},{en:'It can find / a seed.',jp:'それは見つけることができます / 種を'},{en:'It can carry / the seed.',jp:'それは運ぶことができます / その種を'},{en:'It can also eat / grass.',jp:'それはまた食べることができます / 草を'},{en:'An enemy can look for / the hamster.',jp:'敵は探すことがあります / そのハムスターを'},{en:'The hamster can hide / in the grass.',jp:'そのハムスターは隠れることができます / 草の中に'},{en:'Though there is / an enemy, / it can stay / safe.',jp:'いるけれど / 敵が / それは〜でいることができます / 安全な'},{en:'Daytime and nighttime are / very different / for the hamster.',jp:'昼間と夜間は〜です / とても異なる / ハムスターにとって'},{en:'A lovely animal is not always / easy to understand.',jp:'愛らしい動物でもいつも〜とは限りません / 理解しやすい'}],
 questions:[{prompt:'1. ハムスターはどのような動物ですか。本文から英語で1語抜き出しなさい。',answer:'lovely',evidence:'A hamster is lovely.',evidenceJp:'ハムスターは愛らしいです。',reason:'lovely が hamster の様子を表しています。'},{prompt:'2. ハムスターは昼間いつも目を覚ましていますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'It is not always awake in the daytime.',evidenceJp:'昼間にいつも目を覚ましているとは限りません。',reason:'not always awake とあるので No です。'},{prompt:'3. 夜間には何を探すことができますか。本文から英語で1語抜き出しなさい。',answer:'food',evidence:'At nighttime, it can look for food.',evidenceJp:'夜間には食べ物を探すことができます。',reason:'look for の目的語が food です。'},{prompt:'4. 何を運ぶことができますか。本文から英語で答えなさい。',answer:'the seed',evidence:'It can carry the seed.',evidenceJp:'その種を運ぶこともできます。',reason:'carry の目的語が the seed です。'},{prompt:'5. 敵がいるとき、どこに隠れることができますか。本文から英語で答えなさい。',answer:'in the grass',evidence:'The hamster can hide in the grass.',evidenceJp:'ハムスターは草の中に隠れることができます。',reason:'in the grass が隠れる場所を表しています。'}],
 allowedWords:[['though / enemy / not always ~ / lovely / seed / daytime / nighttime / once / grass','PROGRAM 7-3: canonical Sheet IDs 3317-3325'],['hamster','PROGRAM 7 textbook text: canonical Sheet ID 3327'],['awake','PROGRAM 7-1,2 cumulative'],['small / move / quickly / sleep / safe / place / look for / food / find / carry / eat / hide / stay / very / different / animal / easy / understand','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 7-3をID3317〜3325まで直接照合。thoughとnot always ~を文法・表現軸にし、enemy / lovely / seed / daytime / nighttime / grassを1つの動物説明文に統合。onceは時制を不自然に増やすため未使用。hamsterは同PROGRAM教科書本文ID3327、awakeは7-1/2共通プールID3311からの累積として使用した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
