window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 9-1'] = {
 id:'V10-NH-G1-U9-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 9-1',level:'HOP',title:'During Vacation',
 sentences:['Do you like snowboarding?','Yes, I do.','Do you like ice hockey?','Yes, I do.','During vacation, I went to a mountain.','I met my friend there.','We went snowboarding.','Really?','Yes.','I went back home.','At home, I saw my family.','Great!'],
 fullTranslation:'「スノーボードは好きですか。」「はい、好きです。」「アイスホッケーは好きですか。」「はい、好きです。」「休みの間に山へ行きました。」「そこで友達に会いました。」「私たちはスノーボードをしに行きました。」「本当？」「うん。」「家へ戻りました。」「家で家族に会いました。」「いいね！」',
 slashRows:[{en:'Do you like / snowboarding?',jp:'あなたは好きですか / スノーボードが'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'Do you like / ice hockey?',jp:'あなたは好きですか / アイスホッケーが'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'During vacation, / I went / to a mountain.',jp:'休みの間に / 私は行きました / 山へ'},{en:'I met / my friend / there.',jp:'私は会いました / 友達に / そこで'},{en:'We went / snowboarding.',jp:'私たちは行きました / スノーボードをしに'},{en:'Really?',jp:'本当？'},{en:'Yes.',jp:'うん。'},{en:'I went back / home.',jp:'私は戻りました / 家へ'},{en:'At home, / I saw / my family.',jp:'家で / 私は会いました / 家族に'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. 話し手はスノーボードが好きですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Do you like snowboarding? / Yes, I do.',evidenceJp:'スノーボードは好きですか。／はい、好きです。',reason:'snowboarding が好きかという質問に Yes, I do. と答えています。'},{prompt:'2. 話し手は休みの間にどこへ行きましたか。本文から英語で答えなさい。',answer:'a mountain',evidence:'During vacation, I went to a mountain.',evidenceJp:'休みの間に山へ行きました。',reason:'went to の後ろの a mountain が行った場所です。'},{prompt:'3. 話し手はそこで誰に会いましたか。本文から英語で答えなさい。',answer:'my friend',evidence:'I met my friend there.',evidenceJp:'そこで友達に会いました。',reason:'met の目的語 my friend が会った相手です。'},{prompt:'4. 話し手と友達は何をしましたか。本文から英語で答えなさい。',answer:'went snowboarding',evidence:'We went snowboarding.',evidenceJp:'私たちはスノーボードをしに行きました。',reason:'went snowboarding が2人のしたことを表しています。'},{prompt:'5. 話し手は家で誰に会いましたか。本文から英語で答えなさい。',answer:'my family',evidence:'At home, I saw my family.',evidenceJp:'家で家族に会いました。',reason:'saw の目的語 my family が家で会った相手です。'}],
 allowedWords:[['snowboarding','Unit 9-1'],['ice hockey','Unit 9-1'],['during','Unit 9-1'],['vacation','Unit 9-1'],['mountain','Unit 9-1'],['met','Unit 9-1 explicit past of meet'],['went','Unit 9-1 explicit past of go'],['saw','Unit 9-1 explicit past of see'],['back','Unit 9-1'],['at home','Unit 9-1 phrase'],['friend','Unit 1-2 cumulative'],['there','Unit 5-2 cumulative'],['family','Unit 3-1 cumulative'],['really / great','cumulative'],['do / you / like / yes / I / to / a / my / we / home','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 9-1をid2475〜2488まで照合し、id2489からUnit 9-2へ切り替わることを確認。snowboarding / Christmas Day / ice hockey / stay / relax / back / during / vacation / mountain / met / went / saw / go back / at home が登録されている。met / went / saw は過去形そのものが正本登録されているため使用。stayed / relaxedのような未登録の規則過去形は生成しない。went back は正本登録済みwentとbackをそのまま組み合わせており、新しい活用形は作っていない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};