(function installV10PassageLocalNotesBatch15(){
  const defs=[
    {book:'ニューホライズン',grade:'3',section:'Unit 1-4',english:'forms',japanese:'形・形式',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 6-1',english:'four',japanese:'4（の）',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-3',english:'grew',japanese:'成長した',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 6-2',english:'hard',japanese:'一生懸命に',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 1-1',english:'hi',japanese:'やあ・こんにちは',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'1',section:'Unit 0',english:'hi',japanese:'やあ・こんにちは',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 5-3',english:'life',japanese:'生活・人生',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 6-1',english:'life',japanese:'生活・人生',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-1',english:'mark',japanese:'印をつける・印',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 8-3',english:'market',japanese:'市場',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'2',section:'PROGRAM 5-3',english:'U.N.',japanese:'国際連合',basis:'Canonical v7 chronology does not license this abbreviation at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 9-4',english:'outside',japanese:'外で・外へ',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-3',english:'pack',japanese:'詰める・荷造りする',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 5-4',english:'person\'s',japanese:'人の・その人の',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 2-3',english:'practical',japanese:'実用的な',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-1',english:'practical',japanese:'実用的な',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 5-1',english:'pull',japanese:'引く',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 0',english:'real',japanese:'本当の・本物の',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 2-2',english:'real',japanese:'本当の・本物の',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-3',english:'reopened',japanese:'再開した・再び開いた',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 1-2',english:'rest',japanese:'残り・その他',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'3',section:'PROGRAM 2-3',english:'rest',japanese:'残り・その他',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 3-1',english:'roads',japanese:'道路（複数）',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 3-2',english:'sells',japanese:'売る（三単現）',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-1',english:'several',japanese:'いくつかの',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 6-4',english:'shipped',japanese:'発送した・輸送した',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'2',section:'Unit 5-4',english:'similar',japanese:'似ている・類似した',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-2',english:'similar',japanese:'似ている・類似した',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 3-2',english:'sounds',japanese:'〜のように聞こえる（三単現）',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 4-4',english:'step',japanese:'段階・一歩',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-1',english:'systems',japanese:'仕組み・制度（複数）',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'1',section:'Unit 3-2',english:'talk',japanese:'話す',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 9-1',english:'trip',japanese:'旅行',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'サンシャイン',grade:'1',section:'PROGRAM 9-4',english:'trip',japanese:'旅行',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-3',english:'variety',japanese:'多様性・種類',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 1-2',english:'visitor\'s',japanese:'訪問者の',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'},
    {book:'ニューホライズン',grade:'3',section:'Unit 5-2',english:'wider',japanese:'より広い',basis:'Canonical v7 chronology does not license this exact surface token at this passage; retained only here with a Japanese gloss. No cumulative/global authorization.'}
  ];
  function pools(){return [window.V10_SUNSHINE_G1,window.V10_NEWHORIZON_G1,window.V10_PASSAGES_G2_SS,window.V10_PASSAGES_G2_NH,window.V10_PASSAGES_G3_SS,window.V10_PASSAGES_G3_NH].filter(Boolean);}
  function apply(){let added=0,seen=0;for(const d of defs){for(const pool of pools())for(const m of Object.values(pool||{})){if(!m||String(m.textbook)!==d.book||String(m.grade)!==d.grade||String(m.section)!==d.section)continue;seen++;m.notes=Array.isArray(m.notes)?m.notes:[];if(!m.notes.some(n=>n&&String(n.english||'').toLowerCase()===d.english.toLowerCase())){m.notes.push({english:d.english,japanese:d.japanese,basis:d.basis});added++;}}}window.V10_PASSAGE_LOCAL_NOTES_BATCH15={seen,added,definitions:defs.length};return {seen,added};}
  apply();window.V10_APPLY_PASSAGE_LOCAL_NOTES_BATCH15=apply;
})();
