// Reference/minimum-rule slash audit passages 091-100.
(function(){
 const PASS='PASS_REFERENCE_20260820';
 function setAudit(data,section,rows,n){const p=data&&data[section];if(!p)throw new Error('Missing reference passage '+n+': '+section);if(rows.length!==(p.sentences||[]).length)throw new Error('Row mismatch '+n);for(let i=0;i<rows.length;i++){const e=String(rows[i].en||'').replace(/\s*\/\s*/g,' ').replace(/\s+/g,' ').trim(),s=String(p.sentences[i]||'').replace(/\s+/g,' ').trim();if(e!==s)throw new Error('English mismatch '+n+'#'+(i+1)+': '+e+' <> '+s);const ec=String(rows[i].en||'').split(/\s*\/\s*/).filter(Boolean).length,jc=String(rows[i].jp||'').split(/\s*\/\s*/).filter(Boolean).length;if(ec!==jc)throw new Error('EN/JP chunks '+n+'#'+(i+1)+' '+ec+'/'+jc)}p.slashRows=rows;p.slashReadingVersion='reference-book-minimum-rules-20260820';p.slashReferenceAudit=PASS;p.slashReferencePassageNo=n}
 const s2=window.V10_PASSAGES_G2_SS||{}, n2=window.V10_PASSAGES_G2_NH||{};
 setAudit(s2,'PROGRAM 8-1',[
  {en:'Today, / we visit a stationery store.',jp:'今日 / 私たちは文房具店を訪れます'},{en:'I see a notebook made / from recycled paper.',jp:'私は作られたノートを見ます / 再利用された紙から'},{en:'A short message is written / on the first page.',jp:'短いメッセージが書かれています / 最初のページに'},{en:'The message is, / “A hope / for lasting peace.”',jp:'そのメッセージは〜です / 「願い / 長く続く平和への」'},{en:'The notebook is sold / at this store.',jp:'そのノートは売られています / この店で'},{en:'“I did not know recycled stationery was sold here.”',jp:'「再利用された文房具がここで売られているとは知りませんでした。」'},{en:'“Me neither.”',jp:'「私もです。」'},{en:'We read the message again.',jp:'私たちはそのメッセージをもう一度読みます。'},{en:'We think / about peace.',jp:'私たちは考えます / 平和について'},{en:'I think the notebook is a good idea.',jp:'私はこのノートはよい考えだと思います。'},{en:'I want lasting peace, / too.',jp:'私は長く続く平和を願っています / 〜もまた'}
 ],91);
 setAudit(s2,'PROGRAM 8-2',[
  {en:'Today, / we visit a peace monument.',jp:'今日 / 私たちは平和の記念碑を訪れます'},{en:'The monument is known / to many people.',jp:'その記念碑は知られています / 多くの人に'},{en:'It was built / for peace.',jp:'それは建てられました / 平和のために'},{en:'We learn / about a victim / of the atomic bomb.',jp:'私たちは学びます / 犠牲者について / 原子爆弾の'},{en:'The story is so sad / that we are quiet.',jp:'その話はとても悲しいです / そのため私たちは静かになります'},{en:'We read the story / at the monument.',jp:'私たちはその話を読みます / 記念碑で'},{en:'We think / about the victim.',jp:'私たちは考えます / その犠牲者について'},{en:'We look / at the monument again.',jp:'私たちは見ます / もう一度その記念碑を'},{en:'We renew our hope / for peace.',jp:'私たちは願いを新たにします / 平和への'},{en:'We want peace / for everyone.',jp:'私たちは平和を望みます / すべての人のために'},{en:'We want / to learn more / about the monument.',jp:'私たちは望んでいます / もっと学ぶことを / その記念碑について'}
 ],92);
 setAudit(s2,'PROGRAM 8-3',[
  {en:'Our class has a project / about old tin.',jp:'私たちのクラスにはプロジェクトがあります / 古いブリキについての'},{en:'A box is filled / with old tin.',jp:'箱は満たされています / 古いブリキで'},{en:'We want / to make the most / of the tin.',jp:'私たちは望んでいます / 最大限に活用することを / そのブリキを'},{en:'The tin is so thin / that we can fold it.',jp:'そのブリキはとても薄いです / そのため私たちは折れます'},{en:'We make a small badge / from the tin.',jp:'私たちは小さなバッジを作ります / そのブリキから'},{en:'Each badge has a peace message.',jp:'それぞれのバッジには平和のメッセージがあります。'},{en:'After the project, / I receive one badge.',jp:'プロジェクトのあと / 私はバッジを1つ受け取ります'},{en:'I wear the badge / at school.',jp:'私はそのバッジを身につけます / 学校で'},{en:'I think this is a good way / to use old tin.',jp:'私はこれはよい方法だと思います / 古いブリキを使うための'},{en:'We can make more / from the old tin.',jp:'私たちはさらに作れます / その古いブリキから'},{en:'We want / to make the most / of it again.',jp:'私たちは望んでいます / 最大限に活用することを / またそれを'}
 ],93);
 setAudit(n2,'Unit 0',[
  {en:'During spring vacation, / I had a new experience.',jp:'春休みに / 私は新しい経験をしました'},{en:'I ate ramen / with my friend / at my friend’s house.',jp:'私はラーメンを食べました / 友達と / 友達の家で'},{en:'We ate the same ramen.',jp:'私たちは同じラーメンを食べました。'},{en:'The noodle was very good.',jp:'そのめんはとてもおいしかったです。'},{en:'At first, / I did not know it was instant ramen.',jp:'最初 / 私はそれが即席ラーメンだとは知りませんでした'},{en:'Actually, / it was instant ramen.',jp:'実は / 即席ラーメンでした'},{en:'Now I know instant ramen can be very good.',jp:'今では即席ラーメンもとてもおいしくなり得ると分かります。'},{en:'My friend / and I want / to eat ramen again.',jp:'私の友達 / そして私は望んでいます / またラーメンを食べることを'},{en:'The experience was interesting.',jp:'その経験はおもしろかったです。'},{en:'Spring vacation was fun.',jp:'春休みは楽しかったです。'}
 ],94);
 setAudit(n2,'Unit 1-1',[
  {en:'I am going / to take a trip / to my friend’s city.',jp:'私は予定です / 旅行する / 友達の町へ'},{en:'My flight is / in the morning.',jp:'私の便は〜です / 午前に'},{en:'I am going / to arrive / before lunch.',jp:'私は予定です / 到着する / 昼食前に'},{en:'My friend is going / to meet me / at the airport.',jp:'友達は予定です / 私に会う / 空港で'},{en:'We are going / to leave the airport together.',jp:'私たちは予定です / いっしょに空港を出る'},{en:'My friend is going / to show me around the city.',jp:'友達は予定です / 私を街のあちこちへ案内する'},{en:'We want / to walk / around the city.',jp:'私たちは望んでいます / 歩くことを / 街のあちこちを'},{en:'We are going / to take a picture.',jp:'私たちは予定です / 写真を1枚撮る'},{en:'It is going / to be a golden holiday / for me.',jp:'それは予定です / すばらしい休日になる / 私にとって'},{en:'The trip is going / to start soon.',jp:'その旅行は予定です / まもなく始まる'}
 ],95);
 setAudit(n2,'Unit 1-2',[
  {en:'My flight will arrive / in the afternoon.',jp:'私の便は到着するでしょう / 午後に'},{en:'I will meet my friend first.',jp:'私はまず友達に会います。'},{en:'I will make a reservation / before dinner.',jp:'私は予約をします / 夕食前に'},{en:'We will go / to a restaurant / near the airport.',jp:'私たちは行くでしょう / レストランへ / 空港の近くの'},{en:'I will eat seafood there.',jp:'私はそこでシーフードを食べます。'},{en:'My friend will not eat seafood.',jp:'友達はシーフードを食べません。'},{en:'My friend will eat ramen.',jp:'友達はラーメンを食べます。'},{en:'We will eat / at the same restaurant.',jp:'私たちは食べます / 同じレストランで'},{en:'The restaurant is not far / from the airport.',jp:'そのレストランは遠くありません / 空港から'},{en:'I am excited / about dinner.',jp:'私はわくわくしています / 夕食について'},{en:'My friend is excited, / too.',jp:'友達もわくわくしています / 〜もまた'},{en:'We will have a good evening together.',jp:'私たちはいっしょによい夜を過ごすでしょう。'}
 ],96);
 setAudit(n2,'Unit 1-3',[
  {en:'Yesterday, / we went / to a shop.',jp:'昨日 / 私たちは行きました / 店へ'},{en:'I found a small card there.',jp:'私はそこで小さなカードを見つけました。'},{en:'The card had English / and Chinese.',jp:'そのカードには英語がありました / そして中国語も'},{en:'We can use the card / to communicate / with the shop staff.',jp:'私たちはそのカードを使えます / 意思を伝え合うために / 店員と'},{en:'For example, / I can use a short English question.',jp:'例えば / 私は短い英語の質問を使えます'},{en:'My friend can use a different word / in Chinese.',jp:'友達は別の単語を使えます / 中国語で'},{en:'We look / at the card / when we need help.',jp:'私たちは見ます / そのカードを / 助けが必要なとき'},{en:'We found a good way / to communicate.',jp:'私たちはよい方法を見つけました / 意思を伝え合うための'},{en:'Shopping was an interesting experience.',jp:'買い物はおもしろい経験でした。'}
 ],97);
 setAudit(n2,'Unit 1-4',[
  {en:'We are / in a special area / in Singapore.',jp:'私たちはいます / 特別な地域に / シンガポールの'},{en:'We see a large wall there.',jp:'私たちはそこで大きな壁を見ます。'},{en:'A painting is / on the wall.',jp:'絵があります / 壁に'},{en:'The painting is / about a culture / from India.',jp:'その絵は〜です / 文化についての / インドの'},{en:'We look / at the painting / and talk / about India.',jp:'私たちは見ます / その絵を / そして話します / インドについて'},{en:'I am surprised / by the painting.',jp:'私は驚いています / その絵に'},{en:'My friend is surprised, / too.',jp:'友達も驚いています / 〜もまた'},{en:'We also see a mosque / near the wall.',jp:'私たちはモスクも見ます / 壁の近くに'},{en:'The mosque is very beautiful.',jp:'そのモスクはとても美しいです。'},{en:'In this area, / we can learn / about a different culture.',jp:'この地域では / 私たちは学べます / 異なる文化について'},{en:'We take a picture / of the wall.',jp:'私たちは写真を撮ります / 壁の'},{en:'I want / to visit the area again.',jp:'私は望んでいます / またその地域を訪れることを'}
 ],98);
 setAudit(n2,'Unit 2-1',[
  {en:'Today, / we are / at a local restaurant.',jp:'今日 / 私たちはいます / 地元のレストランに'},{en:'I can order ramen here.',jp:'私はここでラーメンを注文できます。'},{en:'I order ramen / with soy sauce.',jp:'私はラーメンを注文します / しょうゆ味で'},{en:'Egg is my favorite topping.',jp:'卵は私のお気に入りのトッピングです。'},{en:'My friend / and I like corn / as a topping.',jp:'私の友達 / そして私はコーンが好きです / トッピングとして'},{en:'I order ramen / with egg / and corn.',jp:'私はラーメンを注文します / 卵入りで / そしてコーン入りで'},{en:'The flavor is strong.',jp:'風味は強いです。'},{en:'I especially like this flavor.',jp:'私は特にこの風味が好きです。'},{en:'We eat ramen together.',jp:'私たちはいっしょにラーメンを食べます。'},{en:'When we eat it, / we talk / about the flavor.',jp:'食べるとき / 私たちは話します / 風味について'},{en:'I want / to eat this local ramen again.',jp:'私は望んでいます / またこの地元のラーメンを食べることを'}
 ],99);
 setAudit(n2,'Unit 2-2',[
  {en:'At school, / I give a short speech / about local food.',jp:'学校で / 私は短いスピーチをします / 地元の食べ物について'},{en:'I often eat ramen / in my town.',jp:'私はよくラーメンを食べます / 私の町で'},{en:'If you visit my town, / you can try ramen.',jp:'もし私の町を訪れたら / ラーメンを食べてみることができます'},{en:'You can order it / with soy sauce.',jp:'あなたはそれを注文できます / しょうゆ味で'},{en:'If you like butter, / you can add butter.',jp:'バターが好きなら / バターを加えることができます'},{en:'You can add corn, / too.',jp:'あなたはコーンを加えることができます / 〜もまた'},{en:'Local food has a special flavor.',jp:'地元の食べ物には特別な風味があります。'},{en:'I like this ramen very much.',jp:'私はこのラーメンがとても好きです。'},{en:'I would love / to eat it / with my friends again.',jp:'私はぜひしたいです / それを食べることを / また友達と'},{en:'After the speech, / I hear, / “I would love / to try it, / too.”',jp:'スピーチのあと / 私は聞きます / 「私はぜひしたいです / それを試すことを / 〜もまた」'},{en:'I am happy / to hear that.',jp:'私はうれしいです / それを聞いて'}
 ],100);
 window.V10_REFERENCE_SLASH_AUDIT={version:'2026-08-20',passagesAudited:100,total:168,lastCompleted:100,minimumRuleImageConfirmed:true};
})();