window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 7-1'] = {
 id:'V10-NH-G1-U7-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 7-1',level:'HOP',title:'Are You Free Tomorrow?',
 sentences:['What’s up?','Are you busy tomorrow morning?','Yes, I am.','I want to practice tennis tomorrow morning.','Are you free after school?','Yes, I am.','Why don’t we talk after school?','Great!','Let’s talk after school.','I look forward to tomorrow.','Sounds great.','Thank you.'],
 fullTranslation:'「どうしたの？」「明日の朝は忙しい？」「うん。」「明日の朝はテニスを練習したいんだ。」「放課後はひま？」「うん、ひまだよ。」「放課後に話さない？」「いいね！」「放課後に話そう。」「明日が楽しみだよ。」「楽しそうだね。」「ありがとう。」',
 slashRows:[{en:'What’s up?',jp:'どうしたの？'},{en:'Are you / busy / tomorrow morning?',jp:'あなたは〜ですか / 忙しい / 明日の朝は'},{en:'Yes, / I am.',jp:'はい / そうです'},{en:'I want to practice / tennis / tomorrow morning.',jp:'私は練習したいです / テニスを / 明日の朝に'},{en:'Are you / free / after school?',jp:'あなたは〜ですか / ひまな / 放課後は'},{en:'Yes, / I am.',jp:'はい / そうです'},{en:'Why don’t we / talk / after school?',jp:'〜しませんか / 話すことを / 放課後に'},{en:'Great!',jp:'いいね！'},{en:'Let’s talk / after school.',jp:'話しましょう / 放課後に'},{en:'I look forward to / tomorrow.',jp:'私は楽しみにしています / 明日を'},{en:'Sounds / great.',jp:'〜そうですね / とても楽しそう'},{en:'Thank you.',jp:'ありがとう。'}],
 questions:[{prompt:'1. 話し手は明日の朝、忙しいですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Are you busy tomorrow morning? / Yes, I am.',evidenceJp:'明日の朝は忙しいですか。／はい、そうです。',reason:'busy かどうかの質問に Yes, I am. と答えています。'},{prompt:'2. 話し手は明日の朝、何をしたいですか。本文から英語で答えなさい。',answer:'practice tennis',evidence:'I want to practice tennis tomorrow morning.',evidenceJp:'明日の朝はテニスを練習したいです。',reason:'want to の後ろの practice tennis がしたいことです。'},{prompt:'3. 話し手は放課後、ひまですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Are you free after school? / Yes, I am.',evidenceJp:'放課後はひまですか。／はい、そうです。',reason:'free かどうかの質問に Yes, I am. と答えています。'},{prompt:'4. 2人は放課後に何をすることにしましたか。本文から英語で答えなさい。',answer:'talk',evidence:'Why don’t we talk after school? / Let’s talk after school.',evidenceJp:'放課後に話しませんか。／放課後に話しましょう。',reason:'誘いと返答の両方で talk が使われています。'},{prompt:'5. `I look forward to tomorrow.` はどのような意味ですか。日本語で答えなさい。',answer:'私は明日を楽しみにしています。',evidence:'I look forward to tomorrow.',evidenceJp:'私は明日を楽しみにしています。',reason:'Unit 7-1で明示登録された look forward to を tomorrow と組み合わせた表現です。'}],
 allowedWords:[['tomorrow','Unit 7-1'],['free','Unit 7-1'],['talk','Unit 7-1'],['busy','Unit 7-1'],['What’s up?','Unit 7-1 phrase'],['look forward to','Unit 7-1 phrase'],['morning','Unit 0 cumulative'],['want to','Unit 1-1 cumulative'],['practice','Unit 3-3 cumulative'],['tennis','Unit 0 cumulative'],['after school','Unit 3-2 cumulative'],['Why don’t we ...? / Let’s','Unit 6-1 cumulative phrases'],['Sounds ...','Unit 4-2 cumulative phrase'],['great','Unit 1-2 cumulative'],['Thank you.','Unit 2-3 cumulative'],['are / you / yes / I / am','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 7-1をid2356〜2364まで照合し、id2365からUnit 7-2へ切り替わることを確認。tomorrow / plan / mean / free / talk / busy / What’s up? / look forward to / sound like が登録されている。v9正本検索ではUnit 7-1のbe going toを確認できなかったため未来表現を推測で解禁せず、既習のbe動詞・want to・Why don’t we ...?・Let’sで明日の予定を相談する1場面にした。plan / mean / sound like は新出語消化のためだけには使用していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 7-2'] = {
 id:'V10-NH-G1-U7-2-001',textbook:'ニューホライズン',grade:'1',section:'Unit 7-2',level:'HOP',title:'At the Market',
 sentences:['Welcome to this market.','This is a popular place.','Look at those people.','They are in the market.','Do you like this place?','Yes, I do.','I want to buy this souvenir.','Do you want to buy it, too?','Yes, I do.','It is beautiful.','Great!','Let’s buy it.'],
 fullTranslation:'「この市場へようこそ。」「ここは人気のある場所です。」「あの人たちを見て。」「あの人たちは市場にいます。」「この場所は好きですか。」「はい、好きです。」「私はこのおみやげを買いたいです。」「あなたもそれを買いたいですか。」「はい、買いたいです。」「きれいですね。」「いいね！」「それを買いましょう。」',
 slashRows:[{en:'Welcome to / this market.',jp:'〜へようこそ / この市場'},{en:'This is / a popular place.',jp:'ここは〜です / 人気のある場所'},{en:'Look at / those people.',jp:'見てください / あの人たちを'},{en:'They are / in the market.',jp:'彼らはいます / その市場に'},{en:'Do you like / this place?',jp:'あなたは好きですか / この場所が'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'I want to buy / this souvenir.',jp:'私は買いたいです / このおみやげを'},{en:'Do you want to buy / it, too?',jp:'あなたも買いたいですか / それを'},{en:'Yes, / I do.',jp:'はい / そうです'},{en:'It is / beautiful.',jp:'それは〜です / 美しい'},{en:'Great!',jp:'いいね！'},{en:'Let’s buy / it.',jp:'買いましょう / それを'}],
 questions:[{prompt:'1. 2人はどこにいますか。本文から英語で答えなさい。',answer:'the market',evidence:'They are in the market.',evidenceJp:'彼らは市場にいます。',reason:'in the market がいる場所を示しています。'},{prompt:'2. `those people` は何を表していますか。日本語で答えなさい。',answer:'あの人たち',evidence:'Look at those people.',evidenceJp:'あの人たちを見て。',reason:'those が複数の people を指し示しています。'},{prompt:'3. 話し手は何を買いたいですか。本文から英語で答えなさい。',answer:'this souvenir',evidence:'I want to buy this souvenir.',evidenceJp:'私はこのおみやげを買いたいです。',reason:'buy の目的語 this souvenir が買いたい物です。'},{prompt:'4. 相手もそのおみやげを買いたいですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Do you want to buy it, too? / Yes, I do.',evidenceJp:'あなたもそれを買いたいですか。／はい、そうです。',reason:'買いたいかという質問に Yes, I do. と答えています。'},{prompt:'5. おみやげはどのようだと書かれていますか。本文から英語で1語抜き出しなさい。',answer:'beautiful',evidence:'It is beautiful.',evidenceJp:'それは美しいです。',reason:'beautiful がそのおみやげの様子を表しています。'}],
 allowedWords:[['place','Unit 7-2'],['market','Unit 7-2'],['souvenir','Unit 7-2'],['those','Unit 7-2'],['people','Unit 7-2 exact lexical plural'],['buy','Unit 7-2'],['Welcome to ...','Unit 7-2 phrase'],['popular','Unit 5-3 cumulative'],['look at','Unit 4-3 cumulative phrase'],['they','Unit 4-1 cumulative'],['want to','Unit 1-1 cumulative'],['beautiful','Unit 5-1 cumulative'],['Let’s','Unit 6-1 cumulative'],['too / great','cumulative'],['this / is / a / in / the / do / you / like / yes / I / it / are','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 7-2をid2365〜2372まで照合し、id2373からUnit 7-3へ切り替わることを確認。place / market / souvenir / appear / those / people / buy / Welcome to ... が登録されている。peopleは正本に複数を表す語として明示登録されているためそのまま使用。souvenirsなどの未確認複数形は作らない。appearは新出語消化のためだけには使わず、市場でおみやげを選ぶ1場面に限定した。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};