window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 3-1']={
id:'V10-SS-G3-P3-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 3-1',level:'HOP',title:'Mascots at a Sports Event',
sentences:['Today we visit a sports event.','A player was born in Australia.','His team has a kangaroo mascot.','Another team has an octopus mascot.','We also see a dove on a team flag.','I ask, “Whose mascot is the kangaroo?”','My friend can draw a picture of the kangaroo.','We draw a picture of the octopus too.','The mascots live in our event poster.','Players must follow the rules.','We talk about the teams and their mascots.','The event is lively and fun.'],
fullTranslation:'「今日、私たちはスポーツイベントを訪れます。ある選手はオーストラリアで生まれました。その選手のチームにはカンガルーのマスコットがあります。別のチームにはタコのマスコットがあります。チームの旗にはハトも見えます。私は『カンガルーはどのチームのマスコットですか』とたずねます。友達はカンガルーの絵を描くことができます。私たちはタコの絵も描きます。マスコットたちはイベントのポスターの中で生き生きとしています。選手たちは規則に従わなければなりません。私たちはチームとそのマスコットについて話します。そのイベントは活気があって楽しいです。」',
slashRows:[{en:'Today / we visit / a sports event.',jp:'今日 / 私たちは訪れます / スポーツイベントを'},{en:'A player was born / in Australia.',jp:'ある選手は生まれました / オーストラリアで'},{en:'His team has / a kangaroo mascot.',jp:'その選手のチームにはあります / カンガルーのマスコットが'},{en:'Another team has / an octopus mascot.',jp:'別のチームにはあります / タコのマスコットが'},{en:'We also see / a dove / on a team flag.',jp:'私たちはまた見ます / ハトを / チームの旗に'},{en:'I ask, / “Whose mascot is / the kangaroo?”',jp:'私はたずねます / 「だれのマスコットですか / カンガルーは」'},{en:'My friend can draw a picture of / the kangaroo.',jp:'友達は絵を描くことができます / カンガルーの'},{en:'We draw a picture of / the octopus / too.',jp:'私たちは絵を描きます / タコの / も'},{en:'The mascots live / in our event poster.',jp:'マスコットたちは生きています / イベントのポスターの中で'},{en:'Players must follow / the rules.',jp:'選手たちは従わなければなりません / 規則に'},{en:'We talk about / the teams and their mascots.',jp:'私たちは話します / チームとそのマスコットについて'},{en:'The event is / lively and fun.',jp:'そのイベントは〜です / 活気があって楽しい'}],
questions:[{prompt:'1. ある選手はどこで生まれましたか。本文から英語で答えなさい。',answer:'in Australia',evidence:'A player was born in Australia.',evidenceJp:'ある選手はオーストラリアで生まれました。',reason:'生まれた場所が in Australia です。'},{prompt:'2. その選手のチームには何のマスコットがありますか。本文から英語で答えなさい。',answer:'a kangaroo mascot',evidence:'His team has a kangaroo mascot.',evidenceJp:'その選手のチームにはカンガルーのマスコットがあります。',reason:'has の目的語が a kangaroo mascot です。'},{prompt:'3. 別のチームには何のマスコットがありますか。本文から英語で答えなさい。',answer:'an octopus mascot',evidence:'Another team has an octopus mascot.',evidenceJp:'別のチームにはタコのマスコットがあります。',reason:'has の目的語が an octopus mascot です。'},{prompt:'4. 友達は何の絵を描くことができますか。本文から英語で答えなさい。',answer:'the kangaroo',evidence:'My friend can draw a picture of the kangaroo.',evidenceJp:'友達はカンガルーの絵を描くことができます。',reason:'draw a picture of の後ろが the kangaroo です。'},{prompt:'5. 選手たちは何に従わなければなりませんか。本文から英語で答えなさい。',answer:'the rules',evidence:'Players must follow the rules.',evidenceJp:'選手たちは規則に従わなければなりません。',reason:'follow の目的語が the rules です。'}],
allowedWords:[["whose / be born / must / kangaroo / octopus / dove / draw a picture of ~ / live",'PROGRAM3 3-1: v7 canonical partition'],['today / visit / sports / event / player / Australia / team / another / mascot / also / see / flag / ask / friend / can / picture / poster / follow / rule / talk about / lively / fun','G1-G2 and PROGRAM1-2 cumulative']],
auditNote:'最新v7正本PROGRAM3 3-1を直接照合。whose / be born / must / kangaroo / octopus / dove / draw a picture of / liveを、スポーツイベントのマスコット紹介に統合。3-2のathlete / trainer / runner / sportswear / progress等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 3-2']={
id:'V10-SS-G3-P3-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 3-2',level:'HOP',title:'A Runner and a Trainer',
sentences:['An athlete is a runner in our town.','A trainer works with the athlete.','The runner wears typical sportswear.','The weather is hot today.','The runner takes care of himself.','He has a little sunburn on his arm.','The trainer talks about his progress.','The progress is incredible.','Practice can sometimes be boring.','The runner wants to go beyond his old record.','A huge crowd comes to watch.','Many people are attracted to the race.','The athlete will take part in the race tomorrow.'],
fullTranslation:'「ある運動選手は私たちの町のランナーです。トレーナーがその選手といっしょに取り組みます。そのランナーは典型的なスポーツウェアを着ています。今日は暑い天気です。ランナーは自分自身の健康管理をします。腕に少し日焼けがあります。トレーナーは彼の進歩について話します。その進歩は信じられないほどです。練習は時には退屈なこともあります。ランナーは以前の記録を越えたいと思っています。大勢の観客が見に来ます。多くの人がそのレースに引きつけられます。その選手は明日のレースに参加します。」',
slashRows:[{en:'An athlete is / a runner / in our town.',jp:'ある運動選手は〜です / ランナー / 私たちの町の'},{en:'A trainer works with / the athlete.',jp:'トレーナーは取り組みます / その選手と'},{en:'The runner wears / typical sportswear.',jp:'そのランナーは着ています / 典型的なスポーツウェアを'},{en:'The weather is / hot / today.',jp:'天気は〜です / 暑い / 今日'},{en:'The runner takes care of / himself.',jp:'そのランナーは自分を大切にします / 自分自身を'},{en:'He has / a little sunburn / on his arm.',jp:'彼にはあります / 少し日焼けが / 腕に'},{en:'The trainer talks about / his progress.',jp:'トレーナーは話します / 彼の進歩について'},{en:'The progress is / incredible.',jp:'その進歩は〜です / 信じられないほど'},{en:'Practice can sometimes be / boring.',jp:'練習は時には〜のことがあります / 退屈'},{en:'The runner wants to go / beyond his old record.',jp:'そのランナーは行きたいです / 以前の記録を越えて'},{en:'A huge crowd / comes to watch.',jp:'大勢の観客が / 見に来ます'},{en:'Many people are / attracted to / the race.',jp:'多くの人が〜です / 引きつけられて / そのレースに'},{en:'The athlete will take part in / the race / tomorrow.',jp:'その選手は参加します / レースに / 明日'}],
questions:[{prompt:'1. その運動選手は何ですか。本文から英語で答えなさい。',answer:'a runner',evidence:'An athlete is a runner in our town.',evidenceJp:'ある運動選手は私たちの町のランナーです。',reason:'be動詞の後ろが a runner です。'},{prompt:'2. ランナーはどのようなスポーツウェアを着ていますか。本文から英語で1語抜き出しなさい。',answer:'typical',evidence:'The runner wears typical sportswear.',evidenceJp:'そのランナーは典型的なスポーツウェアを着ています。',reason:'sportswear を説明する語が typical です。'},{prompt:'3. 腕には何がありますか。本文から英語で答えなさい。',answer:'a little sunburn',evidence:'He has a little sunburn on his arm.',evidenceJp:'腕に少し日焼けがあります。',reason:'has の目的語が a little sunburn です。'},{prompt:'4. 進歩はどうですか。本文から英語で1語抜き出しなさい。',answer:'incredible',evidence:'The progress is incredible.',evidenceJp:'その進歩は信じられないほどです。',reason:'progress の状態を表す語が incredible です。'},{prompt:'5. 明日、何に参加しますか。本文から英語で答えなさい。',answer:'the race',evidence:'The athlete will take part in the race tomorrow.',evidenceJp:'その選手は明日のレースに参加します。',reason:'take part in の後ろが the race です。'}],
allowedWords:[["attracted / take part in ~ / incredible / boring / progress / sportswear / beyond / huge / sunburn / runner / typical / take care of oneself / trainer / athlete / weather",'PROGRAM3 3-2: v7 canonical partition'],['town / work with / wear / hot / today / himself / arm / talk about / training / can / sometimes / old / record / crowd / watch / many / people / race / tomorrow','PROGRAM3 3-1 and G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM3 3-2を直接照合。athlete / trainer / runner / typical / sportswear / weather / take care of oneself / sunburn / progress / incredible / boring / beyond / huge / attracted / take part inを、ランナーの練習と大会参加に統合。3-3のdevelopment / breathing / diet / nutritional等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 3-3']={
id:'V10-SS-G3-P3-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 3-3',level:'HOP',title:'Training, Diet, and Breathing',
sentences:['Good training needs a good base.','A trainer can recommend a simple diet.','A nutritional meal is important for an athlete.','The athlete checks the meal carefully.','Good breathing is also important.','Bad breathing can cause a problem during training.','The development of strength takes time.','Failure can teach an athlete something.','The trainer explains the importance of rest.','The athlete follows the training plan carefully.','A good diet supports training.','Careful breathing helps the athlete during a race.'],
fullTranslation:'「よいトレーニングにはよい基礎が必要です。トレーナーは簡単な食事を勧めることができます。栄養のある食事は運動選手にとって大切です。その選手は食事を注意深く確認します。よい呼吸も大切です。悪い呼吸はトレーニング中に問題を引き起こすことがあります。力の発達には時間がかかります。失敗は運動選手に何かを教えることがあります。トレーナーは休息の重要性を説明します。その選手はトレーニング計画に注意深く従います。よい食事はトレーニングを支えます。注意深い呼吸はレース中の選手を助けます。」',
slashRows:[{en:'Good training needs / a good base.',jp:'よいトレーニングには必要です / よい基礎が'},{en:'A trainer / can recommend / a simple diet.',jp:'トレーナーは / 勧めることができます / 簡単な食事を'},{en:'A nutritional meal is / important / for an athlete.',jp:'栄養のある食事は〜です / 大切 / 運動選手にとって'},{en:'The athlete checks / the meal / carefully.',jp:'その選手は確認します / 食事を / 注意深く'},{en:'Good breathing is / also important.',jp:'よい呼吸も〜です / 大切'},{en:'Bad breathing / can cause / a problem / during training.',jp:'悪い呼吸は / 引き起こすことがあります / 問題を / トレーニング中に'},{en:'The development / of strength / takes time.',jp:'発達には / 力の / 時間がかかります'},{en:'Failure can teach / an athlete / something.',jp:'失敗は教えることがあります / 運動選手に / 何かを'},{en:'The trainer explains / the importance / of rest.',jp:'トレーナーは説明します / 重要性を / 休息の'},{en:'The athlete follows / the training plan / carefully.',jp:'その選手は従います / トレーニング計画に / 注意深く'},{en:'A good diet supports / training.',jp:'よい食事は支えます / トレーニングを'},{en:'Careful breathing helps / the athlete / during a race.',jp:'注意深い呼吸は助けます / 運動選手を / レース中に'}],
questions:[{prompt:'1. よいトレーニングには何が必要ですか。本文から英語で答えなさい。',answer:'a good base',evidence:'Good training needs a good base.',evidenceJp:'よいトレーニングにはよい基礎が必要です。',reason:'needs の目的語が a good base です。'},{prompt:'2. トレーナーは何を勧めることができますか。本文から英語で答えなさい。',answer:'a simple diet',evidence:'A trainer can recommend a simple diet.',evidenceJp:'トレーナーは簡単な食事を勧めることができます。',reason:'recommend の目的語が a simple diet です。'},{prompt:'3. 何がトレーニング中の問題を引き起こすことがありますか。本文から英語で答えなさい。',answer:'bad breathing',evidence:'Bad breathing can cause a problem during training.',evidenceJp:'悪い呼吸はトレーニング中に問題を引き起こすことがあります。',reason:'can cause の主語が Bad breathing です。'},{prompt:'4. 失敗は運動選手に何をすることがありますか。本文から英語で1語抜き出しなさい。',answer:'teach',evidence:'Failure can teach an athlete something.',evidenceJp:'失敗は運動選手に何かを教えることがあります。',reason:'can の後ろの動詞が teach です。'},{prompt:'5. トレーナーは何の重要性を説明しますか。本文から英語で答えなさい。',answer:'rest',evidence:'The trainer explains the importance of rest.',evidenceJp:'トレーナーは休息の重要性を説明します。',reason:'of の後ろが rest です。'}],
allowedWords:[["development / cause / breathing / recommend / base / training / failure / diet / carefully / importance / nutritional",'PROGRAM3 3-3: v7 canonical partition'],['good / need / trainer / can / simple / meal / important / athlete / check / also / bad / problem / during / strength / time / teach / something / explain / rest / follow / plan / support / help / race','PROGRAM3 3-1/3-2 and G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM3 3-3を直接照合。development / cause / breathing / recommend / base / training / failure / diet / carefully / importance / nutritionalを、運動選手のトレーニング・食事・呼吸の説明に統合。PROGRAM4以降の語彙は使用していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
