window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 7-1']={
id:'V10-SS-G3-P7-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 7-1',level:'HOP',title:'A Robot for a Patient',
sentences:['A patient has a disease that makes his muscle weak.','He can control a simple robot from his room.','The robot can move abroad through a network.','The patient can imagine a visit to a place far from home.','A small dictionary can help him understand new words.','The robot can belong to a hospital project.','Probably, the project can help many people.','The patient wants his dream to come true.','He can control the robot with a computer.','The simple system is easy to use.','We imagine how the robot can change his life.','The patient says the project gives him hope.'],
fullTranslation:'「ある患者には筋肉を弱くする病気があります。彼は自分の部屋から簡単なロボットを操作できます。そのロボットはネットワークを通して外国へ動くことができます。患者は家から遠い場所を訪れることを想像できます。小さな辞書は新しいことばを理解する助けになります。そのロボットは病院のプロジェクトに所属することができます。おそらく、そのプロジェクトは多くの人を助けることができます。患者は自分の夢が実現することを願っています。彼はコンピューターでロボットを操作できます。その簡単な仕組みは使いやすいです。私たちはそのロボットが彼の生活をどう変えられるか想像します。患者はそのプロジェクトが希望を与えてくれると言います。」',
slashRows:[{en:'A patient has / a disease / that makes his muscle weak.',jp:'ある患者にはあります / 病気が / 彼の筋肉を弱くする'},{en:'He can control / a simple robot / from his room.',jp:'彼は操作できます / 簡単なロボットを / 自分の部屋から'},{en:'The robot can move / abroad / through a network.',jp:'そのロボットは動くことができます / 外国へ / ネットワークを通して'},{en:'The patient can imagine / a visit / to a place far from home.',jp:'その患者は想像できます / 訪問を / 家から遠い場所への'},{en:'A small dictionary / can help / him understand / new words.',jp:'小さな辞書は / 助けることができます / 彼が理解するのを / 新しいことばを'},{en:'The robot can belong to / a hospital project.',jp:'そのロボットは所属できます / 病院のプロジェクトに'},{en:'Probably, / the project / can help / many people.',jp:'おそらく / そのプロジェクトは / 助けることができます / 多くの人を'},{en:'The patient wants / his dream / to come true.',jp:'その患者は願っています / 自分の夢が / 実現することを'},{en:'He can control / the robot / with a computer.',jp:'彼は操作できます / そのロボットを / コンピューターで'},{en:'The simple system is / easy to use.',jp:'その簡単な仕組みは〜です / 使いやすい'},{en:'We imagine / how the robot can change / his life.',jp:'私たちは想像します / そのロボットがどう変えられるか / 彼の生活を'},{en:'The patient says / the project gives him hope.',jp:'その患者は言います / そのプロジェクトが彼に希望を与えると'}],
questions:[{prompt:'1. 患者には何がありますか。本文から英語で答えなさい。',answer:'a disease',evidence:'A patient has a disease that makes his muscle weak.',evidenceJp:'ある患者には筋肉を弱くする病気があります。',reason:'has の目的語が a disease です。'},{prompt:'2. 患者は何を操作できますか。本文から英語で答えなさい。',answer:'a simple robot',evidence:'He can control a simple robot from his room.',evidenceJp:'彼は自分の部屋から簡単なロボットを操作できます。',reason:'control の目的語が a simple robot です。'},{prompt:'3. ロボットはどこへ動くことができますか。本文から英語で1語抜き出しなさい。',answer:'abroad',evidence:'The robot can move abroad through a network.',evidenceJp:'そのロボットはネットワークを通して外国へ動くことができます。',reason:'abroad が移動先を表します。'},{prompt:'4. 何が新しいことばを理解する助けになりますか。本文から英語で答えなさい。',answer:'a small dictionary',evidence:'A small dictionary can help him understand new words.',evidenceJp:'小さな辞書は新しいことばを理解する助けになります。',reason:'can help の主語が A small dictionary です。'},{prompt:'5. 患者は何が実現することを願っていますか。本文から英語で答えなさい。',answer:'his dream',evidence:'The patient wants his dream to come true.',evidenceJp:'患者は自分の夢が実現することを願っています。',reason:'come true の主語にあたる内容が his dream です。'}],
allowedWords:[["dictionary / simple / weak / probably / control / abroad / patient / come true / muscle / belong to ~ / disease / imagine",'PROGRAM7 7-1/2 shared pool: first-half split used for 7-1'],['robot / room / network / visit / place / home / small / help / understand / new / word / hospital / project / many / people / want / dream / computer / system / easy / use / change / life / hope','earlier cumulative']],
auditNote:'最新v7正本ではPROGRAM7 7-1,2が共有語彙プール（ID3878-3901）。順序を保持し、前半12語 dictionary〜imagine を7-1、後半12語 AI〜far away を7-2に分割して監査する。7-1では後半語彙と7-3語彙を先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 7-2']={
id:'V10-SS-G3-P7-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 7-2',level:'HOP',title:'AI and Human Emotion',
sentences:['These days, AI can control many kinds of machines.','A vacuum cleaner can work by itself.','A robot can wear a mask with a simple face.','Its quality can improve with AI.','Can a robot understand human emotion?','We use our imagination to think about that question.','A musical robot can play with a band.','A patient far away can watch the music.','If the patient has a fever, the robot can still send music.','The robot would not replace a human friend.','A mask cannot show every emotion.','AI can help people, but human care is important.','We imagine a future with useful robots.'],
fullTranslation:'「近ごろ、AIは多くの種類の機械を制御できます。電気掃除機はそれ自体で動くことができます。ロボットは簡単な顔の仮面をつけることができます。その質はAIによって向上できます。ロボットは人間の感情を理解できるでしょうか。私たちはその問いについて考えるために想像力を使います。ミュージカルのロボットはバンドといっしょに演奏できます。はるか遠くにいる患者もその音楽を見ることができます。患者に熱があっても、ロボットは音楽を送ることができます。ロボットは人間の友達の代わりにはならないでしょう。仮面ですべての感情を表すことはできません。AIは人々を助けることができますが、人の世話も大切です。私たちは役立つロボットのいる未来を想像します。」',
slashRows:[{en:'These days, / AI can control / many kinds of machines.',jp:'近ごろ / AIは制御できます / 多くの種類の機械を'},{en:'A vacuum cleaner / can work / by itself.',jp:'電気掃除機は / 動くことができます / それ自体で'},{en:'A robot / can wear / a mask / with a simple face.',jp:'ロボットは / つけることができます / 仮面を / 簡単な顔の'},{en:'Its quality / can improve / with AI.',jp:'その質は / 向上できます / AIによって'},{en:'Can a robot understand / human emotion?',jp:'ロボットは理解できますか / 人間の感情を'},{en:'We use / our imagination / to think about / that question.',jp:'私たちは使います / 想像力を / 考えるために / その問いについて'},{en:'A musical robot / can play / with a band.',jp:'ミュージカルのロボットは / 演奏できます / バンドと'},{en:'A patient far away / can watch / the music.',jp:'はるか遠くの患者は / 見ることができます / その音楽を'},{en:'If the patient has a fever, / the robot / can still send / music.',jp:'患者に熱があっても / そのロボットは / 送ることができます / 音楽を'},{en:'The robot would not / replace / a human friend.',jp:'そのロボットは〜しないでしょう / 置き換える / 人間の友達を'},{en:'A mask cannot show / every emotion.',jp:'仮面は表すことができません / すべての感情を'},{en:'AI can help / people, / but human care is / important.',jp:'AIは助けることができます / 人々を / しかし人の世話は〜です / 大切な'},{en:'We imagine / a future / with useful robots.',jp:'私たちは想像します / 未来を / 役立つロボットのいる'}],
questions:[{prompt:'1. 近ごろ、何が多くの種類の機械を制御できますか。本文から英語で答えなさい。',answer:'AI',evidence:'These days, AI can control many kinds of machines.',evidenceJp:'近ごろ、AIは多くの種類の機械を制御できます。',reason:'can control の主語が AI です。'},{prompt:'2. 何がそれ自体で動くことができますか。本文から英語で答えなさい。',answer:'a vacuum cleaner',evidence:'A vacuum cleaner can work by itself.',evidenceJp:'電気掃除機はそれ自体で動くことができます。',reason:'can work の主語が A vacuum cleaner です。'},{prompt:'3. ロボットは何を理解できるかが問われていますか。本文から英語で答えなさい。',answer:'human emotion',evidence:'Can a robot understand human emotion?',evidenceJp:'ロボットは人間の感情を理解できるでしょうか。',reason:'understand の目的語が human emotion です。'},{prompt:'4. ミュージカルのロボットは何と演奏できますか。本文から英語で答えなさい。',answer:'a band',evidence:'A musical robot can play with a band.',evidenceJp:'ミュージカルのロボットはバンドといっしょに演奏できます。',reason:'with の後ろが a band です。'},{prompt:'5. 患者に何があってもロボットは音楽を送れますか。本文から英語で答えなさい。',answer:'a fever',evidence:'If the patient has a fever, the robot can still send music.',evidenceJp:'患者に熱があっても、ロボットは音楽を送ることができます。',reason:'has の目的語が a fever です。'}],
allowedWords:[["AI / mask / vacuum cleaner / imagination / quality / emotion / wouldn't / musical / have a fever / band / these days / far away",'PROGRAM7 7-1/2 shared pool: second-half split used for 7-2'],['dictionary / simple / weak / probably / control / abroad / patient / come true / muscle / belong to / disease / imagine','PROGRAM7 7-1 cumulative'],['many / kind / machine / robot / work / itself / wear / face / improve / human / understand / use / think about / question / play / watch / music / if / still / send / replace / friend / show / every / help / people / care / important / future / useful','earlier cumulative / textbook-body itself allowed']],
auditNote:'共有語彙プール後半12語 AI〜far away を7-2として使用。7-1の語彙は累積使用可。7-3初出 wish / lift / alone / powerful / society等は先取りしていない。textbook-bodyのitselfは本文テーマに自然なため使用。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 7-3']={
id:'V10-SS-G3-P7-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 7-3',level:'HOP',title:'Robots and Loneliness',
sentences:['An inventor can imagine a powerful robot for society.','The robot can lift a heavy box.','It can connect with a person who lives alone.','A person may wish for someone to talk with.','The robot can help shrink loneliness.','But it should not make a person no longer meet people.','People can get along with a robot and with each other.','The inventor can take part in a meeting about robots.','A document can explain the purpose of the robot.','A password can protect the robot system.','The robot can shake hands with a person.','Certainly, a heater or a robot can make life easier.','Rather, the important point is how people use technology.','A useful robot can connect people in society.'],
fullTranslation:'「発明家は社会のための強力なロボットを想像できます。そのロボットは重い箱を持ち上げることができます。一人で暮らす人とつながることができます。人は話し相手がほしいと願うことがあります。ロボットは孤独を減らす助けになることができます。しかし、人がもはや人々と会わなくなるようにするべきではありません。人々はロボットとも、おたがいとも仲よくやっていくことができます。発明家はロボットについての会議に参加できます。文書はロボットの目的を説明できます。パスワードはロボットの仕組みを守ることができます。ロボットは人と握手できます。確かに、ヒーターやロボットは生活を楽にできます。むしろ、大切なのは人々が技術をどう使うかです。役立つロボットは社会の中で人々をつなぐことができます。」',
slashRows:[{en:'An inventor / can imagine / a powerful robot / for society.',jp:'発明家は / 想像できます / 強力なロボットを / 社会のための'},{en:'The robot / can lift / a heavy box.',jp:'そのロボットは / 持ち上げることができます / 重い箱を'},{en:'It can connect with / a person / who lives alone.',jp:'それはつながることができます / 人と / 一人で暮らす'},{en:'A person / may wish for / someone to talk with.',jp:'人は / 願うことがあります / 話し相手を'},{en:'The robot / can help shrink / loneliness.',jp:'そのロボットは / 減らす助けができます / 孤独を'},{en:'But / it should not make / a person / no longer meet people.',jp:'しかし / それは〜させるべきではありません / 人を / もはや人々と会わないように'},{en:'People / can get along with / a robot and with each other.',jp:'人々は / 仲よくやっていくことができます / ロボットともおたがいとも'},{en:'The inventor / can take part in / a meeting / about robots.',jp:'発明家は / 参加できます / 会議に / ロボットについての'},{en:'A document / can explain / the purpose / of the robot.',jp:'文書は / 説明できます / 目的を / ロボットの'},{en:'A password / can protect / the robot system.',jp:'パスワードは / 守ることができます / ロボットの仕組みを'},{en:'The robot / can shake hands with / a person.',jp:'ロボットは / 握手できます / 人と'},{en:'Certainly, / a heater or a robot / can make / life easier.',jp:'確かに / ヒーターやロボットは / 〜できます / 生活をより楽に'},{en:'Rather, / the important point is / how people use / technology.',jp:'むしろ / 大切な点は〜です / 人々がどう使うか / 技術を'},{en:'A useful robot / can connect / people / in society.',jp:'役立つロボットは / つなぐことができます / 人々を / 社会の中で'}],
questions:[{prompt:'1. 発明家はどのようなロボットを想像できますか。本文から英語で答えなさい。',answer:'a powerful robot',evidence:'An inventor can imagine a powerful robot for society.',evidenceJp:'発明家は社会のための強力なロボットを想像できます。',reason:'imagine の目的語が a powerful robot です。'},{prompt:'2. ロボットは何を持ち上げることができますか。本文から英語で答えなさい。',answer:'a heavy box',evidence:'The robot can lift a heavy box.',evidenceJp:'そのロボットは重い箱を持ち上げることができます。',reason:'lift の目的語が a heavy box です。'},{prompt:'3. ロボットは何を減らす助けができますか。本文から英語で1語抜き出しなさい。',answer:'loneliness',evidence:'The robot can help shrink loneliness.',evidenceJp:'ロボットは孤独を減らす助けになることができます。',reason:'shrink の目的語が loneliness です。'},{prompt:'4. 発明家は何に参加できますか。本文から英語で答えなさい。',answer:'a meeting about robots',evidence:'The inventor can take part in a meeting about robots.',evidenceJp:'発明家はロボットについての会議に参加できます。',reason:'take part in の後ろが a meeting about robots です。'},{prompt:'5. 何がロボットの仕組みを守ることができますか。本文から英語で答えなさい。',answer:'a password',evidence:'A password can protect the robot system.',evidenceJp:'パスワードはロボットの仕組みを守ることができます。',reason:'can protect の主語が A password です。'}],
allowedWords:[["wish / lift / alone / password / powerful / document / certainly / society / take part in ~ / loneliness / get along with ~ / inventor / no longer ~ / heater / shrink / rather / connect / shake hands with ~",'PROGRAM7 7-3 canonical partition'],['including / Anywhere Door / trash can / itself / ALS / noh mask','PROGRAM7 textbook-body pool retained; not forced unless natural'],['imagine / robot / heavy / box / person / someone / talk with / help / but / should not / make / meet / people / each other / meeting / explain / purpose / protect / system / life / easy / important / point / how / use / technology / useful','PROGRAM7 7-1/7-2 and earlier cumulative']],
auditNote:'最新v7正本PROGRAM7 7-3（ID3902-3919）を直接照合。wish / lift / alone / password / powerful / document / certainly / society / take part in / loneliness / get along with / inventor / no longer / heater / shrink / rather / connect / shake hands withを使用。教科書本文固有語 Anywhere Door / ALS / noh mask等は無理に消化していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
