window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 1-1']={
id:'V10-SS-G1-P1-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-1',level:'HOP',title:'A Student at Junior High School',
sentences:['Hi.','I’m a student.','I’m at a junior high school.','I’m not shy.','I’m friendly.','My teacher is kind.','I like my teacher.','I like music.','I play the trumpet.','I practice every Wednesday.','I like my school.','School is really great.','Goodbye.'],
fullTranslation:'「こんにちは。私は生徒です。中学校に通っています。私は恥ずかしがりではありません。人なつっこいです。私の先生は親切です。私は先生が好きです。音楽が好きです。トランペットを演奏します。毎週水曜日に練習します。学校が好きです。学校は本当にすばらしいです。さようなら。」',
slashRows:[{en:'Hi.',jp:'こんにちは。'},{en:'I’m / a student.',jp:'私は〜です / 生徒'},{en:'I’m / at a junior high school.',jp:'私はいます / 中学校に'},{en:'I’m not / shy.',jp:'私は〜ではありません / 恥ずかしがり'},{en:'I’m / friendly.',jp:'私は〜です / 人なつっこい'},{en:'My teacher is / kind.',jp:'私の先生は〜です / 親切な'},{en:'I like / my teacher.',jp:'私は好きです / 私の先生が'},{en:'I like / music.',jp:'私は好きです / 音楽が'},{en:'I play / the trumpet.',jp:'私は演奏します / トランペットを'},{en:'I practice / every Wednesday.',jp:'私は練習します / 毎週水曜日に'},{en:'I like / my school.',jp:'私は好きです / 私の学校が'},{en:'School is / really great.',jp:'学校は〜です / 本当にすばらしい'},{en:'Goodbye.',jp:'さようなら。'}],
questions:[{prompt:'1. 話し手は何ですか。本文から英語で答えなさい。',answer:'a student',evidence:'I’m a student.',evidenceJp:'私は生徒です。',reason:'be動詞の後ろの a student が話し手の立場を表しています。'},{prompt:'2. 話し手はどこに通っていますか。本文から英語で答えなさい。',answer:'a junior high school',evidence:'I’m at a junior high school.',evidenceJp:'私は中学校にいます。',reason:'at の後ろの a junior high school が場所を示しています。'},{prompt:'3. 話し手は恥ずかしがりですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I’m not shy.',evidenceJp:'私は恥ずかしがりではありません。',reason:'not shy と否定しているので No です。'},{prompt:'4. 先生はどのような人ですか。本文から英語で1語抜き出しなさい。',answer:'kind',evidence:'My teacher is kind.',evidenceJp:'私の先生は親切です。',reason:'kind が先生の性格を表しています。'},{prompt:'5. 話し手は何を演奏しますか。本文から英語で答えなさい。',answer:'the trumpet',evidence:'I play the trumpet.',evidenceJp:'私はトランペットを演奏します。',reason:'play の目的語 the trumpet が演奏する楽器です。'}],
allowedWords:[['shy / student / teacher / kind / friendly / not / at / hi / goodbye / I’m / junior high school','PROGRAM 1-1: id129-147'],['music / trumpet / practice / every / Wednesday / school','Get Ready 4 cumulative'],['really / great','Get Ready 2 cumulative'],['I / my / is / like / play / the / a','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-1をid129〜147まで照合し、id148からPROGRAM 1-2へ切り替わることを確認。新出のbe動詞am/I’m、not、student、teacher、shy、kind、friendly、junior high schoolを中心に自己紹介1場面として構成。未確認の三単現・過去形・進行形は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 1-2']={
id:'V10-SS-G1-P1-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-2',level:'HOP',title:'Where Are You From?',
sentences:['Hello.','I’m from Australia.','Are you from Japan?','Yes, I am.','Are you from the U.S.?','No, I’m not.','I’m from Brazil.','Pardon me?','I’m from Brazil.','Oh, I see.','Are you a student?','Yes, I am.','Great.'],
fullTranslation:'「こんにちは。私はオーストラリア出身です。あなたは日本出身ですか。」「はい、そうです。」「アメリカ合衆国出身ですか。」「いいえ、違います。私はブラジル出身です。」「すみません、何とおっしゃいましたか。」「ブラジル出身です。」「ああ、なるほど。」「あなたは生徒ですか。」「はい、そうです。」「すばらしいですね。」',
slashRows:[{en:'Hello.',jp:'こんにちは。'},{en:'I’m from / Australia.',jp:'私は〜出身です / オーストラリア'},{en:'Are you from / Japan?',jp:'あなたは〜出身ですか / 日本'},{en:'Yes, / I am.',jp:'はい / そうです'},{en:'Are you from / the U.S.?',jp:'あなたは〜出身ですか / アメリカ合衆国'},{en:'No, / I’m not.',jp:'いいえ / 違います'},{en:'I’m from / Brazil.',jp:'私は〜出身です / ブラジル'},{en:'Pardon me?',jp:'すみません。何とおっしゃいましたか。'},{en:'I’m from / Brazil.',jp:'私は〜出身です / ブラジル'},{en:'Oh, / I see.',jp:'ああ / なるほど'},{en:'Are you / a student?',jp:'あなたは〜ですか / 生徒'},{en:'Yes, / I am.',jp:'はい / そうです'},{en:'Great.',jp:'すばらしいですね。'}],
questions:[{prompt:'1. 最初の話し手はどこの出身ですか。本文から英語で答えなさい。',answer:'Australia',evidence:'I’m from Australia.',evidenceJp:'私はオーストラリア出身です。',reason:'from の後ろの Australia が出身地を示しています。'},{prompt:'2. 相手は日本出身ですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Are you from Japan? / Yes, I am.',evidenceJp:'あなたは日本出身ですか。／はい、そうです。',reason:'Japan 出身かという質問に Yes, I am. と答えています。'},{prompt:'3. 最初の話し手はアメリカ合衆国出身ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Are you from the U.S.? / No, I’m not.',evidenceJp:'アメリカ合衆国出身ですか。／いいえ、違います。',reason:'the U.S. 出身かという質問を No, I’m not. と否定しています。'},{prompt:'4. 最初の話し手は実際にはどこの出身ですか。本文から英語で答えなさい。',answer:'Brazil',evidence:'I’m from Brazil.',evidenceJp:'私はブラジル出身です。',reason:'聞き返した後も Brazil と繰り返して出身地を示しています。'},{prompt:'5. `Pardon me?` はこの場面で何のために使っていますか。日本語で答えなさい。',answer:'相手の言ったことを聞き返すため。',evidence:'Pardon me?',evidenceJp:'すみません。何とおっしゃいましたか。',reason:'PROGRAM 1-2で登録された聞き返しの定型表現です。'}],
allowedWords:[['the U.S. / Australia / Brazil / Japan / no / yes / hello / be from ～ / I’m sorry. / Pardon me?','PROGRAM 1-2: id148-158'],['I’m / not / student','PROGRAM 1-1 cumulative'],['I see. / great','Get Ready 2 cumulative'],['are / you / from / I / am / a / the / oh','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-2をid148〜158まで照合し、id159からPROGRAM 1-3へ切り替わることを確認。国名とbe from ～、Pardon me?を中心に出身地を確認する1会話として構成。未習語を補うための国名追加や派生形は行っていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 1-3']={
id:'V10-SS-G1-P1-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 1-3',level:'HOP',title:'A New Student in This City',
sentences:['This city is nice.','I’m a new student.','This is my new class.','Nice to meet you.','I’m quiet.','I’m cheerful, too.','I like math.','I’m good at math.','I like science, too.','I’m good at science, too.','I like Japanese.','I’m a fan of movies.','My teacher is kind.','I want to be friendly.','School is really great.'],
fullTranslation:'「この町はすてきです。私は新しい生徒です。ここが私の新しいクラスです。はじめまして。私はおとなしいです。明るいところもあります。数学が好きです。数学が得意です。理科も好きです。理科も得意です。国語も好きです。映画のファンです。私の先生は親切です。人なつっこくなりたいです。学校は本当にすばらしいです。」',
slashRows:[{en:'This city is / nice.',jp:'この町は〜です / すてきな'},{en:'I’m / a new student.',jp:'私は〜です / 新しい生徒'},{en:'This is / my new class.',jp:'これは〜です / 私の新しいクラス'},{en:'Nice to meet you.',jp:'はじめまして。'},{en:'I’m / quiet.',jp:'私は〜です / おとなしい'},{en:'I’m / cheerful, too.',jp:'私は〜です / 明るくもあります'},{en:'I like / math.',jp:'私は好きです / 数学が'},{en:'I’m good at / math.',jp:'私は得意です / 数学が'},{en:'I like / science, too.',jp:'私は好きです / 理科も'},{en:'I’m good at / science, too.',jp:'私は得意です / 理科も'},{en:'I like / Japanese.',jp:'私は好きです / 国語が'},{en:'I’m / a fan of movies.',jp:'私は〜です / 映画のファン'},{en:'My teacher is / kind.',jp:'私の先生は〜です / 親切な'},{en:'I want to be / friendly.',jp:'私は〜になりたいです / 人なつっこい'},{en:'School is / really great.',jp:'学校は〜です / 本当にすばらしい'}],
questions:[{prompt:'1. 話し手はどんな立場の人ですか。本文から英語で答えなさい。',answer:'a new student',evidence:'I’m a new student.',evidenceJp:'私は新しい生徒です。',reason:'a new student が話し手の立場を表しています。'},{prompt:'2. 話し手はどんな性格ですか。本文から英語で2語答えなさい。',answer:'quiet, cheerful',evidence:'I’m quiet. / I’m cheerful, too.',evidenceJp:'私はおとなしいです。／明るいところもあります。',reason:'quiet と cheerful の2つで性格を説明しています。'},{prompt:'3. 話し手が得意な教科を2つ、本文から英語で答えなさい。',answer:'math, science',evidence:'I’m good at math. / I’m good at science, too.',evidenceJp:'数学が得意です。／理科も得意です。',reason:'be good at ～ の後ろに math と science が置かれています。'},{prompt:'4. 話し手は何のファンですか。本文から英語で答えなさい。',answer:'movies',evidence:'I’m a fan of movies.',evidenceJp:'私は映画のファンです。',reason:'a fan of の後ろの movies が好きな対象です。'},{prompt:'5. 話し手はどのようになりたいですか。本文から英語で答えなさい。',answer:'friendly',evidence:'I want to be friendly.',evidenceJp:'私は人なつっこくなりたいです。',reason:'want to be の後ろの friendly がなりたい状態です。'}],
allowedWords:[['city / just / nice / this / Nice to meet you. / problem / class / go / new / want to ～ / No problem. / social studies / quiet / careful / polite / cheerful / honest / of / fan / movie / math / P.E. / Japanese / science / be good at ～','PROGRAM 1-3: id159-184'],['student / I’m / teacher / kind / friendly','PROGRAM 1-1 cumulative'],['school','Get Ready 4 cumulative'],['really / great / too','Get Ready 2 cumulative'],['I / my / is / like / a / be / want / to','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 1-3をid159〜184まで照合し、id185からPROGRAM 2-1へ切り替わることを確認。city / new / class / Nice to meet you. / quiet / cheerful / fan / movie / math / Japanese / science / be good at ～を中心に、新しいクラスでの自己紹介1場面に限定。新出語を全部消化するための不自然な羅列は避け、未確認の比較級・三単現・過去形等は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};