window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['Unit 10-1']={
 id:'V10-NH-G1-U10-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 10-1',level:'HOP',title:'A Chorus Contest Memory',
 sentences:['At first, I was bored.','It was a chorus contest.','Were you in the chorus?','Yes, I was.','Did you like the contest?','Yes, I did.','We made a mistake.','Anyway, we won the contest.','Really?','Yes.','I remember that day.','It is a good memory.','I realized my mistake.','Anyone can make a mistake.'],
 fullTranslation:'「最初は退屈していました。」「それは合唱コンクールでした。」「あなたは合唱に参加していたの？」「はい。」「そのコンクールは好きでしたか。」「はい。」「私たちはまちがいをしました。」「それでも、私たちはコンクールで勝ちました。」「本当？」「うん。」「私はその日を覚えています。」「よい思い出です。」「私は自分のまちがいに気づきました。」「だれでもまちがいをすることがあります。」',
 slashRows:[{en:'At first, / I was bored.',jp:'最初は / 私は退屈していました'},{en:'It was / a chorus contest.',jp:'それは〜でした / 合唱コンクール'},{en:'Were you / in the chorus?',jp:'あなたは〜でしたか / 合唱に参加して'},{en:'Yes, / I was.',jp:'はい / そうでした'},{en:'Did you like / the contest?',jp:'あなたは好きでしたか / そのコンクールが'},{en:'Yes, / I did.',jp:'はい / 好きでした'},{en:'We made / a mistake.',jp:'私たちはしました / まちがいを'},{en:'Anyway, / we won / the contest.',jp:'それでも / 私たちは勝ちました / そのコンクールで'},{en:'Really?',jp:'本当？'},{en:'Yes.',jp:'うん。'},{en:'I remember / that day.',jp:'私は覚えています / その日を'},{en:'It is / a good memory.',jp:'それは〜です / よい思い出'},{en:'I realized / my mistake.',jp:'私は気づきました / 自分のまちがいに'},{en:'Anyone can make / a mistake.',jp:'だれでもすることがあります / まちがいを'}],
 questions:[{prompt:'1. 最初、話し手はどのような気持ちでしたか。本文から英語で1語抜き出しなさい。',answer:'bored',evidence:'At first, I was bored.',evidenceJp:'最初は退屈していました。',reason:'bored が話し手の最初の状態を表しています。'},{prompt:'2. 何のコンクールでしたか。本文から英語で答えなさい。',answer:'a chorus contest',evidence:'It was a chorus contest.',evidenceJp:'それは合唱コンクールでした。',reason:'be動詞の後ろの a chorus contest がコンクールの種類です。'},{prompt:'3. 話し手たちはまちがいをしましたか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'We made a mistake.',evidenceJp:'私たちはまちがいをしました。',reason:'made a mistake と明示されています。'},{prompt:'4. それでもコンクールではどうなりましたか。本文から英語で答えなさい。',answer:'won the contest',evidence:'Anyway, we won the contest.',evidenceJp:'それでも、私たちはコンクールで勝ちました。',reason:'won the contest が結果を表しています。'},{prompt:'5. 最後に話し手は何に気づきましたか。本文から英語で答えなさい。',answer:'my mistake',evidence:'I realized my mistake.',evidenceJp:'私は自分のまちがいに気づきました。',reason:'realized の目的語 my mistake が気づいた内容です。'}],
 allowedWords:[['mistake','Unit 10-1'],['anyone','Unit 10-1'],['remember','Unit 10-1'],['realize','Unit 10-1'],['bored','Unit 10-1'],['anyway','Unit 10-1'],['contest','Unit 10-1'],['memory','Unit 10-1'],['chorus','Unit 10-1'],['were','Unit 10-1 explicit past of are'],['made','Unit 10-1 explicit past of make'],['won','Unit 10-1 explicit past of win'],['was','Unit 10-1 explicit past of am/is'],['at first','Unit 10-1 phrase'],['did','Unit 9-2 cumulative past-question grammar'],['can / make / day / good / my / we','cumulative']],
 auditNote:'v9正本を再照合してUnit 10-1の境界をid2535〜2551に確定。mistake / anyone / remember / realize / bored / anyway / contest / memory / chorus / were / made / won / was / wasn’t / weren’t / at first / like ...ing が登録され、id2552からUnit 10-2。以前のhero系本文は別境界情報に基づく誤実装だったため完全に破棄。本文は合唱コンクールの1場面に限定し、正本登録の過去形was / were / made / wonのみを使用。wasn’t / weren’t / like ...ingは不自然な詰め込みを避けるため未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 10-2']={
 id:'V10-NH-G1-U10-2-001',textbook:'ニューホライズン',grade:'1',section:'Unit 10-2',level:'HOP',title:'An Album and a Memory',
 sentences:['Hey, look at this album.','I saw it yesterday.','Did you see it on your way to school?','Yes, I did.','Each picture can bring back a memory.','Really?','Yes.','This picture can bring back my memory of the contest.','My heart can beat fast.','Why?','I remember the contest.','Then I had a break.','Great!'],
 fullTranslation:'「ねえ、このアルバムを見て。」「昨日見たんだ。」「学校へ行く途中で見たの？」「うん。」「それぞれの写真が思い出をよみがえらせることがあるよ。」「本当？」「うん。」「この写真はコンクールの思い出をよみがえらせるんだ。」「心臓が速くどきどきすることもあるよ。」「どうして？」「そのコンクールを思い出すから。」「そのあと休憩したよ。」「いいね！」',
 slashRows:[{en:'Hey, / look at this album.',jp:'ねえ / このアルバムを見て'},{en:'I saw / it / yesterday.',jp:'私は見ました / それを / 昨日'},{en:'Did you see / it / on your way to school?',jp:'あなたは見ましたか / それを / 学校へ行く途中で'},{en:'Yes, / I did.',jp:'はい / 見ました'},{en:'Each picture / can bring back / a memory.',jp:'それぞれの写真は / 思い出させることがあります / 1つの思い出を'},{en:'Really?',jp:'本当？'},{en:'Yes.',jp:'うん。'},{en:'This picture / can bring back / my memory of the contest.',jp:'この写真は / 思い出させることがあります / コンクールの私の思い出を'},{en:'My heart / can beat / fast.',jp:'私の心臓は / どきどきすることがあります / 速く'},{en:'Why?',jp:'どうして？'},{en:'I remember / the contest.',jp:'私は思い出します / そのコンクールを'},{en:'Then / I had / a break.',jp:'そのとき / 私は取りました / 休憩を'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. 話し手はいつアルバムを見ましたか。本文から英語で答えなさい。',answer:'yesterday',evidence:'I saw it yesterday.',evidenceJp:'私はそれを昨日見ました。',reason:'yesterday が見た時を表しています。'},{prompt:'2. 話し手はどこへ行く途中でアルバムを見ましたか。本文から英語で答えなさい。',answer:'school',evidence:'Did you see it on your way to school?',evidenceJp:'学校へ行く途中でそれを見ましたか。',reason:'on your way to の後ろの school が向かっていた場所です。'},{prompt:'3. それぞれの写真は何を思い出させることがありますか。本文から英語で答えなさい。',answer:'a memory',evidence:'Each picture can bring back a memory.',evidenceJp:'それぞれの写真が1つの思い出をよみがえらせることがあります。',reason:'bring back の目的語 a memory が思い出されるものです。'},{prompt:'4. 話し手の心臓はどのように動くことがありますか。本文から英語で答えなさい。',answer:'beat fast',evidence:'My heart can beat fast.',evidenceJp:'私の心臓は速くどきどきすることがあります。',reason:'beat fast が心臓の動きを表しています。'},{prompt:'5. 話し手は何を思い出しますか。本文から英語で答えなさい。',answer:'the contest',evidence:'I remember the contest.',evidenceJp:'私はそのコンクールを思い出します。',reason:'remember の目的語 the contest が思い出す内容です。'}],
 allowedWords:[['break','Unit 10-2 noun: 休憩'],['heart','Unit 10-2'],['way','Unit 10-2'],['bring','Unit 10-2'],['beat','Unit 10-2'],['each','Unit 10-2'],['then','Unit 10-2'],['hey','Unit 10-2'],['yesterday','Unit 10-2'],['album','Unit 10-2'],['fast','Unit 10-2'],['bring back','Unit 10-2 phrase: …を思い出させる'],['on one’s way (to)','Unit 10-2 phrase'],['picture','Sounds and Letters 4 cumulative'],['memory / remember / contest','Unit 10-1 cumulative'],['saw','Unit 9-1 cumulative explicit past of see'],['did / had / can','cumulative']],
 auditNote:'v9正本でUnit 10-2をid2552〜2564に確定。break / heart / way / bring / beat / each / then / hey / yesterday / album / fast / bring back / on one’s way (to) が登録され、id2565からUnit 10-3。旧実装のsafety pinは正本に存在せず誤実装だったため完全に破棄。特にbring backは正本語義「…を思い出させる」に固定し、「返す」の意味では使わない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 10-3']={
 id:'V10-NH-G1-U10-3-001',textbook:'ニューホライズン',grade:'1',section:'Unit 10-3',level:'HOP',title:'A Camping Trip',
 sentences:['This is my camping trip.','We went to a campground.','There’s a hot spring near the campground.','We set up a tent.','The tent is near the hot spring.','At night, there is a campfire.','The campfire is the main event.','Isn’t it exciting?','Yes, it is.','Aren’t you happy?','Yes, I am.','I like camping.','It is a great trip.'],
 fullTranslation:'「これは私のキャンプ旅行です。」「私たちはキャンプ場へ行きました。」「キャンプ場の近くには温泉があります。」「私たちはテントを張りました。」「テントは温泉の近くにあります。」「夜にはキャンプファイアがあります。」「キャンプファイアが主な行事です。」「わくわくしない？」「うん、わくわくするよ。」「うれしくない？」「うん、うれしいよ。」「私はキャンプが好きです。」「すばらしい旅行です。」',
 slashRows:[{en:'This is / my camping trip.',jp:'これは〜です / 私のキャンプ旅行'},{en:'We went / to a campground.',jp:'私たちは行きました / キャンプ場へ'},{en:'There’s / a hot spring / near the campground.',jp:'〜があります / 温泉が / キャンプ場の近くに'},{en:'We set up / a tent.',jp:'私たちは建てました / テントを'},{en:'The tent is / near the hot spring.',jp:'そのテントはあります / 温泉の近くに'},{en:'At night, / there is / a campfire.',jp:'夜には / 〜があります / キャンプファイアが'},{en:'The campfire is / the main event.',jp:'そのキャンプファイアは〜です / 主な行事'},{en:'Isn’t it / exciting?',jp:'それは〜ではないですか / わくわくする'},{en:'Yes, / it is.',jp:'はい / そうです'},{en:'Aren’t you / happy?',jp:'あなたは〜ではないですか / うれしい'},{en:'Yes, / I am.',jp:'はい / そうです'},{en:'I like / camping.',jp:'私は好きです / キャンプが'},{en:'It is / a great trip.',jp:'それは〜です / すばらしい旅行'}],
 questions:[{prompt:'1. 話し手たちはどこへ行きましたか。本文から英語で答えなさい。',answer:'a campground',evidence:'We went to a campground.',evidenceJp:'私たちはキャンプ場へ行きました。',reason:'went to の後ろの a campground が行った場所です。'},{prompt:'2. キャンプ場の近くには何がありますか。本文から英語で答えなさい。',answer:'a hot spring',evidence:'There’s a hot spring near the campground.',evidenceJp:'キャンプ場の近くには温泉があります。',reason:'There’s の後ろの a hot spring があるものです。'},{prompt:'3. 話し手たちは何を張りましたか。本文から英語で答えなさい。',answer:'a tent',evidence:'We set up a tent.',evidenceJp:'私たちはテントを張りました。',reason:'set up の目的語 a tent が建てたものです。'},{prompt:'4. 夜には何がありますか。本文から英語で答えなさい。',answer:'a campfire',evidence:'At night, there is a campfire.',evidenceJp:'夜にはキャンプファイアがあります。',reason:'there is の後ろの a campfire が夜にあるものです。'},{prompt:'5. 主な行事は何ですか。本文から英語で答えなさい。',answer:'the campfire',evidence:'The campfire is the main event.',evidenceJp:'キャンプファイアが主な行事です。',reason:'main event として the campfire が示されています。'}],
 allowedWords:[['trip','Unit 10-3'],['campground','Unit 10-3'],['hot spring','Unit 10-3 phrase'],['tent','Unit 10-3'],['campfire','Unit 10-3'],['set','Unit 10-3 present/past same form explicitly registered'],['main','Unit 10-3'],['night','Unit 10-3'],['event','Unit 10-3'],['camping','Unit 10-3'],['there’s','Unit 10-3 contraction'],['isn’t','Unit 10-3 contraction'],['aren’t','Unit 10-3 contraction'],['there is[are]','Unit 10-3 phrase'],['set up','Unit 10-3 phrase'],['went','Unit 9-1 cumulative explicit past of go'],['near','Unit 3-3 cumulative'],['exciting','Unit 7-3 cumulative'],['happy','Unit 8-3 cumulative'],['great','cumulative']],
 auditNote:'v9正本でUnit 10-3をid2565〜2580に確定し、id2581からReal Life English 6へ切り替わることを確認。trip / campground / hot spring / tent / campfire / set / main / night / event / camping / set（過去形）/ there’s / isn’t / aren’t / there is[are] / set up を正本どおり使用。setは現在形と過去形が同形として正本に別登録されているため、We set up a tent.を過去文として使用している。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};