window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 4-1']={
 id:'V10-SS-G2-P4-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 4-1',level:'HOP',title:'Footprints on a Clear Day',
 sentences:['Today, the sky is clear.','My friend and I go hiking.','My friend can guide me.','We walk in a forest.','I see a footprint.','Is it a deer footprint?','Yes, it is.','Actually, we see a deer near us.','I am glad to see it.','The story about the deer is true.','After the hike, I hear from my friend.','We talk about the footprint.','I want to go hiking again.'],
 fullTranslation:'「今日は空がよく晴れています。友達と私はハイキングに行きます。友達が私を案内してくれます。私たちは森の中を歩きます。私は足跡を見つけます。シカの足跡でしょうか。はい、そうです。実際、近くでシカも見ます。私はそれを見ることができてうれしいです。シカについての話は本当です。ハイキングのあと、友達から連絡をもらいます。私たちはその足跡について話します。またハイキングに行きたいです。」',
 slashRows:[{en:'Today, / the sky is / clear.',jp:'今日 / 空は〜です / よく晴れた'},{en:'My friend and I / go hiking.',jp:'友達と私は / ハイキングに行きます'},{en:'My friend can guide / me.',jp:'友達は案内できます / 私を'},{en:'We walk / in a forest.',jp:'私たちは歩きます / 森の中を'},{en:'I see / a footprint.',jp:'私は見ます / 足跡を'},{en:'Is it / a deer footprint?',jp:'それは〜ですか / シカの足跡'},{en:'Yes, / it is.',jp:'はい / そうです'},{en:'Actually, / we see / a deer / near us.',jp:'実際 / 私たちは見ます / シカを / 私たちの近くで'},{en:'I am / glad / to see it.',jp:'私は〜です / うれしい / それを見られて'},{en:'The story about the deer is / true.',jp:'シカについての話は〜です / 本当の'},{en:'After the hike, / I hear from / my friend.',jp:'ハイキングのあと / 私は連絡をもらいます / 友達から'},{en:'We talk about / the footprint.',jp:'私たちは話します / その足跡について'},{en:'I want to / go hiking / again.',jp:'私は〜したいです / ハイキングに行く / また'}],
 questions:[{prompt:'1. 今日の空はどのようですか。本文から英語で1語抜き出しなさい。',answer:'clear',evidence:'Today, the sky is clear.',evidenceJp:'今日は空がよく晴れています。',reason:'clear が空の様子です。'},{prompt:'2. 友達と話し手は何をしますか。本文から英語で答えなさい。',answer:'go hiking',evidence:'My friend and I go hiking.',evidenceJp:'友達と私はハイキングに行きます。',reason:'主語の後ろの go hiking が行動です。'},{prompt:'3. 友達は何をしてくれますか。本文から英語で答えなさい。',answer:'guide me',evidence:'My friend can guide me.',evidenceJp:'友達が私を案内してくれます。',reason:'can の後ろの guide me ができることです。'},{prompt:'4. 話し手は何を見つけますか。本文から英語で答えなさい。',answer:'a footprint',evidence:'I see a footprint.',evidenceJp:'私は足跡を見つけます。',reason:'see の目的語が a footprint です。'},{prompt:'5. 実際に近くで何を見ますか。本文から英語で答えなさい。',answer:'a deer',evidence:'Actually, we see a deer near us.',evidenceJp:'実際、近くでシカも見ます。',reason:'see の目的語が a deer です。'}],
 allowedWords:[['glad / footprint / actually / true / hear from ~ / clear / guide / go hiking / deer','PROGRAM 4-1: canonical Sheet IDs 3045-3053'],['forest','elementary/G1 cumulative'],['today / sky / friend / walk / see / near / story / after / talk about / want to / again / can','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でSunshine中2 PROGRAM 4-1をID3045〜3053まで直接照合。footprint / clear / guide / go hiking / deer / hear fromを、晴れた日のハイキング1場面に統合。forestは小学校・中1累積語彙として使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 4-2']={
 id:'V10-SS-G2-P4-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 4-2',level:'HOP',title:'Rules in the Forest',
 sentences:['We are in a forest today.','First of all, we must protect the forest.','We must remember this rule.','We must not leave garbage.','We mustn’t leave a potato chip bag, either.','We must keep the forest clean.','We must walk in the forest.','We must help each other.','If we have trouble, we should talk to our guide.','The forest is quiet.','We mustn’t make trouble.','We use this rule to protect the forest.','I am glad to learn this rule.'],
 fullTranslation:'「今日は森にいます。まず何よりも、森を守らなければなりません。私たちはこの規則を覚えなければなりません。ごみを置いていってはいけません。ポテトチップの袋も置いていってはいけません。森をきれいに保たなければなりません。森の中を歩かなければなりません。お互いに助け合わなければなりません。困ったことがあれば、ガイドに話すべきです。森は静かです。困ったことを起こしてはいけません。私たちは森を守るためにこの規則を使います。私はこの規則を学べてうれしいです。」',
 slashRows:[{en:'We are / in a forest / today.',jp:'私たちはいます / 森に / 今日'},{en:'First of all, / we must protect / the forest.',jp:'まず何よりも / 私たちは守らなければなりません / 森を'},{en:'We must remember / this rule.',jp:'私たちは覚えなければなりません / この規則を'},{en:'We must not leave / garbage.',jp:'私たちは残してはいけません / ごみを'},{en:'We mustn’t leave / a potato chip bag, either.',jp:'私たちは残してはいけません / ポテトチップの袋も'},{en:'We must keep / the forest / clean.',jp:'私たちは保たなければなりません / 森を / きれいに'},{en:'We must walk / in the forest.',jp:'私たちは歩かなければなりません / 森の中を'},{en:'We must help / each other.',jp:'私たちは助け合わなければなりません / お互いに'},{en:'If we have / trouble, / we should talk to / our guide.',jp:'もし私たちにあれば / 困ったことが / 私たちは話すべきです / ガイドに'},{en:'The forest is / quiet.',jp:'森は〜です / 静かな'},{en:'We mustn’t make / trouble.',jp:'私たちは起こしてはいけません / 困ったことを'},{en:'We use / this rule / to protect the forest.',jp:'私たちは使います / この規則を / 森を守るために'},{en:'I am / glad / to learn this rule.',jp:'私は〜です / うれしい / この規則を学べて'}],
 questions:[{prompt:'1. まず何を守らなければなりませんか。本文から英語で答えなさい。',answer:'the forest',evidence:'First of all, we must protect the forest.',evidenceJp:'まず何よりも、森を守らなければなりません。',reason:'protect の目的語が the forest です。'},{prompt:'2. ごみを残してもよいですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'We must not leave garbage.',evidenceJp:'ごみを置いていってはいけません。',reason:'must not leave と禁止しているので No です。'},{prompt:'3. 困ったとき、誰に話すべきですか。本文から英語で答えなさい。',answer:'our guide',evidence:'If we have trouble, we should talk to our guide.',evidenceJp:'困ったことがあれば、ガイドに話すべきです。',reason:'talk to の後ろが our guide です。'},{prompt:'4. 森はどのような場所ですか。本文から英語で1語抜き出しなさい。',answer:'quiet',evidence:'The forest is quiet.',evidenceJp:'森は静かです。',reason:'quiet が forest の様子です。'},{prompt:'5. この規則を何のために使いますか。本文から英語で答えなさい。',answer:'to protect the forest',evidence:'We use this rule to protect the forest.',evidenceJp:'私たちは森を守るためにこの規則を使います。',reason:'to protect the forest が目的を表しています。'}],
 allowedWords:[['must / garbage / mustn’t / forest / protect / potato chip / first of all / trouble / rule','PROGRAM 4-2: canonical Sheet IDs 3054-3066'],['guide / glad','PROGRAM 4-1 cumulative'],['if / should / remember','PROGRAM 2 cumulative'],['today / leave / bag / keep / clean / walk / help / each other / quiet / make / use / learn / either','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 4-2をID3054〜3066まで直接照合。初稿に4-3初出のloud / noiseとrule→rulesの自動複数化が混入したため、人手ゲートで削除。ruleは登録表層の単数形だけを使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 4-3']={
 id:'V10-SS-G2-P4-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 4-3',level:'HOP',title:'Our School Trip List',
 sentences:['Tomorrow, we have a school trip.','We have our own list.','First of all, we must be on time.','We must come to school by seven.','We visit a dam in the morning.','An engineer can guide us there.','We must remember this rule.','We mustn’t make loud noise.','We can have a snack at noon.','I have a hood in my bag.','We must not cut down a tree.','At night, we go to bed by ten.','I check the list again.','I am ready for the school trip.'],
 fullTranslation:'「明日、私たちは修学旅行があります。私たちには自分たちのリストがあります。まず何よりも、時間どおりでなければなりません。7時までに学校へ来なければなりません。午前中にダムを訪れます。そこでエンジニアが私たちを案内してくれます。この規則を覚えなければなりません。大きな音を立ててはいけません。正午には軽食をとることができます。私はかばんにフードを入れています。木を1本でも切り倒してはいけません。夜は10時までに寝ます。私はもう一度リストを確認します。修学旅行の準備ができています。」',
 slashRows:[{en:'Tomorrow, / we have / a school trip.',jp:'明日 / 私たちにはあります / 修学旅行が'},{en:'We have / our own list.',jp:'私たちにはあります / 自分たちのリストが'},{en:'First of all, / we must be / on time.',jp:'まず何よりも / 私たちは〜でなければなりません / 時間どおり'},{en:'We must come / to school / by seven.',jp:'私たちは来なければなりません / 学校へ / 7時までに'},{en:'We visit / a dam / in the morning.',jp:'私たちは訪れます / ダムを / 午前中に'},{en:'An engineer can guide / us / there.',jp:'エンジニアは案内できます / 私たちを / そこで'},{en:'We must remember / this rule.',jp:'私たちは覚えなければなりません / この規則を'},{en:'We mustn’t make / loud noise.',jp:'私たちは立ててはいけません / 大きな音を'},{en:'We can have / a snack / at noon.',jp:'私たちは食べられます / 軽食を / 正午に'},{en:'I have / a hood / in my bag.',jp:'私は持っています / フードを / かばんに'},{en:'We must not cut down / a tree.',jp:'私たちは切り倒してはいけません / 木を1本でも'},{en:'At night, / we go to bed / by ten.',jp:'夜 / 私たちは寝ます / 10時までに'},{en:'I check / the list / again.',jp:'私は確認します / リストを / もう一度'},{en:'I am / ready / for the school trip.',jp:'私は〜です / 準備ができている / 修学旅行の'}],
 questions:[{prompt:'1. 明日は何がありますか。本文から英語で答えなさい。',answer:'a school trip',evidence:'Tomorrow, we have a school trip.',evidenceJp:'明日、私たちは修学旅行があります。',reason:'have の目的語が a school trip です。'},{prompt:'2. 何時までに学校へ来なければなりませんか。本文から英語で答えなさい。',answer:'by seven',evidence:'We must come to school by seven.',evidenceJp:'7時までに学校へ来なければなりません。',reason:'by seven が期限を表しています。'},{prompt:'3. 午前中にどこを訪れますか。本文から英語で答えなさい。',answer:'a dam',evidence:'We visit a dam in the morning.',evidenceJp:'午前中にダムを訪れます。',reason:'visit の目的語が a dam です。'},{prompt:'4. 誰が案内してくれますか。本文から英語で答えなさい。',answer:'An engineer',evidence:'An engineer can guide us there.',evidenceJp:'そこでエンジニアが私たちを案内してくれます。',reason:'文の主語 An engineer が案内する人です。'},{prompt:'5. 夜は何時までに寝ますか。本文から英語で答えなさい。',answer:'by ten',evidence:'At night, we go to bed by ten.',evidenceJp:'夜は10時までに寝ます。',reason:'by ten が寝る期限を表しています。'}],
 allowedWords:[['school trip / own / noise / by / list / on time / engineer / go to bed / dam / hood / snack / loud / cut down ~','PROGRAM 4-3: canonical Sheet IDs 3067-3082'],['must / mustn’t / first of all / rule','PROGRAM 4-2 cumulative'],['guide','PROGRAM 4-1 cumulative'],['tomorrow / school / seven / visit / morning / remember / make / noon / bag / tree / night / ten / check / again / ready','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 4-3をID3067〜3082まで直接照合。初稿のrule→rules、tree→treesという自動複数化を人手ゲートで削除し、登録済み単数形rule / treeを使用。build / cover / shampooは無理な消化を避け未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
