(()=>{const D=window.V10_PASSAGES_G3_NH;
let m=D['Unit 2-1'];
m.sentences[4]='I read about ethical fashion from the designer.';
m.sentences[5]='One message is about new fashion.';
m.sentences[8]='I read one question, “Have you read it yet?”';
m.slashRows[4]={en:'I read about / ethical fashion / from the designer.',jp:'私は読みます / エシカルファッションについて / そのデザイナーから'};
m.slashRows[5]={en:'One message is / about new fashion.',jp:'1つのメッセージは〜です / 新しいファッションについて'};
m.slashRows[8]={en:'I read / one question, / “Have you read it yet?”',jp:'私は読みます / 1つの質問を / 「もうそれを読みましたか」'};
m.fullTranslation='「今日、私はエシカルファッションについての評論を読みます。その評論にはデザイナーへのインタビューがあります。私は最初のメッセージをすでに読みました。次のメッセージもちょうど読みました。私はそのデザイナーからエシカルファッションについて読みます。1つのメッセージは新しいファッションについてです。別のメッセージは睡眠についてです。私は最後のメッセージをまだ読んでいません。私は『もうそれを読みましたか』という1つの質問を読みます。私は『まだです』と答えます。私は今日その評論を読み終えたいです。そのインタビューは私にファッションについて考えさせます。」';
m.allowedWords[1][0]='fashion / today / first / next / another / new / last / question / answer / want to / finish / make A B / think about';
m.auditNote+=' 人手監査でPart2以降のdesignとReadThinkのclothingを先取りから削除し、talks / asksの自動三単現も削除。';

m=D['Unit 2-2'];
m.sentences[2]='The answer is, “I have known it since last year.”';
m.sentences[3]='The designer can introduce the design this year.';
m.sentences[7]='I have known this idea for two years.';
m.sentences[8]='My friend has known it since last year.';
m.slashRows[2]={en:'The answer is, / “I have known it / since last year.”',jp:'答えは〜です / 「私はそれを知っています / 去年から」'};
m.slashRows[3]={en:'The designer can introduce / the design / this year.',jp:'そのデザイナーは導入できます / そのデザインを / 今年'};
m.slashRows[7]={en:'I have known / this idea / for two years.',jp:'私は知っています / この考えを / 2年間'};
m.slashRows[8]={en:'My friend has known / it / since last year.',jp:'私の友達は知っています / それを / 去年から'};
m.fullTranslation='「私は新しいデザインについてデザイナーに電話をします。私は『このデザインについてどれくらい長く知っていますか』とたずねます。答えは『去年から知っています』です。そのデザイナーは今年そのデザインを導入できます。そのデザインはよい影響を与えることができます。私たちは古いアクセサリーをリサイクルできます。古いアクセサリーは新しい製品になることができます。私はこの考えを2年間知っています。友達は去年からそれを知っています。私たちは放課後、そのデザインについて話します。私はその影響についてもっと学びたいです。この考えは私たちが衣類について考える助けになります。」';
m.questions[1]={prompt:'2. いつからそのデザインを知っていますか。本文から英語で答えなさい。',answer:'since last year',evidence:'The answer is, “I have known it since last year.”',evidenceJp:'答えは「去年から知っています」です。',reason:'since last year が開始時点です。'};
m.questions[2]={prompt:'3. 誰がそのデザインを導入できますか。本文から英語で答えなさい。',answer:'the designer',evidence:'The designer can introduce the design this year.',evidenceJp:'そのデザイナーは今年そのデザインを導入できます。',reason:'can introduce の主語が The designer です。'};
m.questions[4]={prompt:'5. 話し手はこの考えをどれくらいの間知っていますか。本文から英語で答えなさい。',answer:'for two years',evidence:'I have known this idea for two years.',evidenceJp:'私はこの考えを2年間知っています。',reason:'for two years が期間です。'};
m.allowedWords[1][0]='designer / know-known / year / good / old / new / product / idea / friend / after school / want to / learn / more / can / help / think about / clothing';
m.auditNote+=' 人手監査でReadThink初出companyの先取りとanswers / recyclingの自動派生を削除。';

m=D['Unit 2-3'];
m.sentences[1]='People in the company want to use less material.';
m.sentences[3]='The company can include old material in a product.';
m.sentences[5]='I talk with a worker about the use of wool.';
m.sentences[6]='The company can prohibit the use of too much wool.';
m.sentences[8]='I read, “You’ve learned a lot.”';
m.sentences[11]='I want to know more about clothing.';
m.slashRows[1]={en:'People in the company / want to use / less material.',jp:'会社の人々は / 使いたいです / より少ない材料を'};
m.slashRows[3]={en:'The company can include / old material / in a product.',jp:'その会社は含めることができます / 古い材料を / 製品に'};
m.slashRows[5]={en:'I talk with / a worker / about the use of wool.',jp:'私は話します / 労働者と / 羊毛の使用について'};
m.slashRows[6]={en:'The company can prohibit / the use / of too much wool.',jp:'その会社は禁止できます / 使用を / 多すぎる羊毛の'};
m.slashRows[8]={en:'I read, / “You’ve learned a lot.”',jp:'私は読みます / 「たくさん学んだね」'};
m.slashRows[11]={en:'I want to know / more / about clothing.',jp:'私は知りたいです / もっと / 衣類について'};
m.fullTranslation='「私はある衣料品会社について読みます。会社の人々はより少ない材料を使いたいと考えています。羊毛を使いすぎることを避けることができます。その会社は製品に古い材料を含めることができます。さらに、古いデザインをもう一度使うこともできます。私は労働者と羊毛の使用について話します。その会社は羊毛を使いすぎることを禁止できます。この行動はよりよい製品につながることがあります。私は『たくさん学んだね』と読みます。私はその会社によい考えがあると思います。私たちは授業でその会社について書きます。私は衣類についてもっと知りたいです。」';
m.questions[1]={prompt:'2. 会社の人々は何をより少なく使いたいですか。本文から英語で答えなさい。',answer:'material',evidence:'People in the company want to use less material.',evidenceJp:'会社の人々はより少ない材料を使いたいと考えています。',reason:'less の後ろが material です。'};
m.questions[3]={prompt:'4. 会社は何の使用を禁止できますか。本文から英語で答えなさい。',answer:'too much wool',evidence:'The company can prohibit the use of too much wool.',evidenceJp:'その会社は羊毛を使いすぎることを禁止できます。',reason:'of の後ろが too much wool です。'};
m.allowedWords[1][0]='material / product / old / design / again / action / better / friend / learn / think / good / idea / write about / class / want to / know / more / clothing / people / talk with';
m.auditNote+=' 共通プール後半のchemical / responsibleを先取りから削除し、wants / talks / says / learnedとrecycledの自動派生も削除。';

m=D['Unit 2-4'];
m.sentences=['A clothing company should be responsible.','A worker should have a fair condition.','A low wage can have a negative impact.','Fair labor is important.','A responsible company should think about a worker.','It should also think about each chemical in clothing.','Leather is a material for some clothing.','Fur is a material too.','A company can choose another material.','The condition of labor can change a product.','A fair wage is important for a worker.','I think responsible clothing should have a fair idea.','I want to learn more before I choose clothing.'];
m.slashRows=[{en:'A clothing company / should be / responsible.',jp:'衣料品会社は / 〜であるべきです / 責任がある'},{en:'A worker / should have / a fair condition.',jp:'労働者は / 持つべきです / 公平な状況を'},{en:'A low wage / can have / a negative impact.',jp:'低い賃金は / 持つことがあります / 悪い影響を'},{en:'Fair labor is / important.',jp:'公平な労働は〜です / 大切'},{en:'A responsible company / should think about / a worker.',jp:'責任ある会社は / 考えるべきです / 労働者について'},{en:'It should also think about / each chemical / in clothing.',jp:'それはまた考えるべきです / それぞれの化学物質について / 衣類の'},{en:'Leather is / a material / for some clothing.',jp:'革は〜です / 材料 / 一部の衣類の'},{en:'Fur is / a material / too.',jp:'毛皮も〜です / 材料 / も'},{en:'A company can choose / another material.',jp:'会社は選ぶことができます / 別の材料を'},{en:'The condition / of labor / can change / a product.',jp:'状況は / 労働の / 変えることがあります / 製品を'},{en:'A fair wage is / important / for a worker.',jp:'公平な賃金は〜です / 大切 / 労働者にとって'},{en:'I think / responsible clothing / should have / a fair idea.',jp:'私は思います / 責任ある衣類は / 持つべきだと / 公平な考えを'},{en:'I want to learn / more / before I choose clothing.',jp:'私は学びたいです / もっと / 衣類を選ぶ前に'}];
m.fullTranslation='「衣料品会社は責任を持つべきです。労働者は公平な状況を持つべきです。低い賃金は悪い影響を与えることがあります。公平な労働は大切です。責任ある会社は労働者について考えるべきです。また、衣類に含まれるそれぞれの化学物質についても考えるべきです。革は一部の衣類の材料です。毛皮も材料です。会社は別の材料を選ぶことができます。労働の状況は製品を変えることがあります。公平な賃金は労働者にとって大切です。責任ある衣類は公平な考え方を持つべきだと私は思います。私は衣類を選ぶ前にもっと学びたいです。」';
m.questions=[{prompt:'1. 労働者はどのような状況を持つべきですか。本文から英語で答えなさい。',answer:'a fair condition',evidence:'A worker should have a fair condition.',evidenceJp:'労働者は公平な状況を持つべきです。',reason:'have の目的語が a fair condition です。'},{prompt:'2. 低い賃金はどのような影響を与えることがありますか。本文から英語で答えなさい。',answer:'a negative impact',evidence:'A low wage can have a negative impact.',evidenceJp:'低い賃金は悪い影響を与えることがあります。',reason:'have の目的語が a negative impact です。'},{prompt:'3. 何が大切ですか。本文から英語で答えなさい。',answer:'fair labor',evidence:'Fair labor is important.',evidenceJp:'公平な労働は大切です。',reason:'important の主語が Fair labor です。'},{prompt:'4. 革は何ですか。本文から英語で答えなさい。',answer:'a material',evidence:'Leather is a material for some clothing.',evidenceJp:'革は一部の衣類の材料です。',reason:'be動詞の後ろが a material です。'},{prompt:'5. 公平な賃金は誰にとって大切ですか。本文から英語で答えなさい。',answer:'a worker',evidence:'A fair wage is important for a worker.',evidenceJp:'公平な賃金は労働者にとって大切です。',reason:'for の後ろが a worker です。'}];
m.allowedWords[1][0]='company / worker / material / impact / important / should / think about / each / some / can / choose / another / change / product / idea / want to / learn / more / before';
m.auditNote+=' responsibility / needs / materialsなど未登録派生を削除し、responsible / wage / leather / labor / fur / condition / clothing / chemical / low / negative / fairの正本形に統一。';
})();
