// Reference/minimum-rule slash audit passages 101-110.
(function(){
 const PASS='PASS_REFERENCE_20260820';
 function setAudit(data,section,rows,n){const p=data&&data[section];if(!p)throw new Error('Missing reference passage '+n+': '+section);if(rows.length!==(p.sentences||[]).length)throw new Error('Row mismatch '+n);for(let i=0;i<rows.length;i++){const e=String(rows[i].en||'').replace(/\s*\/\s*/g,' ').replace(/\s+/g,' ').trim(),s=String(p.sentences[i]||'').replace(/\s+/g,' ').trim();if(e!==s)throw new Error('English mismatch '+n+'#'+(i+1)+': '+e+' <> '+s);const ec=String(rows[i].en||'').split(/\s*\/\s*/).filter(Boolean).length,jc=String(rows[i].jp||'').split(/\s*\/\s*/).filter(Boolean).length;if(ec!==jc)throw new Error('EN/JP chunks '+n+'#'+(i+1)+' '+ec+'/'+jc)}p.slashRows=rows;p.slashReadingVersion='reference-book-minimum-rules-20260820';p.slashReferenceAudit=PASS;p.slashReferencePassageNo=n}
 const d=window.V10_PASSAGES_G2_NH||{};
 setAudit(d,'Unit 2-3',[
  {en:'Today, / my friend / and I go / to a recommended local restaurant.',jp:'今日 / 私の友達 / そして私は行きます / おすすめの地元のレストランへ'},{en:'We go there early / because the restaurant is popular.',jp:'私たちは早くそこへ行きます / そのレストランが人気だから'},{en:'We order the local soup / before the lunch crowd.',jp:'私たちは地元のスープを注文します / 昼食時の混雑の前に'},{en:'The soup is thick.',jp:'そのスープは濃厚です。'},{en:'It is soy sauce-based.',jp:'しょうゆをベースにしています。'},{en:'This is one kind / of local food.',jp:'これは1種類です / 地元の食べ物の'},{en:'I like the strong flavor.',jp:'私はその強い風味が好きです。'},{en:'My friend likes the soup, / too.',jp:'友達もそのスープが好きです / 〜もまた'},{en:'We eat slowly / and talk / about the flavor.',jp:'私たちはゆっくり食べます / そして話します / 風味について'},{en:'I do not want / to forget this soup.',jp:'私は望みません / このスープを忘れることを'},{en:'I would recommend it / to another friend.',jp:'私はそれをすすめたいです / 別の友達に'}
 ],101);
 setAudit(d,'Unit 2-4',[
  {en:'Our city has a hot climate.',jp:'私たちの町は暑い気候です。'},{en:'A local chef wanted / to create a fresh sauce / for hot days.',jp:'地元のシェフは望みました / さわやかなソースを作ることを / 暑い日のために'},{en:'The chef came / from a foreign country.',jp:'そのシェフは来ました / 外国から'},{en:'The chef used a local fruit / in the sauce.',jp:'そのシェフは地元の果物を使いました / ソースに'},{en:'The fruit gives the sauce a fresh flavor.',jp:'その果物がソースにさわやかな風味を与えます。'},{en:'The sauce reflects both the local climate / and the chef’s background.',jp:'そのソースは地元の気候を反映しています / そしてシェフの背景も'},{en:'People / in the city liked the new sauce.',jp:'人々が / 町の中のその新しいソースを気に入りました'},{en:'They named it / after the city.',jp:'彼らはそれに名前を付けました / 町にちなんで'},{en:'Later, / another chef created a different variation.',jp:'後に / 別のシェフが違う変化形を作りました'},{en:'The second sauce has a stronger flavor.',jp:'2つ目のソースはより強い風味があります。'},{en:'Both sauces are now local food.',jp:'今ではどちらのソースも地元の食べ物です。'},{en:'Food can change / when people bring different ideas together.',jp:'食べ物は変わることがあります / 人々が異なる考えを合わせると'}
 ],102);
 setAudit(d,'Unit 3-1',[
  {en:'Today is Career Day.',jp:'今日は職業体験日です。'},{en:'I chose a nursery school.',jp:'私は保育園を選びました。'},{en:'In the morning, / I help the children get ready / to play.',jp:'朝 / 私は子どもたちが準備するのを手伝います / 遊ぶために'},{en:'I read a short picture book / to them.',jp:'私は短い絵本を読みます / 彼らに'},{en:'Then I play / with the children.',jp:'それから私は遊びます / 子どもたちと'},{en:'One child needs help, / so I stay / near the child.',jp:'1人の子どもが助けを必要としています / だから私はいます / その子の近くに'},{en:'I learn / that nursery-school work needs care / and attention.',jp:'私は学びます / 保育園の仕事には思いやりが必要だと / そして注意も'},{en:'I make a note / about the work.',jp:'私はメモを取ります / 仕事について'},{en:'The teacher gives me useful information / about the career.',jp:'先生が私に役立つ情報をくれます / その職業について'},{en:'I think / about my own career / after the visit.',jp:'私は考えます / 自分自身の職業について / 訪問のあと'},{en:'Career Day is a good experience / for me.',jp:'職業体験日はよい経験です / 私にとって'}
 ],103);
 setAudit(d,'Unit 3-2',[
  {en:'Today is Career Day.',jp:'今日は職業体験日です。'},{en:'I work / at a shop / that sells chopsticks.',jp:'私は働きます / 店で / はしを売る'},{en:'My job is / to make a colorful tag / for a new product.',jp:'私の仕事は〜です / 色彩豊かなタグを作ること / 新しい商品のために'},{en:'First, / I draw an illustration / on the tag.',jp:'まず / 私はイラストを描きます / タグに'},{en:'Then I write a short note / about the chopsticks.',jp:'それから私は短い説明を書きます / はしについて'},{en:'The shop uses the tag / to help customers understand the product.',jp:'店はそのタグを使います / お客さんが商品を理解できるように'},{en:'I show my own design / to a shop worker.',jp:'私は自分自身のデザインを見せます / 店員に'},{en:'The worker gives me advice.',jp:'店員は私に助言をくれます。'},{en:'I change one part / of the illustration.',jp:'私は一部を変えます / イラストの'},{en:'The finished tag is easy / to understand.',jp:'完成したタグは簡単です / 理解するのが'},{en:'I learn / that design can help a shop communicate / with customers.',jp:'私は学びます / デザインは店が情報を伝える助けになると / お客さんに'},{en:'I want / to learn more / about this work.',jp:'私は望んでいます / もっと学ぶことを / この仕事について'}
 ],104);
 setAudit(d,'Unit 3-3',[
  {en:'Yesterday, / our teacher taught us / with a picture book.',jp:'昨日 / 先生は私たちに教えました / 絵本を使って'},{en:'At the beginning, / a tiny caterpillar lay / on a leaf.',jp:'はじめに / 小さなイモムシがいました / 葉の上に'},{en:'The moon came up, / and the caterpillar came out.',jp:'月がのぼりました / そしてイモムシが出てきました'},{en:'The next day, / the caterpillar looked / for food.',jp:'次の日 / イモムシは探しました / 食べ物を'},{en:'It found a pear.',jp:'それは西洋ナシを見つけました。'},{en:'Then it found a plum.',jp:'それからプラムを見つけました。'},{en:'The caterpillar ate the fruit / and rested / on a leaf.',jp:'イモムシは果物を食べました / そして休みました / 葉の上で'},{en:'The pictures were pretty.',jp:'絵はきれいでした。'},{en:'The light / from the moon made the first picture special.',jp:'光が / 月からの最初の絵を特別なものにしました'},{en:'After the lesson, / the book lay / on my desk.',jp:'授業のあと / その本はありました / 私の机の上に'},{en:'I looked / at the pictures again.',jp:'私は見ました / もう一度絵を'},{en:'I liked the tiny caterpillar very much.',jp:'私はその小さなイモムシがとても気に入りました。'}
 ],105);
 setAudit(d,'Unit 3-4',[
  {en:'Dear Ms. Brown,',jp:'ブラウン先生へ'},{en:'Thank you / for your reading lesson.',jp:'ありがとうございます / 読書の授業を'},{en:'I understand the story better now.',jp:'今ではその話を前よりよく理解しています。'},{en:'I learned how / to read clearly.',jp:'私は方法を学びました / はっきり読む'},{en:'When a sentence is difficult, / I adjust my speed.',jp:'文が難しいとき / 私は読む速さを調節します'},{en:'I read the sentence again / and again.',jp:'私はその文を読みます / 何度も'},{en:'This practice is necessary / for me.',jp:'この練習は必要です / 私に'},{en:'I am glad / that I learned this way / of reading.',jp:'私はうれしいです / この方法を学べたことが / 読むための'},{en:'From now on, / I will practice every day.',jp:'これからは / 私は毎日練習します'},{en:'I want / to read the next story clearly, / too.',jp:'私は望んでいます / 次の話をはっきり読むことを / 〜もまた'},{en:'Thank you / for your help.',jp:'ありがとうございます / あなたの助けを'},{en:'Sincerely yours,',jp:'敬具'},{en:'Ken',jp:'ケン'}
 ],106);
 setAudit(d,'Unit 4-1',[
  {en:'I am / on a homestay.',jp:'私は〜です / ホームステイ中'},{en:'At first, / I think I am only a guest / in the house.',jp:'最初 / 私はただの客だと思っています / この家では'},{en:'My host tells me one house rule.',jp:'ホストが家の規則を1つ教えてくれます。'},{en:'I have / to help / at dinner.',jp:'私はしなければなりません / 手伝うことを / 夕食で'},{en:'I ask my host why I have / to help.',jp:'私はなぜしなければならないかホストにたずねます / 手伝うことを'},{en:'My host says, / “You are a member / of the family / while you are here.”',jp:'ホストは言います / 「あなたは一員です / 家族の / ここにいる間」'},{en:'I do not have / to be perfect.',jp:'私は必要はありません / 完ぺきである'},{en:'I only have / to help / with simple things.',jp:'私は〜すればよいだけです / 手伝う / 簡単なことを'},{en:'The advice makes the rule easy / to understand.',jp:'その助言で規則が簡単になります / 理解するのが'},{en:'That evening, / I help / at dinner.',jp:'その晩 / 私は手伝います / 夕食で'},{en:'I feel more like a member / of the family.',jp:'私はより一員らしく感じます / 家族の'},{en:'I want / to follow the rule / during my homestay.',jp:'私は望んでいます / その規則に従うことを / ホームステイ中'}
 ],107);
 setAudit(d,'Unit 4-2',[
  {en:'My host explains a shower rule / to me.',jp:'ホストがシャワーの規則を説明します / 私に'},{en:'We must save water / in this house.',jp:'私たちは水を節約しなければなりません / この家で'},{en:'For that reason, / I must take a short shower.',jp:'そのため / 私は短いシャワーを浴びなければなりません'},{en:'I must not use water / for a long time.',jp:'私は水を使ってはいけません / 長い時間'},{en:'The shower also has a time limit.',jp:'シャワーには時間制限もあります。'},{en:'I ask my host / about the limit.',jp:'私はホストにたずねます / 制限について'},{en:'My host explains how long I can use the shower.',jp:'ホストはシャワーをどのくらい使えるか説明してくれます。'},{en:'I understand the rule now.',jp:'今では規則を理解しています。'},{en:'That night, / I take a short shower.',jp:'その晩 / 私は短いシャワーを浴びます'},{en:'I finish / before the time limit.',jp:'私は終えます / 時間制限の前に'},{en:'I think saving water is an important house rule.',jp:'水を節約することは大切な家の規則だと思います。'}
 ],108);
 setAudit(d,'Unit 4-3',[
  {en:'At dinner, / I make a small mistake.',jp:'夕食で / 私は小さな間違いをします'},{en:'I put food / on the wrong plate.',jp:'私は食べ物を置きます / 間違った皿に'},{en:'My host notices it / and explains the dinner rule.',jp:'ホストがそれに気づきます / そして食事の規則を説明します'},{en:'I should use my own plate / for this food.',jp:'私は自分の皿を使うべきです / この食べ物に'},{en:'I listen / to my host carefully.',jp:'私は聞きます / ホストの話を注意深く'},{en:'I ask, / “Is this plate right?”',jp:'私はたずねます / 「この皿で合っていますか」'},{en:'My host says, / “Yes, / it is.”',jp:'ホストは言います / 「はい / 合っています」'},{en:'I use the right plate / and continue dinner.',jp:'私は正しい皿を使います / そして夕食を続けます'},{en:'My host / and I listen / to each other.',jp:'私のホスト / そして私は聞きます / おたがいに'},{en:'I think / about my host’s feeling, / too.',jp:'私は考えます / ホストの気持ちについて / 〜もまた'},{en:'In the end, / the rule is not difficult.',jp:'最後には / その規則は難しくありません'},{en:'Dinner is fun / after I understand it.',jp:'夕食は楽しいです / 私がそれを理解したあと'},{en:'I want / to remember this rule / in the future.',jp:'私は望んでいます / この規則を覚えておくことを / 将来'}
 ],109);
 setAudit(d,'Unit 4-4',[
  {en:'During my homestay, / I stayed / with an elderly couple.',jp:'ホームステイ中 / 私は滞在しました / 年配の夫婦と'},{en:'On the first evening, / I entered the house / with my shoes on.',jp:'最初の晩 / 私は家に入りました / 靴をはいたまま'},{en:'The couple stopped me / at the door.',jp:'その夫婦は私を止めました / ドアで'},{en:'At first, / I couldn’t understand the rule.',jp:'最初 / 私はその規則を理解できませんでした'},{en:'I felt nervous / because I thought I had done something wrong.',jp:'私は緊張しました / 何か悪いことをしたと思ったから'},{en:'The couple explained / that I should take off my shoes / before I enter the room.',jp:'その夫婦は説明しました / 私は靴を脱ぐべきだと / 部屋に入る前に'},{en:'I listened / to the couple carefully.',jp:'私は聞きました / その夫婦の話を注意深く'},{en:'Then I took off my shoes / at the door.',jp:'それから私は靴を脱ぎました / ドアで'},{en:'The couple smiled, / and I felt better.',jp:'夫婦はほほえみました / そして私は気持ちが楽になりました'},{en:'After that, / I followed the rule every day.',jp:'そのあと / 私は毎日その規則に従いました'},{en:'In the end, / the rule was easy / to understand.',jp:'最後には / その規則は簡単でした / 理解するのが'},{en:'I want / to remember this experience / in the future.',jp:'私は望んでいます / この経験を覚えておくことを / 将来'}
 ],110);
 window.V10_REFERENCE_SLASH_AUDIT={version:'2026-08-20',passagesAudited:110,total:168,lastCompleted:110,minimumRuleImageConfirmed:true};
})();