window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 4-1']={
id:'V10-SS-G3-P4-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 4-1',level:'HOP',title:'Signs at a Restaurant',
sentences:['Today I travel with my friend.','We are at a restaurant.','A waiter is behind the counter.','The waiter can use sign language.','My friend can use a gesture too.','A gesture is not always sign language.','I watch the waiter carefully.','The waiter and my friend can understand each other.','I want to learn sign language.','We talk about our travel after dinner.','Sign language is interesting to me.','I write about the day in my notebook.'],
fullTranslation:'「今日、私は友達と旅行をしています。私たちはレストランにいます。ウェイターはカウンターのうしろにいます。そのウェイターは手話を使うことができます。友達も身ぶりを使うことができます。身ぶりがいつも手話というわけではありません。私はウェイターを注意深く見ます。ウェイターと友達はおたがいを理解できます。私は手話を学びたいです。夕食のあと、私たちは旅行について話します。手話は私にとって興味深いです。私はその日のことをノートに書きます。」',
slashRows:[{en:'Today / I travel / with my friend.',jp:'今日 / 私は旅行をします / 友達と'},{en:'We are / at a restaurant.',jp:'私たちはいます / レストランに'},{en:'A waiter is / behind the counter.',jp:'ウェイターはいます / カウンターのうしろに'},{en:'The waiter / can use / sign language.',jp:'そのウェイターは / 使うことができます / 手話を'},{en:'My friend / can use / a gesture / too.',jp:'私の友達も / 使うことができます / 身ぶりを'},{en:'A gesture is not always / sign language.',jp:'身ぶりはいつも〜とは限りません / 手話とは'},{en:'I watch / the waiter / carefully.',jp:'私は見ます / ウェイターを / 注意深く'},{en:'The waiter and my friend / can understand / each other.',jp:'ウェイターと私の友達は / 理解できます / おたがいを'},{en:'I want to learn / sign language.',jp:'私は学びたいです / 手話を'},{en:'We talk about / our travel / after dinner.',jp:'私たちは話します / 私たちの旅行について / 夕食のあと'},{en:'Sign language is / interesting / to me.',jp:'手話は〜です / 興味深い / 私にとって'},{en:'I write about / the day / in my notebook.',jp:'私は書きます / その日のことを / ノートに'}],
questions:[{prompt:'1. 話し手はだれと旅行をしていますか。本文から英語で答えなさい。',answer:'my friend',evidence:'Today I travel with my friend.',evidenceJp:'今日、私は友達と旅行をしています。',reason:'with の後ろが my friend です。'},{prompt:'2. ウェイターはどこにいますか。本文から英語で答えなさい。',answer:'behind the counter',evidence:'A waiter is behind the counter.',evidenceJp:'ウェイターはカウンターのうしろにいます。',reason:'behind the counter が場所を表しています。'},{prompt:'3. ウェイターは何を使うことができますか。本文から英語で答えなさい。',answer:'sign language',evidence:'The waiter can use sign language.',evidenceJp:'そのウェイターは手話を使うことができます。',reason:'use の目的語が sign language です。'},{prompt:'4. 友達は何を使うことができますか。本文から英語で答えなさい。',answer:'a gesture',evidence:'My friend can use a gesture too.',evidenceJp:'友達も身ぶりを使うことができます。',reason:'use の目的語が a gesture です。'},{prompt:'5. 話し手は何を学びたいですか。本文から英語で答えなさい。',answer:'sign language',evidence:'I want to learn sign language.',evidenceJp:'私は手話を学びたいです。',reason:'learn の目的語が sign language です。'}],
allowedWords:[["behind / sign language / travel / gesture / waiter",'PROGRAM4 4-1: v7 canonical partition'],['today / friend / restaurant / counter / can / use / always / watch / carefully / understand / each other / want to / learn / talk about / after / dinner / interesting / write / day / notebook','G1-G2 and PROGRAM1-3 cumulative']],
auditNote:'最新v7正本PROGRAM4 4-1（ID3720-3724）を直接照合。behind / sign language / travel / gesture / waiterを中心に構成。4-2のaccording to / official / user / widely / part、4-3のrealize以降、PROGRAM5語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 4-2']={
id:'V10-SS-G3-P4-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 4-2',level:'HOP',title:'An Official Guide',
sentences:['Our school has an official guide.','According to the guide, sign language is important.','A user can read the guide at school.','The guide has one part about sign language.','People can use sign language widely.','I read the official guide with my friend.','My friend can find the sign language part.','According to the guide, a gesture and sign language are different.','A user can choose the information he needs.','We talk about one part of the guide.','The guide is useful for a new user.','I want to read the guide again.'],
fullTranslation:'「私たちの学校には公式の案内があります。その案内によれば、手話は大切です。利用者は学校でその案内を読むことができます。その案内には手話についての部分が1つあります。人々は手話を広く使うことができます。私は友達と公式の案内を読みます。友達は手話の部分を見つけることができます。その案内によれば、身ぶりと手話は異なります。利用者は必要な情報を選ぶことができます。私たちは案内の1つの部分について話します。その案内は新しい利用者に役立ちます。私はもう一度その案内を読みたいです。」',
slashRows:[{en:'Our school has / an official guide.',jp:'私たちの学校にはあります / 公式の案内が'},{en:'According to the guide, / sign language is / important.',jp:'その案内によれば / 手話は〜です / 大切な'},{en:'A user / can read / the guide / at school.',jp:'利用者は / 読むことができます / その案内を / 学校で'},{en:'The guide has / one part / about sign language.',jp:'その案内にはあります / 1つの部分が / 手話についての'},{en:'People / can use / sign language / widely.',jp:'人々は / 使うことができます / 手話を / 広く'},{en:'I read / the official guide / with my friend.',jp:'私は読みます / 公式の案内を / 友達と'},{en:'My friend / can find / the sign language part.',jp:'私の友達は / 見つけることができます / 手話の部分を'},{en:'According to the guide, / a gesture and sign language are / different.',jp:'その案内によれば / 身ぶりと手話は〜です / 異なる'},{en:'A user / can choose / the information / he needs.',jp:'利用者は / 選ぶことができます / 情報を / 必要な'},{en:'We talk about / one part / of the guide.',jp:'私たちは話します / 1つの部分について / その案内の'},{en:'The guide is / useful / for a new user.',jp:'その案内は〜です / 役立つ / 新しい利用者にとって'},{en:'I want to read / the guide / again.',jp:'私は読みたいです / その案内を / もう一度'}],
questions:[{prompt:'1. 学校にはどのような案内がありますか。本文から英語で答えなさい。',answer:'an official guide',evidence:'Our school has an official guide.',evidenceJp:'私たちの学校には公式の案内があります。',reason:'has の目的語が an official guide です。'},{prompt:'2. 案内によれば、何が大切ですか。本文から英語で答えなさい。',answer:'sign language',evidence:'According to the guide, sign language is important.',evidenceJp:'その案内によれば、手話は大切です。',reason:'important の主語が sign language です。'},{prompt:'3. 利用者はどこで案内を読むことができますか。本文から英語で答えなさい。',answer:'at school',evidence:'A user can read the guide at school.',evidenceJp:'利用者は学校でその案内を読むことができます。',reason:'at school が場所を示しています。'},{prompt:'4. 案内には何についての部分がありますか。本文から英語で答えなさい。',answer:'sign language',evidence:'The guide has one part about sign language.',evidenceJp:'その案内には手話についての部分が1つあります。',reason:'about の後ろが sign language です。'},{prompt:'5. 手話はどのように使うことができますか。本文から英語で1語抜き出しなさい。',answer:'widely',evidence:'People can use sign language widely.',evidenceJp:'人々は手話を広く使うことができます。',reason:'widely が使われ方を表す副詞です。'}],
allowedWords:[["according to ~ / official / user / widely / part",'PROGRAM4 4-2: v7 canonical partition'],['behind / sign language / travel / gesture / waiter','PROGRAM4 4-1 cumulative'],['school / guide / important / can / read / people / use / friend / find / different / choose / information / need / talk about / useful / new / again','G1-G2 and PROGRAM1-3 cumulative']],
auditNote:'最新v7正本PROGRAM4 4-2（ID3725-3729）を直接照合。according to / official / user / widely / partを案内文の文脈に統合。4-3のrealize / enter / wide / point / along等とPROGRAM5語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 4-3']={
id:'V10-SS-G3-P4-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 4-3',level:'HOP',title:'A Barrier-Free Facility',
sentences:['At first, I cannot understand every type of sign.','I enter a barrier-free facility with my friend.','The entrance is wide.','A hand rail is along the wall.','An elderly customer is near the stage.','The customer can point at a sign.','In addition, the sign can represent an important message.','A blind person is with the customer.','I realize that sign language has more than one type.','A door can open automatically.','My friend says, “I’m afraid that this place is new to me.”','We drop by the stage after the event.','A student from Asia talks about ASL.','ASL is one type of sign language.','The facility is easy to enter.','I realize that a wide space can help many people.'],
fullTranslation:'「はじめは、私はすべての種類の表示を理解できません。私は友達とバリアフリーの施設に入ります。入口は広いです。壁に沿って手すりがあります。年配のお客さんがステージの近くにいます。そのお客さんは表示を指さすことができます。さらに、その表示は大切なメッセージを表すことができます。目が見えない人がお客さんといっしょにいます。私は手話には2つ以上の種類があることに気づきます。ドアは自動的に開くことができます。友達は『残念ながら、この場所は私には初めてです』と言います。私たちはイベントのあとでステージに立ち寄ります。アジア出身の生徒がアメリカ手話について話します。アメリカ手話は手話の1つの種類です。その施設は入りやすいです。私は広い空間が多くの人を助けることができると気づきます。」',
slashRows:[{en:'At first, / I cannot understand / every type / of sign.',jp:'はじめは / 私は理解できません / すべての種類を / 表示の'},{en:'I enter / a barrier-free facility / with my friend.',jp:'私は入ります / バリアフリーの施設に / 友達と'},{en:'The entrance is / wide.',jp:'入口は〜です / 広い'},{en:'A hand rail is / along the wall.',jp:'手すりがあります / 壁に沿って'},{en:'An elderly customer is / near the stage.',jp:'年配のお客さんはいます / ステージの近くに'},{en:'The customer / can point at / a sign.',jp:'そのお客さんは / 指さすことができます / 表示を'},{en:'In addition, / the sign / can represent / an important message.',jp:'さらに / その表示は / 表すことができます / 大切なメッセージを'},{en:'A blind person is / with the customer.',jp:'目が見えない人はいます / そのお客さんと'},{en:'I realize / that sign language has / more than one type.',jp:'私は気づきます / 手話にはあります / 2つ以上の種類が'},{en:'A door / can open / automatically.',jp:'ドアは / 開くことができます / 自動的に'},{en:'My friend says, / “I’m afraid that / this place is new to me.”',jp:'友達は言います / 「残念ながら / この場所は私には初めてです」'},{en:'We drop by / the stage / after the event.',jp:'私たちは立ち寄ります / ステージに / イベントのあと'},{en:'A student from Asia / talks about / ASL.',jp:'アジア出身の生徒は / 話します / アメリカ手話について'},{en:'ASL is / one type / of sign language.',jp:'アメリカ手話は〜です / 1つの種類 / 手話の'},{en:'The facility is / easy to enter.',jp:'その施設は〜です / 入りやすい'},{en:'I realize / that a wide space / can help / many people.',jp:'私は気づきます / 広い空間が / 助けることができると / 多くの人を'}],
questions:[{prompt:'1. 話し手はどのような施設に入りますか。本文から英語で答えなさい。',answer:'a barrier-free facility',evidence:'I enter a barrier-free facility with my friend.',evidenceJp:'私は友達とバリアフリーの施設に入ります。',reason:'enter の目的語が a barrier-free facility です。'},{prompt:'2. 入口はどのようですか。本文から英語で1語抜き出しなさい。',answer:'wide',evidence:'The entrance is wide.',evidenceJp:'入口は広いです。',reason:'entrance の状態を表す語が wide です。'},{prompt:'3. 手すりはどこにありますか。本文から英語で答えなさい。',answer:'along the wall',evidence:'A hand rail is along the wall.',evidenceJp:'壁に沿って手すりがあります。',reason:'along the wall が場所を表しています。'},{prompt:'4. 年配のお客さんはどこにいますか。本文から英語で答えなさい。',answer:'near the stage',evidence:'An elderly customer is near the stage.',evidenceJp:'年配のお客さんがステージの近くにいます。',reason:'near the stage が場所を表しています。'},{prompt:'5. アメリカ手話は何の1つの種類ですか。本文から英語で答えなさい。',answer:'sign language',evidence:'ASL is one type of sign language.',evidenceJp:'アメリカ手話は手話の1つの種類です。',reason:'of の後ろが sign language です。'}],
allowedWords:[["realize / enter / wide / point / along / stage / in addition / type / at first / customer / drop by ~ / elderly / I'm afraid (that)~ / blind / represent / automatically",'PROGRAM4 4-3: v7 canonical partition'],['must / facility / ASL / hand rail / Asia / barrier-free','PROGRAM4 textbook-body pool'],['according to / official / user / widely / part / behind / sign language / travel / gesture / waiter','PROGRAM4 4-1/4-2 cumulative'],['cannot / understand / every / sign / friend / entrance / wall / near / important / message / person / more than / one / door / open / place / new / after / event / student / talk about / easy / space / can / help / many / people','G1-G2 and PROGRAM1-3 cumulative']],
auditNote:'最新v7正本PROGRAM4 4-3（ID3730-3745）とPROGRAM4教科書本文語彙（ID3746-3751）を直接照合。realize / enter / wide / point / along / stage / in addition / type / at first / customer / drop by / elderly / I’m afraid that / blind / represent / automatically、facility / ASL / hand rail / Asia / barrier-freeを使用。PROGRAM5 5-1以降の語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
