window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 0']={
id:'V10-NH-G3-U0-001',textbook:'ニューホライズン',grade:'3',section:'Unit 0',level:'HOP',title:'A New Side of My Classmate',
sentences:['Today our class has a short activity.','We talk about a new side of our classmates.','My friend likes a musical.','He wants to be an actor someday.','I did not know that before.','I discover a new side of him.','Another friend likes music and drawing.','She shows us one picture.','We talk about our interests together.','Finally, I understand my classmates better.','The activity is simple but interesting.','I want to discover more about my friends.'],
fullTranslation:'「今日、私たちのクラスでは短い活動があります。私たちはクラスメートの新しい一面について話します。私の友達はミュージカルが好きです。彼はいつか俳優になりたいと思っています。私はそれを前には知りませんでした。私は彼の新しい一面を発見します。別の友達は音楽と絵が好きです。彼女は私たちに1枚の絵を見せます。私たちは興味についていっしょに話します。ついに、私はクラスメートのことをもっとよく理解します。その活動は簡単ですがおもしろいです。私は友達についてもっと発見したいです。」',
slashRows:[{en:'Today / our class has / a short activity.',jp:'今日 / 私たちのクラスではあります / 短い活動が'},{en:'We talk about / a new side / of our classmates.',jp:'私たちは話します / 新しい一面について / クラスメートの'},{en:'My friend likes / a musical.',jp:'私の友達は好きです / ミュージカルが'},{en:'He wants to be / an actor / someday.',jp:'彼はなりたいです / 俳優に / いつか'},{en:'I did not know / that / before.',jp:'私は知りませんでした / それを / 前には'},{en:'I discover / a new side / of him.',jp:'私は発見します / 新しい一面を / 彼の'},{en:'Another friend likes / music and drawing.',jp:'別の友達は好きです / 音楽と絵が'},{en:'She shows / us / one picture.',jp:'彼女は見せます / 私たちに / 1枚の絵を'},{en:'We talk about / our interests / together.',jp:'私たちは話します / 興味について / いっしょに'},{en:'Finally, / I understand / my classmates / better.',jp:'ついに / 私は理解します / クラスメートを / もっとよく'},{en:'The activity is / simple / but interesting.',jp:'その活動は〜です / 簡単 / しかしおもしろい'},{en:'I want to discover / more / about my friends.',jp:'私は発見したいです / もっと / 友達について'}],
questions:[{prompt:'1. クラスでは何について話しますか。本文から英語で答えなさい。',answer:'a new side of our classmates',evidence:'We talk about a new side of our classmates.',evidenceJp:'私たちはクラスメートの新しい一面について話します。',reason:'talk about の後ろが a new side of our classmates です。'},{prompt:'2. 友達は何が好きですか。本文から英語で答えなさい。',answer:'a musical',evidence:'My friend likes a musical.',evidenceJp:'私の友達はミュージカルが好きです。',reason:'likes の目的語が a musical です。'},{prompt:'3. 友達は何になりたいですか。本文から英語で答えなさい。',answer:'an actor',evidence:'He wants to be an actor someday.',evidenceJp:'彼はいつか俳優になりたいと思っています。',reason:'be の後ろが an actor です。'},{prompt:'4. 話し手は何を発見しますか。本文から英語で答えなさい。',answer:'a new side of him',evidence:'I discover a new side of him.',evidenceJp:'私は彼の新しい一面を発見します。',reason:'discover の目的語が a new side of him です。'},{prompt:'5. 最後に話し手は誰をもっとよく理解しますか。本文から英語で答えなさい。',answer:'my classmates',evidence:'Finally, I understand my classmates better.',evidenceJp:'ついに、私はクラスメートのことをもっとよく理解します。',reason:'understand の目的語が my classmates です。'}],
allowedWords:[['finally / actor / discover / musical / side','Unit 0: v7 canonical Sheet IDs 1651-1655'],['today / class / activity / talk about / new / classmate / friend / like / want to / someday / know / before / another / music / drawing / show / picture / interest / together / understand / better / simple / interesting / more','G1-G2 cumulative']],
auditNote:'最新v7正本Unit0（Sheet ID1651〜1655）を直接照合。finally / actor / discover / musical / sideをクラスメートの新しい一面を知る活動に統合。Unit1の現在完了経験用 been / ever / never / have been to 等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 1-1']={
id:'V10-NH-G3-U1-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 1-1',level:'HOP',title:'Places I Have Visited',
sentences:["I've been to Kyoto once.","I've been to Osaka twice.",'I have been to a small museum too.','I have never been to Hokkaido.','My friend has been to Kyoto too.','We talk about places in Japan.','Kyoto has many old buildings.','Osaka has many interesting places.','I show my friend one picture from Kyoto.','We want to travel together someday.','I write about my experience in my notebook.','Travel can help us discover a new side of Japan.'],
fullTranslation:'「私は京都に1度行ったことがあります。大阪には2度行ったことがあります。小さな博物館にも行ったことがあります。北海道には一度も行ったことがありません。私の友達も京都に行ったことがあります。私たちは日本の場所について話します。京都には古い建物がたくさんあります。大阪にはおもしろい場所がたくさんあります。私は友達に京都での写真を1枚見せます。私たちはいつかいっしょに旅行したいです。私は自分の経験をノートに書きます。旅行は日本の新しい一面を発見する助けになります。」',
slashRows:[{en:"I've been to / Kyoto / once.",jp:'私は行ったことがあります / 京都に / 1度'},{en:"I've been to / Osaka / twice.",jp:'私は行ったことがあります / 大阪に / 2度'},{en:'I have been to / a small museum / too.',jp:'私は行ったことがあります / 小さな博物館に / も'},{en:'I have never been to / Hokkaido.',jp:'私は一度も行ったことがありません / 北海道に'},{en:'My friend has been to / Kyoto / too.',jp:'私の友達も行ったことがあります / 京都に / も'},{en:'We talk about / places / in Japan.',jp:'私たちは話します / 場所について / 日本の'},{en:'Kyoto has / many old buildings.',jp:'京都にはあります / 多くの古い建物が'},{en:'Osaka has / many interesting places.',jp:'大阪にはあります / 多くのおもしろい場所が'},{en:'I show / my friend / one picture / from Kyoto.',jp:'私は見せます / 友達に / 1枚の写真を / 京都での'},{en:'We want to travel / together / someday.',jp:'私たちは旅行したいです / いっしょに / いつか'},{en:'I write about / my experience / in my notebook.',jp:'私は書きます / 自分の経験について / ノートに'},{en:'Travel can help / us / discover / a new side of Japan.',jp:'旅行は助けになります / 私たちが / 発見する / 日本の新しい一面を'}],
questions:[{prompt:'1. 京都には何度行ったことがありますか。本文から英語で答えなさい。',answer:'once',evidence:"I've been to Kyoto once.",evidenceJp:'私は京都に1度行ったことがあります。',reason:'回数を表す語が once です。'},{prompt:'2. 大阪には何度行ったことがありますか。本文から英語で答えなさい。',answer:'twice',evidence:"I've been to Osaka twice.",evidenceJp:'大阪には2度行ったことがあります。',reason:'回数を表す語が twice です。'},{prompt:'3. 話し手は北海道に行ったことがありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I have never been to Hokkaido.',evidenceJp:'北海道には一度も行ったことがありません。',reason:'never been to とあるので No です。'},{prompt:'4. 友達もどこに行ったことがありますか。本文から英語で答えなさい。',answer:'Kyoto',evidence:'My friend has been to Kyoto too.',evidenceJp:'私の友達も京都に行ったことがあります。',reason:'been to の後ろが Kyoto です。'},{prompt:'5. 旅行は何を発見する助けになりますか。本文から英語で答えなさい。',answer:'a new side of Japan',evidence:'Travel can help us discover a new side of Japan.',evidenceJp:'旅行は日本の新しい一面を発見する助けになります。',reason:'discover の目的語が a new side of Japan です。'}],
allowedWords:[["been / I've / never ~ / once / have been to ~ / twice",'Unit 1 Part1,2 shared pool first half: v7 canonical Sheet IDs 1656-1661'],['Kyoto / Osaka / Hokkaido','proper nouns'],['museum / friend / talk about / place / Japan / old / building / interesting / show / picture / want to / travel / together / someday / write about / experience / notebook / can / help / discover / side','G1-G2/Unit0 cumulative']],
auditNote:'最新v7正本Unit1 Part1,2共通プール（Sheet ID1656〜1667）の前半ID1656〜1661をUnit1-1へ割り当て。been / I’ve / never / once / have been to / twiceを現在完了の経験を表す文脈に統合。後半のfashion / haven’t / regional / hear / ever / foreignerは先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 1-2']={
id:'V10-NH-G3-U1-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 1-2',level:'HOP',title:'Japanese Fashion and a Visitor',
sentences:['A foreigner visits our school today.','We talk about Japanese fashion.','I hear about regional fashion from him.','He has been to many places in Japan.','I ask, “Have you ever been to Kyoto?”','He says, “Yes, twice.”','I say, “I have never been there.”','I haven’t seen that regional style before.','He shows us a picture of the style.','The picture is colorful and interesting.','We talk about Japanese culture too.','I want to learn more from visitors.'],
fullTranslation:'「今日、外国人が私たちの学校を訪れます。私たちは日本のファッションについて話します。私は彼から地方のファッションについて聞きます。彼は日本の多くの場所に行ったことがあります。私は『今まで京都に行ったことがありますか』とたずねます。彼は『はい、2度あります』と言います。私は『私はそこに一度も行ったことがありません』と言います。私はその地方のスタイルを前に見たことがありません。彼は私たちにそのスタイルの写真を見せます。その写真は色鮮やかでおもしろいです。私たちは日本文化についても話します。私は訪問者からもっと学びたいです。」',
slashRows:[{en:'A foreigner / visits / our school / today.',jp:'外国人が / 訪れます / 私たちの学校を / 今日'},{en:'We talk about / Japanese fashion.',jp:'私たちは話します / 日本のファッションについて'},{en:'I hear about / regional fashion / from him.',jp:'私は聞きます / 地方のファッションについて / 彼から'},{en:'He has been to / many places / in Japan.',jp:'彼は行ったことがあります / 多くの場所に / 日本の'},{en:'I ask, / “Have you ever been to Kyoto?”',jp:'私はたずねます / 「今まで京都に行ったことがありますか」'},{en:'He says, / “Yes, twice.”',jp:'彼は言います / 「はい、2度あります」'},{en:'I say, / “I have never been there.”',jp:'私は言います / 「私はそこに一度も行ったことがありません」'},{en:'I haven’t seen / that regional style / before.',jp:'私は見たことがありません / その地方のスタイルを / 前に'},{en:'He shows / us / a picture / of the style.',jp:'彼は見せます / 私たちに / 写真を / そのスタイルの'},{en:'The picture is / colorful and interesting.',jp:'その写真は〜です / 色鮮やかでおもしろい'},{en:'We talk about / Japanese culture / too.',jp:'私たちは話します / 日本文化について / も'},{en:'I want to learn / more / from visitors.',jp:'私は学びたいです / もっと / 訪問者から'}],
questions:[{prompt:'1. 誰が学校を訪れますか。本文から英語で答えなさい。',answer:'a foreigner',evidence:'A foreigner visits our school today.',evidenceJp:'今日、外国人が私たちの学校を訪れます。',reason:'visits の主語が A foreigner です。'},{prompt:'2. 何について話しますか。本文から英語で答えなさい。',answer:'Japanese fashion',evidence:'We talk about Japanese fashion.',evidenceJp:'私たちは日本のファッションについて話します。',reason:'talk about の後ろが Japanese fashion です。'},{prompt:'3. 話し手は何について聞きますか。本文から英語で答えなさい。',answer:'regional fashion',evidence:'I hear about regional fashion from him.',evidenceJp:'私は彼から地方のファッションについて聞きます。',reason:'hear about の後ろが regional fashion です。'},{prompt:'4. 外国人は京都に何度行ったことがありますか。本文から英語で答えなさい。',answer:'twice',evidence:'He says, “Yes, twice.”',evidenceJp:'彼は「はい、2度あります」と言います。',reason:'回数を表す語が twice です。'},{prompt:'5. 話し手は地方のスタイルを前に見たことがありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I haven’t seen that regional style before.',evidenceJp:'私はその地方のスタイルを前に見たことがありません。',reason:'haven’t seen とあるので No です。'}],
allowedWords:[['fashion / haven’t / regional / hear / ever / foreigner','Unit 1 Part1,2 shared pool second half: v7 canonical Sheet IDs 1662-1667'],['been / never / have been to / twice','Unit1-1 cumulative'],['school / today / Japanese / from / many / place / Japan / ask / say / there / seen / before / show / picture / style / colorful / interesting / culture / want to / learn / more / visitor','G1-G2 cumulative']],
auditNote:'最新v7正本Unit1 Part1,2共通プール後半（Sheet ID1662〜1667）をUnit1-2へ割り当て。fashion / haven’t / regional / hear / ever / foreignerを訪問者との日本文化交流に統合。Read and Think1のanimation / quality / global / delicate / drawing等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 1-3']={
id:'V10-NH-G3-U1-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 1-3',level:'HOP',title:'Why Japanese Animation Is Popular',
sentences:['Japanese animation is a global genre.','Children and adults enjoy it.','An adventure story can make people excited.','In addition, animation can have a positive message.','The quality of a story is important.','The quality of drawing is important too.','A delicate drawing can match a quiet scene.','Some animation uses a simple drawing style.','Other animation uses a different genre.','Good stories can go global.','People around the world enjoy Japanese animation.','I think its quality is one reason for its popularity.'],
fullTranslation:'「日本のアニメーションは世界的なジャンルです。子どもも大人もそれを楽しみます。冒険の物語は人々をわくわくさせることができます。さらに、アニメーションには前向きなメッセージがあることがあります。物語の質は大切です。絵の質も大切です。繊細な絵は静かな場面と調和することができます。簡単な絵のスタイルを使うアニメーションもあります。別のジャンルを使うアニメーションもあります。よい物語は世界的になることができます。世界中の人々が日本のアニメーションを楽しみます。私はその質が人気の理由の1つだと思います。」',
slashRows:[{en:'Japanese animation is / a global genre.',jp:'日本のアニメーションは〜です / 世界的なジャンル'},{en:'Children and adults / enjoy / it.',jp:'子どもと大人は / 楽しみます / それを'},{en:'An adventure story / can make / people / excited.',jp:'冒険の物語は / 〜にできます / 人々を / わくわくした状態に'},{en:'In addition, / animation can have / a positive message.',jp:'さらに / アニメーションにはあることがあります / 前向きなメッセージが'},{en:'The quality / of a story / is important.',jp:'質は / 物語の / 大切です'},{en:'The quality / of drawing / is important / too.',jp:'質は / 絵の / 大切です / も'},{en:'A delicate drawing / can match / a quiet scene.',jp:'繊細な絵は / 調和できます / 静かな場面と'},{en:'Some animation / uses / a simple drawing style.',jp:'いくつかのアニメーションは / 使います / 簡単な絵のスタイルを'},{en:'Other animation / uses / a different genre.',jp:'別のアニメーションは / 使います / 別のジャンルを'},{en:'Good stories / can go / global.',jp:'よい物語は / 〜になれます / 世界的に'},{en:'People around the world / enjoy / Japanese animation.',jp:'世界中の人々は / 楽しみます / 日本のアニメーションを'},{en:'I think / its quality is / one reason / for its popularity.',jp:'私は思います / その質が〜だと / 1つの理由 / 人気の'}],
questions:[{prompt:'1. 日本のアニメーションはどのようなジャンルですか。本文から英語で1語抜き出しなさい。',answer:'global',evidence:'Japanese animation is a global genre.',evidenceJp:'日本のアニメーションは世界的なジャンルです。',reason:'genre を説明する語が global です。'},{prompt:'2. 誰がアニメーションを楽しみますか。本文から英語で答えなさい。',answer:'children and adults',evidence:'Children and adults enjoy it.',evidenceJp:'子どもも大人もそれを楽しみます。',reason:'enjoy の主語が Children and adults です。'},{prompt:'3. 冒険の物語は人々をどのような状態にできますか。本文から英語で1語抜き出しなさい。',answer:'excited',evidence:'An adventure story can make people excited.',evidenceJp:'冒険の物語は人々をわくわくさせることができます。',reason:'make A B の B が excited です。'},{prompt:'4. 繊細な絵は何と調和できますか。本文から英語で答えなさい。',answer:'a quiet scene',evidence:'A delicate drawing can match a quiet scene.',evidenceJp:'繊細な絵は静かな場面と調和することができます。',reason:'match の目的語が a quiet scene です。'},{prompt:'5. 話し手は何が人気の理由の1つだと思っていますか。本文から英語で答えなさい。',answer:'its quality',evidence:'I think its quality is one reason for its popularity.',evidenceJp:'私はその質が人気の理由の1つだと思います。',reason:'reason の内容として its quality が示されています。'}],
allowedWords:[['make A B / animation / match / adventure / in addition / adult / go / positive / quality / global / genre / delicate / drawing','Unit 1 Read and Think1: v7 canonical Sheet IDs 1668-1680'],['Japanese / child / enjoy / story / can / people / excited / message / important / quiet / scene / some / use / simple / style / other / different / good / around the world / think / reason / popularity','G1-G2/Unit0-1 cumulative']],
auditNote:'最新v7正本Unit1 Read and Think1（Sheet ID1668〜1680）を直接照合。make A B / animation / match / adventure / in addition / adult / go / positive / quality / global / genre / delicate / drawingを、日本のアニメーションの特徴を説明する文章に統合。Read and Think2のscroll / roots / influence / technique等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 1-4']={
id:'V10-NH-G3-U1-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 1-4',level:'HOP',title:'Old Art and Modern Animation',
sentences:['A picture scroll has a long history in Japan.','It is said that its roots are in old Japanese art.','A drawing can express movement.','One drawing can link to the next drawing.','This technique can show movement clearly.','Modern animation can take advantage of this technique.','Old art can influence modern animation.','We should not ignore the existence of this link.','The link is not entirely clear.','The advantage is that one drawing can show movement.','Different people have different taste in art.','This history helps us understand Japanese animation.'],
fullTranslation:'「絵巻物には日本で長い歴史があります。その起源は古い日本美術にあると言われています。絵は動きを表現することができます。1つの絵は次の絵へつながることができます。この手法は動きをはっきり示すことができます。現代のアニメーションはこの手法を利用することができます。古い美術は現代のアニメーションに影響を及ぼすことがあります。私たちはこのつながりの存在を無視すべきではありません。そのつながりは完全には明らかではありません。利点は、1枚の絵で動きを示せることです。人によって美術の好みは異なります。この歴史は日本のアニメーションを理解する助けになります。」',
slashRows:[{en:'A picture scroll has / a long history / in Japan.',jp:'絵巻物にはあります / 長い歴史が / 日本で'},{en:'It is said that / its roots are / in old Japanese art.',jp:'〜と言われています / その起源は〜だと / 古い日本美術に'},{en:'A drawing can express / movement.',jp:'絵は表現できます / 動きを'},{en:'One drawing can link / to the next drawing.',jp:'1つの絵はつながることができます / 次の絵へ'},{en:'This technique can show / movement / clearly.',jp:'この手法は示せます / 動きを / はっきりと'},{en:'Modern animation can take advantage of / this technique.',jp:'現代のアニメーションは利用できます / この手法を'},{en:'Old art can influence / modern animation.',jp:'古い美術は影響を及ぼすことがあります / 現代のアニメーションに'},{en:'We should not ignore / the existence / of this link.',jp:'私たちは無視すべきではありません / 存在を / このつながりの'},{en:'The link is / not entirely clear.',jp:'そのつながりは〜です / 完全には明らかでない'},{en:'The advantage is / that one drawing can show movement.',jp:'利点は〜です / 1枚の絵で動きを示せること'},{en:'Different people have / different taste / in art.',jp:'人によってあります / 異なる好みが / 美術に'},{en:'This history helps / us / understand / Japanese animation.',jp:'この歴史は助けます / 私たちが / 理解するのを / 日本のアニメーションを'}],
questions:[{prompt:'1. 何に長い歴史がありますか。本文から英語で答えなさい。',answer:'a picture scroll',evidence:'A picture scroll has a long history in Japan.',evidenceJp:'絵巻物には日本で長い歴史があります。',reason:'has の主語が A picture scroll です。'},{prompt:'2. 起源はどこにあると言われていますか。本文から英語で答えなさい。',answer:'in old Japanese art',evidence:'It is said that its roots are in old Japanese art.',evidenceJp:'その起源は古い日本美術にあると言われています。',reason:'roots の場所を表す部分が in old Japanese art です。'},{prompt:'3. 絵は何を表現できますか。本文から英語で答えなさい。',answer:'movement',evidence:'A drawing can express movement.',evidenceJp:'絵は動きを表現することができます。',reason:'express の目的語が movement です。'},{prompt:'4. 現代のアニメーションは何を利用できますか。本文から英語で答えなさい。',answer:'this technique',evidence:'Modern animation can take advantage of this technique.',evidenceJp:'現代のアニメーションはこの手法を利用することができます。',reason:'take advantage of の後ろが this technique です。'},{prompt:'5. 古い美術は何に影響を及ぼすことがありますか。本文から英語で答えなさい。',answer:'modern animation',evidence:'Old art can influence modern animation.',evidenceJp:'古い美術は現代のアニメーションに影響を及ぼすことがあります。',reason:'influence の目的語が modern animation です。'}],
allowedWords:[['taste / draw-drew-drawn / scroll / It is said that ~ / roots / link / movement / influence / existence / ignore / entirely / express / advantage / technique / take advantage of ~','Unit 1 Read and Think2: v7 canonical Sheet IDs 1681-1695'],['you / around','Unit1 textbook-body canonical Sheet IDs 1696-1697'],['picture / long / history / Japan / old / Japanese / art / drawing / can / next / show / clearly / modern / animation / should / not / clear / different / people / help / understand','G1-G2/Unit0-1-3 cumulative']],
auditNote:'最新v7正本Unit1 Read and Think2（Sheet ID1681〜1695）と教科書本文補助語を直接照合。taste / scroll / It is said that / roots / link / movement / influence / existence / ignore / entirely / express / advantage / technique / take advantage ofを、絵巻物と現代アニメーションの関係を説明する文章に統合。Unit2のalready / just / yet / since / recycle等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
