// Reference/minimum-rule slash audit passages 071-080.
(function(){
 const PASS='PASS_REFERENCE_20260820';
 function setAudit(data,section,rows,n){const p=data&&data[section];if(!p)throw new Error('Missing reference passage '+n+': '+section);if(rows.length!==(p.sentences||[]).length)throw new Error('Row mismatch '+n);for(let i=0;i<rows.length;i++){const e=String(rows[i].en||'').replace(/\s*\/\s*/g,' ').replace(/\s+/g,' ').trim(),s=String(p.sentences[i]||'').replace(/\s+/g,' ').trim();if(e!==s)throw new Error('English mismatch '+n+'#'+(i+1)+': '+e+' <> '+s);const ec=String(rows[i].en||'').split(/\s*\/\s*/).filter(Boolean).length,jc=String(rows[i].jp||'').split(/\s*\/\s*/).filter(Boolean).length;if(ec!==jc)throw new Error('EN/JP chunks '+n+'#'+(i+1)+' '+ec+'/'+jc)}p.slashRows=rows;p.slashReadingVersion='reference-book-minimum-rules-20260820';p.slashReferenceAudit=PASS;p.slashReferencePassageNo=n}
 const d=window.V10_PASSAGES_G2_SS||{};
 setAudit(d,'PROGRAM 1-2',[
  {en:'Tomorrow, / I will leave this town.',jp:'明日 / 私はこの町を出ます'},{en:'I am a bit worried.',jp:'私は少し心配です。'},{en:'My friend / and I are / at the local park.',jp:'私の友達 / そして私はいます / 地元の公園に'},{en:'This park is special / to us.',jp:'この公園は特別です / 私たちにとって'},{en:'We often talked here / after school.',jp:'私たちはよくここで話しました / 放課後に'},{en:'“Take care.”',jp:'「気をつけてね。」'},{en:'“Thank you.”',jp:'「ありがとう。」'},{en:'I won’t forget my friends.',jp:'私は友達を忘れません。'},{en:'I won’t forget this town, / either.',jp:'私はこの町を忘れません / 〜もまた'},{en:'“I’ll text you.”',jp:'「メールするね。」'},{en:'“You can text me, / too.”',jp:'「あなたも私にメールしてね / 〜もまた」'},{en:'We will keep / in touch.',jp:'私たちは保ちます / 連絡を'},{en:'I hope my friend will be fine.',jp:'友達が元気でいてくれることを願っています。'},{en:'I will visit this park again someday.',jp:'私はいつかまたこの公園を訪れます。'}
 ],71);
 setAudit(d,'PROGRAM 1-3',[
  {en:'I am overseas now.',jp:'私は今、海外にいます。'},{en:'Today is my first day / at my new school.',jp:'今日は私の初日です / 新しい学校での'},{en:'My class has a short quiz.',jp:'私のクラスでは短い小テストがあります。'},{en:'I am a bit worried.',jp:'私は少し心配です。'},{en:'“Why don’t you take a short break?”',jp:'「少し休憩したらどう？」'},{en:'A student / near me smiles.',jp:'生徒が / 私の近くのほほえみます'},{en:'“Sounds nice. Thank you.”',jp:'「いいね。ありがとう。」'},{en:'We read our books / during the break.',jp:'私たちは本を読みます / 休憩中に'},{en:'We talk / about the quiz.',jp:'私たちは話します / 小テストについて'},{en:'The student helps me.',jp:'その生徒は私を助けてくれます。'},{en:'Maybe I can make a new friend.',jp:'もしかすると新しい友達ができるかもしれません。'},{en:'I won’t cry.',jp:'私は泣きません。'},{en:'I’ll do my best.',jp:'私はできるだけ頑張ります。'}
 ],72);
 setAudit(d,'PROGRAM 2-1',[
  {en:'I heard / about a baseball project / in Africa.',jp:'私は聞きました / 野球プロジェクトについて / アフリカの'},{en:'The project promotes baseball / for children / in a city.',jp:'そのプロジェクトは野球を広めます / 子どもたちのために / ある町で'},{en:'A coach is very passionate / about the project.',jp:'あるコーチはとても情熱を持っています / そのプロジェクトについて'},{en:'The coach teaches baseball / after school.',jp:'そのコーチは野球を教えます / 放課後に'},{en:'Children practice together.',jp:'子どもたちはいっしょに練習します。'},{en:'Games take place / around the city.',jp:'試合が行われます / 町のあちこちで'},{en:'The work is not easy.',jp:'その活動は簡単ではありません。'},{en:'Some days are difficult.',jp:'大変な日もあります。'},{en:'Many people root / for the children.',jp:'多くの人が応援しています / 子どもたちを'},{en:'I am interested / in the project.',jp:'私は興味があります / そのプロジェクトに'},{en:'I hope the project will be successful.',jp:'私はそのプロジェクトが成功することを願っています。'},{en:'Baseball can bring people together.',jp:'野球は人々を結びつけることができます。'}
 ],73);
 setAudit(d,'PROGRAM 2-2',[
  {en:'Today, / I visit a university.',jp:'今日 / 私は大学を訪れます'},{en:'I meet a baseball coach there.',jp:'私はそこで野球のコーチに会います。'},{en:'The coach works / in a national program.',jp:'そのコーチは活動しています / 全国的なプログラムで'},{en:'The program is / about baseball / and peace.',jp:'そのプログラムは〜です / 野球について / そして平和について'},{en:'The coach tells me / about the program.',jp:'そのコーチは私に話します / プログラムについて'},{en:'People play baseball together / in the program.',jp:'人々はいっしょに野球をします / そのプログラムで'},{en:'When people play together, / they can be friends.',jp:'人々がいっしょにプレーすると / 友達になることができます'},{en:'The coach believes sport can create peace.',jp:'そのコーチはスポーツが平和を生み出せると信じています。'},{en:'I am interested / in the program.',jp:'私は興味があります / そのプログラムに'},{en:'We talk / about baseball / and peace.',jp:'私たちは話します / 野球について / そして平和について'},{en:'I want / to join the program someday.',jp:'私は望んでいます / いつかそのプログラムに参加することを'},{en:'I hope many people will be interested / in it.',jp:'私は多くの人が興味を持つことを願っています / それに'}
 ],74);
 setAudit(d,'PROGRAM 2-3',[
  {en:'Our baseball project has a game today.',jp:'私たちの野球プロジェクトでは今日、試合があります。'},{en:'Our goal is / to play together / and learn / from the game.',jp:'私たちの目標は〜です / いっしょにプレーすること / そして学ぶこと / 試合から'},{en:'The game is difficult.',jp:'その試合は難しいです。'},{en:'One player has trouble.',jp:'1人の選手が困ります。'},{en:'We help each other.',jp:'私たちは助け合います。'},{en:'A player hits a home run.',jp:'ある選手がホームランを打ちます。'},{en:'Everyone is happy.',jp:'みんなうれしいです。'},{en:'After the game, / we talk together.',jp:'試合のあと / 私たちはいっしょに話します'},{en:'We learn / through the game.',jp:'私たちは学びます / その試合を通して'},{en:'In fact, / sport can have a positive effect.',jp:'実際 / スポーツにはよい効果があります'},{en:'Sport can foster peace.',jp:'スポーツは平和を育むことができます。'},{en:'We believe / in the power / of sport.',jp:'私たちは信じています / 力を / スポーツの'},{en:'I want / to remember this idea.',jp:'私は望んでいます / この考えを覚えておくことを'}
 ],75);
 setAudit(d,'PROGRAM 3-1',[
  {en:'Today, / I am / at an American festival.',jp:'今日 / 私はいます / アメリカの祭りに'},{en:'I wait / for my friend.',jp:'私は待ちます / 友達を'},{en:'Many people are / at the festival.',jp:'多くの人がいます / 祭りに'},{en:'My friend is here now.',jp:'友達が今ここにいます。'},{en:'We eat a light meal together.',jp:'私たちはいっしょに軽い食事をします。'},{en:'The taste is very good.',jp:'その味はとてもよいです。'},{en:'We listen / to music.',jp:'私たちは聞きます / 音楽を'},{en:'We talk / about the festival.',jp:'私たちは話します / 祭りについて'},{en:'I am interested / in American culture.',jp:'私は興味があります / アメリカの文化に'},{en:'The festival is very exciting.',jp:'その祭りはとてもわくわくします。'},{en:'I want / to visit the festival again.',jp:'私は望んでいます / またその祭りを訪れることを'},{en:'It is a special day / for me.',jp:'それは特別な一日です / 私にとって'}
 ],76);
 setAudit(d,'PROGRAM 3-2',[
  {en:'Today, / we sell handmade cards / at the festival.',jp:'今日 / 私たちは手作りのカードを売ります / 祭りで'},{en:'The cards are / for our project.',jp:'そのカードは〜です / 私たちのプロジェクトのための'},{en:'Some children make the cards themselves.',jp:'何人かの子どもたちは自分たちでカードを作ります。'},{en:'Here is a thin card.',jp:'ここに薄いカードがあります。'},{en:'It is light / and beautiful.',jp:'それは軽いです / そして美しいです'},{en:'I make a card, / too.',jp:'私もカードを作ります / 〜もまた'},{en:'Many people buy the cards.',jp:'多くの人がカードを買います。'},{en:'We earn money / for our project.',jp:'私たちはお金を得ます / 私たちのプロジェクトのために'},{en:'I like the children’s work.',jp:'私は子どもたちの作品が好きです。'},{en:'The festival is special / for me.',jp:'その祭りは特別です / 私にとって'},{en:'I look forward / to visiting the festival again.',jp:'私は楽しみにしています / また祭りを訪れることを'}
 ],77);
 setAudit(d,'PROGRAM 3-3',[
  {en:'At the festival, / I meet a Dutch student.',jp:'祭りで / 私はオランダ人の生徒に会います'},{en:'The student is / from the Netherlands.',jp:'その生徒は〜出身です / オランダ'},{en:'The student has a job / at a charity stall.',jp:'その生徒には仕事があります / 慈善活動の屋台で'},{en:'“Can you show me this bowl?”',jp:'「このおわんを見せてもらえますか。」'},{en:'“Sure.”',jp:'「もちろん。」'},{en:'The bowl is handmade.',jp:'そのおわんは手作りです。'},{en:'Each bowl is light.',jp:'どのおわんも軽いです。'},{en:'I can carry it easily.',jp:'私は簡単にそれを持ち運べます。'},{en:'People buy the handmade bowls.',jp:'人々は手作りのおわんを買います。'},{en:'The stall earns money.',jp:'その屋台はお金を得ます。'},{en:'At the end, / the students donate the money.',jp:'最後に / 生徒たちはそのお金を寄付します'},{en:'I like their work.',jp:'私は彼らの活動が好きです。'},{en:'I want / to visit this festival again.',jp:'私は望んでいます / またこの祭りを訪れることを'}
 ],78);
 setAudit(d,'PROGRAM 4-1',[
  {en:'Today, / the sky is clear.',jp:'今日 / 空は晴れています'},{en:'My friend / and I go hiking.',jp:'私の友達 / そして私はハイキングに行きます'},{en:'My friend can guide me.',jp:'友達は私を案内できます。'},{en:'We walk / in a forest.',jp:'私たちは歩きます / 森の中を'},{en:'I see a footprint.',jp:'私は足跡を見つけます。'},{en:'“Is it a deer footprint?”',jp:'「鹿の足跡ですか。」'},{en:'“Yes, / it is.”',jp:'「はい / そうです」'},{en:'Actually, / we see a deer / near us.',jp:'実際 / 私たちは鹿を見ます / 私たちの近くに'},{en:'I am glad / to see it.',jp:'私はうれしいです / それを見ることができて'},{en:'We watch the deer / for a short time.',jp:'私たちはその鹿を見ます / 少しの間'},{en:'After the hike, / we talk / about the footprint / and the deer.',jp:'ハイキングのあと / 私たちは話します / 足跡について / そして鹿について'},{en:'I want / to go hiking again.',jp:'私は望んでいます / またハイキングに行くことを'}
 ],79);
 setAudit(d,'PROGRAM 4-2',[
  {en:'We are / in a forest today.',jp:'私たちはいます / 今日、森に'},{en:'Our guide tells us an important rule.',jp:'ガイドが大切なルールを教えてくれます。'},{en:'First of all, / we must protect the forest.',jp:'まず何より / 私たちは森を守らなければなりません'},{en:'We must not leave garbage.',jp:'ごみを残してはいけません。'},{en:'We must keep the forest clean.',jp:'森をきれいに保たなければなりません。'},{en:'We must help each other.',jp:'私たちは助け合わなければなりません。'},{en:'If we have trouble, / we should talk / to our guide.',jp:'困ったことがあれば / 私たちは話すべきです / ガイドに'},{en:'The forest is quiet.',jp:'森は静かです。'},{en:'We should walk carefully / and enjoy it.',jp:'私たちは注意して歩くべきです / そして森を楽しむべきです'},{en:'This rule helps us protect the forest.',jp:'このルールは私たちが森を守るのに役立ちます。'},{en:'I am glad / to learn the rule.',jp:'私はうれしいです / そのルールを学べて'}
 ],80);
 window.V10_REFERENCE_SLASH_AUDIT={version:'2026-08-20',passagesAudited:80,total:168,lastCompleted:80,minimumRuleImageConfirmed:true};
})();