window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 8-1'] = {
 id:'V10-NH-G1-U8-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 8-1',level:'HOP',title:'A Volunteer in Kenya',
 sentences:['This is a volunteer.','He is from Kenya.','Does he teach children?','Yes, he does.','Are the children in need?','Yes, they are.','Does he respect the children?','Yes, he does.','Do you respect him?','Yes, I do.','I want to become a volunteer.','I want to do my best.','Great!'],
 fullTranslation:'こちらはボランティアです。彼はケニア出身です。「彼は子どもたちに教えますか。」「はい、教えます。」「その子どもたちは困っていますか。」「はい、困っています。」「彼はその子どもたちを尊重していますか。」「はい、しています。」「あなたは彼を尊敬していますか。」「はい、しています。」「私はボランティアになりたいです。」「最善を尽くしたいです。」「いいね！」',
 slashRows:[{en:'This is / a volunteer.',jp:'こちらは〜です / ボランティア'},{en:'He is from / Kenya.',jp:'彼は〜出身です / ケニア'},{en:'Does he teach / children?',jp:'彼は教えますか / 子どもたちに'},{en:'Yes, / he does.',jp:'はい / 教えます'},{en:'Are the children / in need?',jp:'その子どもたちは〜ですか / 困っている状態に'},{en:'Yes, / they are.',jp:'はい / そうです'},{en:'Does he respect / the children?',jp:'彼は尊重しますか / その子どもたちを'},{en:'Yes, / he does.',jp:'はい / します'},{en:'Do you respect / him?',jp:'あなたは尊敬しますか / 彼を'},{en:'Yes, / I do.',jp:'はい / します'},{en:'I want to become / a volunteer.',jp:'私はなりたいです / ボランティアに'},{en:'I want to do / my best.',jp:'私は尽くしたいです / 最善を'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. そのボランティアはどこの出身ですか。本文から英語で答えなさい。',answer:'Kenya',evidence:'He is from Kenya.',evidenceJp:'彼はケニア出身です。',reason:'from の後ろの Kenya が出身地を示しています。'},{prompt:'2. そのボランティアは誰に教えますか。本文から英語で答えなさい。',answer:'children',evidence:'Does he teach children? / Yes, he does.',evidenceJp:'彼は子どもたちに教えますか。／はい、教えます。',reason:'teach の後ろの children が教える相手です。'},{prompt:'3. その子どもたちは困っていますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Are the children in need? / Yes, they are.',evidenceJp:'その子どもたちは困っていますか。／はい、そうです。',reason:'in need かどうかの質問に Yes, they are. と答えています。'},{prompt:'4. 話し手は何になりたいですか。本文から英語で答えなさい。',answer:'a volunteer',evidence:'I want to become a volunteer.',evidenceJp:'私はボランティアになりたいです。',reason:'become の後ろの a volunteer がなりたいものです。'},{prompt:'5. 話し手は何をしたいと言っていますか。本文中の表現を使って英語で答えなさい。',answer:'do my best',evidence:'I want to do my best.',evidenceJp:'私は最善を尽くしたいです。',reason:'Unit 8-1で登録された do one’s best を my に合わせて使った表現です。'}],
 allowedWords:[['volunteer','Unit 8-1'],['Kenya','Unit 8-1'],['teach','Unit 8-1'],['respect','Unit 8-1'],['children','Unit 8-1 exact plural form'],['become','Unit 8-1'],['in need','Unit 8-1 phrase'],['do one’s best','Unit 8-1 phrase'],['does','Unit 5-2 cumulative grammar'],['him','Unit 6-1 cumulative object pronoun'],['want to','Unit 1-1 cumulative'],['great','Unit 1-2 cumulative'],['this / is / a / he / from / yes / are / the / they / do / you / I / my','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 8-1をid2402〜2418まで照合し、id2419からUnit 8-2へ切り替わることを確認。volunteer / need / best / Africa / Kenya / teach / try / become / respect / ethnic / children / child / country / cousin / always / in need / do one’s best が登録されている。childrenは正本にchildの複数形として明示登録されているためそのまま使用。teaches / respects等の肯定三単現形は自動生成せず、Unit 5-2で解禁済みのDoes he + 原形を使用。未使用の語は新出語消化のためだけには詰め込まない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 8-2'] = {
 id:'V10-NH-G1-U8-2-001',textbook:'ニューホライズン',grade:'1',section:'Unit 8-2',level:'HOP',title:'Two Straws',
 sentences:['This is a reusable straw.','Is it plastic?','Yes, it is.','Do you use this straw?','Yes, I do.','This is a paper straw.','Do you use the paper straw, too?','Yes, I do.','I want to reduce waste.','Really?','Of course.','Great!'],
 fullTranslation:'「これは再利用できるストローです。」「プラスチック製ですか。」「はい、そうです。」「このストローを使いますか。」「はい、使います。」「こちらは紙のストローです。」「紙のストローも使いますか。」「はい、使います。」「ごみを減らしたいです。」「本当に？」「もちろん。」「いいね！」',
 slashRows:[{en:'This is / a reusable straw.',jp:'これは〜です / 再利用できるストロー'},{en:'Is it / plastic?',jp:'それは〜ですか / プラスチック製'},{en:'Yes, / it is.',jp:'はい / そうです'},{en:'Do you use / this straw?',jp:'あなたは使いますか / このストローを'},{en:'Yes, / I do.',jp:'はい / 使います'},{en:'This is / a paper straw.',jp:'こちらは〜です / 紙のストロー'},{en:'Do you use / the paper straw, too?',jp:'あなたも使いますか / その紙のストローを'},{en:'Yes, / I do.',jp:'はい / 使います'},{en:'I want to reduce / waste.',jp:'私は減らしたいです / ごみを'},{en:'Really?',jp:'本当に？'},{en:'Of course.',jp:'もちろん。'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. 最初のストローは再利用できますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'This is a reusable straw.',evidenceJp:'これは再利用できるストローです。',reason:'reusable が「再利用できる」という意味なので Yes です。'},{prompt:'2. 最初のストローは何製ですか。本文から英語で1語抜き出しなさい。',answer:'plastic',evidence:'Is it plastic? / Yes, it is.',evidenceJp:'プラスチック製ですか。／はい、そうです。',reason:'plastic かどうかの質問に Yes, it is. と答えています。'},{prompt:'3. 2つ目のストローは何製ですか。本文から英語で1語抜き出しなさい。',answer:'paper',evidence:'This is a paper straw.',evidenceJp:'こちらは紙のストローです。',reason:'paper が straw を修飾し、紙製であることを示しています。'},{prompt:'4. 話し手は紙のストローも使いますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Do you use the paper straw, too? / Yes, I do.',evidenceJp:'紙のストローも使いますか。／はい、使います。',reason:'too を含む質問に Yes, I do. と答えています。'},{prompt:'5. 話し手は何を減らしたいですか。本文から英語で答えなさい。',answer:'waste',evidence:'I want to reduce waste.',evidenceJp:'私はごみを減らしたいです。',reason:'reduce の目的語 waste が減らしたいものです。'}],
 allowedWords:[['paper','Unit 8-2 adjective'],['waste','Unit 8-2'],['straw','Unit 8-2'],['reduce','Unit 8-2'],['plastic','Unit 8-2 adjective'],['reusable','Unit 8-2'],['of course','Unit 8-2 phrase'],['use','Unit 6-3 cumulative'],['want to','Unit 1-1 cumulative'],['really','Unit 2-2 cumulative'],['too / great','cumulative'],['this / is / a / it / yes / do / you / I / the','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 8-2をid2419〜2433まで照合し、id2434からUnit 8-3へ切り替わることを確認。paper / waste / straw / reduce / African / plastic / original / reusable / soup / meat / pie / bean / chicken / curry / of course が登録されている。paperとplasticは正本の形容詞用法どおりstrawを修飾。食べ物語彙は環境・ストローの話に混ぜると水増しになるため未使用。未確認複数形strawsは生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};