window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 2-1']={
id:'V10-SS-G1-P2-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-1',level:'HOP',title:'My Bicycle After School',
sentences:['After school, I ride my bicycle.','I ride in my town.','My town is beautiful.','I sometimes ride with my friend.','My friend and I walk, too.','I like my bicycle very much.','I go home after school.','At home, I clean my bicycle.','I read at home.','I sometimes watch tennis at home.','I don’t watch tennis after school.','I like my town, too.','I like my bicycle and my town.'],
fullTranslation:'「放課後、私は自転車に乗ります。町の中を走ります。私の町は美しいです。ときどき友達といっしょに自転車に乗ります。友達と私は歩くこともあります。私は自分の自転車がとても好きです。放課後は家に帰ります。家では自転車をきれいにします。家で本を読みます。ときどき家でテニスを見ます。放課後にはテニスを見ません。自分の町も好きです。自転車も町も好きです。」',
slashRows:[{en:'After school, / I ride / my bicycle.',jp:'放課後 / 私は乗ります / 私の自転車に'},{en:'I ride / in my town.',jp:'私は乗ります / 私の町の中で'},{en:'My town is / beautiful.',jp:'私の町は〜です / 美しい'},{en:'I sometimes ride / with my friend.',jp:'私はときどき乗ります / 私の友達といっしょに'},{en:'My friend and I / walk, too.',jp:'私の友達と私は / 歩くこともあります'},{en:'I like / my bicycle / very much.',jp:'私は好きです / 私の自転車が / とても'},{en:'I go home / after school.',jp:'私は家に帰ります / 放課後に'},{en:'At home, / I clean / my bicycle.',jp:'家で / 私はきれいにします / 私の自転車を'},{en:'I read / at home.',jp:'私は読みます / 家で'},{en:'I sometimes watch / tennis / at home.',jp:'私はときどき見ます / テニスを / 家で'},{en:'I don’t watch / tennis / after school.',jp:'私は見ません / テニスを / 放課後に'},{en:'I like / my town, too.',jp:'私は好きです / 私の町も'},{en:'I like / my bicycle and my town.',jp:'私は好きです / 私の自転車と町が'}],
questions:[{prompt:'1. 話し手は放課後、何に乗りますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'After school, I ride my bicycle.',evidenceJp:'放課後、私は自転車に乗ります。',reason:'ride の目的語 my bicycle が乗るものです。'},{prompt:'2. 話し手の町はどのようだと書かれていますか。本文から英語で1語抜き出しなさい。',answer:'beautiful',evidence:'My town is beautiful.',evidenceJp:'私の町は美しいです。',reason:'beautiful が町の様子を表しています。'},{prompt:'3. 話し手はときどき誰と自転車に乗りますか。本文から英語で答えなさい。',answer:'my friend',evidence:'I sometimes ride with my friend.',evidenceJp:'私はときどき友達といっしょに自転車に乗ります。',reason:'with の後ろの my friend がいっしょに乗る相手です。'},{prompt:'4. 家で何をきれいにしますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'At home, I clean my bicycle.',evidenceJp:'家では自転車をきれいにします。',reason:'clean の目的語 my bicycle がきれいにするものです。'},{prompt:'5. 話し手は放課後にテニスを見ますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I don’t watch tennis after school.',evidenceJp:'私は放課後にはテニスを見ません。',reason:'don’t watch と否定しているので No です。'}],
allowedWords:[['grow / use / after / town / bicycle / flower / walk / ride / watch / read / clean / beautiful / many / sometimes / don’t / at home / very much / after school','PROGRAM 2-1: id185-202'],['friend','cumulative'],['tennis','Get Ready cumulative'],['go / home / in / with / my / it / I / is / like / and','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-1をid185〜202まで照合し、id203からPROGRAM 2-2へ切り替わることを確認。自転車での放課後と帰宅後という1日の流れに限定。初稿に混入した三単現likesは人手監査で削除し、確認済みの原形だけへ修正した。grow / use / flower / many等は新出語消化だけのためには入れていない。未確認の過去形・進行形は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 2-2']={
id:'V10-SS-G1-P2-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-2',level:'HOP',title:'My Weekend Routine',
sentences:['On the weekend, I study at home.','I study math before dinner.','I like math, but I like science, too.','After dinner, I read at home.','I sometimes watch tennis.','I ride my bicycle on the weekend.','I ride with my friend.','We like our town.','Our town is beautiful.','Before dinner, I clean my bicycle.','After dinner, I study Japanese.','I like the weekend very much.'],
fullTranslation:'「週末は家で勉強します。夕食前に数学を勉強します。数学が好きですが、理科も好きです。夕食後は家で本を読みます。ときどきテニスを見ます。週末には自転車に乗ります。友達といっしょに自転車に乗ります。私たちは自分たちの町が好きです。私たちの町は美しいです。夕食前には自転車をきれいにします。夕食後には国語を勉強します。私は週末がとても好きです。」',
slashRows:[{en:'On the weekend, / I study / at home.',jp:'週末に / 私は勉強します / 家で'},{en:'I study / math / before dinner.',jp:'私は勉強します / 数学を / 夕食前に'},{en:'I like math, / but I like science, too.',jp:'私は数学が好きです / しかし理科も好きです'},{en:'After dinner, / I read / at home.',jp:'夕食後 / 私は読みます / 家で'},{en:'I sometimes watch / tennis.',jp:'私はときどき見ます / テニスを'},{en:'I ride / my bicycle / on the weekend.',jp:'私は乗ります / 私の自転車に / 週末に'},{en:'I ride / with my friend.',jp:'私は乗ります / 私の友達といっしょに'},{en:'We like / our town.',jp:'私たちは好きです / 私たちの町が'},{en:'Our town is / beautiful.',jp:'私たちの町は〜です / 美しい'},{en:'Before dinner, / I clean / my bicycle.',jp:'夕食前に / 私はきれいにします / 私の自転車を'},{en:'After dinner, / I study / Japanese.',jp:'夕食後に / 私は勉強します / 国語を'},{en:'I like / the weekend / very much.',jp:'私は好きです / 週末が / とても'}],
questions:[{prompt:'1. 話し手は週末、どこで勉強しますか。本文から英語で答えなさい。',answer:'at home',evidence:'On the weekend, I study at home.',evidenceJp:'週末は家で勉強します。',reason:'at home が勉強する場所を表しています。'},{prompt:'2. 話し手は夕食前に何を勉強しますか。本文から英語で答えなさい。',answer:'math',evidence:'I study math before dinner.',evidenceJp:'夕食前に数学を勉強します。',reason:'before dinner の文で study の目的語が math です。'},{prompt:'3. 話し手は数学だけが好きですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I like math, but I like science, too.',evidenceJp:'数学が好きですが、理科も好きです。',reason:'science, too とあるため、数学だけではありません。'},{prompt:'4. 夕食前に何をきれいにしますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'Before dinner, I clean my bicycle.',evidenceJp:'夕食前には自転車をきれいにします。',reason:'clean の目的語 my bicycle が対象です。'},{prompt:'5. 話し手は週末が好きですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I like the weekend very much.',evidenceJp:'私は週末がとても好きです。',reason:'like ... very much と強く好んでいることが示されています。'}],
allowedWords:[['weekend / but / before / dinner / study / on','PROGRAM 2-2: id203-208'],['after / bicycle / ride / read / watch / clean / beautiful / sometimes / at home / very much','PROGRAM 2-1 cumulative'],['math / science / Japanese','PROGRAM 1-3 cumulative'],['friend / we / our / with / I / like / the','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-2をid203〜208まで照合し、id209からPROGRAM 2-3へ切り替わることを確認。weekend / before dinner / study / butを、週末の学習と自転車の手入れという1日の流れにまとめた。初稿に混入した三単現ridesは人手監査でI rideへ修正し、未確認の活用形を残していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 2-3']={
id:'V10-SS-G1-P2-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-3',level:'HOP',title:'Drawing During the Break',
sentences:['Look at this picture.','Wow!','I draw this picture in my notebook.','Are you an artist?','No, I’m not.','I like this picture.','I draw at home, too.','I have a question.','Sure.','This pencil is for you.','Thank you.','I have two.','We can draw during the break.','Let’s draw tomorrow.'],
fullTranslation:'「この絵を見て。」「わあ！」「私はこの絵をノートにかきます。」「あなたはアーティストですか。」「いいえ、違います。」「私はこの絵が好きです。」「家でも絵をかきます。」「質問があります。」「もちろん。」「この鉛筆はあなた用です。」「ありがとう。」「私は2本持っています。」「休み時間に絵をかくことができます。」「明日、絵をかこう。」',
slashRows:[{en:'Look at / this picture.',jp:'見てください / この絵を'},{en:'Wow!',jp:'わあ！'},{en:'I draw / this picture / in my notebook.',jp:'私はかきます / この絵を / 私のノートに'},{en:'Are you / an artist?',jp:'あなたは〜ですか / アーティスト'},{en:'No, / I’m not.',jp:'いいえ / 違います'},{en:'I like / this picture.',jp:'私は好きです / この絵が'},{en:'I draw / at home, too.',jp:'私はかきます / 家でも'},{en:'I have / a question.',jp:'私は持っています / 1つの質問を'},{en:'Sure.',jp:'もちろん。'},{en:'This pencil is / for you.',jp:'この鉛筆は〜です / あなた用'},{en:'Thank you.',jp:'ありがとう。'},{en:'I have / two.',jp:'私は持っています / 2本'},{en:'We can draw / during the break.',jp:'私たちはかくことができます / 休憩の間に'},{en:'Let’s draw / tomorrow.',jp:'かきましょう / 明日'}],
questions:[{prompt:'1. 話し手は絵をどこにかきますか。本文から英語で答えなさい。',answer:'my notebook',evidence:'I draw this picture in my notebook.',evidenceJp:'私はこの絵をノートにかきます。',reason:'in の後ろの my notebook がかく場所を示しています。'},{prompt:'2. 話し手はアーティストですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Are you an artist? / No, I’m not.',evidenceJp:'あなたはアーティストですか。／いいえ、違います。',reason:'質問に No, I’m not. と答えています。'},{prompt:'3. 話し手は質問がありますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I have a question.',evidenceJp:'私は質問があります。',reason:'I have a question. と明示されています。'},{prompt:'4. 相手に渡しているものは何ですか。本文から英語で答えなさい。',answer:'this pencil',evidence:'This pencil is for you.',evidenceJp:'この鉛筆はあなた用です。',reason:'for you とされている主語が This pencil です。'},{prompt:'5. いついっしょに絵をかこうと言っていますか。本文から英語で答えなさい。',answer:'tomorrow',evidence:'Let’s draw tomorrow.',evidenceJp:'明日、絵をかきましょう。',reason:'tomorrow が提案した時を表しています。'}],
allowedWords:[['flip / wow / picture / notebook / artist / draw / look / look at ～ / question / break / sure / tomorrow / during / for / any / pencil / two / how / How many ～?','PROGRAM 2-3: id209-227'],['this / I’m','PROGRAM 1 cumulative'],['at home','PROGRAM 2-1 cumulative'],['have / can / we / Thank you. / Let’s / like / in / my / are / you / no / an / a / is','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-3をid209〜227まで照合し、id228からアクションコーナーへ切り替わることを確認。picture / notebook / artist / draw / look at / question / break / pencil / two / tomorrow / duringを、絵を見せて休み時間と翌日の活動につなげる1場面にまとめた。How many ～?は複数形生成を伴うため、新出語消化だけを目的に本文へ無理に入れていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};