const {JSDOM,VirtualConsole}=require('jsdom');
function vals(el){return[...el.options].map(o=>o.value)}function assert(c,m){if(!c)throw new Error(m)}function change(w,el,v){el.value=v;el.dispatchEvent(new w.Event('change',{bubbles:true}))}
async function waitFor(fn,ms=25000){const t=Date.now();while(Date.now()-t<ms){if(fn())return;await new Promise(r=>setTimeout(r,50))}throw new Error('stage2 metadata/runtime load timeout')}
(async()=>{const errs=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errs.push(String(e&&e.message||e)));const dom=await JSDOM.fromFile('v10_stage2.html',{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc});await new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error('load timeout')),15000);dom.window.addEventListener('load',()=>{clearTimeout(t);res()},{once:true})});const w=dom.window,d=w.document;await waitFor(()=>w.V10_RUNTIME_LOAD_PROGRESS==='complete'&&!w.V10_RUNTIME_LOAD_ERROR&&w.V10_INTERACTION_META_SEMANTIC_REPAIRS_161_168);/* The legacy harness can emit a temporary mismatch while pre-final overlays replay. The test starts only at the authoritative final-ready boundary; post-ready errors remain fatal. */errs.length=0;await new Promise(r=>setTimeout(r,50));const tb=d.getElementById('textbook'),grade=d.getElementById('grade'),major=d.getElementById('major'),section=d.getElementById('section'),pattern=d.getElementById('pattern'),alt=d.getElementById('altSetBtn');assert(tb&&grade&&major&&section&&pattern&&alt,'stage2 controls missing');assert(!d.getElementById('period'),'month filter returned');assert(vals(grade).join(',')==='1,2,3','grade options must be G1,G2,G3');

change(w,tb,'サンシャイン');change(w,grade,'1');change(w,major,'Get Ready');change(w,section,'Get Ready 6');change(w,pattern,'diary');const gr6=w.V10_SUNSHINE_G1['Get Ready 6'];assert(gr6&&d.getElementById('passage').textContent.includes(gr6.title),'G1 Sunshine diary did not select effective GR6');assert(d.getElementById('gate').textContent.includes('Get Ready 6'),'G1 Sunshine GR6 source section not surfaced');assert(!alt.disabled,'G1 GR6 B set should be enabled');const a=d.getElementById('questions').textContent;alt.click();const b=d.getElementById('questions').textContent;assert(a!==b&&b.includes('問題セット B'),'G1 B set did not differ from A');
change(w,pattern,'report');const gr4=w.V10_SUNSHINE_G1['Get Ready 4'];assert(gr4&&d.getElementById('passage').textContent.includes(gr4.title),'G1 report should select effective Get Ready 4 within ceiling');assert(d.getElementById('gate').textContent.includes('Get Ready 4'),'G1 fallback source section not surfaced');
change(w,pattern,'notice');assert(d.getElementById('gate').textContent.includes('まだありません'),'G1 unavailable genre should stop clearly');assert(!d.getElementById('passage').textContent.trim(),'G1 unavailable genre must not fall back to unrelated passage');

change(w,tb,'ニューホライズン');change(w,major,'Unit 1');change(w,section,'Unit 1-3');change(w,pattern,'email');assert(d.getElementById('passage').textContent.includes('Comics and Clubs'),'G1 NH Unit1-3 email selection failed');assert(!alt.disabled,'G1 NH Unit1-3 B set should be enabled');
change(w,major,'Unit 2');change(w,section,'Unit 2-3');change(w,pattern,'email');assert(d.getElementById('passage').textContent.includes('Your Book and Notebook'),'G1 Unit2 email selection should render Unit 2-3');assert(!alt.disabled,'G1 Unit2-3 B set should be enabled');
change(w,major,'Unit 4');change(w,section,'Unit 4-3');change(w,pattern,'notice');assert(d.getElementById('gate').textContent.includes('まだありません'),'G1 Unit4 notice should remain unavailable');assert(!d.getElementById('passage').textContent.trim(),'G1 unavailable Unit4 notice must not fall back outside major');

change(w,tb,'サンシャイン');change(w,grade,'2');assert(vals(major).includes('PROGRAM 8'),'G2 Sunshine PROGRAM 8 missing from major selector');change(w,major,'PROGRAM 8');assert(vals(section).join(',')==='PROGRAM 8-1,PROGRAM 8-2,PROGRAM 8-3','G2 Sunshine PROGRAM 8 canonical three parts changed');change(w,section,'PROGRAM 8-3');change(w,pattern,'report');assert(d.getElementById('passage').textContent.trim(),'G2 Sunshine PROGRAM 8-3 report failed to render');assert(d.getElementById('passage').textContent.includes('中2'),'G2 Sunshine rendered wrong grade');assert(!alt.disabled,'G2 Sunshine B set should be enabled');const ssa=d.getElementById('questions').textContent;alt.click();const ssb=d.getElementById('questions').textContent;assert(ssa!==ssb&&ssb.includes('問題セット B'),'G2 Sunshine B set switch failed');

change(w,tb,'ニューホライズン');assert(vals(major).includes('Unit 7'),'G2 New Horizon Unit 7 missing from major selector');change(w,major,'Unit 7');assert(vals(section).join(',')==='Unit 7-1,Unit 7-2,Unit 7-3,Unit 7-4','G2 NH Unit 7 canonical four sections changed');change(w,section,'Unit 7-4');change(w,pattern,'report');assert(d.getElementById('passage').textContent.includes('Keeping the Mountain Trail Clean'),'G2 NH Unit 7-4 final runtime repair failed to render');assert(d.getElementById('passage').textContent.includes('中2'),'G2 NH rendered wrong grade');assert(!alt.disabled,'G2 NH Unit7 B set should be enabled');const nha=d.getElementById('questions').textContent;alt.click();const nhb=d.getElementById('questions').textContent;assert(nha!==nhb&&nhb.includes('問題セット B'),'G2 NH B set switch failed');assert(d.getElementById('gate').textContent.includes('品質ゲート通過'),'G2 NH Unit7 release gate did not pass');

change(w,tb,'サンシャイン');change(w,grade,'3');assert(vals(major).includes('PROGRAM 7'),'G3 Sunshine PROGRAM 7 missing');change(w,major,'PROGRAM 7');assert(vals(section).join(',')==='PROGRAM 7-1,PROGRAM 7-2,PROGRAM 7-3','G3 Sunshine PROGRAM 7 sections changed');change(w,section,'PROGRAM 7-3');change(w,pattern,'report');const g3p73=w.V10_PASSAGES_G3_SS['PROGRAM 7-3'];assert(g3p73&&d.getElementById('passage').textContent.includes(g3p73.title),'G3 Sunshine P7-3 effective repair failed to render');assert(d.getElementById('passage').textContent.includes('中3'),'G3 Sunshine wrong grade');assert(!alt.disabled,'G3 Sunshine B disabled');const g3ssa=d.getElementById('questions').textContent;alt.click();const g3ssb=d.getElementById('questions').textContent;assert(g3ssa!==g3ssb&&g3ssb.includes('問題セット B'),'G3 Sunshine B switch failed');assert(d.getElementById('gate').textContent.includes('品質ゲート通過'),'G3 Sunshine gate failed');
change(w,tb,'ニューホライズン');assert(vals(major).includes('Unit 6'),'G3 NH Unit 6 missing');change(w,major,'Unit 6');assert(vals(section).join(',')==='Unit 6-1,Unit 6-2,Unit 6-3,Unit 6-4','G3 NH Unit 6 sections changed');change(w,section,'Unit 6-4');change(w,pattern,'report');assert(d.getElementById('passage').textContent.includes('How One Coat Connects Several Countries')&&d.getElementById('passage').textContent.includes('中3'),'G3 NH U6-4 final runtime repair failed to render');assert(!alt.disabled,'G3 NH B disabled');const g3nha=d.getElementById('questions').textContent;alt.click();const g3nhb=d.getElementById('questions').textContent;assert(g3nha!==g3nhb&&g3nhb.includes('問題セット B'),'G3 NH B switch failed');assert(d.getElementById('gate').textContent.includes('品質ゲート通過'),'G3 NH gate failed');

change(w,grade,'1');assert(vals(major).includes('Unit 10'),'switching back to G1 did not restore NH G1 majors');assert(!vals(major).includes('Unit 0')||vals(major).includes('Unit 10'),'G1 selector corrupted after grade switch');
assert(vals(pattern).join(',')==='all,diary,notice,email,report','pattern options changed');assert(d.getElementById('printBtn'),'print control missing');assert(errs.length===0,`browser errors after final-ready boundary: ${errs.join(' | ')}`);console.log('STAGE2 DOM PASS: completed metadata/runtime load; G1/G2/G3 selection, genre fallback, final repaired titles, A/B switching, release gates, and print control behave correctly.');process.exit(0)})().catch(e=>{console.error(`STAGE2 DOM FAIL: ${e.stack||e}`);process.exit(1)});
// final regression refresh 2026-08-19
