window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 6-1'] = {
 id:'V10-NH-G1-U6-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 6-1',level:'HOP',title:'A Show from the U.K.',
 sentences:['This is a show from the U.K.','This is a performer in the show.','Do you know him?','Yes, I do.','Is he from the U.K.?','Yes, he is.','Do you like him?','Yes, I do.','Why don’t we watch the show?','Great!','Let’s watch it together.','Sounds great.','Thank you.'],
 fullTranslation:'これはイギリスのショーです。こちらはそのショーの出演者です。「彼を知っていますか。」「はい、知っています。」「彼はイギリス出身ですか。」「はい、そうです。」「彼が好きですか。」「はい、好きです。」「そのショーを見ませんか。」「いいね！」「いっしょに見よう。」「楽しそうだね。」「ありがとう。」',
 slashRows:[{en:'This is / a show / from the U.K.',jp:'これは〜です / ショー / イギリスの'},{en:'This is / a performer / in the show.',jp:'こちらは〜です / 出演者 / そのショーの'},{en:'Do you know / him?',jp:'あなたは知っていますか / 彼を'},{en:'Yes, / I do.',jp:'はい / 知っています'},{en:'Is he from / the U.K.?',jp:'彼は〜出身ですか / イギリス'},{en:'Yes, / he is.',jp:'はい / そうです'},{en:'Do you like / him?',jp:'あなたは好きですか / 彼が'},{en:'Yes, / I do.',jp:'はい / 好きです'},{en:'Why don’t we / watch the show?',jp:'〜しませんか / そのショーを見る'},{en:'Great!',jp:'いいね！'},{en:'Let’s watch / it / together.',jp:'見ましょう / それを / いっしょに'},{en:'Sounds / great.',jp:'〜そうですね / とても楽しそう'},{en:'Thank you.',jp:'ありがとう。'}],
 questions:[{prompt:'1. ショーはどこのものですか。本文から英語で答えなさい。',answer:'the U.K.',evidence:'This is a show from the U.K.',evidenceJp:'これはイギリスのショーです。',reason:'from the U.K. がショーの出所を表しています。'},{prompt:'2. 話し相手はその出演者を知っていますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Do you know him? / Yes, I do.',evidenceJp:'彼を知っていますか。／はい、知っています。',reason:'him を目的語にした質問に Yes, I do. と答えています。'},{prompt:'3. `him` は本文中でだれを指しますか。日本語で答えなさい。',answer:'そのショーの出演者',evidence:'This is a performer in the show. / Do you know him?',evidenceJp:'こちらはそのショーの出演者です。／彼を知っていますか。',reason:'直前に示された男性の出演者を目的格 him で受けています。'},{prompt:'4. 相手は何に誘っていますか。本文から英語で答えなさい。',answer:'watch the show',evidence:'Why don’t we watch the show?',evidenceJp:'そのショーを見ませんか。',reason:'Why don’t we ...? の後ろの watch the show が誘っている内容です。'},{prompt:'5. 最後にいっしょに何をしようと言っていますか。本文から英語で答えなさい。',answer:'watch it together',evidence:'Let’s watch it together.',evidenceJp:'いっしょにそれを見ましょう。',reason:'Let’s の後ろの watch it together が提案内容です。'}],
 allowedWords:[['show','Unit 6-1'],['performer','Unit 6-1'],['the U.K.','Unit 6-1'],['him','Unit 6-1 object pronoun'],['together','Unit 6-1'],['let’s','Unit 6-1 phrase'],['Why don’t we ...?','Unit 6-1 phrase'],['know','Unit 5-3 cumulative'],['watch','Unit 1-2 cumulative'],['Sounds ...','Unit 4-2 cumulative phrase'],['great','Unit 1-2 cumulative'],['Thank you.','Unit 2-3 cumulative'],['from / in / do / you / yes / I / is / he / like / it / the / a / this','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 6-1をid2292〜2302まで照合し、id2303からUnit 6-2へ切り替わることを確認。show / performer / the U.K. / everything / him / her / say / together / let’s / how’s / Why don’t we ...? が登録されている。本文では目的格himを明示的に使用し、her・everything・say・how’sは新出語消化のためだけには入れない。未確認のsays等を自動生成せず、既習のDo you ...? と登録済みのWhy don’t we ...? / let’sを中心に構成した。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
window.V10_PASSAGES['Unit 6-2'] = {
 id:'V10-NH-G1-U6-2-001',textbook:'ニューホライズン',grade:'1',section:'Unit 6-2',level:'HOP',title:'Whose Ticket Is This?',
 sentences:['This is a ticket.','Whose ticket is this?','Is it yours?','No, it is not.','Maybe it is Riko\'s.','Yes, it is.','This is a history book.','Whose book is this?','It is mine.','Here you are.','Thanks.','Thank you.'],
 fullTranslation:'「これはチケットです。」「これはだれのチケットですか。」「あなたのものですか。」「いいえ、違います。」「たぶん理子のものです。」「はい、そうです。」「これは歴史の本です。」「この本はだれのものですか。」「私のものです。」「はい、どうぞ。」「ありがとう。」「ありがとう。」',
 slashRows:[{en:'This is / a ticket.',jp:'これは〜です / 1枚のチケット'},{en:'Whose ticket / is this?',jp:'だれのチケットが / これですか'},{en:'Is it / yours?',jp:'それは〜ですか / あなたのもの'},{en:'No, / it is not.',jp:'いいえ / そうではありません'},{en:'Maybe / it is Riko\'s.',jp:'たぶん / それは理子のものです'},{en:'Yes, / it is.',jp:'はい / そうです'},{en:'This is / a history book.',jp:'これは〜です / 歴史の本'},{en:'Whose book / is this?',jp:'だれの本が / これですか'},{en:'It is / mine.',jp:'それは〜です / 私のもの'},{en:'Here you are.',jp:'はい、どうぞ。'},{en:'Thanks.',jp:'ありがとう。'},{en:'Thank you.',jp:'ありがとう。'}],
 questions:[{prompt:'1. 最初に見つかったものは何ですか。本文から英語で答えなさい。',answer:'a ticket',evidence:'This is a ticket.',evidenceJp:'これはチケットです。',reason:'最初の文で見つかった物が ticket と示されています。'},{prompt:'2. そのチケットは話し相手のものですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Is it yours? / No, it is not.',evidenceJp:'あなたのものですか。／いいえ、違います。',reason:'所有代名詞 yours を使った質問に No, it is not. と答えています。'},{prompt:'3. チケットはだれのものだと考えられていますか。本文から英語で答えなさい。',answer:'Riko\'s',evidence:'Maybe it is Riko\'s.',evidenceJp:'たぶん理子のものです。',reason:'Maybe の後ろで所有者を Riko\'s と示しています。'},{prompt:'4. 歴史の本はだれのものですか。本文から英語で答えなさい。',answer:'mine',evidence:'Whose book is this? / It is mine.',evidenceJp:'この本はだれのものですか。／私のものです。',reason:'whose の質問に所有代名詞 mine で答えています。'},{prompt:'5. `yours` と `mine` は何を表す語ですか。日本語で答えなさい。',answer:'持ち主（あなたのもの・私のもの）を表す語。',evidence:'Is it yours? / It is mine.',evidenceJp:'あなたのものですか。／私のものです。',reason:'名詞を繰り返さず、所有者を示す所有代名詞として使われています。'}],
 allowedWords:[['history','Unit 6-2'],['whose','Unit 6-2'],['yours','Unit 6-2 possessive pronoun'],['mine','Unit 6-2 possessive pronoun'],['maybe','Unit 6-2'],['ticket','Unit 6-2'],['(Riko)\'s','Unit 6-2 possessive form'],['Thanks.','Unit 6-2 phrase'],['book','elementary'],['Here you are. / Thank you.','Unit 2-3 cumulative phrases'],['this / is / a / it / no / not / yes / you','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 6-2をid2303〜2319まで照合し、id2320からUnit 6-3へ切り替わることを確認。minute / history / whose / yours / mine / wait / careful / crowded / still / maybe / over / ticket / start / (Riko)s / Thanks. / be careful with / How old ...? が登録されている。本文は持ち物の所有者を確認する1場面に限定し、未確認複数形tickets等は生成しない。whose / yours / mine / Riko\'sを明示的に使って所有表現の読解にした。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};