window.V10_VOCAB_CORRECTIONS = [
  {textbook:'ニューホライズン',grade:'1',section:'Unit 1-1',english:'sweets',japanese:'甘い菓子',basis:'Unit 1 Part 1 textbook booklet explicitly lists sweet(s) and uses Japanese sweets.',rule:'explicit textbook form; not automatic plural inflection'},
  {textbook:'ニューホライズン',grade:'1',section:'Unit 1-2',english:'friends',japanese:'友達',basis:'Unit 1 Part 2 textbook booklet explicitly lists friend(s) and uses with my friends.',rule:'explicit textbook form; not automatic plural inflection'},
  {textbook:'ニューホライズン',grade:'1',section:'Unit 1-2',english:'soccer',japanese:'サッカー',basis:'Unit 1 Part 2 textbook body explicitly uses I play soccer, but the embedded Unit 1-2 word rows do not expose a separate soccer row.',rule:'textbook-confirmed missing base entry; register before passage release'},
  {textbook:'ニューホライズン',grade:'1',section:'Unit 1-3',english:'comics',japanese:'マンガ',basis:'Unit 1 Part 3 textbook booklet explicitly lists comic(s) and uses Do you like comics? / I draw comics, too.',rule:'explicit textbook form; not automatic plural inflection'},
  {textbook:'ニューホライズン',grade:'1',section:'Unit 1-3',english:'lessons',japanese:'レッスン',basis:'Unit 1 Part 3 textbook booklet explicitly lists lesson(s) and uses I take swimming lessons.',rule:'explicit textbook form; not automatic plural inflection'},
  {textbook:'サンシャイン',grade:'1',section:'Get Ready 4',english:'play',japanese:'~をする',basis:'v7 master SS1 pre-step record ID 2146: プレステップ4 だれが何をどうする / play / ~をする.',rule:'v7-confirmed cumulative vocabulary; repair allowedWords metadata omission, not an unknown-word note'},
  {textbook:'サンシャイン',grade:'2',section:'PROGRAM 1-1',english:'eat',japanese:'~を食べる',basis:'v7 master SS1 record ID 2152: プレステップ4 だれが何をどうする / eat / ~を食べる.',rule:'prior-grade v7-confirmed vocabulary; repair first G2 allowedWords metadata omission'},
  {textbook:'ニューホライズン',grade:'2',section:'Unit 0',english:'eat',japanese:'~を食べる',basis:'v7 master NH1 record ID 39: プレステップ4 だれが何をどうする / eat / ~を食べる.',rule:'prior-grade v7-confirmed vocabulary; repair first G2 allowedWords metadata omission'},
  {textbook:'ニューホライズン',grade:'2',section:'Unit 1-3',english:'large',japanese:'大きい, 広い',basis:'v7 master NH1 record ID 558: Unit7 / Real Life English 3 / large / 大きい, 広い.',rule:'prior-grade v7-confirmed vocabulary; repair first G2 allowedWords metadata omission'}
];
(function installV10VocabularyCorrectionApplier(){
  function pools(){return [window.V10_SUNSHINE_G1,window.V10_NEWHORIZON_G1,window.V10_PASSAGES_G2_SS,window.V10_PASSAGES_G2_NH,window.V10_PASSAGES_G3_SS,window.V10_PASSAGES_G3_NH].filter(Boolean);}
  function hasToken(rows,word){const re=new RegExp('(^|[^A-Za-z])'+String(word).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'([^A-Za-z]|$)','i');return (rows||[]).some(r=>re.test(Array.isArray(r)?String(r[0]||''):String(r||'')));}
  function apply(){let applied=0,targetsSeen=0;for(const c of (window.V10_VOCAB_CORRECTIONS||[])){for(const pool of pools())for(const m of Object.values(pool||{})){if(!m||String(m.textbook)!==String(c.textbook)||String(m.grade)!==String(c.grade)||String(m.section)!==String(c.section))continue;targetsSeen++;m.allowedWords=Array.isArray(m.allowedWords)?m.allowedWords:[];if(!hasToken(m.allowedWords,c.english)){m.allowedWords.push([c.english,`v7 correction: ${c.basis}`]);applied++;}}}window.V10_VOCAB_CORRECTIONS_APPLIED=(window.V10_VOCAB_CORRECTIONS_APPLIED||0)+applied;window.V10_VOCAB_CORRECTION_TARGETS_SEEN=targetsSeen;return targetsSeen;}
  let tries=0;apply();const timer=setInterval(()=>{tries++;const targetsSeen=apply();const expected=(window.V10_VOCAB_CORRECTIONS||[]).length;if((window.V10_RUNTIME_LOAD_PROGRESS==='complete'&&targetsSeen>=expected)||tries>=120){clearInterval(timer);apply();}},100);window.addEventListener('load',()=>setTimeout(apply,0),{once:true});
})();
(function installV10GlossRenderer(){if(typeof document==='undefined')return;const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));function pools(){return [window.V10_SUNSHINE_G1,window.V10_NEWHORIZON_G1,window.V10_PASSAGES_G2_SS,window.V10_PASSAGES_G2_NH,window.V10_PASSAGES_G3_SS,window.V10_PASSAGES_G3_NH].filter(Boolean);}function byId(id){for(const pool of pools())for(const m of Object.values(pool||{}))if(m&&m.id===id)return m;return null;}function ensureStyle(){if(document.getElementById('v10-gloss-style'))return;const style=document.createElement('style');style.id='v10-gloss-style';style.textContent=`.v10-gloss-box{margin:14px 0;padding:12px 14px;border:1px solid #dbe4ee;border-radius:12px;background:#f8fafc}.v10-gloss-title{font-weight:800;margin-bottom:6px}.v10-gloss-list{display:flex;flex-wrap:wrap;gap:6px 14px;line-height:1.8}.v10-gloss-item{overflow-wrap:anywhere;word-break:break-word}.v10-gloss-en{font-weight:800}@media print{.v10-gloss-box{break-inside:avoid;page-break-inside:avoid}}`;document.head.appendChild(style);}function render(){const host=document.getElementById('passage');if(!host)return;const old=host.querySelector('.v10-gloss-box');if(old)old.remove();const meta=host.querySelector('.meta');if(!meta)return;const id=(meta.textContent||'').split('/')[0].trim();const m=byId(id);if(!m)return;const notes=(Array.isArray(m.notes)?m.notes:[]).filter(n=>n&&String(n.english||'').trim()&&String(n.japanese||'').trim());if(!notes.length)return;ensureStyle();const box=document.createElement('div');box.className='v10-gloss-box';box.setAttribute('data-v10-gloss-count',String(notes.length));box.innerHTML=`<div class="v10-gloss-title">注（未習語）</div><div class="v10-gloss-list">${notes.map(n=>`<span class="v10-gloss-item"><span class="v10-gloss-en">${esc(n.english)}</span>：${esc(n.japanese)}${n.reading?`（${esc(n.reading)}）`:''}</span>`).join('')}</div>`;const en=host.querySelector('.en');if(en&&en.parentNode)en.insertAdjacentElement('afterend',box);else host.appendChild(box);}function start(){const host=document.getElementById('passage');if(!host)return;let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render();});});obs.observe(host,{childList:true,subtree:true});render();window.V10_GLOSS_RENDERER_INSTALLED=true;}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();
(function installV10MobileLayoutGuard(){if(typeof document==='undefined'||document.getElementById('v10-mobile-layout-guard'))return;const style=document.createElement('style');style.id='v10-mobile-layout-guard';style.textContent=`html,body{width:100%;max-width:100%;min-width:0;overflow-x:hidden}.wrap,.panel,.tabpage,.row,.field,.controlbar,.q,.slash,.evidence,.meta,.notice,.fail,.v10-gloss-box{max-width:100%;min-width:0}.panel *{min-width:0}.en,.slash,.q,.evidence,.meta,.notice,.fail,.muted,.v10-gloss-box,p,div,span,li,td,th,a{overflow-wrap:anywhere;word-break:break-word}pre,code{max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word}table{max-width:100%;width:100%;table-layout:fixed}select,button,input,textarea{max-width:100%;min-width:0}@media(max-width:700px){.wrap{width:100%}.row{width:100%;min-width:0}.field{min-width:0!important;flex:1 1 calc(50% - 8px);max-width:100%}.field select{display:block;width:100%!important;min-width:0!important;max-width:100%!important}.controlbar>*{max-width:100%;white-space:normal}}`;document.head.appendChild(style);})();
