window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};
window.V10_PASSAGES_G2_SS['PROGRAM 4-2']={
 id:'V10-SS-G2-P4-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 4-2',level:'HOP',title:'Rules in the Forest',
 sentences:['We are in a forest today.','First of all, we must protect the forest.','We must remember this rule.','We must not leave garbage.','We mustn’t leave a potato chip bag, either.','We must keep the forest clean.','We must walk in the forest.','We must help each other.','If we have trouble, we should talk to our guide.','The forest is quiet.','We mustn’t make trouble.','We use this rule to protect the forest.','I am glad to learn this rule.'],
 fullTranslation:'「今日は森にいます。まず何よりも、森を守らなければなりません。私たちはこの規則を覚えなければなりません。ごみを置いていってはいけません。ポテトチップの袋も置いていってはいけません。森をきれいに保たなければなりません。森の中を歩かなければなりません。お互いに助け合わなければなりません。困ったことがあれば、ガイドに話すべきです。森は静かです。困ったことを起こしてはいけません。私たちは森を守るためにこの規則を使います。私はこの規則を学べてうれしいです。」',
 slashRows:[{en:'We are / in a forest / today.',jp:'私たちはいます / 森に / 今日'},{en:'First of all, / we must protect / the forest.',jp:'まず何よりも / 私たちは守らなければなりません / 森を'},{en:'We must remember / this rule.',jp:'私たちは覚えなければなりません / この規則を'},{en:'We must not leave / garbage.',jp:'私たちは残してはいけません / ごみを'},{en:'We mustn’t leave / a potato chip bag, either.',jp:'私たちは残してはいけません / ポテトチップの袋も'},{en:'We must keep / the forest / clean.',jp:'私たちは保たなければなりません / 森を / きれいに'},{en:'We must walk / in the forest.',jp:'私たちは歩かなければなりません / 森の中を'},{en:'We must help / each other.',jp:'私たちは助け合わなければなりません / お互いに'},{en:'If we have / trouble, / we should talk to / our guide.',jp:'もし私たちにあれば / 困ったことが / 私たちは話すべきです / ガイドに'},{en:'The forest is / quiet.',jp:'森は〜です / 静かな'},{en:'We mustn’t make / trouble.',jp:'私たちは起こしてはいけません / 困ったことを'},{en:'We use / this rule / to protect the forest.',jp:'私たちは使います / この規則を / 森を守るために'},{en:'I am / glad / to learn this rule.',jp:'私は〜です / うれしい / この規則を学べて'}],
 questions:[{prompt:'1. まず何を守らなければなりませんか。本文から英語で答えなさい。',answer:'the forest',evidence:'First of all, we must protect the forest.',evidenceJp:'まず何よりも、森を守らなければなりません。',reason:'protect の目的語が the forest です。'},{prompt:'2. ごみを残してもよいですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'We must not leave garbage.',evidenceJp:'ごみを置いていってはいけません。',reason:'must not leave と禁止しているので No です。'},{prompt:'3. 困ったとき、誰に話すべきですか。本文から英語で答えなさい。',answer:'our guide',evidence:'If we have trouble, we should talk to our guide.',evidenceJp:'困ったことがあれば、ガイドに話すべきです。',reason:'talk to の後ろが our guide です。'},{prompt:'4. 森はどのような場所ですか。本文から英語で1語抜き出しなさい。',answer:'quiet',evidence:'The forest is quiet.',evidenceJp:'森は静かです。',reason:'quiet が forest の様子です。'},{prompt:'5. この規則を何のために使いますか。本文から英語で答えなさい。',answer:'to protect the forest',evidence:'We use this rule to protect the forest.',evidenceJp:'私たちは森を守るためにこの規則を使います。',reason:'to protect the forest が目的を表しています。'}],
 allowedWords:[['must / garbage / mustn’t / forest / protect / potato chip / first of all / trouble / rule','PROGRAM 4-2: canonical Sheet IDs 3054-3066'],['guide / glad','PROGRAM 4-1 cumulative'],['if / should / remember','PROGRAM 2 cumulative'],['today / leave / bag / keep / clean / walk / help / each other / quiet / make / use / learn / either','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 4-2をID3054〜3066まで直接照合。初稿に4-3初出のloud / noiseとrule→rulesの自動複数化が混入したため、人手ゲートで削除。ruleは登録表層の単数形だけを使用し、must / mustn’t / garbage / forest / protect / troubleを中心に再構成した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
