window.V10_PASSAGES = window.V10_PASSAGES || {};
window.V10_PASSAGES['Unit 8-1'] = {
 id:'V10-NH-G1-U8-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 8-1',level:'HOP',title:'A Volunteer in Kenya',
 sentences:['This is a volunteer.','He is from Kenya.','Does he teach children?','Yes, he does.','Are the children in need?','Yes, they are.','Does he respect the children?','Yes, he does.','Do you respect him?','Yes, I do.','I want to become a volunteer.','I want to do my best.','Great!'],
 fullTranslation:'こちらはボランティアです。彼はケニア出身です。「彼は子どもたちに教えますか。」「はい、教えます。」「その子どもたちは困っていますか。」「はい、困っています。」「彼はその子どもたちを尊重していますか。」「はい、しています。」「あなたは彼を尊敬していますか。」「はい、しています。」「私はボランティアになりたいです。」「最善を尽くしたいです。」「いいね！」',
 slashRows:[{en:'This is / a volunteer.',jp:'こちらは〜です / ボランティア'},{en:'He is from / Kenya.',jp:'彼は〜出身です / ケニア'},{en:'Does he teach / children?',jp:'彼は教えますか / 子どもたちに'},{en:'Yes, / he does.',jp:'はい / 教えます'},{en:'Are the children / in need?',jp:'その子どもたちは〜ですか / 困っている状態に'},{en:'Yes, / they are.',jp:'はい / そうです'},{en:'Does he respect / the children?',jp:'彼は尊重しますか / その子どもたちを'},{en:'Yes, / he does.',jp:'はい / します'},{en:'Do you respect / him?',jp:'あなたは尊敬しますか / 彼を'},{en:'Yes, / I do.',jp:'はい / します'},{en:'I want to become / a volunteer.',jp:'私はなりたいです / ボランティアに'},{en:'I want to do / my best.',jp:'私は尽くしたいです / 最善を'},{en:'Great!',jp:'いいね！'}],
 questions:[{prompt:'1. そのボランティアはどこの出身ですか。本文から英語で答えなさい。',answer:'Kenya',evidence:'He is from Kenya.',evidenceJp:'彼はケニア出身です。',reason:'from の後ろの Kenya が出身地を示しています。'},{prompt:'2. そのボランティアは誰に教えますか。本文から英語で答えなさい。',answer:'children',evidence:'Does he teach children? / Yes, he does.',evidenceJp:'彼は子どもたちに教えますか。／はい、教えます。',reason:'teach の後ろの children が教える相手です。'},{prompt:'3. その子どもたちは困っていますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Are the children in need? / Yes, they are.',evidenceJp:'その子どもたちは困っていますか。／はい、そうです。',reason:'in need かどうかの質問に Yes, they are. と答えています。'},{prompt:'4. 話し手は何になりたいですか。本文から英語で答えなさい。',answer:'a volunteer',evidence:'I want to become a volunteer.',evidenceJp:'私はボランティアになりたいです。',reason:'become の後ろの a volunteer がなりたいものです。'},{prompt:'5. 話し手は何をしたいと言っていますか。本文中の表現を使って英語で答えなさい。',answer:'do my best',evidence:'I want to do my best.',evidenceJp:'私は最善を尽くしたいです。',reason:'Unit 8-1で登録された do one’s best を my に合わせて使った表現です。'}],
 allowedWords:[['volunteer','Unit 8-1'],['Kenya','Unit 8-1'],['teach','Unit 8-1'],['respect','Unit 8-1'],['children','Unit 8-1 exact plural form'],['become','Unit 8-1'],['in need','Unit 8-1 phrase'],['do one’s best','Unit 8-1 phrase'],['does','Unit 5-2 cumulative grammar'],['him','Unit 6-1 cumulative object pronoun'],['want to','Unit 1-1 cumulative'],['great','Unit 1-2 cumulative'],['this / is / a / he / from / yes / are / the / they / do / you / I / my','cumulative / elementary']],
 auditNote:'v9内蔵VOCABでUnit 8-1をid2402〜2418まで照合し、id2419からUnit 8-2へ切り替わることを確認。volunteer / need / best / Africa / Kenya / teach / try / become / respect / ethnic / children / child / country / cousin / always / in need / do one’s best が登録されている。childrenは正本にchildの複数形として明示登録されているためそのまま使用。teaches / respects等の肯定三単現形は自動生成せず、Unit 5-2で解禁済みのDoes he + 原形を使用。未使用の語は新出語消化のためだけには詰め込まない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};