const fs=require('fs');const vm=require('vm');
const SUN_FILES=['v10_data_sunshine_g1.js','v10_data_sunshine_g1_program1.js','v10_data_sunshine_g1_program2.js','v10_data_sunshine_g1_program4.js','v10_data_sunshine_g1_program5.js','v10_data_sunshine_g1_program6.js','v10_data_sunshine_g1_program7.js','v10_data_sunshine_g1_program8.js','v10_data_sunshine_g1_program9.js','v10_data_sunshine_g1_program10.js','v10_data_sunshine_g1_program10_fix.js'];
const NH_FILES=['v10_data_newhorizon_g1.js','v10_data_newhorizon_g1_unit1_2.js','v10_data_newhorizon_g1_unit1_3.js','v10_data_newhorizon_g1_unit2_1.js','v10_data_newhorizon_g1_unit2_2.js','v10_data_newhorizon_g1_unit2_3.js','v10_data_newhorizon_g1_unit3_1.js','v10_data_newhorizon_g1_unit3_2.js','v10_data_newhorizon_g1_unit4_3.js','v10_data_newhorizon_g1_unit5_1.js','v10_data_newhorizon_g1_unit5_2.js','v10_data_newhorizon_g1_unit5_3.js','v10_data_newhorizon_g1_unit6_1.js','v10_data_newhorizon_g1_unit7_1.js','v10_data_newhorizon_g1_unit8_1.js','v10_data_newhorizon_g1_unit9_1.js','v10_data_newhorizon_g1_unit10_1.js'];
function load(files){const c={window:{}};vm.createContext(c);for(const f of files)vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});return c.window.V10_PASSAGES||{}}
const sun=load(SUN_FILES),nh=load(NH_FILES);const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('v10_interaction_metadata_initial.js','utf8'),c);const chunks=['v10_interaction_metadata_sun_p1_p3.js','v10_interaction_metadata_sun_p4_p6.js','v10_interaction_metadata_sun_p7_p8.js','v10_interaction_metadata_sun_p9_p10.js','v10_interaction_metadata_nh_u2_u4.js','v10_interaction_metadata_nh_u5_u7.js'];for(const f of chunks)vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});c.window.V10_INTERACTION_META=Object.assign({},c.window.V10_INTERACTION_META||{},c.window.V10_INTERACTION_META_P1P3||{},c.window.V10_INTERACTION_META_P4P6||{},c.window.V10_INTERACTION_META_P7P8||{},c.window.V10_INTERACTION_META_P9P10||{},c.window.V10_INTERACTION_META_NH_U2U4||{},c.window.V10_INTERACTION_META_NH_U5U7||{});const meta=c.window.V10_INTERACTION_META||{};const genres=new Set(['diary','notice','email','report']);const errors=[];let bQuestions=0;
for(const [key,md] of Object.entries(meta)){
 const cut=key.indexOf('|'),tb=key.slice(0,cut),section=key.slice(cut+1),data=tb==='サンシャイン'?sun:tb==='ニューホライズン'?nh:null,m=data&&data[section];
 if(!m){errors.push(`${key}: master missing`);continue}if(!genres.has(md.genre))errors.push(`${key}: invalid genre ${md.genre}`);if(!Array.isArray(md.questionSetB)||md.questionSetB.length<3){errors.push(`${key}: questionSetB missing/short`);continue}
 const aSig=JSON.stringify(m.questions.map(q=>[q.prompt,q.answer]));const bSig=JSON.stringify(md.questionSetB.map(q=>[q.prompt,q.answer]));if(aSig===bSig)errors.push(`${key}: B set identical to A`);
 md.questionSetB.forEach((q,i)=>{bQuestions++;for(const k of ['prompt','answer','evidence','evidenceJp','reason'])if(typeof q[k]!=='string'||!q[k].trim())errors.push(`${key}: BQ${i+1} ${k} empty`);for(const part of String(q.evidence||'').split(' / ').map(x=>x.trim()).filter(Boolean))if(!m.sentences.includes(part))errors.push(`${key}: BQ${i+1} evidence not verbatim: ${part}`)});
}
if(Object.keys(meta).length!==60)errors.push(`reviewed interaction masters expected 60, got ${Object.keys(meta).length}`);
console.log(`INTERACTION reviewed_masters=${Object.keys(meta).length} alternate_questions=${bQuestions}`);if(errors.length){console.error(`INTERACTION FAIL ${errors.length}`);for(const e of errors)console.error(`- ${e}`);process.exit(1)}console.log('INTERACTION PASS: reviewed genres and hand-authored B question sets are structurally valid and evidence-linked.');
