window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 0']={
id:'V10-NH-G2-U0-001',textbook:'ニューホライズン',grade:'2',section:'Unit 0',level:'HOP',title:'Ramen on Spring Vacation',
sentences:['During spring vacation, I had a new experience.','I ate ramen with my friend.','We ate the same ramen.','The noodle was very good.','Actually, it was instant ramen.','I did not know that at first.','My friend told me about it.','We talked about ramen after lunch.','I like ramen very much.','My friend likes ramen, too.','By the way, we want to eat ramen again.','Spring vacation was fun.'],
fullTranslation:'「春休みに、私は新しい経験をしました。友達とラーメンを食べました。私たちは同じラーメンを食べました。めんはとてもおいしかったです。実は、それは即席ラーメンでした。私は最初そのことを知りませんでした。友達がそのことを教えてくれました。昼食後、私たちはラーメンについて話しました。私はラーメンがとても好きです。友達もラーメンが好きです。ところで、私たちはまたラーメンを食べたいです。春休みは楽しかったです。」',
slashRows:[{en:'During spring vacation, / I had / a new experience.',jp:'春休みに / 私はしました / 新しい経験を'},{en:'I ate / ramen / with my friend.',jp:'私は食べました / ラーメンを / 友達と'},{en:'We ate / the same ramen.',jp:'私たちは食べました / 同じラーメンを'},{en:'The noodle was / very good.',jp:'そのめんは〜でした / とてもおいしい'},{en:'Actually, / it was / instant ramen.',jp:'実は / それは〜でした / 即席ラーメン'},{en:'I did not know / that / at first.',jp:'私は知りませんでした / そのことを / 最初は'},{en:'My friend told / me / about it.',jp:'友達は教えました / 私に / それについて'},{en:'We talked about / ramen / after lunch.',jp:'私たちは話しました / ラーメンについて / 昼食後に'},{en:'I like / ramen / very much.',jp:'私は好きです / ラーメンが / とても'},{en:'My friend likes / ramen, too.',jp:'友達も好きです / ラーメンが'},{en:'By the way, / we want to eat / ramen again.',jp:'ところで / 私たちは食べたいです / ラーメンをまた'},{en:'Spring vacation was / fun.',jp:'春休みは〜でした / 楽しい'}],
questions:[{prompt:'1. 春休みに何を食べましたか。本文から英語で答えなさい。',answer:'ramen',evidence:'I ate ramen with my friend.',evidenceJp:'友達とラーメンを食べました。',reason:'ate の目的語が ramen です。'},{prompt:'2. 2人は違うラーメンを食べましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'We ate the same ramen.',evidenceJp:'私たちは同じラーメンを食べました。',reason:'the same ramen とあるので同じものです。'},{prompt:'3. 実はどんなラーメンでしたか。本文から英語で答えなさい。',answer:'instant ramen',evidence:'Actually, it was instant ramen.',evidenceJp:'実は、それは即席ラーメンでした。',reason:'Actually の文で instant ramen と説明しています。'},{prompt:'4. 話し手は最初からそのことを知っていましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I did not know that at first.',evidenceJp:'私は最初そのことを知りませんでした。',reason:'did not know と否定されています。'},{prompt:'5. 春休みはどうでしたか。本文から英語で1語抜き出しなさい。',answer:'fun',evidence:'Spring vacation was fun.',evidenceJp:'春休みは楽しかったです。',reason:'fun が春休みの感想です。'}],
allowedWords:[['experience / ramen / same / noodle / actually / instant / by the way','Unit 0: v7 canonical Sheet IDs 945-951'],['spring vacation / had / ate / friend / did not / know / told / talked / lunch / like / likes / want to / again / was / fun','G1 cumulative']],
auditNote:'最新v7正本Unit0教科書本文（Sheet ID945〜951）を直接照合。experience / ramen / same / noodle / actually / instant / by the wayを春休みの1場面に統合。過去形は中1既習の表層形だけを使用し、新規活用は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 1-1']={
id:'V10-NH-G2-U1-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 1-1',level:'HOP',title:'A Trip Plan at the Airport',
sentences:['We are going to take a trip.','I am going to meet my friend at the airport.','Our flight is in the morning.','We are going to leave the airport soon.','We are going to arrive before lunch.','My friend is going to show me around the city.','It is a golden holiday for us.','We want to walk around the city.','We are going to take many pictures.','I am excited about the trip.','I say, “See you.”','The trip is going to start soon.'],
fullTranslation:'「私たちは旅行をする予定です。私は空港で友達に会う予定です。私たちの便は午前です。私たちはまもなく空港を出発する予定です。昼食前に到着する予定です。友達が街のあちこちを案内してくれる予定です。私たちにとってすばらしい休日です。私たちは街のあちこちを歩きたいです。たくさん写真を撮る予定です。私は旅行を楽しみにしています。『またね』と言います。旅行はまもなく始まります。」',
slashRows:[{en:'We are going to take / a trip.',jp:'私たちはする予定です / 旅行を'},{en:'I am going to meet / my friend / at the airport.',jp:'私は会う予定です / 友達に / 空港で'},{en:'Our flight is / in the morning.',jp:'私たちの便は〜です / 午前に'},{en:'We are going to leave / the airport / soon.',jp:'私たちは出発する予定です / 空港を / まもなく'},{en:'We are going to arrive / before lunch.',jp:'私たちは到着する予定です / 昼食前に'},{en:'My friend is going to show / me / around the city.',jp:'友達は案内する予定です / 私を / 街のあちこちへ'},{en:'It is / a golden holiday / for us.',jp:'それは〜です / すばらしい休日 / 私たちにとって'},{en:'We want to walk / around the city.',jp:'私たちは歩きたいです / 街のあちこちを'},{en:'We are going to take / many pictures.',jp:'私たちは撮る予定です / たくさんの写真を'},{en:'I am / excited / about the trip.',jp:'私は〜です / わくわくして / 旅行について'},{en:'I say, / “See you.”',jp:'私は言います / 「またね」'},{en:'The trip is going to start / soon.',jp:'旅行は始まる予定です / まもなく'}],
questions:[{prompt:'1. どこで友達に会う予定ですか。本文から英語で答えなさい。',answer:'at the airport',evidence:'I am going to meet my friend at the airport.',evidenceJp:'私は空港で友達に会う予定です。',reason:'at the airport が場所です。'},{prompt:'2. いつ空港を出発する予定ですか。本文から英語で1語抜き出しなさい。',answer:'soon',evidence:'We are going to leave the airport soon.',evidenceJp:'私たちはまもなく空港を出発する予定です。',reason:'soon が時を表します。'},{prompt:'3. 誰が街を案内する予定ですか。本文から英語で答えなさい。',answer:'my friend',evidence:'My friend is going to show me around the city.',evidenceJp:'友達が街のあちこちを案内してくれる予定です。',reason:'主語 My friend が案内する人です。'},{prompt:'4. 話し手は旅行についてどう感じていますか。本文から英語で1語抜き出しなさい。',answer:'excited',evidence:'I am excited about the trip.',evidenceJp:'私は旅行を楽しみにしています。',reason:'excited が気持ちを表します。'},{prompt:'5. 旅行はいつ始まる予定ですか。本文から英語で1語抜き出しなさい。',answer:'soon',evidence:'The trip is going to start soon.',evidenceJp:'旅行はまもなく始まります。',reason:'soon が開始時期です。'}],
allowedWords:[['be going to ~ / show / meet / flight / leave / airport / arrive / golden / holiday / around ~ / soon / See you.','Unit 1-1: v7 canonical Sheet IDs 952-963'],['trip / friend / morning / before lunch / city / want to / walk / take / picture / excited / say / start','G1/Unit1 cumulative']],
auditNote:'最新v7正本Unit1 Part1（Sheet ID952〜963）を直接照合。be going to ~を中心に旅行計画の1場面へ統合。show / meet / flight / leave / airport / arrive / golden / holiday / around / soon / See you.を確認済み形で使用。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 1-2']={
id:'V10-NH-G2-U1-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 1-2',level:'HOP',title:'Dinner after the Flight',
sentences:['Our flight will arrive in the afternoon.','I will meet my friend first.','We will go to a restaurant.','I will eat seafood there.','My friend will not eat seafood.','We will have different food.','I will make a reservation.','The restaurant is not far from the airport.','I am excited about dinner.','My friend is excited, too.','I say, “I’ll call you after dinner.”','My friend says, “You’ll have a good evening.”'],
fullTranslation:'「私たちの便は午後に到着するでしょう。私はまず友達に会います。私たちはレストランへ行くでしょう。私はそこでシーフードを食べます。友達はシーフードを食べません。私たちは違う食べ物を食べます。私は予約をします。そのレストランは空港から遠くありません。私は夕食を楽しみにしています。友達もわくわくしています。私は『夕食後に電話するよ』と言います。友達は『よい夜になるよ』と言います。」',
slashRows:[{en:'Our flight will arrive / in the afternoon.',jp:'私たちの便は到着するでしょう / 午後に'},{en:'I will meet / my friend / first.',jp:'私は会います / 友達に / まず'},{en:'We will go / to a restaurant.',jp:'私たちは行くでしょう / レストランへ'},{en:'I will eat / seafood / there.',jp:'私は食べます / シーフードを / そこで'},{en:'My friend will not eat / seafood.',jp:'友達は食べません / シーフードを'},{en:'We will have / different food.',jp:'私たちは食べます / 違う食べ物を'},{en:'I will make / a reservation.',jp:'私はします / 予約を'},{en:'The restaurant is not / far from the airport.',jp:'そのレストランは〜ではありません / 空港から遠い'},{en:'I am / excited / about dinner.',jp:'私は〜です / わくわくして / 夕食について'},{en:'My friend is / excited, too.',jp:'友達も〜です / わくわくして'},{en:'I say, / “I’ll call you / after dinner.”',jp:'私は言います / 「あなたに電話します / 夕食後に」'},{en:'My friend says, / “You’ll have / a good evening.”',jp:'友達は言います / 「あなたは過ごすでしょう / よい夜を」'}],
questions:[{prompt:'1. 便はいつ到着するでしょうか。本文から英語で答えなさい。',answer:'in the afternoon',evidence:'Our flight will arrive in the afternoon.',evidenceJp:'私たちの便は午後に到着するでしょう。',reason:'in the afternoon が時です。'},{prompt:'2. 話し手は何を食べる予定ですか。本文から英語で答えなさい。',answer:'seafood',evidence:'I will eat seafood there.',evidenceJp:'私はそこでシーフードを食べます。',reason:'eat の目的語が seafood です。'},{prompt:'3. 友達もシーフードを食べますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'My friend will not eat seafood.',evidenceJp:'友達はシーフードを食べません。',reason:'will not eat と否定されています。'},{prompt:'4. レストランは空港から遠いですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'The restaurant is not far from the airport.',evidenceJp:'そのレストランは空港から遠くありません。',reason:'is not far と否定されています。'},{prompt:'5. 話し手は何をしますか。本文から英語で答えなさい。',answer:'a reservation',evidence:'I will make a reservation.',evidenceJp:'私は予約をします。',reason:'make の目的語が a reservation です。'}],
allowedWords:[['will / you’ll / won’t / seafood / I’ll / reservation / excited / far / first','Unit 1-2: v7 canonical Sheet IDs 964-972'],['flight / arrive / meet / friend / afternoon / restaurant / eat / different / food / airport / dinner / say / call / evening','Unit1/G1 cumulative']],
auditNote:'最新v7正本Unit1 Part2（Sheet ID964〜972）を直接照合。will / you’ll / won’t / I’ll と seafood / reservation / excited / far / firstを旅行後の夕食計画へ統合。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 1-3']={
id:'V10-NH-G2-U1-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 1-3',level:'HOP',title:'Shopping with Different Languages',
sentences:['Yesterday, we went to a shop.','I found a small card there.','The card had two languages.','One language was English.','The other language was Chinese.','We tried to communicate with the shop staff.','For example, I used a short English question.','My friend used a different word.','The card was one dollar.','It was about one meter from a large sign.','The sign was two meters tall.','We did not know the weight of the sign.','We found a good way to communicate.','Shopping was an interesting experience.'],
fullTranslation:'「昨日、私たちは店へ行きました。私はそこで小さなカードを見つけました。そのカードには2つの言語がありました。1つは英語でした。もう1つは中国語でした。私たちは店員と意思を伝え合おうとしました。例えば、私は短い英語の質問を使いました。友達は違う単語を使いました。そのカードは1ドルでした。それは大きな看板から約1メートルのところにありました。その看板は高さ2メートルでした。私たちは看板の重さを知りませんでした。私たちは意思を伝え合うよい方法を見つけました。買い物はおもしろい経験でした。」',
slashRows:[{en:'Yesterday, / we went / to a shop.',jp:'昨日 / 私たちは行きました / 店へ'},{en:'I found / a small card / there.',jp:'私は見つけました / 小さなカードを / そこで'},{en:'The card had / two languages.',jp:'そのカードにはありました / 2つの言語が'},{en:'One language was / English.',jp:'1つの言語は〜でした / 英語'},{en:'The other language was / Chinese.',jp:'もう1つの言語は〜でした / 中国語'},{en:'We tried to communicate / with the shop staff.',jp:'私たちは意思を伝え合おうとしました / 店員と'},{en:'For example, / I used / a short English question.',jp:'例えば / 私は使いました / 短い英語の質問を'},{en:'My friend used / a different word.',jp:'友達は使いました / 違う単語を'},{en:'The card was / one dollar.',jp:'そのカードは〜でした / 1ドル'},{en:'It was / about one meter / from a large sign.',jp:'それはありました / 約1メートル / 大きな看板から'},{en:'The sign was / two meters tall.',jp:'その看板は〜でした / 高さ2メートル'},{en:'We did not know / the weight / of the sign.',jp:'私たちは知りませんでした / 重さを / 看板の'},{en:'We found / a good way / to communicate.',jp:'私たちは見つけました / よい方法を / 意思を伝え合うための'},{en:'Shopping was / an interesting experience.',jp:'買い物は〜でした / おもしろい経験'}],
questions:[{prompt:'1. どこへ行きましたか。本文から英語で答えなさい。',answer:'a shop',evidence:'Yesterday, we went to a shop.',evidenceJp:'昨日、私たちは店へ行きました。',reason:'went to の後ろが a shop です。'},{prompt:'2. カードには何語がありましたか。本文から英語で2つ答えなさい。',answer:'English, Chinese',evidence:'One language was English. / The other language was Chinese.',evidenceJp:'1つは英語でした。／もう1つは中国語でした。',reason:'2文で言語が明示されています。'},{prompt:'3. カードはいくらでしたか。本文から英語で答えなさい。',answer:'one dollar',evidence:'The card was one dollar.',evidenceJp:'そのカードは1ドルでした。',reason:'one dollar が価格です。'},{prompt:'4. 看板はどのくらいの高さでしたか。本文から英語で答えなさい。',answer:'two meters tall',evidence:'The sign was two meters tall.',evidenceJp:'その看板は高さ2メートルでした。',reason:'two meters tall が高さです。'},{prompt:'5. 最後に何を見つけましたか。本文から英語で答えなさい。',answer:'a good way to communicate',evidence:'We found a good way to communicate.',evidenceJp:'私たちは意思を伝え合うよい方法を見つけました。',reason:'found の目的語が a good way to communicate です。'}],
allowedWords:[['find-found / shop / language / communicate / Chinese / example / different / meter / for example / dollar / weigh / ~tall','Unit 1-3: v7 canonical Sheet IDs 973-984'],['went / card / English / staff / short / question / friend / word / sign / did not know / weight / good / way / shopping / interesting / experience','G1/Unit0 cumulative']],
auditNote:'最新v7正本Unit1 Read and Think1（Sheet ID973〜984）を直接照合。過去形foundはfind-foundとして正本に明示された形だけを使用。language / communicate / Chinese / different / meter / dollar / ~tallを買い物場面に統合。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 1-4']={
id:'V10-NH-G2-U1-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 1-4',level:'HOP',title:'Culture on a Wall',
sentences:['We visited a special area in Singapore.','We saw a large wall there.','A painting was on the wall.','The painting showed a culture from India.','I was surprised by the painting.','My friend was surprised, too.','We talked about the area.','We also saw a mosque near the wall.','The mosque was very beautiful.','We learned about different culture.','The area was quiet in the morning.','We took a picture of the wall.','I want to visit the area again.','The trip gave me a new experience.'],
fullTranslation:'「私たちはシンガポールの特別な地域を訪れました。そこに大きな壁がありました。その壁に絵がありました。その絵はインドの文化を表していました。私はその絵に驚きました。友達も驚きました。私たちはその地域について話しました。壁の近くにモスクも見ました。そのモスクはとても美しかったです。私たちは異なる文化について学びました。その地域は朝は静かでした。私たちは壁の写真を撮りました。私はまたその地域を訪れたいです。その旅行は私に新しい経験を与えました。」',
slashRows:[{en:'We visited / a special area / in Singapore.',jp:'私たちは訪れました / 特別な地域を / シンガポールで'},{en:'We saw / a large wall / there.',jp:'私たちは見ました / 大きな壁を / そこで'},{en:'A painting was / on the wall.',jp:'1枚の絵がありました / 壁に'},{en:'The painting showed / a culture / from India.',jp:'その絵は表していました / 文化を / インドの'},{en:'I was / surprised / by the painting.',jp:'私は〜でした / 驚いて / その絵に'},{en:'My friend was / surprised, too.',jp:'友達も〜でした / 驚いて'},{en:'We talked about / the area.',jp:'私たちは話しました / その地域について'},{en:'We also saw / a mosque / near the wall.',jp:'私たちはまた見ました / モスクを / 壁の近くに'},{en:'The mosque was / very beautiful.',jp:'そのモスクは〜でした / とても美しい'},{en:'We learned about / different culture.',jp:'私たちは学びました / 異なる文化について'},{en:'The area was / quiet / in the morning.',jp:'その地域は〜でした / 静か / 朝に'},{en:'We took / a picture / of the wall.',jp:'私たちは撮りました / 写真を / 壁の'},{en:'I want to visit / the area / again.',jp:'私は訪れたいです / その地域を / また'},{en:'The trip gave / me / a new experience.',jp:'その旅行は与えました / 私に / 新しい経験を'}],
questions:[{prompt:'1. どこを訪れましたか。本文から英語で答えなさい。',answer:'a special area in Singapore',evidence:'We visited a special area in Singapore.',evidenceJp:'私たちはシンガポールの特別な地域を訪れました。',reason:'visited の目的語と場所が a special area in Singapore です。'},{prompt:'2. 壁には何がありましたか。本文から英語で答えなさい。',answer:'a painting',evidence:'A painting was on the wall.',evidenceJp:'その壁に絵がありました。',reason:'主語 A painting が壁にあったものです。'},{prompt:'3. その絵はどこの文化を表していましたか。本文から英語で答えなさい。',answer:'India',evidence:'The painting showed a culture from India.',evidenceJp:'その絵はインドの文化を表していました。',reason:'from の後ろが India です。'},{prompt:'4. 話し手は絵を見てどう感じましたか。本文から英語で1語抜き出しなさい。',answer:'surprised',evidence:'I was surprised by the painting.',evidenceJp:'私はその絵に驚きました。',reason:'surprised が気持ちです。'},{prompt:'5. 壁の近くには何がありましたか。本文から英語で答えなさい。',answer:'a mosque',evidence:'We also saw a mosque near the wall.',evidenceJp:'壁の近くにモスクも見ました。',reason:'saw の目的語が a mosque です。'}],
allowedWords:[['culture / painting / surprised / India / area / wall','Unit 1-4: v7 canonical Sheet IDs 985-990'],['Singapore / mosque / ton','Unit 1 textbook body: v7 canonical Sheet IDs 991-993'],['visited / saw / showed / was / friend / talked / near / beautiful / learned / different / quiet / morning / took / picture / want to / again / trip / gave / experience','G1/Unit1 cumulative']],
auditNote:'最新v7正本Unit1 Read and Think2（Sheet ID985〜990）と同Unit教科書本文（991〜993）を照合。culture / painting / surprised / India / area / wall / Singapore / mosqueを1つの旅行体験にまとめた。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};