window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['Unit 10-1']={
id:'V10-NH-G1-U10-1-001',textbook:'ニューホライズン',grade:'1',section:'Unit 10-1',level:'HOP',title:'My Hero',
sentences:['This is my hero.','This is his life.','He was born in Japan.','He moved to Canada.','He became a teacher.','Did he teach children?','Yes, he did.','He moved back to Japan.','Did he travel?','Yes, he did.','He died.','I still respect him.','He is my hero.'],
fullTranslation:'「この人は私のヒーローです。」「これは彼の人生です。」「彼は日本で生まれました。」「カナダへ引っ越しました。」「先生になりました。」「子どもたちに教えましたか。」「はい、教えました。」「日本へ戻りました。」「旅行しましたか。」「はい、しました。」「彼は亡くなりました。」「私は今でも彼を尊敬しています。」「彼は私のヒーローです。」',
slashRows:[{en:'This is / my hero.',jp:'この人は〜です / 私のヒーロー'},{en:'This is / his life.',jp:'これは〜です / 彼の人生'},{en:'He was born / in Japan.',jp:'彼は生まれました / 日本で'},{en:'He moved / to Canada.',jp:'彼は引っ越しました / カナダへ'},{en:'He became / a teacher.',jp:'彼はなりました / 先生に'},{en:'Did he teach / children?',jp:'彼は教えましたか / 子どもたちに'},{en:'Yes, / he did.',jp:'はい / 教えました'},{en:'He moved back / to Japan.',jp:'彼は戻りました / 日本へ'},{en:'Did he travel?',jp:'彼は旅行しましたか'},{en:'Yes, / he did.',jp:'はい / しました'},{en:'He died.',jp:'彼は亡くなりました'},{en:'I still respect / him.',jp:'私は今でも尊敬しています / 彼を'},{en:'He is / my hero.',jp:'彼は〜です / 私のヒーロー'}],
questions:[{prompt:'1. その人はどこで生まれましたか。本文から英語で答えなさい。',answer:'Japan',evidence:'He was born in Japan.',evidenceJp:'彼は日本で生まれました。',reason:'born の後ろの in Japan が生まれた場所を示しています。'},{prompt:'2. その人はどこへ引っ越しましたか。本文から英語で答えなさい。',answer:'Canada',evidence:'He moved to Canada.',evidenceJp:'彼はカナダへ引っ越しました。',reason:'moved to の後ろの Canada が移動先です。'},{prompt:'3. その人は何になりましたか。本文から英語で答えなさい。',answer:'a teacher',evidence:'He became a teacher.',evidenceJp:'彼は先生になりました。',reason:'became の後ろの a teacher がなったものです。'},{prompt:'4. その人は子どもたちに教えましたか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Did he teach children? / Yes, he did.',evidenceJp:'彼は子どもたちに教えましたか。／はい、教えました。',reason:'過去の疑問文に Yes, he did. と答えています。'},{prompt:'5. 話し手はその人を今でもどう思っていますか。本文から英語で答えなさい。',answer:'respect him',evidence:'I still respect him.',evidenceJp:'私は今でも彼を尊敬しています。',reason:'still respect him が現在も続いている気持ちを表しています。'}],
allowedWords:[['hero','Unit 10-1'],['life','Unit 10-1'],['his','Unit 10-1'],['born','Unit 10-1 explicit past participle of bear'],['was','Unit 10-1 explicit past of be'],['moved','Unit 10-1 explicit past of move'],['became','Unit 10-1 explicit past of become'],['died','Unit 10-1 explicit past of die'],['Japan','Unit 4-1 cumulative'],['Canada','Unit 2-1 cumulative'],['teacher','Unit 2-1 cumulative'],['children / teach / respect','Unit 8-1 cumulative'],['did','Unit 9-2 cumulative past-question grammar'],['travel','Unit 7-3 cumulative'],['back','Unit 9-1 cumulative'],['still','Unit 6-2 cumulative'],['him','Unit 6-1 cumulative'],['this / is / my / he / in / to / a / yes / I','cumulative / elementary']],
auditNote:'v9内蔵VOCABでUnit 10-1をid2520〜2528まで照合し、id2529からUnit 10-2へ切り替わることを確認。hero / life / his / born / was / moved / became / died / be born が登録されている。was / moved / became / died は正本に明示された過去形だけを使用。実在人物の伝記知識は持ち込まず、架空の人物についての本文として構成した。',
vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};