window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 1-1']={
 id:'V10-SS-G2-P1-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 1-1',level:'HOP',title:'My Special Party',
 sentences:['What’s up?','Nothing special.','By the way, I have a plan.','I plan a party with my friends.','I leave this town on Sunday.','I move to a new city.','The party is at my house.','We play music.','We eat dinner together.','We talk about our school.','I want to see my friends again.','This party is special for me.','I like this town very much.','I am happy today.'],
 fullTranslation:'「どうしたの？」「特に何もないよ。ところで、私には計画があります。友達とパーティーを計画しています。私は日曜日にこの町を出発します。新しい町へ引っ越します。パーティーは私の家でします。私たちは音楽を演奏します。いっしょに夕食を食べます。学校について話します。また友達に会いたいです。このパーティーは私にとって特別です。私はこの町がとても好きです。今日はうれしいです。」',
 slashRows:[{en:'What’s up?',jp:'どうしたの？'},{en:'Nothing special.',jp:'特に何もないよ。'},{en:'By the way, / I have / a plan.',jp:'ところで / 私にはあります / 1つの計画が'},{en:'I plan / a party / with my friends.',jp:'私は計画します / パーティーを / 友達と'},{en:'I leave / this town / on Sunday.',jp:'私は出発します / この町を / 日曜日に'},{en:'I move / to a new city.',jp:'私は引っ越します / 新しい町へ'},{en:'The party is / at my house.',jp:'そのパーティーはあります / 私の家で'},{en:'We play / music.',jp:'私たちは演奏します / 音楽を'},{en:'We eat / dinner / together.',jp:'私たちは食べます / 夕食を / いっしょに'},{en:'We talk about / our school.',jp:'私たちは話します / 私たちの学校について'},{en:'I want to see / my friends / again.',jp:'私は会いたいです / 友達に / また'},{en:'This party is / special / for me.',jp:'このパーティーは〜です / 特別な / 私にとって'},{en:'I like / this town / very much.',jp:'私は好きです / この町が / とても'},{en:'I am / happy / today.',jp:'私は〜です / うれしい / 今日'}],
 questions:[{prompt:'1. 話し手は何を計画していますか。本文から英語で答えなさい。',answer:'a party',evidence:'I plan a party with my friends.',evidenceJp:'友達とパーティーを計画しています。',reason:'plan の目的語が a party です。'},{prompt:'2. 話し手はいつこの町を出発しますか。本文から英語で答えなさい。',answer:'on Sunday',evidence:'I leave this town on Sunday.',evidenceJp:'私は日曜日にこの町を出発します。',reason:'on Sunday が出発する時を表しています。'},{prompt:'3. 話し手はどこへ引っ越しますか。本文から英語で答えなさい。',answer:'to a new city',evidence:'I move to a new city.',evidenceJp:'新しい町へ引っ越します。',reason:'to a new city が移動先です。'},{prompt:'4. パーティーはどこでしますか。本文から英語で答えなさい。',answer:'at my house',evidence:'The party is at my house.',evidenceJp:'パーティーは私の家でします。',reason:'at my house が場所を表しています。'},{prompt:'5. このパーティーは話し手にとってどのようなものですか。本文から英語で1語抜き出しなさい。',answer:'special',evidence:'This party is special for me.',evidenceJp:'このパーティーは私にとって特別です。',reason:'special がパーティーへの気持ちを表しています。'}],
 allowedWords:[['move / by the way / leave / plan / again / party / nothing / special / What’s up?','PROGRAM 1-1: canonical Sheet IDs 2833-2841'],['town / Sunday / city / house / music / dinner / together / school / friends / happy / today / want to / very much','G1 cumulative / elementary']],
 auditNote:'Google Sheet正本 v7「単語マスター」でSunshine中2 PROGRAM 1-1をID2833〜2841まで直接照合。v7監査ではv6との差分（英語・日本語）0。willは1-2初出のため、この本文では未使用。新出語の自動活用形は生成していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 1-2']={
 id:'V10-SS-G2-P1-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 1-2',level:'HOP',title:'Keep in Touch',
 sentences:['Tomorrow, I will leave this town.','I am a bit worried.','My friend is worried, too.','Take care.','Thank you.','I won’t forget my friends.','I won’t forget this town, either.','I’ll text you.','You can text me, too.','We will keep in touch.','I hope you will be fine.','By the way, the local park is special to me.','I’ll visit the local park again.','See you soon.'],
 fullTranslation:'「明日、私はこの町を出発します。少し心配です。友達も心配しています。」「気をつけてね。」「ありがとう。私は友達を忘れません。この町も忘れません。あなたにメールします。あなたも私にメールできます。私たちは連絡を取り続けます。あなたが元気でいてくれるといいな。ところで、その地元の公園は私にとって特別です。またその公園を訪れます。では、またすぐに。」',
 slashRows:[{en:'Tomorrow, / I will leave / this town.',jp:'明日 / 私は出発します / この町を'},{en:'I am / a bit worried.',jp:'私は〜です / 少し心配な'},{en:'My friend is / worried, too.',jp:'私の友達も〜です / 心配している'},{en:'Take care.',jp:'気をつけてね。'},{en:'Thank you.',jp:'ありがとう。'},{en:'I won’t forget / my friends.',jp:'私は忘れません / 友達を'},{en:'I won’t forget / this town, either.',jp:'私は忘れません / この町も'},{en:'I’ll text / you.',jp:'私はメールします / あなたに'},{en:'You can text / me, too.',jp:'あなたもメールできます / 私に'},{en:'We will keep in touch.',jp:'私たちは連絡を取り続けます'},{en:'I hope / you will be fine.',jp:'私は願います / あなたが元気でいることを'},{en:'By the way, / the local park is / special to me.',jp:'ところで / その地元の公園は〜です / 私にとって特別な'},{en:'I’ll visit / the local park / again.',jp:'私は訪れます / その地元の公園を / また'},{en:'See you / soon.',jp:'また会いましょう / すぐに'}],
 questions:[{prompt:'1. 話し手はいつ町を出発しますか。本文から英語で答えなさい。',answer:'Tomorrow',evidence:'Tomorrow, I will leave this town.',evidenceJp:'明日、私はこの町を出発します。',reason:'Tomorrow が出発する時を示しています。'},{prompt:'2. 話し手はどんな気持ちですか。本文から英語で1語抜き出しなさい。',answer:'worried',evidence:'I am a bit worried.',evidenceJp:'少し心配です。',reason:'worried が話し手の状態です。'},{prompt:'3. 話し手は友達を忘れますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I won’t forget my friends.',evidenceJp:'私は友達を忘れません。',reason:'won’t forget と否定しているので No です。'},{prompt:'4. 2人はこれからどうしますか。本文から英語で答えなさい。',answer:'keep in touch',evidence:'We will keep in touch.',evidenceJp:'私たちは連絡を取り続けます。',reason:'will の後ろの keep in touch が今後の行動です。'},{prompt:'5. 話し手にとって特別な場所はどこですか。本文から英語で答えなさい。',answer:'the local park',evidence:'By the way, the local park is special to me.',evidenceJp:'その地元の公園は私にとって特別です。',reason:'special to me の主語が the local park です。'}],
 allowedWords:[['will / take care / won’t / a bit / hope / text / forget / worried / late / local / either / it’ll / soon / I’ll / keep in touch','PROGRAM 1-2: canonical Sheet IDs 2842-2856'],['leave / by the way / again / special','PROGRAM 1-1 cumulative'],['tomorrow / town / friend / fine / park / visit / Thank you. / See you','G1 cumulative / elementary']],
 auditNote:'Google Sheet正本でPROGRAM 1-2をID2842〜2856まで直接照合。will / won’t / I’ll / keep in touch をこのPartから使用。it’ll / late は自然な流れに不要なため無理に消化していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 1-3']={
 id:'V10-SS-G2-P1-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 1-3',level:'HOP',title:'My First Day Overseas',
 sentences:['I am overseas now.','My new school has a short quiz today.','Maybe it is easy.','I am a bit worried.','I won’t cry.','I’ll do my best.','After school, I text my friend.','Why don’t you take a short break?','Sounds nice.','I read a book in the park.','I see a child near me.','The child has a book, too.','Maybe I can make a new friend.','Thanks for your help.','I’ll do my best again.'],
 fullTranslation:'「私は今、海外にいます。新しい学校では今日、短い小テストがあります。たぶん簡単です。私は少し心配です。でも泣きません。最善をつくします。放課後、友達にメールします。」「少し休憩したらどう？」「よさそうだね。」私は公園で本を読みます。近くに子どもがいます。その子も本を持っています。たぶん新しい友達を作ることができます。手伝ってくれてありがとう。私はまた最善をつくします。」',
 slashRows:[{en:'I am / overseas / now.',jp:'私はいます / 海外に / 今'},{en:'My new school has / a short quiz / today.',jp:'私の新しい学校にはあります / 短い小テストが / 今日'},{en:'Maybe / it is / easy.',jp:'たぶん / それは〜です / 簡単な'},{en:'I am / a bit worried.',jp:'私は〜です / 少し心配な'},{en:'I won’t cry.',jp:'私は泣きません'},{en:'I’ll do my best.',jp:'私は最善をつくします'},{en:'After school, / I text / my friend.',jp:'放課後 / 私はメールします / 友達に'},{en:'Why don’t you take / a short break?',jp:'〜してはどうですか / 短い休憩を取る'},{en:'Sounds nice.',jp:'よさそうですね。'},{en:'I read / a book / in the park.',jp:'私は読みます / 本を / 公園で'},{en:'I see / a child / near me.',jp:'私は見ます / 子どもを / 私の近くに'},{en:'The child has / a book, too.',jp:'その子どもも持っています / 本を'},{en:'Maybe / I can make / a new friend.',jp:'たぶん / 私は作れます / 新しい友達を'},{en:'Thanks for / your help.',jp:'ありがとう / あなたの助けを'},{en:'I’ll do my best / again.',jp:'私は最善をつくします / また'}],
 questions:[{prompt:'1. 話し手は今どこにいますか。本文から英語で答えなさい。',answer:'overseas',evidence:'I am overseas now.',evidenceJp:'私は今、海外にいます。',reason:'overseas が現在いる場所を示しています。'},{prompt:'2. 学校では今日何がありますか。本文から英語で答えなさい。',answer:'a short quiz',evidence:'My new school has a short quiz today.',evidenceJp:'新しい学校では今日、短い小テストがあります。',reason:'has の目的語が a short quiz です。'},{prompt:'3. 話し手は泣きますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I won’t cry.',evidenceJp:'私は泣きません。',reason:'won’t cry と否定しているので No です。'},{prompt:'4. 友達は何をするよう提案していますか。本文から英語で答えなさい。',answer:'take a short break',evidence:'Why don’t you take a short break?',evidenceJp:'少し休憩したらどう？',reason:'Why don’t you ...? の後ろが提案内容です。'},{prompt:'5. 話し手は新しく何を作れそうだと考えていますか。本文から英語で答えなさい。',answer:'a new friend',evidence:'Maybe I can make a new friend.',evidenceJp:'たぶん新しい友達を作ることができます。',reason:'make の目的語が a new friend です。'}],
 allowedWords:[['cry / do my best / money / quiz / child / short / maybe / overseas / Why don’t you ~? / Sounds nice. / Thanks for ~.','PROGRAM 1-3: canonical Sheet IDs 2857-2867'],['will / won’t / a bit / text / worried / I’ll','PROGRAM 1-2 cumulative'],['school / easy / after school / friend / break / read / book / park / near / help / again / can / make / has','G1 cumulative / elementary']],
 auditNote:'Google Sheet正本でPROGRAM 1-3をID2857〜2867まで直接照合。Why don’t you ~? / Sounds nice. / Thanks for ~. は登録表現をそのまま使用。money は場面を散らすため未使用。新しい活用形を自動生成していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
