window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 6-1']={
id:'V10-SS-G3-P6-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 6-1',level:'HOP',title:'A Patch in the Ocean',
sentences:['A Canadian researcher can study a patch in the ocean.','It is said that a lot of trash can gather in the patch.','A plastic bottle can get caught in a net.','People sometimes leave trash behind.','The patch can contain a ton of plastic.','A net can kill an animal.','A bottle can float near ice.','The researcher can gather information.','The trash is mostly plastic.','We look at a map of the patch.','I am surprised by the amount of trash.','We talk about how to reduce trash.'],
fullTranslation:'「カナダの研究者は海の一区画を調べることができます。その一区画には多くのごみが集まると言われています。プラスチックのボトルが網に引っかかることがあります。人々はごみを置き去りにすることがあります。その一区画には1トンのプラスチックが含まれることがあります。網は動物を殺してしまうことがあります。ボトルは氷の近くに浮かぶことがあります。研究者は情報を集めることができます。そのごみは大部分がプラスチックです。私たちはその一区画の地図を見ます。私はごみの量に驚きます。私たちはごみを減らす方法について話します。」',
slashRows:[{en:'A Canadian researcher / can study / a patch / in the ocean.',jp:'カナダの研究者は / 調べることができます / 一区画を / 海の'},{en:'It is said that / a lot of trash / can gather / in the patch.',jp:'〜と言われています / 多くのごみが / 集まることがあると / その一区画に'},{en:'A plastic bottle / can get caught in / a net.',jp:'プラスチックのボトルは / 引っかかることがあります / 網に'},{en:'People sometimes / leave trash behind.',jp:'人々は時々 / ごみを置き去りにします'},{en:'The patch / can contain / a ton of plastic.',jp:'その一区画には / 含まれることがあります / 1トンのプラスチックが'},{en:'A net / can kill / an animal.',jp:'網は / 殺してしまうことがあります / 動物を'},{en:'A bottle / can float / near ice.',jp:'ボトルは / 浮かぶことがあります / 氷の近くに'},{en:'The researcher / can gather / information.',jp:'研究者は / 集めることができます / 情報を'},{en:'The trash is / mostly plastic.',jp:'そのごみは〜です / 大部分がプラスチック'},{en:'We look at / a map / of the patch.',jp:'私たちは見ます / 地図を / その一区画の'},{en:'I am / surprised / by the amount of trash.',jp:'私は〜です / 驚いて / ごみの量に'},{en:'We talk about / how to reduce / trash.',jp:'私たちは話します / 減らす方法について / ごみを'}],
questions:[{prompt:'1. だれが海の一区画を調べることができますか。本文から英語で答えなさい。',answer:'a Canadian researcher',evidence:'A Canadian researcher can study a patch in the ocean.',evidenceJp:'カナダの研究者は海の一区画を調べることができます。',reason:'can study の主語が A Canadian researcher です。'},{prompt:'2. 何がその一区画に集まると言われていますか。本文から英語で答えなさい。',answer:'a lot of trash',evidence:'It is said that a lot of trash can gather in the patch.',evidenceJp:'その一区画には多くのごみが集まると言われています。',reason:'can gather の主語が a lot of trash です。'},{prompt:'3. プラスチックのボトルは何に引っかかることがありますか。本文から英語で答えなさい。',answer:'a net',evidence:'A plastic bottle can get caught in a net.',evidenceJp:'プラスチックのボトルが網に引っかかることがあります。',reason:'get caught in の後ろが a net です。'},{prompt:'4. その一区画にはどれくらいのプラスチックが含まれることがありますか。本文から英語で答えなさい。',answer:'a ton of plastic',evidence:'The patch can contain a ton of plastic.',evidenceJp:'その一区画には1トンのプラスチックが含まれることがあります。',reason:'contain の目的語が a ton of plastic です。'},{prompt:'5. ごみの大部分は何ですか。本文から英語で1語抜き出しなさい。',answer:'plastic',evidence:'The trash is mostly plastic.',evidenceJp:'そのごみは大部分がプラスチックです。',reason:'mostly の後ろが plastic です。'}],
allowedWords:[["get caught in ~ / patch / leave A behind / trash / it is said that ~ / net / kill / ice / gather / bottle / contain / plastic / ton / mostly / researcher / Canadian",'PROGRAM6 6-1: v7 canonical partition'],['study / ocean / a lot of / people / sometimes / animal / float / near / information / look at / map / surprised / amount / talk about / how to / reduce','G1-G2 and PROGRAM1-5 cumulative']],
auditNote:'最新v7正本PROGRAM6 6-1（ID3820-3835）を直接照合。get caught in / patch / leave A behind / trash / it is said that / net / kill / ice / gather / bottle / contain / plastic / ton / mostly / researcher / Canadianを海洋ごみの説明文に統合。6-2以降とPROGRAM7語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 6-2']={
id:'V10-SS-G3-P6-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 6-2',level:'HOP',title:'An Idea for Collecting Trash',
sentences:['At the age of sixteen, a boy saw trash at the beach.','He was shocked by the trash.','He could dive in the sea.','A balloon can float above the water.','He wanted to collect trash.','He thought about a new system.','The system can collect plastic from the water.','It can help an animal that is hurt.','He wrote the idea in a notebook.','His family read the idea.','The idea can become a real project.','He wanted to improve the system.'],
fullTranslation:'「16歳のとき、ある少年は海辺でごみを見ました。彼はそのごみに衝撃を受けました。彼は海でダイビングすることができました。風船は水の上に浮かぶことができます。彼はごみを集めたいと思いました。彼は新しい仕組みについて考えました。その仕組みは水からプラスチックを集めることができます。それは傷ついた動物を助けることができます。彼はその考えをノートに書きました。家族はその考えを読みました。その考えは本当のプロジェクトになる可能性があります。彼はその仕組みを改善したいと思いました。」',
slashRows:[{en:'At the age of sixteen, / a boy saw / trash / at the beach.',jp:'16歳のとき / ある少年は見ました / ごみを / 海辺で'},{en:'He was / shocked / by the trash.',jp:'彼は〜でした / 衝撃を受けて / そのごみに'},{en:'He could dive / in the sea.',jp:'彼はダイビングできました / 海で'},{en:'A balloon / can float / above the water.',jp:'風船は / 浮かぶことができます / 水の上に'},{en:'He wanted to collect / trash.',jp:'彼は集めたいと思いました / ごみを'},{en:'He thought about / a new system.',jp:'彼は考えました / 新しい仕組みについて'},{en:'The system / can collect / plastic / from the water.',jp:'その仕組みは / 集めることができます / プラスチックを / 水から'},{en:'It can help / an animal / that is hurt.',jp:'それは助けることができます / 動物を / 傷ついた'},{en:'He wrote / the idea / in a notebook.',jp:'彼は書きました / その考えを / ノートに'},{en:'His family read / the idea.',jp:'彼の家族は読みました / その考えを'},{en:'The idea / can become / a real project.',jp:'その考えは / なることができます / 本当のプロジェクトに'},{en:'He wanted to improve / the system.',jp:'彼は改善したいと思いました / その仕組みを'}],
questions:[{prompt:'1. 少年は何歳のときにごみを見ましたか。本文から英語で答えなさい。',answer:'sixteen',evidence:'At the age of sixteen, a boy saw trash at the beach.',evidenceJp:'16歳のとき、ある少年は海辺でごみを見ました。',reason:'at the age of の後ろが sixteen です。'},{prompt:'2. 少年はごみを見てどのような状態でしたか。本文から英語で1語抜き出しなさい。',answer:'shocked',evidence:'He was shocked by the trash.',evidenceJp:'彼はそのごみに衝撃を受けました。',reason:'was の後ろが shocked です。'},{prompt:'3. 少年は海で何をすることができましたか。本文から英語で1語抜き出しなさい。',answer:'dive',evidence:'He could dive in the sea.',evidenceJp:'彼は海でダイビングすることができました。',reason:'could の後ろの動詞が dive です。'},{prompt:'4. 新しい仕組みは何を集めることができますか。本文から英語で答えなさい。',answer:'plastic',evidence:'The system can collect plastic from the water.',evidenceJp:'その仕組みは水からプラスチックを集めることができます。',reason:'collect の目的語が plastic です。'},{prompt:'5. その仕組みは何を助けることができますか。本文から英語で答えなさい。',answer:'an animal that is hurt',evidence:'It can help an animal that is hurt.',evidenceJp:'それは傷ついた動物を助けることができます。',reason:'help の目的語が an animal that is hurt です。'}],
allowedWords:[["collect / system / at the age of ~ / balloon / hurt / shocked / dive",'PROGRAM6 6-2: v7 canonical partition'],['trash / beach / sea / float / water / want to / think about / new / plastic / help / animal / write / idea / notebook / family / read / become / real / project / improve','PROGRAM6 6-1 and earlier cumulative']],
auditNote:'最新v7正本PROGRAM6 6-2（ID3836-3842）を直接照合。collect / system / at the age of / balloon / hurt / shocked / diveを、海洋ごみ回収のアイデアの流れに統合。6-3語彙とPROGRAM7語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 6-3']={
id:'V10-SS-G3-P6-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 6-3',level:'HOP',title:'Small Actions for Less Waste',
sentences:['Some people think ocean cleanup is impossible.','But a system can remove waste from water.','We should not throw a mug away.','A fish can swallow small plastic.','The waste is mainly plastic.','We can use a mug many times.','A cleanup can start with one small action.','We can remove one piece of waste at a time.','We talk about what is possible.','We make a simple plan.','The plan is not impossible.','We decide not to throw useful things away.'],
fullTranslation:'「海の浄化は不可能だと考える人もいます。しかし、仕組みを使って水からごみを取り除くことができます。私たちはマグカップを捨てるべきではありません。魚は小さなプラスチックを飲み込んでしまうことがあります。そのごみは主にプラスチックです。私たちはマグカップを何度も使うことができます。浄化は1つの小さな行動から始めることができます。私たちは一度に1つのごみを取り除くことができます。私たちは何が可能かについて話します。私たちは簡単な計画を立てます。その計画は不可能ではありません。私たちは役立つ物を捨てないと決めます。」',
slashRows:[{en:'Some people think / ocean cleanup is / impossible.',jp:'人々の中には考えます / 海の浄化は〜だと / 不可能だと'},{en:'But / a system / can remove / waste / from water.',jp:'しかし / 仕組みは / 取り除くことができます / ごみを / 水から'},{en:'We should not / throw a mug away.',jp:'私たちは〜すべきではありません / マグカップを捨てる'},{en:'A fish / can swallow / small plastic.',jp:'魚は / 飲み込むことがあります / 小さなプラスチックを'},{en:'The waste is / mainly plastic.',jp:'そのごみは〜です / 主にプラスチック'},{en:'We can use / a mug / many times.',jp:'私たちは使うことができます / マグカップを / 何度も'},{en:'A cleanup / can start / with one small action.',jp:'浄化は / 始めることができます / 1つの小さな行動から'},{en:'We can remove / one piece of waste / at a time.',jp:'私たちは取り除くことができます / 1つのごみを / 一度に'},{en:'We talk about / what is possible.',jp:'私たちは話します / 何が可能かについて'},{en:'We make / a simple plan.',jp:'私たちは立てます / 簡単な計画を'},{en:'The plan is not / impossible.',jp:'その計画は〜ではありません / 不可能な'},{en:'We decide not to / throw useful things away.',jp:'私たちは〜しないと決めます / 役立つ物を捨てる'}],
questions:[{prompt:'1. 仕組みは水から何を取り除くことができますか。本文から英語で答えなさい。',answer:'waste',evidence:'But a system can remove waste from water.',evidenceJp:'仕組みを使って水からごみを取り除くことができます。',reason:'remove の目的語が waste です。'},{prompt:'2. 私たちは何を捨てるべきではありませんか。本文から英語で答えなさい。',answer:'a mug',evidence:'We should not throw a mug away.',evidenceJp:'私たちはマグカップを捨てるべきではありません。',reason:'throw A away のAが a mug です。'},{prompt:'3. 魚は何を飲み込んでしまうことがありますか。本文から英語で答えなさい。',answer:'small plastic',evidence:'A fish can swallow small plastic.',evidenceJp:'魚は小さなプラスチックを飲み込んでしまうことがあります。',reason:'swallow の目的語が small plastic です。'},{prompt:'4. ごみは主に何ですか。本文から英語で1語抜き出しなさい。',answer:'plastic',evidence:'The waste is mainly plastic.',evidenceJp:'そのごみは主にプラスチックです。',reason:'mainly の後ろが plastic です。'},{prompt:'5. 計画は不可能ですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'The plan is not impossible.',evidenceJp:'その計画は不可能ではありません。',reason:'not impossible と否定しているので No です。'}],
allowedWords:[["impossible / mug / throw A away / stew / swallow / waste / remove / mainly",'PROGRAM6 6-3: v7 canonical partition; stew retained but not forced'],['cleanup','PROGRAM6 textbook-body pool used'],['people / think / ocean / system / water / should not / fish / small / plastic / use / many times / start / one / action / piece / at a time / talk about / possible / make / simple / plan / decide / useful / thing','PROGRAM6 6-1/6-2 and earlier cumulative']],
auditNote:'最新v7正本PROGRAM6 6-3（ID3843-3850）とPROGRAM6教科書本文語彙のcleanupを照合。impossible / mug / throw A away / swallow / waste / remove / mainlyを使用。stewは海洋ごみテーマを壊すため無理に消化せず、PROGRAM7語彙は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
