const fs=require('fs');const vm=require('vm');
function filled(v){return typeof v==='string'&&v.trim().length>0}
function load(files,key){const c={window:{}};vm.createContext(c);for(const f of files){if(!fs.existsSync(f))throw new Error(`missing ${f}`);vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f})}return c.window[key]||{}}
const data=load(['v10_data_sunshine_g3_program5.js','v10_data_sunshine_g3_program5_fix.js'],'V10_PASSAGES_G3_SS');
const meta=load(['v10_interaction_metadata_sun_g3_p5.js'],'V10_INTERACTION_META_G3_SS_P5');
const expected=['PROGRAM 5-1','PROGRAM 5-2','PROGRAM 5-3'];const errors=[];let bq=0;
for(const k of expected)if(!data[k])errors.push(`missing passage ${k}`);for(const k of Object.keys(data))if(!expected.includes(k))errors.push(`unexpected passage ${k}`);
for(const [section,m] of Object.entries(data)){
 const tag=`SS3/${section}`;if(m.grade!=='3'||m.textbook!=='サンシャイン'||m.section!==section)errors.push(`${tag}: identity mismatch`);for(const k of ['id','title','fullTranslation','auditNote'])if(!filled(m[k]))errors.push(`${tag}: ${k} empty`);if(!Array.isArray(m.sentences)||m.sentences.length<10)errors.push(`${tag}: fewer than 10 sentences`);if(!Array.isArray(m.slashRows)||m.slashRows.length!==m.sentences.length)errors.push(`${tag}: slash count mismatch`);if(Array.isArray(m.slashRows)&&m.slashRows.some(r=>!r||!filled(r.en)||!filled(r.jp)))errors.push(`${tag}: empty slash row`);
 if(!Array.isArray(m.questions)||m.questions.length<3)errors.push(`${tag}: A questions short`);else m.questions.forEach((q,i)=>{for(const x of ['prompt','answer','evidence','evidenceJp','reason'])if(!filled(q[x]))errors.push(`${tag}: AQ${i+1} ${x} empty`);for(const p of String(q.evidence||'').split(' / ').map(x=>x.trim()).filter(Boolean))if(!m.sentences.includes(p))errors.push(`${tag}: AQ${i+1} evidence not verbatim: ${p}`)});for(const x of ['vocabAudit','manualSlashAudit','manualMeaningAudit','manualQuestionAudit'])if(m[x]!==true)errors.push(`${tag}: ${x} false`);
 const md=meta[`サンシャイン|3|${section}`];if(!md){errors.push(`${tag}: interaction metadata missing`);continue}if(!['diary','notice','email','report'].includes(md.genre))errors.push(`${tag}: genre invalid`);if(!Array.isArray(md.questionSetB)||md.questionSetB.length<3)errors.push(`${tag}: B questions short`);else md.questionSetB.forEach((q,i)=>{bq++;for(const x of ['prompt','answer','evidence','evidenceJp','reason'])if(!filled(q[x]))errors.push(`${tag}: BQ${i+1} ${x} empty`);for(const p of String(q.evidence||'').split(' / ').map(x=>x.trim()).filter(Boolean))if(!m.sentences.includes(p))errors.push(`${tag}: BQ${i+1} evidence not verbatim: ${p}`)});
}
function text(section){return ` ${(data[section].sentences||[]).join(' ').toLowerCase()} `}
const p52=[' begun ',' neck ',' improve ',' male ',' consume ',' female ',' european ',' graph ',' century ',' solid ',' trunk ',' british ',' stripe '];
const p53=[' perfect ',' package ',' look for ',' movement ',' be forced to ',' image ',' serve ',' farm ',' yard ',' fair trade ',' powder ',' magazine ',' flavor ',' scene ',' combination ',' dark ',' side ',' dramatic ',' price ',' unfairly '];
const p6=['get caught in',' patch ','leave a behind',' trash ','it is said that',' net ',' kill ',' ice ',' gather ',' bottle ',' contain ',' plastic ',' ton ',' mostly ',' researcher ',' canadian ',' collect ',' system ','at the age of',' balloon ',' hurt ',' shocked ',' dive ',' impossible ',' mug ','throw a away',' stew ',' swallow ',' waste ',' remove ',' mainly ',' cleanup ',' greece ',' npo ',' anyone ','even if',' suggestion '," i'm sure ",' challenge ',' item ',' measure ',' choice ',' leftover ',' fashionable ',' purpose ',' instant ',' extra ',' compact ',' sdgs '," what's more "];
const future={'PROGRAM 5-1':[...p52,...p53,...p6],'PROGRAM 5-2':[...p53,...p6],'PROGRAM 5-3':p6};
for(const [section,terms] of Object.entries(future)){const t=text(section);for(const term of terms)if(t.includes(term))errors.push(`SS3/${section}: future-vocab leak ${term.trim()}`)}
const forbidden=['regards','crushes','websites','topics','cacaos','improves','consumes','graphs','centuries','packages','movements','images','serves','farms','yards','magazines','flavors','scenes','combinations','prices'];
for(const [section,m] of Object.entries(data)){const t=(m.sentences||[]).join(' ').toLowerCase();for(const term of forbidden)if(new RegExp(`\\b${term}\\b`).test(t))errors.push(`SS3/${section}: unsupported form ${term}`)}
console.log(`G3 SS P5 AUDIT passages=${Object.keys(data).length}/${expected.length} alternate_questions=${bq}`);
console.log('G3 SS P5 CANONICAL v7=PROGRAM5 5-1 / 5-2 / 5-3 exact source partitions; PROGRAM6 vocabulary gated');
if(errors.length){console.error(`G3 SS P5 AUDIT FAIL ${errors.length}`);for(const e of errors)console.error(`- ${e}`);process.exit(1)}
console.log('G3 SS P5 AUDIT PASS: Program 5 passages, slash rows, A/B questions, evidence links, release flags, morphology guard, chronological partitions, and Program 6 future-vocab gate are consistent.');
