window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 5-1']={
 id:'V10-SS-G2-P5-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 5-1',level:'HOP',title:'My First Day at the Shop',
 sentences:['Today, I work at a shop.','The director can tell me what to do.','First, I learn how to handle a book.','I also learn where to put it.','There is a shelf near me.','There are shelves by the wall.','I put a book on this shelf by mistake.','The director can help me.','At noon, I know when to take a coffee break.','There is a vending machine near the shop.','I buy water there.','After the break, I know what to do.','I can handle the work.','I want to work here again.'],
 fullTranslation:'「今日、私は店で仕事をします。店長が私に何をすればよいか教えてくれます。まず、本をどう扱えばよいか学びます。また、それをどこに置けばよいかも学びます。私の近くに棚が1つあります。壁のそばにはいくつか棚があります。私はまちがって、この棚に本を置きます。店長が助けてくれます。正午になると、いつコーヒー休憩をとればよいか分かります。店の近くには自動販売機があります。そこで水を買います。休憩のあと、何をすればよいか分かります。私はその仕事を扱えるようになります。またここで働きたいです。」',
 slashRows:[{en:'Today, / I work / at a shop.',jp:'今日 / 私は働きます / 店で'},{en:'The director can tell / me / what to do.',jp:'店長は教えられます / 私に / 何をすればよいか'},{en:'First, / I learn / how to handle / a book.',jp:'まず / 私は学びます / どう扱うか / 本を'},{en:'I also learn / where to put / it.',jp:'私はまた学びます / どこに置くか / それを'},{en:'There is / a shelf / near me.',jp:'あります / 棚が1つ / 私の近くに'},{en:'There are / shelves / by the wall.',jp:'あります / 棚が / 壁のそばに'},{en:'I put / a book / on this shelf / by mistake.',jp:'私は置きます / 本を / この棚に / まちがって'},{en:'The director can help / me.',jp:'店長は助けられます / 私を'},{en:'At noon, / I know / when to take / a coffee break.',jp:'正午に / 私は分かります / いつ取るか / コーヒー休憩を'},{en:'There is / a vending machine / near the shop.',jp:'あります / 自動販売機が / 店の近くに'},{en:'I buy / water / there.',jp:'私は買います / 水を / そこで'},{en:'After the break, / I know / what to do.',jp:'休憩のあと / 私は分かります / 何をすればよいか'},{en:'I can handle / the work.',jp:'私は扱えます / その仕事を'},{en:'I want to work / here / again.',jp:'私は働きたいです / ここで / また'}],
 questions:[{prompt:'1. 誰が話し手に何をすればよいか教えますか。本文から英語で答えなさい。',answer:'The director',evidence:'The director can tell me what to do.',evidenceJp:'店長が私に何をすればよいか教えてくれます。',reason:'文の主語 The director が教える人です。'},{prompt:'2. 話し手は最初に何をどう扱うか学びますか。本文から英語で答えなさい。',answer:'a book',evidence:'First, I learn how to handle a book.',evidenceJp:'まず、本をどう扱えばよいか学びます。',reason:'handle の目的語が a book です。'},{prompt:'3. 壁のそばには何がありますか。本文から英語で答えなさい。',answer:'shelves',evidence:'There are shelves by the wall.',evidenceJp:'壁のそばには棚があります。',reason:'There are の後ろが shelves です。'},{prompt:'4. いつコーヒー休憩をとるか分かるのは何時ごろですか。本文から英語で答えなさい。',answer:'At noon',evidence:'At noon, I know when to take a coffee break.',evidenceJp:'正午になると、いつコーヒー休憩をとればよいか分かります。',reason:'At noon が時を表しています。'},{prompt:'5. 店の近くに何がありますか。本文から英語で答えなさい。',answer:'a vending machine',evidence:'There is a vending machine near the shop.',evidenceJp:'店の近くには自動販売機があります。',reason:'There is の後ろが a vending machine です。'}],
 allowedWords:[['run / short / director / site / must / shelf-shelves / by mistake / handle / how to ~ / where to ~ / when to ~ / what to ~ / coffee break / vending machine','PROGRAM 5-1: canonical Sheet IDs 3110-3123'],['learn / put / wall / noon / buy / water / work / help / know / after / break / want to / again','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でSunshine中2 PROGRAM 5-1をID3110〜3123まで直接照合。how to / where to / when to / what to と、正本に shelf-shelves として表層登録された複数形 shelves を仕事体験の1場面で使用。run / site / short / must は無理な消化を避け未使用または累積扱い。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 5-2']={
 id:'V10-SS-G2-P5-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 5-2',level:'HOP',title:'Take Action in an Earthquake',
 sentences:['Today, an architect visits our school.','We learn about an earthquake.','A strong earthquake can be dangerous.','We must take action.','During an earthquake, the elevator can be dangerous.','In particular, we must not use the elevator.','We choose a safe place.','We decide to remember the safety rule.','We try to remember it.','We practice again and again.','While we practice, the architect can guide us.','Earthquake safety is especially important.','An international organization can help people.','We want to prevent trouble.','We decide to learn more.'],
 fullTranslation:'「今日、建築家が私たちの学校を訪れます。私たちは地震について学びます。強い地震は危険なことがあります。私たちは行動を起こさなければなりません。地震の間、エレベーターは危険なことがあります。特に、エレベーターを使ってはいけません。私たちは安全な場所を選びます。安全の規則を覚えることに決めます。それを覚えようとします。何度も練習します。練習している間、建築家が私たちを案内できます。地震の安全は特に重要です。国際的な組織は人々を助けることができます。私たちは問題を防ぎたいです。もっと学ぶことに決めます。」',
 slashRows:[{en:'Today, / an architect visits / our school.',jp:'今日 / 建築家が訪れます / 私たちの学校を'},{en:'We learn about / an earthquake.',jp:'私たちは学びます / 地震について'},{en:'A strong earthquake can be / dangerous.',jp:'強い地震は〜なことがあります / 危険な'},{en:'We must take action.',jp:'私たちは行動を起こさなければなりません'},{en:'During an earthquake, / the elevator can be / dangerous.',jp:'地震の間 / エレベーターは〜なことがあります / 危険な'},{en:'In particular, / we must not use / the elevator.',jp:'特に / 私たちは使ってはいけません / エレベーターを'},{en:'We choose / a safe place.',jp:'私たちは選びます / 安全な場所を'},{en:'We decide to remember / the safety rule.',jp:'私たちは覚えることに決めます / 安全の規則を'},{en:'We try to remember / it.',jp:'私たちは覚えようとします / それを'},{en:'We practice / again and again.',jp:'私たちは練習します / 何度も'},{en:'While we practice, / the architect can guide / us.',jp:'私たちが練習している間 / 建築家は案内できます / 私たちを'},{en:'Earthquake safety is / especially important.',jp:'地震の安全は〜です / 特に重要な'},{en:'An international organization can help / people.',jp:'国際的な組織は助けられます / 人々を'},{en:'We want to prevent / trouble.',jp:'私たちは防ぎたいです / 問題を'},{en:'We decide to learn / more.',jp:'私たちは学ぶことに決めます / もっと'}],
 questions:[{prompt:'1. 誰が学校を訪れますか。本文から英語で答えなさい。',answer:'an architect',evidence:'Today, an architect visits our school.',evidenceJp:'今日、建築家が私たちの学校を訪れます。',reason:'文の主語が an architect です。'},{prompt:'2. 強い地震はどのようなものになりえますか。本文から英語で1語抜き出しなさい。',answer:'dangerous',evidence:'A strong earthquake can be dangerous.',evidenceJp:'強い地震は危険なことがあります。',reason:'dangerous が earthquake を説明しています。'},{prompt:'3. 地震のとき、何を使ってはいけませんか。本文から英語で答えなさい。',answer:'the elevator',evidence:'In particular, we must not use the elevator.',evidenceJp:'特に、エレベーターを使ってはいけません。',reason:'use の目的語が the elevator です。'},{prompt:'4. 何度くらい練習しますか。本文から英語で答えなさい。',answer:'again and again',evidence:'We practice again and again.',evidenceJp:'何度も練習します。',reason:'again and again が反復を表しています。'},{prompt:'5. 何を防ぎたいですか。本文から英語で答えなさい。',answer:'trouble',evidence:'We want to prevent trouble.',evidenceJp:'私たちは問題を防ぎたいです。',reason:'prevent の目的語が trouble です。'}],
 allowedWords:[['architect / especially / choose / prevent / earthquake / decide to ~ / take action / certain / while / during / elevator / strong / dangerous / almost / in particular / again and again / international organization / try to ~','PROGRAM 5-2: canonical Sheet IDs 3124-3141'],['must / rule / guide / trouble','PROGRAM 4 cumulative'],['school / learn / safe / place / remember / practice / important / help / people / want to / more / use','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 5-2をID3124〜3141まで直接照合。take action / during / in particular / decide to / try to / while / again and again / international organizationを地震時の行動という1場面に統合。certain / almost は無理に入れていない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 5-3']={
 id:'V10-SS-G2-P5-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 5-3',level:'HOP',title:'A Postcard and a Book',
 sentences:['Yesterday, I gave my friend a postcard.','I sent my friend a message, too.','I lent my friend a book.','The book was about a volunteer.','It was about a U.N. worker, too.','My friend gave me good advice.','I want to make use of the advice.','After a while, I was sleepy.','At home, I fall asleep easily.','Today, I read the book again.','I make use of the book for my project.','I remember the postcard.','I send a message to my friend.','Thanks for your help.'],
 fullTranslation:'「昨日、私は友達にはがきを渡しました。友達にメッセージも送りました。友達に本を貸しました。その本はボランティアについてのものでした。国連で働く人についての本でもありました。友達は私によい助言をくれました。私はその助言を活用したいです。しばらくすると眠くなりました。家では私は簡単に眠りにつきます。今日、その本をもう一度読みます。プロジェクトのためにその本を活用します。はがきを覚えています。友達にメッセージを送ります。手伝ってくれてありがとう。」',
 slashRows:[{en:'Yesterday, / I gave / my friend / a postcard.',jp:'昨日 / 私は渡しました / 友達に / はがきを'},{en:'I sent / my friend / a message, too.',jp:'私は送りました / 友達に / メッセージも'},{en:'I lent / my friend / a book.',jp:'私は貸しました / 友達に / 本を'},{en:'The book was / about a volunteer.',jp:'その本は〜でした / ボランティアについての'},{en:'It was / about a U.N. worker, too.',jp:'それは〜でもありました / 国連で働く人についての'},{en:'My friend gave / me / good advice.',jp:'友達はくれました / 私に / よい助言を'},{en:'I want to make use of / the advice.',jp:'私は活用したいです / その助言を'},{en:'After a while, / I was / sleepy.',jp:'しばらくすると / 私は〜でした / 眠い'},{en:'At home, / I fall asleep / easily.',jp:'家で / 私は眠りにつきます / 簡単に'},{en:'Today, / I read / the book / again.',jp:'今日 / 私は読みます / その本を / また'},{en:'I make use of / the book / for my project.',jp:'私は活用します / その本を / プロジェクトのために'},{en:'I remember / the postcard.',jp:'私は覚えています / そのはがきを'},{en:'I send / a message / to my friend.',jp:'私は送ります / メッセージを / 友達に'},{en:'Thanks for / your help.',jp:'ありがとう / あなたの助けを'}],
 questions:[{prompt:'1. 昨日、友達に何を渡しましたか。本文から英語で答えなさい。',answer:'a postcard',evidence:'Yesterday, I gave my friend a postcard.',evidenceJp:'昨日、私は友達にはがきを渡しました。',reason:'gave の目的語が a postcard です。'},{prompt:'2. 友達に何を送りましたか。本文から英語で答えなさい。',answer:'a message',evidence:'I sent my friend a message, too.',evidenceJp:'友達にメッセージも送りました。',reason:'sent の目的語が a message です。'},{prompt:'3. 友達に何を貸しましたか。本文から英語で答えなさい。',answer:'a book',evidence:'I lent my friend a book.',evidenceJp:'友達に本を貸しました。',reason:'lent の目的語が a book です。'},{prompt:'4. 友達は何をくれましたか。本文から英語で答えなさい。',answer:'good advice',evidence:'My friend gave me good advice.',evidenceJp:'友達は私によい助言をくれました。',reason:'gave の目的語が good advice です。'},{prompt:'5. 話し手は助言をどうしたいですか。本文から英語で答えなさい。',answer:'make use of the advice',evidence:'I want to make use of the advice.',evidenceJp:'私はその助言を活用したいです。',reason:'want to の後ろが make use of the advice です。'}],
 allowedWords:[['advice / U.N. / send-sent / lend-lent / fall asleep / make use of ~ / give-gave / postcard / after a while / volunteer / according / respect / broadcast','PROGRAM 5-3: canonical Sheet IDs 3142-3154'],['easily','PROGRAM 3-3 cumulative'],['friend / message / book / worker / good / want to / sleepy / at home / today / read / again / project / remember / help / Thanks for ~','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 5-3をID3142〜3154まで直接照合。give-gave / send-sent / lend-lent は正本に過去形表層が明示登録されているため使用。fall asleep は登録原形のまま現在文で使用し、fell asleep のような未登録過去形は生成していない。according / respect / broadcastは無理な消化を避け未使用。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
