const {JSDOM,VirtualConsole}=require('jsdom');
function vals(el){return[...el.options].map(o=>o.value)}function assert(c,m){if(!c)throw new Error(m)}function change(w,el,v){el.value=v;el.dispatchEvent(new w.Event('change',{bubbles:true}))}
(async()=>{const errs=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errs.push(String(e&&e.message||e)));const dom=await JSDOM.fromFile('v10_stage2.html',{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc});await new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error('load timeout')),15000);dom.window.addEventListener('load',()=>{clearTimeout(t);setTimeout(res,120)},{once:true})});const w=dom.window,d=w.document,tb=d.getElementById('textbook'),grade=d.getElementById('grade'),major=d.getElementById('major'),section=d.getElementById('section'),pattern=d.getElementById('pattern'),alt=d.getElementById('altSetBtn');assert(tb&&grade&&major&&section&&pattern&&alt,'stage2 controls missing');assert(!d.getElementById('period'),'month filter returned');assert(vals(grade).join(',')==='1,2','grade options must be G1,G2');

// G1 Sunshine regression
change(w,major,'Get Ready');change(w,section,'Get Ready 6');change(w,pattern,'diary');assert(d.getElementById('passage').textContent.includes('Lunch and the Zoo'),'G1 Sunshine diary did not select GR6');assert(!alt.disabled,'G1 GR6 B set should be enabled');const a=d.getElementById('questions').textContent;alt.click();const b=d.getElementById('questions').textContent;assert(a!==b&&b.includes('問題セット B'),'G1 B set did not differ from A');
change(w,pattern,'report');assert(d.getElementById('passage').textContent.includes('Basketball in the Gym'),'G1 report should select latest reviewed report within Get Ready ceiling');assert(d.getElementById('gate').textContent.includes('Get Ready 4'),'G1 fallback source section not surfaced');
change(w,pattern,'notice');assert(d.getElementById('gate').textContent.includes('まだありません'),'G1 unavailable genre should stop clearly');assert(!d.getElementById('passage').textContent.trim(),'G1 unavailable genre must not fall back to unrelated passage');

// G1 New Horizon regression
change(w,tb,'ニューホライズン');change(w,major,'Unit 1');change(w,section,'Unit 1-3');change(w,pattern,'email');assert(d.getElementById('passage').textContent.includes('Comics and Clubs'),'G1 NH Unit1-3 email selection failed');assert(!alt.disabled,'G1 NH Unit1-3 B set should be enabled');
change(w,major,'Unit 2');change(w,section,'Unit 2-3');change(w,pattern,'email');assert(d.getElementById('passage').textContent.includes('Your Book and Notebook'),'G1 Unit2 email selection should render Unit 2-3');assert(!alt.disabled,'G1 Unit2-3 B set should be enabled');
change(w,major,'Unit 4');change(w,section,'Unit 4-3');change(w,pattern,'notice');assert(d.getElementById('gate').textContent.includes('まだありません'),'G1 Unit4 notice should remain unavailable');assert(!d.getElementById('passage').textContent.trim(),'G1 unavailable Unit4 notice must not fall back outside major');

// G2 Sunshine integration
change(w,tb,'サンシャイン');change(w,grade,'2');assert(vals(major).includes('PROGRAM 8'),'G2 Sunshine PROGRAM 8 missing from major selector');change(w,major,'PROGRAM 8');assert(vals(section).join(',')==='PROGRAM 8-1,PROGRAM 8-2,PROGRAM 8-3','G2 Sunshine PROGRAM 8 canonical three parts changed');change(w,section,'PROGRAM 8-3');change(w,pattern,'report');assert(d.getElementById('passage').textContent.trim(),'G2 Sunshine PROGRAM 8-3 report failed to render');assert(d.getElementById('passage').textContent.includes('中2'),'G2 Sunshine rendered wrong grade');assert(!alt.disabled,'G2 Sunshine B set should be enabled');const ssa=d.getElementById('questions').textContent;alt.click();const ssb=d.getElementById('questions').textContent;assert(ssa!==ssb&&ssb.includes('問題セット B'),'G2 Sunshine B set switch failed');

// G2 New Horizon through Unit 7
change(w,tb,'ニューホライズン');assert(vals(major).includes('Unit 7'),'G2 New Horizon Unit 7 missing from major selector');change(w,major,'Unit 7');assert(vals(section).join(',')==='Unit 7-1,Unit 7-2,Unit 7-3,Unit 7-4','G2 NH Unit 7 canonical four sections changed');change(w,section,'Unit 7-4');change(w,pattern,'report');assert(d.getElementById('passage').textContent.includes('Protecting a Mountain Heritage Site'),'G2 NH Unit 7-4 failed to render');assert(d.getElementById('passage').textContent.includes('中2'),'G2 NH rendered wrong grade');assert(!alt.disabled,'G2 NH Unit7 B set should be enabled');const nha=d.getElementById('questions').textContent;alt.click();const nhb=d.getElementById('questions').textContent;assert(nha!==nhb&&nhb.includes('問題セット B'),'G2 NH B set switch failed');assert(d.getElementById('gate').textContent.includes('品質ゲート通過'),'G2 NH Unit7 release gate did not pass');

// Switching back must restore G1 data, not leak G2
change(w,grade,'1');assert(vals(major).includes('Unit 10'),'switching back to G1 did not restore NH G1 majors');assert(!vals(major).includes('Unit 0')||vals(major).includes('Unit 10'),'G1 selector corrupted after grade switch');
assert(vals(pattern).join(',')==='all,diary,notice,email,report','pattern options changed');assert(d.getElementById('printBtn'),'print control missing');assert(errs.length===0,`browser errors: ${errs.join(' | ')}`);console.log('STAGE2 DOM PASS: G1/G2 grade switching, textbook > major > minor selection, genre fallback rules, A/B question switching, Unit7 release gate, and print control behave correctly.');dom.window.close()})().catch(e=>{console.error(`STAGE2 DOM FAIL: ${e.stack||e}`);process.exit(1)});
