window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 2-1']={
id:'V10-SS-G3-P2-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 2-1',level:'HOP',title:'Good Sleep and Health',
sentences:["You've just finished your homework.",'It is already late.','A lack of sleep can affect your health.','You have not gone to bed yet.','A regular sleep time is important.','Do not be in a hurry tonight.','Take at least a few minutes to relax.','Then go to bed at a regular time.','Sleep tight tonight.','Good sleep can affect your day.','Your health is important every day.','You have already done enough for tonight.'],
fullTranslation:'「あなたはちょうど宿題を終えたところです。もう遅い時間です。睡眠不足は健康に影響を与えることがあります。あなたはまだ寝ていません。規則正しい睡眠時間は大切です。今夜は急がないでください。少なくとも数分はリラックスする時間をとりましょう。それから規則正しい時間に寝ましょう。今夜はぐっすり眠ってください。よい睡眠は一日に影響を与えることがあります。健康は毎日大切です。今夜の分はもう十分にやりました。」',
slashRows:[{en:"You've just finished / your homework.",jp:'あなたはちょうど終えました / 宿題を'},{en:'It is / already / late.',jp:'もう〜です / すでに / 遅い'},{en:'A lack of sleep / can affect / your health.',jp:'睡眠不足は / 影響を与えることがあります / 健康に'},{en:'You have not gone to bed / yet.',jp:'あなたは寝ていません / まだ'},{en:'A regular sleep time is / important.',jp:'規則正しい睡眠時間は〜です / 大切'},{en:'Do not be / in a hurry / tonight.',jp:'〜しないでください / 急いで / 今夜'},{en:'Take / at least a few minutes / to relax.',jp:'とってください / 少なくとも数分を / リラックスするために'},{en:'Then go to bed / at a regular time.',jp:'それから寝てください / 規則正しい時間に'},{en:'Sleep tight / tonight.',jp:'ぐっすり眠ってください / 今夜'},{en:'Good sleep / can affect / your day.',jp:'よい睡眠は / 影響を与えることがあります / 一日に'},{en:'Your health is / important / every day.',jp:'あなたの健康は〜です / 大切 / 毎日'},{en:'You have already done / enough / for tonight.',jp:'あなたはもうしました / 十分に / 今夜の分を'}],
questions:[{prompt:'1. 何をちょうど終えたところですか。本文から英語で答えなさい。',answer:'your homework',evidence:"You've just finished your homework.",evidenceJp:'あなたはちょうど宿題を終えたところです。',reason:'finished の目的語が your homework です。'},{prompt:'2. 何が健康に影響を与えることがありますか。本文から英語で答えなさい。',answer:'a lack of sleep',evidence:'A lack of sleep can affect your health.',evidenceJp:'睡眠不足は健康に影響を与えることがあります。',reason:'can affect の主語が A lack of sleep です。'},{prompt:'3. もう寝ましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'You have not gone to bed yet.',evidenceJp:'あなたはまだ寝ていません。',reason:'not ... yet とあるので No です。'},{prompt:'4. 今夜はどのような状態にならないようにしますか。本文から英語で答えなさい。',answer:'in a hurry',evidence:'Do not be in a hurry tonight.',evidenceJp:'今夜は急がないでください。',reason:'be の後ろが in a hurry です。'},{prompt:'5. 今夜どのように眠るように言っていますか。本文から英語で1語抜き出しなさい。',answer:'tight',evidence:'Sleep tight tonight.',evidenceJp:'今夜はぐっすり眠ってください。',reason:'Sleep を説明する語が tight です。'}],
allowedWords:[["just / lack / already / health / yet / regular / affect / tonight / at least / tight / in a hurry / you've",'PROGRAM2 2-1: v7 canonical Sheet IDs 3603-3614'],['finish / homework / late / sleep / can / important / take / minute / relax / then / go to bed / time / good / day / every day / done / enough','G1-G2 and PROGRAM1 cumulative']],
auditNote:'最新v7正本PROGRAM2 2-1（Sheet ID3603〜3614）を直接照合。just / lack / already / health / yet / regular / affect / tonight / at least / tight / in a hurry / you’veを、睡眠と健康についての助言文に統合。2-2のfor / since / habit / concentrate on / keep a diary等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 2-2']={
id:'V10-SS-G3-P2-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 2-2',level:'HOP',title:'My Sleep Habit',
sentences:['I have had this sleep habit for two months.','I have used this diary since April.','Right now, I keep a diary every night.','My plan is based on a regular sleep time.','I concentrate on sleep before a test.','The diary is full of my sleep time.','I write in it every morning.','This habit is good for my health.','I have been careful about sleep for many weeks.','Since April, I have gone to bed at a regular time.','Right now, I feel better in the morning.','I want to keep this habit.'],
fullTranslation:'「私はこの睡眠習慣を2か月続けています。4月からこの日記を使っています。今は毎晩日記をつけています。私の計画は規則正しい睡眠時間に基づいています。テストの前には睡眠に集中します。その日記は私の睡眠時間の記録でいっぱいです。私は毎朝そこに書きます。この習慣は健康によいです。私は何週間も睡眠に気をつけています。4月から規則正しい時間に寝ています。今は朝の調子がよくなっています。私はこの習慣を続けたいです。」',
slashRows:[{en:'I have had / this sleep habit / for two months.',jp:'私は続けています / この睡眠習慣を / 2か月間'},{en:'I have used / this diary / since April.',jp:'私は使っています / この日記を / 4月から'},{en:'Right now, / I keep a diary / every night.',jp:'今は / 私は日記をつけます / 毎晩'},{en:'My plan is based on / a regular sleep time.',jp:'私の計画は基づいています / 規則正しい睡眠時間に'},{en:'I concentrate on / sleep / before a test.',jp:'私は集中します / 睡眠に / テストの前に'},{en:'The diary is full of / my sleep time.',jp:'その日記はいっぱいです / 私の睡眠時間の記録で'},{en:'I write / in it / every morning.',jp:'私は書きます / そこに / 毎朝'},{en:'This habit is / good / for my health.',jp:'この習慣は〜です / よい / 健康にとって'},{en:'I have been / careful about sleep / for many weeks.',jp:'私は気をつけています / 睡眠について / 何週間も'},{en:'Since April, / I have gone to bed / at a regular time.',jp:'4月から / 私は寝ています / 規則正しい時間に'},{en:'Right now, / I feel / better / in the morning.',jp:'今は / 私は感じます / よりよく / 朝に'},{en:'I want to keep / this habit.',jp:'私は続けたいです / この習慣を'}],
questions:[{prompt:'1. この睡眠習慣をどのくらい続けていますか。本文から英語で答えなさい。',answer:'for two months',evidence:'I have had this sleep habit for two months.',evidenceJp:'私はこの睡眠習慣を2か月続けています。',reason:'期間を表す部分が for two months です。'},{prompt:'2. いつから日記を使っていますか。本文から英語で答えなさい。',answer:'since April',evidence:'I have used this diary since April.',evidenceJp:'4月からこの日記を使っています。',reason:'開始時点を表す部分が since April です。'},{prompt:'3. 今は毎晩何をしていますか。本文から英語で答えなさい。',answer:'keep a diary',evidence:'Right now, I keep a diary every night.',evidenceJp:'今は毎晩日記をつけています。',reason:'Right now の後ろの行動が keep a diary です。'},{prompt:'4. 計画は何に基づいていますか。本文から英語で答えなさい。',answer:'a regular sleep time',evidence:'My plan is based on a regular sleep time.',evidenceJp:'私の計画は規則正しい睡眠時間に基づいています。',reason:'be based on の後ろが a regular sleep time です。'},{prompt:'5. テストの前には何に集中しますか。本文から英語で答えなさい。',answer:'sleep',evidence:'I concentrate on sleep before a test.',evidenceJp:'テストの前には睡眠に集中します。',reason:'concentrate on の後ろが sleep です。'}],
allowedWords:[["for ~ / right now / since ~ / be based on ~ / habit / concentrate on ~ / be full of ~ / keep a diary",'PROGRAM2 2-2: v7 canonical Sheet IDs 3615-3622'],['sleep / month / use / diary / April / every night / plan / regular / time / before / test / write / every morning / good / health / been / careful / week / go to bed / feel / better / morning / want to / keep','PROGRAM2 2-1 and G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM2 2-2（Sheet ID3615〜3622）を直接照合。for / sinceを現在完了の継続に使い、right now / be based on / habit / concentrate on / be full of / keep a diaryを睡眠習慣の記録に統合。2-3のhair / position / as a result / title / introduce / rope / dry / bright / tour / thus / tournamentは先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 2-3']={
id:'V10-SS-G3-P2-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 2-3',level:'HOP',title:'Good Sleep before a Tournament',
sentences:['Our team is on a tour for a tournament.','The title of our plan is Good Sleep.','First, I introduce a good sleep position.','We use a rope to mark the position on the floor.','After practice, we dry our hair before bed.','The room is bright, so we turn off the light.','As a result, we can sleep well.','Thus, we have more energy in the morning.','The tournament starts tomorrow.','We keep the same sleep position at the hotel.','The tour is busy, but sleep is important.','Good sleep helps us during the tournament.'],
fullTranslation:'「私たちのチームは大会のための遠征中です。私たちの計画のタイトルは『よい睡眠』です。まず、私はよい睡眠の姿勢を紹介します。床にその位置を示すためにロープを使います。練習のあと、寝る前に髪を乾かします。部屋は明るいので、明かりを消します。その結果、よく眠ることができます。したがって、朝にはより多くの元気があります。大会は明日始まります。ホテルでも同じ睡眠姿勢を保ちます。遠征は忙しいですが、睡眠は大切です。よい睡眠は大会中の私たちを助けます。」',
slashRows:[{en:'Our team is / on a tour / for a tournament.',jp:'私たちのチームは〜です / 遠征中 / 大会のための'},{en:'The title / of our plan / is Good Sleep.',jp:'タイトルは / 私たちの計画の / 「よい睡眠」です'},{en:'First, / I introduce / a good sleep position.',jp:'まず / 私は紹介します / よい睡眠姿勢を'},{en:'We use / a rope / to mark the position / on the floor.',jp:'私たちは使います / ロープを / 位置を示すために / 床に'},{en:'After practice, / we dry / our hair / before bed.',jp:'練習のあと / 私たちは乾かします / 髪を / 寝る前に'},{en:'The room is / bright, / so / we turn off the light.',jp:'部屋は〜です / 明るい / だから / 私たちは明かりを消します'},{en:'As a result, / we can sleep / well.',jp:'その結果 / 私たちは眠れます / よく'},{en:'Thus, / we have / more energy / in the morning.',jp:'したがって / 私たちにはあります / より多くの元気が / 朝に'},{en:'The tournament starts / tomorrow.',jp:'大会は始まります / 明日'},{en:'We keep / the same sleep position / at the hotel.',jp:'私たちは保ちます / 同じ睡眠姿勢を / ホテルで'},{en:'The tour is / busy, / but sleep is important.',jp:'その遠征は〜です / 忙しい / しかし睡眠は大切です'},{en:'Good sleep helps / us / during the tournament.',jp:'よい睡眠は助けます / 私たちを / 大会中に'}],
questions:[{prompt:'1. 何のための遠征中ですか。本文から英語で答えなさい。',answer:'a tournament',evidence:'Our team is on a tour for a tournament.',evidenceJp:'私たちのチームは大会のための遠征中です。',reason:'for の後ろが a tournament です。'},{prompt:'2. 計画のタイトルは何ですか。本文から英語で答えなさい。',answer:'Good Sleep',evidence:'The title of our plan is Good Sleep.',evidenceJp:'私たちの計画のタイトルは「よい睡眠」です。',reason:'title の内容が Good Sleep です。'},{prompt:'3. 何を紹介しますか。本文から英語で答えなさい。',answer:'a good sleep position',evidence:'First, I introduce a good sleep position.',evidenceJp:'まず、私はよい睡眠の姿勢を紹介します。',reason:'introduce の目的語が a good sleep position です。'},{prompt:'4. 練習のあと、何を乾かしますか。本文から英語で答えなさい。',answer:'our hair',evidence:'After practice, we dry our hair before bed.',evidenceJp:'練習のあと、寝る前に髪を乾かします。',reason:'dry の目的語が our hair です。'},{prompt:'5. その結果、何ができますか。本文から英語で答えなさい。',answer:'sleep well',evidence:'As a result, we can sleep well.',evidenceJp:'その結果、よく眠ることができます。',reason:'can の後ろが sleep well です。'}],
allowedWords:[["hair / position / as a result / title / introduce / rope / dry / bright / tour / thus / tournament",'PROGRAM2 2-3: v7 canonical Sheet IDs 3623-3633'],['team / plan / good / sleep / first / use / mark / floor / after / practice / before / bed / room / so / turn off / light / can / well / more / energy / morning / tomorrow / keep / same / hotel / busy / important / help / during','PROGRAM2 2-1/2-2 and G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM2 2-3（Sheet ID3623〜3633）を直接照合。hair / position / as a result / title / introduce / rope / dry / bright / tour / thus / tournamentを、大会遠征で睡眠を整える説明文に統合。PROGRAM3以降の語彙は使用していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
