'use strict';
const fs=require('fs'),vm=require('vm');
const files=['v11_batch10_passages_draft_g1.js','v11_batch10_passages_draft_g2.js','v11_batch10_passages_draft_g3.js','v11_batch10_length_repair_r1.js','v11_batch10_grammar_repair_r1.js','v11_batch10_grammar_repair_r2.js','v11_batch10_length_repair_r2.js','v11_batch10_human_semantic_review_r1.js','v11_batch10_vocab_inventory.js','v11_batch10_prior_verified_gloss.js','v11_batch10_manual_gloss_r1.js','v11_batch10_gloss_apply.js','v11_batch10_vocab_residual_r2_apply.js','v11_batch10_question_human_rewrite.js','v11_batch10_question_human_rewrite_r2.js'];
const s={window:{},console};s.globalThis=s.window;vm.createContext(s);for(const f of files)vm.runInContext(fs.readFileSync(f,'utf8'),s,{filename:f});
const ps=[...(s.window.V11_BATCH10_G1_DRAFTS||[]),...(s.window.V11_BATCH10_G2_DRAFTS||[]),...(s.window.V11_BATCH10_G3_DRAFTS||[])];
const fail=[],rows=[];const wc=x=>(String(x||'').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;let totalQuestions=0;
function bad(id,gate,detail){fail.push({id,gate,detail});}
for(const p of ps){
 if(p.semanticReview!=='BATCH10_HUMAN_REVIEW_20260829'||p.semanticReviewStatus!=='READ_FULL_BODY_TRANSLATION_QUESTIONS'||p.semanticReviewRegistered!==false)bad(p.id,'semantic_review','missing/invalid Batch10 human-review marker');
 if(p.questionStage!=='BATCH10_HUMAN_REWRITE_R2'||p.questionHumanReview!=='FULL_50_PASSAGE_REVIEW_20260829')bad(p.id,'question_stage',`${p.questionStage||''}/${p.questionHumanReview||''}`);
 if(!Array.isArray(p.sentences)||!Array.isArray(p.slashRows)||p.sentences.length!==p.slashRows.length)bad(p.id,'slash_shape','sentence/slash length mismatch');
 else for(let i=0;i<p.sentences.length;i++)if(String(p.sentences[i])!==String(p.slashRows[i]&&p.slashRows[i].en))bad(p.id,'slash_en',`row ${i+1} English mismatch`);
 const rebuilt=(p.slashRows||[]).map(r=>String(r&&r.jp||'')).join('');if(String(p.fullTranslation||'')!==rebuilt)bad(p.id,'full_translation','fullTranslation != slash JP join');
 const actual=wc((p.sentences||[]).join(' '));if(actual!==Number(p.wordCount))bad(p.id,'word_count',`stored ${p.wordCount} actual ${actual}`);const band=p.targetWordBand||[];if(band.length===2&&(actual<band[0]||actual>band[1]))bad(p.id,'word_band',`${actual} outside ${band[0]}-${band[1]}`);
 for(const [name,qs] of [['A',p.questions],['B',p.questionSetB]]){if(!Array.isArray(qs)||qs.length!==5){bad(p.id,`${name}_count`,String(qs&&qs.length));continue;}totalQuestions+=qs.length;qs.forEach((q,i)=>{if(!q||!String(q.prompt||'').trim())bad(p.id,`${name}_prompt`,String(i+1));if(!String(q.answer||'').trim())bad(p.id,`${name}_answer`,String(i+1));if(!String(q.evidence||'').trim())bad(p.id,`${name}_evidence`,String(i+1));if(!String(q.evidenceJp||'').trim())bad(p.id,`${name}_evidenceJp`,String(i+1));if(!String(q.reason||'').trim())bad(p.id,`${name}_reason`,String(i+1));if(/第\s*\d+\s*(?:文|段階)|sentence\s*\d+/i.test(String(q.prompt||'')))bad(p.id,`${name}_mechanical_scaffold`,`${i+1}:${q.prompt}`);const k=(p.sentences||[]).indexOf(q.evidence);if(k<0)bad(p.id,`${name}_evidence_source`,`${i+1}:${q.evidence}`);else if(String(p.slashRows[k].jp)!==String(q.evidenceJp))bad(p.id,`${name}_evidence_sync`,`${i+1}: row ${k+1}`);if(q.questionType==='FREE_WRITE_20_30'){const n=wc(q.answer);if(n<20||n>30)bad(p.id,'free_write_length',`${n} words`);if(!q.scoring||!Array.isArray(q.scoring.conditions)||q.scoring.conditions.length<3)bad(p.id,'free_write_scoring','missing explicit conditions');}});}
 const types=new Set([...(p.questions||[]),...(p.questionSetB||[])].map(q=>q&&q.questionType));if(types.size<4)bad(p.id,'question_diversity',`${types.size} types`);if(p.level==='YAMAGUCHI_EXAM'&&!p.materialData)bad(p.id,'material','Yamaguchi item missing materialData');if(p.level==='YAMAGUCHI_EXAM'&&[...(p.questions||[]),...(p.questionSetB||[])].filter(q=>q.questionType==='MATERIAL_LINK').length<2)bad(p.id,'material_question','Yamaguchi item needs >=2 MATERIAL_LINK');
 for(const n of (p.notes||[])){if(n&&n.kind==='unlearned_local_required'){const j=String(n.japanese||'').trim();if(!j||j.toLowerCase()===String(n.english||'').toLowerCase()||/placeholder|temporary|最終注整理対象/i.test(j))bad(p.id,'required_local_gloss',`${n.english}=${j}`);}}
 rows.push({id:p.id,grade:p.grade,wordCount:actual,a:(p.questions||[]).length,b:(p.questionSetB||[]).length,types:types.size,semanticReview:p.semanticReview});
}
const out={generatedAt:new Date().toISOString(),passages:ps.length,totalQuestions,failures:fail.length,registered:false,finalPass:ps.length===50&&totalQuestions===500&&fail.length===0,fail,rows};fs.writeFileSync('V11_BATCH10_CONTENT_INTEGRITY_REPORT.json',JSON.stringify(out,null,2)+'\n');fs.writeFileSync('V11_BATCH10_CONTENT_INTEGRITY_STATUS.txt',[`passages=${ps.length}/50`,`questions=${totalQuestions}/500`,`failures=${fail.length}`,`registered=false`,`final=${out.finalPass?'PASS':'FAIL'}`].join('\n')+'\n');console.log(fs.readFileSync('V11_BATCH10_CONTENT_INTEGRITY_STATUS.txt','utf8'));if(!out.finalPass)process.exitCode=1;
