const fs=require('fs');
const vm=require('vm');
function run(s,f){vm.runInContext(fs.readFileSync(f,'utf8'),s,{filename:f});}
function jac(a,b){a=new Set(a);b=new Set(b);let n=0;for(const x of a)if(b.has(x))n++;return n/(a.size+b.size-n||1);}
function words(s){return (String(s||'').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
try{
 const s={window:{},console};s.globalThis=s.window;vm.createContext(s);
 for(const f of ['v11_batch04_passages_draft_g1.js','v11_batch04_passages_draft_g2.js','v11_batch04_passages_draft_g3.js','v11_batch04_length_repair.js','v11_batch04_length_repair_r2.js','v11_batch04_chronology_repair.js','v11_batch04_grammar_repair.js','v11_batch04_chronology_repair_r2.js','v11_batch04_postgrammar_length_repair.js','v11_batch04_notes_finalize_g1.js','v11_batch04_translation_sync.js','v11_batch04_question_regenerate.js'])run(s,f);
 const ps=[...(s.window.V11_BATCH04_G1_PASSAGES||[]),...(s.window.V11_BATCH04_G2_PASSAGES||[]),...(s.window.V11_BATCH04_G3_PASSAGES||[])];
 const lengthIssues=[],structureIssues=[],translationIssues=[],questionIssues=[],temporaryGlossPassages=[];
 for(const p of ps){const wc=words((p.sentences||[]).join(' ')),band=p.targetWordBand||[];if(band.length===2&&(wc<+band[0]||wc>+band[1]))lengthIssues.push({id:p.id,wc,band});if(p.wordCount!==wc)structureIssues.push({id:p.id,reason:'wordCount stale',stored:p.wordCount,actual:wc});if(!Array.isArray(p.sentences)||!p.sentences.length||!Array.isArray(p.slashRows)||p.sentences.length!==p.slashRows.length)structureIssues.push({id:p.id,reason:'sentence/slash mismatch'});if((p.slashRows||[]).some(x=>!x||!x.en||!x.jp))structureIssues.push({id:p.id,reason:'empty slash en/jp'});const full=(p.slashRows||[]).map(x=>x&&x.jp||'').join('');if(String(p.fullTranslation||'')!==full)translationIssues.push({id:p.id,reason:'fullTranslation/slash jp mismatch'});if(p.translationSync!=='B04_POST_GRAMMAR_SYNC_20260828')translationIssues.push({id:p.id,reason:'translation sync marker'});if((p.notes||[]).some(n=>!n||!n.english||!n.japanese||String(n.japanese).includes('最終注整理対象')))temporaryGlossPassages.push(p.id);const qs=[...(p.questions||[]),...(p.questionSetB||[])];if(qs.length!==10)questionIssues.push({id:p.id,reason:'question count '+qs.length});const ev=new Set(),prompts=new Set();for(const q of qs){if(!q.prompt||!q.answer||!q.evidence||!q.evidenceJp||!q.reason)questionIssues.push({id:p.id,reason:'missing question field'});if(!(p.sentences||[]).includes(q.evidence))questionIssues.push({id:p.id,reason:'evidence not in body'});const idx=(p.sentences||[]).indexOf(q.evidence),jp=idx>=0&&p.slashRows[idx]&&p.slashRows[idx].jp;if(jp!==q.evidenceJp)questionIssues.push({id:p.id,reason:'evidence jp mismatch'});ev.add(q.evidence);prompts.add(String(q.prompt).replace(/^\d+\.\s*/,''));}if(ev.size!==10)questionIssues.push({id:p.id,reason:'evidence diversity '+ev.size});if(prompts.size!==10)questionIssues.push({id:p.id,reason:'prompt diversity '+prompts.size});}
 const groups=new Map();for(const p of ps){const k=p.textbook+'|'+p.grade+'|'+p.section;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p);}const pairs=[];for(const [g,xs] of groups)for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const score=jac(xs[i].sentences,xs[j].sentences);if(score>=.55)pairs.push({group:g,a:xs[i].id,b:xs[j].id,score:+score.toFixed(3)});}
 const out={generatedAt:new Date().toISOString(),passages:ps.length,lengthIssues,structureIssues,translationIssues,questionIssues,highSharedPairs:pairs,temporaryGlossPassages:[...new Set(temporaryGlossPassages)],nonNoteReady:ps.length===50&&!lengthIssues.length&&!structureIssues.length&&!translationIssues.length&&!questionIssues.length&&!pairs.length,noteReady:new Set(temporaryGlossPassages).size===0,registrationReady:false};out.registrationReady=out.nonNoteReady&&out.noteReady;fs.writeFileSync('V11_BATCH04_POSTCHRONOLOGY_QUALITY_AUDIT.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({passages:out.passages,lengthIssues,lengthIssueCount:lengthIssues.length,structureIssues:structureIssues.length,translationIssues:translationIssues.length,questionIssues:questionIssues.length,highSharedPairs:pairs.length,temporaryGlossPassages:out.temporaryGlossPassages.length,nonNoteReady:out.nonNoteReady,noteReady:out.noteReady,registrationReady:out.registrationReady},null,2));if(!out.nonNoteReady)process.exitCode=1;
}catch(e){console.error(e.stack||e);process.exitCode=1;}
