(function rewriteV11Batch02SemanticPass3Grade3(){
'use strict';
const ps=window.V11_BATCH02_DRAFT_PASSAGES;
if(!Array.isArray(ps)||ps.length!==50)throw new Error('Batch02 draft missing before grade3 semantic rewrite');
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while|although)\b/gi,'/ $1');}
const R={
'V11-SS-G3-P7-3-011':[
['Our class welcomed a new student by explaining routines and important places.','クラスは決まりや大切な場所を説明して、新しい生徒を迎えました。'],
['The student joined our class on Monday morning.','その生徒は月曜日の朝に私たちのクラスへ入りました。'],
['At first, the student looked a little nervous because everything was new.','最初、その生徒はすべてが新しかったので少し緊張して見えました。'],
['Our teacher asked three students to show the school after the first class.','先生は最初の授業のあと、三人の生徒に学校を案内するよう頼みました。'],
['We first showed the library and explained when students could use it.','私たちはまず図書館を見せ、生徒がいつ使えるか説明しました。'],
['Next, we walked to the gym and the room for school clubs.','次に体育館と部活動で使う部屋まで歩きました。'],
['The new student asked where we ate lunch and where we kept our bags.','新しい生徒はどこで昼食を食べ、どこにかばんを置くのかたずねました。'],
['We answered the questions and showed both places.','私たちは質問に答え、両方の場所を見せました。'],
['During lunch, another classmate sat with the student and talked about favorite subjects.','昼食中、別のクラスメートがその生徒と座り、好きな教科について話しました。'],
['In the afternoon, the student could move around the school without asking for help.','午後には、その生徒は助けを求めずに学校の中を移動できました。'],
['Before going home, the student thanked us and smiled.','帰る前、その生徒は私たちにお礼を言って笑いました。'],
['The next day, the student joined our group work more easily.','次の日、その生徒はより気楽に私たちのグループ活動へ参加しました。'],
['I learned that a simple explanation can make a new place feel less difficult.','簡単な説明でも新しい場所をより難しく感じないようにできると学びました。'],
['Now our class has a small welcome plan for any student who joins us later.','今では、あとから入る生徒のためにクラスには小さな歓迎の計画があります。']
],
'V11-NH-G3-U6-4-011':[
['I noticed a mistake in our group chart and checked the original data.','私は班の表の間違いに気づき、元のデータを確認しました。'],
['Our group was preparing a chart for a science presentation.','私たちの班は理科の発表のために表を準備していました。'],
['We had written the results from five days of observation.','私たちは五日間の観察結果を書いていました。'],
['While I was reading the chart, one number looked much larger than the others.','表を読んでいると、一つの数字がほかよりずっと大きく見えました。'],
['At first, I thought that the change might be real.','最初、私はその変化が本当かもしれないと思いました。'],
['However, I decided to check the original notes before we explained it.','しかし、それを説明する前に元のメモを確認することにしました。'],
['The note for Wednesday showed 18, but our chart showed 81.','水曜日のメモは18でしたが、私たちの表には81とありました。'],
['I showed the difference to the other members of my group.','私はその違いを班のほかのメンバーに見せました。'],
['We corrected the number and checked every other row too.','私たちは数字を直し、ほかのすべての行も確認しました。'],
['One student found another small mistake in a date.','一人の生徒は日付にも小さな間違いを見つけました。'],
['After the check, the chart showed a much clearer pattern.','確認のあと、その表にはずっと分かりやすい傾向が表れました。'],
['We changed one part of our explanation because the old number had changed our idea.','古い数字が私たちの考えを変えていたので、説明の一部を変えました。'],
['On presentation day, we also told the class that we had checked the original data.','発表の日には、元のデータを確認したこともクラスに伝えました。'],
['Our teacher said that checking a surprising result was an important part of using data.','先生は、意外な結果を確認することはデータを使ううえで大切だと言いました。'],
['The experience made me more careful when I copied numbers.','その経験で、数字を書き写すときにより注意するようになりました。'],
['Now I compare a chart with the original notes before I call it finished.','今では表を完成とする前に、元のメモと比べます。'],
['A single wrong number can change the meaning of a whole chart.','一つの間違った数字が表全体の意味を変えることがあります。'],
['Because of that, our group added a final checking step to our next project.','そのため、私たちの班は次の課題に最後の確認手順を加えました。']
],
'V11-SS-G3-P7-3-012':[
['My family visited my grandparents and learned the story of an old object.','家族で祖父母を訪ね、古い品物の話を聞きました。'],
['On a shelf in their room, I saw a small wooden box.','部屋の棚に小さな木の箱があるのを見ました。'],
['The box looked old, but it was kept very carefully.','その箱は古く見えましたが、とても大切に保管されていました。'],
['I asked my grandfather why the box was important.','私は祖父に、なぜその箱が大切なのかたずねました。'],
['He said that his father had made it many years ago.','祖父は、自分の父親が何年も前に作ったと言いました。'],
['The box had moved with the family from one town to another.','その箱は家族とともに町から町へ移ってきました。'],
['My grandmother opened it and showed us several old letters inside.','祖母は箱を開け、中にある何通かの古い手紙を見せてくれました。'],
['The letters were written by family members who lived far away.','その手紙は遠くに住んでいた家族によって書かれたものでした。'],
['We read only a few lines because the paper was very old.','紙がとても古かったので、私たちは数行だけ読みました。'],
['My father recognized one name and told us another family story.','父は一つの名前に気づき、別の家族の話をしてくれました。'],
['I had seen the box before, but I had never known its history.','私は以前その箱を見たことがありましたが、その歴史は知りませんでした。'],
['After hearing the story, the small object looked very different to me.','話を聞いたあと、その小さな品物は私にはまったく違って見えました。'],
['I took a picture of it with my grandparents beside me.','私は祖父母といっしょにその箱の写真を撮りました。'],
['I learned that an ordinary object can carry a family memory for a long time.','普通の品物でも長い間家族の思い出を伝えることがあると学びました。']
],
'V11-NH-G3-U6-4-012':[
['I missed a goal, encouraged a teammate, and later helped the team score.','私はゴールを外しましたが、仲間を励まし、後で得点を助けました。'],
['Our team was playing an important game on Saturday.','私たちのチームは土曜日に大切な試合をしていました。'],
['In the first half, I had a good chance near the goal.','前半、私はゴールの近くでよいチャンスを得ました。'],
['I kicked the ball too quickly, and it went outside the goal.','私は急いでボールを蹴りすぎ、ボールはゴールの外へ行きました。'],
['I felt disappointed, but the game continued immediately.','私はがっかりしましたが、試合はすぐに続きました。'],
['A few minutes later, one of my teammates also made a mistake.','数分後、チームメイトの一人もミスをしました。'],
['The teammate looked down, so I told him to keep playing.','その仲間は下を向いたので、私はプレーを続けようと声をかけました。'],
['We began to pass the ball more carefully and watched each other.','私たちはより注意してパスをし、おたがいを見るようになりました。'],
['Early in the second half, I received the ball near the side of the field.','後半の早い時間、私はフィールドの横でボールを受け取りました。'],
['Instead of trying to score alone, I looked for another player.','一人で得点しようとせず、別の選手を探しました。'],
['I passed the ball across the field to the same teammate I had encouraged.','私は励ました同じ仲間へフィールドを横切るパスを出しました。'],
['He controlled the ball and scored.','彼はボールをうまく扱って得点しました。'],
['Everyone ran toward him, and he pointed at me with a smile.','みんなが彼のところへ走り、彼は笑顔で私を指しました。'],
['The goal did not erase my earlier mistake, but it changed how I felt about it.','その得点で前のミスが消えたわけではありませんが、そのミスへの感じ方が変わりました。'],
['I understood that helping a teammate can be as important as scoring myself.','自分で得点することと同じくらい仲間を助けることも大切だと分かりました。'],
['After the game, we talked about both mistakes and the final goal.','試合後、私たちは二つのミスと最後のゴールについて話しました。']
],
'V11-SS-G3-P7-3-013':[
['A book recommendation led my friend and me to discuss different favorite scenes.','本をすすめたことから、友達と私はそれぞれ違う好きな場面について話しました。'],
['I had finished a novel that I enjoyed very much.','私はとても楽しんだ小説を読み終えていました。'],
['The next day, I told my friend that the story was worth reading.','次の日、その物語は読む価値があると友達に伝えました。'],
['My friend borrowed the book and finished it during the weekend.','友達はその本を借り、週末に読み終えました。'],
['On Monday, we began talking about the story before class.','月曜日、授業前に私たちはその物語について話し始めました。'],
['I said that my favorite scene was the quiet conversation near the end.','私は終わり近くの静かな会話の場面がいちばん好きだと言いました。'],
['My friend was surprised because that scene was not the favorite one for him.','友達はその場面が自分のいちばん好きな場面ではなかったので驚きました。'],
['He preferred an earlier scene in which the main character made a difficult choice.','彼は主人公が難しい選択をする、もっと前の場面を好みました。'],
['We each explained why our scene felt important.','私たちはそれぞれ、なぜその場面が大切に感じたか説明しました。'],
['While listening to him, I noticed a detail that I had almost forgotten.','彼の話を聞きながら、私はほとんど忘れていた細かい点に気づきました。'],
['He also said that my explanation made him think again about the ending.','彼も、私の説明で結末についてもう一度考えたと言いました。'],
['We did not decide that one scene was better than the other.','私たちはどちらか一方の場面がよりよいとは決めませんでした。'],
['Instead, the different choices made our conversation more interesting.','むしろ、違う選択が会話をよりおもしろくしました。'],
['After that, we decided to recommend another book to each other next month.','そのあと、来月また別の本をおたがいにすすめることにしました。']
],
'V11-NH-G3-U6-4-013':[
['I planned the order of my homework so I could finish before an evening event.','夜の行事の前に終えられるよう、宿題の順番を計画しました。'],
['That day, I had homework from four subjects.','その日、私は四教科の宿題がありました。'],
['My family also planned to go to an event at seven in the evening.','家族は夜七時に行事へ行く予定も立てていました。'],
['When I came home, I first wrote down every task and the time I thought it would need.','家に帰ると、まずすべての課題と必要だと思う時間を書き出しました。'],
['One math task was short, but a report for another class needed more time.','数学の課題は短かったですが、別の授業のレポートにはより時間が必要でした。'],
['I decided to start with the report while I still had enough energy.','まだ十分元気なうちにレポートから始めることにしました。'],
['After forty minutes, I finished the main part and took a short break.','四十分後、主な部分を終え、短い休憩を取りました。'],
['Next, I completed the math work because I could finish it quickly.','次に、すぐ終えられるので数学の課題を終えました。'],
['I then read the pages for English and marked two points I wanted to review later.','それから英語のページを読み、あとで復習したい二点に印をつけました。'],
['The last task was a short science worksheet.','最後の課題は短い理科のワークシートでした。'],
['I finished it just before my family started getting ready to leave.','家族が出かける準備を始める少し前に、それを終えました。'],
['Before leaving, I checked my list and found that every task was complete.','出かける前に一覧を確認し、すべての課題が終わっていることを確認しました。'],
['At the event, I could enjoy the evening without worrying about unfinished homework.','行事では、終わっていない宿題を心配せず夜を楽しめました。'],
['The next day, I used the same method when I had several things to do.','次の日、することがいくつかあったとき同じ方法を使いました。'],
['Planning the order did not make the homework smaller, but it made the time easier to use.','順番を計画しても宿題が減るわけではありませんが、時間を使いやすくなりました。'],
['Now I make a simple order before I begin a busy evening.','今では忙しい夕方を始める前に簡単な順番を決めます。'],
['I also leave a little extra time because one task sometimes takes longer than expected.','一つの課題が予想より長くかかることがあるので、少し余分な時間も残します。'],
['That small habit helps me finish calmly instead of rushing at the end.','その小さな習慣のおかげで、最後に急ぐのではなく落ち着いて終えられます。']
],
'V11-SS-G3-P7-3-014':[
['Our volunteer activity began slowly but became easier after we divided the jobs.','ボランティア活動はゆっくり始まりましたが、仕事を分けると楽になりました。'],
['Our class went to a community center to help prepare for an event.','私たちのクラスは行事の準備を手伝うため地域の施設へ行きました。'],
['At first, everyone tried to do several things at the same time.','最初、みんなが同時にいくつものことをしようとしました。'],
['Some students moved chairs while others opened boxes, but nobody knew who should check the tables.','いすを動かす生徒も箱を開ける生徒もいましたが、だれが机を確認するのか分かりませんでした。'],
['We stopped for a minute and made a simple list of the jobs.','私たちは少し止まり、仕事の簡単な一覧を作りました。'],
['One group carried chairs, another group prepared the tables, and a third group put signs near the doors.','一つの班はいすを運び、別の班は机を準備し、三つ目の班はドアの近くに案内を置きました。'],
['I joined the table group with two friends.','私は二人の友達と机の班に入りました。'],
['We checked the number of tables and placed them in two rows.','机の数を確認し、二列に並べました。'],
['When our work was finished, we helped the chair group for a few minutes.','自分たちの仕事が終わると、数分いすの班を手伝いました。'],
['The room was ready much sooner after the jobs were divided.','仕事を分けてから、部屋はずっと早く準備できました。'],
['A worker at the center thanked us for working together.','施設の人は協力して働いたことにお礼を言いました。'],
['On the way back to school, we talked about why the second plan worked better.','学校へ戻る途中、なぜ二つ目の計画のほうがうまくいったか話しました。'],
['We agreed that knowing one clear job helped everyone move faster.','一つの明確な仕事が分かっていると、みんながより速く動けると意見が一致しました。'],
['The volunteer activity taught us that dividing work can also improve teamwork.','そのボランティア活動から、仕事を分けることが協力もよくすると学びました。']
],
'V11-NH-G3-U6-4-014':[
['I prepared too much luggage and removed things I did not need.','私は荷物を多く用意しすぎ、必要のない物を取り除きました。'],
['My family was going away for two nights during a school break.','学校の休み中、家族で二泊の外出をする予定でした。'],
['I packed early because I did not want to forget anything.','何も忘れたくなかったので、私は早めに荷造りしました。'],
['Soon my bag was full of clothes, books, and several things for free time.','すぐにかばんは服、本、自由時間用のいくつかの物でいっぱいになりました。'],
['When I tried to lift it, the bag felt much too heavy.','持ち上げようとすると、そのかばんは重すぎました。'],
['My sister laughed and asked how many days I planned to stay.','姉は笑って、何日泊まるつもりなのかたずねました。'],
['I opened the bag again and put everything on the floor.','私はもう一度かばんを開け、中身を全部床に出しました。'],
['First, I removed two books because I knew I would not read both.','まず、両方は読まないと分かっていたので本を二冊減らしました。'],
['I also took out extra clothes that were almost the same.','ほとんど同じ余分な服も取り出しました。'],
['Then I checked the weather and changed one heavy item for a lighter one.','それから天気を確認し、重い物一つをより軽い物に変えました。'],
['After that, everything I truly needed still fit in the bag.','そのあと、本当に必要な物はすべてかばんに入りました。'],
['The bag was easier to carry when we left the next morning.','次の朝出発するとき、かばんはより運びやすくなっていました。'],
['During the trip, I did not miss any of the things I had removed.','旅行中、取り出した物がなくても困りませんでした。'],
['In fact, having less luggage made moving between places much easier.','実際、荷物が少ないことで場所の間を移動するのがずっと楽でした。'],
['When we came home, I made a short list of the things I had actually used.','家に帰ると、実際に使った物の短い一覧を作りました。'],
['I plan to look at that list before I pack for the next trip.','次の旅行の荷造り前にその一覧を見るつもりです。']
],
'V11-SS-G3-P7-3-015':[
['My friends chose a gift by thinking about the receiver’s hobby instead of the price.','友達は値段ではなく、受け取る人の趣味を考えて贈り物を選びました。'],
['One of our friends was going to have a birthday soon.','友達の一人がもうすぐ誕生日を迎える予定でした。'],
['Three of us went to a store after school to look for a gift.','私たち三人は放課後、贈り物を探しに店へ行きました。'],
['At first, we looked at several expensive things near the entrance.','最初、入口の近くにある高価な物をいくつか見ました。'],
['They looked nice, but none of them seemed connected to our friend.','それらはよく見えましたが、どれもその友達らしい物には思えませんでした。'],
['Then one friend remembered that the birthday student loved drawing.','すると一人が、誕生日の友達は絵を描くのが大好きだと思い出しました。'],
['We walked to another part of the store and found a small set of drawing tools.','店の別の場所へ行き、小さな画材のセットを見つけました。'],
['It cost less than the first gifts we had seen.','それは最初に見た贈り物より安かったです。'],
['However, we could easily imagine our friend using it after school.','しかし、友達が放課後にそれを使う姿を簡単に想像できました。'],
['We added a simple card and each wrote a short message.','簡単なカードを加え、それぞれ短いメッセージを書きました。'],
['On the birthday, our friend opened the gift and immediately talked about a picture to draw.','誕生日に友達は贈り物を開け、すぐに描きたい絵について話しました。'],
['That reaction showed us that we had made a good choice.','その反応から、よい選択をしたと分かりました。'],
['The price had not told us which gift would be most useful.','値段はどの贈り物がいちばん役立つか教えてはくれませんでした。'],
['Thinking about the receiver helped us choose something more personal.','受け取る人について考えることで、よりその人らしい物を選べました。']
],
'V11-NH-G3-U6-4-015':[
['A classroom plant grew poorly until we moved it near the window.','教室の植物は、窓の近くへ動かすまでよく育ちませんでした。'],
['Our class had cared for the plant for several months.','私たちのクラスは数か月その植物の世話をしていました。'],
['We gave it water regularly, but its leaves became smaller.','定期的に水をやっていましたが、葉は小さくなりました。'],
['Some leaves also lost their bright color.','いくつかの葉は明るい色も失いました。'],
['At first, we thought the plant needed more water.','最初、もっと水が必要だと思いました。'],
['For a week, we gave it a little more, but nothing improved.','一週間、少し多く水をやりましたが、何もよくなりませんでした。'],
['Then a student noticed that the corner was dark for most of the day.','すると一人の生徒が、その場所は一日の大半暗いことに気づきました。'],
['We checked another place near the window and found that it received much more light.','窓の近くの別の場所を確認すると、そこにはずっと多くの光が当たっていました。'],
['We moved the plant there and returned to the usual amount of water.','植物をそこへ移し、水の量は通常に戻しました。'],
['After several days, the leaves stopped getting smaller.','数日後、葉が小さくなるのが止まりました。'],
['A little later, a new leaf appeared near the top.','少したつと、上のほうに新しい葉が出ました。'],
['We continued watching the plant and wrote down the changes each week.','私たちは植物を観察し続け、毎週変化を書き留めました。'],
['By the end of the month, it looked much healthier.','月末には、その植物はずっと元気に見えました。'],
['The experience showed us that water was not the only thing the plant needed.','その経験から、水だけが植物に必要なものではないと分かりました。'],
['We also learned to look at the whole environment before changing one part again.','一つのことをまた変える前に、周りの環境全体を見ることも学びました。'],
['Now the plant stays near the window, and our class checks both water and light.','今では植物は窓の近くにあり、クラスでは水と光の両方を確認しています。'],
['The small change of place solved a problem that extra water could not solve.','場所を少し変えたことで、水を増やしても解決できなかった問題が解決しました。'],
['Our weekly notes help the next students understand how the plant changed.','毎週の記録は、次の生徒たちが植物の変化を理解する助けになります。']
],
'V11-SS-G3-P7-3-016':[
['I helped a tourist understand a simple local rule.','私は旅行者が簡単な地域のルールを理解するのを手伝いました。'],
['I was waiting near a public garden when a tourist spoke to me.','公共の庭園の近くで待っていると、旅行者が私に話しかけました。'],
['The tourist had a drink and was looking for a place to sit.','その旅行者は飲み物を持ち、座る場所を探していました。'],
['I noticed that he was about to enter an area where food and drinks were not allowed.','その人が飲食禁止の場所へ入ろうとしていることに気づきました。'],
['A sign showed the rule, but it was written only in Japanese.','看板にルールが書いてありましたが、日本語だけでした。'],
['I pointed to the sign and explained the rule in simple English.','私は看板を指し、簡単な英語でルールを説明しました。'],
['At first, the tourist looked worried because he thought he had to leave the garden.','最初、旅行者は庭園を出なければならないと思い心配そうでした。'],
['I explained that drinks were allowed in another area near the entrance.','入口近くの別の場所では飲み物がよいと説明しました。'],
['We walked a short distance, and I showed him several seats there.','少し歩き、そこにあるいくつかのいすを見せました。'],
['The tourist thanked me and said that the sign had been difficult to understand.','旅行者はお礼を言い、看板が理解しにくかったと言いました。'],
['Before I left, I also showed him the path to the main garden.','別れる前に、庭園の中心部への道も示しました。'],
['He followed the rule and could still enjoy his visit.','その人はルールを守りながら訪問を楽しめました。'],
['I realized that explaining what someone can do is as useful as explaining what they cannot do.','できないことだけでなく、できることを説明するのも役立つと気づきました。'],
['A short explanation made the local rule much easier for the visitor to follow.','短い説明で、その地域のルールは旅行者にとってずっと守りやすくなりました。']
],
'V11-NH-G3-U6-4-016':[
['My family canceled an outdoor activity and made a photo album indoors.','家族は外での活動を中止し、家の中で写真アルバムを作りました。'],
['We had planned to spend Sunday afternoon outside.','私たちは日曜日の午後を外で過ごす予定でした。'],
['In the morning, heavy rain began and the weather report said it would continue.','朝、強い雨が降り始め、天気予報では続くと言っていました。'],
['We decided not to go out because the ground would be wet and unsafe.','地面がぬれて危ないので外出しないことにしました。'],
['At first, everyone was disappointed because we had looked forward to the plan.','最初、みんなその計画を楽しみにしていたので残念でした。'],
['Then my mother brought out a box of family photos.','すると母が家族の写真が入った箱を出しました。'],
['Some pictures were recent, while others were from many years ago.','最近の写真もあれば、何年も前の写真もありました。'],
['We decided to make a small album about trips and family events.','旅行や家族の行事についての小さなアルバムを作ることにしました。'],
['My brother sorted the photos by year, and I wrote short notes for several pages.','弟は写真を年ごとに分け、私はいくつかのページに短いメモを書きました。'],
['My father found a picture that none of us children remembered.','父は、子どもたちのだれも覚えていない写真を見つけました。'],
['He explained where it had been taken and why everyone was laughing.','父はそれがどこで撮られ、なぜみんな笑っていたのか説明しました。'],
['That story became one of my favorite parts of the album.','その話はアルバムの中で私のお気に入りの一つになりました。'],
['We worked for more than two hours without noticing the time.','私たちは時間に気づかず二時間以上作業しました。'],
['By evening, the album had many pages and a simple title.','夕方までに、アルバムにはたくさんのページと簡単な題名ができました。'],
['The rain changed our plan, but it also gave us time to remember old experiences together.','雨で計画は変わりましたが、いっしょに昔の経験を思い出す時間もできました。'],
['We decided to add new photos to the album after our next trip.','次の旅行のあと、新しい写真をアルバムに加えることにしました。']
],
'V11-SS-G3-P7-3-017':[
['I practiced asking clearer questions for an interview assignment.','私はインタビュー課題のため、より分かりやすい質問をする練習をしました。'],
['Our class had an assignment to interview an adult about work.','私たちのクラスには仕事について大人へインタビューする課題がありました。'],
['I wrote eight questions before practicing with a friend.','友達と練習する前に八つの質問を書きました。'],
['My first question was very long and included two different ideas.','最初の質問はとても長く、二つの違う考えが入っていました。'],
['My friend answered only one part and asked what I really wanted to know.','友達は一つの部分だけ答え、私が本当に何を知りたいのかたずねました。'],
['I divided the question into two shorter questions.','私はその質問を二つの短い質問に分けました。'],
['Another question could be answered with only yes or no.','別の質問は「はい」か「いいえ」だけで答えられるものでした。'],
['I changed it so the person could explain an experience instead.','相手が経験を説明できるようにその質問を変えました。'],
['We practiced the full interview twice and checked the order of the questions.','私たちはインタビュー全体を二回練習し、質問の順番を確認しました。'],
['I moved an easy opening question to the beginning.','簡単な最初の質問を冒頭へ移しました。'],
['I also prepared one extra question in case an answer gave me a new idea.','答えから新しい考えが出た場合のために追加質問も一つ準備しました。'],
['On interview day, the conversation was easier to follow than during my first practice.','インタビューの日、会話は最初の練習よりずっと進めやすくなりました。'],
['The adult gave detailed answers because the questions were clear.','質問が分かりやすかったので、その大人は詳しく答えてくれました。'],
['Afterward, I could use the answers easily when I wrote my report.','そのあと、レポートを書くとき答えを簡単に使うことができました。']
],
'V11-NH-G3-U6-4-017':[
['My friends used a timetable to solve a misunderstanding about the meeting time.','友達は時刻表を使い、待ち合わせ時間の思い違いを解決しました。'],
['Four of us planned to meet at a station before a school event.','私たち四人は学校行事の前に駅で待ち合わせる予定でした。'],
['The night before, one friend wrote that we should meet at 8:20.','前の夜、一人の友達が8時20分に会おうと書きました。'],
['Another friend believed the meeting time was 8:40.','別の友達は待ち合わせは8時40分だと思っていました。'],
['The messages became confusing because both times had appeared in our earlier conversation.','前の会話に両方の時刻が出ていたので、メッセージは分かりにくくなりました。'],
['Instead of continuing to guess, one friend opened the train timetable.','推測を続ける代わりに、一人の友達が電車の時刻表を開きました。'],
['The train we needed left our station at 8:32.','私たちが必要な電車は駅を8時32分に出発しました。'],
['That meant 8:40 could not be the meeting time.','つまり8時40分は待ち合わせ時刻ではありえませんでした。'],
['We checked the earlier message and found that 8:40 was the time we expected to arrive at the next station.','前のメッセージを確認すると、8時40分は次の駅へ到着する予定時刻でした。'],
['Everyone then agreed to meet at 8:20 near the ticket gate.','そこで全員が8時20分に改札近くで会うことに同意しました。'],
['The next morning, all four of us arrived before the train came.','次の朝、四人全員が電車が来る前に着きました。'],
['We laughed about the two times while we waited.','待っている間、二つの時刻について笑いました。'],
['The timetable gave us a fact that was clearer than our memory of the messages.','時刻表は、メッセージの記憶よりはっきりした事実を示してくれました。'],
['Since then, our group writes both the meeting time and the train time when we make a plan.','それ以来、計画を立てるとき待ち合わせ時刻と電車時刻の両方を書くようにしています。'],
['That small change has prevented the same misunderstanding from happening again.','その小さな変更で、同じ思い違いが再び起こるのを防げています。'],
['We learned that checking a shared source can solve a disagreement quickly.','共通の情報源を確認すると意見の違いをすぐ解決できると学びました。'],
['It also gave everyone confidence that the final plan was correct.','また、最終的な計画が正しいという自信をみんなに与えました。'],
['Now the timetable is the first thing we check when train times are part of a meeting plan.','今では電車時刻が待ち合わせ計画に関わるとき、最初に時刻表を確認します。']
],
'V11-SS-G3-P7-3-018':[
['Our class compared energy use before and after a one-week saving challenge.','クラスは一週間の節電の前後でエネルギー使用量を比べました。'],
['Our science teacher asked us to think about how we used electricity at school.','理科の先生は学校でどのように電気を使っているか考えるよう言いました。'],
['For three days, we first watched our usual habits without changing them.','三日間、まず何も変えず普段の習慣を観察しました。'],
['We noticed that lights sometimes stayed on in an empty classroom.','だれもいない教室で時々照明がついたままだと気づきました。'],
['Some computers were also left on during lunch.','昼食中、いくつかのコンピューターもついたままでした。'],
['We wrote down these examples and made a simple saving plan.','それらの例を書き出し、簡単な節電計画を作りました。'],
['During the next week, the last student leaving a room checked the lights.','次の一週間、部屋を最後に出る生徒が照明を確認しました。'],
['Students also turned off computers when nobody needed them for a long time.','長い間だれも使わないときはコンピューターも消しました。'],
['We did not stop using anything that was necessary for class.','授業に必要なものを使うのをやめたわけではありません。'],
['At the end of each day, two students recorded what our class had done.','毎日の終わりに二人の生徒がクラスで行ったことを記録しました。'],
['After one week, our teacher showed us the energy-use numbers from before and after the challenge.','一週間後、先生は挑戦前後のエネルギー使用量を見せました。'],
['The number after the challenge was lower.','挑戦後の数字は低くなっていました。'],
['We were surprised that several small actions could make a clear difference together.','いくつかの小さな行動を合わせるとはっきりした違いになることに驚きました。'],
['Our class discussed which habits were easy enough to continue.','クラスで、どの習慣なら続けやすいか話し合いました。'],
['We decided to keep the light check and the computer check as regular class jobs.','照明確認とコンピューター確認を普段のクラスの仕事として続けることにしました。'],
['A month later, the teacher showed us another set of numbers.','一か月後、先生は別の数字も見せてくれました。'],
['The lower level had continued, so we knew the new habits had not ended after one week.','低い水準が続いていたので、新しい習慣が一週間で終わっていないと分かりました。'],
['The project taught us that saving energy does not always require one large change.','その課題から、節電には必ずしも一つの大きな変化が必要ではないと学びました。'],
['It can begin with small actions that many people remember to do.','多くの人が覚えて実行する小さな行動から始めることができます。']
],
'V11-NH-G3-U6-4-018':[
['I thought about a small failure and wrote one clear next step.','私は小さな失敗について考え、次にすることを一つ具体的に書きました。'],
['I had prepared for a short class presentation, but it did not go as well as I hoped.','短いクラス発表の準備をしていましたが、思ったほど上手くいきませんでした。'],
['I knew the topic, yet I spoke too quickly during the first half.','内容は分かっていましたが、前半で話すのが速すぎました。'],
['Because of that, I missed one explanation that I had planned to give.','そのため、説明する予定だった一つを飛ばしてしまいました。'],
['After class, I first wanted to forget the presentation.','授業後、最初はその発表を忘れたいと思いました。'],
['However, our teacher asked us to write one thing that we would change next time.','しかし先生は、次回変えたいことを一つ書くよう言いました。'],
['I looked at my notes and remembered the point where I had started rushing.','私はメモを見て、急ぎ始めたところを思い出しました。'],
['The problem was not that I had no information.','問題は情報がなかったことではありませんでした。'],
['I had tried to say too much without stopping between ideas.','考えの間で止まらず、多くを言いすぎようとしていました。'],
['I wrote one next step: put a short pause mark after each main point.','私は次の一歩を一つ書きました。主な要点のあとに短い間の印を入れることです。'],
['That evening, I practiced the same presentation again with the new marks.','その夜、新しい印を使って同じ発表をもう一度練習しました。'],
['The pauses made my speaking slower and helped me remember the missing explanation.','間を取ることで話す速度が遅くなり、飛ばした説明も思い出せました。'],
['A week later, I used the same idea in another short talk.','一週間後、別の短い発表で同じ考えを使いました。'],
['I still felt nervous, but I did not rush through the main points.','まだ緊張しましたが、主な要点を急いで話しませんでした。'],
['The second talk was easier for my classmates to follow.','二回目の発表はクラスメートにとって理解しやすくなりました。'],
['Looking at one small failure gave me a practical change I could actually use.','一つの小さな失敗を見ることで、実際に使える具体的な改善が得られました。'],
['I learned that a next step is more useful when it is clear and small enough to try.','次の一歩は、明確で試せるほど小さいほうが役立つと学びました。'],
['Now, after a mistake, I try to write one action instead of only writing that I should do better.','今では失敗のあと、ただ「もっとよくする」と書くのではなく、一つの行動を書くようにしています。']
]};
let changed=0;
for(const p of ps){if(p.grade!=='3')continue;const rows=R[p.id];if(!rows)throw new Error('No grade3 rewrite for '+p.id);p.sentences=rows.map(r=>r[0]);p.fullTranslation=rows.map(r=>r[1]).join('');p.slashRows=rows.map(r=>({en:slash(r[0]),jp:r[1]}));p.wordCount=(p.sentences.join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;p.questions=[];p.questionSetB=[];p.semanticRewrite='PASS3_GRADE3_20260828';p.auditNote+=' Grade3 story-specific semantic rewrite pass3 applied; questions intentionally cleared for regeneration after chronology validation.';changed++;}
if(changed!==16)throw new Error('grade3 rewrite count '+changed);
window.V11_BATCH02_SEMANTIC_REWRITE_PASS3_GRADE3_STATE={version:'20260828-grade3',changed,registered:false,questionsPending:true};
})();