'use strict';
const fs=require('fs');
const additions={
'V11-B15-G2-001':{en:' They also asked five students to point to the box before and after the change. Four more students noticed it after the sign was moved.',jp:' さらに変更の前後で5人の生徒に箱の場所を指してもらうと、表示を移した後は気づける生徒が4人増えました。'},
'V11-B15-G2-002':{en:' The club kept the message itself unchanged during the test, so they could compare the effect of timing fairly.',jp:' 比較を公平にするため、テスト中は連絡文そのものを変えず、送る時刻だけを変えました。'},
'V11-B15-G2-003':{en:' Teachers then repeated the timing test on a rainy day, when more students stayed inside. Route B still moved more steadily, which supported the recommendation.',jp:' 先生たちは、生徒が廊下に多く残る雨の日にも時間を測り直しました。それでもBルートの流れは安定しており、提案を裏づける結果になりました。'},
'V11-B15-G2-004':{en:' They measured the line again at the next busy hour and found that customers reached the counter with an order already chosen.',jp:' 次の混雑時間にも列を測ると、多くの客が注文を決めた状態でカウンターへ着くようになっていました。'},
'V11-B15-G2-005':{en:' They kept both forms available, because some students still preferred paper even after the online form became easier.',jp:' オンライン版が使いやすくなった後も紙を好む生徒はいたため、部は二つの申込方法を残しました。'},
'V11-B15-G2-006':{en:' The committee asked students to report new icy spots for two weeks. No additional place caused repeated problems, so the map stayed focused on the shaded section.',jp:' 委員会は二週間、新しい凍結場所があれば報告するよう生徒に頼みました。繰り返し問題になる別の場所はなく、地図では日陰の区間を重点的に示しました。'},
'V11-B15-G2-008':{en:' A short follow-up survey also showed that students still noticed the cheerful music, even at the lower volume.',jp:' 短い追加アンケートでは、音量を下げても生徒たちは明るい音楽に気づいていたことも分かりました。'},
'V11-B15-G2-009':{en:' They repeated the change during the final sale period and saw the same pattern, so the improvement was not limited to one unusually quiet moment.',jp:' 最後の販売時間にも同じ変更を繰り返すと同じ傾向が見られたため、たまたま空いていた一回だけの改善ではないと確認できました。'},
'V11-B15-G2-010':{en:' They left the tree in place and checked the sign again one week later to make sure new leaf growth had not hidden it.',jp:' 木はそのまま残し、一週間後にも葉が伸びて再び案内を隠していないか確認しました。'},
'V11-B15-G2-011':{en:' The five minutes also gave injured players time to tell the captain what activities they needed to avoid that day.',jp:' その5分間は、けがをしている選手がその日に避ける活動を主将へ伝える時間にもなりました。'},
'V11-B15-G2-012':{en:' Volunteers recorded the reasons for every rejected book during the second collection. Water damage, not unclear categories, became the most common reason after the redesign.',jp:' 二回目の回収では、係が返却理由をすべて記録しました。案内改善後は、分類の分かりにくさではなく水ぬれが最も多い返却理由になりました。'},
'V11-B15-G2-013':{en:' They also placed the opening hours below the welcome sign, which prevented people from trying the door after the room had closed.',jp:' 歓迎表示の下には利用時間も付け、閉室後にドアを開けようとする人が出ないようにしました。'},
'V11-B15-G2-014':{en:' The students kept the same breaks and subjects, allowing them to judge the effect of task order instead of several changes at once.',jp:' 休憩や学習科目は同じにし、複数の条件を一度に変えず課題の順番の効果を確かめました。'},
'V11-B15-G2-015':{en:' The team posted simple return instructions at the two reusable-plate stalls and counted missing plates at closing time. Only a few were unreturned, so the next event kept the mixed system.',jp:' チームは再利用皿を使う二店に簡単な返却案内を出し、閉店時に不足枚数も数えました。戻らなかった皿はわずかだったため、次の行事でも混合方式を続けることになりました。'},
'V11-B15-G2-016':{en:' A final test included a spoken room number and a short safety instruction. Students in all four areas could repeat both correctly.',jp:' 最終テストでは部屋番号と短い安全指示も放送し、四つの場所すべてで生徒が両方を正しく言い直せました。'},
'V11-B15-G2-017':{en:' They also displayed a progress bar, so students could see that the remaining questions were short after the main section.',jp:' さらに進行状況の表示を付け、中心部分の後に残る質問が少ないことも生徒に分かるようにしました。'},
'V11-B15-G3-001':{en:' The students also compared how long the door remained open on ordinary days. It was usually less than two minutes, but large-delivery days averaged nearly nine minutes. They placed a rolling cart beside the sorting table so chilled items could be grouped together before the door opened. Volunteers then recorded both temperature and door-open time for another ten days. Short door openings matched the more stable temperatures. The pantry added the new routine to its volunteer guide and kept the log in case the pattern changed later.',jp:' 生徒たちは通常の日に扉が開いている時間も比べました。普段は2分未満でしたが、大きな配送の日は平均約9分でした。そこで仕分け台の横に移動式ワゴンを置き、冷蔵品をまとめてから扉を開けられるようにしました。さらに10日間、温度と開扉時間の両方を記録すると、扉を短く開けた日は温度もより安定していました。配布所は新しい手順をボランティア用案内に加え、今後傾向が変わった場合に確認できるよう記録も続けました。'},
'V11-B15-G3-002':{en:' To prevent the same problem later, the team marked conditions such as “in the work area” in a separate review column. Translators had to check that column before approving a sentence. The teacher preferred this method because it protected the exact rule without forcing both languages to use identical word order.',jp:' 同じ問題を防ぐため、チームは「作業区域内」のような条件を別の確認欄に記録することにしました。翻訳担当者は文を承認する前にその欄も確認します。先生は、両言語の語順を同じにしなくても規則の正確な条件を守れるとして、この方法を評価しました。'},
'V11-B15-G3-003':{en:' The organizers tested the plan by estimating walking times. The seaside route normally took forty minutes, the inland walk to the market square took twenty-five minutes, and the lower beach path needed about thirty-five minutes. This confirmed that the 10:20 group could not simply hurry through the closed section. They also considered asking that group to wait until 1:00, but that would delay lunch and separate them from the event program. The shuttle solution kept their arrival close to the other groups. On the route board, a blue line showed the normal seaside route, a green line showed the inland route, and a red mark identified the closed section. Next to the tide table, organizers added a note explaining that “open now” did not mean “safe for the whole walk.” Volunteers at Harbor Station received the same information so they could answer questions consistently. On the event morning, each group leader checked the current board before departure because weather or repair work could still change the plan.',jp:' 主催者は歩行時間を見積もって計画を確かめました。海沿いの通常ルートは約40分、市場広場までの内陸ルートは25分、下側の浜辺の道は約35分かかります。このため10時20分のグループが急いで通行止め区間を抜ける案は使えないと確認できました。1時まで待つ案も考えましたが、それでは昼食が遅れ、行事の予定から外れてしまいます。シャトルを使えば他のグループに近い時刻に到着できます。案内板では通常の海沿いルートを青、内陸ルートを緑、通行止め区間を赤で示しました。潮位表の横には、「今通れる」ことと「歩き終えるまで安全」なことは同じではないという説明も加えました。港駅のボランティアにも同じ情報を渡し、質問への答えが人によって変わらないようにしました。当日の朝も、天候や工事状況が変わる可能性があるため、各班のリーダーが出発前に最新の案内板を確認しました。'},
'V11-B15-G3-004':{en:' The editor then asked each writer to label notes as direct quote, summary, or background fact. That small change made it easier to see when shortened wording needed to be checked against the recording before publication.',jp:' 編集担当はさらに、メモを「直接引用」「要約」「背景事実」に分けて表示するよう決めました。この小さな変更で、短くした表現を公開前に録音と照合すべき場所が分かりやすくなりました。'},
'V11-B15-G3-005':{en:' The students also compared weather within the new survey. Weekend afternoon use dropped during light rain, while the pond path still had several regular walkers. This helped them avoid treating every difference as a weekday-versus-weekend effect. They included the weather beside each count in the final table and wrote that future surveys should use the same categories. A park manager said the richer record was more useful because it showed not only how many people came but also which spaces they used under different conditions.',jp:' 生徒たちは新しい調査の中で天候による違いも比べました。休日の午後でも弱い雨の日は利用者が減りましたが、池の道にはいつものように歩く人が何人かいました。この結果から、すべての差を平日と休日だけの違いとは考えないようにしました。最終表では各人数の横に天候も記し、今後の調査でも同じ分類を使うべきだと書きました。公園管理者は、人数だけでなく異なる条件でどの場所が使われたか分かるため、この詳しい記録の方が役立つと話しました。'},
'V11-B15-G3-006':{en:' The class then built a timetable for every twenty-minute block. From 10:00 to 10:20, all groups received orientation. Group A entered robotics at 10:20, while Groups B and C went to the 10:30 planetarium. After that show, Group B had enough time to reach the 11:20 robotics workshop. Group C moved to the interactive lab, where eighteen students fit comfortably. Group A used the exhibition floor after robotics. At 11:30, Group A joined other visitors in the planetarium because enough seats remained, while Groups B and C continued activities they had not yet completed. The teacher checked walking time between rooms and required a ten-minute movement margin, so no group was scheduled in two distant places back-to-back. The final chart used three colors, one for each group, and showed meeting points as well as activity times. Students accepted that Group C would not do robotics because trying to force all three groups into two workshops would violate the room capacity. Instead, the interactive lab gave that group a hands-on activity of similar length. Everyone returned to the entrance by 12:20, leaving ten minutes for attendance before departure.',jp:' クラスは次に20分ごとの詳しい予定表を作りました。10時から10時20分までは全班が説明を受けます。A班は10時20分のロボット教室へ入り、B班とC班は10時30分のプラネタリウムへ行きます。上映後、B班には11時20分のロボット教室へ移動する時間があります。C班は18人が十分入れる体験実験室へ移動します。A班はロボット教室の後に展示フロアを利用します。11時30分には空席があるプラネタリウムへA班が入り、B班とC班はまだ行っていない活動を続けます。先生は部屋間の移動時間も確認し、10分の移動余裕を必ず取るようにしたため、離れた場所を連続して予定する班はありません。最終表では三班を別々の色で示し、活動時刻だけでなく集合場所も書きました。二回しかないロボット教室へ三班すべてを無理に入れると定員違反になるため、C班が参加しないことを受け入れました。その代わり、同程度の時間の体験実験を行います。全員が12時20分までに入口へ戻り、出発前に10分間出席確認できる計画になりました。'},
'V11-B15-G3-007':{en:' Before choosing the new crop, the students showed both versions to six classmates without revealing the intended caption. Several described the narrow image as “unmanaged,” while the wider image led them to mention sorting work. That response supported the change.',jp:' 新しい切り取りを決める前に、意図した説明文を見せず二つの写真を6人のクラスメートに見てもらいました。狭い写真では「管理されていない」と表現する人が何人もいましたが、広い写真では仕分け作業について話す人が増えました。この反応も変更を裏づけました。'},
'V11-B15-G3-008':{en:' The students also counted empty spaces at different times instead of relying on one daily average. Rack B filled briefly during evening meetings, which explained why users valued its position despite the lower average. For Rack C, they observed where riders parked when puddles formed and found several bicycles attached to a fence on higher ground. After moving Rack C, those bicycles shifted to the rack. The follow-up supported the idea that poor use had reflected the wet location rather than a lack of demand.',jp:' 生徒たちは一日の平均だけでなく、時間帯ごとの空きも数えました。Bは平均利用数が少なくても夕方の会合時には一時的に埋まり、入口近くの場所が評価される理由が分かりました。Cの周囲に水たまりができる日は、利用者が高い場所のフェンスに自転車を止めていることも確認しました。Cを移動すると、それらの自転車が置き場を使うようになりました。利用が少なかったのは需要がないからではなく、ぬれる場所が原因だったという考えを追跡調査が支えました。'},
'V11-B15-G3-009':{en:' The team also prepared decision rules instead of relying on a last-minute guess. If rain at 10:45 was only light and radar showed the dry period continuing, the music performance would stay outside. If heavier rain arrived early, staff would move chairs into the hall and delay the start by ten minutes. A volunteer counted available hall seats after the market tables were reduced, confirming that seventy visitors could enter without blocking exits. For the craft activity, families registered at the information desk so organizers knew whether the forty-seat estimate remained reasonable. The small tent was reserved for the food talk from 12:40, leaving twenty minutes for setup before the speaker began. Signs at the entrance used the same activity names and times as the printed program, reducing confusion when a location changed. After the market, organizers compared attendance with the revised schedule and found that no activity had to be cancelled. They saved the weather-and-capacity table as a model for future outdoor events, while noting that new forecasts must always replace the old numbers.',jp:' チームは直前の勘だけに頼らず、判断ルールも準備しました。10時45分の雨が弱く、雨雲情報でも雨のない時間が続くなら音楽演奏は屋外で行います。強い雨が早く来れば、係がホールへいすを移し、開始を10分遅らせます。市場の机を減らした後のホールの利用可能席も数え、70人が非常口をふさがず入れることを確認しました。工作については案内所で家族の参加を受け付け、40席という見込みが妥当か確認できるようにしました。小テントは12時40分から食の話のために確保し、講師開始前に20分の準備時間を取りました。入口の案内は印刷プログラムと同じ活動名と時刻を使い、場所が変わっても混乱しにくくしました。行事後に参加者数と変更後の予定を比べると、中止になった活動はありませんでした。主催者は天気と定員を組み合わせた表を次回の屋外行事の参考として保存しましたが、予報数値は毎回最新情報へ置き換える必要があることも記しました。'},
'V11-B15-G3-010':{en:' The club added the original survey question below the graph so readers could judge the number themselves. They also stopped using the word “prefer” by itself when a choice depended on a particular situation.',jp:' 部はグラフの下に元の質問文も載せ、読者自身が数字の意味を判断できるようにしました。また、特定の状況での選択を示すときは「好む」という言葉だけで一般化しないことにしました。'},
'V11-B15-G3-011':{en:' To test the new plan fairly, volunteers recorded planting dates, watering, and harvest weights for both beds. They used the same tomato variety in the small Bed B test, so a different variety would not confuse the comparison. The test tomatoes in Bed B produced less fruit but remained healthy, while leafy vegetables used the shaded space effectively. These results supported keeping a small experiment while using most of each bed for crops suited to its light conditions.',jp:' 新しい計画を公平に確かめるため、ボランティアは両区画の植え付け日、水やり、収穫重量を記録しました。Bの小さな試験区画でも同じ品種のトマトを使い、品種差が比較を乱さないようにしました。Bの試験トマトは実の数は少ないものの健康に育ち、葉物野菜は日陰の場所を有効に使えました。この結果から、小さな実験は残しつつ、各区画の大部分を日当たり条件に合う作物へ使う方針が支持されました。'},
'V11-B15-G3-012':{en:' The committee wrote the confirmed times in one column and uncertain descriptions in another. This made it clear that height and bag color were useful leads but not proof of identity. Staff members later adopted the same format for other lost-property reports.',jp:' 委員会は確認できた時刻を一つの欄へ、確かでない人物や物の特徴を別の欄へ書きました。背の高さやかばんの色は手がかりにはなっても、本人や物を特定する証拠ではないと明確になりました。職員も後の落とし物報告で同じ形式を使うようになりました。'},
'V11-B15-G3-013':{en:' The volunteers also checked whether age affected the result. Younger and older visitors preferred slightly different speeds, but both groups completed Version C more often than Version B. The museum therefore kept one main version and added a pause button reminder at the start for anyone who wanted extra viewing time.',jp:' ボランティアは年齢による違いも確認しました。若い来館者と年齢の高い来館者では好む速さに少し差がありましたが、どちらもB版よりC版を最後まで聞く割合が高くなりました。そこで博物館は基本版を一つにし、もっと見る時間が欲しい人のため開始時に一時停止ボタンの案内を加えました。'},
'V11-B15-G3-014':{en:' The students then tested the room plan against two changes. First, they assumed four additional adults might arrive after 6:00. Rooms A and B still had enough unused capacity for them without moving the families. Second, they considered what would happen if the 6:30 delivery was delayed. Baby-care space near the sink would still be available, but volunteers would need to keep a small emergency set from existing supplies. The entrance map marked a wide route to Room A and prohibited boxes from being stored along it. Room C received a quiet-area sign because young children might sleep there, while louder information announcements were made near Rooms A and B. Each room leader received a list showing current人数, free spaces, and the location of water after the first delivery. The final plan was not permanent; students wrote that assignments should change if a person's health or mobility needs changed. By checking both capacity and possible disruptions, they made the shelter plan flexible rather than merely fitting everyone into the rooms once.',jp:' 生徒たちはさらに二つの変化を想定して部屋割りを確かめました。まず午後6時以降に大人が4人追加で来る場合を考えました。A室とB室にはまだ空きがあり、家族を移動させなくても受け入れられます。次に6時30分の配送が遅れる場合も検討しました。流し近くの乳幼児用スペースは使えますが、それまでのために既存物資から少量の緊急用品を確保する必要があります。入口地図にはA室までの広い通路を示し、その通路には箱を置かないようにしました。C室には小さな子どもが眠る可能性を考えて静かな区域の表示を出し、大きな情報放送はA室とB室の近くで行います。各部屋の担当者には現在人数、空き人数、最初の配送後の水の場所を示す一覧を渡しました。この部屋割りは固定ではなく、体調や移動上の必要が変われば変更すると記しました。定員だけでなく起こり得る変更も確認したことで、一度全員を入れるだけではない柔軟な避難計画になりました。'},
'V11-B15-G3-015':{en:' The article also linked the graph title directly to the survey question and stated the number of respondents. Readers could then see the difference between a report about regular users and a claim about the whole school.',jp:' 記事ではグラフの題名もアンケート質問に直接対応させ、回答者数も示しました。これにより、常用者についての報告と学校全体についての主張の違いを読者が確認できるようになりました。'},
'V11-B15-G3-016':{en:' The group scheduled future sampling for the first Friday of each month at the same hour and planned to record recent rainfall beside every result. They noted that matching conditions would not remove every difference, but it would make changes easier to interpret.',jp:' グループは今後、毎月最初の金曜日の同じ時刻に採水し、各結果の横に直前の降雨量も記録することにしました。条件をそろえてもすべての違いがなくなるわけではありませんが、変化の意味を判断しやすくなると考えました。'}
};
for(const file of ['v11_batch15_g2_body_draft.json','v11_batch15_g3_body_draft.json']){
 const d=JSON.parse(fs.readFileSync(file,'utf8'));
 for(const p of d.passages){const a=additions[p.id];if(!a) continue;if(p.bodyExpansion==='B15_R2') continue;p.body+=a.en;p.fullTranslation+=a.jp;p.bodyExpansion='B15_R2';p.humanSemanticReview=`B15_G${d.grade}_HUMAN_DRAFT_R2`;}
 d.status='BODY_TRANSLATION_HUMAN_SEMANTIC_DRAFT_R2_WORDCOUNT_REPAIR';
 fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
}
console.log('Batch15 R2 body expansions applied',Object.keys(additions).length);
