(function finalizeV11Batch04Grade3Notes(){
'use strict';
const gloss={
'attached':'添付した・取り付けた','balance':'バランス','command':'指示・命令','correct':'正しい','delay':'遅れ','email':'メール','exactly':'正確に','file':'ファイル','files':'ファイル','final':'最終の','joint':'共同の','partner':'相手','photos':'写真','project':'課題','projects':'課題','purpose':'目的','quickly':'すばやく','rather':'むしろ','request':'依頼','requests':'依頼','require':'必要とする','rewrote':'書き直した','rude':'失礼な','schedule':'予定','specific':'具体的な','state':'述べる・状態','urgency':'緊急性','version':'版・バージョン','within':'〜以内に','without':'〜なしで',
'beside':'〜のそばに','compared':'比べた','delete':'削除する','directly':'直接','focused':'集中した','hiding':'隠して','location':'場所','mark':'印','marked':'印をつけた','normal':'通常の','period':'期間・時間帯','readings':'測定値・読み取り値','record':'記録','similar':'似ている','simply':'単に','strange':'奇妙な','sunny':'晴れた','temperature':'温度','unusual':'珍しい・通常でない','unusually':'珍しく','usual':'いつもの',
'activity':'活動','choice':'選択','clever':'巧みな','conversation':'会話','easier':'より簡単な','explanation':'説明','expression':'表現','hoped':'望んだ','idioms':'慣用表現','immediately':'すぐに','matters':'重要である','phrase':'表現・句','plain':'平易な','replaced':'置き換えた','simple':'簡単な','simpler':'より簡単な','used':'使った',
'accurate':'正確な','advertising':'広告','confused':'混乱した','confusion':'混乱','copy':'写し・コピー','copying':'写すこと','details':'詳細','direct':'直接の','easiest':'最も簡単な','festival':'祭り','grammar':'文法','individual':'個々の','itself':'それ自体','lively':'生き生きした','mentioned':'述べた','obviously':'明らかに','readers':'読者','remained':'残った','shape':'形','suggested':'提案した','though':'〜だけれども','title':'題名','titles':'題名','translated':'翻訳した','translation':'翻訳','visitor':'訪問者','visitors':'訪問者たち',
'activities':'活動','classrooms':'教室','compare':'比べる','evidence':'根拠','grade':'学年','habits':'習慣','honestly':'正直に','pattern':'型・傾向','proposed':'提案した','repeating':'繰り返して','stated':'述べた','statement':'記述・文','test':'テスト','thirty':'30','wide':'幅が広い','wider':'より幅が広い',
'black':'黒い','blue':'青い','description':'説明','entrance':'入口','form':'用紙・形式','prompts':'設問文','six':'6',
'automatically':'自動的に','community':'地域社会','crossings':'横断場所・交差点','difference':'違い','five':'5','narrow':'狭い','passed':'通った','preparations':'準備','routes':'経路','seem':'〜のように思える','slightly':'少し','streetlights':'街灯',
'advised':'助言した','attend':'参加する','coach':'コーチ','complete':'完成させる・完全な','completed':'完成した','concerns':'懸念','deadline':'締め切り','estimated':'見積もった','extra':'追加の','paragraph':'段落','phone':'電話','preparation':'準備','reasonable':'妥当な','recent':'最近の','section':'部分・節','session':'時間・講習','skip':'飛ばす','suggestion':'提案','tired':'疲れた','using':'使って',
'area':'地域・場所','argument':'議論','background':'背景','bicycle':'自転車','checked':'確認した','copied':'写した','date':'日付','noticed':'気づいた','office':'事務所','page':'ページ','practice':'練習','previous':'前の','recorded':'記録した','several':'いくつかの','source':'出典','taught':'教えた','totals':'合計','update':'更新する','web':'ウェブ',
'blank':'空欄の','columns':'列','confirmed':'確認した','event':'行事','everyone':'みんな','messy':'まとまりのない','morning':'朝','organizers':'主催者','rebuilding':'作り直して','reply':'返事','role':'役割','roles':'役割','rows':'行','separate':'分ける・別々の','separately':'別々に','sheets':'用紙','starting':'始めること','unclear':'不明確な','updated':'更新した','usable':'使える','volunteers':'ボランティアたち','whole':'全体の',
'bus':'バス','cheaper':'より安い','cheapest':'最も安い','comparing':'比べて','fit':'合う','garden':'庭','group':'グループ','limit':'制限','market':'市場','museum':'博物館','photographs':'写真','produced':'作った・生産した','reason':'理由','required':'必要とされた','seemed':'〜のように思えた','stop':'停留所・止まる','total':'合計','tourism':'観光','transportation':'交通','unexpected':'予想外の','value':'価値',
'audience':'聴衆','bar':'棒・帯','data':'データ','e':'e','groups':'グループ','heights':'高さ','incorrectly':'誤って','label':'ラベル','labeled':'ラベルを付けた','labels':'ラベル','meant':'意味した','nobody':'だれも〜ない','per':'〜につき','presentation':'発表','real':'本当の','unit':'単位','week':'週',
'actual':'実際の','broad':'幅広い','described':'説明した','detail':'詳細','general':'一般的な','hard':'難しい','interviewed':'インタビューした','producing':'作成して','reminder':'注意・思い出させるもの','unnatural':'不自然な','volunteer':'ボランティア',
'applications':'申請・応募','arguing':'議論して','board':'掲示板','calendar':'カレンダー','confirming':'確認して','dates':'日付','discussed':'話し合った','exact':'正確な','forms':'用紙・形式','included':'含めた','month':'月','notice':'掲示・知らせ','online':'オンラインの','posted':'掲示した','preferred':'より好んだ','stopped':'止めた','thought':'考えた','versions':'版',
'allowed':'許された','attractive':'魅力的な','checking':'確認すること','chose':'選んだ','decision':'決定','edit':'編集する','editing':'編集','features':'特徴・機能','functions':'機能','offered':'提供した','popularity':'人気','products':'製品','replace':'置き換える','slide':'スライド','slides':'スライド','tested':'試した',
'geographically':'地理的に','hall':'ホール','helpful':'役に立つ','main':'主な','map':'地図','path':'道筋','printed':'印刷した','restrooms':'トイレ','route':'経路','secondary':'補助的な','staircase':'階段','symbol':'記号',
'reading':'読むこと','nighttime':'夜','port':'港','mud':'泥','divided':'分けられた','protect':'守る','local people':'地元の人々','swallowed':'飲み込んだ','space':'場所・空間','smell':'におい','further':'さらに遠く','leaf':'葉','flood':'洪水','filtered':'ろ過した','insects':'昆虫','sealed':'密閉した','threatened':'おびやかした'
};
const grade3=[...(window.V11_BATCH04_G3_PASSAGES||[])];
let replaced=0,unresolved=[];
for(const p of grade3){p.notes=Array.isArray(p.notes)?p.notes:[];for(const n of p.notes){if(!n||!n.english||!String(n.japanese||'').includes('最終注整理対象'))continue;const key=String(n.english).replace(/[’]/g,"'").toLowerCase();if(gloss[key]){n.japanese=gloss[key];n.source='v11 Batch04 grade3 final context gloss 20260828';replaced++;}else unresolved.push({id:p.id,english:n.english});}}
window.V11_BATCH04_G3_NOTE_FINALIZE_STATE={version:'20260828-g3-final',passages:grade3.length,replaced,unresolved,ready:grade3.length===16&&unresolved.length===0};
})();
