(function buildV11Batch03Grade3Draft(){
'use strict';
const BATCH='V11-B03-G3-DRAFT-20260828';
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while|although)\b/gi,'/ $1');}
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function build(id,textbook,section,baseline,title,rows,long,notes){const qs=rows.slice(0,10).map((r,i)=>({prompt:`${i+1}. 本文の第${i+1}文の内容に合う英文を本文から一文答えなさい。`,answer:r[0],evidence:r[0],evidenceJp:r[1],reason:`第${i+1}文が直接の根拠です。`}));return {id,textbook,grade:'3',section,level:'JUMP',title,genre:'story',batch:BATCH,sourceSectionBaselineId:baseline,targetWordBand:long?[210,270]:[140,185],wordCount:wc(rows),sentences:rows.map(r=>r[0]),fullTranslation:rows.map(r=>r[1]).join(''),slashRows:rows.map(r=>({en:slash(r[0]),jp:r[1]})),questions:qs.slice(0,5),questionSetB:qs.slice(5,10),notes:(notes||[]).map(n=>({english:n[0],japanese:n[1],kind:'unlearned_local_required',source:'v11 Batch03 G3 story-specific required note seed'})),semanticRewrite:'BATCH03_G3_STORY_SPECIFIC_20260828',registered:false,auditNote:'Batch03 G3 non-runtime authoring draft. Story-specific passage; chronology, length, question diversity, notes, cross-batch, PC/iPhone and A4 gates still required.'};}
const SS='サンシャイン',NH='ニューホライズン',ssBase='V10-SS-G3-P7-3-001',nhBase='V10-NH-G3-U6-4-001';
const all=[
build('V11-SS-G3-P7-3-019',SS,'PROGRAM 7-3',ssBase,'A Robot for Carrying Books',[
['Our class was asked to imagine a robot that could solve one real school problem.','私たちのクラスは、学校の実際の問題を一つ解決できるロボットを考えるよう求められました。'],
['My group thought about the heavy boxes of books that teachers sometimes move between rooms.','私たちの班は先生たちがときどき部屋の間を運ぶ重い本の箱について考えました。'],
['We imagined a small robot that could lift one box and follow a person through the hall.','私たちは箱を一つ持ち上げ、人について廊下を進める小さなロボットを想像しました。'],
['At first, the idea sounded simple and useful.','最初、その案は簡単で役立ちそうに思えました。'],
['Then one student asked what would happen if someone suddenly walked in front of the robot.','すると一人の生徒が、だれかが急にロボットの前を歩いたらどうなるのかたずねました。'],
['That question made us add a rule that the robot must stop when a person is too close.','その質問から、人が近すぎるときロボットは止まらなければならないというルールを加えました。'],
['Another student suggested that the robot should move slowly when it was carrying a heavy box.','別の生徒は重い箱を運ぶときはゆっくり動くべきだと提案しました。'],
['We wrote these points in a short document beside our drawing.','私たちはこれらの点を絵のそばの短い文書に書きました。'],
['Our teacher liked the useful purpose but asked us not to forget the people around the machine.','先生は役立つ目的を評価しましたが、機械の周りの人を忘れないよう言いました。'],
['By the end of the activity, we understood that a powerful robot also needs careful limits.','活動の終わりには、強力なロボットには注意深い制限も必要だと分かりました。'],
['The best part of our idea was not lifting books; it was thinking about how the robot could help without causing a new problem.','私たちの案のいちばん大切な点は本を持ち上げることではなく、新しい問題を起こさずにどう助けられるか考えることでした。']
],false,[['limit','制限'],['suddenly','急に']]),
build('V11-SS-G3-P7-3-020',SS,'PROGRAM 7-3',ssBase,'A Robot That Listens',[
['During a class discussion about technology, we imagined a robot for a person who lives alone.','技術についての授業で、私たちは一人暮らしの人のためのロボットを想像しました。'],
['The robot would not be designed to clean a room or carry heavy boxes.','そのロボットは部屋を掃除したり重い箱を運んだりするためのものではありません。'],
['Its main purpose would be to listen and help a person feel connected during quiet parts of the day.','主な目的は話を聞き、一日の静かな時間に人がつながりを感じる助けをすることです。'],
['One student suggested that the robot could ask simple questions about meals, weather, or a favorite memory.','一人の生徒は食事、天気、好きな思い出について簡単な質問をできると提案しました。'],
['Another student wanted it to remember topics that the person enjoyed talking about.','別の生徒は、その人が話すのを楽しむ話題を覚えてほしいと考えました。'],
['At first, our group became excited about all the things the robot might say.','最初、私たちの班はロボットが話せるかもしれない多くのことにわくわくしました。'],
['Then our teacher asked whether a machine should become the only conversation partner in someone’s life.','すると先生は、機械がだれかの人生で唯一の話し相手になってよいのかたずねました。'],
['That question changed the direction of our discussion.','その質問で話し合いの方向が変わりました。'],
['We decided that the robot should help a person connect with family, neighbors, or other people rather than replace them.','私たちはロボットが人の代わりになるのではなく、家族や近所の人などとつながるのを助けるべきだと決めました。'],
['For example, it could remind the person about a planned call or help start a video conversation.','例えば、予定された電話を知らせたり、ビデオでの会話を始める助けをしたりできます。'],
['It might also notice when the person had not spoken with anyone for a long time and suggest contacting someone.','長い間だれとも話していないことに気づき、だれかに連絡することを提案することも考えられます。'],
['We added a clear privacy rule: the robot should not share personal information without permission.','私たちは明確なプライバシーのルールも加えました。許可なく個人情報を共有してはいけないというものです。'],
['Our document described the robot as a bridge to people, not a replacement for people.','私たちの文書では、ロボットを人の代わりではなく、人へつながる橋として説明しました。'],
['The final idea was less simple than our first idea, but it felt more responsible.','最終案は最初の案より単純ではありませんでしたが、より責任あるものに感じました。'],
['We learned that reducing loneliness is not only a technical problem.','孤独を減らすことは技術だけの問題ではないと学びました。'],
['Technology can support human relationships, but those relationships still need real people.','技術は人間関係を支えられますが、その関係にはやはり実際の人が必要です。']
],true,[['privacy','プライバシー'],['permission','許可'],['bridge','橋・つなぐもの'],['responsible','責任ある']]),
build('V11-SS-G3-P7-3-021',SS,'PROGRAM 7-3',ssBase,'The Password Rule',[
['Our team designed a simple system for a classroom robot.','私たちの班は教室ロボットのための簡単なシステムを考えました。'],
['At first, every student used the same password to open the control page.','最初、全員が同じパスワードで操作ページを開いていました。'],
['It was easy to remember, so no one saw a problem.','覚えやすかったので、だれも問題だと思いませんでした。'],
['Then one student wrote the password on a paper and left it beside the computer.','すると一人の生徒がパスワードを紙に書き、コンピューターのそばに置いたままにしました。'],
['Our teacher asked what could happen if a visitor found that paper.','先生は来客がその紙を見つけたらどうなるかたずねました。'],
['We realized that the robot could be controlled by someone who should not use it.','使うべきでない人がロボットを操作できてしまうと気づきました。'],
['The team changed the rule and stopped leaving the password in an open place.','班はルールを変え、パスワードを見える場所に置かないようにしました。'],
['We also decided that an adult should change it when too many people knew it.','あまりに多くの人が知ったときは大人が変更することにしました。'],
['A short safety note was added to the document for the robot system.','ロボットシステムの文書に短い安全上の注意を加えました。'],
['The password had seemed like a small detail, but it protected the whole system.','パスワードは小さな点に見えましたが、システム全体を守るものでした。'],
['That activity taught us that useful technology also needs simple rules that people can actually follow.','その活動から、役立つ技術には人が実際に守れる簡単なルールも必要だと学びました。']
],false,[['password','パスワード'],['control','操作する'],['detail','細部']]),
build('V11-SS-G3-P7-3-022',SS,'PROGRAM 7-3',ssBase,'Shaking Hands with a Robot',[
['Our class watched a small robot demonstrate how it could greet a person.','私たちのクラスは小さなロボットが人にあいさつする実演を見ました。'],
['The robot could move one arm and shake hands.','そのロボットは片腕を動かして握手できました。'],
['During the first test, the movement was faster and stronger than we expected.','最初のテストでは、動きが予想より速く強いものでした。'],
['The student who tested it pulled a hand back and laughed, but the team became serious.','試した生徒は手を引いて笑いましたが、班は真剣になりました。'],
['A greeting should not make a person feel unsafe.','あいさつで人を不安にさせてはいけません。'],
['The team reduced the speed and changed how far the robot moved its arm.','班は速さを下げ、腕を動かす距離を変えました。'],
['They tested the new movement several times with an adult watching.','大人が見守る中、新しい動きを何度か試しました。'],
['The second handshake felt much gentler.','二回目の握手はずっとやさしく感じました。'],
['Students then discussed why a small movement can matter when a machine touches a person.','生徒たちは機械が人に触れるとき、なぜ小さな動きが重要なのか話し合いました。'],
['Power was not the goal; a comfortable human interaction was the goal.','力が目的ではなく、人が心地よく関われることが目的でした。'],
['The demonstration showed that a robot must be designed around people, not only around what the machine can do.','その実演から、ロボットは機械に何ができるかだけでなく、人を中心に設計する必要があると分かりました。']
],false,[['demonstrate','実演する'],['gentle','やさしい'],['interaction','関わり']]),
build('V11-SS-G3-P7-3-023',SS,'PROGRAM 7-3',ssBase,'A Meeting about School Robots',[
['Our student group joined a meeting about possible uses for robots at school.','私たちの生徒グループは学校でのロボット利用についての会議に参加しました。'],
['Two ideas received the most attention.','二つの案がもっとも注目を集めました。'],
['The first was a robot that could guide visitors through the building.','一つ目は来校者を校内で案内できるロボットでした。'],
['The second was a robot that could carry heavy materials between classrooms.','二つ目は教室間で重い材料を運べるロボットでした。'],
['At first, the guide robot sounded more interesting because it could talk with many people.','最初、案内ロボットは多くの人と話せるので、よりおもしろそうに思えました。'],
['Then we listed problems that teachers and students actually faced every week.','それから先生や生徒が毎週実際に直面している問題を挙げました。'],
['Heavy boxes appeared on the list several times, while visitors were usually helped by people at the office.','重い箱は何度もリストに出ましたが、来校者はたいてい事務室の人が案内していました。'],
['The group began to see that the less exciting idea might solve the greater need.','班は、あまり派手でない案のほうが大きな必要を解決するかもしれないと分かり始めました。'],
['We chose the carrying robot and wrote reasons for the decision.','私たちは運搬ロボットを選び、その理由を書きました。'],
['Our document also said that people should continue helping visitors directly.','文書には来校者への案内は人が直接続けるべきだとも書きました。'],
['The meeting taught us to start with a real problem instead of choosing technology because it looks impressive.','その会議から、技術が印象的だから選ぶのではなく、実際の問題から始めることを学びました。']
],false,[['impressive','印象的な'],['directly','直接']]),
build('V11-SS-G3-P7-3-024',SS,'PROGRAM 7-3',ssBase,'The Document beside the Robot',[
['Our group built a simple model of a robot for a class project, but the teacher gave us another task.','私たちの班は授業のプロジェクトで簡単なロボット模型を作りましたが、先生は別の課題を出しました。'],
['We had to write a document that explained the robot’s purpose so another class could understand it without hearing our presentation.','発表を聞かなくても別のクラスが理解できるよう、ロボットの目的を説明する文書を書く必要がありました。'],
['At first, we filled the page with technical words that seemed clear to us.','最初、私たちには分かりやすく思えた技術的な言葉でページをいっぱいにしました。'],
['We described the robot system, its password, and several parts of its movement.','ロボットのシステム、パスワード、動きのいくつかの部分について説明しました。'],
['Then students from another class read the page beside the robot model.','それから別のクラスの生徒たちがロボット模型のそばでそのページを読みました。'],
['They understood what the robot looked like, but several students could not tell what problem it was supposed to solve.','ロボットの見た目は分かりましたが、何の問題を解決するものなのか分からない生徒が何人もいました。'],
['That result surprised us because the purpose had seemed obvious while we were writing.','書いている間は目的が明らかだと思っていたので、その結果に驚きました。'],
['We asked the readers which parts were unclear and wrote down their questions.','どの部分が分かりにくかったか読み手にたずね、質問を書き留めました。'],
['One question was simply, “Who is this robot for?”','一つの質問は単純に「このロボットはだれのためですか」でした。'],
['Another was, “Why is a robot needed here?”','別の質問は「なぜここにロボットが必要なのですか」でした。'],
['We rewrote the beginning of the document to answer those questions first.','私たちは文書の最初を書き直し、まずそれらの質問に答えるようにしました。'],
['The new version started with the person who needed help and the problem that person faced.','新しい版は助けを必要とする人と、その人が直面する問題から始めました。'],
['Technical details came later, after the purpose was clear.','技術的な詳細は、目的が明確になったあとに置きました。'],
['When the second group read the new document, they explained the robot’s purpose correctly in their own words.','二つ目のグループが新しい文書を読むと、自分たちの言葉でロボットの目的を正しく説明できました。'],
['Our robot model had not changed at all, but the way people understood it had changed greatly.','ロボット模型自体はまったく変わっていませんでしたが、人の理解の仕方は大きく変わりました。'],
['We learned that a useful document begins with the reader’s question, not with the writer’s knowledge.','役立つ文書は書き手の知識ではなく、読み手の疑問から始まると学びました。']
],true,[['technical','技術的な'],['obvious','明らかな'],['reader','読み手']]),
build('V11-SS-G3-P7-3-025',SS,'PROGRAM 7-3',ssBase,'Connecting Two Generations',[
['Our class discussed how technology might connect older and younger people in the same town.','私たちのクラスは技術が同じ町の年上の人と若い人をどうつなげられるか話し合いました。'],
['One idea was a simple robot that could help start regular conversations.','一つの案は定期的な会話を始める助けをする簡単なロボットでした。'],
['The robot could remind an older person about a planned call with a student group.','ロボットは年上の人に生徒グループとの予定された電話を知らせることができます。'],
['It could also help the person open the right screen for the conversation.','会話のための正しい画面を開く助けもできます。'],
['Students could ask about local history, old school life, or changes in the town.','生徒は地域の歴史、昔の学校生活、町の変化などをたずねられます。'],
['The older person could ask students about present school life in return.','年上の人も代わりに現在の学校生活について生徒にたずねられます。'],
['Our group agreed that the robot should only support the connection.','私たちの班はロボットはつながりを支えるだけにすべきだと意見が一致しました。'],
['If the machine did all the talking, the two generations would not really get to know each other.','もし機械が全部話したら、二つの世代は本当におたがいを知ることができません。'],
['We wrote a rule that every meeting should include real conversation between people.','私たちはすべての交流に人同士の実際の会話を含めるというルールを書きました。'],
['Technology could make the first step easier, but people would create the relationship themselves.','技術は最初の一歩を簡単にできますが、関係を作るのは人自身です。'],
['That balance became the most important part of our plan.','そのバランスが私たちの計画で最も大切な部分になりました。']
],false,[['generation','世代'],['regular','定期的な'],['balance','バランス']]),
build('V11-SS-G3-P7-3-026',SS,'PROGRAM 7-3',ssBase,'When the Robot Stops',[
['A small classroom robot stopped moving during our demonstration.','小さな教室ロボットが実演中に動かなくなりました。'],
['The robot had worked correctly during practice only ten minutes earlier.','そのロボットはわずか十分前の練習では正しく動いていました。'],
['Several students looked worried because another class was watching.','別のクラスが見ていたので、何人かの生徒は心配そうでした。'],
['One student wanted to restart everything immediately.','一人の生徒はすぐに全部を再起動したがりました。'],
['Our team leader asked everyone to stop and check the system step by step.','班のリーダーはみんなに止まり、システムを一つずつ確認するよう言いました。'],
['We first checked the power and then the connection to the control page.','まず電源を確認し、それから操作ページとの接続を確認しました。'],
['The power was fine, but the connection had been lost.','電源は問題ありませんでしたが、接続が切れていました。'],
['An adult helped us connect the system again.','大人がシステムを再接続するのを手伝ってくれました。'],
['Before continuing, we told the audience what had happened.','続ける前に、何が起きたか見ている人たちに説明しました。'],
['We did not pretend that the stop was part of the demonstration.','停止が実演の一部だったふりはしませんでした。'],
['The robot moved again, and we finished the final part safely.','ロボットはまた動き、最後の部分を安全に終えました。'],
['The unexpected stop showed us that technology can fail and that a calm response is part of using it responsibly.','予想外の停止から、技術は失敗することがあり、落ち着いて対応することも責任ある利用の一部だと分かりました。']
],false,[['connection','接続'],['audience','見ている人たち'],['unexpected','予想外の']]),
build('V11-NH-G3-U6-4-019',NH,'Unit 6-4',nhBase,'The Coat from Another Country',[
['I bought a coat at a small shop in my town and later looked at the label inside it.','私は町の小さな店でコートを買い、あとで内側のラベルを見ました。'],
['The label showed that the coat had been made in another country.','ラベルにはそのコートが別の国で作られたと書かれていました。'],
['That made me wonder how many places were connected to one ordinary coat.','それを見て、一着の普通のコートにいくつの場所がつながっているのか考えました。'],
['In class, I used the coat as an example during a discussion about trade.','授業で貿易について話し合うとき、そのコートを例として使いました。'],
['The cloth might come from one country, while buttons or other parts could come from somewhere else.','布は一つの国から来て、ボタンなどの部品は別の場所から来るかもしれません。'],
['Workers in another place could put the parts together.','別の場所の人々が部品を組み合わせることもあります。'],
['After that, transport would carry the finished coat across borders to shops.','そのあと、輸送によって完成したコートが国境を越えて店へ運ばれます。'],
['A local shop worker would finally place it where customers could see it.','最後に地域の店員が客に見える場所へ置きます。'],
['Our teacher pointed out that we could not know every step from one label alone.','先生は一つのラベルだけではすべての段階を知ることはできないと指摘しました。'],
['Still, the coat helped us understand that daily life can depend on people in many different places.','それでもそのコートのおかげで、日常生活が多くの場所の人々に支えられていると理解できました。'],
['I left class thinking differently about an object that had seemed completely ordinary that morning.','私はその朝はまったく普通に見えた物について、違う考え方をしながら授業を終えました。']
],false,[['label','ラベル'],['cloth','布'],['button','ボタン'],['transport','輸送']]),
build('V11-NH-G3-U6-4-020',NH,'Unit 6-4',nhBase,'An Island and Clean Water',[
['Our class studied an island surrounded by the sea and asked a question that seemed strange at first.','私たちのクラスは海に囲まれた島について学び、最初は不思議に思える質問を考えました。'],
['If water is everywhere around an island, why might the people there still depend on trade for water-related needs?','島の周りに水がたくさんあるのに、なぜそこに住む人々が水に関する必要で貿易に頼ることがあるのでしょうか。'],
['We quickly realized that sea water is not the same as clean water for drinking and daily life.','海水は飲み水や生活に使う清潔な水と同じではないとすぐ気づきました。'],
['Some islands have enough fresh water, while others have limited natural supplies.','十分な淡水がある島もあれば、自然の供給が限られている島もあります。'],
['People may need equipment, fuel, containers, or other products to collect, clean, or move water safely.','水を安全に集め、きれいにし、運ぶために設備、燃料、容器などが必要になることがあります。'],
['Those products can come from other countries through trade.','それらの製品は貿易を通じて他国から来ることがあります。'],
['Our group drew a simple diagram showing an island, a port, and several incoming products.','私たちの班は島、港、いくつかの入ってくる製品を示す簡単な図を描きました。'],
['Another group added food and medicine to show that water was only one part of a larger relationship.','別の班は食料と薬も加え、水はより大きな関係の一部にすぎないことを示しました。'],
['Then we imagined what could happen if ships could not arrive for several weeks.','それから数週間船が来られなかったら何が起きるか想像しました。'],
['The island might still have many local resources, but some important goods could become difficult to replace.','島には多くの地域資源があっても、重要な品物の一部は補うのが難しくなるかもしれません。'],
['This did not mean that the island was weak.','これは島が弱いという意味ではありません。'],
['It meant that modern daily life often depends on relationships beyond one border.','現代の日常生活は一つの国境を越えた関係に頼ることが多いという意味です。'],
['We also discussed how other countries could depend on products or knowledge from the island in return.','逆に他国も島の製品や知識に頼ることがあると話し合いました。'],
['The relationship was not one direction; it was interdependent.','その関係は一方向ではなく、相互依存でした。'],
['By the end of the lesson, the sea around the island no longer looked like a wall separating it from the world.','授業の終わりには、島を囲む海は世界から隔てる壁のようには見えなくなりました。'],
['Instead, we saw it as part of the routes that connect the island to many other places.','むしろ、島を多くの場所とつなぐ道の一部として見えるようになりました。']
],true,[['fresh water','淡水'],['equipment','設備'],['port','港'],['resource','資源']]),
build('V11-NH-G3-U6-4-021',NH,'Unit 6-4',nhBase,'Three Countries, One Product',[
['Our teacher gave each group a card describing one simple product.','先生はそれぞれの班に一つの簡単な製品を説明したカードを渡しました。'],
['Our card showed that the product passed through three countries before reaching a customer.','私たちのカードには、その製品が客に届くまで三つの国を通ると書かれていました。'],
['The first country provided a basic material.','最初の国が基本となる材料を提供しました。'],
['The second country used that material to make an important part.','二つ目の国がその材料を使って重要な部品を作りました。'],
['The third country put several parts together and prepared the final product for sale.','三つ目の国がいくつかの部品を組み合わせ、最終製品を販売できる状態にしました。'],
['We drew arrows between the three countries to show the movement.','私たちは動きを示すため三つの国の間に矢印を描きました。'],
['Then our teacher removed one arrow and asked what would happen.','すると先生は一つの矢印を消し、何が起きるかたずねました。'],
['We saw that the next country might not receive the part it needed.','次の国が必要な部品を受け取れなくなるかもしれないと分かりました。'],
['The whole chain could slow down even though only one connection had changed.','一つのつながりが変わっただけでも、全体の流れが遅くなる可能性がありました。'],
['The activity helped us understand why countries can be interdependent through one ordinary product.','その活動から、一つの普通の製品を通して国々が相互依存する理由を理解できました。']
],false,[['provided','提供した'],['chain','つながり・連鎖']]),
build('V11-NH-G3-U6-4-022',NH,'Unit 6-4',nhBase,'When One Border Closes',[
['We used a classroom map to model trade between several countries.','私たちは教室の地図を使って、いくつかの国の間の貿易を模型化しました。'],
['Colored lines showed the routes used to move products.','色のついた線が製品を運ぶルートを示していました。'],
['Our teacher suddenly covered one border on the map.','先生が突然、地図上の一つの国境を隠しました。'],
['The class had to imagine that goods could no longer pass through that route.','そのルートを品物が通れなくなったと想像しなければなりませんでした。'],
['At first, one group thought the trade would simply stop.','最初、一つの班は貿易が単純に止まると思いました。'],
['Another group noticed a longer route through a third country.','別の班が第三国を通る長いルートに気づきました。'],
['Using that route would take more time and might cost more, but it could keep some trade moving.','そのルートは時間がかかり費用も増えるかもしれませんが、一部の貿易を続けられます。'],
['We moved the colored line and compared the new map with the original one.','色の線を動かし、新しい地図と元の地図を比べました。'],
['The change showed both the strength and the risk of interdependence.','その変化は相互依存の強さと危険の両方を示しました。'],
['Connections can provide another way to solve a problem, but a problem in one place can also affect many others.','つながりは問題を解決する別の方法を与えますが、一か所の問題が多くの場所へ影響することもあります。'],
['The model was simple, yet it made the idea of trade relationships much easier to understand.','模型は単純でしたが、貿易関係の考えをずっと理解しやすくしました。']
],false,[['model','模型化する'],['route','ルート'],['affect','影響する']]),
build('V11-NH-G3-U6-4-023',NH,'Unit 6-4',nhBase,'The Exception on the List',[
['Our class received a list showing where several everyday products came from.','私たちのクラスは、いくつかの日用品がどこから来たかを示すリストを受け取りました。'],
['Most products followed a similar pattern and passed through more than one country.','多くの製品は似た流れで、一つより多くの国を通っていました。'],
['One item on the list was different.','リストの一つの品物だけが違っていました。'],
['It was produced and sold within the same country.','それは同じ国内で作られ、販売されていました。'],
['At first, some students thought the item did not belong in a lesson about trade.','最初、何人かの生徒はその品物は貿易の授業に合わないと思いました。'],
['Our teacher asked us to keep it and explain why the exception was useful.','先生はそれを残し、なぜその例外が役立つのか説明するよう求めました。'],
['Comparing it with the other products helped us see which parts of their movement depended on crossing borders.','ほかの製品と比べることで、その流れのどの部分が国境を越えることに頼っているか分かりました。'],
['The local item also reminded us that not every daily product has the same trade story.','地域の品物は、すべての日用品が同じ貿易の物語を持つわけではないことも思い出させました。'],
['The exception made the common pattern clearer instead of weakening it.','その例外は共通の流れを弱めるのではなく、よりはっきりさせました。'],
['By the end, we understood why good comparisons often need at least one different case.','最後には、よい比較には少なくとも一つ違う事例が必要なことが多いと理解しました。']
],false,[['exception','例外'],['pattern','型・パターン'],['case','事例']]),
build('V11-NH-G3-U6-4-024',NH,'Unit 6-4',nhBase,'Daily Life without One Import',[
['Our teacher asked us to choose one familiar imported product and imagine a day without it.','先生は身近な輸入品を一つ選び、それがない一日を想像するよう言いました。'],
['My group chose a common electronic device used at both school and home.','私たちの班は学校と家庭の両方で使う一般的な電子機器を選びました。'],
['At first, we thought the change would only affect people who wanted to buy a new device.','最初、その変化は新しい機器を買いたい人だけに影響すると思いました。'],
['Then we began listing all the services and activities connected to that product.','それから、その製品につながるサービスや活動をすべて挙げ始めました。'],
['A shop might have less to sell, and repair workers might have difficulty getting replacement parts.','店は売る物が減り、修理する人は交換部品を手に入れにくくなるかもしれません。'],
['Schools could face problems if older devices stopped working and new ones were unavailable.','古い機器が壊れ、新しい物が手に入らなければ、学校も問題に直面するかもしれません。'],
['Families might keep using old products longer or share devices more often.','家庭では古い製品をより長く使ったり、機器を共有することが増えたりするかもしれません。'],
['Transport companies and stores would also change their plans because fewer products were moving.','運ぶ製品が減るので、輸送会社や店も計画を変えるでしょう。'],
['Our list became much longer than we expected.','私たちのリストは予想よりずっと長くなりました。'],
['The exercise showed that one import can be connected to many jobs and routines.','その活動から、一つの輸入品が多くの仕事や日常の行動につながっていると分かりました。'],
['We also discussed possible alternatives instead of assuming that daily life would simply stop.','日常生活が単に止まると考えるのではなく、代わりの方法についても話し合いました。'],
['People might repair more, reuse older products, or buy a different product from another source.','人々はより多く修理し、古い製品を再利用し、別の供給元から違う製品を買うかもしれません。'],
['Each response would create new effects of its own.','それぞれの対応がまた別の影響を生みます。'],
['By imagining only one missing import, we could see how complex international connections are.','一つの輸入品がないと想像するだけで、国際的なつながりがどれほど複雑か見ることができました。'],
['The product itself was ordinary, but the network around it was not simple at all.','製品自体は普通でしたが、その周りのつながりは決して単純ではありませんでした。']
],true,[['electronic','電子の'],['replacement','交換用の'],['alternative','代わりの方法'],['network','つながり・ネットワーク']]),
build('V11-NH-G3-U6-4-025',NH,'Unit 6-4',nhBase,'A Small Shop and the World',[
['There is a small shop near my home that sells clothes, food, and simple household goods.','家の近くに衣類、食べ物、簡単な日用品を売る小さな店があります。'],
['I had visited it many times without thinking about where the products came from.','私は製品がどこから来るか考えずに何度もその店を訪れていました。'],
['For a class project, I chose the shop as a starting point for studying trade.','授業の課題で、その店を貿易について調べる出発点に選びました。'],
['I looked at several labels and wrote down the countries named on them.','いくつかのラベルを見て、書かれていた国名をメモしました。'],
['The products came from many different places, even though they were sitting on shelves only a few meters apart.','製品はほんの数メートルしか離れていない棚に並んでいましたが、多くの違う場所から来ていました。'],
['I then thought about the people needed to move one product from a producer to this small shop.','それから一つの製品を生産者からこの小さな店まで運ぶのに必要な人々について考えました。'],
['Someone had to make or grow it, someone had to prepare it for transport, and others had to carry it across long distances.','だれかが作ったり育てたりし、だれかが輸送の準備をし、別の人々が長い距離を運ぶ必要があります。'],
['After it entered the country, more workers moved it to local stores.','その国に入ったあと、さらに別の働く人が地域の店まで運びます。'],
['Finally, a shop worker placed it on a shelf and a customer chose whether to buy it.','最後に店員が棚に置き、客が買うかどうか選びます。'],
['The chain included people who would never meet one another.','その流れにはおたがいに会うことのない人々も含まれていました。'],
['Still, their work was connected through the same product.','それでも彼らの仕事は同じ製品を通してつながっていました。'],
['I also realized that money moved in the opposite direction through the relationship.','また、その関係ではお金が反対方向へ動くことにも気づきました。'],
['The customer paid the shop, and the value was shared through different parts of the trade system.','客が店に払い、その価値が貿易システムのさまざまな部分を通して分けられます。'],
['Our teacher reminded us that the real system was more complicated than my simple drawing.','先生は実際の仕組みは私の簡単な絵より複雑だと教えてくれました。'],
['Even so, the drawing changed the way I saw the little shop.','それでも、その絵は私がその小さな店を見る目を変えました。'],
['It was not only a local place; it was one small point in a much larger international network.','そこは地域の場所であるだけでなく、はるかに大きな国際的なつながりの一つの小さな点でした。']
],true,[['household','家庭の'],['producer','生産者'],['value','価値']]),
build('V11-NH-G3-U6-4-026',NH,'Unit 6-4',nhBase,'Why Trade Needs Trust',[
['Our class compared two imaginary trade relationships between countries.','私たちのクラスは国どうしの二つの架空の貿易関係を比べました。'],
['In the first relationship, information about delivery times and product quality was shared clearly.','一つ目の関係では、配達時期や製品の品質についての情報が明確に共有されていました。'],
['When a problem happened, both sides reported it quickly and worked on a solution.','問題が起きたとき、両側がすぐ報告し、解決に取り組みました。'],
['In the second relationship, important information was often late or incomplete.','二つ目の関係では、大切な情報が遅れたり不完全だったりしました。'],
['Companies did not know when products would arrive, and plans changed without warning.','企業は製品がいつ届くか分からず、計画が予告なく変わりました。'],
['Our group discussed which relationship would be easier to continue for many years.','私たちの班はどちらの関係が何年も続けやすいか話し合いました。'],
['Everyone chose the first one, even though both relationships could move the same kinds of goods.','どちらも同じ種類の品物を動かせますが、全員が一つ目を選びました。'],
['The difference was not the product; it was the reliability of the relationship.','違いは製品ではなく、関係の信頼性でした。'],
['Repeated cooperation can create trust, while repeated surprises can weaken it.','協力を繰り返すことで信頼が生まれ、予想外のことが続くと弱まります。'],
['We concluded that trade depends on information and behavior as well as ships, roads, and products.','私たちは貿易は船、道路、製品だけでなく、情報や行動にも頼っていると結論づけました。'],
['A border can be crossed physically, but a long relationship also needs people to believe that agreements will be kept.','国境は物理的に越えられますが、長い関係には約束が守られると人々が信じることも必要です。']
],false,[['quality','品質'],['reliability','信頼性'],['cooperation','協力'],['agreement','約束・合意']])
];
if(all.length!==16)throw new Error('Batch03 G3 draft count '+all.length);
if(new Set(all.map(x=>x.id)).size!==16)throw new Error('Batch03 G3 duplicate IDs');
window.V11_BATCH03_DRAFT_G3_PASSAGES=all;
window.V11_BATCH03_DRAFT_G3_STATE={batch:BATCH,count:16,registered:false,currentRuntimeTotal:268,targetRuntimeTotalAfterFullBatch03:318,wordCounts:all.map(p=>({id:p.id,wordCount:p.wordCount,target:p.targetWordBand}))};
})();