const fs=require('fs');
const src=require('./v11_batch13_final_candidate.json');
if(src.registered!==false||src.officialTotal!==768||src.passages.length!==50) throw new Error('Batch13 final candidate contract mismatch');
const enSeg=new Intl.Segmenter('en',{granularity:'sentence'}), jpSeg=new Intl.Segmenter('ja',{granularity:'sentence'});
const split=(seg,s)=>[...seg.segment(s)].map(x=>x.segment.trim()).filter(Boolean);
const small={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};
const months={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
const jpSimple={'一':1,'二':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9,'十':10};
function wordNumber(w){w=w.toLowerCase();if(small[w]!==undefined)return small[w];const a=w.split('-');if(a.length===2&&small[a[0]]>=20&&small[a[0]]%10===0&&small[a[1]]>0&&small[a[1]]<10)return small[a[0]]+small[a[1]];return null}
function nums(s){const out=[];for(const m of s.matchAll(/\d+(?::\d+)?/g)){const x=m[0];if(x.includes(':'))out.push(...x.split(':').map(v=>String(Number(v))));else out.push(String(Number(x)));}for(const m of s.matchAll(/\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)(?:-(?:one|two|three|four|five|six|seven|eight|nine))?\b/gi)){const n=wordNumber(m[0]);if(n!==null)out.push(String(n));}for(const m of s.matchAll(/\b(january|february|march|april|may|june|july|august|september|october|november|december)\b/gi))out.push(String(months[m[1].toLowerCase()]));for(const m of s.matchAll(/[一二三四五六七八九十](?=つ|人|枚|回|度|か所|箇所|チーム|室|台|本|日|月|時|分|年|$)/g))out.push(String(jpSimple[m[0]]));return out.sort((a,b)=>Number(a)-Number(b)||a.localeCompare(b)).join('|')}
function coreLen(s){return Math.max(1,[...s.replace(/[\s\p{P}\p{S}]/gu,'')].length)}
function groupCost(ea,ja,ratio,ec,jc){const e=ea.join(' '),j=ja.join('');const lenCost=Math.abs(Math.log((coreLen(j)/coreLen(e))/ratio));const de=nums(e),dj=nums(j);const numCost=(de||dj)&&de!==dj?1.35:0;return lenCost+numCost+(ec+jc-2)*0.22}
function align(en,jp,id){const ratio=jp.reduce((a,s)=>a+coreLen(s),0)/en.reduce((a,s)=>a+coreLen(s),0),N=en.length,M=jp.length;if(N===M)return en.map((e,i)=>({en:e,jp:jp[i],alignmentShape:'1:1',alignmentCost:+groupCost([e],[jp[i]],ratio,1,1).toFixed(4),humanReview:'PENDING_CONFIRM'}));const INF=1e9,dp=Array.from({length:N+1},()=>Array(M+1).fill(INF)),prev=Array.from({length:N+1},()=>Array(M+1).fill(null)),steps=[[1,1],[1,2],[2,1]];dp[0][0]=0;for(let i=0;i<=N;i++)for(let j=0;j<=M;j++)if(dp[i][j]<INF)for(const [ec,jc] of steps){if(i+ec>N||j+jc>M)continue;const c=groupCost(en.slice(i,i+ec),jp.slice(j,j+jc),ratio,ec,jc),v=dp[i][j]+c;if(v<dp[i+ec][j+jc]){dp[i+ec][j+jc]=v;prev[i+ec][j+jc]={i,j,ec,jc,c}}}if(dp[N][M]>=INF)throw new Error(`${id} slash alignment impossible en=${N} jp=${M}`);const rev=[];let i=N,j=M;while(i||j){const p=prev[i][j];if(!p)throw new Error(`${id} traceback failed ${i}/${j}`);rev.push({en:en.slice(p.i,i).join(' '),jp:jp.slice(p.j,j).join(''),ec:p.ec,jc:p.jc,cost:+p.c.toFixed(4)});i=p.i;j=p.j;}const groups=rev.reverse(),avg=dp[N][M]/groups.length;if(avg>0.95)throw new Error(`${id} alignment confidence low avg=${avg.toFixed(3)}`);return groups.map(g=>({en:g.en,jp:g.jp,alignmentShape:`${g.ec}:${g.jc}`,alignmentCost:g.cost,humanReview:g.ec===1&&g.jc===1?'PENDING_CONFIRM':'PENDING_GROUP_BOUNDARY'}))}
const out=JSON.parse(JSON.stringify(src));let rows=0,groupedPassages=0,groupedRows=0;const packet=[];
for(const p of out.passages){if(p.humanSemanticReview!=='B13_HUMAN_REVIEW_COMPLETE_R3')throw new Error(`${p.id} semantic human review missing`);const qs=[...(p.questions||[]),...(p.questionSetB||[])];if(qs.length!==10)throw new Error(`${p.id} question count ${qs.length}`);for(const q of qs){if(!q.evidence||!p.body.includes(q.evidence))throw new Error(`${p.id} evidence not in body: ${q.prompt}`);if(!q.evidenceJp||!p.fullTranslation.includes(q.evidenceJp))throw new Error(`${p.id} evidenceJp not in translation: ${q.prompt}`);}const en=split(enSeg,p.body),jp=split(jpSeg,p.fullTranslation);if(en.length<6||jp.length<6)throw new Error(`${p.id} too few units ${en.length}/${jp.length}`);p.sentences=en;p.slashRows=align(en,jp,p.id);p.slashStage='B13_SLASH_SEQUENCE_ALIGNED_HUMAN_REVIEW_REQUIRED';const g=p.slashRows.filter(r=>r.humanReview==='PENDING_GROUP_BOUNDARY');rows+=p.slashRows.length;groupedRows+=g.length;if(g.length){groupedPassages++;packet.push({id:p.id,title:p.title,enUnits:en.length,jpUnits:jp.length,groupedRows:g});}}
out.status='BODY_TRANSLATION_QUESTIONS_FINAL_SLASH_ALIGNED_HUMAN_REVIEW_REQUIRED';out.slashRowsTotal=rows;out.slashGroupedBoundaryPassages=groupedPassages;out.slashGroupedRows=groupedRows;out.slashHumanReviewed=0;out.registered=false;fs.writeFileSync('v11_batch13_slash_candidate.json',JSON.stringify(out,null,2)+'\n');fs.writeFileSync('V11_BATCH13_GROUPED_SLASH_REVIEW_PACKET.json',JSON.stringify({batch:'V11-B13',registered:false,passageCount:groupedPassages,rowCount:groupedRows,passages:packet},null,2)+'\n');console.log(JSON.stringify({passages:50,slashRows:rows,groupedBoundaryPassages:groupedPassages,groupedRows,questions:500,registered:false},null,2));
