'use strict';
const fs=require('fs'),vm=require('vm');
function norm(w){return String(w||'').toLowerCase().replace(/[’‘]/g,"'").trim()}
function loadGloss(){const sandbox={window:{},console};vm.createContext(sandbox);for(const f of ['v11_batch10_prior_verified_gloss.js','v11_batch10_manual_gloss_r1.js','v11_batch11_manual_gloss_r1.js'])vm.runInContext(fs.readFileSync(f,'utf8'),sandbox,{filename:f});const manual=require('./v11_batch12_manual_gloss_r1.js');return {...(sandbox.window.V11_BATCH10_PRIOR_VERIFIED_GLOSS||{}),...(sandbox.window.V11_BATCH10_MANUAL_GLOSS||{}),...(sandbox.window.V11_BATCH11_MANUAL_GLOSS||{}),...manual};}
function candidates(w){const a=[w];if(/'s$/.test(w))a.push(w.slice(0,-2));if(/ies$/.test(w))a.push(w.slice(0,-3)+'y');if(/ves$/.test(w))a.push(w.slice(0,-3)+'f',w.slice(0,-3)+'fe');if(/ied$/.test(w))a.push(w.slice(0,-3)+'y');if(/es$/.test(w))a.push(w.slice(0,-2),w.slice(0,-1));if(/s$/.test(w)&&w.length>3)a.push(w.slice(0,-1));for(const suf of ['ing','ed','er','est'])if(w.endsWith(suf)&&w.length>suf.length+2){const b=w.slice(0,-suf.length);a.push(b,b+'e');if(b.endsWith('i'))a.push(b.slice(0,-1)+'y');if(b.length>2&&b.at(-1)===b.at(-2))a.push(b.slice(0,-1));}return [...new Set(a.map(norm))];}
function findGloss(gloss,w){for(const b of candidates(norm(w))){const jp=gloss[b];if(jp&&String(jp).trim()&&norm(jp)!==norm(w)&&!/placeholder|temporary|最終注整理対象|本文で使用/i.test(jp))return{base:b,jp:String(jp).trim()};}return null;}
function frozenNeeded(){const d=JSON.parse(fs.readFileSync('V11_BATCH12_CHRONOLOGY_DIAGNOSTIC.json','utf8'));const needed=new Map();for(const group of [d.vocab&&d.vocab.unregistered&&d.vocab.unregistered.top,d.vocab&&d.vocab.future&&d.vocab.future.top])for(const r of group||[]){for(const id of r.ids||[]){if(!needed.has(id))needed.set(id,new Set());needed.get(id).add(norm(r.word));}}return needed;}
module.exports=function applyVerifiedGloss(candidate){const gloss=loadGloss(),needed=frozenNeeded();let added=0,coveredDistinct=new Set(),uncoveredDistinct=new Set();for(const p of candidate.passages||[]){p.notes=Array.isArray(p.notes)?p.notes:[];const have=new Set(p.notes.map(n=>norm(n&&n.english)));for(const w of needed.get(p.id)||[]){if(have.has(w)){coveredDistinct.add(w);continue;}const g=findGloss(gloss,w);if(!g){uncoveredDistinct.add(w);continue;}const isB12=Object.prototype.hasOwnProperty.call(require('./v11_batch12_manual_gloss_r1.js'),g.base);p.notes.push({english:w,japanese:g.jp,kind:'unlearned_local_required',source:isB12?'Batch12 human-finalized Japanese gloss':(g.base===w?'prior human-verified Japanese gloss':'inflection of prior human-verified gloss '+g.base)});have.add(w);coveredDistinct.add(w);added++;}}
candidate.verifiedGlossReuse={inventorySource:'frozen initial Batch12 chronology diagnostic',notesAdded:added,coveredDistinct:coveredDistinct.size,uncoveredDistinct:uncoveredDistinct.size,uncoveredWords:[...uncoveredDistinct].sort(),registered:false};return candidate;};
