(function buildV11Batch04Grade2Draft(){
'use strict';
const BATCH='V11-B04-G2-DRAFT-20260828';
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while)\b/gi,'/ $1');}
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function build(id,textbook,section,baseline,title,rows,long,notes){const qs=rows.slice(0,10).map((r,i)=>({prompt:`${i+1}. 本文の第${i+1}文の内容に合う英文を本文から一文答えなさい。`,answer:r[0],evidence:r[0],evidenceJp:r[1],reason:`第${i+1}文が直接の根拠です。`}));return {id,textbook,grade:'2',section,level:'STEP',title,genre:'story',batch:BATCH,sourceSectionBaselineId:baseline,targetWordBand:long?[170,210]:[115,155],wordCount:wc(rows),sentences:rows.map(r=>r[0]),fullTranslation:rows.map(r=>r[1]).join(''),slashRows:rows.map(r=>({en:slash(r[0]),jp:r[1]})),questions:qs.slice(0,5),questionSetB:qs.slice(5,10),notes:(notes||[]).map(n=>({english:n[0],japanese:n[1],kind:'unlearned_local_required',source:'v11 Batch04 G2 story-specific required note seed'})),semanticRewrite:'BATCH04_G2_STORY_SPECIFIC_20260828',registered:false,auditNote:'Batch04 G2 non-runtime authoring draft. Story-specific passage; chronology, length, question diversity, notes, cross-batch, PC/iPhone and A4 gates still required.'};}
const SS='サンシャイン',NH='ニューホライズン',ssBase='V10-SS-G2-P8-3-001',nhBase='V10-NH-G2-U7-4-001';
const all=[
build('V11-SS-G2-P8-3-026',SS,'PROGRAM 8-3',ssBase,'Which Report Is Newer?',[
['Our group was finishing a class report on a shared computer.','私たちの班は共用コンピューターでクラスのレポートを仕上げていました。'],
['Two files had almost the same name, and both looked complete.','二つのファイルはほとんど同じ名前で、どちらも完成しているように見えました。'],
['One student wanted to send the first file because it appeared at the top of the folder.','一人の生徒はフォルダの上に表示された最初のファイルを送ろうとしました。'],
['Another student remembered changing one paragraph during lunch.','別の生徒は昼休みに一つの段落を直したことを思い出しました。'],
['We opened both files instead of guessing from their names.','私たちは名前だけで判断せず、両方のファイルを開きました。'],
['The first file did not include the new paragraph or the corrected title.','最初のファイルには新しい段落も直した題名も入っていませんでした。'],
['Then we checked the date and time shown beside each file.','それから各ファイルのそばに表示された日付と時刻を確認しました。'],
['The second file had been saved after our lunch meeting.','二つ目のファイルは昼の話し合いのあとに保存されていました。'],
['We renamed it “Final Report” and moved the older copy into another folder.','それを「Final Report」と名前を変え、古いほうは別のフォルダへ移しました。'],
['Before sending anything, one member read the last paragraph aloud.','送る前に、一人のメンバーが最後の段落を声に出して読みました。'],
['That final check showed that the correct changes were there.','その最後の確認で、正しい修正が入っていることが分かりました。'],
['Comparing the actual contents and saved time kept us from sending an older report.','実際の内容と保存時刻を比べたことで、古いレポートを送らずにすみました。']
],false,[['shared','共用の'],['folder','フォルダ'],['renamed','名前を変えた']]),
build('V11-SS-G2-P8-3-027',SS,'PROGRAM 8-3',ssBase,'One Ingredient Short',[
['Our cooking group planned to make a simple vegetable dish after school.','私たちの調理班は放課後に簡単な野菜料理を作る予定でした。'],
['We brought the vegetables, rice, and seasonings that were written on our list.','一覧に書かれた野菜、ご飯、調味料を持ってきました。'],
['When we checked the table, one important ingredient was missing.','机を確認すると、大切な材料が一つ足りませんでした。'],
['No one had time to go to a store before the room closed.','部屋が閉まる前に店へ行く時間はだれにもありませんでした。'],
['At first, one member suggested canceling the cooking activity.','最初、一人のメンバーは調理活動を中止しようと提案しました。'],
['Instead, we looked at the food we already had and discussed a smaller plan.','代わりに、すでにある食材を見て、もっと簡単な計画を話し合いました。'],
['The vegetables could be cooked with rice without the missing ingredient.','その足りない材料がなくても、野菜はご飯といっしょに調理できました。'],
['We changed the recipe and wrote the new steps on a piece of paper.','レシピを変え、新しい手順を紙に書きました。'],
['Each person took one job, so the work continued without confusion.','一人ずつ仕事を担当したので、混乱せず作業を続けられました。'],
['The finished dish was different from our first plan, but everyone could eat it together.','完成した料理は最初の計画と違いましたが、全員で食べられました。'],
['We also wrote the missing ingredient at the top of our next shopping list.','次の買い物一覧の一番上に、足りなかった材料も書きました。'],
['Changing the plan was more useful than giving up because one thing was missing.','一つ足りないからとあきらめるより、計画を変えるほうが役立ちました。']
],false,[['ingredient','材料・食材'],['recipe','レシピ'],['seasoning','調味料']]),
build('V11-SS-G2-P8-3-028',SS,'PROGRAM 8-3',ssBase,'The Absent Teammate',[
['Our team had a practice match on Wednesday afternoon.','私たちのチームは水曜日の午後に練習試合がありました。'],
['One teammate sent a message saying that he was sick and could not come.','一人の仲間が病気で来られないとメッセージを送りました。'],
['He usually played an important position, so everyone became worried.','彼はいつも大切な位置を担当していたので、みんな心配になりました。'],
['Canceling the match would also cause trouble for the other team.','試合を中止すると相手チームにも迷惑がかかります。'],
['Our captain asked us to list the jobs that still had to be covered.','主将は残っている役割を挙げるよう私たちに言いました。'],
['Two players could share part of the missing teammate’s work.','二人の選手が欠席した仲間の仕事の一部を分担できました。'],
['Another player moved to a different position for the first half.','別の選手は前半だけ違う位置へ移りました。'],
['We practiced the new arrangement for ten minutes before the match.','試合前に十分钟、新しい配置を練習しました。'],
['The first few plays felt unfamiliar, but our voices became clearer as we continued.','最初の数回は慣れませんでしたが、続けるうちに声かけがはっきりしました。'],
['We finished the whole match without asking one person to do everything.','一人に全部を任せることなく、試合全体を終えました。'],
['Afterward, we wrote down which changes had worked well.','そのあと、どの変更がうまくいったか書き留めました。'],
['Sharing the roles kept the practice useful even when one teammate was absent.','役割を分けることで、一人欠席しても練習を有意義にできました。']
],false,[['position','位置・ポジション'],['captain','主将'],['arrangement','配置']]),
build('V11-SS-G2-P8-3-029',SS,'PROGRAM 8-3',ssBase,'A Shorter Festival Poster',[
['Our class made a poster for a small festival activity.','私たちのクラスは文化祭の小さな活動のポスターを作りました。'],
['The first version had many sentences about why our activity was interesting.','最初の版には、その活動がおもしろい理由がたくさん書かれていました。'],
['It also had the room number and starting time in small letters near the bottom.','部屋番号と開始時刻は下のほうに小さな文字で書かれていました。'],
['We put the poster on a wall and asked another class to look at it for five seconds.','ポスターを壁に貼り、別のクラスに五秒間見てもらいました。'],
['Most students remembered the picture, but few could tell us the time.','多くの生徒は絵を覚えていましたが、時間を言える生徒はほとんどいませんでした。'],
['That result showed us that our main information was not clear enough.','その結果から、大切な情報が十分にはっきりしていないと分かりました。'],
['We shortened the long explanation to one sentence.','長い説明を一文に短くしました。'],
['Then we moved the time and room number to the center in larger writing.','そして時間と部屋番号を中央へ移し、より大きく書きました。'],
['We kept one small picture because it helped people notice the poster.','人がポスターに気づく助けになるので、小さな絵を一つ残しました。'],
['A second group looked at the new version for the same five seconds.','二つ目の班にも同じ五秒間、新しい版を見てもらいました。'],
['This time, almost everyone could say when and where the activity would happen.','今度はほとんど全員が、いつどこで活動があるか言えました。'],
['The shorter poster gave people the information they needed first.','短くしたポスターは、必要な情報を最初に伝えられました。']
],false,[['poster','ポスター'],['version','版'],['center','中央']]),
build('V11-SS-G2-P8-3-030',SS,'PROGRAM 8-3',ssBase,'Captions Instead of Audio',[
['Our class visited a museum that had an audio guide for several exhibits.','私たちのクラスは、いくつかの展示に音声ガイドがある博物館を訪れました。'],
['My group planned to use the guide for a short report.','私たちの班は短いレポートのためにそのガイドを使う予定でした。'],
['When we arrived at one room, the guide device for that exhibit was not working.','ある部屋に着くと、その展示のガイド機器が動いていませんでした。'],
['We could have skipped the exhibit, but it was important for our topic.','その展示を飛ばすこともできましたが、私たちのテーマには重要でした。'],
['A sign beside the display had several short captions and dates.','展示のそばの看板には短い説明文と日付がいくつかありました。'],
['We read the highlighted parts first and copied only the facts connected to our report.','まず強調された部分を読み、レポートに関係する事実だけを書き写しました。'],
['One student took a photo of the sign so we could check the words later.','一人の生徒があとで言葉を確認できるよう看板の写真を撮りました。'],
['Another student compared the dates with information from the previous room.','別の生徒は日付を前の部屋の情報と比べました。'],
['Our notes were shorter than an audio explanation, but they answered our main question.','私たちのメモは音声説明より短かったですが、主な疑問には答えられました。'],
['Back at school, we used the photo to make sure our copied facts were correct.','学校に戻ってから、写真を使って書き写した事実が正しいか確認しました。'],
['We also mentioned in the report that the audio guide had been unavailable.','レポートには音声ガイドが使えなかったことも書きました。'],
['Reading the captions carefully let us continue without pretending that we had heard the guide.','説明文を注意して読むことで、ガイドを聞いたふりをせずに学習を続けられました。']
],false,[['audio guide','音声ガイド'],['caption','説明文'],['highlighted','強調された']]),
build('V11-SS-G2-P8-3-031',SS,'PROGRAM 8-3',ssBase,'The Side Street by Bicycle',[
['My friend and I planned to ride our bicycles to a sports field.','友達と私は自転車で運動場へ行く予定でした。'],
['We usually used the same wide road because it was easy to remember.','覚えやすいので、いつも同じ広い道を使っていました。'],
['That afternoon, road work blocked one part of our usual route.','その午後、道路工事でいつもの道の一部が通れませんでした。'],
['A worker told us that bicycles could not pass through the closed area.','作業員は自転車は閉鎖区域を通れないと教えてくれました。'],
['We stopped in a safe place and opened a map on my phone.','安全な場所に止まり、私のスマートフォンで地図を開きました。'],
['One side street went around the work and joined the main road again.','一本の脇道が工事を回り、再び大通りにつながっていました。'],
['It was a little longer, but it had less traffic than another choice.','少し遠回りでしたが、別の道より交通量が少ない道でした。'],
['We chose that street and rode slowly because it was new to us.','初めての道なので、その脇道を選んでゆっくり走りました。'],
['At each turn, we checked the map before moving on.','曲がり角ごとに、進む前に地図を確認しました。'],
['Soon we reached the same main road beyond the construction area.','すぐに工事区域の先で同じ大通りに戻りました。'],
['We arrived at the field only a few minutes later than usual.','いつもより数分遅れただけで運動場に着きました。'],
['A mapped side street gave us a safe solution without trying to pass the road work.','地図で確認した脇道のおかげで、工事中の道を無理に通らず安全に解決できました。']
],false,[['road work','道路工事'],['route','道順'],['traffic','交通量']]),
build('V11-SS-G2-P8-3-032',SS,'PROGRAM 8-3',ssBase,'The Low Calculator Battery',[
['I borrowed a calculator from our classroom shelf for a math activity.','数学の活動のために教室の棚から電卓を借りました。'],
['At first, the numbers appeared normally on the screen.','最初は画面に数字が普通に表示されました。'],
['After several questions, the screen became faint and hard to read.','何問か解くと、画面が薄くなり読みにくくなりました。'],
['I pressed the buttons again, but the problem did not go away.','もう一度ボタンを押しましたが、問題は直りませんでした。'],
['My partner had another classroom calculator with a clear screen.','相手は画面がはっきりした別の教室用電卓を持っていました。'],
['We decided to share that one instead of trusting unclear numbers.','見えにくい数字を信じるのではなく、その一台を共有することにしました。'],
['Before returning the weak calculator, I wrote a short note for our teacher.','弱くなった電卓を返す前に、先生への短いメモを書きました。'],
['The note said that the screen had become faint during class.','メモには授業中に画面が薄くなったと書きました。'],
['I placed the note under the calculator on the shelf.','そのメモを棚の電卓の下に置きました。'],
['Our teacher checked it later and found that the battery was low.','先生があとで確認し、電池が少ないと分かりました。'],
['The next class received a working calculator instead of the weak one.','次の授業では弱い電卓ではなく、使える電卓が用意されました。'],
['Sharing one good tool and leaving a clear note prevented the same problem from surprising someone else.','使える道具を共有し、はっきりしたメモを残すことで、次の人が同じ問題に驚かずにすみました。']
],false,[['calculator','電卓'],['battery','電池'],['faint','薄い・見えにくい']]),
build('V11-SS-G2-P8-3-033',SS,'PROGRAM 8-3',ssBase,'Color-Coded Festival Shifts',[
['Our class needed volunteers for three jobs during the school festival.','文化祭で三つの仕事をするボランティアがクラスに必要でした。'],
['We first wrote every name and time in one long list.','最初、すべての名前と時間を一つの長い一覧に書きました。'],
['The list looked complete, but two students were assigned to two jobs at the same time.','一覧は完成しているように見えましたが、二人の生徒が同じ時間に二つの仕事を割り当てられていました。'],
['We noticed the problem while checking the first afternoon period.','午後の最初の時間帯を確認しているとき、その問題に気づきました。'],
['Instead of changing names one by one, we rebuilt the schedule in a clearer form.','名前を一つずつ直す代わりに、もっと分かりやすい形で予定を作り直しました。'],
['Each job received its own column, and each time received one row.','仕事ごとに列を一つ、時間ごとに行を一つ作りました。'],
['We also used three simple colors to make the jobs easy to see.','仕事を見分けやすくするため、三つの簡単な色も使いました。'],
['Then we checked each student’s name across the same row.','それから同じ行で各生徒の名前を確認しました。'],
['The two overlaps became obvious, and we moved one shift for each student.','二つの重なりがはっきりし、それぞれ一つの担当時間を移しました。'],
['We asked the students before making the final changes.','最終変更をする前に、その生徒たちにも確認しました。'],
['The new schedule was posted where every volunteer could read it.','新しい予定表を、全員が読める場所に掲示しました。'],
['A clearer table helped us see time conflicts that the long list had hidden.','分かりやすい表にしたことで、長い一覧では見えにくかった時間の重なりを見つけられました。']
],false,[['shift','担当時間'],['column','列'],['overlap','重なり']]),
build('V11-NH-G2-U7-4-028',NH,'Unit 7-4',nhBase,'The Platform Changed',[
['Our group was taking a train to a museum for a class activity.','私たちの班は授業の活動で博物館へ電車で向かっていました。'],
['We arrived at the station early and waited near our usual platform.','駅に早く着き、いつものホームの近くで待っていました。'],
['A few minutes later, an announcement said that our train would leave from a different platform.','数分後、私たちの電車は別のホームから出るという放送がありました。'],
['The station was noisy, and two group members did not hear the whole message.','駅はうるさく、班の二人は放送全体を聞き取れませんでした。'],
['We checked the notice board instead of repeating what we thought we had heard.','聞こえたと思う内容を繰り返すのではなく、案内板を確認しました。'],
['The train number and new platform were shown clearly there.','そこには電車番号と新しいホームがはっきり表示されていました。'],
['One member wrote one short group message with both pieces of information.','一人がその二つの情報を入れた短いグループメッセージを書きました。'],
['Everyone read the same message before we moved.','移動する前に全員が同じメッセージを読みました。'],
['We walked together to the new platform and checked the train number again.','いっしょに新しいホームへ行き、電車番号をもう一度確認しました。'],
['The train arrived on time, and nobody was left at the old place.','電車は時間どおり到着し、だれも古い場所に残りませんでした。'],
['The board gave us a shared fact when the announcement had been difficult to hear.','放送が聞き取りにくいとき、案内板が全員で共有できる確かな情報になりました。'],
['Sending one clear message also kept different guesses from spreading through the group.','一つの明確なメッセージを送ることで、違う推測が班に広がるのも防げました。']
],false,[['platform','ホーム'],['announcement','放送'],['notice board','案内板']]),
build('V11-NH-G2-U7-4-029',NH,'Unit 7-4',nhBase,'Rain Changes the Observation',[
['Our science group planned to measure shadows outside during the afternoon.','理科の班で午後に外で影を測る予定でした。'],
['We had prepared a stick, paper, and a simple table for our results.','棒、紙、結果を書く簡単な表を準備していました。'],
['Just before the activity, dark clouds covered the sky and rain began.','活動の直前、暗い雲が空をおおい、雨が降り始めました。'],
['Without strong sunlight, our original shadow experiment would not work.','強い日光がなければ、元の影の実験はできません。'],
['Our teacher asked us to think about what we could still observe from inside.','先生は室内からでも何を観察できるか考えるよう言いました。'],
['We moved to a window and watched how raindrops collected on different parts of the glass.','窓へ移動し、雨粒がガラスの場所によってどう集まるか観察しました。'],
['We marked three small areas and counted visible drops after the same amount of time.','三つの小さな場所を決め、同じ時間のあとに見える雨粒を数えました。'],
['Each group member recorded one area so that our counting would be organized.','数え方を整理するため、一人ずつ一つの場所を記録しました。'],
['The activity was not the experiment we had planned that morning.','その活動は朝に計画した実験とは違いました。'],
['However, we still practiced measuring, recording, and comparing observations.','しかし、測ること、記録すること、観察結果を比べることは練習できました。'],
['We saved the shadow plan for a sunny day instead of pretending that the rainy data answered the same question.','雨の日のデータが同じ疑問に答えるふりをせず、影の計画は晴れの日のために残しました。'],
['Changing the question honestly made the rainy afternoon useful.','疑問を正直に変えることで、雨の午後も有意義になりました。']
],false,[['observation','観察'],['raindrop','雨粒'],['recording','記録すること']]),
build('V11-NH-G2-U7-4-030',NH,'Unit 7-4',nhBase,'The Missing Attachment',[
['I wrote an email to my teacher after finishing a group document at home.','家で班の文書を仕上げたあと、先生へメールを書きました。'],
['The message said, “Please see our report in the attached file.”','メッセージには「添付したファイルのレポートをご覧ください」と書きました。'],
['I checked the subject and the teacher’s address, and both looked correct.','件名と先生のアドレスを確認し、どちらも正しく見えました。'],
['My finger was almost on the send button when I read the message one more time.','もう送信ボタンを押すところで、メッセージをもう一度読みました。'],
['The word “attached” made me look below the message box.','「添付した」という言葉を見て、メッセージ欄の下を確認しました。'],
['There was no file name there because I had forgotten to add the report.','レポートを付け忘れていたので、そこにファイル名はありませんでした。'],
['I attached the correct file and opened it once to make sure it was the final version.','正しいファイルを添付し、それが最終版か確認するため一度開きました。'],
['After sending the email, I made a three-part checklist for future messages.','メールを送ったあと、今後のために三項目のチェックリストを作りました。'],
['It said “address, message, file.”','そこには「宛先、本文、ファイル」と書きました。'],
['I placed the list beside my computer screen.','その一覧をコンピューター画面のそばに置きました。'],
['The next time I sent a document, the short list reminded me to check the file before sending.','次に文書を送るとき、その短い一覧が送信前のファイル確認を思い出させてくれました。'],
['A ten-second check prevented an email that would have asked my teacher to read a file that was not there.','十秒の確認で、存在しないファイルを読んでくださいと頼むメールを送らずにすみました。']
],false,[['attachment','添付ファイル'],['attached','添付された'],['checklist','チェックリスト']]),
build('V11-NH-G2-U7-4-031',NH,'Unit 7-4',nhBase,'A Better Survey Question',[
['Our class made a survey about a possible new reading space at school.','私たちのクラスは学校の新しい読書スペースについてアンケートを作りました。'],
['Our first question was, “Don’t you think a quiet reading room would be useful?”','最初の質問は「静かな読書室は役立つと思いませんか」でした。'],
['Most of us liked the idea, so the question sounded natural at first.','私たちの多くがその案を気に入っていたので、最初は自然な質問に思えました。'],
['Then our teacher asked whether someone could easily answer “no” after reading those words.','先生は、その言い方を読んだあと簡単に「いいえ」と答えられるかたずねました。'],
['We noticed that the question seemed to push people toward one answer.','その質問は一つの答えへ人を押しているようだと気づきました。'],
['We rewrote it as, “How useful would a quiet reading space be for you?”','「静かな読書スペースはあなたにとってどのくらい役立ちますか」と書き直しました。'],
['We added several answer choices from “very useful” to “not useful.”','「とても役立つ」から「役立たない」までいくつかの選択肢を加えました。'],
['We also added a space for a short reason.','短い理由を書く欄も加えました。'],
['When the class answered the new survey, the results included positive and negative opinions.','クラスが新しいアンケートに答えると、結果には賛成と反対の意見の両方が入りました。'],
['Those different answers gave us more useful information for our report.','その異なる答えが、レポートにより役立つ情報を与えてくれました。'],
['We learned that a survey should collect opinions instead of telling people which opinion to choose.','アンケートはどの意見を選ぶべきか伝えるのではなく、意見を集めるものだと学びました。'],
['Changing a few words made the question fairer and the results more meaningful.','いくつかの言葉を変えることで、質問はより公平になり、結果も意味のあるものになりました。']
],false,[['survey','アンケート'],['opinion','意見'],['meaningful','意味のある']]),
build('V11-NH-G2-U7-4-032',NH,'Unit 7-4',nhBase,'Check the Library Sign',[
['I went to the public library on Saturday to finish a school project.','土曜日、学校の課題を終えるため公共図書館へ行きました。'],
['A quiet desk near a window was empty, and I wanted to use it.','窓の近くの静かな机が空いていて、私は使いたいと思いました。'],
['There was a small sign on the desk, but I could not read it from the aisle.','机には小さな表示がありましたが、通路からは読めませんでした。'],
['I almost sat down and put my bag on the chair.','私は座って、かばんをいすに置きそうになりました。'],
['Then I walked closer and read the sign first.','そのとき、近づいて先に表示を読みました。'],
['It said that the desk was reserved for a study group starting in fifteen minutes.','その机は十五分後に始まる学習グループのために予約されていると書かれていました。'],
['Another table nearby had no reserved sign.','近くの別の机には予約の表示がありませんでした。'],
['I moved there and began my project without needing to move again later.','私はそこへ移り、あとでまた移動する必要なく課題を始めました。'],
['A group arrived at the first desk soon afterward.','そのあとすぐ、最初の机にグループが来ました。'],
['They could use their reserved place without asking anyone to leave.','彼らはだれかに移動を頼むことなく、予約した場所を使えました。'],
['Reading a small sign took only a few seconds.','小さな表示を読むのに数秒しかかかりませんでした。'],
['Those few seconds helped both me and the group use the library smoothly.','その数秒のおかげで、私もそのグループも図書館をスムーズに使えました。']
],false,[['reserved','予約された'],['aisle','通路']]),
build('V11-NH-G2-U7-4-033',NH,'Unit 7-4',nhBase,'Stop Before Explaining',[
['Our class prepared a short walking tour for visitors to the school.','私たちのクラスは来校者のために短い校内ツアーを準備しました。'],
['During practice, each guide talked while the group was moving through the hall.','練習では、案内役が廊下を歩きながら説明していました。'],
['The hall was busy, and footsteps made some words difficult to hear.','廊下はにぎやかで、足音のために言葉が聞き取りにくくなりました。'],
['People at the back also had to watch where they were walking.','後ろの人たちは歩く場所にも注意しなければなりませんでした。'],
['One visitor in our practice group missed the explanation about the science room.','練習に参加した一人が理科室についての説明を聞き逃しました。'],
['We changed the tour rule before the real event.','本番前にツアーのルールを変えました。'],
['At each important point, the guide would stop the group before speaking.','大切な場所では、案内役が話す前にグループを止めることにしました。'],
['The guide would face everyone and give only the key information.','案内役は全員のほうを向き、大切な情報だけを伝えます。'],
['After the explanation, the group could begin walking again.','説明のあと、グループは再び歩き始めます。'],
['We practiced the new method, and even students at the back could answer questions.','新しい方法で練習すると、後ろの生徒も質問に答えられました。'],
['The tour took only a little longer than before.','ツアーは以前より少し長くなっただけでした。'],
['Stopping for information made the walk safer and the explanation easier to understand.','情報を伝えるときに止まることで、歩行は安全になり、説明も分かりやすくなりました。']
],false,[['guide','案内役'],['footstep','足音'],['key information','重要な情報']]),
build('V11-NH-G2-U7-4-034',NH,'Unit 7-4',nhBase,'The Lost Locker Key',[
['I could not find my locker key after club practice.','部活動の練習後、私はロッカーの鍵を見つけられませんでした。'],
['I checked my pockets, sports bag, and the bench where I had changed shoes.','ポケット、スポーツバッグ、靴を履き替えたベンチを確認しました。'],
['The key was not in any of those places.','どこにも鍵はありませんでした。'],
['At first, I wanted to search every room I had visited that afternoon.','最初、その午後に行ったすべての部屋を探そうと思いました。'],
['My friend reminded me that the school had a procedure for lost keys.','友達が、学校には鍵をなくしたときの手順があると教えてくれました。'],
['We went to the office and told a staff member my name and locker number.','私たちは事務室へ行き、職員に私の名前とロッカー番号を伝えました。'],
['The staff member checked the lost-item box before doing anything else.','職員はまず落とし物の箱を確認しました。'],
['Someone had already brought in a key found near the gym door.','だれかが体育館のドアの近くで見つけた鍵をすでに届けていました。'],
['I described the small tag on my key, and the description matched.','私は鍵についた小さな札を説明し、その特徴が一致しました。'],
['The staff member returned it after checking my information.','職員は私の情報を確認してから鍵を返しました。'],
['I saved time because I followed the school procedure instead of searching alone for an hour.','一時間一人で探す代わりに学校の手順に従ったので、時間を節約できました。'],
['I also put the key in a safer inside pocket before going home.','帰宅前に、鍵をもっと安全な内ポケットへ入れました。']
],false,[['locker','ロッカー'],['procedure','手順'],['staff member','職員']]),
build('V11-NH-G2-U7-4-035',NH,'Unit 7-4',nhBase,'The Wet Sports Bag',[
['It rained while our team was returning from an outdoor sports practice.','屋外のスポーツ練習から帰る途中、雨が降りました。'],
['My sports bag became wet before I reached the school building.','校舎へ着く前に、スポーツバッグがぬれてしまいました。'],
['Inside the bag were wet clothes, a towel, and several paper notes from our coach.','バッグの中にはぬれた服、タオル、コーチからの紙のメモが数枚ありました。'],
['I first thought I could leave everything inside until I got home.','最初は家に帰るまで全部そのままにしておこうと思いました。'],
['Then I saw water on one corner of the top note.','そのとき、一番上のメモの角に水がついているのを見つけました。'],
['I took the papers out and put them in a dry folder from my school bag.','紙を取り出し、通学かばんの乾いたフォルダに入れました。'],
['The wet clothes went into a separate plastic bag.','ぬれた服は別のビニール袋に入れました。'],
['I left the sports bag open for a few minutes so air could reach the inside.','中に空気が入るよう、スポーツバッグを数分開けておきました。'],
['When I got home, the notes were still easy to read.','家に着いたとき、メモはまだ読みやすい状態でした。'],
['I dried the bag and clothes before putting anything back inside.','何かを戻す前に、バッグと服を乾かしました。'],
['Separating wet things from paper took little time but protected information I still needed.','ぬれた物と紙を分けるのは短時間でしたが、まだ必要な情報を守れました。'],
['The next rainy day, I carried an extra plastic bag from the start.','次の雨の日には、最初から予備のビニール袋を持って行きました。']
],false,[['separate','別の'],['plastic','ビニール・プラスチック'],['protected','守った']]),
build('V11-NH-G2-U7-4-036',NH,'Unit 7-4',nhBase,'Two Backup Examples',[
['I was going to meet an exchange student during a school event.','学校行事で交流生に会う予定でした。'],
['Our teacher asked me to explain one part of our school life in simple English.','先生は学校生活の一部を簡単な英語で説明するよう私に頼みました。'],
['I chose our cleaning time because it happens every day.','毎日行うので、掃除の時間を選びました。'],
['My first plan used one example about cleaning the classroom floor.','最初の計画では、教室の床掃除の例を一つ使いました。'],
['Then I imagined that the student might not understand one of my words.','そのとき、交流生が私の言葉の一つを理解できない場合を考えました。'],
['I prepared two backup examples with easier actions: moving chairs and cleaning the board.','私は「いすを動かす」「黒板をきれいにする」という、より簡単な二つの予備例を用意しました。'],
['I also drew three tiny pictures beside the examples.','例のそばに小さな絵も三つ描きました。'],
['During the meeting, the student understood the first sentence but looked unsure about the next one.','交流中、最初の文は伝わりましたが、次の文では相手が少し困った様子でした。'],
['I used the chair example and pointed to my picture.','私はいすの例を使い、絵を指しました。'],
['The student smiled and said that students did something similar at home.','その生徒は笑顔になり、家でも似たことをすると言いました。'],
['We continued talking without stopping to search for a perfect explanation.','完璧な説明を探すために止まることなく、会話を続けられました。'],
['Two simple backup examples gave me another path when my first words were not enough.','二つの簡単な予備例が、最初の言葉だけでは足りないときの別の伝え方になりました。']
],false,[['exchange student','交流生'],['backup','予備の']])
];
if(all.length!==17)throw new Error('Batch04 G2 count '+all.length);
window.V11_BATCH04_G2_PASSAGES=all;
window.V11_BATCH04_G2_STATE={version:'20260828-g2-authoring',count:all.length,registered:false};
})();