(function buildV11Batch04Grade3Draft(){
'use strict';
const BATCH='V11-B04-G3-DRAFT-20260828';
function slash(en){return en.replace(/, /g,', / ').replace(/\b(and|but|because|so|before|after|until|then|when|while|although)\b/gi,'/ $1');}
function wc(rows){return (rows.map(r=>r[0]).join(' ').match(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)||[]).length;}
function build(id,textbook,section,baseline,title,rows,long,notes){const qs=rows.slice(0,10).map((r,i)=>({prompt:`${i+1}. 本文の第${i+1}文の内容に合う英文を本文から一文答えなさい。`,answer:r[0],evidence:r[0],evidenceJp:r[1],reason:`第${i+1}文が直接の根拠です。`}));return {id,textbook,grade:'3',section,level:'JUMP',title,genre:'story',batch:BATCH,sourceSectionBaselineId:baseline,targetWordBand:long?[210,270]:[140,185],wordCount:wc(rows),sentences:rows.map(r=>r[0]),fullTranslation:rows.map(r=>r[1]).join(''),slashRows:rows.map(r=>({en:slash(r[0]),jp:r[1]})),questions:qs.slice(0,5),questionSetB:qs.slice(5,10),notes:(notes||[]).map(n=>({english:n[0],japanese:n[1],kind:'unlearned_local_required',source:'v11 Batch04 G3 story-specific required note seed'})),semanticRewrite:'BATCH04_G3_STORY_SPECIFIC_20260828',registered:false,auditNote:'Batch04 G3 non-runtime authoring draft. Story-specific passage; chronology, length, question diversity, notes, cross-batch, PC/iPhone and A4 gates still required.'};}
const SS='サンシャイン',NH='ニューホライズン',ssBase='V10-SS-G3-P7-3-001',nhBase='V10-NH-G3-U6-4-001';
const all=[
build('V11-SS-G3-P7-3-027',SS,'PROGRAM 7-3',ssBase,'Check the Update Date',[
['Our debate team was preparing an argument about how students travel to school.','私たちのディベート班は、生徒の通学方法についての主張を準備していました。'],
['One member found a useful-looking web page with numbers about bicycle use in our area.','一人が地域の自転車利用について数字が載った、役立ちそうなウェブページを見つけました。'],
['The numbers supported our idea, so we almost copied them directly into our notes.','その数字は私たちの考えを支えていたので、そのままメモへ写しそうになりました。'],
['Then another student noticed a small date at the bottom of the page.','すると別の生徒がページ下部の小さな日付に気づきました。'],
['The information had been published several years earlier.','その情報は数年前に公開されたものでした。'],
['We did not know whether bicycle use had changed since then.','それ以降、自転車利用が変わったかどうか分かりませんでした。'],
['Instead of throwing the old page away, we used its title to search for a newer report.','古いページを捨てるのではなく、その題名を使って新しい報告を探しました。'],
['A local office had published updated numbers the previous year.','地域の機関が前年に更新された数字を公開していました。'],
['The newer report showed a similar pattern but different totals.','新しい報告は似た傾向を示していましたが、合計数は違っていました。'],
['We replaced the old figures in our debate notes and recorded the new source date.','ディベート用のメモの古い数字を置き換え、新しい資料の日付も記録しました。'],
['We kept the older page only as background information.','古いページは背景情報としてだけ残しました。'],
['During practice, our teacher asked where our numbers had come from.','練習中、先生はその数字がどこから来たのかたずねました。'],
['Because we had checked the update date, we could explain the source clearly.','更新日を確認していたので、資料の出所をはっきり説明できました。'],
['The experience taught us that information can look convincing even when its date makes it less useful.','情報は説得力があるように見えても、日付によって役立ち方が変わると学びました。']
],false,[['debate','ディベート'],['published','公開された'],['updated','更新された'],['convincing','説得力のある']]),
build('V11-SS-G3-P7-3-028',SS,'PROGRAM 7-3',ssBase,'One Volunteer Role Table',[
['Our school was preparing a community event that needed many student volunteers.','学校では多くの生徒ボランティアが必要な地域行事を準備していました。'],
['Students signed up on several sheets that had been placed in different classrooms.','生徒たちは別々の教室に置かれた何枚かの用紙に申し込みました。'],
['When the event team collected the sheets, some names appeared twice and several roles were unclear.','行事班が用紙を集めると、名前が二度出ていたり、役割が不明だったりしました。'],
['One student had written only “morning,” while another had written a job but no time.','ある生徒は「午前」だけを書き、別の生徒は仕事だけで時間を書いていませんでした。'],
['Calling every volunteer separately would take too long.','全員に別々に連絡すると時間がかかりすぎます。'],
['We created one table with three clear columns: name, role, and time.','私たちは「名前・役割・時間」の三つのはっきりした列を持つ表を一つ作りました。'],
['We copied only confirmed information into the table and marked missing parts with a question mark.','確認済みの情報だけを表に写し、不足部分には疑問符をつけました。'],
['Then we contacted only the students whose rows still had a question mark.','それから、まだ疑問符がある生徒だけに連絡しました。'],
['After each reply, one team member updated the same master table.','返事が来るたびに、一人の班員が同じ基準表を更新しました。'],
['No new lists were created, so everyone looked at the same information.','新しい一覧は作らなかったので、全員が同じ情報を見ました。'],
['On the event day, volunteers checked the table when they arrived.','行事当日、ボランティアは到着するとその表を確認しました。'],
['The sign-in line moved quickly because each person could see a role and starting time.','一人ずつ役割と開始時間を確認できたので、受付の列はスムーズに進みました。'],
['The table did not reduce the number of volunteers, but it reduced confusion about who should do what.','その表でボランティアの人数は減りませんが、だれが何をするかの混乱は減りました。'],
['One shared source of information turned several messy sheets into a usable plan.','一つの共有情報源によって、何枚もの分かりにくい用紙が使える計画になりました。']
],false,[['volunteer','ボランティア'],['column','列'],['master table','基準となる表'],['sign-in','受付・記名']]),
build('V11-SS-G3-P7-3-029',SS,'PROGRAM 7-3',ssBase,'Cut the Optional Stop',[
['Our group planned a one-day trip for an English project about local tourism.','私たちの班は地域観光についての英語課題で日帰り旅行を計画しました。'],
['We wanted to visit a museum, a garden, a market, and a small viewing point.','博物館、庭園、市場、小さな展望場所を訪れたいと思っていました。'],
['After adding transportation, tickets, and lunch, our total cost was higher than the class limit.','交通費、入場料、昼食を足すと、合計費用はクラスの上限を超えました。'],
['At first, everyone suggested choosing cheaper food because lunch seemed easiest to change.','最初、昼食がもっとも変えやすそうなので、みんな安い食事を選ぼうとしました。'],
['However, even the cheapest lunch would not reduce the total enough.','しかし、最も安い昼食にしても合計は十分下がりませんでした。'],
['We listed the purpose, cost, and time needed for each stop.','私たちは各訪問場所の目的、費用、必要時間を一覧にしました。'],
['The museum and market were directly connected to our project questions.','博物館と市場は課題の質問に直接関係していました。'],
['The garden was free and near the museum, so keeping it added little cost.','庭園は無料で博物館の近くだったので、残してもほとんど費用は増えませんでした。'],
['The viewing point required a separate bus ride and was mainly for photographs.','展望場所は別のバス移動が必要で、主な目的は写真でした。'],
['We decided that it was the most optional part of the trip.','私たちはそこが旅行で最も省略できる部分だと判断しました。'],
['After removing that stop, the plan fit both our budget and our project goals.','その場所を外すと、計画は予算と課題の目的の両方に合いました。'],
['We still left a little extra money for unexpected transportation changes.','予想外の交通変更のために少し余分なお金も残しました。'],
['Our final schedule had fewer places, but every stop had a clear reason.','最終予定は場所が減りましたが、どの訪問にも明確な理由がありました。'],
['Comparing value instead of cutting the first easy thing produced a stronger travel plan.','最初に変えやすいものを削るのではなく価値を比べたことで、よりよい旅行計画になりました。']
],false,[['optional','省略可能な'],['budget','予算'],['viewing point','展望場所']]),
build('V11-SS-G3-P7-3-030',SS,'PROGRAM 7-3',ssBase,'Rename the Graph Axes',[
['I made a graph for a presentation about how long students read each week.','私は生徒が一週間にどのくらい読書するかについて、発表用のグラフを作りました。'],
['The horizontal axis showed five student groups, and the vertical axis showed time.','横軸には五つの生徒グループ、縦軸には時間を示しました。'],
['I labeled the vertical axis only with the word “Reading.”','私は縦軸に「Reading」とだけ書きました。'],
['During practice, my partner asked whether the numbers meant minutes per day or hours per week.','練習中、相手が数字は一日あたりの分数なのか一週間あたりの時間なのかたずねました。'],
['I knew the answer because I had collected the data, but the graph itself did not show it.','私はデータを集めたので答えを知っていましたが、グラフ自体には示されていませんでした。'],
['That meant an audience could easily understand the scale incorrectly.','つまり、聞き手が目盛りを間違って理解する可能性がありました。'],
['I changed the label to “Reading Time per Week (minutes).”','私はラベルを「一週間の読書時間（分）」に変えました。'],
['I also changed the other axis from “Group” to “Student Group A-E.”','もう一方の軸も「Group」から「Student Group A-E」に変えました。'],
['Then we looked at the graph without reading my speaking notes.','それから発表原稿を読まずにグラフを見ました。'],
['My partner could now explain what every number represented.','相手は今度は各数字が何を表すか説明できました。'],
['I kept the data and bar heights exactly the same.','データと棒の高さはまったく変えませんでした。'],
['Only the labels changed, but the meaning became much clearer.','ラベルだけを変えましたが、意味はずっと明確になりました。'],
['During the real presentation, nobody needed to ask what the unit was.','本番では、単位が何かをたずねる必要がある人はいませんでした。'],
['A graph should not require its maker to stand beside it and explain a missing label.','グラフは、作った人が横に立って不足したラベルを説明しなければ分からないものであってはいけないと学びました。']
],false,[['axis','軸'],['vertical','縦の'],['horizontal','横の'],['scale','目盛り・尺度']]),
build('V11-SS-G3-P7-3-031',SS,'PROGRAM 7-3',ssBase,'Ask Why and How',[
['For a class project, I interviewed a student who had helped at a local event.','授業の課題で、地域行事を手伝った生徒にインタビューしました。'],
['My first question was, “Was the experience good?”','最初の質問は「その経験はよかったですか」でした。'],
['The student answered, “Yes, it was good,” and then became quiet.','その生徒は「はい、よかったです」と答え、そのあと黙りました。'],
['My second question asked whether the event was busy, and the answer was simply “yes” again.','二つ目は行事が忙しかったかをたずね、答えはまた「はい」だけでした。'],
['I realized that my questions were producing very broad answers with little detail.','私の質問では、詳しさのない大まかな答えしか得られていないと気づきました。'],
['Before the next interview, I added two kinds of follow-up questions: “Why?” and “How?”','次のインタビューの前に、「なぜ」と「どのように」という二種類の追加質問を加えました。'],
['I asked why one job had been difficult and how the student had solved the problem.','一つの仕事がなぜ難しかったのか、そしてどう解決したのかをたずねました。'],
['The student explained that many visitors arrived at once and the signs were hard to see.','多くの来場者が一度に来て、看板が見えにくかったと説明してくれました。'],
['Then she described moving one sign closer to the entrance and asking another volunteer for help.','そして、一つの看板を入口近くへ移し、別のボランティアに助けを求めたと話しました。'],
['That answer gave me an actual problem, action, and result to write about.','その答えで、実際の問題、行動、結果を書くことができました。'],
['I did not ask “why” after every sentence because that would sound unnatural.','不自然になるので、すべての文のあとに「なぜ」とは聞きませんでした。'],
['Instead, I used a follow-up only when an important point needed more detail.','代わりに、大切な点に詳しさが必要なときだけ追加質問を使いました。'],
['My final interview notes were longer, but they were also more specific and useful.','最終的なインタビューメモは長くなりましたが、より具体的で役立つものになりました。'],
['A good follow-up question helped the speaker move from a general opinion to a real example.','よい追加質問は、話し手が一般的な意見から実際の例へ進む助けになりました。']
],false,[['interview','インタビュー'],['follow-up','追加の質問'],['specific','具体的な']]),
build('V11-SS-G3-P7-3-032',SS,'PROGRAM 7-3',ssBase,'Confirm the Deadline',[
['Our school posted a notice about applications for a student event.','学校が生徒行事の申し込みについてお知らせを出しました。'],
['The notice said that forms should be submitted “by next Friday.”','お知らせには用紙を「次の金曜日までに」提出すると書かれていました。'],
['Some students read the notice on Friday morning, while others first saw it after school.','金曜日の朝に読んだ生徒もいれば、放課後に初めて見た生徒もいました。'],
['Soon two different dates were being discussed as the deadline.','すぐに二つの違う日付が締切として話されるようになりました。'],
['One group thought “next Friday” meant seven days later.','ある班は「次の金曜日」が七日後を意味すると考えました。'],
['Another group believed it meant the Friday of the following week.','別の班はその次の週の金曜日だと思いました。'],
['Instead of choosing the interpretation we preferred, we went to the school office.','自分たちに都合のよい解釈を選ぶのではなく、学校の事務室へ行きました。'],
['A staff member checked the event calendar and gave us the exact date.','職員が行事カレンダーを確認し、正確な日付を教えてくれました。'],
['We asked whether the form had to arrive before school ended that day.','その日の学校終了前までに用紙が届く必要があるかも確認しました。'],
['The staff member confirmed both the date and the time.','職員は日付と時刻の両方を確認してくれました。'],
['Our class leader wrote the exact information on the board and included the month and day.','学級の係は月日を含む正確な情報を黒板に書きました。'],
['That stopped different versions of the deadline from continuing to spread.','それによって違う締切情報が広がり続けるのを止められました。'],
['Later, the school replaced the unclear words on the online notice with the exact date.','その後、学校はオンラインのお知らせの曖昧な言葉を正確な日付へ変えました。'],
['When a deadline matters, confirming one exact date is safer than arguing about an unclear phrase.','締切が重要なときは、曖昧な表現について議論するより、一つの正確な日付を確認するほうが確実です。']
],false,[['deadline','締切'],['submitted','提出された'],['interpretation','解釈']]),
build('V11-SS-G3-P7-3-033',SS,'PROGRAM 7-3',ssBase,'Popular Is Not Enough',[
['Our class was choosing an online tool for a group presentation.','私たちのクラスは班の発表に使うオンラインツールを選んでいました。'],
['One student immediately recommended the most popular tool because many people used it.','一人の生徒は多くの人が使っているという理由で、最も人気のあるツールをすぐ勧めました。'],
['The tool had many features and attractive examples on its website.','そのツールには多くの機能があり、ウェブサイトには魅力的な例がありました。'],
['However, our project required only simple slides, shared editing, and easy use on school computers.','しかし、私たちの課題に必要なのは簡単なスライド、共同編集、学校のコンピューターでの使いやすさだけでした。'],
['We wrote those three needs before comparing any products.','私たちは製品を比べる前に、その三つの必要条件を書きました。'],
['The popular tool worked well, but one important feature required a paid account.','人気のツールはよく動きましたが、一つの大切な機能には有料アカウントが必要でした。'],
['A less famous tool offered the three functions we needed without that problem.','あまり有名でないツールは、その問題なく必要な三つの機能を使えました。'],
['We tested both tools with the same short practice slide.','同じ短い練習スライドで両方のツールを試しました。'],
['The second tool opened faster on the older school computer.','二つ目のツールのほうが古い学校のコンピューターで早く開きました。'],
['It also allowed every group member to edit the file.','また、班の全員がファイルを編集できました。'],
['We chose it even though it was not the most popular option.','最も人気のある選択肢ではありませんでしたが、私たちはそれを選びました。'],
['Our decision was based on the needs of our project rather than the number of users online.','私たちの判断は、オンラインの利用者数ではなく課題の必要条件に基づいていました。'],
['During the presentation week, every group could open and change its slides without buying anything.','発表週間には、どの班も何かを購入せずにスライドを開き変更できました。'],
['Popularity can be useful information, but it cannot replace checking what a situation actually requires.','人気は役立つ情報ですが、実際の状況に何が必要かを確認する代わりにはなりません。']
],false,[['feature','機能'],['paid account','有料アカウント'],['requires','必要とする']]),
build('V11-SS-G3-P7-3-034',SS,'PROGRAM 7-3',ssBase,'Stairs and Elevator on the Map',[
['Our group created a simple map for visitors to a community center.','私たちの班は地域センターの来訪者向けに簡単な地図を作りました。'],
['The first version showed the entrance, meeting rooms, restrooms, and a large staircase.','最初の版には入口、会議室、トイレ、大きな階段を示しました。'],
['We thought the map was complete because every room was in the correct place.','すべての部屋が正しい位置にあるので、地図は完成したと思いました。'],
['Then a volunteer asked how someone using a wheelchair could reach the second floor.','するとボランティアが、車いすを使う人はどう二階へ行くのかたずねました。'],
['Our map showed only the shortest route, and that route used stairs.','私たちの地図は最短経路しか示しておらず、その道は階段を使っていました。'],
['We returned to the building and checked the other side of the hall.','私たちは建物へ戻り、廊下の反対側を確認しました。'],
['There was an elevator near a smaller entrance that we had not marked.','印をつけていなかった小さな入口の近くにエレベーターがありました。'],
['We measured the walking route from the main entrance to that elevator.','正面入口からそのエレベーターまでの歩行経路を確認しました。'],
['Then we added an elevator symbol and a second route to the map.','それからエレベーターの記号と二つ目の経路を地図へ加えました。'],
['We also marked where the route became narrow so visitors could plan before arriving.','来訪者が到着前に計画できるよう、道が狭くなる場所も示しました。'],
['A staff member checked our new version for accuracy.','職員が新しい版の正確さを確認しました。'],
['The final map was slightly busier, but it gave useful choices to more people.','最終地図は少し情報が増えましたが、より多くの人に役立つ選択肢を示しました。'],
['We learned that a map can be geographically correct and still leave out important access information.','地図は地理的に正しくても、大切な利用情報が抜けることがあると学びました。'],
['Adding one elevator changed the map from a picture of the building into a better guide for its visitors.','エレベーターを一つ加えることで、地図は建物の絵から来訪者にとってよりよい案内へ変わりました。']
],false,[['wheelchair','車いす'],['elevator','エレベーター'],['access','利用・アクセス'],['accuracy','正確さ']]),
build('V11-NH-G3-U6-4-027',NH,'Unit 6-4',nhBase,'A Politer Group Email',[
['Our project group needed another class to send us two photographs for a shared presentation.','私たちの課題班は共同発表のため、別のクラスから写真を二枚送ってもらう必要がありました。'],
['I wrote the first email quickly because our work was already behind schedule.','作業が予定より遅れていたので、私は最初のメールを急いで書きました。'],
['The message began, “Send us the photos today. We need them now.”','そのメッセージは「今日写真を送ってください。今必要です」と始まりました。'],
['The information was clear, but my partner said the request sounded more like an order.','情報は明確でしたが、相手はお願いというより命令のように聞こえると言いました。'],
['We did need the files soon, yet the other class was helping us rather than working for us.','確かにファイルは早く必要でしたが、別のクラスは私たちのために働くのではなく協力してくれていました。'],
['We rewrote the opening to explain the purpose of the request first.','まずお願いの目的を説明するよう書き出しを直しました。'],
['Then we asked whether they could send the two selected photos by the end of the day.','それから、選んだ二枚の写真をその日の終わりまでに送ってもらえるかたずねました。'],
['We added the file names so they would know exactly which photos we meant.','どの写真か正確に分かるよう、ファイル名も加えました。'],
['At the end, we thanked them for helping with the joint presentation.','最後に共同発表への協力にお礼を書きました。'],
['The final email was only a little longer than the first version.','最終メールは最初の版より少し長いだけでした。'],
['However, it gave a reason, a clear deadline, and a polite request instead of a command.','しかし、命令ではなく理由、明確な締切、丁寧なお願いが入りました。'],
['The other class replied within an hour and attached the correct two files.','別のクラスは一時間以内に返事をし、正しい二つのファイルを添付しました。'],
['Our group saved the wording as an example for future shared projects.','私たちの班は今後の共同課題の例として、その表現を保存しました。'],
['Being specific did not require being rude; careful wording made the request both clear and respectful.','具体的に伝えることは失礼にすることではなく、注意した表現で明確さと礼儀の両方を保てました。']
],false,[['polite','丁寧な'],['deadline','締切'],['respectful','礼儀を示す']]),
build('V11-NH-G3-U6-4-028',NH,'Unit 6-4',nhBase,'The Strange Weather Number',[
['Our group compared temperature data collected outside the school for two weeks.','私たちの班は学校の外で二週間集めた気温データを比べました。'],
['Most afternoon readings were between similar values, but one day showed a number much higher than the rest.','午後の測定値の多くは似た範囲でしたが、ある日だけほかよりずっと高い数字でした。'],
['At first, we thought that day had simply been unusually hot.','最初、その日はただ特別に暑かったのだと思いました。'],
['One member wanted to use the number as the main example in our report.','一人はその数字をレポートの主な例に使おうとしました。'],
['Before writing the conclusion, we checked the notes beside each measurement.','結論を書く前に、各測定値のそばのメモを確認しました。'],
['The unusual reading had a short note saying that the sensor had been moved during cleaning.','異常な測定値には、掃除中にセンサーが動かされたという短いメモがありました。'],
['For part of that afternoon, it had been placed near a sunny wall instead of its usual shaded position.','その午後の一部、いつもの日陰ではなく日当たりのよい壁の近くに置かれていました。'],
['That change could explain why the reading was so different.','その変更で、なぜ測定値が大きく違ったか説明できる可能性がありました。'],
['We did not delete the number because it was part of the real record.','実際の記録の一部なので、その数字を削除はしませんでした。'],
['Instead, we marked it clearly and explained why it should not be compared directly with the normal readings.','代わりにはっきり印をつけ、通常の測定値と直接比べるべきでない理由を説明しました。'],
['Our graph showed the point with a note rather than hiding it.','グラフではその点を隠さず、注をつけて示しました。'],
['The final conclusion focused on the days measured under the same conditions.','最終的な結論は、同じ条件で測った日に注目しました。'],
['Checking the sensor note changed our interpretation without changing the original data.','センサーのメモを確認したことで、元のデータを変えずに解釈を変えました。'],
['A strange number became useful because it reminded us to ask how the data had been collected.','異常な数字は、データがどう集められたかを考えるきっかけとして役立ちました。']
],false,[['sensor','センサー'],['measurement','測定値'],['interpretation','解釈'],['shaded','日陰の']]),
build('V11-NH-G3-U6-4-029',NH,'Unit 6-4',nhBase,'Plain Words in an Exchange Email',[
['I wrote an email to a student I had met during an international exchange activity.','国際交流活動で会った生徒にメールを書きました。'],
['I wanted the message to sound friendly, so I used an English idiom that I had recently learned online.','親しみやすくしたくて、最近オンラインで知った英語の慣用表現を使いました。'],
['The phrase sounded natural to me because I had seen it in several videos.','いくつかの動画で見ていたので、その表現は私には自然に思えました。'],
['My exchange partner replied and asked what the sentence meant.','交流相手は返事で、その文がどういう意味かたずねました。'],
['I tried to explain the idiom with more English, but my explanation became longer and less clear.','さらに英語で慣用表現を説明しようとしましたが、説明は長く分かりにくくなりました。'],
['Then I looked at the idea I actually wanted to communicate.','そこで、本当に伝えたかった内容を考え直しました。'],
['It was simple: I hoped we could meet again if she visited Japan.','それは単純で、彼女が日本を訪れたらまた会えたらよいということでした。'],
['I replaced the idiom with that direct sentence.','私は慣用表現をその直接的な文に置き換えました。'],
['My partner immediately understood and answered with a similar wish.','相手はすぐ理解し、同じような願いを返してくれました。'],
['After that, I read the rest of my message and removed another expression that was only meant to sound clever.','そのあとメールの残りも読み、かっこよく聞かせるだけの別の表現も外しました。'],
['The final email was simpler, but our conversation became easier to continue.','最終メールは簡単になりましたが、会話は続けやすくなりました。'],
['I did not decide that idioms were always bad.','慣用表現がいつも悪いと決めたわけではありません。'],
['I learned instead that shared understanding matters more than showing a difficult phrase.','難しい表現を見せることより、共通理解のほうが大切だと学びました。'],
['Plain words were the better choice when the first expression created more questions than meaning.','最初の表現が意味より疑問を増やしたときは、平易な言葉のほうがよい選択でした。']
],false,[['idiom','慣用表現'],['direct','直接的な'],['shared understanding','共通理解']]),
build('V11-NH-G3-U6-4-030',NH,'Unit 6-4',nhBase,'Translate for the Audience',[
['Our class made a Japanese and English poster for a local culture event.','私たちのクラスは地域文化行事のために日本語と英語のポスターを作りました。'],
['The Japanese title used a short phrase that sounded lively and natural to local readers.','日本語の題名は地域の人には活気があり自然に聞こえる短い表現でした。'],
['I translated each word directly and put the result at the top of the English version.','私は一語ずつ直接訳し、その結果を英語版の一番上に置きました。'],
['The grammar was not obviously wrong, but an English-speaking visitor looked confused when she read it.','文法が明らかに間違っていたわけではありませんが、英語を話す来訪者は読んで困った様子でした。'],
['She understood the individual words but not what kind of event the phrase was advertising.','一つ一つの単語は分かっても、その表現がどんな行事を宣伝しているのか分かりませんでした。'],
['We explained that the event included local food, music, and short performances.','その行事には地域の食べ物、音楽、短い演奏があると説明しました。'],
['She suggested that the English title should tell readers that main idea more directly.','英語の題名では、その主な内容をもっと直接伝えたほうがよいと提案されました。'],
['Our group wrote three new titles and asked two other visitors which one was easiest to understand.','班で新しい題名を三つ作り、別の来訪者二人にどれが最も分かりやすいかたずねました。'],
['Both chose the version that clearly mentioned a local culture festival.','二人とも「地域文化祭」とはっきり分かる版を選びました。'],
['We used that title even though it was not a word-for-word copy of the Japanese phrase.','日本語表現の逐語訳ではありませんでしたが、その題名を使いました。'],
['The dates, place, and event details remained the same in both languages.','日付、場所、行事の詳細は両方の言語で同じままにしました。'],
['Only the headline changed to match what the English readers needed to know first.','見出しだけを、英語の読者が最初に知る必要がある内容に合わせて変えました。'],
['The experience showed us that accurate translation is not always the same as copying the shape of the original sentence.','正確な翻訳は必ずしも元の文の形をそのまま写すことと同じではないと分かりました。'],
['Thinking about the audience made the English poster more useful without changing the event itself.','読み手を考えることで、行事そのものを変えずに英語ポスターをより役立つものにできました。']
],false,[['audience','読み手・聞き手'],['word-for-word','逐語的な'],['headline','見出し']]),
build('V11-NH-G3-U6-4-031',NH,'Unit 6-4',nhBase,'Say What the Survey Cannot Prove',[
['Our group surveyed students about how often they used the school library after class.','私たちの班は放課後に学校図書館をどのくらい使うか生徒にアンケートしました。'],
['We hoped to understand whether longer opening hours would be useful.','開館時間を長くすることが役立つか知りたいと思っていました。'],
['Because we had only one lunch period to collect answers, we asked students in two nearby classrooms.','回答を集める時間が昼休み一回だけだったので、近くの二教室の生徒にたずねました。'],
['Thirty students answered, and many said they would use the library later in the afternoon.','三十人が答え、多くが午後遅くにも図書館を使いたいと言いました。'],
['At first, our conclusion said, “Students at our school want longer library hours.”','最初の結論には「この学校の生徒は図書館の開館時間延長を望んでいる」と書きました。'],
['Our teacher asked us to compare that statement with the people we had actually surveyed.','先生はその文と、実際にアンケートした人を比べるよう言いました。'],
['We had not asked every grade, club, or student group.','私たちはすべての学年、部活動、生徒グループにたずねたわけではありませんでした。'],
['Students who stayed in other parts of the school might have different habits.','学校の別の場所にいた生徒は違う習慣を持っているかもしれません。'],
['We changed the conclusion to say that many students in our small sample supported longer hours.','結論を「私たちの小さな調査対象では、多くの生徒が開館時間延長を支持した」に変えました。'],
['Then we added that a wider survey would be needed before making a school-wide claim.','学校全体について主張する前に、より広いアンケートが必要だとも加えました。'],
['The data itself did not become weaker after we wrote this limitation.','この限界を書いても、データ自体が弱くなったわけではありません。'],
['Instead, readers could see exactly what the survey did and did not show.','むしろ、アンケートが何を示し、何を示さないか読者が正確に分かるようになりました。'],
['Our report became more careful because the conclusion matched the size of our evidence.','結論を証拠の規模に合わせたことで、レポートはより慎重になりました。'],
['A small survey can still be useful when its limits are stated honestly.','小さなアンケートでも、限界を正直に示せば役立つと学びました。']
],false,[['sample','調査対象・標本'],['limitation','限界'],['claim','主張']]),
build('V11-NH-G3-U6-4-032',NH,'Unit 6-4',nhBase,'A Clear Lost-Item Report',[
['I found a small black case near the school gym after an evening event.','夕方の行事のあと、体育館の近くで小さな黒いケースを見つけました。'],
['I took it to the office and first said only, “I found this outside.”','私はそれを事務室へ持って行き、最初は「外でこれを見つけました」とだけ言いました。'],
['The staff member thanked me but asked where and when I had found it.','職員はお礼を言いましたが、どこでいつ見つけたのかたずねました。'],
['I realized that “outside” covered a large area and would not help someone match a lost-item report.','「外」では範囲が広すぎて、落とし物の届け出と照合する助けにならないと気づきました。'],
['I remembered that the case had been beside the second bench near the gym entrance.','そのケースは体育館入口近くの二つ目のベンチのそばにあったことを思い出しました。'],
['I had seen it at about six thirty, just after the final group left the building.','最後のグループが建物を出た直後の六時半ごろに見つけました。'],
['The case was black, had a short blue strap, and was about the size of my hand.','ケースは黒く、短い青いストラップがあり、手のひらほどの大きさでした。'],
['The staff member wrote those details in the office record.','職員はその詳細を事務室の記録に書きました。'],
['We did not open the case because the outside description was enough for the report.','外側の特徴だけで届け出には十分だったので、ケースは開けませんでした。'],
['The next morning, a student came looking for a case with a blue strap.','翌朝、青いストラップのケースを探している生徒が来ました。'],
['The time and place also matched where the student thought it had been lost.','時間と場所も、その生徒がなくしたと思っていた場所と一致しました。'],
['After checking the description, the staff member returned the case.','特徴を確認したあと、職員はケースを返しました。'],
['My first sentence had been true, but it was too vague to be very useful.','最初の一文は本当でしたが、役立つには曖昧すぎました。'],
['Adding time, place, and visible details turned a vague report into information that could be checked.','時間、場所、見える特徴を加えることで、曖昧な報告が確認できる情報へ変わりました。']
],false,[['strap','ストラップ'],['vague','曖昧な'],['visible','見える']]),
build('V11-NH-G3-U6-4-033',NH,'Unit 6-4',nhBase,'The Safer Night Route',[
['Our group stayed late at a community center to finish preparations for an event.','私たちの班は行事の準備を終えるため、地域センターに遅くまで残りました。'],
['When we were ready to leave, it was already dark outside.','帰る準備ができたとき、外はすでに暗くなっていました。'],
['A map showed two walking routes to the station.','地図には駅まで二つの徒歩経路がありました。'],
['The shortest route passed through a narrow road behind several closed buildings.','最短経路は、閉まった建物の裏の狭い道を通っていました。'],
['We had used that road during the day and knew it saved about five minutes.','昼間にはその道を使ったことがあり、約五分短縮できると知っていました。'],
['The second route followed a larger street with stores, streetlights, and more people.','二つ目の道は、店や街灯、人通りの多い大きな通りを進むものでした。'],
['One member suggested taking the fast route because everyone wanted to get home.','みんな早く帰りたかったので、一人は速い道を提案しました。'],
['Another member pointed out that the narrow road had very little light after the stores closed.','別の一人は、店が閉まったあとの狭い道には明かりがほとんどないと指摘しました。'],
['We compared the difference in time with the difference in visibility and activity around us.','時間の差と、周囲の見えやすさや人の動きの差を比べました。'],
['The five-minute saving did not seem important enough to choose the darker road.','五分の短縮は、暗い道を選ぶほど重要には思えませんでした。'],
['We stayed together and took the larger street.','私たちはいっしょに大通りを選びました。'],
['The walk was slightly longer, but we could see crossings and other people clearly.','少し遠回りでしたが、交差点やほかの人をはっきり見ることができました。'],
['We reached the station without any problem and sent a message when everyone had arrived.','問題なく駅へ着き、全員が到着したときにメッセージを送りました。'],
['The fastest route on a map was not automatically the best route under different conditions at night.','地図上で最速の道が、夜の違う条件でも自動的に最善の道になるわけではありませんでした。']
],false,[['route','経路'],['streetlight','街灯'],['visibility','見えやすさ']]),
build('V11-NH-G3-U6-4-034',NH,'Unit 6-4',nhBase,'Two Different Pieces of Advice',[
['I had to choose between joining an extra practice session and spending the evening finishing a school report.','私は追加練習に参加するか、その夜に学校のレポートを仕上げるか選ぶ必要がありました。'],
['My coach advised me to attend the practice because an important match was coming soon.','コーチは大切な試合が近いので練習に参加するよう勧めました。'],
['At home, my father advised me to skip the practice and complete the report first.','家では父が練習を休み、先にレポートを終えるよう勧めました。'],
['Both adults knew me well, and both pieces of advice sounded reasonable.','二人とも私をよく知っていて、どちらの助言ももっともに聞こえました。'],
['For a while, I hoped one of them would simply make the decision for me.','しばらくは、どちらかが私の代わりに決めてくれればと思いました。'],
['Instead, I wrote down why each person had given that advice.','代わりに、それぞれがなぜその助言をしたのか書き出しました。'],
['The coach was thinking about team preparation and the fact that I had missed one earlier session.','コーチはチームの準備と、私が以前一回練習を休んだことを考えていました。'],
['My father was thinking about the report deadline and how tired I had been after recent practices.','父はレポートの締切と、最近の練習後に私が疲れていたことを考えていました。'],
['I checked my report and found that only the final section and proofreading remained.','レポートを確認すると、最後の部分と見直しだけが残っていました。'],
['I estimated that I could finish those parts before practice if I worked without using my phone.','スマートフォンを使わず集中すれば、練習前にその部分を終えられると考えました。'],
['I completed the final section, asked my father to read one paragraph, and then went to practice.','最後の部分を終え、父に一段落だけ読んでもらってから練習へ行きました。'],
['After returning home, I did a short final check and submitted the report.','帰宅後、短い最終確認をしてレポートを提出しました。'],
['My choice was not exactly the same as either adult’s first suggestion.','私の選択は、どちらの大人の最初の提案とも完全には同じではありませんでした。'],
['Listening to both reasons helped me make a plan that answered the real concerns behind both pieces of advice.','両方の理由を聞くことで、二つの助言の背景にある本当の心配に応える計画を自分で作れました。']
],false,[['advice','助言'],['proofreading','見直し・校正'],['submitted','提出した'],['concern','心配・考慮点']])
];
if(all.length!==16)throw new Error('Batch04 G3 count '+all.length);
window.V11_BATCH04_G3_PASSAGES=all;
window.V11_BATCH04_G3_STATE={version:'20260828-g3-authoring',count:all.length,registered:false};
})();