'use strict';
const fs=require('fs'),vm=require('vm');global.window={};
const chain=['v11_batch11_passages_draft_g1.js','v11_batch11_passages_draft_g2.js','v11_batch11_g3_core.js','v11_batch11_passages_draft_g3_standard.js','v11_batch11_passages_draft_g3_long.js','v11_batch11_passages_draft_g3_yamaguchi_a.js','v11_batch11_passages_draft_g3_yamaguchi_b.js','v11_batch11_length_repair_r1.js','v11_batch11_length_repair_r2.js','v11_batch11_length_repair_r3.js','v11_batch11_length_repair_r4.js','v11_batch11_grammar_repair_r1.js','v11_batch11_grammar_repair_r2.js','v11_batch11_semantic_repair_r5.js','v11_batch11_semantic_repair_r6.js','v11_batch11_question_human_rewrite_r1.js','v11_batch11_question_human_rewrite_r2.js','v11_batch11_question_human_rewrite_r3.js','v11_batch11_question_human_rewrite_r4.js','v11_batch11_question_human_rewrite_r5.js','v11_batch11_question_human_rewrite_r6.js','v11_batch11_question_human_rewrite_r7.js','v11_batch11_question_human_rewrite_r8.js','v11_batch11_question_human_rewrite_r9.js'];for(const f of chain)vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const all=[...(window.V11_BATCH11_G1_DRAFTS||[]),...(window.V11_BATCH11_G2_DRAFTS||[]),...(window.V11_BATCH11_G3_DRAFTS||[])];
const generic=[/重要な具体的事実/,/判断・行動をした理由または必要だった条件/,/内容と一致する事実を、本文に基づいて一つ/,/行動や確認のあとに起きたこと/,/流れを要約するとき、空所/,/判断を支える手がかり・証拠となった内容/,/出来事の流れを自然につなぐため、空所/,/後半で述べられている具体的な事実/,/第\s*\d+\s*(?:段階|文)/];
const issues=[],seenPrompts=new Map(),types=new Map();let questions=0,reviewed=0;
function arr(x){return Array.isArray(x)?x:[x]}
for(const p of all){const qs=[...(p.questions||[]),...(p.questionSetB||[])];if((p.questions||[]).length!==5||(p.questionSetB||[]).length!==5)issues.push([p.id,'question-count']);if(/PENDING|R4_NONLEAK/i.test(String(p.questionStage||'')))issues.push([p.id,'pending-stage',p.questionStage]);const hr=Object.keys(p).some(k=>/^humanReviewR\d+$/.test(k)&&p[k]&&p[k].reviewed===true);if(hr)reviewed++;else issues.push([p.id,'human-review-missing']);
 for(const q of qs){questions++;const pr=String(q.prompt||'').trim(),an=String(q.answer||'').trim(),re=String(q.reason||'').trim();if(!pr||!an||re.length<8)issues.push([p.id,'empty-or-thin-question',q.questionType]);if(generic.some(rx=>rx.test(pr)))issues.push([p.id,'generic-prompt',pr]);if(!q.questionReview||!/HUMAN_REVIEW/.test(q.questionReview))issues.push([p.id,'question-review-missing',q.questionReview||null]);const es=arr(q.evidence),js=arr(q.evidenceJp);if(es.length!==js.length)issues.push([p.id,'evidence-pair-length',q.questionType]);for(let i=0;i<es.length;i++){const si=p.sentences.indexOf(es[i]);if(si<0)issues.push([p.id,'evidence-not-in-passage',es[i]]);else if(String((p.slashRows[si]||{}).jp)!==String(js[i]))issues.push([p.id,'evidence-jp-mismatch',q.questionType,si]);}const key=pr.replace(/\s+/g,' ');const prev=seenPrompts.get(key);if(prev&&prev!==p.id)issues.push([p.id,'duplicate-prompt-across-passages',prev,pr]);else seenPrompts.set(key,p.id);types.set(q.questionType,(types.get(q.questionType)||0)+1);}}
const requiredTypes=['DETAIL','REASON','GIST','INFERENCE','CONTENT_MATCH','SUMMARY_FILL'];for(const t of requiredTypes)if(!types.get(t))issues.push(['GLOBAL','missing-type',t]);
const result={passages:all.length,questions,reviewedPassages:reviewed,types:Object.fromEntries(types),issues,finalPass:all.length===50&&questions===500&&reviewed===50&&issues.length===0};fs.writeFileSync('V11_BATCH11_HUMAN_QUESTION_GATE.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passages:result.passages,questions:result.questions,reviewedPassages:reviewed,issues:issues.length,finalPass:result.finalPass}));if(!result.finalPass)process.exit(1);