'use strict';
const fs=require('fs');
const build=require('./v11_batch13_build_final_candidate.js');
function seg(locale,text){return [...new Intl.Segmenter(locale,{granularity:'sentence'}).segment(String(text||''))].map(x=>x.segment.trim()).filter(Boolean);}
function die(m){throw new Error(m);}
function score(a,b){const x=String(a).replace(/\s+/g,'').length,y=String(b).replace(/\s+/g,'').length;if(!x||!y)return 9;const r=x/y;return Math.abs(Math.log(r/0.42));}
function align(en,jp,id){const n=en.length,m=jp.length,INF=1e9,dp=Array.from({length:n+1},()=>Array(m+1).fill(INF)),prev=Array.from({length:n+1},()=>Array(m+1).fill(null));dp[0][0]=0;const moves=[[1,1],[1,2],[2,1]];for(let i=0;i<=n;i++)for(let j=0;j<=m;j++){if(dp[i][j]>=INF)continue;for(const [a,b] of moves){if(i+a>n||j+b>m)continue;const es=en.slice(i,i+a).join(' '),js=jp.slice(j,j+b).join('');const penalty=(a===1&&b===1?0:0.18)+score(es,js);const v=dp[i][j]+penalty;if(v<dp[i+a][j+b]){dp[i+a][j+b]=v;prev[i+a][j+b]=[i,j,a,b,penalty];}}}if(!prev[n][m])die(`unalignable ${id} en=${n} jp=${m}`);const rows=[];let i=n,j=m;while(i||j){const p=prev[i][j];if(!p)die(`alignment backtrack ${id}`);const [pi,pj,a,b,penalty]=p;rows.push({en:en.slice(pi,i).join(' '),jp:jp.slice(pj,j).join(''),enSentenceCount:a,jpSentenceCount:b,alignmentScore:Number(penalty.toFixed(4)),humanReviewed:false});i=pi;j=pj;}rows.reverse();if(rows.some(r=>r.enSentenceCount>2||r.jpSentenceCount>2||(r.enSentenceCount===2&&r.jpSentenceCount===2)))die(`illegal grouping ${id}`);return rows;}
function chunk(s){return String(s).replace(/([,;:]\s+)/g,'$1/ ').replace(/\s+(because|when|while|after|before|if|but|so|and)\s+/gi,' / $1 ' ).replace(/\s+\/\s+\/\s+/g,' / ').trim();}
const c=build();const packet={batch:'V11-B13',registered:false,officialTotal:768,humanReviewed:false,policy:{allowedAlignment:['1:1','1:2','2:1'],forbid:['2:2','partial-registration'],note:'suggested slash chunks are machine-generated starting points only; every row must be human-read before PASS'},passages:[]};let rows=0;for(const p of c.passages){const ens=seg('en',p.body),jps=seg('ja',p.fullTranslation);const aligned=align(ens,jps,p.id);for(const r of aligned){r.suggestedEn=chunk(r.en);r.suggestedJp=r.jp;}rows+=aligned.length;packet.passages.push({id:p.id,englishSentenceCount:ens.length,japaneseSentenceCount:jps.length,rows:aligned});}packet.summary={passages:packet.passages.length,rows,allHumanReviewed:false};if(packet.passages.length!==50)die('passage count');fs.writeFileSync('v11_batch13_slash_review_packet.json',JSON.stringify(packet,null,2));console.log(JSON.stringify(packet.summary));
