'use strict';
const fs=require('fs');
const plan=fs.readFileSync('V11_BATCH07_50_PASSAGE_PLAN.md','utf8');
const profile=JSON.parse(fs.readFileSync('V11_BATCH07_YAMAGUCHI_PROFILE.json','utf8'));
const ids=[...plan.matchAll(/^\d+\. `([^`]+)`/gm)].map(m=>m[1]);
const g3=ids.filter(x=>/-G3-/.test(x));
const rows=profile.passages||[];
const tiers=rows.reduce((a,r)=>(a[r.tier]=(a[r.tier]||0)+1,a),{});
const dupIds=rows.map(r=>r.id).filter((id,i,a)=>a.indexOf(id)!==i);
const missingProfile=g3.filter(id=>!rows.some(r=>r.id===id));
const extraProfile=rows.filter(r=>!g3.includes(r.id)).map(r=>r.id);
const yam=rows.filter(r=>r.tier==='yamaguchi_long_350_450');
const integrated=yam.filter(r=>(r.questionProfile||[]).includes('integrated_material')).length;
const shortOrSummary=yam.filter(r=>{const q=r.questionProfile||[];return q.includes('short_english_answer')||q.includes('summary_fill')}).length;
const req=profile.requirements||{};
const expected=profile.distribution||{};
const tierPass=(tiers.standard_140_220||0)===(expected.standard_140_220||0)&&(tiers.medium_long_230_320||0)===(expected.medium_long_230_320||0)&&(tiers.yamaguchi_long_350_450||0)===(expected.yamaguchi_long_350_450||0);
const out={generatedAt:new Date().toISOString(),g3PlanCount:g3.length,profileCount:rows.length,tiers,dupIds,missingProfile,extraProfile,integratedYamaguchiLong:integrated,shortEnglishOrSummaryYamaguchiLong:shortOrSummary,registered:req.registered===true,pass:g3.length===16&&rows.length===16&&!dupIds.length&&!missingProfile.length&&!extraProfile.length&&tierPass&&integrated>=(req.minIntegratedMaterialAmongYamaguchiLong||0)&&shortOrSummary>=(req.minShortEnglishOrSummaryAmongYamaguchiLong||0)&&req.registered!==true};
fs.writeFileSync('V11_BATCH07_YAMAGUCHI_PROFILE_AUDIT.json',JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify(out,null,2));
if(!out.pass)process.exitCode=1;
