const fs=require('fs');
const {loadCanonicalV7}=require('./v10_v7_lexicon_loader');
const ELEMENTARY_SOURCE=JSON.parse(fs.readFileSync('v10_elementary_vocab_allowlist.json','utf8'));
const ELEMENTARY=new Set((ELEMENTARY_SOURCE.words||[]).map(x=>String(x).toLowerCase()));
const v7=loadCanonicalV7();
const FILES=['v11_batch15_g1_body_draft.json','v11_batch15_g2_body_draft.json','v11_batch15_g3_body_draft.json'];
function tok(s){return (String(s||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(x=>x.toLowerCase())}
function uniq(a){return [...new Set(a)]}
function morph(w){const o=[];if(w.endsWith("'s")&&w.length>3)o.push(w.slice(0,-2));if(w.endsWith('ies')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ied')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ves')&&w.length>4)o.push(w.slice(0,-3)+'f',w.slice(0,-3)+'fe');if(w.endsWith('es')&&w.length>3)o.push(w.slice(0,-2),w.slice(0,-1));if(w.endsWith('s')&&w.length>3)o.push(w.slice(0,-1));if(w.endsWith('ing')&&w.length>4){const b=w.slice(0,-3);o.push(b,b+'e');if(b.length>2&&b.at(-1)===b.at(-2))o.push(b.slice(0,-1))}if(w.endsWith('ed')&&w.length>3){const b=w.slice(0,-2);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y');if(b.length>2&&b.at(-1)===b.at(-2))o.push(b.slice(0,-1))}if(w.endsWith('er')&&w.length>4){const b=w.slice(0,-2);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y')}if(w.endsWith('est')&&w.length>5){const b=w.slice(0,-3);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y')}return uniq(o.filter(Boolean))}
const IR=new Map(Object.entries({went:'go',gone:'go',came:'come',seen:'see',saw:'see',made:'make',took:'take',taken:'take',gave:'give',given:'give',wrote:'write',written:'write',read:'read',bought:'buy',brought:'bring',thought:'think',found:'find',knew:'know',known:'know',told:'tell',said:'say',spoke:'speak',spoken:'speak',ate:'eat',eaten:'eat',drank:'drink',drunk:'drink',ran:'run',swam:'swim',swum:'swim',became:'become',began:'begin',begun:'begin',left:'leave',felt:'feel',kept:'keep',met:'meet',sent:'send',built:'build',held:'hold',heard:'hear',lost:'lose',paid:'pay',put:'put',stood:'stand',understood:'understand',lying:'lie',dying:'die',tying:'tie'}));
const FUNC=new Set(`a an the i me my mine you your yours he him his she her hers it its we us our ours they them their theirs this that these those who whose whom which what when where why how am is are was were be been being do does did doing have has had having can cannot could may might must shall should will would not no yes and or but so if because as than to of in on at by for from with about into over under before after during while through up down out off again then there here also too very more most less least some any many much few little each every all both either neither another other same own one two first second third whether`.split(/\s+/));
const CONTR=new Set(["i'm","you're","he's","she's","it's","we're","they're","let's","isn't","aren't","wasn't","weren't","don't","doesn't","didn't","can't","couldn't","won't","wouldn't","shouldn't","mustn't","i've","you've","we've","they've","hasn't","haven't","hadn't","i'll","you'll","he'll","she'll","we'll","they'll","i'd"]);
function code(anchor){return /^NH\b/i.test(anchor)?'NH':'SS'}
function section(anchor){return String(anchor).replace(/^NH\s+/i,'').replace(/^Sunshine\s+/i,'').trim()}
function cutoff(c,g,s){const units=v7.units[`${c}|${g}`]||{};const at=(u,r)=>{const p=Number(units[u]);if(!p)throw Error(`mapping missing ${c}|${g}|${s}|${u}`);return {code:c,grade:g,pdf:p,subrank:Number(r)}};if(c==='SS'){let m=s.match(/^Get Ready\s*(\d+)$/i);if(m)return at('Pr',+m[1]);if(/Step\s*6|Our Project\s*3|Power-Up\s*6/i.test(s))return at('P10',8);m=s.match(/^PROGRAM\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r=k;if(g===1&&n===9&&k>=2)r=Math.max(r,3);if(g===1&&n===10&&k===1)r=2;if(g===1&&n===10&&k>=4)r=8;if(g===2&&n===7&&k===1)r=2;if(g===2&&n===8&&k>=2)r=3;if(g===3&&n===7&&k===1)r=2;return at(`P${n}`,r)}}else{let m=s.match(/^Unit\s*0$/i);if(m)return at('U0',9);m=s.match(/^Unit\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r;if(g===1){r=k<=2?k:(n<=4?3:6);if(n===8&&k===1)r=2}else{r=k===1?1:k===2?2:k===3?4:5;if(g===2&&n===3&&k===1)r=2;if(g===2&&n===7&&k===1)r=2;if(g===3&&n===1&&k===1)r=2}return at(`U${n}`,r)}}throw Error(`no cutoff ${c}|${g}|${s}`)}
function intro(c,w){return v7.lex[`${c}|${w}`]||null}function allowed(i,cut){if(!i)return false;const [g,p,s]=i;if(+g<cut.grade)return true;if(+g>cut.grade)return false;return +p<cut.pdf||(+p===cut.pdf&&+s<=cut.subrank)}
function classify(w,cut,noted){if(noted.has(w))return ['NOTED_UNLEARNED_ALLOWED'];if(CONTR.has(w))return ['CONTRACTION_TO_GRAMMAR'];if(FUNC.has(w))return ['FUNCTION_TO_GRAMMAR'];const bases=uniq([IR.get(w),...morph(w)].filter(Boolean));for(const b of bases)if(ELEMENTARY.has(b))return ['MORPHOLOGY_TO_GRAMMAR',b];if(ELEMENTARY.has(w))return ['ELEMENTARY_ALLOWED'];for(const b of bases){const i=intro(cut.code,b);if(i&&allowed(i,cut))return ['MORPHOLOGY_TO_GRAMMAR',b,i]}const d=intro(cut.code,w);if(d)return allowed(d,cut)?['V7_ALLOWED',null,d]:['FUTURE_V7_LEAK',null,d];for(const b of bases){const i=intro(cut.code,b);if(i&&!allowed(i,cut))return ['FUTURE_V7_LEAK',b,i]}return ['UNREGISTERED_V7']}
const report={batch:'V11-B15',scope:'draft body only; 50 current passages; no historical re-audit',canonicalSource:v7.source,passages:0,counts:{},violations:[],byPassage:[]};
for(const file of FILES){const d=JSON.parse(fs.readFileSync(file,'utf8'));const grade=Number(d.grade);for(const p of d.passages||[]){report.passages++;const c=code(p.anchor),cut=cutoff(c,grade,section(p.anchor));const notes=Array.isArray(p.notes)?p.notes:[];const noted=new Set(notes.filter(n=>n&&String(n.english||'').trim()&&String(n.japanese||'').trim()).flatMap(n=>tok(n.english)));const seen=[];const raw=String(p.body||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[];for(const r of raw){const w=r.toLowerCase(),cl=classify(w,cut),kind=cl[0];report.counts[kind]=(report.counts[kind]||0)+1;if(kind==='FUTURE_V7_LEAK'||kind==='UNREGISTERED_V7')seen.push({word:w,kind,base:cl[1]||null,intro:cl[2]||null})}const u=[];const key=new Set;for(const x of seen){const k=x.word+'|'+x.kind;if(!key.has(k)){key.add(k);u.push(x)}}if(u.length){report.byPassage.push({id:p.id,grade,anchor:p.anchor,violations:u});report.violations.push(...u.map(x=>({id:p.id,grade,anchor:p.anchor,...x})))}}}
report.uniqueViolations=report.violations.length;report.futureVocab=report.violations.filter(x=>x.kind==='FUTURE_V7_LEAK').length;report.unregistered=report.violations.filter(x=>x.kind==='UNREGISTERED_V7').length;report.pass=report.passages===50&&report.futureVocab===0&&report.unregistered===0;
fs.writeFileSync('v11_batch15_vocab_chronology_report.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({passages:report.passages,pass:report.pass,futureVocab:report.futureVocab,unregistered:report.unregistered,uniqueViolations:report.uniqueViolations,counts:report.counts},null,2));
if(report.passages!==50)process.exit(3);
