const fs=require('fs');
const {chromium}=require('playwright');
const report={generatedAt:new Date().toISOString(),batch:'V11-B15',student:null,teacher:null,persistent:null,finalPass:false};
function assert(c,m){if(!c)throw new Error(m)}
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}});const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});let r=await p.goto('http://127.0.0.1:4173/index.html',{waitUntil:'networkidle',timeout:60000});assert(r&&r.ok(),'HTTP '+(r&&r.status()));await p.waitForTimeout(1200);assert(errs.length===0,'initial errors '+errs.join(' | '));
await p.emulateMedia({media:'print'});
async function mode(name,cls){await p.evaluate(c=>{document.body.classList.remove('print-student','print-teacher');document.body.classList.add(c)},cls);const s=await p.evaluate(()=>{const q=x=>document.querySelector(x);const d=x=>q(x)?getComputedStyle(q(x)).display:null;return{passage:d('#passage'),slash:d('#slash'),questions:d('#questions'),answers:d('#answers'),audit:d('#audit')}});if(name==='student'){assert(s.passage==='block'&&s.questions==='block','student passage/questions');assert(s.slash==='none'&&s.answers==='none','student leaked teacher content')}else{for(const k of ['passage','slash','questions','answers'])assert(s[k]==='block',`teacher ${k} ${s[k]}`)}const pdf=await p.pdf({format:'A4',printBackground:true,margin:{top:'10mm',right:'10mm',bottom:'10mm',left:'10mm'}});assert(pdf.length>15000,`${name} PDF too small ${pdf.length}`);return{pass:true,styles:s,pdfBytes:pdf.length}}
report.student=await mode('student','print-student');report.teacher=await mode('teacher','print-teacher');
await p.emulateMedia({media:'screen'});await p.evaluate(()=>{document.body.classList.remove('print-student','print-teacher');localStorage.setItem('v11-b15-persistence-probe','ok')});for(let i=0;i<2;i++){await p.reload({waitUntil:'networkidle',timeout:60000});await p.waitForTimeout(800);const st=await p.evaluate(()=>({probe:localStorage.getItem('v11-b15-persistence-probe'),ready:document.readyState,body:(document.body&&document.body.innerText||'').length,hasRegister:typeof window.V11_REGISTER_PASSAGES==='function',hasPassage:!!document.querySelector('#passage')}));assert(st.probe==='ok'&&st.ready==='complete'&&st.body>500&&st.hasRegister&&st.hasPassage,'persistent reload '+JSON.stringify(st))}assert(errs.length===0,'runtime errors '+errs.join(' | '));report.persistent={pass:true,reloads:2,localStorage:true,errors:[]};report.finalPass=true;fs.writeFileSync('V11_BATCH15_A4_PERSISTENT_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}catch(e){report.error=String(e.stack||e);fs.writeFileSync('V11_BATCH15_A4_PERSISTENT_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.error(e);process.exitCode=1}finally{await b.close()}})();
