const fs=require('fs');
const bodyFiles=['V11_FINAL32_BODY_TRANSLATION_DRAFT_G1_001_008.json','V11_FINAL32_BODY_TRANSLATION_DRAFT_G1_009_011.json','V11_FINAL32_BODY_TRANSLATION_DRAFT_G2_001_008.json','V11_FINAL32_BODY_TRANSLATION_DRAFT_G2_009_011.json','V11_FINAL32_BODY_TRANSLATION_DRAFT_G3_001_010.json'];
const items=bodyFiles.flatMap(f=>JSON.parse(fs.readFileSync(f,'utf8')).items||[]);
if(items.length!==32||new Set(items.map(x=>x.id)).size!==32)throw Error('FINAL32 count/ids');
function norm(s){return String(s||'').replace(/[’]/g,"'").replace(/\s+/g,' ').trim();}
const rules=[
['WILL_FUTURE',/\bwill\s+(?:not\s+)?[a-z]+\b|\b(?:i|you|he|she|it|we|they)'ll\b/i,2],['BE_GOING_TO',/\b(?:am|is|are) going to\s+[a-z]+\b/i,2],['MODAL_CAN',/\bcan\s+(?:not\s+)?[a-z]+\b/i,1],['MODAL_COULD',/\bcould\s+(?:not\s+)?[a-z]+\b/i,2],['MODAL_MAY_MIGHT',/\b(?:may|might)\s+(?:not\s+)?[a-z]+\b/i,2],['MODAL_MUST',/\bmust\s+(?:not\s+)?[a-z]+\b/i,2],['MODAL_SHOULD',/\bshould\s+(?:not\s+)?[a-z]+\b/i,2],['HAVE_TO',/\b(?:have|has|had) to\s+[a-z]+\b/i,2],
['PRESENT_PROGRESSIVE',/\b(?:am|is|are)\s+(?!(?:interesting|amazing|exciting|surprising|boring|tiring|worrying|frightening|moving|touching|charming|promising|missing|following|leading|remaining|outstanding|willing)\b)[a-z]+ing\b/i,1],['PAST_PROGRESSIVE',/\b(?:was|were)\s+(?!(?:interesting|amazing|exciting|surprising|boring|tiring|worrying|frightening|moving|touching|charming|promising|missing|following|leading|remaining|outstanding|willing)\b)[a-z]+ing\b/i,1],['PRESENT_PERFECT_PROGRESSIVE',/\b(?:have|has)\s+been\s+[a-z]+ing\b/i,3],['PRESENT_PERFECT',/\b(?:have|has)\s+(?!to\b)(?:been|gone|seen|done|made|taken|given|written|known|come|become|found|felt|kept|met|left|heard|lost|built|bought|brought|thought|told|said|spoken|eaten|drunk|swum|begun|[a-z]+ed)\b/i,3],
['WANT_TO',/\b(?:want|wants|wanted)\s+to\s+[a-z]+\b/i,1],['VERB_TO_INFINITIVE',/\b(?:need|hope|plan|decide|try|learn|start|begin|like|love|choose|promise|agree|expect|wish|help)\s+to\s+[a-z]+\b/i,2],['WH_TO_INFINITIVE',/\b(?:what|when|where|which|who|how)\s+to\s+[a-z]+\b/i,2],['COMPARATIVE',/\b(?:better|worse|bigger|smaller|larger|longer|shorter|higher|lower|older|younger|faster|slower|easier|harder|more\s+[a-z]+|less\s+[a-z]+)\s+than\b/i,2],['SUPERLATIVE',/\b(?:the\s+(?:best|worst|biggest|smallest|largest|longest|shortest|highest|lowest|oldest|youngest|fastest|slowest|easiest|hardest|most\s+[a-z]+|least\s+[a-z]+)|(?:best|worst|biggest|smallest|largest|longest|shortest|highest|lowest|oldest|youngest|fastest|slowest|easiest|hardest))\b/i,2],['IF_CLAUSE',/\bif\s+(?:i|you|he|she|it|we|they|people|someone|something|there|this|that)\s+/i,2],['WHEN_WHILE_CLAUSE',/\b(?:when|while)\s+(?:i|you|he|she|it|we|they|people|someone|something|there|this|that)\s+/i,2],['WHETHER_CLAUSE',/\bwhether\s+(?:i|you|he|she|it|we|they|people|someone|something|there|this|that)\s+/i,3],['BECAUSE_CLAUSE',/\bbecause\s+(?:i|you|he|she|it|we|they|people|someone|something|there|this|that)\s+/i,2],['PASSIVE',/\b(?:am|is|are|was|were|be|been)\s+(?!(?:tired|surprised|interested|excited|worried|pleased|glad|afraid|ready|gone)\b)(?:[a-z]+ed|built|made|known|seen|given|taken|written|shown|thrown|found|called|sent|told|kept|held|lost|bought|brought)\b/i,2],['RELATIVE_PRONOUN',/\b(?:people|person|persons|man|woman|boy|girl|student|students|teacher|teachers|friend|friends|thing|things|book|books|food|foods|product|products|animal|animals|place|places|item|items|country|countries|city|cities|building|buildings|story|stories|message|messages)\s+(?:who|which|that)\s+(?:am|is|are|was|were|can|could|will|would|has|have|had|do|does|did|[a-z]+s?)\b/i,3],['IT_IS_ADJ_TO',/\bit\s+(?:is|was)\s+(?:easy|hard|difficult|important|necessary|possible|good|nice|useful|dangerous|safe|fun|interesting)\s+(?:for\s+(?:me|you|him|her|us|them|people|students)\s+)?to\s+[a-z]+\b/i,2],['SO_THAT',/\bso\s+that\s+(?:i|you|he|she|it|we|they|people|someone|something)\s+/i,3],['NOT_ONLY_BUT_ALSO',/\bnot only\b[^.?!]{1,160}\bbut also\b/i,3]];
const detections=[],future=[]; for(const item of items){const grade=Number(item.id.match(/-G([123])-/)[1]);for(const [feature,re,minGrade] of rules){const m=norm(item.body).match(re);if(m){const row={id:item.id,grade,feature,minGrade,match:m[0]};detections.push(row);if(minGrade>grade)future.push(row);}}}
const out={batch:'V11-FINAL32',gate:'FORMAL_GRAMMAR_CHRONOLOGY_TEACHING_YEAR',registered:false,officialTotal:968,passages:items.length,uniqueIds:new Set(items.map(x=>x.id)).size,detectedOccurrences:detections.length,unresolvedOccurrences:0,futureGrammarLeak:future.length,finalPass:future.length===0,future,detections};
fs.writeFileSync('V11_FINAL32_FORMAL_GRAMMAR_CHRONOLOGY_REPORT.json',JSON.stringify(out,null,2)+'\n'); console.log(JSON.stringify(out)); if(!out.finalPass)process.exitCode=2;