const fs=require('fs');
const {loadCanonicalV7}=require('../v10_v7_lexicon_loader');
const elementary=JSON.parse(fs.readFileSync('v10_elementary_vocab_allowlist.json','utf8'));
const ELEMENTARY=new Set((elementary.words||[]).map(x=>String(x).toLowerCase()));
const FUNCTION=new Set(`a an the i me my mine you your yours he him his she her hers it its we us our ours they them their theirs this that these those who whose whom which what when where why how am is are was were be been being do does did doing have has had having can cannot could may might must shall should will would not no yes and or but so if because as than to of in on at by for from with about into over under before after during while through up down out off again then there here also too very more most less least some any many much few little each every all both either neither another other same own one two first second third`.split(/\s+/));
const CONTRACTIONS=new Set(["i'm","you're","he's","she's","it's","we're","they're","let's","isn't","aren't","wasn't","weren't","don't","doesn't","didn't","can't","couldn't","won't","wouldn't","shouldn't","mustn't","i've","you've","we've","they've","hasn't","haven't","hadn't","i'll","you'll","he'll","she'll","we'll","they'll","i'd","you'd","he'd","she'd","we'd","they'd"]);
const IRREG=new Map(Object.entries({went:'go',gone:'go',came:'come',seen:'see',saw:'see',made:'make',took:'take',taken:'take',gave:'give',given:'give',wrote:'write',written:'write',read:'read',bought:'buy',brought:'bring',thought:'think',found:'find',knew:'know',known:'know',told:'tell',said:'say',spoke:'speak',spoken:'speak',ate:'eat',eaten:'eat',drank:'drink',drunk:'drink',ran:'run',swam:'swim',swum:'swim',became:'become',began:'begin',begun:'begin',left:'leave',felt:'feel',kept:'keep',met:'meet',sent:'send',built:'build',held:'hold',heard:'hear',lost:'lose',paid:'pay',put:'put',stood:'stand',understood:'understand',lying:'lie',dying:'die',tying:'tie'}));
function tok(s){return (String(s||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(x=>x.toLowerCase())}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function bases(w){const o=[];if(w.endsWith("'s")&&w.length>3)o.push(w.slice(0,-2));if(w.endsWith('ies')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ied')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ves')&&w.length>4)o.push(w.slice(0,-3)+'f',w.slice(0,-3)+'fe');if(w.endsWith('es')&&w.length>3)o.push(w.slice(0,-2),w.slice(0,-1));if(w.endsWith('s')&&w.length>3)o.push(w.slice(0,-1));for(const suf of ['ing','ed','er','est'])if(w.endsWith(suf)&&w.length>suf.length+2){const b=w.slice(0,-suf.length);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y');if(b.length>2&&b.at(-1)===b.at(-2))o.push(b.slice(0,-1));}return uniq(o)}
function introFor(v7,code,w){return v7.lex[`${code}|${w}`]||null}
function classify(v7,w,grade){if(CONTRACTIONS.has(w)||FUNCTION.has(w)||w==='whether')return{kind:'GRAMMAR_ROUTED'};const bs=uniq([IRREG.get(w),...bases(w)]);for(const b of bs)if(ELEMENTARY.has(b))return{kind:'GRAMMAR_ROUTED',base:b};if(ELEMENTARY.has(w))return{kind:'ELEMENTARY'};const forms=uniq([w,...bs]);let found=[];for(const form of forms)for(const code of ['NH','SS']){const i=introFor(v7,code,form);if(i)found.push({code,form,intro:i})}if(!found.length)return{kind:'UNREGISTERED'};const future=found.filter(x=>Number(x.intro[0])>Number(grade));const byCode=new Map();for(const x of found){const old=byCode.get(x.code);if(!old||Number(x.intro[0])<Number(old.intro[0]))byCode.set(x.code,x)}const missingOrFuture=['NH','SS'].filter(c=>!byCode.get(c)||Number(byCode.get(c).intro[0])>Number(grade));if(missingOrFuture.length)return{kind:'FUTURE_V7',found,missingOrFuture};return{kind:'V7_ALLOWED',found:[...byCode.values()]}}
const files=['V11_BATCH16_BODY_TRANSLATION_DRAFT_G1_001_010.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G1_011_017.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G2_001_009.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G2_010_017.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G3_001_008.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G3_009_016.json'];
const ps=files.flatMap(f=>JSON.parse(fs.readFileSync(f,'utf8')).items);if(ps.length!==50)throw Error(`Batch16 ${ps.length}/50`);
const local=new Map();for(const f of fs.readdirSync('.')){if(!/^V11_BATCH16_REQUIRED_LOCAL_GLOSS_G[123]_\d{3}\.json$/.test(f))continue;const j=JSON.parse(fs.readFileSync(f,'utf8'));local.set(j.passageId,new Set((j.requiredLocal||[]).map(v=>String(v.word||'').toLowerCase()).filter(Boolean)))}
function sources(p){const a=[['body',p.body]];if(p.slash)a.push(['slash',p.slash]);for(const key of ['questions','questionSetA','questionSetB'])for(const [i,q] of (p[key]||[]).entries())for(const k of ['answer','evidence'])a.push([`${key}:${i+1}.${k}`,q&&q[k]]);return a}
const v7=loadCanonicalV7();if(Number(v7.source&&v7.source[2])!==3975)throw Error('v7 source count');const unresolved=[],future=[];let tokens=0,noteCovered=0;for(const p of ps){const grade=Number(p.grade||String(p.id).match(/-G([123])-/)?.[1]);if(!grade)throw Error(`grade ${p.id}`);const noted=local.get(p.id)||new Set();for(const[where,text]of sources(p))for(const w of tok(text)){tokens++;if(noted.has(w)){noteCovered++;continue}const c=classify(v7,w,grade);if(c.kind==='UNREGISTERED')unresolved.push({id:p.id,grade,where,word:w});if(c.kind==='FUTURE_V7')future.push({id:p.id,grade,where,word:w,missingOrFuture:c.missingOrFuture,found:c.found})}}
const report={generatedAt:new Date().toISOString(),batch:'V11-B16',gate:'FORMAL_CANONICAL_V7_VOCAB_GRADE_TARGETED_BOTH_TEXTBOOKS',chronologyMode:'Batch16 passages are grade-targeted rather than textbook-section-bound. A non-local lexical item must be introduced by the target grade in both verified canonical-v7 NH and SS tracks; required-local notes remain the only explicit exception.',sourceRecords:v7.source[2],passages:ps.length,tokensScanned:tokens,requiredNoteCoveredOccurrences:noteCovered,unregisteredOccurrences:unresolved.length,futureVocabLeakOccurrences:future.length,finalPass:ps.length===50&&unresolved.length===0&&future.length===0,unresolved,future};fs.writeFileSync('V11_BATCH16_FORMAL_VOCAB_CHRONOLOGY_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(!report.finalPass)process.exitCode=1;
