const fs=require('fs');
const path=require('path');
const {chromium,webkit}=require('playwright');
function filesUnder(dir='.') {let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out=out.concat(filesUnder(p));else out.push(p);}return out;}
function visit(v,fn,seen=new Set()){if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))for(const x of v)visit(x,fn,seen);else for(const x of Object.values(v))visit(x,fn,seen);}
function richness(o){try{return JSON.stringify(o).length}catch{return 0}}
const found=new Map();
for(const f of filesUnder().filter(f=>f.endsWith('.json'))){let v;try{v=JSON.parse(fs.readFileSync(f,'utf8'))}catch{continue}visit(v,o=>{const id=String(o.id||'');if(/^V11-B15-G[123]-\d{3}$/.test(id)){const old=found.get(id);if(!old||richness(o)>richness(old.o))found.set(id,{o,source:f});}})}
const ids=[...found.keys()].sort();
if(ids.length!==50)throw new Error(`Batch15 candidate count ${ids.length} != 50`);
const candidate=ids.map(id=>found.get(id).o);
const report={generatedAt:new Date().toISOString(),batch:'V11-B15',candidatePassages:ids.length,candidateInjected:true,candidateFirst:{id:ids[0],source:found.get(ids[0]).source,keys:Object.keys(candidate[0]).sort()},browsers:{},finalPass:false};
async function run(name,browserType,device){const browser=await browserType.launch({headless:true});const context=await browser.newContext(device||{});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push('pageerror:'+e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});const r=await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'networkidle',timeout:60000});await page.waitForTimeout(1000);const runtime=await page.evaluate(()=>{const keys=Object.keys(window).filter(k=>/^V11/.test(k)).sort();const samples={};for(const k of keys){const v=window[k];if(Array.isArray(v)&&v.length&&v[0]&&typeof v[0]==='object')samples[k]={type:'array',length:v.length,firstKeys:Object.keys(v[0]).sort(),firstId:v[0].id||null};else if(v&&typeof v==='object'){const vals=Object.values(v);const first=vals.find(x=>x&&typeof x==='object');samples[k]={type:'object',keys:Object.keys(v).slice(0,20),firstKeys:first?Object.keys(first).sort():[]};}else samples[k]={type:typeof v};}return{keys,samples,registerSource:typeof window.V11_REGISTER_PASSAGES==='function'?String(window.V11_REGISTER_PASSAGES).slice(0,8000):null};});if(!report.runtime)report.runtime=runtime;const registration=await page.evaluate(batch=>{try{if(typeof window.V11_REGISTER_PASSAGES!=='function')throw new Error('V11_REGISTER_PASSAGES missing');const ret=window.V11_REGISTER_PASSAGES(batch);return{ok:true,returnType:typeof ret}}catch(e){return{ok:false,error:String(e&&e.stack||e)}}},candidate);await page.waitForTimeout(500);const state=await page.evaluate(()=>({title:document.title,bodyChars:(document.body&&document.body.innerText||'').length,ready:document.readyState,hasRegister:typeof window.V11_REGISTER_PASSAGES==='function',hasPassage:!!document.querySelector('#passage'),hasQuestions:!!document.querySelector('#questions'),hasGrade:!!document.querySelector('#grade')}));const pass=!!r&&r.ok()&&registration.ok&&state.ready==='complete'&&state.bodyChars>500&&state.hasRegister&&state.hasPassage&&state.hasQuestions&&state.hasGrade&&errors.length===0;report.browsers[name]={pass,httpStatus:r&&r.status(),registration,...state,errors};fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();if(!pass)throw new Error(`${name} failed: ${JSON.stringify(report.browsers[name])}`)}
(async()=>{try{await run('chromium',chromium);await run('webkit',webkit);await run('iphone-webkit',webkit,{viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true,deviceScaleFactor:3});report.finalPass=Object.values(report.browsers).every(x=>x.pass);fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!report.finalPass)process.exit(1)}catch(e){report.error=String(e.stack||e);fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.error(e);process.exit(1)}})();
