const fs=require('fs');
const path=require('path');
const {chromium,webkit}=require('playwright');
function filesUnder(dir='.') {let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out=out.concat(filesUnder(p));else out.push(p);}return out;}
function visit(v,fn,seen=new Set()){if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))for(const x of v)visit(x,fn,seen);else for(const x of Object.values(v))visit(x,fn,seen);}
function richness(o){try{return JSON.stringify(o).length}catch{return 0}}
const bodies=new Map(),slashes=new Map(),qas=new Map();
for(const f of filesUnder().filter(f=>f.endsWith('.json')&&!/V11_BATCH15_BROWSER_GATE_REPORT/.test(f))){let v;try{v=JSON.parse(fs.readFileSync(f,'utf8'))}catch{continue}visit(v,o=>{
  const id=String(o.id||'');
  if(/^V11-B15-G[123]-\d{3}$/.test(id)&&o.body&&o.fullTranslation){const old=bodies.get(id);if(!old||richness(o)>richness(old.o))bodies.set(id,{o,source:f});}
  if(/^V11-B15-G[123]-\d{3}$/.test(id)&&((o.bodySlash&&o.translationSlash)||Array.isArray(o.slashRows))){const old=slashes.get(id);if(!old||richness(o)>richness(old.o))slashes.set(id,{o,source:f});}
  const qid=String(o.passageId||'');
  if(/^V11-B15-G[123]-\d{3}$/.test(qid)&&Array.isArray(o.questionsA)&&Array.isArray(o.questionsB)){const old=qas.get(qid);if(!old||richness(o)>richness(old.o))qas.set(qid,{o,source:f});}
});}
const ids=[...bodies.keys()].sort();if(ids.length!==50)throw new Error(`Batch15 body count ${ids.length} != 50`);
function anchorMeta(p,id){
  const raw=String(p.anchor||'').trim();
  const idm=/^V11-B15-G([123])-\d{3}$/.exec(id);if(!idm)throw new Error(`${id} invalid id`);const grade=idm[1];
  let book=null,section=null;
  let m=/^(NH|SS)-G([123])-(.+)$/.exec(raw);
  if(m){if(m[2]!==grade)throw new Error(`${id} anchor grade mismatch ${raw}`);book=m[1];const code=m[3];section=code;if(/^U\d/.test(code))section='Unit '+code.slice(1);else if(/^P\d/.test(code))section='PROGRAM '+code.slice(1);}
  if(!book){m=/^(New\s*Horizon|New\s*Horizon|NH|Sunshine|SS)\s+(Unit|PROGRAM)\s+(.+)$/i.exec(raw);if(m){book=/^(New\s*Horizon|NH)$/i.test(m[1].replace(/\s+/g,' '))?'NH':'SS';section=(m[2].toUpperCase()==='PROGRAM'?'PROGRAM':'Unit')+' '+m[3].trim();}}
  if(!book){m=/^(ニューホライズン|サンシャイン)\s+(Unit|PROGRAM)\s+(.+)$/i.exec(raw);if(m){book=m[1]==='ニューホライズン'?'NH':'SS';section=(m[2].toUpperCase()==='PROGRAM'?'PROGRAM':'Unit')+' '+m[3].trim();}}
  if(!book||!section)throw new Error(`${id} unsupported anchor ${raw}`);
  return{textbook:book==='NH'?'ニューホライズン':'サンシャイン',anchor:{textbook:book==='NH'?'New Horizon':'Sunshine',grade:Number(grade),unit:section},grade,section};
}
function slashRowsFor(id){const rec=slashes.get(id);if(!rec)throw new Error(`${id} missing human slash artifact`);const s=rec.o;if(Array.isArray(s.slashRows)&&s.slashRows.length)return s.slashRows.map(r=>({en:String(r.en||r.english||'').trim(),jp:String(r.jp||r.japanese||'').trim(),humanReview:r.humanReview||'B15_HUMAN_SLASH_PASS',alignmentShape:r.alignmentShape||'1:1'}));const en=String(s.bodySlash||'').split(' / ').map(x=>x.trim()).filter(Boolean),jp=String(s.translationSlash||'').split(' / ').map(x=>x.trim()).filter(Boolean);if(en.length!==jp.length||!en.length)throw new Error(`${id} slash count mismatch ${en.length}/${jp.length}`);return en.map((x,i)=>({en:x,jp:jp[i],humanReview:'B15_HUMAN_SLASH_PASS',alignmentShape:'1:1'}));}
function questionsFor(id){const rec=qas.get(id);if(!rec)throw new Error(`${id} missing human question artifact`);const q=rec.o;if(q.questionsA.length!==5||q.questionsB.length!==5)throw new Error(`${id} requires A/B 5 questions`);return{A:q.questionsA.map((x,i)=>({...x,set:'A',no:i+1})),B:q.questionsB.map((x,i)=>({...x,set:'B',no:i+1}))};}
const candidate=ids.map(id=>{const base=bodies.get(id).o,meta=anchorMeta(base,id),slashRows=slashRowsFor(id),qq=questionsFor(id);const sentences=slashRows.map(r=>r.en).filter(Boolean);return{...base,...meta,registered:false,sentences,slashRows,questions:qq.A,questionSetB:qq.B,batch:'V11-B15',finalHumanQuestionReview:true,finalSlashHumanReview:'B15_SLASH_HUMAN_REVIEW_PASS'};});
const report={generatedAt:new Date().toISOString(),batch:'V11-B15',candidatePassages:candidate.length,candidateInjected:true,assembly:{body:ids.length,slash:ids.filter(id=>slashes.has(id)).length,questions:ids.filter(id=>qas.has(id)).length},candidateFirst:{id:ids[0],bodySource:bodies.get(ids[0]).source,slashSource:slashes.get(ids[0]).source,questionSource:qas.get(ids[0]).source,keys:Object.keys(candidate[0]).sort()},browsers:{},finalPass:false};
async function run(name,browserType,device){const browser=await browserType.launch({headless:true});const context=await browser.newContext(device||{});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push('pageerror:'+e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});const r=await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'networkidle',timeout:60000});await page.waitForTimeout(1000);const registration=await page.evaluate(batch=>{try{if(typeof window.V11_REGISTER_PASSAGES!=='function')throw new Error('V11_REGISTER_PASSAGES missing');const ret=window.V11_REGISTER_PASSAGES(batch);return{ok:true,ret}}catch(e){return{ok:false,error:String(e&&e.stack||e)}}},candidate);await page.waitForTimeout(500);const state=await page.evaluate(()=>({title:document.title,bodyChars:(document.body&&document.body.innerText||'').length,ready:document.readyState,hasRegister:typeof window.V11_REGISTER_PASSAGES==='function',hasPassage:!!document.querySelector('#passage'),hasQuestions:!!document.querySelector('#questions'),hasGrade:!!document.querySelector('#grade')}));const pass=!!r&&r.ok()&&registration.ok&&state.ready==='complete'&&state.bodyChars>500&&state.hasRegister&&state.hasPassage&&state.hasQuestions&&state.hasGrade&&errors.length===0;report.browsers[name]={pass,httpStatus:r&&r.status(),registration,...state,errors};fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();if(!pass)throw new Error(`${name} failed: ${JSON.stringify(report.browsers[name])}`)}
(async()=>{try{await run('chromium',chromium);await run('webkit',webkit);await run('iphone-webkit',webkit,{viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true,deviceScaleFactor:3});report.finalPass=Object.values(report.browsers).every(x=>x.pass);fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!report.finalPass)process.exit(1)}catch(e){report.error=String(e.stack||e);fs.writeFileSync('V11_BATCH15_BROWSER_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.error(e);process.exit(1)}})();
