window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 4-1']={
id:'V10-NH-G2-U4-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 4-1',level:'HOP',title:'Rules for My Homestay',
sentences:['I am on a homestay.','I am a guest in this house.','I ask my host for advice.','I have to follow a house rule.','I have to help at dinner.','I do not have to be perfect.','I am a member of the family now.','I ask a question about the rule.','My host and I talk about the homestay.','The advice is useful.','I want to follow the rule.','This homestay is a good experience.'],
fullTranslation:'「私はホームステイ中です。私はこの家の客です。ホストに助言を求めます。私は家の規則に従わなければなりません。夕食では手伝わなければなりません。完ぺきである必要はありません。今は家族の一員です。規則について質問します。ホストと私はホームステイについて話します。その助言は役に立ちます。私はその規則に従いたいです。このホームステイはよい経験です。」',
slashRows:[{en:'I am / on a homestay.',jp:'私は〜です / ホームステイ中'},{en:'I am / a guest / in this house.',jp:'私は〜です / 客 / この家の'},{en:'I ask / my host / for advice.',jp:'私は求めます / ホストに / 助言を'},{en:'I have to follow / a house rule.',jp:'私は従わなければなりません / 家の規則に'},{en:'I have to help / at dinner.',jp:'私は手伝わなければなりません / 夕食で'},{en:'I do not have to be / perfect.',jp:'私は〜である必要はありません / 完ぺき'},{en:'I am / a member / of the family / now.',jp:'私は〜です / 一員 / 家族の / 今'},{en:'I ask / a question / about the rule.',jp:'私はします / 質問を / 規則について'},{en:'My host and I / talk about / the homestay.',jp:'ホストと私は / 話します / ホームステイについて'},{en:'The advice is / useful.',jp:'その助言は〜です / 役に立つ'},{en:'I want to follow / the rule.',jp:'私は従いたいです / その規則に'},{en:'This homestay is / a good experience.',jp:'このホームステイは〜です / よい経験'}],
questions:[{prompt:'1. 話し手はこの家で何ですか。本文から英語で答えなさい。',answer:'a guest',evidence:'I am a guest in this house.',evidenceJp:'私はこの家の客です。',reason:'be動詞の後ろが a guest です。'},{prompt:'2. 誰に助言を求めますか。本文から英語で答えなさい。',answer:'my host',evidence:'I ask my host for advice.',evidenceJp:'ホストに助言を求めます。',reason:'ask の相手が my host です。'},{prompt:'3. 何に従わなければなりませんか。本文から英語で答えなさい。',answer:'a house rule',evidence:'I have to follow a house rule.',evidenceJp:'私は家の規則に従わなければなりません。',reason:'follow の目的語が a house rule です。'},{prompt:'4. 完ぺきである必要がありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I do not have to be perfect.',evidenceJp:'完ぺきである必要はありません。',reason:'do not have to とあるので No です。'},{prompt:'5. 今、話し手は何の一員ですか。本文から英語で答えなさい。',answer:'the family',evidence:'I am a member of the family now.',evidenceJp:'今は家族の一員です。',reason:'member of の後ろが the family です。'}],
allowedWords:[['have to ~ / host / don’t have to ~ / homestay / follow / guest / ask / advice / rule / perfect / member','Unit 4-1: v7 canonical Sheet IDs 1153-1163'],['house / help / dinner / family / question / talk about / useful / want to / good / experience','G1/Unit0-3 cumulative']],
auditNote:'最新v7正本Unit4 Part1（Sheet ID1153〜1163）を直接照合。have to / don’t have to / host / guest / homestay / follow / advice / rule / perfect / memberをホームステイ初日の規則確認に統合。Unit4-2以降のmust / should等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 4-2']={
id:'V10-NH-G2-U4-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 4-2',level:'HOP',title:'Saving Water at My Homestay',
sentences:['My homestay has a shower rule.','I must take a short shower.','I must save water.','I must take a shower by nine.','I must not take a long shower.','I mustn’t use water for a long time.','We also have a time limit.','I can ask my host about the limit.','I must follow this rule.','I do not have to take a shower in the morning.','My host and I talk about water.','Saving water is important.'],
fullTranslation:'「私のホームステイ先にはシャワーの規則があります。私は短いシャワーを浴びなければなりません。水を節約しなければなりません。9時までにシャワーを浴びなければなりません。長いシャワーを浴びてはいけません。長い時間、水を使ってはいけません。時間の制限もあります。制限についてホストにたずねることができます。この規則に従わなければなりません。朝にシャワーを浴びる必要はありません。ホストと私は水について話します。水を節約することは大切です。」',
slashRows:[{en:'My homestay has / a shower rule.',jp:'私のホームステイ先にはあります / シャワーの規則が'},{en:'I must take / a short shower.',jp:'私は浴びなければなりません / 短いシャワーを'},{en:'I must save / water.',jp:'私は節約しなければなりません / 水を'},{en:'I must take / a shower / by nine.',jp:'私は浴びなければなりません / シャワーを / 9時までに'},{en:'I must not take / a long shower.',jp:'私は浴びてはいけません / 長いシャワーを'},{en:'I mustn’t use / water / for a long time.',jp:'私は使ってはいけません / 水を / 長い時間'},{en:'We also have / a time limit.',jp:'私たちにはまたあります / 時間の制限が'},{en:'I can ask / my host / about the limit.',jp:'私はたずねることができます / ホストに / 制限について'},{en:'I must follow / this rule.',jp:'私は従わなければなりません / この規則に'},{en:'I do not have to take / a shower / in the morning.',jp:'私は浴びる必要はありません / シャワーを / 朝に'},{en:'My host and I / talk about / water.',jp:'ホストと私は / 話します / 水について'},{en:'Saving water is / important.',jp:'水を節約することは〜です / 大切'}],
questions:[{prompt:'1. 何を短くしなければなりませんか。本文から英語で答えなさい。',answer:'a shower',evidence:'I must take a short shower.',evidenceJp:'私は短いシャワーを浴びなければなりません。',reason:'take の目的語が a short shower です。'},{prompt:'2. 何を節約しなければなりませんか。本文から英語で答えなさい。',answer:'water',evidence:'I must save water.',evidenceJp:'水を節約しなければなりません。',reason:'save の目的語が water です。'},{prompt:'3. 何時までにシャワーを浴びますか。本文から英語で答えなさい。',answer:'by nine',evidence:'I must take a shower by nine.',evidenceJp:'9時までにシャワーを浴びなければなりません。',reason:'by nine が期限です。'},{prompt:'4. 長いシャワーを浴びてもよいですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I must not take a long shower.',evidenceJp:'長いシャワーを浴びてはいけません。',reason:'must not と禁止されています。'},{prompt:'5. 何についてホストにたずねることができますか。本文から英語で答えなさい。',answer:'the limit',evidence:'I can ask my host about the limit.',evidenceJp:'制限についてホストにたずねることができます。',reason:'about の後ろが the limit です。'}],
allowedWords:[['must ~ / also / must not ~ / save / mustn’t / shower / by ~ / limit','Unit 4-2: v7 canonical Sheet IDs 1164-1171'],['homestay / rule / take / short / water / long / time / can / ask / host / follow / don’t have to / morning / talk about / important','Unit4-1/G1 cumulative']],
auditNote:'最新v7正本Unit4 Part2（Sheet ID1164〜1171）を直接照合。must / must not / mustn’t / save / shower / by / limit / alsoを水の節約ルールに統合。Read and Thinkのfinish / should / carefully等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 4-3']={
id:'V10-NH-G2-U4-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 4-3',level:'HOP',title:'Dinner Manners at My Homestay',
sentences:['Before dinner, I listen to my host carefully.','I should wash my hands.','I should take off my hat.','At dinner, I use a plate.','I answer a question carefully.','I finish dinner with my host.','Nothing is difficult now.','I should listen to each other.','I think about the feeling of my host.','I want to help more in the future.','I feel like eating local food.','In the end, dinner is fun.','I learn an important homestay rule.'],
fullTranslation:'「夕食前、私はホストの話を注意深く聞きます。手を洗うべきです。帽子を脱ぐべきです。夕食では取り皿を使います。質問に注意深く答えます。ホストと夕食を終えます。今は何も難しくありません。おたがいの話を聞くべきです。ホストの気持ちについて考えます。将来はもっと手伝いたいです。地元の食べ物を食べたい気がします。結局、夕食は楽しいです。私は大切なホームステイの規則を学びます。」',
slashRows:[{en:'Before dinner, / I listen to / my host / carefully.',jp:'夕食前 / 私は聞きます / ホストの話を / 注意深く'},{en:'I should wash / my hands.',jp:'私は洗うべきです / 手を'},{en:'I should take off / my hat.',jp:'私は脱ぐべきです / 帽子を'},{en:'At dinner, / I use / a plate.',jp:'夕食では / 私は使います / 取り皿を'},{en:'I answer / a question / carefully.',jp:'私は答えます / 質問に / 注意深く'},{en:'I finish / dinner / with my host.',jp:'私は終えます / 夕食を / ホストと'},{en:'Nothing is / difficult / now.',jp:'何も〜ではありません / 難しい / 今'},{en:'I should listen to / each other.',jp:'私は聞くべきです / おたがいに'},{en:'I think about / the feeling / of my host.',jp:'私は考えます / 気持ちについて / ホストの'},{en:'I want to help / more / in the future.',jp:'私は手伝いたいです / もっと / 将来に'},{en:'I feel like eating / local food.',jp:'私は食べたい気がします / 地元の食べ物を'},{en:'In the end, / dinner is / fun.',jp:'結局 / 夕食は〜です / 楽しい'},{en:'I learn / an important homestay rule.',jp:'私は学びます / 大切なホームステイの規則を'}],
questions:[{prompt:'1. 夕食前に誰の話を注意深く聞きますか。本文から英語で答えなさい。',answer:'my host',evidence:'Before dinner, I listen to my host carefully.',evidenceJp:'夕食前、私はホストの話を注意深く聞きます。',reason:'listen to の目的語が my host です。'},{prompt:'2. 何を脱ぐべきですか。本文から英語で答えなさい。',answer:'my hat',evidence:'I should take off my hat.',evidenceJp:'帽子を脱ぐべきです。',reason:'take off の目的語が my hat です。'},{prompt:'3. 夕食で何を使いますか。本文から英語で答えなさい。',answer:'a plate',evidence:'At dinner, I use a plate.',evidenceJp:'夕食では取り皿を使います。',reason:'use の目的語が a plate です。'},{prompt:'4. 将来もっと何をしたいですか。本文から英語で答えなさい。',answer:'help',evidence:'I want to help more in the future.',evidenceJp:'将来はもっと手伝いたいです。',reason:'want to の後ろが help です。'},{prompt:'5. 最後に何を学びますか。本文から英語で答えなさい。',answer:'an important homestay rule',evidence:'I learn an important homestay rule.',evidenceJp:'私は大切なホームステイの規則を学びます。',reason:'learn の目的語が an important homestay rule です。'}],
allowedWords:[['finish / answer / much / carefully / should / take off / nothing ~ / keep ~ing / hurt / in the future / plate / feel like ~ing / feeling / each other / couple / couldn’t / elderly / explain / listen to ~ / enter / kept / end / get / in the end / feel-felt','Unit 4-3,4 shared v7 canonical Sheet IDs 1172-1196'],['before dinner / host / wash / hands / hat / dinner / use / question / difficult / now / think about / want to / help / more / local food / fun / learn / important / homestay / rule','G1/Unit0-4 cumulative']],
auditNote:'最新v7正本ではUnit4 Read and Think1,2が共通語彙プール（Sheet ID1172〜1196）。Unit4-3はfinish / answer / carefully / should / take off / nothing / plate / feeling / each other / in the future / feel like ~ing / in the end / listen toを食事マナーの1場面に統合。Unit4-4と同一プールを共有する。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 4-4']={
id:'V10-NH-G2-U4-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 4-4',level:'HOP',title:'An Elderly Couple at My Homestay',
sentences:['During my homestay, I meet an elderly couple.','At first, I couldn’t understand one rule.','The couple explain the rule to me.','I listen to the couple carefully.','We listen to each other.','I enter the room with my host.','I felt nervous at first.','The couple kept the room clean.','Nothing is difficult now.','At the end, I understand the rule.','In the end, I feel good.','The couple and I smile.','I want to remember this feeling in the future.'],
fullTranslation:'「ホームステイ中、私は年配の夫婦に会います。最初、私は1つの規則を理解できませんでした。その夫婦が私に規則を説明します。私はその夫婦の話を注意深く聞きます。私たちはおたがいの話を聞きます。ホストといっしょに部屋に入ります。最初、私は緊張していました。その夫婦は部屋をきれいに保っていました。今は何も難しくありません。最後には、私はその規則を理解します。結局、よい気持ちになります。その夫婦と私はほほえみます。私は将来この気持ちを覚えていたいです。」',
slashRows:[{en:'During my homestay, / I meet / an elderly couple.',jp:'ホームステイ中 / 私は会います / 年配の夫婦に'},{en:'At first, / I couldn’t understand / one rule.',jp:'最初 / 私は理解できませんでした / 1つの規則を'},{en:'The couple explain / the rule / to me.',jp:'その夫婦は説明します / 規則を / 私に'},{en:'I listen to / the couple / carefully.',jp:'私は聞きます / その夫婦の話を / 注意深く'},{en:'We listen to / each other.',jp:'私たちは聞きます / おたがいに'},{en:'I enter / the room / with my host.',jp:'私は入ります / 部屋に / ホストといっしょに'},{en:'I felt / nervous / at first.',jp:'私は感じました / 緊張して / 最初'},{en:'The couple kept / the room / clean.',jp:'その夫婦は保ちました / 部屋を / きれいに'},{en:'Nothing is / difficult / now.',jp:'何も〜ではありません / 難しい / 今'},{en:'At the end, / I understand / the rule.',jp:'最後には / 私は理解します / その規則を'},{en:'In the end, / I feel / good.',jp:'結局 / 私は感じます / よい状態を'},{en:'The couple and I / smile.',jp:'その夫婦と私は / ほほえみます'},{en:'I want to remember / this feeling / in the future.',jp:'私は覚えていたいです / この気持ちを / 将来に'}],
questions:[{prompt:'1. 誰に会いますか。本文から英語で答えなさい。',answer:'an elderly couple',evidence:'During my homestay, I meet an elderly couple.',evidenceJp:'ホームステイ中、私は年配の夫婦に会います。',reason:'meet の目的語が an elderly couple です。'},{prompt:'2. 最初、何を理解できませんでしたか。本文から英語で答えなさい。',answer:'one rule',evidence:'At first, I couldn’t understand one rule.',evidenceJp:'最初、私は1つの規則を理解できませんでした。',reason:'understand の目的語が one rule です。'},{prompt:'3. 誰が規則を説明しますか。本文から英語で答えなさい。',answer:'The couple',evidence:'The couple explain the rule to me.',evidenceJp:'その夫婦が私に規則を説明します。',reason:'主語 The couple が説明する人です。'},{prompt:'4. 最初、どんな気持ちでしたか。本文から英語で1語抜き出しなさい。',answer:'nervous',evidence:'I felt nervous at first.',evidenceJp:'最初、私は緊張していました。',reason:'nervous が気持ちです。'},{prompt:'5. 将来、何を覚えていたいですか。本文から英語で答えなさい。',answer:'this feeling',evidence:'I want to remember this feeling in the future.',evidenceJp:'私は将来この気持ちを覚えていたいです。',reason:'remember の目的語が this feeling です。'}],
allowedWords:[['finish / answer / much / carefully / should / take off / nothing ~ / keep ~ing / hurt / in the future / plate / feel like ~ing / feeling / each other / couple / couldn’t / elderly / explain / listen to ~ / enter / kept / end / get / in the end / feel-felt','Unit 4-3,4 shared v7 canonical Sheet IDs 1172-1196'],['homestay / meet / understand / rule / room / host / nervous / clean / difficult / now / good / smile / want to / remember','G1/Unit0-4 cumulative']],
auditNote:'Unit4-4も最新v7共通Read and Thinkプール（1172〜1196）を使用。elderly / couple / couldn’t / explain / listen to / each other / enter / felt / kept / nothing / end / in the end / feeling / in the futureを、年配の夫婦とのホームステイ交流にまとめた。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};