window.V10_PASSAGES=window.V10_PASSAGES||{};
window.V10_PASSAGES['PROGRAM 2-1']={
id:'V10-SS-G1-P2-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-1',level:'HOP',title:'My Bicycle After School',
sentences:['After school, I ride my bicycle.','I ride in my town.','My town is beautiful.','I sometimes ride with my friend.','My friend and I walk, too.','I like my bicycle very much.','I go home after school.','At home, I clean my bicycle.','I read at home.','I sometimes watch tennis at home.','I don’t watch tennis after school.','I like my town, too.','I like my bicycle and my town.'],
fullTranslation:'「放課後、私は自転車に乗ります。町の中を走ります。私の町は美しいです。ときどき友達といっしょに自転車に乗ります。友達と私は歩くこともあります。私は自分の自転車がとても好きです。放課後は家に帰ります。家では自転車をきれいにします。家で本を読みます。ときどき家でテニスを見ます。放課後にはテニスを見ません。自分の町も好きです。自転車も町も好きです。」',
slashRows:[{en:'After school, / I ride / my bicycle.',jp:'放課後 / 私は乗ります / 私の自転車に'},{en:'I ride / in my town.',jp:'私は乗ります / 私の町の中で'},{en:'My town is / beautiful.',jp:'私の町は〜です / 美しい'},{en:'I sometimes ride / with my friend.',jp:'私はときどき乗ります / 私の友達といっしょに'},{en:'My friend and I / walk, too.',jp:'私の友達と私は / 歩くこともあります'},{en:'I like / my bicycle / very much.',jp:'私は好きです / 私の自転車が / とても'},{en:'I go home / after school.',jp:'私は家に帰ります / 放課後に'},{en:'At home, / I clean / my bicycle.',jp:'家で / 私はきれいにします / 私の自転車を'},{en:'I read / at home.',jp:'私は読みます / 家で'},{en:'I sometimes watch / tennis / at home.',jp:'私はときどき見ます / テニスを / 家で'},{en:'I don’t watch / tennis / after school.',jp:'私は見ません / テニスを / 放課後に'},{en:'I like / my town, too.',jp:'私は好きです / 私の町も'},{en:'I like / my bicycle and my town.',jp:'私は好きです / 私の自転車と町が'}],
questions:[{prompt:'1. 話し手は放課後、何に乗りますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'After school, I ride my bicycle.',evidenceJp:'放課後、私は自転車に乗ります。',reason:'ride の目的語 my bicycle が乗るものです。'},{prompt:'2. 話し手の町はどのようだと書かれていますか。本文から英語で1語抜き出しなさい。',answer:'beautiful',evidence:'My town is beautiful.',evidenceJp:'私の町は美しいです。',reason:'beautiful が町の様子を表しています。'},{prompt:'3. 話し手はときどき誰と自転車に乗りますか。本文から英語で答えなさい。',answer:'my friend',evidence:'I sometimes ride with my friend.',evidenceJp:'私はときどき友達といっしょに自転車に乗ります。',reason:'with の後ろの my friend がいっしょに乗る相手です。'},{prompt:'4. 家で何をきれいにしますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'At home, I clean my bicycle.',evidenceJp:'家では自転車をきれいにします。',reason:'clean の目的語 my bicycle がきれいにするものです。'},{prompt:'5. 話し手は放課後にテニスを見ますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I don’t watch tennis after school.',evidenceJp:'私は放課後にはテニスを見ません。',reason:'don’t watch と否定しているので No です。'}],
allowedWords:[['grow / use / after / town / bicycle / flower / walk / ride / watch / read / clean / beautiful / many / sometimes / don’t / at home / very much / after school','PROGRAM 2-1: id185-202'],['friend','cumulative'],['tennis','Get Ready cumulative'],['go / home / in / with / my / it / I / is / like / and','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-1をid185〜202まで照合し、id203からPROGRAM 2-2へ切り替わることを確認。自転車での放課後と帰宅後という1日の流れに限定。初稿に混入した三単現likesは人手監査で削除し、確認済みの原形だけへ修正した。grow / use / flower / many等は新出語消化だけのためには入れていない。未確認の過去形・進行形は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 2-2']={
id:'V10-SS-G1-P2-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-2',level:'HOP',title:'My Weekend Routine',
sentences:['On the weekend, I study at home.','I study math before dinner.','I like math, but I like science, too.','After dinner, I read at home.','I sometimes watch tennis.','I ride my bicycle on the weekend.','I ride with my friend.','We like our town.','Our town is beautiful.','Before dinner, I clean my bicycle.','After dinner, I study Japanese.','I like the weekend very much.'],
fullTranslation:'「週末は家で勉強します。夕食前に数学を勉強します。数学が好きですが、理科も好きです。夕食後は家で本を読みます。ときどきテニスを見ます。週末には自転車に乗ります。友達といっしょに自転車に乗ります。私たちは自分たちの町が好きです。私たちの町は美しいです。夕食前には自転車をきれいにします。夕食後には国語を勉強します。私は週末がとても好きです。」',
slashRows:[{en:'On the weekend, / I study / at home.',jp:'週末に / 私は勉強します / 家で'},{en:'I study / math / before dinner.',jp:'私は勉強します / 数学を / 夕食前に'},{en:'I like math, / but I like science, too.',jp:'私は数学が好きです / しかし理科も好きです'},{en:'After dinner, / I read / at home.',jp:'夕食後 / 私は読みます / 家で'},{en:'I sometimes watch / tennis.',jp:'私はときどき見ます / テニスを'},{en:'I ride / my bicycle / on the weekend.',jp:'私は乗ります / 私の自転車に / 週末に'},{en:'I ride / with my friend.',jp:'私は乗ります / 私の友達といっしょに'},{en:'We like / our town.',jp:'私たちは好きです / 私たちの町が'},{en:'Our town is / beautiful.',jp:'私たちの町は〜です / 美しい'},{en:'Before dinner, / I clean / my bicycle.',jp:'夕食前に / 私はきれいにします / 私の自転車を'},{en:'After dinner, / I study / Japanese.',jp:'夕食後に / 私は勉強します / 国語を'},{en:'I like / the weekend / very much.',jp:'私は好きです / 週末が / とても'}],
questions:[{prompt:'1. 話し手は週末、どこで勉強しますか。本文から英語で答えなさい。',answer:'at home',evidence:'On the weekend, I study at home.',evidenceJp:'週末は家で勉強します。',reason:'at home が勉強する場所を表しています。'},{prompt:'2. 話し手は夕食前に何を勉強しますか。本文から英語で答えなさい。',answer:'math',evidence:'I study math before dinner.',evidenceJp:'夕食前に数学を勉強します。',reason:'before dinner の文で study の目的語が math です。'},{prompt:'3. 話し手は数学だけが好きですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I like math, but I like science, too.',evidenceJp:'数学が好きですが、理科も好きです。',reason:'science, too とあるため、数学だけではありません。'},{prompt:'4. 夕食前に何をきれいにしますか。本文から英語で答えなさい。',answer:'my bicycle',evidence:'Before dinner, I clean my bicycle.',evidenceJp:'夕食前には自転車をきれいにします。',reason:'clean の目的語 my bicycle が対象です。'},{prompt:'5. 話し手は週末が好きですか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I like the weekend very much.',evidenceJp:'私は週末がとても好きです。',reason:'like ... very much と強く好んでいることが示されています。'}],
allowedWords:[['weekend / but / before / dinner / study / on','PROGRAM 2-2: id203-208'],['after / bicycle / ride / read / watch / clean / beautiful / sometimes / at home / very much','PROGRAM 2-1 cumulative'],['math / science / Japanese','PROGRAM 1-3 cumulative'],['friend / we / our / with / I / like / the','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-2をid203〜208まで照合し、id209からPROGRAM 2-3へ切り替わることを確認。weekend / before dinner / study / butを、週末の学習と自転車の手入れという1日の流れにまとめた。初稿に混入した三単現ridesは人手監査でI rideへ修正し、未確認の活用形を残していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 2-3']={
id:'V10-SS-G1-P2-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 2-3',level:'HOP',title:'Drawing During the Break',
sentences:['Look at this picture.','Wow!','I draw this picture in my notebook.','Are you an artist?','No, I’m not.','I like this picture.','I draw at home, too.','I have a question.','Sure.','This pencil is for you.','Thank you.','I have two.','We can draw during the break.','Let’s draw tomorrow.'],
fullTranslation:'「この絵を見て。」「わあ！」「私はこの絵をノートにかきます。」「あなたはアーティストですか。」「いいえ、違います。」「私はこの絵が好きです。」「家でも絵をかきます。」「質問があります。」「もちろん。」「この鉛筆はあなた用です。」「ありがとう。」「私は2本持っています。」「休み時間に絵をかくことができます。」「明日、絵をかこう。」',
slashRows:[{en:'Look at / this picture.',jp:'見てください / この絵を'},{en:'Wow!',jp:'わあ！'},{en:'I draw / this picture / in my notebook.',jp:'私はかきます / この絵を / 私のノートに'},{en:'Are you / an artist?',jp:'あなたは〜ですか / アーティスト'},{en:'No, / I’m not.',jp:'いいえ / 違います'},{en:'I like / this picture.',jp:'私は好きです / この絵が'},{en:'I draw / at home, too.',jp:'私はかきます / 家でも'},{en:'I have / a question.',jp:'私は持っています / 1つの質問を'},{en:'Sure.',jp:'もちろん。'},{en:'This pencil is / for you.',jp:'この鉛筆は〜です / あなた用'},{en:'Thank you.',jp:'ありがとう。'},{en:'I have / two.',jp:'私は持っています / 2本'},{en:'We can draw / during the break.',jp:'私たちはかくことができます / 休憩の間に'},{en:'Let’s draw / tomorrow.',jp:'かきましょう / 明日'}],
questions:[{prompt:'1. 話し手は絵をどこにかきますか。本文から英語で答えなさい。',answer:'my notebook',evidence:'I draw this picture in my notebook.',evidenceJp:'私はこの絵をノートにかきます。',reason:'in の後ろの my notebook がかく場所を示しています。'},{prompt:'2. 話し手はアーティストですか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'Are you an artist? / No, I’m not.',evidenceJp:'あなたはアーティストですか。／いいえ、違います。',reason:'質問に No, I’m not. と答えています。'},{prompt:'3. 話し手は質問がありますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I have a question.',evidenceJp:'私は質問があります。',reason:'I have a question. と明示されています。'},{prompt:'4. 相手に渡しているものは何ですか。本文から英語で答えなさい。',answer:'this pencil',evidence:'This pencil is for you.',evidenceJp:'この鉛筆はあなた用です。',reason:'for you とされている主語が This pencil です。'},{prompt:'5. いついっしょに絵をかこうと言っていますか。本文から英語で答えなさい。',answer:'tomorrow',evidence:'Let’s draw tomorrow.',evidenceJp:'明日、絵をかきましょう。',reason:'tomorrow が提案した時を表しています。'}],
allowedWords:[['flip / wow / picture / notebook / artist / draw / look / look at ～ / question / break / sure / tomorrow / during / for / any / pencil / two / how / How many ～?','PROGRAM 2-3: id209-227'],['this / I’m','PROGRAM 1 cumulative'],['at home','PROGRAM 2-1 cumulative'],['have / can / we / Thank you. / Let’s / like / in / my / are / you / no / an / a / is','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 2-3をid209〜227まで照合し、id228からアクションコーナーへ切り替わることを確認。picture / notebook / artist / draw / look at / question / break / pencil / two / tomorrow / duringを、絵を見せて休み時間と翌日の活動につなげる1場面にまとめた。How many ～?は複数形生成を伴うため、新出語消化だけを目的に本文へ無理に入れていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 3-1']={
id:'V10-SS-G1-P3-1-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 3-1',level:'HOP',title:'My Family in Winter',
sentences:['This is my family.','That is my brother.','He can ski well.','I can ski, too.','We ski in winter.','We don’t ski in summer.','My father can ski.','My mother can’t ski.','My mother can dance.','She can dance well.','My grandfather can dance, too.','My grandmother can dance, too.','We like winter.','Winter is great.'],
fullTranslation:'「これは私の家族です。あれは私の兄（弟）です。兄（弟）はスキーが上手にできます。私もスキーができます。私たちは冬にスキーをします。夏にはスキーをしません。父もスキーができます。母はスキーができません。母は踊ることができます。母は上手に踊れます。祖父も踊れます。祖母も踊れます。私たちは冬が好きです。冬はすばらしいです。」',
slashRows:[{en:'This is / my family.',jp:'これは〜です / 私の家族'},{en:'That is / my brother.',jp:'あれは〜です / 私の兄（弟）'},{en:'He can ski / well.',jp:'彼はスキーができます / 上手に'},{en:'I can ski, / too.',jp:'私もスキーができます / 〜も'},{en:'We ski / in winter.',jp:'私たちはスキーをします / 冬に'},{en:'We don’t ski / in summer.',jp:'私たちはスキーをしません / 夏に'},{en:'My father can ski.',jp:'私の父はスキーができます'},{en:'My mother can’t ski.',jp:'私の母はスキーができません'},{en:'My mother can dance.',jp:'私の母は踊ることができます'},{en:'She can dance / well.',jp:'彼女は踊れます / 上手に'},{en:'My grandfather can dance, / too.',jp:'私の祖父も踊れます / 〜も'},{en:'My grandmother can dance, / too.',jp:'私の祖母も踊れます / 〜も'},{en:'We like / winter.',jp:'私たちは好きです / 冬が'},{en:'Winter is / great.',jp:'冬は〜です / すばらしい'}],
questions:[{prompt:'1. `That` が指しているのは誰ですか。本文から英語で答えなさい。',answer:'my brother',evidence:'That is my brother.',evidenceJp:'あれは私の兄（弟）です。',reason:'That is の後ろに my brother と示されています。'},{prompt:'2. 兄（弟）はスキーができますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'He can ski well.',evidenceJp:'彼はスキーが上手にできます。',reason:'can ski とあるので Yes です。'},{prompt:'3. 家族はいつスキーをしますか。本文から英語で答えなさい。',answer:'in winter',evidence:'We ski in winter.',evidenceJp:'私たちは冬にスキーをします。',reason:'in winter がスキーをする季節を表しています。'},{prompt:'4. 母はスキーができますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'My mother can’t ski.',evidenceJp:'私の母はスキーができません。',reason:'can’t ski と否定されているので No です。'},{prompt:'5. 母ができることは何ですか。本文から英語で答えなさい。',answer:'dance',evidence:'My mother can dance.',evidenceJp:'私の母は踊ることができます。',reason:'can の後ろの dance が母のできることです。'}],
allowedWords:[['uncle / aunt / cousin / roll / kilometer / know / ski / then / summer / winter / brother / father / mother / grandfather / grandmother / that / dance / delicious / well / that’s / can’t','PROGRAM 3-1: id249-269'],['family / he / she','cumulative / elementary'],['can','cumulative'],['don’t','PROGRAM 2-1 cumulative'],['too / great','cumulative'],['this / is / my / I / we / in / like','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 3-1をid249〜269まで照合し、id270からPROGRAM 3-2へ切り替わることを確認。can / can’t + 原形を中心に家族の得意なことを1場面で構成し、三単現-sを使っていない。delicious / roll / kilometer / know / then等は新出語消化のためだけには詰め込まない。wellは正本語義「じょうずに」でのみ使用。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 3-2']={
id:'V10-SS-G1-P3-2-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 3-2',level:'HOP',title:'What Can We Do?',
sentences:['I can speak French.','My friend can play the guitar.','Can you play the guitar?','Yes, I can.','Can you skate?','Yes, I can.','I can skate fast.','Can you do a magic trick?','Yes, I can.','Great!','We can practice after school.','I like the guitar.','My friend and I can skate together.','Sounds great.'],
fullTranslation:'「私はフランス語を話せます。友達はギターを弾けます。」「あなたはギターを弾けますか。」「はい、弾けます。」「スケートはできますか。」「はい、できます。」「私は速くスケートができます。」「手品ができますか。」「はい、できます。」「すごい！」「放課後に練習できます。」「私はギターが好きです。」「友達と私はいっしょにスケートができます。」「楽しそうですね。」',
slashRows:[{en:'I can speak / French.',jp:'私は話せます / フランス語を'},{en:'My friend can play / the guitar.',jp:'私の友達は演奏できます / ギターを'},{en:'Can you play / the guitar?',jp:'あなたは演奏できますか / ギターを'},{en:'Yes, / I can.',jp:'はい / できます'},{en:'Can you skate?',jp:'あなたはスケートができますか'},{en:'Yes, / I can.',jp:'はい / できます'},{en:'I can skate / fast.',jp:'私はスケートができます / 速く'},{en:'Can you do / a magic trick?',jp:'あなたはできますか / 手品を'},{en:'Yes, / I can.',jp:'はい / できます'},{en:'Great!',jp:'すごい！'},{en:'We can practice / after school.',jp:'私たちは練習できます / 放課後に'},{en:'I like / the guitar.',jp:'私は好きです / ギターが'},{en:'My friend and I / can skate / together.',jp:'私の友達と私は / スケートができます / いっしょに'},{en:'Sounds / great.',jp:'〜そうですね / 楽しそう'}],
questions:[{prompt:'1. 話し手は何語を話せますか。本文から英語で答えなさい。',answer:'French',evidence:'I can speak French.',evidenceJp:'私はフランス語を話せます。',reason:'speak の目的語 French が話せる言語です。'},{prompt:'2. 友達は何を演奏できますか。本文から英語で答えなさい。',answer:'the guitar',evidence:'My friend can play the guitar.',evidenceJp:'友達はギターを弾けます。',reason:'play の目的語 the guitar が演奏できる楽器です。'},{prompt:'3. 話し手は速くスケートができますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I can skate fast.',evidenceJp:'私は速くスケートができます。',reason:'can skate fast とあるので Yes です。'},{prompt:'4. 話し手は手品ができますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Can you do a magic trick? / Yes, I can.',evidenceJp:'手品ができますか。／はい、できます。',reason:'Can you ...? に Yes, I can. と答えています。'},{prompt:'5. いつ練習できますか。本文から英語で答えなさい。',answer:'after school',evidence:'We can practice after school.',evidenceJp:'放課後に練習できます。',reason:'after school が練習する時を表しています。'}],
allowedWords:[['French / trick / magic / guitar / curry / soup / map / skate / fast','PROGRAM 3-2: id270-278'],['speak','Action Corner cumulative'],['play / friend / practice / after school / together / Sounds ... / great','cumulative'],['can / do / you / yes / I / we / a / the / like / my / and','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 3-2をid270〜278まで照合し、id279からPROGRAM 3-3へ切り替わることを確認。French / guitar / skate / fast / magic trickを「できること」の会話に統合し、can + 原形だけで構成。curry / soup / mapはこの場面に混ぜると不自然なので未使用。三単現・過去形・進行形は生成していない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES['PROGRAM 3-3']={
id:'V10-SS-G1-P3-3-001',textbook:'サンシャイン',grade:'1',section:'PROGRAM 3-3',level:'HOP',title:'A Rescue Robot',
sentences:['This is a rescue robot.','The robot is in our show.','I am so excited.','It can carry a heavy thing.','It can find people.','It can help people.','It can fly, too.','Can it carry water?','Yes, it can.','Can it help people in a tree?','Yes, it can.','It is wonderful.','Good luck!','Our show is great.'],
fullTranslation:'「これは救助ロボットです。そのロボットは私たちのショーに出ます。私はとてもわくわくしています。そのロボットは重いものを運べます。人を見つけられます。人を助けられます。飛ぶこともできます。」「水を運べますか。」「はい、運べます。」「木にいる人を助けられますか。」「はい、助けられます。」「すばらしいです。」「がんばって！」「私たちのショーはすばらしいです。」',
slashRows:[{en:'This is / a rescue robot.',jp:'これは〜です / 救助ロボット'},{en:'The robot is / in our show.',jp:'そのロボットはいます / 私たちのショーに'},{en:'I am / so excited.',jp:'私は〜です / とてもわくわくしている'},{en:'It can carry / a heavy thing.',jp:'それは運べます / 重いものを'},{en:'It can find / people.',jp:'それは見つけられます / 人々を'},{en:'It can help / people.',jp:'それは助けられます / 人々を'},{en:'It can fly, / too.',jp:'それは飛べます / 〜も'},{en:'Can it carry / water?',jp:'それは運べますか / 水を'},{en:'Yes, / it can.',jp:'はい / 運べます'},{en:'Can it help / people / in a tree?',jp:'それは助けられますか / 人々を / 木にいる'},{en:'Yes, / it can.',jp:'はい / 助けられます'},{en:'It is / wonderful.',jp:'それは〜です / すばらしい'},{en:'Good luck!',jp:'がんばって！'},{en:'Our show is / great.',jp:'私たちのショーは〜です / すばらしい'}],
questions:[{prompt:'1. 最初に示されているものは何ですか。本文から英語で答えなさい。',answer:'a rescue robot',evidence:'This is a rescue robot.',evidenceJp:'これは救助ロボットです。',reason:'最初の文で a rescue robot と示されています。'},{prompt:'2. ロボットは重いものを運べますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'It can carry a heavy thing.',evidenceJp:'そのロボットは重いものを運べます。',reason:'can carry とあるので Yes です。'},{prompt:'3. ロボットは誰を見つけられますか。本文から英語で答えなさい。',answer:'people',evidence:'It can find people.',evidenceJp:'そのロボットは人々を見つけられます。',reason:'find の目的語 people が見つけられる対象です。'},{prompt:'4. ロボットは水を運べますか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'Can it carry water? / Yes, it can.',evidenceJp:'水を運べますか。／はい、運べます。',reason:'Can it ...? に Yes, it can. と答えています。'},{prompt:'5. ロボットについてどのようだと言っていますか。本文から英語で1語抜き出しなさい。',answer:'wonderful',evidence:'It is wonderful.',evidenceJp:'それはすばらしいです。',reason:'wonderful がロボットへの評価を表しています。'}],
allowedWords:[['show / talent / choose / perform / excited / OK / wonderful / so / Good luck! / internet / our / often / thing / robot / rescue / carry / find / heavy / water / tree / people / help / fly / with','PROGRAM 3-3: id279-302'],['can','cumulative'],['too / great','cumulative'],['this / is / a / the / in / I / am / it / yes','cumulative / elementary']],
auditNote:'v9内蔵VOCABでPROGRAM 3-3をid279〜302まで照合し、id303からStep 2 / Our Project 1へ切り替わることを確認。rescue robotを中心にcarry / find / help / fly / heavy / water / tree / peopleを1場面へ統合。すべてcan + 原形で処理し、三単現-sは生成していない。choose / perform / internet / often等は新出語消化だけのためには入れていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};