window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 8-1']={
 id:'V10-SS-G2-P8-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 8-1',level:'HOP',title:'A Recycled Notebook for Peace',
 sentences:['Today, we visit a stationery store.','I see a notebook made from recycled paper.','The notebook is made from recycled paper.','A short message is written on the first page.','The message is, “A hope for lasting peace.”','The notebook is sold at this store.','I see a red line on the notebook.','“I did not know recycled stationery was sold here.”','“Me neither.”','We look at an email about the notebook.','The email was written by a student.','The email is about peace from the heart.','I think this is a good idea.','I want lasting peace, too.'],
 fullTranslation:'「今日、私たちは文房具店を訪れます。私は再利用された紙で作られたノートを見ます。そのノートは再利用された紙で作られています。最初のページには短いメッセージが書かれています。そのメッセージは『長く続く平和への願い』です。そのノートはこの店で売られています。私はノートに赤い線を見ます。『再利用された文房具がここで売られているとは知らなかった。』『私も知らなかった。』私たちはそのノートについてのEメールを見ます。そのEメールはある生徒によって書かれました。そのEメールは心からの平和について書かれています。私はこれはよい考えだと思います。私も長く続く平和を願っています。」',
 slashRows:[{en:'Today, / we visit / a stationery store.',jp:'今日 / 私たちは訪れます / 文房具店を'},{en:'I see / a notebook / made from recycled paper.',jp:'私は見ます / 1冊のノートを / 再利用された紙で作られた'},{en:'The notebook is made / from recycled paper.',jp:'そのノートは作られています / 再利用された紙から'},{en:'A short message is written / on the first page.',jp:'短いメッセージが書かれています / 最初のページに'},{en:'The message is, / “A hope for lasting peace.”',jp:'そのメッセージは〜です / 「長く続く平和への願い」'},{en:'The notebook is sold / at this store.',jp:'そのノートは売られています / この店で'},{en:'I see / a red line / on the notebook.',jp:'私は見ます / 赤い線を / そのノートに'},{en:'“I did not know / recycled stationery was sold here.”',jp:'「私は知らなかった / 再利用された文房具がここで売られているとは」'},{en:'“Me neither.”',jp:'「私も知らなかった。」'},{en:'We look at / an email / about the notebook.',jp:'私たちは見ます / 1通のEメールを / そのノートについての'},{en:'The email was written / by a student.',jp:'そのEメールは書かれました / ある生徒によって'},{en:'The email is / about peace / from the heart.',jp:'そのEメールは〜です / 平和についての / 心からの'},{en:'I think / this is / a good idea.',jp:'私は思います / これは〜だと / よい考え'},{en:'I want / lasting peace, too.',jp:'私は望みます / 長く続く平和を / 私も'}],
 questions:[{prompt:'1. どこを訪れますか。本文から英語で答えなさい。',answer:'a stationery store',evidence:'Today, we visit a stationery store.',evidenceJp:'今日、私たちは文房具店を訪れます。',reason:'visit の目的語が a stationery store です。'},{prompt:'2. ノートは何から作られていますか。本文から英語で答えなさい。',answer:'recycled paper',evidence:'The notebook is made from recycled paper.',evidenceJp:'そのノートは再利用された紙で作られています。',reason:'is made from の後ろが recycled paper です。'},{prompt:'3. 最初のページには何が書かれていますか。本文から英語で答えなさい。',answer:'a short message',evidence:'A short message is written on the first page.',evidenceJp:'最初のページには短いメッセージが書かれています。',reason:'主語 A short message が書かれているものです。'},{prompt:'4. ノートはどこで売られていますか。本文から英語で答えなさい。',answer:'at this store',evidence:'The notebook is sold at this store.',evidenceJp:'そのノートはこの店で売られています。',reason:'at this store が販売場所を表しています。'},{prompt:'5. Eメールは誰によって書かれましたか。本文から英語で答えなさい。',answer:'a student',evidence:'The email was written by a student.',evidenceJp:'そのEメールはある生徒によって書かれました。',reason:'by の後ろの a student が書いた人です。'}],
 allowedWords:[['make-made-made / store / break-broke-broken / stationery / write-wrote-written / paint / see-saw-seen / line / sell-sold-sold / email / take-took-taken / hope / build-built-built / recycled / kitchen / lasting / draw / Absolutely. / heart / Me neither.','PROGRAM 8-1: v7 canonical Sheet IDs 3340-3359'],['notebook / paper / short / message / first / page / red / know / here / student / peace / today / visit / good / idea / want / too','G1/G2 cumulative']],
 auditNote:'最新v7単語マスターの単元索引でSunshine中2 PROGRAM 8は3本文構成であることを確認。8-1はSheet ID3340〜3359を直接照合し、正本に明示されたmade / written / sold / recycled等の形だけで受動表現を構成した。書き込み後の人手監査でvisits / says / writes等の自動活用を削除し、未登録活用形を残していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 8-2']={
 id:'V10-SS-G2-P8-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 8-2',level:'HOP',title:'A Monument for Peace',
 sentences:['Today, we visit a peace monument.','The monument is known to many people.','It was built for peace.','We learn about a victim of the atomic bomb.','The story is so sad that we are quiet.','A tourist is near the monument.','We hear a question about peace.','We hear an answer from our guide.','We renew our hope for peace.','I look at the monument again.','I think about the victim.','My friend is quiet, too.','We want peace for everyone.','We want to learn more about the monument.'],
 fullTranslation:'「今日、私たちは平和の記念碑を訪れます。その記念碑は多くの人に知られています。それは平和のために建てられました。私たちは原子爆弾の犠牲者について学びます。その話はとても悲しいので、私たちは静かになります。1人の観光客が記念碑の近くにいます。私たちは平和についての質問を耳にします。案内の人から答えを聞きます。私たちは平和への願いを新たにします。私はもう一度記念碑を見ます。その犠牲者について考えます。友達も静かです。私たちはすべての人のための平和を望みます。私たちはその記念碑についてもっと学びたいです。」',
 slashRows:[{en:'Today, / we visit / a peace monument.',jp:'今日 / 私たちは訪れます / 平和の記念碑を'},{en:'The monument is known / to many people.',jp:'その記念碑は知られています / 多くの人に'},{en:'It was built / for peace.',jp:'それは建てられました / 平和のために'},{en:'We learn about / a victim / of the atomic bomb.',jp:'私たちは学びます / 1人の犠牲者について / 原子爆弾の'},{en:'The story is / so sad that / we are quiet.',jp:'その話は〜です / とても悲しいので / 私たちは静かです'},{en:'A tourist is / near the monument.',jp:'1人の観光客がいます / 記念碑の近くに'},{en:'We hear / a question / about peace.',jp:'私たちは聞きます / 1つの質問を / 平和について'},{en:'We hear / an answer / from our guide.',jp:'私たちは聞きます / 1つの答えを / 私たちの案内の人から'},{en:'We renew / our hope / for peace.',jp:'私たちは新たにします / 私たちの願いを / 平和への'},{en:'I look at / the monument / again.',jp:'私は見ます / その記念碑を / もう一度'},{en:'I think about / the victim.',jp:'私は考えます / その犠牲者について'},{en:'My friend is / quiet, too.',jp:'私の友達は〜です / 静かでもあります'},{en:'We want / peace / for everyone.',jp:'私たちは望みます / 平和を / すべての人のために'},{en:'We want to learn / more / about the monument.',jp:'私たちは学びたいです / もっと / その記念碑について'}],
 questions:[{prompt:'1. 記念碑は誰に知られていますか。本文から英語で答えなさい。',answer:'many people',evidence:'The monument is known to many people.',evidenceJp:'その記念碑は多くの人に知られています。',reason:'is known to の後ろが many people です。'},{prompt:'2. 記念碑は何のために建てられましたか。本文から英語で答えなさい。',answer:'peace',evidence:'It was built for peace.',evidenceJp:'それは平和のために建てられました。',reason:'for の後ろが peace です。'},{prompt:'3. 誰について学びますか。本文から英語で答えなさい。',answer:'a victim of the atomic bomb',evidence:'We learn about a victim of the atomic bomb.',evidenceJp:'私たちは原子爆弾の犠牲者について学びます。',reason:'learn about の後ろが a victim of the atomic bomb です。'},{prompt:'4. 観光客はどこにいますか。本文から英語で答えなさい。',answer:'near the monument',evidence:'A tourist is near the monument.',evidenceJp:'1人の観光客が記念碑の近くにいます。',reason:'near the monument が場所です。'},{prompt:'5. 私たちは何への願いを新たにしますか。本文から英語で答えなさい。',answer:'peace',evidence:'We renew our hope for peace.',evidenceJp:'私たちは平和への願いを新たにします。',reason:'for の後ろの peace が願いの対象です。'}],
 allowedWords:[['pass away / be covered with ~ / victim / renew / monument / cost / tourist / wine / atomic bomb / straw / get well / snow / wear / tin / receive / wood / stand / butter / so A that B / be filled with ~ / be known to ~ / make the most of ~','PROGRAM 8-2,3 shared v7 canonical Sheet IDs 3360-3381'],['built / hope','PROGRAM 8-1 cumulative'],['today / visit / peace / many / people / learn about / story / sad / quiet / near / hear / question / answer / guide / again / think about / friend / too / everyone / want to / more','G1/G2 cumulative']],
 auditNote:'最新v7正本ではPROGRAM 8-2と8-3が共通語彙プール（Sheet ID3360〜3381）として登録されている。8-2ではmonument / victim / tourist / atomic bomb / renew / so A that B / be known to ~を平和記念碑の1場面に限定。書き込み後の人手監査でtourists / victims / tells / asks / answers等の自動活用・複数化を削除した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 8-3']={
 id:'V10-SS-G2-P8-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 8-3',level:'HOP',title:'Making the Most of Old Tin and Wood',
 sentences:['Our class has a project about old tin and wood.','A box is filled with old tin and wood.','We want to make the most of the tin and wood.','The tin is so thin that we can fold it.','We make a small badge from the tin.','We make a small figure from the wood.','Each badge has a peace message.','The badge is known to our class.','After the project, we receive one badge.','I wear the badge at school.','The box is still filled with tin and wood.','We can make more.','We think this is a good way to use old tin and wood.','We want to make the most of them again.'],
 fullTranslation:'「私たちのクラスには古いブリキと木材についてのプロジェクトがあります。箱は古いブリキと木材でいっぱいです。私たちはそのブリキと木材を最大限に活用したいです。ブリキはとても薄いので、折ることができます。私たちはブリキから小さなバッジを作ります。木材から小さな人形を作ります。それぞれのバッジには平和のメッセージがあります。そのバッジは私たちのクラスに知られています。プロジェクトのあと、私たちは1つのバッジを受け取ります。私は学校でそのバッジを身につけます。箱にはまだブリキと木材が入っています。私たちはさらに作ることができます。これは古いブリキと木材を使うよい方法だと思います。私たちはまたそれらを最大限に活用したいです。」',
 slashRows:[{en:'Our class has / a project / about old tin and wood.',jp:'私たちのクラスにはあります / 1つのプロジェクトが / 古いブリキと木材についての'},{en:'A box is filled / with old tin and wood.',jp:'箱は満たされています / 古いブリキと木材で'},{en:'We want to make the most of / the tin and wood.',jp:'私たちは最大限に活用したいです / そのブリキと木材を'},{en:'The tin is / so thin that / we can fold it.',jp:'そのブリキは〜です / とても薄いので / 私たちはそれを折れます'},{en:'We make / a small badge / from the tin.',jp:'私たちは作ります / 小さなバッジを / そのブリキから'},{en:'We make / a small figure / from the wood.',jp:'私たちは作ります / 小さな人形を / その木材から'},{en:'Each badge has / a peace message.',jp:'それぞれのバッジにはあります / 平和のメッセージが'},{en:'The badge is known / to our class.',jp:'そのバッジは知られています / 私たちのクラスに'},{en:'After the project, / we receive / one badge.',jp:'プロジェクトのあと / 私たちは受け取ります / 1つのバッジを'},{en:'I wear / the badge / at school.',jp:'私は身につけます / そのバッジを / 学校で'},{en:'The box is still filled / with tin and wood.',jp:'その箱はまだ満たされています / ブリキと木材で'},{en:'We can make / more.',jp:'私たちはさらに作ることができます'},{en:'We think / this is / a good way to use old tin and wood.',jp:'私たちは思います / これは〜だと / 古いブリキと木材を使うよい方法'},{en:'We want to make the most of / them / again.',jp:'私たちは最大限に活用したいです / それらを / また'}],
 questions:[{prompt:'1. 箱は何で満たされていますか。本文から英語で答えなさい。',answer:'old tin and wood',evidence:'A box is filled with old tin and wood.',evidenceJp:'箱は古いブリキと木材でいっぱいです。',reason:'is filled with の後ろが old tin and wood です。'},{prompt:'2. ブリキはどのようなので折ることができますか。本文から英語で1語抜き出しなさい。',answer:'thin',evidence:'The tin is so thin that we can fold it.',evidenceJp:'ブリキはとても薄いので、折ることができます。',reason:'so thin that ... の thin が状態を表しています。'},{prompt:'3. 木材から何を作りますか。本文から英語で答えなさい。',answer:'a small figure',evidence:'We make a small figure from the wood.',evidenceJp:'木材から小さな人形を作ります。',reason:'make の目的語が a small figure です。'},{prompt:'4. プロジェクトのあと、何を受け取りますか。本文から英語で答えなさい。',answer:'one badge',evidence:'After the project, we receive one badge.',evidenceJp:'プロジェクトのあと、私たちは1つのバッジを受け取ります。',reason:'receive の目的語が one badge です。'},{prompt:'5. 話し手たちは最後に何をしたいと考えていますか。本文から英語で答えなさい。',answer:'make the most of them again',evidence:'We want to make the most of them again.',evidenceJp:'私たちはまたそれらを最大限に活用したいです。',reason:'want to の後ろが make the most of them again です。'}],
 allowedWords:[['pass away / be covered with ~ / victim / renew / monument / cost / tourist / wine / atomic bomb / straw / get well / snow / wear / tin / receive / wood / stand / butter / so A that B / be filled with ~ / be known to ~ / make the most of ~','PROGRAM 8-2,3 shared v7 canonical Sheet IDs 3360-3381'],['badge / figure','PROGRAM 8 textbook text v7 canonical IDs 3382-3393'],['class / has / project / old / box / want to / thin / fold / make / small / from / each / peace / message / after / one / at school / still / can / more / think / good / way / use / them / again','G1/G2 cumulative']],
 auditNote:'PROGRAM 8-3は8-2と同じ最新v7共通プールを使用。be filled with ~ / tin / wood / receive / wear / so A that B / be known to ~ / make the most of ~を古い材料の再利用という1場面にまとめた。badge / figureは同PROGRAM教科書本文の正本語。人手監査でbadges / students / materials / thingsなどの自動複数化を削除し、未登録活用形を残していない。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};