window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 6-1']={
id:'V10-NH-G2-U6-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 6-1',level:'HOP',title:'A Sports Quiz for Our Presentation',
sentences:['Our class has a presentation about sports.','I make a quiz for the presentation.','The quiz has sports trivia.','One question is about a tennis court.','Court A is big.','Court B is bigger than Court A.','I show a picture of Court A and Court B.','My class thinks about the question.','We talk about the trivia together.','The quiz is fun.','It helps us learn about sports.','I want to use a quiz again next time.'],
fullTranslation:'「私たちのクラスではスポーツについての発表があります。私は発表のためにクイズを作ります。そのクイズにはスポーツの雑学があります。1つの問題はテニスコートについてです。コートAは大きいです。コートBはコートAより大きいです。私はコートAとコートBの絵を見せます。クラスのみんなはその問題について考えます。私たちはいっしょにその雑学について話します。そのクイズは楽しいです。それはスポーツについて学ぶ助けになります。私は次回もクイズを使いたいです。」',
slashRows:[{en:'Our class has / a presentation / about sports.',jp:'私たちのクラスではあります / 発表が / スポーツについての'},{en:'I make / a quiz / for the presentation.',jp:'私は作ります / クイズを / 発表のために'},{en:'The quiz has / sports trivia.',jp:'そのクイズにはあります / スポーツの雑学が'},{en:'One question is / about a tennis court.',jp:'1つの問題は〜です / テニスコートについて'},{en:'Court A is / big.',jp:'コートAは〜です / 大きい'},{en:'Court B is / bigger than / Court A.',jp:'コートBは〜です / より大きい / コートAより'},{en:'I show / a picture / of Court A and Court B.',jp:'私は見せます / 絵を / コートAとコートBの'},{en:'My class / thinks about / the question.',jp:'クラスのみんなは / 考えます / その問題について'},{en:'We talk about / the trivia / together.',jp:'私たちは話します / その雑学について / いっしょに'},{en:'The quiz is / fun.',jp:'そのクイズは〜です / 楽しい'},{en:'It helps us / learn about sports.',jp:'それは私たちを助けます / スポーツについて学ぶのを'},{en:'I want to use / a quiz / again / next time.',jp:'私は使いたいです / クイズを / また / 次回に'}],
questions:[{prompt:'1. 話し手は何のためにクイズを作りますか。本文から英語で答えなさい。',answer:'the presentation',evidence:'I make a quiz for the presentation.',evidenceJp:'私は発表のためにクイズを作ります。',reason:'for の後ろが the presentation です。'},{prompt:'2. クイズには何がありますか。本文から英語で答えなさい。',answer:'sports trivia',evidence:'The quiz has sports trivia.',evidenceJp:'そのクイズにはスポーツの雑学があります。',reason:'has の目的語が sports trivia です。'},{prompt:'3. 1つの問題は何についてですか。本文から英語で答えなさい。',answer:'a tennis court',evidence:'One question is about a tennis court.',evidenceJp:'1つの問題はテニスコートについてです。',reason:'about の後ろが a tennis court です。'},{prompt:'4. コートAとコートBではどちらが大きいですか。本文から英語で答えなさい。',answer:'Court B',evidence:'Court B is bigger than Court A.',evidenceJp:'コートBはコートAより大きいです。',reason:'bigger than の主語が Court B です。'},{prompt:'5. クイズは何について学ぶ助けになりますか。本文から英語で答えなさい。',answer:'sports',evidence:'It helps us learn about sports.',evidenceJp:'それはスポーツについて学ぶ助けになります。',reason:'learn about の後ろが sports です。'}],
allowedWords:[['than ~ / quiz / trivia / court','Unit 6-1: v7 canonical Sheet IDs 1261-1264'],['class / presentation / sports / make / question / tennis / big / picture / think about / talk about / together / fun / help / learn / want to / use / again / next time','Unit0-5 cumulative; comparative -er is Unit6 Part1 target grammar']],
auditNote:'最新v7正本Unit6 Part1（Sheet ID1261〜1264）を直接照合。than / quiz / trivia / courtを、発表に入れるスポーツクイズの流れに統合。比較級はUnit6 Part1の目標文法としてbig→biggerを使用。Part2のmore / most / survey / strategy等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 6-2']={
id:'V10-NH-G2-U6-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 6-2',level:'HOP',title:'A Survey about Sports Skills',
sentences:['We make a survey about sports.','I ask my class about curling.','One answer is about curling.','We ask about tennis and soccer too.','In our survey, more people like soccer than curling.','Some people have good curling skill.','We talk about a strategy for curling.','We think curling needs the most skill.','I write each answer on paper.','The survey is useful for our presentation.','We use the survey in our presentation.','I want to know more about curling.'],
fullTranslation:'「私たちはスポーツについて調査をします。私はクラスのみんなにカーリングについてたずねます。1つの答えはカーリングについてです。テニスとサッカーについてもたずねます。私たちの調査では、カーリングよりサッカーが好きな人のほうが多いです。カーリングの腕前がよい人もいます。私たちはカーリングの作戦について話します。カーリングには最も高い技術が必要だと考えます。私はそれぞれの答えを用紙に書きます。その調査は私たちの発表に役立ちます。私たちは発表でその調査を使います。私はカーリングについてもっと知りたいです。」',
slashRows:[{en:'We make / a survey / about sports.',jp:'私たちはします / 調査を / スポーツについて'},{en:'I ask / my class / about curling.',jp:'私はたずねます / クラスのみんなに / カーリングについて'},{en:'One answer is / about curling.',jp:'1つの答えは〜です / カーリングについて'},{en:'We ask about / tennis and soccer / too.',jp:'私たちはたずねます / テニスとサッカーについて / も'},{en:'In our survey, / more people like / soccer / than curling.',jp:'私たちの調査では / より多くの人が好きです / サッカーを / カーリングより'},{en:'Some people have / good curling skill.',jp:'何人かの人にはあります / よいカーリングの腕前が'},{en:'We talk about / a strategy / for curling.',jp:'私たちは話します / 作戦について / カーリングの'},{en:'We think / curling needs / the most skill.',jp:'私たちは思います / カーリングには必要だと / 最も高い技術が'},{en:'I write / each answer / on paper.',jp:'私は書きます / それぞれの答えを / 用紙に'},{en:'The survey is / useful / for our presentation.',jp:'その調査は〜です / 役に立つ / 私たちの発表に'},{en:'We use / the survey / in our presentation.',jp:'私たちは使います / その調査を / 発表で'},{en:'I want to know / more / about curling.',jp:'私は知りたいです / もっと / カーリングについて'}],
questions:[{prompt:'1. 何について調査をしますか。本文から英語で答えなさい。',answer:'sports',evidence:'We make a survey about sports.',evidenceJp:'私たちはスポーツについて調査をします。',reason:'about の後ろが sports です。'},{prompt:'2. 話し手はクラスに何についてたずねますか。本文から英語で答えなさい。',answer:'curling',evidence:'I ask my class about curling.',evidenceJp:'私はクラスのみんなにカーリングについてたずねます。',reason:'about の後ろが curling です。'},{prompt:'3. 調査では、カーリングより何が好きな人のほうが多いですか。本文から英語で答えなさい。',answer:'soccer',evidence:'In our survey, more people like soccer than curling.',evidenceJp:'私たちの調査では、カーリングよりサッカーが好きな人のほうが多いです。',reason:'more people like の目的語が soccer です。'},{prompt:'4. 何の作戦について話しますか。本文から英語で答えなさい。',answer:'curling',evidence:'We talk about a strategy for curling.',evidenceJp:'私たちはカーリングの作戦について話します。',reason:'for の後ろが curling です。'},{prompt:'5. 答えを何に書きますか。本文から英語で答えなさい。',answer:'paper',evidence:'I write each answer on paper.',evidenceJp:'私はそれぞれの答えを用紙に書きます。',reason:'on の後ろが paper です。'}],
allowedWords:[['more / skill / most / curling / survey / answer / strategy','Unit 6-2: v7 canonical Sheet IDs 1265-1271'],['make / sports / ask / class / tennis / soccer / people / like / talk about / think / need / write / paper / useful / presentation / use / want to / know / than','Unit0-6-1 cumulative']],
auditNote:'最新v7正本Unit6 Part2（Sheet ID1265〜1271）を直接照合。more / skill / most / curling / survey / answer / strategyをスポーツ調査の流れに統合。Read and Think1のin conclusion / percent / graph / according to等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 6-3']={
id:'V10-NH-G2-U6-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 6-3',level:'HOP',title:'What Our Survey Shows',
sentences:['We finish our sports survey.','Then I make a graph.','According to the survey, 60 percent of people like soccer.','Half of the people like tennis.','More people choose soccer than tennis.','We find that the graph makes the result better.','A graph such as this one is useful.','As for our quiz, it is the best part.','We use one picture in the presentation.','In conclusion, the graph is easy to understand.','We want to make a better presentation.','I check the graph again.'],
fullTranslation:'「私たちはスポーツの調査を終えます。それから私はグラフを作ります。調査によると、60パーセントの人がサッカーを好きです。半分の人はテニスが好きです。テニスよりサッカーを選ぶ人のほうが多いです。私たちはグラフによって結果がよりよくなることに気づきます。このようなグラフは役に立ちます。クイズについて言えば、それが一番よい部分です。私たちは発表で1枚の絵を使います。結論として、そのグラフは理解しやすいです。私たちはよりよい発表を作りたいです。私はもう一度グラフを確認します。」',
slashRows:[{en:'We finish / our sports survey.',jp:'私たちは終えます / スポーツの調査を'},{en:'Then / I make / a graph.',jp:'それから / 私は作ります / グラフを'},{en:'According to the survey, / 60 percent of people / like soccer.',jp:'調査によると / 60パーセントの人が / サッカーを好きです'},{en:'Half of the people / like tennis.',jp:'半分の人は / テニスが好きです'},{en:'More people choose / soccer / than tennis.',jp:'より多くの人が選びます / サッカーを / テニスより'},{en:'We find / that the graph makes / the result better.',jp:'私たちは気づきます / グラフが〜すると / 結果をよりよく'},{en:'A graph such as this one / is / useful.',jp:'このようなグラフは / 〜です / 役に立つ'},{en:'As for our quiz, / it is / the best part.',jp:'私たちのクイズについて言えば / それは〜です / 一番よい部分'},{en:'We use / one picture / in the presentation.',jp:'私たちは使います / 1枚の絵を / 発表で'},{en:'In conclusion, / the graph is / easy to understand.',jp:'結論として / そのグラフは〜です / 理解しやすい'},{en:'We want to make / a better presentation.',jp:'私たちは作りたいです / よりよい発表を'},{en:'I check / the graph / again.',jp:'私は確認します / グラフを / もう一度'}],
questions:[{prompt:'1. 調査のあと、話し手は何を作りますか。本文から英語で答えなさい。',answer:'a graph',evidence:'Then I make a graph.',evidenceJp:'それから私はグラフを作ります。',reason:'make の目的語が a graph です。'},{prompt:'2. 調査によると、何パーセントの人がサッカーを好きですか。本文から英語で答えなさい。',answer:'60 percent',evidence:'According to the survey, 60 percent of people like soccer.',evidenceJp:'調査によると、60パーセントの人がサッカーを好きです。',reason:'割合を表す部分が 60 percent です。'},{prompt:'3. 半分の人は何が好きですか。本文から英語で答えなさい。',answer:'tennis',evidence:'Half of the people like tennis.',evidenceJp:'半分の人はテニスが好きです。',reason:'like の目的語が tennis です。'},{prompt:'4. クイズについて言えば、それはどのような部分ですか。本文から英語で答えなさい。',answer:'the best part',evidence:'As for our quiz, it is the best part.',evidenceJp:'クイズについて言えば、それが一番よい部分です。',reason:'it の説明が the best part です。'},{prompt:'5. 結論として、グラフはどうですか。本文から英語で答えなさい。',answer:'easy to understand',evidence:'In conclusion, the graph is easy to understand.',evidenceJp:'結論として、そのグラフは理解しやすいです。',reason:'graph の状態を表す部分が easy to understand です。'}],
allowedWords:[['in conclusion / better / find / percent / best / half / then / graph / according to ~ / more / A such as B / as for ~','Unit 6 Read and Think1: v7 canonical Sheet IDs 1272-1283'],['finish / sports / survey / make / people / like / soccer / tennis / choose / result / useful / quiz / part / use / picture / presentation / easy / understand / want to / check / again / than','Unit0-6-2 cumulative']],
auditNote:'最新v7正本Unit6 Read and Think1（Sheet ID1272〜1283）を直接照合。in conclusion / better / find / percent / best / half / then / graph / according to / more / such as / as forを、調査結果をグラフでまとめる説明文に統合。Read and Think2のfeedback / delivery / data / content / slide / clear等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 6-4']={
id:'V10-NH-G2-U6-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 6-4',level:'HOP',title:'Feedback after My Presentation',
sentences:['Yesterday I spoke about universal design.','My topic was easy to understand.','I used one slide with data.','The content of the slide was clear.','Each letter was big.','My delivery was as clear as my friend’s delivery.','After the presentation, I got feedback.','One comment was about my voice.','Another comment was about the slide.','I write the feedback on paper.','I want to work on my delivery.','I want good eye contact next time.','For a good speaker, clear content and good eye contact are important.','I will use this feedback next time.'],
fullTranslation:'「昨日、私はユニバーサルデザインについて話しました。私の話題は理解しやすいものでした。私はデータを入れたスライドを1枚使いました。そのスライドの内容ははっきりしていました。それぞれの文字は大きかったです。私の話しぶりは友達の話しぶりと同じくらい明瞭でした。発表のあと、私は意見をもらいました。1つのコメントは私の声についてでした。もう1つのコメントはスライドについてでした。私はその意見を用紙に書きます。私は自分の話しぶりを改善したいです。次回はよいアイコンタクトをしたいです。よい話し手にとって、はっきりした内容とよいアイコンタクトは大切です。私は次回、この意見を生かします。」',
slashRows:[{en:'Yesterday / I spoke / about universal design.',jp:'昨日 / 私は話しました / ユニバーサルデザインについて'},{en:'My topic was / easy to understand.',jp:'私の話題は〜でした / 理解しやすい'},{en:'I used / one slide / with data.',jp:'私は使いました / 1枚のスライドを / データを入れた'},{en:'The content / of the slide / was clear.',jp:'内容は / スライドの / はっきりしていました'},{en:'Each letter was / big.',jp:'それぞれの文字は〜でした / 大きい'},{en:'My delivery was / as clear as / my friend’s delivery.',jp:'私の話しぶりは〜でした / 同じくらい明瞭 / 友達の話しぶりと'},{en:'After the presentation, / I got / feedback.',jp:'発表のあと / 私はもらいました / 意見を'},{en:'One comment was / about my voice.',jp:'1つのコメントは〜でした / 私の声について'},{en:'Another comment was / about the slide.',jp:'もう1つのコメントは〜でした / スライドについて'},{en:'I write / the feedback / on paper.',jp:'私は書きます / その意見を / 用紙に'},{en:'I want to work on / my delivery.',jp:'私は取り組みたいです / 自分の話しぶりに'},{en:'I want / good eye contact / next time.',jp:'私はほしいです / よいアイコンタクトが / 次回に'},{en:'For a good speaker, / clear content and good eye contact / are important.',jp:'よい話し手にとって / はっきりした内容とよいアイコンタクトは / 大切です'},{en:'I will use / this feedback / next time.',jp:'私は生かします / この意見を / 次回に'}],
questions:[{prompt:'1. 昨日、話し手は何について話しましたか。本文から英語で答えなさい。',answer:'universal design',evidence:'Yesterday I spoke about universal design.',evidenceJp:'昨日、私はユニバーサルデザインについて話しました。',reason:'spoke about の後ろが universal design です。'},{prompt:'2. スライドには何が入っていましたか。本文から英語で答えなさい。',answer:'data',evidence:'I used one slide with data.',evidenceJp:'私はデータを入れたスライドを1枚使いました。',reason:'with の後ろが data です。'},{prompt:'3. スライドの内容はどうでしたか。本文から英語で1語抜き出しなさい。',answer:'clear',evidence:'The content of the slide was clear.',evidenceJp:'そのスライドの内容ははっきりしていました。',reason:'content の状態を表す語が clear です。'},{prompt:'4. 発表のあと、何をもらいましたか。本文から英語で答えなさい。',answer:'feedback',evidence:'After the presentation, I got feedback.',evidenceJp:'発表のあと、私は意見をもらいました。',reason:'got の目的語が feedback です。'},{prompt:'5. 次に取り組みたいことは何ですか。本文から英語で答えなさい。',answer:'my delivery',evidence:'I want to work on my delivery.',evidenceJp:'私は自分の話しぶりを改善したいです。',reason:'work on の後ろが my delivery です。'}],
allowedWords:[['as A as B / feedback / spoke / delivery / letter / data / work / content / topic / contact / speaker / comment / slide / clear','Unit 6 Read and Think2: v7 canonical Sheet IDs 1284-1297'],['yesterday / universal design / easy to understand / use-used / big / friend / after / presentation / get-got / voice / another / write / paper / want to / eye / next time / important / will','Unit0-6-3 cumulative']],
auditNote:'最新v7正本Unit6 Read and Think2（Sheet ID1284〜1297）を直接照合。as A as B / feedback / spoke / delivery / letter / data / work / content / topic / contact / speaker / comment / slide / clearを、発表後の振り返りという自然な流れに統合。Unit7のheritage / protect / pollution / tourist等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
