window.V10_PASSAGES_G2_SS=window.V10_PASSAGES_G2_SS||{};

window.V10_PASSAGES_G2_SS['PROGRAM 6-1']={
 id:'V10-SS-G2-P6-1-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 6-1',level:'HOP',title:'Leaves and a High-Tech Idea',
 sentences:['Today, we learn about a high-tech idea from a leaf.','We look at a wet leaf.','Water can stick to this leaf.','Then, we look at another leaf.','Water does not stick to it.','This leaf can work better than the first leaf.','We meet a student from Germany.','We look at the two leaves together.','The idea can help people.','We write about the two leaves.','For this idea, the second leaf is better than the first leaf.','I do not want my bag to get wet.','A leaf can teach us a lot.','I want to learn about another high-tech idea.'],
 fullTranslation:'「今日、私たちは葉から生まれたハイテクの考えについて学びます。ぬれた葉を見ます。水はこの葉にくっつくことがあります。次に、別の葉を見ます。水はその葉にはくっつきません。この葉は最初の葉よりもうまく働くことができます。私たちはドイツから来た生徒に会います。2枚の葉をいっしょに見ます。その考えは人々の役に立つことができます。私たちは2枚の葉について書きます。この考えには、2枚目の葉のほうが最初の葉より適しています。私はかばんをぬらしたくありません。葉は私たちに多くのことを教えてくれます。私は別のハイテクの考えについても学びたいです。」',
 slashRows:[{en:'Today, / we learn about / a high-tech idea / from a leaf.',jp:'今日 / 私たちは学びます / ハイテクの考えについて / 葉から生まれた'},{en:'We look at / a wet leaf.',jp:'私たちは見ます / ぬれた葉を'},{en:'Water can stick / to this leaf.',jp:'水はくっつくことがあります / この葉に'},{en:'Then, / we look at / another leaf.',jp:'次に / 私たちは見ます / 別の葉を'},{en:'Water does not stick / to it.',jp:'水はくっつきません / それに'},{en:'This leaf can work / better than / the first leaf.',jp:'この葉は働くことができます / よりうまく / 最初の葉より'},{en:'We meet / a student / from Germany.',jp:'私たちは会います / 生徒に / ドイツから来た'},{en:'We look at / the two leaves / together.',jp:'私たちは見ます / 2枚の葉を / いっしょに'},{en:'The idea can help / people.',jp:'その考えは役に立てます / 人々の'},{en:'We write about / the two leaves.',jp:'私たちは書きます / 2枚の葉について'},{en:'For this idea, / the second leaf is / better than / the first leaf.',jp:'この考えには / 2枚目の葉は〜です / よりよい / 最初の葉より'},{en:'I do not want / my bag / to get wet.',jp:'私は望みません / かばんが / ぬれることを'},{en:'A leaf can teach / us / a lot.',jp:'葉は教えることができます / 私たちに / 多くのことを'},{en:'I want to learn about / another high-tech idea.',jp:'私は学びたいです / 別のハイテクの考えについて'}],
 questions:[{prompt:'1. 今日、何について学びますか。本文から英語で答えなさい。',answer:'a high-tech idea',evidence:'Today, we learn about a high-tech idea from a leaf.',evidenceJp:'今日、私たちは葉から生まれたハイテクの考えについて学びます。',reason:'learn about の目的内容が a high-tech idea です。'},{prompt:'2. 最初に見る葉はどのような葉ですか。本文から英語で2語抜き出しなさい。',answer:'wet leaf',evidence:'We look at a wet leaf.',evidenceJp:'ぬれた葉を見ます。',reason:'leaf を説明している語句が wet leaf です。'},{prompt:'3. この葉には何がくっつくことがありますか。本文から英語で1語抜き出しなさい。',answer:'Water',evidence:'Water can stick to this leaf.',evidenceJp:'水はこの葉にくっつくことがあります。',reason:'文の主語 Water がくっつくものです。'},{prompt:'4. どこの国から来た生徒に会いますか。本文から英語で1語抜き出しなさい。',answer:'Germany',evidence:'We meet a student from Germany.',evidenceJp:'私たちはドイツから来た生徒に会います。',reason:'from の後ろの Germany が国を表しています。'},{prompt:'5. この考えには、どちらの葉のほうがよいですか。本文から英語で答えなさい。',answer:'the second leaf',evidence:'For this idea, the second leaf is better than the first leaf.',evidenceJp:'この考えには、2枚目の葉のほうが最初の葉より適しています。',reason:'better than で比較され、the second leaf がよりよい側です。'}],
 allowedWords:[['better / Germany / than ~ / wet / leaf-leaves / high-tech / another / stick to ~','PROGRAM 6-1: canonical Sheet IDs 3173-3180'],['today / learn about / idea / water / work / first / meet / student / two / together / help / people / write / second / bag / teach / want to','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でSunshine中2 PROGRAM 6-1をID3173〜3180まで直接照合。比較級betterとthan ~を文法軸にし、leaf-leavesは正本が単数・複数の両表層を明示しているためleaf / leavesを使用。P6-2以降で初出するbest / develop / useful等は先取りせず、PROGRAM 6-1内の1場面に限定した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 6-2']={
 id:'V10-SS-G2-P6-2-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 6-2',level:'HOP',title:'A Boat Shoe from a Pet',
 sentences:['One day, I sail on a boat.','The deck is wet.','I can slip on the deck.','My pet can walk there without trouble.','I look at my pet’s paw.','I get inspiration from the paw.','I decide to develop a better shoe.','I make a boat shoe.','The invention is useful on a wet deck.','With the shoe, I can walk on the wet deck.','I think it is my best idea.','Later, other people use the invention.','Nature can give people a good idea.','I want to learn about another invention.'],
 fullTranslation:'「ある日、私は船で航海します。甲板はぬれています。私は甲板ですべることがあります。私のペットはそこで困ることなく歩くことができます。私はペットの足を見ます。その足からひらめきを得ます。私はもっとよい靴を開発することに決めます。デッキシューズを作ります。その発明はぬれた甲板で役に立ちます。その靴があれば、ぬれた甲板を歩くことができます。私はそれが自分の最高の考えだと思います。あとで、ほかの人々もその発明を使います。自然は人々によい考えを与えることができます。私は別の発明についても学びたいです。」',
 slashRows:[{en:'One day, / I sail / on a boat.',jp:'ある日 / 私は航海します / 船で'},{en:'The deck is / wet.',jp:'甲板は〜です / ぬれた'},{en:'I can slip / on the deck.',jp:'私はすべることがあります / 甲板で'},{en:'My pet can walk / there / without trouble.',jp:'私のペットは歩くことができます / そこで / 困ることなく'},{en:'I look at / my pet’s paw.',jp:'私は見ます / ペットの足を'},{en:'I get / inspiration / from the paw.',jp:'私は得ます / ひらめきを / その足から'},{en:'I decide to develop / a better shoe.',jp:'私は開発することに決めます / もっとよい靴を'},{en:'I make / a boat shoe.',jp:'私は作ります / デッキシューズを'},{en:'The invention is / useful / on a wet deck.',jp:'その発明は〜です / 役に立つ / ぬれた甲板で'},{en:'With the shoe, / I can walk / on the wet deck.',jp:'その靴があれば / 私は歩くことができます / ぬれた甲板を'},{en:'I think / it is / my best idea.',jp:'私は思います / それは〜だと / 私の最高の考え'},{en:'Later, / other people use / the invention.',jp:'あとで / ほかの人々は使います / その発明を'},{en:'Nature can give / people / a good idea.',jp:'自然は与えることができます / 人々に / よい考えを'},{en:'I want to learn about / another invention.',jp:'私は学びたいです / 別の発明について'}],
 questions:[{prompt:'1. いつ船で航海しますか。本文から英語で答えなさい。',answer:'One day',evidence:'One day, I sail on a boat.',evidenceJp:'ある日、私は船で航海します。',reason:'One day が時を表しています。'},{prompt:'2. 甲板で何をすることがありますか。本文から英語で1語抜き出しなさい。',answer:'slip',evidence:'I can slip on the deck.',evidenceJp:'私は甲板ですべることがあります。',reason:'can の後ろの slip が動作です。'},{prompt:'3. 何からひらめきを得ますか。本文から英語で答えなさい。',answer:'the paw',evidence:'I get inspiration from the paw.',evidenceJp:'その足からひらめきを得ます。',reason:'from の後ろの the paw がひらめきのもとです。'},{prompt:'4. 何を開発することに決めますか。本文から英語で答えなさい。',answer:'a better shoe',evidence:'I decide to develop a better shoe.',evidenceJp:'私はもっとよい靴を開発することに決めます。',reason:'develop の目的語が a better shoe です。'},{prompt:'5. 話し手はその考えをどのように評価していますか。本文から英語で3語抜き出しなさい。',answer:'my best idea',evidence:'I think it is my best idea.',evidenceJp:'私はそれが自分の最高の考えだと思います。',reason:'best が最上級を表し、my best idea が評価部分です。'}],
 allowedWords:[['best / sail / develop / pet / useful / invention / without / inspiration / one day / London / survive / icy / slip / fall into ~','PROGRAM 6-2: canonical Sheet IDs 3181-3194'],['decide to / boat shoe / paw / deck','PROGRAM 6 textbook text: canonical Sheet IDs 3217-3218, 3229, 3233'],['wet / better / another','PROGRAM 6-1 cumulative'],['boat / trouble / look at / get / shoe / make / walk / think / later / other / people / use / nature / give / good / idea / want to / learn about','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 6-2をID3181〜3194まで直接照合し、同PROGRAM教科書本文のdecide to / boat shoe / paw / deckもID3217〜3218・3229・3233で照合。最上級bestを文法軸にした。London / survive / icy / fall into ~は同一場面に無理に詰め込まず未使用とし、未登録の三単現や自動-ing化を避けて原形中心で構成した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};

window.V10_PASSAGES_G2_SS['PROGRAM 6-3']={
 id:'V10-SS-G2-P6-3-001',textbook:'サンシャイン',grade:'2',section:'PROGRAM 6-3',level:'HOP',title:'Our Eco-Friendly Classroom',
 sentences:['Today, we start an eco-friendly effort.','We want to save energy at school.','First, we turn off the light when we do not need it.','We can use less electricity this way.','We are able to save energy every day.','We also keep a plant by the window.','We give the plant light and water.','A bee can come to the plant.','We learn about agriculture, too.','There is a narrow space by the window.','We put one plant in that space.','We continue this effort every day.','There is potential in a small effort.','We search for another eco-friendly idea.','We want to use less energy tomorrow.'],
 fullTranslation:'「今日、私たちは環境にやさしい取り組みを始めます。学校でエネルギーを節約したいです。まず、必要でないときは明かりを消します。このようにして、より少ない電気を使うことができます。私たちは毎日エネルギーを節約することができます。窓のそばに植物も置きます。植物に光と水を与えます。ハチがその植物に来ることもあります。農業についても学びます。窓のそばには狭い空間があります。そこに植物を1つ置きます。私たちは毎日この取り組みを続けます。小さな取り組みにも可能性があります。私たちは別の環境にやさしい考えを探します。明日はもっと少ないエネルギーを使いたいです。」',
 slashRows:[{en:'Today, / we start / an eco-friendly effort.',jp:'今日 / 私たちは始めます / 環境にやさしい取り組みを'},{en:'We want to save / energy / at school.',jp:'私たちは節約したいです / エネルギーを / 学校で'},{en:'First, / we turn off / the light / when we do not need it.',jp:'まず / 私たちは消します / 明かりを / 必要でないとき'},{en:'We can use / less electricity / this way.',jp:'私たちは使うことができます / より少ない電気を / このようにして'},{en:'We are able to save / energy / every day.',jp:'私たちは節約することができます / エネルギーを / 毎日'},{en:'We also keep / a plant / by the window.',jp:'私たちはまた置きます / 植物を / 窓のそばに'},{en:'We give / the plant / light and water.',jp:'私たちは与えます / 植物に / 光と水を'},{en:'A bee can come / to the plant.',jp:'ハチは来ることがあります / その植物に'},{en:'We learn about / agriculture, too.',jp:'私たちは学びます / 農業についても'},{en:'There is / a narrow space / by the window.',jp:'あります / 狭い空間が / 窓のそばに'},{en:'We put / one plant / in that space.',jp:'私たちは置きます / 植物を1つ / その空間に'},{en:'We continue / this effort / every day.',jp:'私たちは続けます / この取り組みを / 毎日'},{en:'There is / potential / in a small effort.',jp:'あります / 可能性が / 小さな取り組みに'},{en:'We search for / another eco-friendly idea.',jp:'私たちは探します / 別の環境にやさしい考えを'},{en:'We want to use / less energy / tomorrow.',jp:'私たちは使いたいです / より少ないエネルギーを / 明日'}],
 questions:[{prompt:'1. 今日、どのような取り組みを始めますか。本文から英語で答えなさい。',answer:'an eco-friendly effort',evidence:'Today, we start an eco-friendly effort.',evidenceJp:'今日、私たちは環境にやさしい取り組みを始めます。',reason:'start の目的語が an eco-friendly effort です。'},{prompt:'2. 学校で何を節約したいですか。本文から英語で1語抜き出しなさい。',answer:'energy',evidence:'We want to save energy at school.',evidenceJp:'学校でエネルギーを節約したいです。',reason:'save の目的語が energy です。'},{prompt:'3. 必要でないとき、何を消しますか。本文から英語で答えなさい。',answer:'the light',evidence:'First, we turn off the light when we do not need it.',evidenceJp:'まず、必要でないときは明かりを消します。',reason:'turn off の目的語が the light です。'},{prompt:'4. どのくらいの電気を使うことができますか。本文から英語で答えなさい。',answer:'less electricity',evidence:'We can use less electricity this way.',evidenceJp:'このようにして、より少ない電気を使うことができます。',reason:'less が electricity の量を比較しています。'},{prompt:'5. 窓のそばに何を置きますか。本文から英語で答えなさい。',answer:'a plant',evidence:'We also keep a plant by the window.',evidenceJp:'窓のそばに植物も置きます。',reason:'keep の目的語が a plant です。'}],
 allowedWords:[['save / potential / continue / plant / energy / creature / less / coin / turn off~ / bee / be able to ~ / agriculture / light / centimeter / electricity / eco-friendly / effort / narrow / space / living / search / stylish','PROGRAM 6-3: canonical Sheet IDs 3195-3216'],['another','PROGRAM 6-1 cumulative'],['today / start / want to / school / first / when / need / use / this way / every day / keep / window / give / water / come / learn about / too / put / one / small / search for / idea / tomorrow','G1/G2 cumulative']],
 auditNote:'Google Sheet正本でPROGRAM 6-3をID3195〜3216まで直接照合。lessを比較量、be able to ~を可能表現として本文内で使用し、save / energy / turn off~ / electricity / eco-friendly / effortを1つの学校場面に統合。coin / centimeter / creature / living / stylishは文脈を壊すため無理に消化せず未使用。三単現を避け、plantは正本登録表層の単数形だけを使用した。',
 vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true
};
