const fs=require('fs');
const path=require('path');
function filesUnder(dir='.') {let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out=out.concat(filesUnder(p));else out.push(p);}return out;}
function visit(v,fn,seen=new Set()){if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))for(const x of v)visit(x,fn,seen);else for(const x of Object.values(v))visit(x,fn,seen);}
function richness(o){try{return JSON.stringify(o).length}catch{return 0}}
const bodies=new Map(),slashes=new Map(),qas=new Map();
for(const f of filesUnder().filter(f=>f.endsWith('.json')&&!/V11_BATCH15_RUNTIME_CANDIDATE/.test(f))){let v;try{v=JSON.parse(fs.readFileSync(f,'utf8'))}catch{continue}visit(v,o=>{
  const id=String(o.id||'');
  if(/^V11-B15-G[123]-\d{3}$/.test(id)&&o.body&&o.fullTranslation){const old=bodies.get(id);if(!old||richness(o)>richness(old.o))bodies.set(id,{o,source:f});}
  if(/^V11-B15-G[123]-\d{3}$/.test(id)&&((o.bodySlash&&o.translationSlash)||Array.isArray(o.slashRows))){const old=slashes.get(id);if(!old||richness(o)>richness(old.o))slashes.set(id,{o,source:f});}
  const qid=String(o.passageId||o.id||'');
  const qa=Array.isArray(o.questionsA)?o.questionsA:(o.sets&&Array.isArray(o.sets.A)?o.sets.A:(Array.isArray(o.questions)?o.questions:null));
  const qb=Array.isArray(o.questionsB)?o.questionsB:(o.sets&&Array.isArray(o.sets.B)?o.sets.B:(Array.isArray(o.questionSetB)?o.questionSetB:null));
  if(/^V11-B15-G[123]-\d{3}$/.test(qid)&&Array.isArray(qa)&&Array.isArray(qb)){const normalized={...o,questionsA:qa,questionsB:qb};const old=qas.get(qid);if(!old||richness(normalized)>richness(old.o))qas.set(qid,{o:normalized,source:f});}
});}
const ids=[...bodies.keys()].sort();if(ids.length!==50)throw new Error(`Batch15 body count ${ids.length} != 50`);
function anchorMeta(p,id){const raw=String(p.anchor||'').trim();const idm=/^V11-B15-G([123])-\d{3}$/.exec(id);if(!idm)throw new Error(`${id} invalid id`);const grade=idm[1];let book=null,section=null;let m=/^(NH|SS)-G([123])-(.+)$/.exec(raw);if(m){if(m[2]!==grade)throw new Error(`${id} anchor grade mismatch ${raw}`);book=m[1];const code=m[3];section=code;if(/^U\d/.test(code))section='Unit '+code.slice(1);else if(/^P\d/.test(code))section='PROGRAM '+code.slice(1);}if(!book){m=/^(New\s*Horizon|NH|Sunshine|SS)\s+(Unit|PROGRAM)\s+(.+)$/i.exec(raw);if(m){book=/^(New\s*Horizon|NH)$/i.test(m[1].replace(/\s+/g,' '))?'NH':'SS';section=(m[2].toUpperCase()==='PROGRAM'?'PROGRAM':'Unit')+' '+m[3].trim();}}if(!book){m=/^(ニューホライズン|サンシャイン)\s+(Unit|PROGRAM)\s+(.+)$/i.exec(raw);if(m){book=m[1]==='ニューホライズン'?'NH':'SS';section=(m[2].toUpperCase()==='PROGRAM'?'PROGRAM':'Unit')+' '+m[3].trim();}}if(!book||!section)throw new Error(`${id} unsupported anchor ${raw}`);return{textbook:book==='NH'?'ニューホライズン':'サンシャイン',anchor:{textbook:book==='NH'?'New Horizon':'Sunshine',grade:Number(grade),unit:section},grade,section};}
function slashRowsFor(id){const rec=slashes.get(id);if(!rec)throw new Error(`${id} missing human slash artifact`);const s=rec.o;if(Array.isArray(s.slashRows)&&s.slashRows.length)return s.slashRows.map(r=>({en:String(r.en||r.english||'').trim(),jp:String(r.jp||r.japanese||'').trim(),humanReview:r.humanReview||'B15_HUMAN_SLASH_PASS',alignmentShape:r.alignmentShape||'1:1'}));const en=String(s.bodySlash||'').split(' / ').map(x=>x.trim()).filter(Boolean),jp=String(s.translationSlash||'').split(' / ').map(x=>x.trim()).filter(Boolean);if(en.length!==jp.length||!en.length)throw new Error(`${id} slash count mismatch ${en.length}/${jp.length}`);return en.map((x,i)=>({en:x,jp:jp[i],humanReview:'B15_HUMAN_SLASH_PASS',alignmentShape:'1:1'}));}
function questionsFor(id){const rec=qas.get(id);if(!rec)throw new Error(`${id} missing human question artifact`);const q=rec.o;if(q.questionsA.length!==5||q.questionsB.length!==5)throw new Error(`${id} requires A/B 5 questions`);for(const [set,arr] of [['A',q.questionsA],['B',q.questionsB]])for(const [i,x] of arr.entries())for(const k of ['answer','evidence','evidenceJp','reason'])if(!String(x&&x[k]||'').trim())throw new Error(`${id} ${set}${i+1} missing ${k}`);return{A:q.questionsA.map((x,i)=>({...x,set:'A',no:i+1})),B:q.questionsB.map((x,i)=>({...x,set:'B',no:i+1}))};}
const candidate=ids.map(id=>{const base=bodies.get(id).o,meta=anchorMeta(base,id),slashRows=slashRowsFor(id),qq=questionsFor(id);const sentences=slashRows.map(r=>r.en).filter(Boolean);return{...base,...meta,registered:false,sentences,slashRows,questions:qq.A,questionSetB:qq.B,batch:'V11-B15',finalHumanQuestionReview:true,finalSlashHumanReview:'B15_SLASH_HUMAN_REVIEW_PASS'};});
const out={generatedAt:new Date().toISOString(),batch:'V11-B15',count:candidate.length,source:'verified Batch15 artifacts; same assembly rules as browser gate',passages:candidate};
fs.writeFileSync('V11_BATCH15_RUNTIME_CANDIDATE.json',JSON.stringify(out,null,2)+'\n');
console.log(`exported ${candidate.length} Batch15 passages`);
