const fs=require('fs');
const {chromium,webkit,devices}=require('playwright');
const URL=process.env.V11_LOCAL_URL||'http://127.0.0.1:4174/index.html';
const report={generatedAt:new Date().toISOString(),batch:'V11-FINAL32',registered:false,officialTotal:968,browsers:{},a4:{student:{passages:0,failures:[]},teacher:{passages:0,failures:[]}},persistent:null,finalPass:false};
function assert(c,m){if(!c)throw new Error(m)}
function meta(id){const m=/^V11-F32-G([123])-(\d{3})$/.exec(id);const g=m[1],n=Number(m[2]),ss=n%2===1;return g==='1'?{textbook:ss?'サンシャイン':'ニューホライズン',grade:'1',major:ss?'PROGRAM 10':'Unit 10',section:ss?'PROGRAM 10-2':'Unit 10-2'}:g==='2'?{textbook:ss?'サンシャイン':'ニューホライズン',grade:'2',major:ss?'PROGRAM 8':'Unit 7',section:ss?'PROGRAM 8-3':'Unit 7-4'}:{textbook:ss?'サンシャイン':'ニューホライズン',grade:'3',major:ss?'PROGRAM 7':'Unit 6',section:ss?'PROGRAM 7-3':'Unit 6-4'};}
async function register(page){
 await page.waitForFunction(()=>window.V11_MULTI_PASSAGE_STATE&&Number(window.V11_MULTI_PASSAGE_STATE.extraPassages)===800&&window.V11_BATCH16_REGISTERED===true,{timeout:120000});
 await page.addScriptTag({url:'./v11_final32_runtime_bundle.js'});
 await page.waitForFunction(()=>window.V11_FINAL32_RUNTIME_READY&&window.V11_FINAL32_PASSAGES,{timeout:30000});
 const res=await page.evaluate(async()=>{await window.V11_FINAL32_RUNTIME_READY;const ps=window.V11_FINAL32_PASSAGES;if(!Array.isArray(ps)||ps.length!==32)throw new Error('candidate count '+(ps&&ps.length));const st=window.V11_REGISTER_PASSAGES(ps);const all=Object.values(window.V11_EXTRA_PASSAGES||{}).flat();const f=all.filter(p=>/^V11-F32-G[123]-\d{3}$/.test(String(p&&p.id||'')));return{st,count:f.length,unique:new Set(f.map(x=>x.id)).size};});
 assert(Number(res.st.extraPassages)===832,'extraPassages '+JSON.stringify(res));
 assert(res.count===32&&res.unique===32,'FINAL32 registry '+JSON.stringify(res));return res;
}
async function choose(page,id){
 const m=meta(id);await page.selectOption('#textbook',{label:m.textbook});await page.selectOption('#grade',m.grade);await page.waitForTimeout(80);await page.selectOption('#major',{label:m.major});await page.waitForTimeout(80);await page.selectOption('#section',{label:m.section});await page.waitForFunction(target=>[...document.querySelectorAll('#v11PassageVariant option')].some(o=>o.value===target),id,{timeout:10000});await page.selectOption('#v11PassageVariant',id);await page.waitForFunction(target=>window.V11_MULTI_PASSAGE_UI_STATE&&window.V11_MULTI_PASSAGE_UI_STATE.selectedId===target,id,{timeout:10000});
 return page.evaluate(()=>({selectedId:window.V11_MULTI_PASSAGE_UI_STATE&&window.V11_MULTI_PASSAGE_UI_STATE.selectedId,passage:(document.querySelector('#passage')?.innerText||'').length,questions:(document.querySelector('#questions')?.innerText||'').length,answers:(document.querySelector('#answers')?.innerText||'').length}));
}
async function browserCase(name,type,contextOptions={}){
 const b=await type.launch({headless:true});const errors=[];try{const p=await b.newPage(contextOptions);p.on('pageerror',e=>errors.push('page:'+e.message));p.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});const r=await p.goto(URL,{waitUntil:'networkidle',timeout:120000});assert(r&&r.ok(),name+' HTTP');const reg=await register(p);const rendered=[];for(const id of ['V11-F32-G1-001','V11-F32-G2-001','V11-F32-G3-001'])rendered.push({id,...await choose(p,id)});assert(rendered.every(x=>x.selectedId===x.id&&x.passage>100&&x.questions>100&&x.answers>100),name+' render '+JSON.stringify(rendered));assert(errors.length===0,name+' errors '+errors.join(' | '));report.browsers[name]={pass:true,registration:reg,rendered,errors:[]};return p;}catch(e){report.browsers[name]={pass:false,error:String(e.stack||e),errors};throw e}finally{await b.close()}}
async function chromiumA4AndPersistent(){
 const b=await chromium.launch({headless:true});const errors=[];try{const p=await b.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push('page:'+e.message));p.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});let r=await p.goto(URL,{waitUntil:'networkidle',timeout:120000});assert(r&&r.ok(),'A4 HTTP');await register(p);const ids=await p.evaluate(()=>window.V11_FINAL32_PASSAGES.map(x=>x.id));assert(ids.length===32,'A4 candidate count');
 await p.emulateMedia({media:'print'});
 for(const id of ids){await choose(p,id);for(const [name,cls] of [['student','print-student'],['teacher','print-teacher']]){await p.evaluate(c=>{document.body.classList.remove('print-student','print-teacher');document.body.classList.add(c)},cls);const styles=await p.evaluate(()=>{const d=s=>document.querySelector(s)?getComputedStyle(document.querySelector(s)).display:null;return{passage:d('#passage'),slash:d('#slash'),questions:d('#questions'),answers:d('#answers')}});try{if(name==='student'){assert(styles.passage==='block'&&styles.questions==='block',id+' student passage/questions');assert(styles.slash==='none'&&styles.answers==='none',id+' student leak '+JSON.stringify(styles));}else{for(const k of ['passage','slash','questions','answers'])assert(styles[k]==='block',id+' teacher '+k+' '+styles[k]);}const pdf=await p.pdf({format:'A4',printBackground:true,margin:{top:'10mm',right:'10mm',bottom:'10mm',left:'10mm'}});assert(pdf.length>8000,id+' '+name+' PDF too small '+pdf.length);report.a4[name].passages++;}catch(e){report.a4[name].failures.push(id+': '+e.message);}}}
 await p.emulateMedia({media:'screen'});await p.evaluate(()=>{document.body.classList.remove('print-student','print-teacher');localStorage.setItem('v11-final32-candidate-persistence','ok')});
 const reloads=[];for(let i=0;i<2;i++){await p.reload({waitUntil:'networkidle',timeout:120000});await p.waitForFunction(()=>window.V11_MULTI_PASSAGE_STATE&&Number(window.V11_MULTI_PASSAGE_STATE.extraPassages)===800,{timeout:120000});const reg=await register(p);const st=await p.evaluate(()=>({probe:localStorage.getItem('v11-final32-candidate-persistence'),ready:document.readyState,extra:Number(window.V11_MULTI_PASSAGE_STATE&&window.V11_MULTI_PASSAGE_STATE.extraPassages||0)}));assert(st.probe==='ok'&&st.ready==='complete'&&st.extra===832,'candidate reload '+JSON.stringify(st));reloads.push({registration:reg,state:st});}
 assert(errors.length===0,'A4/persistent errors '+errors.join(' | '));report.persistent={pass:true,reloads:2,localStorage:true,states:reloads,errors:[]};
 }finally{await b.close()}}
(async()=>{try{await browserCase('chromium',chromium,{viewport:{width:1440,height:1000}});await browserCase('webkit',webkit,{viewport:{width:1440,height:1000}});const iphone=devices['iPhone 13'];await browserCase('iphone-webkit',webkit,{...iphone});await chromiumA4AndPersistent();report.finalPass=Object.values(report.browsers).every(x=>x.pass)&&report.a4.student.passages===32&&report.a4.teacher.passages===32&&report.a4.student.failures.length===0&&report.a4.teacher.failures.length===0&&report.persistent&&report.persistent.pass;}catch(e){report.error=String(e.stack||e);}finally{fs.writeFileSync('V11_FINAL32_BROWSER_A4_PERSISTENT_GATE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!report.finalPass)process.exit(2);}})();