const fs=require('fs');
const {loadCanonicalV7}=require('../v10_v7_lexicon_loader');
const elementary=JSON.parse(fs.readFileSync('v10_elementary_vocab_allowlist.json','utf8'));
const ELEMENTARY=new Set((elementary.words||[]).map(x=>String(x).toLowerCase()));
const FUNCTION=new Set(`a an the i me my mine you your yours he him his she her hers it its we us our ours they them their theirs this that these those who whose whom which what when where why how am is are was were be been being do does did doing have has had having can cannot could may might must shall should will would not no yes and or but so if because as than to of in on at by for from with about into over under before after during while through up down out off again then there here also too very more most less least some any many much few little each every all both either neither another other same own one two first second third`.split(/\s+/));
const CONTRACTIONS=new Set(["i'm","you're","he's","she's","it's","we're","they're","let's","isn't","aren't","wasn't","weren't","don't","doesn't","didn't","can't","couldn't","won't","wouldn't","shouldn't","mustn't","i've","you've","we've","they've","hasn't","haven't","hadn't","i'll","you'll","he'll","she'll","we'll","they'll","i'd","you'd","he'd","she'd","we'd","they'd"]);
const IRREG=new Map(Object.entries({went:'go',gone:'go',came:'come',seen:'see',saw:'see',made:'make',took:'take',taken:'take',gave:'give',given:'give',wrote:'write',written:'write',read:'read',bought:'buy',brought:'bring',thought:'think',found:'find',knew:'know',known:'know',told:'tell',said:'say',spoke:'speak',spoken:'speak',ate:'eat',eaten:'eat',drank:'drink',drunk:'drink',ran:'run',swam:'swim',swum:'swim',became:'become',began:'begin',begun:'begin',left:'leave',felt:'feel',kept:'keep',met:'meet',sent:'send',built:'build',held:'hold',heard:'hear',lost:'lose',paid:'pay',put:'put',stood:'stand',understood:'understand',lying:'lie',dying:'die',tying:'tie'}));
function tok(s){return (String(s||'').replace(/[’]/g,"'").match(/[A-Za-z]+(?:'[A-Za-z]+)*/g)||[]).map(x=>x.toLowerCase())}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function bases(w){const o=[];if(w.endsWith("'s")&&w.length>3)o.push(w.slice(0,-2));if(w.endsWith('ies')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ied')&&w.length>4)o.push(w.slice(0,-3)+'y');if(w.endsWith('ves')&&w.length>4)o.push(w.slice(0,-3)+'f',w.slice(0,-3)+'fe');if(w.endsWith('es')&&w.length>3)o.push(w.slice(0,-2),w.slice(0,-1));if(w.endsWith('s')&&w.length>3)o.push(w.slice(0,-1));for(const suf of ['ing','ed','er','est'])if(w.endsWith(suf)&&w.length>suf.length+2){const b=w.slice(0,-suf.length);o.push(b,b+'e');if(b.endsWith('i'))o.push(b.slice(0,-1)+'y');if(b.length>2&&b.at(-1)===b.at(-2))o.push(b.slice(0,-1));}return uniq(o)}
function code(book){if(book==='ニューホライズン')return'NH';if(book==='サンシャイン')return'SS';throw Error('book '+book)}
function cutoff(v7,book,grade,section){const c=code(book),g=Number(grade),u=v7.units[`${c}|${g}`]||{};const at=(fu,sr)=>{const pdf=Number(u[fu]);if(!pdf)throw Error(`mapping ${c}|${g}|${section}|${fu}`);return{code:c,grade:g,pdf,subrank:Number(sr)}};let m;if(c==='SS'){m=String(section).match(/^PROGRAM\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r=k;if(g===1&&n===10&&k>=4)r=8;if(g===2&&n===8&&k>=2)r=3;if(g===3&&n===7&&k===1)r=2;return at(`P${n}`,r)}}else{m=String(section).match(/^Unit\s*(\d+)-(\d+)$/i);if(m){const n=+m[1],k=+m[2];let r;if(g===1)r=k<=2?k:(n<=4?3:6);else{r=k===1?1:k===2?2:k===3?4:5;if(g===2&&n===7&&k===1)r=2}return at(`U${n}`,r)}}throw Error(`no cutoff ${book}|${grade}|${section}`)}
function allowed(intro,cut){if(!intro)return false;const[g,p,s]=intro;if(+g<cut.grade)return true;if(+g>cut.grade)return false;return +p<cut.pdf||(+p===cut.pdf&&+s<=cut.subrank)}
function classify(v7,w,cut){if(CONTRACTIONS.has(w)||FUNCTION.has(w)||w==='whether')return{kind:'GRAMMAR_ROUTED'};const bs=uniq([IRREG.get(w),...bases(w)]);for(const b of bs)if(ELEMENTARY.has(b))return{kind:'GRAMMAR_ROUTED',base:b};if(ELEMENTARY.has(w))return{kind:'ELEMENTARY'};for(const b of bs){const i=v7.lex[`${cut.code}|${b}`];if(i&&allowed(i,cut))return{kind:'GRAMMAR_ROUTED',base:b,intro:i}}const d=v7.lex[`${cut.code}|${w}`];if(d)return allowed(d,cut)?{kind:'V7_ALLOWED',intro:d}:{kind:'FUTURE_V7',intro:d};for(const b of bs){const i=v7.lex[`${cut.code}|${b}`];if(i&&!allowed(i,cut))return{kind:'FUTURE_V7',base:b,intro:i}}return{kind:'UNREGISTERED'}}
const files=['V11_BATCH16_BODY_TRANSLATION_DRAFT_G1_001_010.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G1_011_017.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G2_001_009.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G2_010_017.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G3_001_008.json','V11_BATCH16_BODY_TRANSLATION_DRAFT_G3_009_016.json'];
const ps=files.flatMap(f=>JSON.parse(fs.readFileSync(f,'utf8')).items);if(ps.length!==50)throw Error(`Batch16 ${ps.length}/50`);
const local=new Map();for(const f of fs.readdirSync('.')){if(!/^V11_BATCH16_REQUIRED_LOCAL_GLOSS_G[123]_\d{3}\.json$/.test(f))continue;const j=JSON.parse(fs.readFileSync(f,'utf8'));local.set(j.passageId,new Set((j.requiredLocal||[]).map(v=>String(v.word||'').toLowerCase()).filter(Boolean)))}
function sources(p){const a=[['body',p.body]];if(p.slash)a.push(['slash',p.slash]);for(const key of ['questions','questionSetA','questionSetB'])for(const [i,q] of (p[key]||[]).entries())for(const k of ['answer','evidence'])a.push([`${key}:${i+1}.${k}`,q&&q[k]]);return a}
const v7=loadCanonicalV7();if(Number(v7.source&&v7.source[2])!==3975)throw Error('v7 source count');const unresolved=[],future=[];let tokens=0,noteCovered=0;for(const p of ps){const cut=cutoff(v7,p.textbook,p.grade,p.section),noted=local.get(p.id)||new Set();for(const[where,text]of sources(p))for(const w of tok(text)){tokens++;if(noted.has(w)){noteCovered++;continue}const c=classify(v7,w,cut);if(c.kind==='UNREGISTERED')unresolved.push({id:p.id,book:p.textbook,grade:p.grade,section:p.section,where,word:w});if(c.kind==='FUTURE_V7')future.push({id:p.id,book:p.textbook,grade:p.grade,section:p.section,where,word:w,intro:c.intro,base:c.base||null})}}
const report={generatedAt:new Date().toISOString(),batch:'V11-B16',sourceRecords:v7.source[2],passages:ps.length,tokensScanned:tokens,requiredNoteCoveredOccurrences:noteCovered,unregisteredOccurrences:unresolved.length,futureVocabLeakOccurrences:future.length,finalPass:ps.length===50&&unresolved.length===0&&future.length===0,unresolved,future};fs.writeFileSync('V11_BATCH16_FORMAL_VOCAB_CHRONOLOGY_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(!report.finalPass)process.exitCode=1;
