window.V10_PASSAGES_G2_NH=window.V10_PASSAGES_G2_NH||{};

window.V10_PASSAGES_G2_NH['Unit 5-1']={
id:'V10-NH-G2-U5-1-001',textbook:'ニューホライズン',grade:'2',section:'Unit 5-1',level:'HOP',title:'Universal Design Fair at City Hall',
sentences:['Today I go to city hall.','There is a universal design fair there.','I want to know how to use a new product.','I see a bottle at the fair.','The bottle has an adjustable design.','I touch the bottle and open it.','I learn how to use the design.','I also see an automatic door.','The door is part of a public facility.','The design is good for many people.','I write about the product.','I want to learn about universal design.'],
fullTranslation:'「今日、私は市役所へ行きます。そこではユニバーサルデザインの博覧会があります。私は新しい製品の使い方を知りたいです。博覧会でボトルを見ます。そのボトルには調節可能なデザインがあります。私はボトルにさわって開けます。そのデザインの使い方を学びます。自動ドアも見ます。そのドアは公共施設の一部です。そのデザインは多くの人にとってよいものです。私はその製品について書きます。ユニバーサルデザインについて学びたいです。」',
slashRows:[{en:'Today / I go to / city hall.',jp:'今日 / 私は行きます / 市役所へ'},{en:'There is / a universal design fair / there.',jp:'あります / ユニバーサルデザインの博覧会が / そこに'},{en:'I want to know / how to use / a new product.',jp:'私は知りたいです / 使い方を / 新しい製品の'},{en:'I see / a bottle / at the fair.',jp:'私は見ます / ボトルを / 博覧会で'},{en:'The bottle has / an adjustable design.',jp:'そのボトルにはあります / 調節可能なデザインが'},{en:'I touch / the bottle / and open it.',jp:'私はさわります / ボトルに / そしてそれを開けます'},{en:'I learn / how to use / the design.',jp:'私は学びます / 使い方を / そのデザインの'},{en:'I also see / an automatic door.',jp:'私はまた見ます / 自動ドアを'},{en:'The door is / part of / a public facility.',jp:'そのドアは〜です / 一部 / 公共施設の'},{en:'The design is / good / for many people.',jp:'そのデザインは〜です / よい / 多くの人にとって'},{en:'I write about / the product.',jp:'私は書きます / その製品について'},{en:'I want to learn / about universal design.',jp:'私は学びたいです / ユニバーサルデザインについて'}],
questions:[{prompt:'1. 話し手はどこへ行きますか。本文から英語で答えなさい。',answer:'city hall',evidence:'Today I go to city hall.',evidenceJp:'今日、私は市役所へ行きます。',reason:'go to の後ろが city hall です。'},{prompt:'2. 何の博覧会がありますか。本文から英語で答えなさい。',answer:'a universal design fair',evidence:'There is a universal design fair there.',evidenceJp:'そこではユニバーサルデザインの博覧会があります。',reason:'There is の後ろが a universal design fair です。'},{prompt:'3. 話し手は何の使い方を知りたいですか。本文から英語で答えなさい。',answer:'a new product',evidence:'I want to know how to use a new product.',evidenceJp:'私は新しい製品の使い方を知りたいです。',reason:'how to use の目的語が a new product です。'},{prompt:'4. ボトルにはどのようなデザインがありますか。本文から英語で1語抜き出しなさい。',answer:'adjustable',evidence:'The bottle has an adjustable design.',evidenceJp:'そのボトルには調節可能なデザインがあります。',reason:'design を説明している語が adjustable です。'},{prompt:'5. 自動ドアは何の一部ですか。本文から英語で答えなさい。',answer:'a public facility',evidence:'The door is part of a public facility.',evidenceJp:'そのドアは公共施設の一部です。',reason:'part of の後ろが a public facility です。'}],
allowedWords:[['how to ~ / city hall / touch / bottle / product / universal / fair / public / facility / automatic / design / adjustable','Unit 5-1: v7 canonical Sheet IDs 1210-1221'],['go / there is / want to / know / use / new / see / open / learn / door / part / many / people / write','G1/Unit0-4 cumulative']],
auditNote:'最新v7正本Unit5 Part1（Sheet ID1210〜1221）を直接照合。how to / city hall / touch / bottle / product / universal / fair / public / facility / automatic / design / adjustableを市役所のユニバーサルデザイン博覧会という自然な流れに統合。Part2のboth A and B / staff等、Read and Thinkのregardless of / wheelchair / accessible等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 5-2']={
id:'V10-NH-G2-U5-2-001',textbook:'ニューホライズン',grade:'2',section:'Unit 5-2',level:'HOP',title:'A Product for Both Hands',
sentences:['At city hall, I meet a staff member.','The staff and I talk about a new product.','It is for both right-handed people and left-handed people.','I tap the product with my right hand.','I also tap it with my left hand.','Both are easy for me.','Thanks to this design, I can use the product.','Over here, there is paper about the product.','I read the paper with the staff member.','The paper has a picture of the design.','I want to show this product to my friend.','I think this design is good for many people.'],
fullTranslation:'「市役所で、私は職員に会います。職員と私は新しい製品について話します。それは右利きの人にも左利きの人にも使えるものです。私は右手でその製品を軽くたたきます。左手でも軽くたたきます。どちらも私には簡単です。このデザインのおかげで、私はその製品を使うことができます。こちらには、その製品についての用紙があります。私は職員とその用紙を読みます。その用紙にはデザインの絵があります。私はこの製品を友達に見せたいです。このデザインは多くの人にとってよいと思います。」',
slashRows:[{en:'At city hall, / I meet / a staff member.',jp:'市役所で / 私は会います / 職員に'},{en:'The staff and I / talk about / a new product.',jp:'職員と私は / 話します / 新しい製品について'},{en:'It is / for both right-handed people / and left-handed people.',jp:'それは〜です / 右利きの人にも / 左利きの人にも'},{en:'I tap / the product / with my right hand.',jp:'私は軽くたたきます / その製品を / 右手で'},{en:'I also tap / it / with my left hand.',jp:'私はまた軽くたたきます / それを / 左手で'},{en:'Both are / easy / for me.',jp:'どちらも〜です / 簡単 / 私には'},{en:'Thanks to this design, / I can use / the product.',jp:'このデザインのおかげで / 私は使えます / その製品を'},{en:'Over here, / there is / paper / about the product.',jp:'こちらには / あります / 用紙が / その製品についての'},{en:'I read / the paper / with the staff member.',jp:'私は読みます / その用紙を / 職員と'},{en:'The paper has / a picture / of the design.',jp:'その用紙にはあります / 絵が / デザインの'},{en:'I want to show / this product / to my friend.',jp:'私は見せたいです / この製品を / 友達に'},{en:'I think / this design is good / for many people.',jp:'私は思います / このデザインはよいと / 多くの人にとって'}],
questions:[{prompt:'1. 話し手は誰に会いますか。本文から英語で答えなさい。',answer:'a staff member',evidence:'At city hall, I meet a staff member.',evidenceJp:'市役所で、私は職員に会います。',reason:'meet の目的語が a staff member です。'},{prompt:'2. 製品はどのような人のためのものですか。本文から英語で答えなさい。',answer:'both right-handed people and left-handed people',evidence:'It is for both right-handed people and left-handed people.',evidenceJp:'それは右利きの人にも左利きの人にも使えるものです。',reason:'both A and B の部分が対象を示しています。'},{prompt:'3. 話し手は最初にどちらの手で製品を軽くたたきますか。本文から英語で答えなさい。',answer:'my right hand',evidence:'I tap the product with my right hand.',evidenceJp:'私は右手でその製品を軽くたたきます。',reason:'with の後ろが my right hand です。'},{prompt:'4. 何のおかげで製品を使えますか。本文から英語で答えなさい。',answer:'this design',evidence:'Thanks to this design, I can use the product.',evidenceJp:'このデザインのおかげで、私はその製品を使うことができます。',reason:'Thanks to の後ろが this design です。'},{prompt:'5. こちらには何がありますか。本文から英語で答えなさい。',answer:'paper about the product',evidence:'Over here, there is paper about the product.',evidenceJp:'こちらには、その製品についての用紙があります。',reason:'there is の後ろが paper about the product です。'}],
allowedWords:[['both A and B / paper / thanks to ~ / right-handed / tap / left-handed / staff / over here','Unit 5-2: v7 canonical Sheet IDs 1222-1229'],['city hall / meet / member / talk about / product / people / hand / easy / can / use / read / picture / design / want to / show / friend / think / many','Unit0-5-1/G1 cumulative']],
auditNote:'最新v7正本Unit5 Part2（Sheet ID1222〜1229）を直接照合。both A and B / paper / thanks to / right-handed / tap / left-handed / staff / over hereを、両利きで使える製品を試す場面に統合。Read and Thinkのbe sure / regardless of / wheelchair / presentation / accessible等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 5-3']={
id:'V10-NH-G2-U5-3-001',textbook:'ニューホライズン',grade:'2',section:'Unit 5-3',level:'HOP',title:'A Professor and Universal Design',
sentences:['I listen to a professor at a universal design fair.','The professor is in a wheelchair.','I am sure his story is important.','In his childhood, a public facility was difficult to use.','At one door, he could not pull it.','This was a difficult situation for him.','Now a useful design can remove this problem.','A young child can use the same design.','People can use it regardless of their situation.','I am sure universal design is useful.','I want to learn how to make a good design.','I write about the professor and the wheelchair.'],
fullTranslation:'「私はユニバーサルデザインの博覧会で教授の話を聞きます。その教授は車いすに乗っています。私は彼の話が大切だと確信しています。彼が子どものころ、ある公共施設は使いにくいものでした。あるドアでは、それを引くことができませんでした。これは彼にとって難しい状況でした。今では、役に立つデザインがこの問題を取り除くことができます。幼い子どもも同じデザインを使えます。人々は自分の状況にかかわらずそれを使うことができます。私はユニバーサルデザインが役に立つと確信しています。私はよいデザインの作り方を学びたいです。教授と車いすについて書きます。」',
slashRows:[{en:'I listen to / a professor / at a universal design fair.',jp:'私は聞きます / 教授の話を / ユニバーサルデザインの博覧会で'},{en:'The professor is / in a wheelchair.',jp:'その教授は〜です / 車いすに乗って'},{en:'I am sure / his story is important.',jp:'私は確信しています / 彼の話は大切だと'},{en:'In his childhood, / a public facility was / difficult to use.',jp:'彼が子どものころ / ある公共施設は〜でした / 使いにくい'},{en:'At one door, / he could not pull / it.',jp:'あるドアで / 彼は引くことができませんでした / それを'},{en:'This was / a difficult situation / for him.',jp:'これは〜でした / 難しい状況 / 彼にとって'},{en:'Now / a useful design can remove / this problem.',jp:'今では / 役に立つデザインが取り除けます / この問題を'},{en:'A young child / can use / the same design.',jp:'幼い子どもも / 使えます / 同じデザインを'},{en:'People can use / it / regardless of their situation.',jp:'人々は使えます / それを / 自分の状況にかかわらず'},{en:'I am sure / universal design is useful.',jp:'私は確信しています / ユニバーサルデザインは役に立つと'},{en:'I want to learn / how to make / a good design.',jp:'私は学びたいです / 作り方を / よいデザインの'},{en:'I write about / the professor / and the wheelchair.',jp:'私は書きます / 教授について / そして車いすについて'}],
questions:[{prompt:'1. 教授は何に乗っていますか。本文から英語で答えなさい。',answer:'a wheelchair',evidence:'The professor is in a wheelchair.',evidenceJp:'その教授は車いすに乗っています。',reason:'in の後ろが a wheelchair です。'},{prompt:'2. 教授が子どものころ、何が使いにくかったですか。本文から英語で答えなさい。',answer:'a public facility',evidence:'In his childhood, a public facility was difficult to use.',evidenceJp:'彼が子どものころ、ある公共施設は使いにくいものでした。',reason:'difficult to use の主語が a public facility です。'},{prompt:'3. ドアで何をすることができませんでしたか。本文から英語で1語抜き出しなさい。',answer:'pull',evidence:'At one door, he could not pull it.',evidenceJp:'あるドアでは、それを引くことができませんでした。',reason:'could not の後ろの動詞が pull です。'},{prompt:'4. 役に立つデザインは何を取り除けますか。本文から英語で答えなさい。',answer:'this problem',evidence:'Now a useful design can remove this problem.',evidenceJp:'今では、役に立つデザインがこの問題を取り除くことができます。',reason:'remove の目的語が this problem です。'},{prompt:'5. 人々は何にかかわらずデザインを使えますか。本文から英語で答えなさい。',answer:'their situation',evidence:'People can use it regardless of their situation.',evidenceJp:'人々は自分の状況にかかわらずそれを使うことができます。',reason:'regardless of の後ろが their situation です。'}],
allowedWords:[['be sure (that) ~ / regardless of ~ / young / remove / useful / found / pull / situation / wheelchair / professor / stair / childhood','Unit 5 Read and Think shared pool first half: v7 canonical Sheet IDs 1230-1241'],['universal / design / fair / public / facility / difficult / use / door / could not / problem / child / people / can / want to / learn / how to / write','Unit0-5-2/G1 cumulative']],
auditNote:'最新v7正本Unit5 Read and Think1,2共通プール（Sheet ID1230〜1253）の前半ID1230〜1241をUnit5-3へ割り当て。be sure / regardless of / young / remove / useful / pull / situation / wheelchair / professor / childhoodを、教授の体験からユニバーサルデザインを考える説明文に統合。後半のsign / center / presentation / barrier / baggage / ability / baby / disabled / the elderly / American / spread / accessibleは先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G2_NH['Unit 5-4']={
id:'V10-NH-G2-U5-4-001',textbook:'ニューホライズン',grade:'2',section:'Unit 5-4',level:'HOP',title:'A Presentation about Accessible Design',
sentences:['At a center, I give a presentation about universal design.','I show a sign in my presentation.','The sign is easy to see.','An accessible sign can help many people.','A good design can remove a barrier.','It can help a person with baggage.','It can help a family with a baby.','It can help disabled people and the elderly.','It is useful regardless of ability.','I also talk about an American professor.','I want to spread the idea of universal design too.','The center has an accessible design.','I am sure this design is good for everyone.'],
fullTranslation:'「あるセンターで、私はユニバーサルデザインについて発表します。発表の中で標識を見せます。その標識は見やすいです。使いやすい標識は多くの人を助けることができます。よいデザインは障壁を取り除くことができます。手荷物を持つ人を助けることもできます。赤ん坊のいる家族を助けることもできます。体の不自由な人々やお年寄りを助けることもできます。それは能力にかかわらず役に立ちます。私はアメリカの教授についても話します。私もユニバーサルデザインの考えを広めたいです。そのセンターには使いやすいデザインがあります。私はこのデザインがすべての人にとってよいと確信しています。」',
slashRows:[{en:'At a center, / I give / a presentation / about universal design.',jp:'あるセンターで / 私はします / 発表を / ユニバーサルデザインについて'},{en:'I show / a sign / in my presentation.',jp:'私は見せます / 標識を / 発表の中で'},{en:'The sign is / easy to see.',jp:'その標識は〜です / 見やすい'},{en:'An accessible sign / can help / many people.',jp:'使いやすい標識は / 助けることができます / 多くの人を'},{en:'A good design / can remove / a barrier.',jp:'よいデザインは / 取り除けます / 障壁を'},{en:'It can help / a person / with baggage.',jp:'それは助けることができます / 人を / 手荷物を持つ'},{en:'It can help / a family / with a baby.',jp:'それは助けることができます / 家族を / 赤ん坊のいる'},{en:'It can help / disabled people / and the elderly.',jp:'それは助けることができます / 体の不自由な人々を / そしてお年寄りを'},{en:'It is / useful / regardless of ability.',jp:'それは〜です / 役に立つ / 能力にかかわらず'},{en:'I also talk about / an American professor.',jp:'私はまた話します / アメリカの教授について'},{en:'I want to spread / the idea / of universal design / too.',jp:'私は広めたいです / 考えを / ユニバーサルデザインの / 私も'},{en:'The center has / an accessible design.',jp:'そのセンターにはあります / 使いやすいデザインが'},{en:'I am sure / this design is good / for everyone.',jp:'私は確信しています / このデザインはよいと / すべての人にとって'}],
questions:[{prompt:'1. 話し手は何について発表しますか。本文から英語で答えなさい。',answer:'universal design',evidence:'At a center, I give a presentation about universal design.',evidenceJp:'あるセンターで、私はユニバーサルデザインについて発表します。',reason:'about の後ろが universal design です。'},{prompt:'2. 何が多くの人を助けることができますか。本文から英語で答えなさい。',answer:'an accessible sign',evidence:'An accessible sign can help many people.',evidenceJp:'使いやすい標識は多くの人を助けることができます。',reason:'can help の主語が An accessible sign です。'},{prompt:'3. よいデザインは何を取り除けますか。本文から英語で答えなさい。',answer:'a barrier',evidence:'A good design can remove a barrier.',evidenceJp:'よいデザインは障壁を取り除くことができます。',reason:'remove の目的語が a barrier です。'},{prompt:'4. デザインはどのような人々を助けますか。本文から英語で答えなさい。',answer:'disabled people and the elderly',evidence:'It can help disabled people and the elderly.',evidenceJp:'体の不自由な人々やお年寄りを助けることもできます。',reason:'help の目的語が disabled people and the elderly です。'},{prompt:'5. 話し手は何を広めたいですか。本文から英語で答えなさい。',answer:'the idea of universal design',evidence:'I want to spread the idea of universal design too.',evidenceJp:'私もユニバーサルデザインの考えを広めたいです。',reason:'spread の目的語が the idea of universal design です。'}],
allowedWords:[['sign / center / presentation / barrier / baggage / ability / baby / disabled / the elderly / American / spread-spread / accessible','Unit 5 Read and Think shared pool second half: v7 canonical Sheet IDs 1242-1253'],['be sure / regardless of / useful / remove / professor / universal / design / easy / see / help / many / people / person / family / talk about / want to / idea / good / everyone','Unit0-5-3/G1 cumulative']],
auditNote:'最新v7正本Unit5 Read and Think1,2共通プール（Sheet ID1230〜1253）の後半ID1242〜1253をUnit5-4へ割り当て。sign / center / presentation / barrier / baggage / ability / baby / disabled / the elderly / American / spread / accessibleを一つの発表文に統合。Unit6のthan / quiz / more / survey / graph / feedback等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
