window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 5-1']={
id:'V10-NH-G3-U5-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 5-1',level:'HOP',title:'Learning about a National Leader',
sentences:['Today we study a national leader.','The leader was born in a small town.','We see an image of the leader on a note.','I find the image on the internet.','We print the image for our class.','We read about non-violence.','Non-violence is an important idea.','The leader can influence people greatly.','A national leader can change a country.','One person asks about the note.','We talk about what makes a good leader.','I want to learn more about the person.'],
fullTranslation:'「今日、私たちは国の指導者について学びます。その指導者は小さな町で生まれました。私たちは紙幣にあるその指導者の肖像を見ます。私はインターネットでその肖像を見つけます。私たちは授業のためにその肖像を印刷します。私たちは非暴力について読みます。非暴力は大切な考えです。その指導者は人々に大きな影響を与えることができます。国の指導者は国を変えることができます。1人の人がその紙幣についてたずねます。私たちは何がよい指導者を作るのかについて話します。私はその人物についてもっと学びたいです。」',
slashRows:[{en:'Today / we study / a national leader.',jp:'今日 / 私たちは学びます / 国の指導者について'},{en:'The leader was born / in a small town.',jp:'その指導者は生まれました / 小さな町で'},{en:'We see / an image / of the leader / on a note.',jp:'私たちは見ます / 肖像を / 指導者の / 紙幣にある'},{en:'I find / the image / on the internet.',jp:'私は見つけます / その肖像を / インターネットで'},{en:'We print / the image / for our class.',jp:'私たちは印刷します / その肖像を / 授業のために'},{en:'We read about / non-violence.',jp:'私たちは読みます / 非暴力について'},{en:'Non-violence is / an important idea.',jp:'非暴力は〜です / 大切な考え'},{en:'The leader can influence / people / greatly.',jp:'その指導者は影響を与えることができます / 人々に / 大いに'},{en:'A national leader / can change / a country.',jp:'国の指導者は / 変えることができます / 国を'},{en:'One person / asks about / the note.',jp:'1人の人が / たずねます / その紙幣について'},{en:'We talk about / what makes / a good leader.',jp:'私たちは話します / 何が作るかについて / よい指導者を'},{en:'I want to learn / more / about the person.',jp:'私は学びたいです / もっと / その人物について'}],
questions:[{prompt:'1. 何について学びますか。本文から英語で答えなさい。',answer:'a national leader',evidence:'Today we study a national leader.',evidenceJp:'今日、私たちは国の指導者について学びます。',reason:'study の目的語が a national leader です。'},{prompt:'2. 指導者はどこで生まれましたか。本文から英語で答えなさい。',answer:'in a small town',evidence:'The leader was born in a small town.',evidenceJp:'その指導者は小さな町で生まれました。',reason:'生まれた場所を表す部分が in a small town です。'},{prompt:'3. 紙幣には何がありますか。本文から英語で答えなさい。',answer:'an image of the leader',evidence:'We see an image of the leader on a note.',evidenceJp:'私たちは紙幣にあるその指導者の肖像を見ます。',reason:'see の目的語が an image of the leader です。'},{prompt:'4. どこでその肖像を見つけますか。本文から英語で答えなさい。',answer:'on the internet',evidence:'I find the image on the internet.',evidenceJp:'私はインターネットでその肖像を見つけます。',reason:'場所を表す部分が on the internet です。'},{prompt:'5. 指導者は人々にどのように影響を与えることができますか。本文から英語で1語抜き出しなさい。',answer:'greatly',evidence:'The leader can influence people greatly.',evidenceJp:'その指導者は人々に大きな影響を与えることができます。',reason:'influence の程度を表す語が greatly です。'}],
allowedWords:[['be born / note / person / non-violence / national / leader / on the internet / image / print / greatly','Unit 5 Part1: v7 canonical Sheet IDs 1931-1940'],['today / study / small / town / see / find / class / read about / important / idea / can / influence / people / change / country / ask about / talk about / good / want to / learn / more','Unit0-4/G1-G2 cumulative']],
auditNote:'最新v7正本Unit5 Part1（Sheet ID1931〜1940）を直接照合。be born / note / person / non-violence / national / leader / on the internet / image / print / greatlyを、国の指導者について調べる活動に統合。Part2のfight / fast / protest / human rights / independence等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 5-2']={
id:'V10-NH-G3-U5-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 5-2',level:'HOP',title:'A Fight for Human Rights',
sentences:['We read about a fight for human rights.','A leader can fight for human rights.','Some people go on a fast.','The fast is tough.','People protest without violence.','There is little violence in this protest.','People ask for a right.','They want independence.','They want more for their country.','The protest is difficult but important.','People do not use violence.','We talk about non-violence and independence.'],
fullTranslation:'「私たちは人権のためのたたかいについて読みます。指導者は人権のためにたたかうことができます。断食をする人もいます。その断食はつらいものです。人々は暴力を使わずに抗議します。この抗議には暴力がほとんどありません。人々は1つの権利を求めます。彼らは独立を望みます。彼らは自分たちの国のためにもっと多くのものを望みます。その抗議は困難ですが大切です。人々は暴力を使いません。私たちは非暴力と独立について話します。」',
slashRows:[{en:'We read about / a fight / for human rights.',jp:'私たちは読みます / たたかいについて / 人権のための'},{en:'A leader / can fight / for human rights.',jp:'指導者は / たたかうことができます / 人権のために'},{en:'Some people / go on / a fast.',jp:'何人かの人は / します / 断食を'},{en:'The fast is / tough.',jp:'その断食は〜です / つらい'},{en:'People protest / without violence.',jp:'人々は抗議します / 暴力を使わずに'},{en:'There is / little violence / in this protest.',jp:'あります / ほとんど暴力がない状態が / この抗議に'},{en:'People ask for / a right.',jp:'人々は求めます / 1つの権利を'},{en:'They want / independence.',jp:'彼らは望みます / 独立を'},{en:'They want / more / for their country.',jp:'彼らは望みます / もっと多くのものを / 自分たちの国のために'},{en:'The protest is / difficult / but important.',jp:'その抗議は〜です / 困難 / しかし大切'},{en:'People do not use / violence.',jp:'人々は使いません / 暴力を'},{en:'We talk about / non-violence and independence.',jp:'私たちは話します / 非暴力と独立について'}],
questions:[{prompt:'1. 何のためのたたかいについて読みますか。本文から英語で答えなさい。',answer:'human rights',evidence:'We read about a fight for human rights.',evidenceJp:'私たちは人権のためのたたかいについて読みます。',reason:'for の後ろが human rights です。'},{prompt:'2. 何をする人がいますか。本文から英語で答えなさい。',answer:'a fast',evidence:'Some people go on a fast.',evidenceJp:'断食をする人もいます。',reason:'go on の後ろが a fast です。'},{prompt:'3. 断食はどうですか。本文から英語で1語抜き出しなさい。',answer:'tough',evidence:'The fast is tough.',evidenceJp:'その断食はつらいものです。',reason:'fast の状態を表す語が tough です。'},{prompt:'4. 人々は何を望みますか。本文から英語で答えなさい。',answer:'independence',evidence:'They want independence.',evidenceJp:'彼らは独立を望みます。',reason:'want の目的語が independence です。'},{prompt:'5. 人々は何を使いませんか。本文から英語で答えなさい。',answer:'violence',evidence:'People do not use violence.',evidenceJp:'人々は暴力を使いません。',reason:'use の目的語が violence です。'}],
allowedWords:[['fight / fast / go on ~ / tough / protest / little ~ / violence / more / right / human rights / independence','Unit 5 Part2: v7 canonical Sheet IDs 1941-1951'],['leader / can / some / people / without / there is / ask for / want / country / difficult / important / use / talk about / non-violence','Unit0-5-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit5 Part2（Sheet ID1941〜1951）を直接照合。fight / fast / go on / tough / protest / little / violence / more / right / human rights / independenceを、非暴力による権利運動の説明に統合。Read and Think1のstood / law / lawyer / jail / discrimination等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 5-3']={
id:'V10-NH-G3-U5-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 5-3',level:'HOP',title:'Standing against Discrimination',
sentences:['At that time, a lawyer stood against discrimination.','The law was not fair.','The lawyer can lead a movement.','The movement can be effective.','Even if the rule is hard, people do not accept discrimination.','Some people go out together.','A leader can go to jail.','Police can arrest a leader.','People want to speak freely.','People accept a new law.','The movement can change an unfair rule.','We learn how a movement can lead people.'],
fullTranslation:'「その当時、ある弁護士が差別に反対して立ち上がりました。その法律は公平ではありませんでした。その弁護士は運動を導くことができます。その運動は効果的なものになりえます。たとえ支配が厳しくても、人々は差別を受け入れません。外へ出ていっしょに行動する人もいます。指導者が刑務所へ行くこともあります。警察が指導者を逮捕することもあります。人々は自由に話したいと望みます。人々は新しい法律を受け入れます。その運動は不公平な支配を変えることができます。私たちは運動がどのように人々を導くかを学びます。」',
slashRows:[{en:'At that time, / a lawyer stood / against discrimination.',jp:'その当時 / ある弁護士が立ち上がりました / 差別に反対して'},{en:'The law was / not fair.',jp:'その法律は〜でした / 公平ではない'},{en:'The lawyer / can lead / a movement.',jp:'その弁護士は / 導くことができます / 運動を'},{en:'The movement / can be / effective.',jp:'その運動は / 〜になれます / 効果的に'},{en:'Even if the rule is hard, / people do not accept / discrimination.',jp:'たとえ支配が厳しくても / 人々は受け入れません / 差別を'},{en:'Some people / go out / together.',jp:'何人かの人は / 外へ出ます / いっしょに'},{en:'A leader / can go to / jail.',jp:'指導者は / 行くことがあります / 刑務所へ'},{en:'Police can arrest / a leader.',jp:'警察は逮捕することがあります / 指導者を'},{en:'People want to speak / freely.',jp:'人々は話したいです / 自由に'},{en:'People accept / a new law.',jp:'人々は受け入れます / 新しい法律を'},{en:'The movement / can change / an unfair rule.',jp:'その運動は / 変えることができます / 不公平な支配を'},{en:'We learn / how a movement can lead / people.',jp:'私たちは学びます / 運動がどのように導くか / 人々を'}],
questions:[{prompt:'1. 誰が差別に反対して立ち上がりましたか。本文から英語で答えなさい。',answer:'a lawyer',evidence:'At that time, a lawyer stood against discrimination.',evidenceJp:'その当時、ある弁護士が差別に反対して立ち上がりました。',reason:'stood の主語が a lawyer です。'},{prompt:'2. 法律は公平でしたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'The law was not fair.',evidenceJp:'その法律は公平ではありませんでした。',reason:'not fair とあるので No です。'},{prompt:'3. 弁護士は何を導くことができますか。本文から英語で答えなさい。',answer:'a movement',evidence:'The lawyer can lead a movement.',evidenceJp:'その弁護士は運動を導くことができます。',reason:'lead の目的語が a movement です。'},{prompt:'4. 人々は何を受け入れませんか。本文から英語で答えなさい。',answer:'discrimination',evidence:'Even if the rule is hard, people do not accept discrimination.',evidenceJp:'たとえ支配が厳しくても、人々は差別を受け入れません。',reason:'accept の目的語が discrimination です。'},{prompt:'5. 人々はどのように話したいですか。本文から英語で1語抜き出しなさい。',answer:'freely',evidence:'People want to speak freely.',evidenceJp:'人々は自由に話したいと望みます。',reason:'speak の仕方を表す語が freely です。'}],
allowedWords:[['stand-stood / rule / law / movement / at that time / lawyer / go out / jail / even if ~ / discrimination / lead / effective / arrest / freely / accept','Unit 5 Read and Think1: v7 canonical Sheet IDs 1952-1966'],['against / fair / can / hard / people / some / together / leader / police / want to / speak / new / change / unfair / learn / how','Unit0-5-2/G1-G2 cumulative']],
auditNote:'最新v7正本Unit5 Read and Think1（Sheet ID1952〜1966）を直接照合。stood / rule / law / movement / at that time / lawyer / go out / jail / even if / discrimination / lead / effective / arrest / freely / acceptを差別に反対する運動の説明に統合。Read and Think2のproduce / tax / legacy / colony / peaceful等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 5-4']={
id:'V10-NH-G3-U5-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 5-4',level:'HOP',title:'A Peaceful Way to Change a Tax',
sentences:['In those days, a colony had an expensive tax.','A government can put a tax on food.','This can make food expensive.','People look for a way to change the tax.','Thousands of people join a peaceful movement.','They walk one kilometer together.','The movement can spread.','A colony can produce food.','People do not want the tax.','They remember the movement as a legacy.','The peaceful idea can spread to another country.','This is one way to change a difficult situation.'],
fullTranslation:'「そのころ、ある植民地には高い税がありました。政府は食べ物に税を課すことができます。これは食べ物を高価にすることがあります。人々は税を変える方法を探します。何千もの人々が平和的な運動に加わります。彼らはいっしょに1キロメートル歩きます。その運動は広がることがあります。植民地は食べ物を生産できます。人々はその税を望みません。彼らはその運動を遺産として覚えています。その平和的な考えは別の国へ広がることがあります。これは困難な状況を変える1つの方法です。」',
slashRows:[{en:'In those days, / a colony had / an expensive tax.',jp:'そのころ / ある植民地にはありました / 高い税が'},{en:'A government / can put / a tax / on food.',jp:'政府は / 課すことができます / 税を / 食べ物に'},{en:'This can make / food / expensive.',jp:'これは〜にすることがあります / 食べ物を / 高価に'},{en:'People look for / a way to change / the tax.',jp:'人々は探します / 変える方法を / その税を'},{en:'Thousands of people / join / a peaceful movement.',jp:'何千もの人々は / 加わります / 平和的な運動に'},{en:'They walk / one kilometer / together.',jp:'彼らは歩きます / 1キロメートル / いっしょに'},{en:'The movement / can spread.',jp:'その運動は / 広がることがあります'},{en:'A colony / can produce / food.',jp:'植民地は / 生産できます / 食べ物を'},{en:'People do not want / the tax.',jp:'人々は望みません / その税を'},{en:'They remember / the movement / as a legacy.',jp:'彼らは覚えています / その運動を / 遺産として'},{en:'The peaceful idea / can spread / to another country.',jp:'その平和的な考えは / 広がることがあります / 別の国へ'},{en:'This is / one way to change / a difficult situation.',jp:'これは〜です / 変える1つの方法 / 困難な状況を'}],
questions:[{prompt:'1. 植民地にはどのような税がありましたか。本文から英語で答えなさい。',answer:'an expensive tax',evidence:'In those days, a colony had an expensive tax.',evidenceJp:'そのころ、ある植民地には高い税がありました。',reason:'had の目的語が an expensive tax です。'},{prompt:'2. 政府は何に税を課すことができますか。本文から英語で答えなさい。',answer:'food',evidence:'A government can put a tax on food.',evidenceJp:'政府は食べ物に税を課すことができます。',reason:'on の後ろが food です。'},{prompt:'3. 何千もの人々は何に加わりますか。本文から英語で答えなさい。',answer:'a peaceful movement',evidence:'Thousands of people join a peaceful movement.',evidenceJp:'何千もの人々が平和的な運動に加わります。',reason:'join の目的語が a peaceful movement です。'},{prompt:'4. どのくらい歩きますか。本文から英語で答えなさい。',answer:'one kilometer',evidence:'They walk one kilometer together.',evidenceJp:'彼らはいっしょに1キロメートル歩きます。',reason:'距離を表す部分が one kilometer です。'},{prompt:'5. 何を遺産として覚えていますか。本文から英語で答えなさい。',answer:'the movement',evidence:'They remember the movement as a legacy.',evidenceJp:'彼らはその運動を遺産として覚えています。',reason:'remember の目的語が the movement です。'}],
allowedWords:[['produce / put / expensive / tax / way to ~ / legacy / thousands of ~ / kilometer / in those days / colony / spread / peaceful','Unit 5 Read and Think2: v7 canonical Sheet IDs 1967-1978'],['movement / had / government / can / food / make A B / people / look for / change / join / walk / together / want / remember / idea / another / country / difficult / situation','Unit0-5-3/G1-G2 cumulative']],
auditNote:'最新v7正本Unit5 Read and Think2（Sheet ID1967〜1978）を直接照合。produce / put / expensive / tax / way to / legacy / thousands of / kilometer / in those days / colony / spread / peacefulを、税を平和的に変える運動の説明に統合。Unit6のwish / supply / backpack / abroad / donate / so far / connect等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
