window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 6-1']={
id:'V10-NH-G3-U6-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 6-1',level:'HOP',title:'An Unused Backpack for a New Project',
sentences:['I wish to help a student abroad.','We have an unused backpack at school.','A school supply is in the backpack.','We can use the backpack for a project.','I felt happy about this idea.','We run a small project in our class.','The unused backpack is still good.','We put one supply in it.','We talk about life abroad.','I wish the backpack could help a student.','Our class can run this project together.','I felt ready to start.'],
fullTranslation:'「私は海外の生徒を助けたいと願っています。学校に使われていないリュックサックがあります。リュックサックの中には学用品が1つあります。私たちはそのリュックサックをプロジェクトに使えます。私はこの考えをうれしく感じました。私たちはクラスで小さなプロジェクトを運営します。その使われていないリュックサックはまだよい状態です。私たちはその中に学用品を1つ入れます。海外の生活について話します。私はそのリュックサックが生徒の助けになればいいと思います。私たちのクラスはいっしょにこのプロジェクトを運営できます。私は始める準備ができたと感じました。」',
slashRows:[{en:'I wish / to help / a student / abroad.',jp:'私は願います / 助けたいと / 生徒を / 海外の'},{en:'We have / an unused backpack / at school.',jp:'私たちにはあります / 使われていないリュックサックが / 学校に'},{en:'A school supply is / in the backpack.',jp:'学用品が1つあります / リュックサックの中に'},{en:'We can use / the backpack / for a project.',jp:'私たちは使えます / そのリュックサックを / プロジェクトに'},{en:'I felt / happy / about this idea.',jp:'私は感じました / うれしく / この考えについて'},{en:'We run / a small project / in our class.',jp:'私たちは運営します / 小さなプロジェクトを / クラスで'},{en:'The unused backpack is / still good.',jp:'その使われていないリュックサックは〜です / まだよい状態'},{en:'We put / one supply / in it.',jp:'私たちは入れます / 学用品を1つ / その中に'},{en:'We talk about / life / abroad.',jp:'私たちは話します / 生活について / 海外の'},{en:'I wish / the backpack / could help / a student.',jp:'私は願います / そのリュックサックが / 助けられればと / 生徒を'},{en:'Our class / can run / this project / together.',jp:'私たちのクラスは / 運営できます / このプロジェクトを / いっしょに'},{en:'I felt / ready / to start.',jp:'私は感じました / 準備ができたと / 始めるために'}],
questions:[{prompt:'1. 誰を助けたいと願っていますか。本文から英語で答えなさい。',answer:'a student abroad',evidence:'I wish to help a student abroad.',evidenceJp:'私は海外の生徒を助けたいと願っています。',reason:'help の目的語が a student で、abroad が場所を示しています。'},{prompt:'2. 学校には何がありますか。本文から英語で答えなさい。',answer:'an unused backpack',evidence:'We have an unused backpack at school.',evidenceJp:'学校に使われていないリュックサックがあります。',reason:'have の目的語が an unused backpack です。'},{prompt:'3. リュックサックの中には何がありますか。本文から英語で答えなさい。',answer:'a school supply',evidence:'A school supply is in the backpack.',evidenceJp:'リュックサックの中には学用品が1つあります。',reason:'主語が A school supply です。'},{prompt:'4. 話し手はこの考えについてどう感じましたか。本文から英語で1語抜き出しなさい。',answer:'happy',evidence:'I felt happy about this idea.',evidenceJp:'私はこの考えをうれしく感じました。',reason:'felt の後ろが happy です。'},{prompt:'5. クラスでは何を運営しますか。本文から英語で答えなさい。',answer:'a small project',evidence:'We run a small project in our class.',evidenceJp:'私たちはクラスで小さなプロジェクトを運営します。',reason:'run の目的語が a small project です。'}],
allowedWords:[['wish / supply / feel-felt-felt / backpack / run / abroad / unused','Unit 6 Part1,2 shared pool first half: v7 canonical Sheet IDs 2009-2015'],['help / student / have / school / can / use / project / happy / idea / small / class / still / good / put / one / talk about / life / could / together / ready / start','Unit0-5/G1-G2 cumulative']],
auditNote:'最新v7正本Unit6 Part1,2共通プール（Sheet ID2009〜2021）の前半ID2009〜2015をUnit6-1へ割り当て。wish / supply / felt / backpack / run / abroad / unusedを、使われていないリュックサックを活用するプロジェクトの導入に統合。後半のoverseas / donate / this way / so far / connect / Afghanistanは先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 6-2']={
id:'V10-NH-G3-U6-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 6-2',level:'HOP',title:'Sending a Backpack Overseas',
sentences:['We donate an unused backpack overseas.','We send a school supply with it.','This way, we can help a student.','So far, our project is small.','We want to connect with people overseas.','Our class learns about Afghanistan.','Afghanistan is far from Japan.','We donate one backpack from our school.','This way, our class can connect with another place.','We talk about life in Afghanistan.','So far, we have one clear goal.','I hope our project can help someone overseas.'],
fullTranslation:'「私たちは使われていないリュックサックを海外へ寄付します。学用品もいっしょに送ります。このようにして、私たちは生徒を助けることができます。今までのところ、私たちのプロジェクトは小さいものです。私たちは海外の人々とつながりたいです。私たちのクラスはアフガニスタンについて学びます。アフガニスタンは日本から遠く離れています。私たちは学校からリュックサックを1つ寄付します。このようにして、私たちのクラスは別の場所とつながることができます。私たちはアフガニスタンの生活について話します。今までのところ、私たちには明確な目標が1つあります。このプロジェクトが海外の誰かを助けられることを願います。」',
slashRows:[{en:'We donate / an unused backpack / overseas.',jp:'私たちは寄付します / 使われていないリュックサックを / 海外へ'},{en:'We send / a school supply / with it.',jp:'私たちは送ります / 学用品を / それといっしょに'},{en:'This way, / we can help / a student.',jp:'このようにして / 私たちは助けられます / 生徒を'},{en:'So far, / our project is / small.',jp:'今までのところ / 私たちのプロジェクトは〜です / 小さい'},{en:'We want to connect / with people / overseas.',jp:'私たちはつながりたいです / 人々と / 海外の'},{en:'Our class learns about / Afghanistan.',jp:'私たちのクラスは学びます / アフガニスタンについて'},{en:'Afghanistan is / far from Japan.',jp:'アフガニスタンは〜です / 日本から遠い'},{en:'We donate / one backpack / from our school.',jp:'私たちは寄付します / リュックサックを1つ / 私たちの学校から'},{en:'This way, / our class can connect / with another place.',jp:'このようにして / 私たちのクラスはつながれます / 別の場所と'},{en:'We talk about / life / in Afghanistan.',jp:'私たちは話します / 生活について / アフガニスタンの'},{en:'So far, / we have / one clear goal.',jp:'今までのところ / 私たちにはあります / 明確な目標が1つ'},{en:'I hope / our project can help / someone / overseas.',jp:'私は願います / 私たちのプロジェクトが助けられることを / 誰かを / 海外の'}],
questions:[{prompt:'1. 何を海外へ寄付しますか。本文から英語で答えなさい。',answer:'an unused backpack',evidence:'We donate an unused backpack overseas.',evidenceJp:'私たちは使われていないリュックサックを海外へ寄付します。',reason:'donate の目的語が an unused backpack です。'},{prompt:'2. このようにして誰を助けることができますか。本文から英語で答えなさい。',answer:'a student',evidence:'This way, we can help a student.',evidenceJp:'このようにして、私たちは生徒を助けることができます。',reason:'help の目的語が a student です。'},{prompt:'3. どこの国について学びますか。本文から英語で答えなさい。',answer:'Afghanistan',evidence:'Our class learns about Afghanistan.',evidenceJp:'私たちのクラスはアフガニスタンについて学びます。',reason:'learns about の後ろが Afghanistan です。'},{prompt:'4. 何とつながりたいですか。本文から英語で答えなさい。',answer:'people overseas',evidence:'We want to connect with people overseas.',evidenceJp:'私たちは海外の人々とつながりたいです。',reason:'connect with の後ろが people overseas です。'},{prompt:'5. 今までのところ、何が1つありますか。本文から英語で答えなさい。',answer:'one clear goal',evidence:'So far, we have one clear goal.',evidenceJp:'今までのところ、私たちには明確な目標が1つあります。',reason:'have の目的語が one clear goal です。'}],
allowedWords:[['overseas / donate / this way / so far / connect / Afghanistan','Unit 6 Part1,2 shared pool second half: v7 canonical Sheet IDs 2016-2021'],['unused / backpack / supply / send / school / can / help / student / project / small / want to / people / class / learn about / far from / Japan / one / another / place / talk about / life / have / clear / goal / hope / someone','Unit0-6-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit6 Part1,2共通プール後半（Sheet ID2016〜2021）をUnit6-2へ割り当て。overseas / donate / this way / so far / connect / Afghanistanを、リュックサックを海外へ届ける活動に統合。Read and Think1のservice / globe / border / illiterate / be ready for等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 6-3']={
id:'V10-NH-G3-U6-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 6-3',level:'HOP',title:'A Service across a Border',
sentences:['We run a service program at school.','We look at a globe.','We imagine a family in another country.','A son and a daughter want to study.','An illiterate person may need support.','Most of our class is ready for the service.','Through the service, we connect with people.','We can send a book by air.','The border is far away.','This service can definitely help.','We imagine how education can connect people.','Our class is ready for another service project.'],
fullTranslation:'「私たちは学校で奉仕活動のプログラムを運営します。地球儀を見ます。別の国の家族を想像します。息子と娘は勉強したいと思っています。読み書きのできない人には支援が必要かもしれません。クラスのほとんどがその奉仕活動の準備ができています。その奉仕活動を通して、私たちは人々とつながります。私たちは本を空輸できます。国境は遠く離れています。この奉仕活動はきっと助けになります。教育がどのように人々をつなぐことができるかを想像します。私たちのクラスは別の奉仕活動プロジェクトへの準備ができています。」',
slashRows:[{en:'We run / a service program / at school.',jp:'私たちは運営します / 奉仕活動のプログラムを / 学校で'},{en:'We look at / a globe.',jp:'私たちは見ます / 地球儀を'},{en:'We imagine / a family / in another country.',jp:'私たちは想像します / 家族を / 別の国の'},{en:'A son and a daughter / want to study.',jp:'息子と娘は / 勉強したいです'},{en:'An illiterate person / may need / support.',jp:'読み書きのできない人は / 必要かもしれません / 支援が'},{en:'Most of our class / is ready for / the service.',jp:'私たちのクラスのほとんどは / 準備ができています / その奉仕活動への'},{en:'Through the service, / we connect / with people.',jp:'その奉仕活動を通して / 私たちはつながります / 人々と'},{en:'We can send / a book / by air.',jp:'私たちは送ることができます / 本を / 空路で'},{en:'The border is / far away.',jp:'その国境は〜です / 遠く離れている'},{en:'This service / can definitely help.',jp:'この奉仕活動は / きっと助けになります'},{en:'We imagine / how education can connect / people.',jp:'私たちは想像します / 教育がどのようにつなぐか / 人々を'},{en:'Our class is / ready for / another service project.',jp:'私たちのクラスは〜です / 準備ができている / 別の奉仕活動プロジェクトへの'}],
questions:[{prompt:'1. 学校で何を運営しますか。本文から英語で答えなさい。',answer:'a service program',evidence:'We run a service program at school.',evidenceJp:'私たちは学校で奉仕活動のプログラムを運営します。',reason:'run の目的語が a service program です。'},{prompt:'2. 何を見ますか。本文から英語で答えなさい。',answer:'a globe',evidence:'We look at a globe.',evidenceJp:'地球儀を見ます。',reason:'look at の目的語が a globe です。'},{prompt:'3. 読み書きのできない人には何が必要かもしれませんか。本文から英語で答えなさい。',answer:'support',evidence:'An illiterate person may need support.',evidenceJp:'読み書きのできない人には支援が必要かもしれません。',reason:'need の目的語が support です。'},{prompt:'4. クラスのほとんどは何への準備ができていますか。本文から英語で答えなさい。',answer:'the service',evidence:'Most of our class is ready for the service.',evidenceJp:'クラスのほとんどがその奉仕活動の準備ができています。',reason:'ready for の後ろが the service です。'},{prompt:'5. 何を空輸できますか。本文から英語で答えなさい。',answer:'a book',evidence:'We can send a book by air.',evidenceJp:'私たちは本を空輸できます。',reason:'send の目的語が a book です。'}],
allowedWords:[['service / definitely / globe / imagine / border / son / run / air / daughter / illiterate / most of ~ / through / be ready for ~','Unit 6 Read and Think1: v7 canonical Sheet IDs 2022-2034'],['program / school / look at / family / another / country / want to / study / person / may / need / support / class / connect / people / can / send / book / far away / help / how / education / project','Unit0-6-2/G1-G2 cumulative']],
auditNote:'最新v7正本Unit6 Read and Think1（Sheet ID2022〜2034）を直接照合。service / definitely / globe / imagine / border / son / run / air / daughter / illiterate / most of / through / be ready forを、国境を越える奉仕活動の説明に統合。Read and Think2のin the open air / interdependent / import / trade / beyond / relationship等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 6-4']={
id:'V10-NH-G3-U6-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 6-4',level:'HOP',title:'Trade and an Interdependent World',
sentences:['A person can sell a coat in the open air.','One shop sold a coat yesterday.','Trade can support daily life.','In fact, a country can depend on another country.','A third country can import a product.','Water can surround an island.','People in different places are interdependent.','There is one exception.','Trade can go beyond a border.','This relationship is quite important for survival.','We encourage a student to study trade.','A daily relationship can connect people.','I think trade can support life beyond a border.'],
fullTranslation:'「人は屋外でコートを売ることができます。ある店は昨日コートを売りました。貿易は日々の生活を支えることができます。実際、ある国は別の国に依存することがあります。3番目の国が製品を輸入することもできます。水が島を囲むことがあります。異なる場所の人々は相互依存しています。1つの例外があります。貿易は国境を越えることができます。この関係は生存にとってかなり重要です。私たちは生徒に貿易を学ぶよう励まします。日々の関係は人々をつなぐことができます。私は貿易が国境を越えて生活を支えられると思います。」',
slashRows:[{en:'A person / can sell / a coat / in the open air.',jp:'人は / 売ることができます / コートを / 屋外で'},{en:'One shop / sold / a coat / yesterday.',jp:'ある店は / 売りました / コートを / 昨日'},{en:'Trade can support / daily life.',jp:'貿易は支えることができます / 日々の生活を'},{en:'In fact, / a country / can depend on / another country.',jp:'実際 / ある国は / 依存することがあります / 別の国に'},{en:'A third country / can import / a product.',jp:'3番目の国は / 輸入できます / 製品を'},{en:'Water can surround / an island.',jp:'水は囲むことがあります / 島を'},{en:'People in different places / are / interdependent.',jp:'異なる場所の人々は / 〜です / 相互依存している'},{en:'There is / one exception.',jp:'あります / 1つの例外が'},{en:'Trade can go / beyond a border.',jp:'貿易は越えることができます / 国境を越えて'},{en:'This relationship is / quite important / for survival.',jp:'この関係は〜です / かなり重要 / 生存にとって'},{en:'We encourage / a student / to study trade.',jp:'私たちは励まします / 生徒に / 貿易を学ぶように'},{en:'A daily relationship / can connect / people.',jp:'日々の関係は / つなぐことができます / 人々を'},{en:'I think / trade can support / life / beyond a border.',jp:'私は思います / 貿易は支えられると / 生活を / 国境を越えて'}],
questions:[{prompt:'1. 屋外で何を売ることができますか。本文から英語で答えなさい。',answer:'a coat',evidence:'A person can sell a coat in the open air.',evidenceJp:'人は屋外でコートを売ることができます。',reason:'sell の目的語が a coat です。'},{prompt:'2. 昨日、店は何を売りましたか。本文から英語で答えなさい。',answer:'a coat',evidence:'One shop sold a coat yesterday.',evidenceJp:'ある店は昨日コートを売りました。',reason:'sold の目的語が a coat です。'},{prompt:'3. 国は何に依存することがありますか。本文から英語で答えなさい。',answer:'another country',evidence:'In fact, a country can depend on another country.',evidenceJp:'実際、ある国は別の国に依存することがあります。',reason:'depend on の後ろが another country です。'},{prompt:'4. 3番目の国は何を輸入できますか。本文から英語で答えなさい。',answer:'a product',evidence:'A third country can import a product.',evidenceJp:'3番目の国が製品を輸入することもできます。',reason:'import の目的語が a product です。'},{prompt:'5. この関係は何にとって重要ですか。本文から英語で答えなさい。',answer:'survival',evidence:'This relationship is quite important for survival.',evidenceJp:'この関係は生存にとってかなり重要です。',reason:'for の後ろが survival です。'}],
allowedWords:[['in the open air / encourage A to B / sell-sold / support / exception / in fact / coat / depend on ~ / third / surround / interdependent / import / daily / trade / quite / survival / beyond / relationship','Unit 6 Read and Think2: v7 canonical Sheet IDs 2035-2052'],['person / can / one / shop / yesterday / life / country / another / product / water / island / people / different / place / there is / border / important / student / study / connect / think','Unit0-6-3/G1-G2 cumulative']],
auditNote:'最新v7正本Unit6 Read and Think2（Sheet ID2035〜2052）を直接照合。in the open air / encourage A to B / sell-sold / support / exception / in fact / coat / depend on / third / surround / interdependent / import / daily / trade / quite / survival / beyond / relationshipを、国どうしの貿易と相互依存の説明に統合。Unit6後のReal Life English 6・Stage Activity 3・Let’s Read 2はコア単元に含めていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
