(()=>{const D=window.V10_PASSAGES_G3_NH;
let m=D['Unit 0'];
m.sentences=['Today our class has a short activity.','We talk about a new side of a classmate.','A musical is one topic.','An actor is in the musical.','I did not know that before.','I discover a new side of my friend.','Another topic is music and drawing.','We see one picture from a friend.','We talk about one interest together.','Finally, I understand my friend better.','The activity is simple but interesting.','I want to discover more about my friend.'];
m.fullTranslation='「今日、私たちのクラスでは短い活動があります。私たちはクラスメートの新しい一面について話します。1つの話題はミュージカルです。そのミュージカルには俳優が出ています。私はそれを前には知りませんでした。私は友達の新しい一面を発見します。別の話題は音楽と絵です。私たちは友達から1枚の絵を見ます。私たちは1つの興味についていっしょに話します。ついに、私は友達のことをもっとよく理解します。その活動は簡単ですがおもしろいです。私は友達についてもっと発見したいです。」';
m.slashRows=[{en:'Today / our class has / a short activity.',jp:'今日 / 私たちのクラスではあります / 短い活動が'},{en:'We talk about / a new side / of a classmate.',jp:'私たちは話します / 新しい一面について / クラスメートの'},{en:'A musical is / one topic.',jp:'ミュージカルは〜です / 1つの話題'},{en:'An actor is / in the musical.',jp:'俳優がいます / そのミュージカルに'},{en:'I did not know / that / before.',jp:'私は知りませんでした / それを / 前には'},{en:'I discover / a new side / of my friend.',jp:'私は発見します / 新しい一面を / 友達の'},{en:'Another topic is / music and drawing.',jp:'別の話題は〜です / 音楽と絵'},{en:'We see / one picture / from a friend.',jp:'私たちは見ます / 1枚の絵を / 友達から'},{en:'We talk about / one interest / together.',jp:'私たちは話します / 1つの興味について / いっしょに'},{en:'Finally, / I understand / my friend / better.',jp:'ついに / 私は理解します / 友達を / もっとよく'},{en:'The activity is / simple / but interesting.',jp:'その活動は〜です / 簡単 / しかしおもしろい'},{en:'I want to discover / more / about my friend.',jp:'私は発見したいです / もっと / 友達について'}];
m.questions=[{prompt:'1. 何の新しい一面について話しますか。本文から英語で答えなさい。',answer:'a classmate',evidence:'We talk about a new side of a classmate.',evidenceJp:'私たちはクラスメートの新しい一面について話します。',reason:'of の後ろが a classmate です。'},{prompt:'2. 1つの話題は何ですか。本文から英語で答えなさい。',answer:'a musical',evidence:'A musical is one topic.',evidenceJp:'1つの話題はミュージカルです。',reason:'主語が A musical です。'},{prompt:'3. ミュージカルには誰がいますか。本文から英語で答えなさい。',answer:'an actor',evidence:'An actor is in the musical.',evidenceJp:'そのミュージカルには俳優が出ています。',reason:'主語が An actor です。'},{prompt:'4. 話し手は何を発見しますか。本文から英語で答えなさい。',answer:'a new side of my friend',evidence:'I discover a new side of my friend.',evidenceJp:'私は友達の新しい一面を発見します。',reason:'discover の目的語が a new side of my friend です。'},{prompt:'5. 最後に話し手は誰をもっとよく理解しますか。本文から英語で答えなさい。',answer:'my friend',evidence:'Finally, I understand my friend better.',evidenceJp:'ついに、私は友達のことをもっとよく理解します。',reason:'understand の目的語が my friend です。'}];
m.auditNote+=' 人手語形監査で自動三単現 likes / wants / shows と不要な複数派生を削除。';

m=D['Unit 1-1'];
m.sentences[5]='We talk about travel in Japan.';m.sentences[6]='Kyoto has an old building.';m.sentences[7]='Osaka is interesting too.';
m.slashRows[5]={en:'We talk about / travel / in Japan.',jp:'私たちは話します / 旅行について / 日本の'};m.slashRows[6]={en:'Kyoto has / an old building.',jp:'京都にはあります / 古い建物が'};m.slashRows[7]={en:'Osaka is / interesting / too.',jp:'大阪も〜です / おもしろい / も'};
m.fullTranslation='「私は京都に1度行ったことがあります。大阪には2度行ったことがあります。小さな博物館にも行ったことがあります。北海道には一度も行ったことがありません。私の友達も京都に行ったことがあります。私たちは日本の旅行について話します。京都には古い建物があります。大阪もおもしろいです。私は友達に京都での写真を1枚見せます。私たちはいつかいっしょに旅行したいです。私は自分の経験をノートに書きます。旅行は日本の新しい一面を発見する助けになります。」';
m.auditNote+=' 人手語形監査で自動複数派生 places / buildings を削除。';

m=D['Unit 1-2'];
m.sentences=['Today, we meet a foreigner at school.','We talk about Japanese fashion.','I hear about regional fashion from him.','He has been to Kyoto and Osaka.','I ask, “Have you ever been to Kyoto?”','His answer is, “Yes, twice.”','I say, “I have never been there.”','I haven’t seen that regional style before.','We see a picture of the style.','The picture is colorful and interesting.','We talk about Japanese culture too.','I want to learn more from him.'];
m.fullTranslation='「今日、私たちは学校で外国人に会います。私たちは日本のファッションについて話します。私は彼から地方のファッションについて聞きます。彼は京都と大阪に行ったことがあります。私は『今まで京都に行ったことがありますか』とたずねます。彼の答えは『はい、2度あります』です。私は『私はそこに一度も行ったことがありません』と言います。私はその地方のスタイルを前に見たことがありません。私たちはそのスタイルの写真を見ます。その写真は色鮮やかでおもしろいです。私たちは日本文化についても話します。私は彼からもっと学びたいです。」';
m.slashRows=[{en:'Today, / we meet / a foreigner / at school.',jp:'今日 / 私たちは会います / 外国人に / 学校で'},{en:'We talk about / Japanese fashion.',jp:'私たちは話します / 日本のファッションについて'},{en:'I hear about / regional fashion / from him.',jp:'私は聞きます / 地方のファッションについて / 彼から'},{en:'He has been to / Kyoto and Osaka.',jp:'彼は行ったことがあります / 京都と大阪に'},{en:'I ask, / “Have you ever been to Kyoto?”',jp:'私はたずねます / 「今まで京都に行ったことがありますか」'},{en:'His answer is, / “Yes, twice.”',jp:'彼の答えは〜です / 「はい、2度あります」'},{en:'I say, / “I have never been there.”',jp:'私は言います / 「私はそこに一度も行ったことがありません」'},{en:'I haven’t seen / that regional style / before.',jp:'私は見たことがありません / その地方のスタイルを / 前に'},{en:'We see / a picture / of the style.',jp:'私たちは見ます / 写真を / そのスタイルの'},{en:'The picture is / colorful and interesting.',jp:'その写真は〜です / 色鮮やかでおもしろい'},{en:'We talk about / Japanese culture / too.',jp:'私たちは話します / 日本文化について / も'},{en:'I want to learn / more / from him.',jp:'私は学びたいです / もっと / 彼から'}];
m.questions=[{prompt:'1. 誰に学校で会いますか。本文から英語で答えなさい。',answer:'a foreigner',evidence:'Today, we meet a foreigner at school.',evidenceJp:'今日、私たちは学校で外国人に会います。',reason:'meet の目的語が a foreigner です。'},{prompt:'2. 何について話しますか。本文から英語で答えなさい。',answer:'Japanese fashion',evidence:'We talk about Japanese fashion.',evidenceJp:'私たちは日本のファッションについて話します。',reason:'talk about の後ろが Japanese fashion です。'},{prompt:'3. 話し手は何について聞きますか。本文から英語で答えなさい。',answer:'regional fashion',evidence:'I hear about regional fashion from him.',evidenceJp:'私は彼から地方のファッションについて聞きます。',reason:'hear about の後ろが regional fashion です。'},{prompt:'4. 外国人の答えでは京都に何度行ったことがありますか。本文から英語で答えなさい。',answer:'twice',evidence:'His answer is, “Yes, twice.”',evidenceJp:'彼の答えは「はい、2度あります」です。',reason:'回数を表す語が twice です。'},{prompt:'5. 話し手は地方のスタイルを前に見たことがありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I haven’t seen that regional style before.',evidenceJp:'私はその地方のスタイルを前に見たことがありません。',reason:'haven’t seen とあるので No です。'}];
m.auditNote+=' 人手語形監査で未登録三単現 visits / says / shows と不要な複数派生を削除。';

m=D['Unit 1-3'];
m.sentences[1]='A child and an adult can enjoy it.';m.sentences[7]='Some people use a simple drawing style in animation.';m.sentences[8]='Other people use a different genre.';m.sentences[9]='A good story can go global.';
m.slashRows[1]={en:'A child and an adult / can enjoy / it.',jp:'子どもと大人は / 楽しむことができます / それを'};m.slashRows[7]={en:'Some people / use / a simple drawing style / in animation.',jp:'何人かの人は / 使います / 簡単な絵のスタイルを / アニメーションで'};m.slashRows[8]={en:'Other people / use / a different genre.',jp:'別の人は / 使います / 別のジャンルを'};m.slashRows[9]={en:'A good story / can go / global.',jp:'よい物語は / 〜になれます / 世界的に'};
m.fullTranslation='「日本のアニメーションは世界的なジャンルです。子どもと大人はそれを楽しむことができます。冒険の物語は人々をわくわくさせることができます。さらに、アニメーションには前向きなメッセージがあることがあります。物語の質は大切です。絵の質も大切です。繊細な絵は静かな場面と調和することができます。何人かの人はアニメーションで簡単な絵のスタイルを使います。別の人は別のジャンルを使います。よい物語は世界的になることができます。世界中の人々が日本のアニメーションを楽しみます。私はその質が人気の理由の1つだと思います。」';
m.questions[1]={prompt:'2. 誰がアニメーションを楽しむことができますか。本文から英語で答えなさい。',answer:'a child and an adult',evidence:'A child and an adult can enjoy it.',evidenceJp:'子どもと大人はそれを楽しむことができます。',reason:'can enjoy の主語が A child and an adult です。'};
m.auditNote+=' 人手語形監査で自動派生 children / adults / uses / stories を削除。';

m=D['Unit 1-4'];m.sentences[11]='This history can help us understand Japanese animation.';m.slashRows[11]={en:'This history / can help / us / understand / Japanese animation.',jp:'この歴史は / 助けることができます / 私たちが / 理解するのを / 日本のアニメーションを'};m.fullTranslation='「絵巻物には日本で長い歴史があります。その起源は古い日本美術にあると言われています。絵は動きを表現することができます。1つの絵は次の絵へつながることができます。この手法は動きをはっきり示すことができます。現代のアニメーションはこの手法を利用することができます。古い美術は現代のアニメーションに影響を及ぼすことがあります。私たちはこのつながりの存在を無視すべきではありません。そのつながりは完全には明らかではありません。利点は、1枚の絵で動きを示せることです。人によって美術の好みは異なります。この歴史は日本のアニメーションを理解する助けになります。」';m.auditNote+=' 人手語形監査で自動三単現 helps を削除。';
})();
