window.V10_PASSAGES_G3_NH=window.V10_PASSAGES_G3_NH||{};

window.V10_PASSAGES_G3_NH['Unit 2-1']={
id:'V10-NH-G3-U2-1-001',textbook:'ニューホライズン',grade:'3',section:'Unit 2-1',level:'HOP',title:'An Interview about Ethical Fashion',
sentences:['Today I read an essay about ethical fashion.','The essay has an interview with a designer.','I have already read the first message.','I have just read the next message too.','The designer talks about ethical clothing.','One message is about a new design.','Another message is about sleep.','I have not read the last message yet.','My friend asks, “Have you read it yet?”','I answer, “Not yet.”','I want to finish the essay today.','The interview makes me think about fashion.'],
fullTranslation:'「今日、私はエシカルファッションについての評論を読みます。その評論にはデザイナーへのインタビューがあります。私は最初のメッセージをすでに読みました。次のメッセージもちょうど読みました。そのデザイナーは倫理的な衣類について話します。1つのメッセージは新しいデザインについてです。別のメッセージは睡眠についてです。私は最後のメッセージをまだ読んでいません。友達が『もうそれを読みましたか』とたずねます。私は『まだです』と答えます。私は今日その評論を読み終えたいです。そのインタビューは私にファッションについて考えさせます。」',
slashRows:[{en:'Today / I read / an essay / about ethical fashion.',jp:'今日 / 私は読みます / 評論を / エシカルファッションについての'},{en:'The essay has / an interview / with a designer.',jp:'その評論にはあります / インタビューが / デザイナーとの'},{en:'I have already read / the first message.',jp:'私はすでに読みました / 最初のメッセージを'},{en:'I have just read / the next message / too.',jp:'私はちょうど読みました / 次のメッセージを / も'},{en:'The designer talks about / ethical clothing.',jp:'そのデザイナーは話します / 倫理的な衣類について'},{en:'One message is / about a new design.',jp:'1つのメッセージは〜です / 新しいデザインについて'},{en:'Another message is / about sleep.',jp:'別のメッセージは〜です / 睡眠について'},{en:'I have not read / the last message / yet.',jp:'私は読んでいません / 最後のメッセージを / まだ'},{en:'My friend asks, / “Have you read it yet?”',jp:'友達がたずねます / 「もうそれを読みましたか」'},{en:'I answer, / “Not yet.”',jp:'私は答えます / 「まだです」'},{en:'I want to finish / the essay / today.',jp:'私は読み終えたいです / その評論を / 今日'},{en:'The interview makes / me / think about fashion.',jp:'そのインタビューは〜させます / 私に / ファッションについて考え'}],
questions:[{prompt:'1. 何についての評論を読みますか。本文から英語で答えなさい。',answer:'ethical fashion',evidence:'Today I read an essay about ethical fashion.',evidenceJp:'今日、私はエシカルファッションについての評論を読みます。',reason:'about の後ろが ethical fashion です。'},{prompt:'2. 評論には誰とのインタビューがありますか。本文から英語で答えなさい。',answer:'a designer',evidence:'The essay has an interview with a designer.',evidenceJp:'その評論にはデザイナーへのインタビューがあります。',reason:'with の後ろが a designer です。'},{prompt:'3. 最初のメッセージはもう読みましたか。本文に合うように Yes / No で答えなさい。',answer:'Yes',evidence:'I have already read the first message.',evidenceJp:'私は最初のメッセージをすでに読みました。',reason:'have already read とあるので Yes です。'},{prompt:'4. 最後のメッセージはもう読みましたか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:'I have not read the last message yet.',evidenceJp:'私は最後のメッセージをまだ読んでいません。',reason:'not read ... yet とあるので No です。'},{prompt:'5. インタビューは話し手に何について考えさせますか。本文から英語で答えなさい。',answer:'fashion',evidence:'The interview makes me think about fashion.',evidenceJp:'そのインタビューは私にファッションについて考えさせます。',reason:'think about の後ろが fashion です。'}],
allowedWords:[['already / interview / just / message / essay / yet / designer / sleep / ethical / read-read-read','Unit 2 Part1: v7 canonical Sheet IDs 1702-1711'],['fashion / clothing / design / today / first / next / another / new / last / friend / ask / answer / want to / finish / make A B / think about','Unit0-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit2 Part1（Sheet ID1702〜1711）を直接照合。already / interview / just / message / essay / yet / designer / sleep / ethical / readを、エシカルファッションのインタビューを読む現在完了の文脈に統合。Part2のfor / since / recycle / impact等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 2-2']={
id:'V10-NH-G3-U2-2-001',textbook:'ニューホライズン',grade:'3',section:'Unit 2-2',level:'HOP',title:'How Long Have You Known This Design?',
sentences:['I call a designer about a new design.','I ask, “How long have you known about this design?”','The designer answers, “I have known it since last year.”','The company can introduce the design this year.','The design can have a good impact.','We can recycle an old accessory.','The old accessory can become a new product.','I have known about recycling for two years.','My friend has known about it since last year.','We talk about the design after school.','I want to learn more about its impact.','This idea can help us think about clothing.'],
fullTranslation:'「私は新しいデザインについてデザイナーに電話をします。私は『このデザインについてどれくらい長く知っていますか』とたずねます。デザイナーは『去年から知っています』と答えます。その会社は今年そのデザインを導入できます。そのデザインはよい影響を与えることができます。私たちは古いアクセサリーをリサイクルできます。古いアクセサリーは新しい製品になることができます。私はリサイクルについて2年間知っています。友達は去年からそれについて知っています。私たちは放課後、そのデザインについて話します。私はその影響についてもっと学びたいです。この考えは私たちが衣類について考える助けになります。」',
slashRows:[{en:'I call / a designer / about a new design.',jp:'私は電話をします / デザイナーに / 新しいデザインについて'},{en:'I ask, / “How long have you known / about this design?”',jp:'私はたずねます / 「どれくらい長く知っていますか / このデザインについて」'},{en:'The designer answers, / “I have known it / since last year.”',jp:'デザイナーは答えます / 「私はそれを知っています / 去年から」'},{en:'The company can introduce / the design / this year.',jp:'その会社は導入できます / そのデザインを / 今年'},{en:'The design can have / a good impact.',jp:'そのデザインは持つことができます / よい影響を'},{en:'We can recycle / an old accessory.',jp:'私たちはリサイクルできます / 古いアクセサリーを'},{en:'The old accessory can become / a new product.',jp:'古いアクセサリーは〜になれます / 新しい製品に'},{en:'I have known / about recycling / for two years.',jp:'私は知っています / リサイクルについて / 2年間'},{en:'My friend has known / about it / since last year.',jp:'私の友達は知っています / それについて / 去年から'},{en:'We talk about / the design / after school.',jp:'私たちは話します / そのデザインについて / 放課後に'},{en:'I want to learn / more / about its impact.',jp:'私は学びたいです / もっと / その影響について'},{en:'This idea can help / us / think about clothing.',jp:'この考えは助けます / 私たちが / 衣類について考えるのを'}],
questions:[{prompt:'1. 誰に電話をしますか。本文から英語で答えなさい。',answer:'a designer',evidence:'I call a designer about a new design.',evidenceJp:'私は新しいデザインについてデザイナーに電話をします。',reason:'call の目的語が a designer です。'},{prompt:'2. デザイナーはいつからそのデザインを知っていますか。本文から英語で答えなさい。',answer:'since last year',evidence:'The designer answers, “I have known it since last year.”',evidenceJp:'デザイナーは「去年から知っています」と答えます。',reason:'since last year が開始時点です。'},{prompt:'3. 会社は何を導入できますか。本文から英語で答えなさい。',answer:'the design',evidence:'The company can introduce the design this year.',evidenceJp:'その会社は今年そのデザインを導入できます。',reason:'introduce の目的語が the design です。'},{prompt:'4. 何をリサイクルできますか。本文から英語で答えなさい。',answer:'an old accessory',evidence:'We can recycle an old accessory.',evidenceJp:'私たちは古いアクセサリーをリサイクルできます。',reason:'recycle の目的語が an old accessory です。'},{prompt:'5. 話し手はリサイクルについてどれくらいの間知っていますか。本文から英語で答えなさい。',answer:'for two years',evidence:'I have known about recycling for two years.',evidenceJp:'私はリサイクルについて2年間知っています。',reason:'for two years が期間です。'}],
allowedWords:[['for ~ / introduce / since ~ / recycle / How long ~? / design / impact / become-became-become / accessory / call','Unit 2 Part2: v7 canonical Sheet IDs 1712-1721'],['designer / know-known / company / year / good / old / new / product / friend / after school / want to / learn / more / idea / can / help / think about / clothing','Unit0-2-1/G1-G2 cumulative']],
auditNote:'最新v7正本Unit2 Part2（Sheet ID1712〜1721）を直接照合。for / introduce / since / recycle / How long / design / impact / become / accessory / callを、デザインとリサイクルについての現在完了継続の文脈に統合。Read and Thinkのcompany / less / avoid ~ing / wool / wage等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 2-3']={
id:'V10-NH-G3-U2-3-001',textbook:'ニューホライズン',grade:'3',section:'Unit 2-3',level:'HOP',title:'A Company That Uses Less Material',
sentences:['I read about a clothing company.','The company wants to use less material.','It can avoid using too much wool.','The company can include recycled material in a product.','Moreover, it can use an old design again.','A worker talks about the use of wool.','The company can prohibit a harmful chemical.','This action can lead to a better product.','My friend says, “You’ve learned a lot.”','I think the company has a good idea.','We write about the company in class.','I want to know more about responsible clothing.'],
fullTranslation:'「私はある衣料品会社について読みます。その会社はより少ない材料を使いたいと考えています。羊毛を使いすぎることを避けることができます。その会社は製品に再利用された材料を含めることができます。さらに、古いデザインをもう一度使うこともできます。労働者が羊毛の使用について話します。その会社は有害な化学物質を禁止することができます。この行動はよりよい製品につながることがあります。友達が『たくさん学んだね』と言います。私はその会社によい考えがあると思います。私たちは授業でその会社について書きます。私は責任ある衣類についてもっと知りたいです。」',
slashRows:[{en:'I read about / a clothing company.',jp:'私は読みます / 衣料品会社について'},{en:'The company wants to use / less material.',jp:'その会社は使いたいです / より少ない材料を'},{en:'It can avoid using / too much wool.',jp:'それは使うことを避けられます / 多すぎる羊毛を'},{en:'The company can include / recycled material / in a product.',jp:'その会社は含めることができます / 再利用された材料を / 製品に'},{en:'Moreover, / it can use / an old design / again.',jp:'さらに / それは使えます / 古いデザインを / 再び'},{en:'A worker talks about / the use / of wool.',jp:'労働者は話します / 使用について / 羊毛の'},{en:'The company can prohibit / a harmful chemical.',jp:'その会社は禁止できます / 有害な化学物質を'},{en:'This action can lead to / a better product.',jp:'この行動はつながることがあります / よりよい製品に'},{en:'My friend says, / “You’ve learned a lot.”',jp:'友達が言います / 「たくさん学んだね」'},{en:'I think / the company has / a good idea.',jp:'私は思います / その会社にはあると / よい考えが'},{en:'We write about / the company / in class.',jp:'私たちは書きます / その会社について / 授業で'},{en:'I want to know / more / about responsible clothing.',jp:'私は知りたいです / もっと / 責任ある衣類について'}],
questions:[{prompt:'1. 何について読みますか。本文から英語で答えなさい。',answer:'a clothing company',evidence:'I read about a clothing company.',evidenceJp:'私はある衣料品会社について読みます。',reason:'read about の後ろが a clothing company です。'},{prompt:'2. 会社は何をより少なく使いたいですか。本文から英語で答えなさい。',answer:'material',evidence:'The company wants to use less material.',evidenceJp:'その会社はより少ない材料を使いたいと考えています。',reason:'less の後ろが material です。'},{prompt:'3. 何を使いすぎることを避けられますか。本文から英語で答えなさい。',answer:'wool',evidence:'It can avoid using too much wool.',evidenceJp:'羊毛を使いすぎることを避けることができます。',reason:'using の目的語が wool です。'},{prompt:'4. 会社は何を禁止できますか。本文から英語で答えなさい。',answer:'a harmful chemical',evidence:'The company can prohibit a harmful chemical.',evidenceJp:'その会社は有害な化学物質を禁止することができます。',reason:'prohibit の目的語が a harmful chemical です。'},{prompt:'5. この行動は何につながることがありますか。本文から英語で答えなさい。',answer:'a better product',evidence:'This action can lead to a better product.',evidenceJp:'この行動はよりよい製品につながることがあります。',reason:'lead to の後ろが a better product です。'}],
allowedWords:[['company / less / avoid ~ing / you’ve / lead / moreover / include / prohibit / wool / worker / use','Unit 2 Read and Think1,2 shared pool first half: v7 canonical Sheet IDs 1722-1732'],['material / recycled / product / old / design / again / chemical / action / better / friend / learn / think / good / idea / write about / class / want to / know / more / responsible / clothing','Unit0-2-2/G1-G2 cumulative']],
auditNote:'最新v7正本Unit2 Read and Think1,2共通プール（Sheet ID1722〜1743）の前半ID1722〜1732をUnit2-3へ割り当て。company / less / avoid ~ing / you’ve / lead / moreover / include / prohibit / wool / worker / useを衣料品会社の材料利用の説明に統合。avoid ~ing は当該単元の明示表現としてusingを使用。後半のwage / leather / labor / fur / condition / responsible / chemical / low / negative / fairは原則先取りしないが、chemical / responsibleは累積語として本文末のつながりに限定。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_NH['Unit 2-4']={
id:'V10-NH-G3-U2-4-001',textbook:'ニューホライズン',grade:'3',section:'Unit 2-4',level:'HOP',title:'What Responsible Clothing Means',
sentences:['A clothing company has a responsibility.','A worker needs a fair condition.','A low wage can have a negative impact.','Fair labor is important.','A responsible company should think about a worker.','It should also think about each chemical in clothing.','Leather and fur are materials for some clothing.','A company can choose another material.','The condition of labor can change a product.','A fair wage is important for a worker.','I think responsible clothing needs a fair idea.','I want to learn more before I choose clothing.'],
fullTranslation:'「衣料品会社には責任があります。労働者には公平な状況が必要です。低い賃金は悪い影響を与えることがあります。公平な労働は大切です。責任ある会社は労働者について考えるべきです。また、衣類に含まれるそれぞれの化学物質についても考えるべきです。革と毛皮は一部の衣類の材料です。会社は別の材料を選ぶことができます。労働の状況は製品を変えることがあります。公平な賃金は労働者にとって大切です。責任ある衣類には公平な考え方が必要だと思います。私は衣類を選ぶ前にもっと学びたいです。」',
slashRows:[{en:'A clothing company has / a responsibility.',jp:'衣料品会社にはあります / 責任が'},{en:'A worker needs / a fair condition.',jp:'労働者には必要です / 公平な状況が'},{en:'A low wage can have / a negative impact.',jp:'低い賃金は持つことがあります / 悪い影響を'},{en:'Fair labor is / important.',jp:'公平な労働は〜です / 大切'},{en:'A responsible company / should think about / a worker.',jp:'責任ある会社は / 考えるべきです / 労働者について'},{en:'It should also think about / each chemical / in clothing.',jp:'それはまた考えるべきです / それぞれの化学物質について / 衣類の'},{en:'Leather and fur are / materials / for some clothing.',jp:'革と毛皮は〜です / 材料 / 一部の衣類の'},{en:'A company can choose / another material.',jp:'会社は選ぶことができます / 別の材料を'},{en:'The condition / of labor / can change / a product.',jp:'状況は / 労働の / 変えることがあります / 製品を'},{en:'A fair wage is / important / for a worker.',jp:'公平な賃金は〜です / 大切 / 労働者にとって'},{en:'I think / responsible clothing needs / a fair idea.',jp:'私は思います / 責任ある衣類には必要だと / 公平な考えが'},{en:'I want to learn / more / before I choose clothing.',jp:'私は学びたいです / もっと / 衣類を選ぶ前に'}],
questions:[{prompt:'1. 労働者にはどのような状況が必要ですか。本文から英語で答えなさい。',answer:'a fair condition',evidence:'A worker needs a fair condition.',evidenceJp:'労働者には公平な状況が必要です。',reason:'needs の目的語が a fair condition です。'},{prompt:'2. 低い賃金はどのような影響を与えることがありますか。本文から英語で答えなさい。',answer:'a negative impact',evidence:'A low wage can have a negative impact.',evidenceJp:'低い賃金は悪い影響を与えることがあります。',reason:'have の目的語が a negative impact です。'},{prompt:'3. 何が大切ですか。本文から英語で答えなさい。',answer:'fair labor',evidence:'Fair labor is important.',evidenceJp:'公平な労働は大切です。',reason:'important の主語が Fair labor です。'},{prompt:'4. 革と毛皮は何ですか。本文から英語で答えなさい。',answer:'materials',evidence:'Leather and fur are materials for some clothing.',evidenceJp:'革と毛皮は一部の衣類の材料です。',reason:'be動詞の後ろが materials です。'},{prompt:'5. 公平な賃金は誰にとって大切ですか。本文から英語で答えなさい。',answer:'a worker',evidence:'A fair wage is important for a worker.',evidenceJp:'公平な賃金は労働者にとって大切です。',reason:'for の後ろが a worker です。'}],
allowedWords:[['wage / leather / labor / fur / condition / clothing / responsible / chemical / low / negative / fair','Unit 2 Read and Think1,2 shared pool second half: v7 canonical Sheet IDs 1733-1743'],['company / worker / responsibility / need / impact / important / should / think about / each / material / some / can / choose / another / change / product / idea / want to / learn / more / before','Unit0-2-3/G1-G2 cumulative']],
auditNote:'最新v7正本Unit2 Read and Think1,2共通プール後半（Sheet ID1733〜1743）をUnit2-4へ割り当て。wage / leather / labor / fur / condition / clothing / responsible / chemical / low / negative / fairを、責任ある衣類と労働条件の説明に統合。Unit3のtrouble / endangered / extinction等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
