window.V10_PASSAGES_G3_SS=window.V10_PASSAGES_G3_SS||{};

window.V10_PASSAGES_G3_SS['PROGRAM 1-1']={
id:'V10-SS-G3-P1-1-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 1-1',level:'HOP',title:'A Colorful Bento at Noon',
sentences:['It is noon at school.','We go to the schoolyard.','Someone has a colorful bento.','The bento is in a small bag.','A colorful lunch is fun to see.','Someone also has a suitcase.','The suitcase is near the schoolyard.','We sit together at noon.','I look at the colorful food.','My friend talks about the bento.','We eat lunch in the schoolyard.','Noon is a good time with friends.'],
fullTranslation:'「学校では正午です。私たちは校庭へ行きます。だれかが色彩豊かなお弁当を持っています。そのお弁当は小さな袋に入っています。色彩豊かな昼食は見ていて楽しいです。だれかはスーツケースも持っています。そのスーツケースは校庭の近くにあります。私たちは正午にいっしょに座ります。私は色彩豊かな食べ物を見ます。友達がお弁当について話します。私たちは校庭で昼食を食べます。正午は友達と過ごすよい時間です。」',
slashRows:[{en:'It is / noon / at school.',jp:'〜です / 正午 / 学校では'},{en:'We go to / the schoolyard.',jp:'私たちは行きます / 校庭へ'},{en:'Someone has / a colorful bento.',jp:'だれかが持っています / 色彩豊かなお弁当を'},{en:'The bento is / in a small bag.',jp:'そのお弁当はあります / 小さな袋の中に'},{en:'A colorful lunch is / fun to see.',jp:'色彩豊かな昼食は〜です / 見ていて楽しい'},{en:'Someone also has / a suitcase.',jp:'だれかはまた持っています / スーツケースを'},{en:'The suitcase is / near the schoolyard.',jp:'そのスーツケースはあります / 校庭の近くに'},{en:'We sit / together / at noon.',jp:'私たちは座ります / いっしょに / 正午に'},{en:'I look at / the colorful food.',jp:'私は見ます / 色彩豊かな食べ物を'},{en:'My friend talks about / the bento.',jp:'友達は話します / お弁当について'},{en:'We eat / lunch / in the schoolyard.',jp:'私たちは食べます / 昼食を / 校庭で'},{en:'Noon is / a good time / with friends.',jp:'正午は〜です / よい時間 / 友達と'}],
questions:[{prompt:'1. 学校では何時ごろですか。本文から英語で1語抜き出しなさい。',answer:'noon',evidence:'It is noon at school.',evidenceJp:'学校では正午です。',reason:'時を表す語が noon です。'},{prompt:'2. どこへ行きますか。本文から英語で答えなさい。',answer:'the schoolyard',evidence:'We go to the schoolyard.',evidenceJp:'私たちは校庭へ行きます。',reason:'go to の後ろが the schoolyard です。'},{prompt:'3. だれかはどのようなお弁当を持っていますか。本文から英語で答えなさい。',answer:'a colorful bento',evidence:'Someone has a colorful bento.',evidenceJp:'だれかが色彩豊かなお弁当を持っています。',reason:'has の目的語が a colorful bento です。'},{prompt:'4. ほかに何を持っている人がいますか。本文から英語で答えなさい。',answer:'a suitcase',evidence:'Someone also has a suitcase.',evidenceJp:'だれかはスーツケースも持っています。',reason:'has の目的語が a suitcase です。'},{prompt:'5. 昼食はどこで食べますか。本文から英語で答えなさい。',answer:'in the schoolyard',evidence:'We eat lunch in the schoolyard.',evidenceJp:'私たちは校庭で昼食を食べます。',reason:'場所を表す部分が in the schoolyard です。'}],
allowedWords:[['noon / schoolyard / someone / colorful / suitcase','PROGRAM1 1-1: v7 canonical Sheet IDs 3558-3562'],['school / go to / bento / small / bag / lunch / fun / see / also / near / sit / together / look at / food / friend / talk about / eat / good / time','G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM1 1-1（Sheet ID3558〜3562）を直接照合。noon / schoolyard / someone / colorful / suitcaseを、正午の校庭でお弁当を見る場面に統合。1-2のmusical instrument / eel / marathon / homemadeは先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 1-2']={
id:'V10-SS-G3-P1-2-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 1-2',level:'HOP',title:'A Homemade Bento after a Marathon',
sentences:['My friend is in a marathon today.','After the marathon, we meet at home.','There is a homemade bento on the table.','The bento has eel in it.','The eel is in a small portion.','We also hear a musical instrument.','The musical instrument is in the next room.','My friend eats the homemade bento.','I eat some eel too.','We talk about the marathon.','The homemade food is very good.','It is a quiet time after the marathon.'],
fullTranslation:'「友達は今日マラソンに出ています。マラソンのあと、私たちは家で会います。テーブルの上には自家製のお弁当があります。そのお弁当にはウナギが入っています。ウナギは少量に分けられています。楽器の音も聞こえます。その楽器は隣の部屋にあります。友達は自家製のお弁当を食べます。私もウナギを少し食べます。私たちはマラソンについて話します。自家製の食べ物はとてもおいしいです。マラソンのあとの静かな時間です。」',
slashRows:[{en:'My friend is / in a marathon / today.',jp:'友達は〜です / マラソンに参加して / 今日'},{en:'After the marathon, / we meet / at home.',jp:'マラソンのあと / 私たちは会います / 家で'},{en:'There is / a homemade bento / on the table.',jp:'あります / 自家製のお弁当が / テーブルの上に'},{en:'The bento has / eel / in it.',jp:'そのお弁当には入っています / ウナギが / その中に'},{en:'The eel is / in a small portion.',jp:'そのウナギはあります / 少量に分けられて'},{en:'We also hear / a musical instrument.',jp:'私たちはまた聞きます / 楽器を'},{en:'The musical instrument is / in the next room.',jp:'その楽器はあります / 隣の部屋に'},{en:'My friend eats / the homemade bento.',jp:'友達は食べます / 自家製のお弁当を'},{en:'I eat / some eel / too.',jp:'私は食べます / ウナギを少し / も'},{en:'We talk about / the marathon.',jp:'私たちは話します / マラソンについて'},{en:'The homemade food is / very good.',jp:'その自家製の食べ物は〜です / とてもおいしい'},{en:'It is / a quiet time / after the marathon.',jp:'それは〜です / 静かな時間 / マラソンのあと'}],
questions:[{prompt:'1. 友達は今日何に参加していますか。本文から英語で答えなさい。',answer:'a marathon',evidence:'My friend is in a marathon today.',evidenceJp:'友達は今日マラソンに出ています。',reason:'in の後ろが a marathon です。'},{prompt:'2. テーブルの上には何がありますか。本文から英語で答えなさい。',answer:'a homemade bento',evidence:'There is a homemade bento on the table.',evidenceJp:'テーブルの上には自家製のお弁当があります。',reason:'There is の後ろが a homemade bento です。'},{prompt:'3. お弁当には何が入っていますか。本文から英語で答えなさい。',answer:'eel',evidence:'The bento has eel in it.',evidenceJp:'そのお弁当にはウナギが入っています。',reason:'has の目的語が eel です。'},{prompt:'4. 何の音も聞こえますか。本文から英語で答えなさい。',answer:'a musical instrument',evidence:'We also hear a musical instrument.',evidenceJp:'楽器の音も聞こえます。',reason:'hear の目的語が a musical instrument です。'},{prompt:'5. 何について話しますか。本文から英語で答えなさい。',answer:'the marathon',evidence:'We talk about the marathon.',evidenceJp:'私たちはマラソンについて話します。',reason:'talk about の後ろが the marathon です。'}],
allowedWords:[['musical instrument / eel / marathon / homemade','PROGRAM1 1-2: v7 canonical Sheet IDs 3563-3566'],['friend / today / after / meet / home / there is / bento / table / small / portion / also / hear / next / room / eat / some / too / talk about / food / very / good / quiet / time','G1-G2 and PROGRAM1 1-1 cumulative']],
auditNote:'最新v7正本PROGRAM1 1-2（Sheet ID3563〜3566）を直接照合。musical instrument / eel / marathon / homemadeを、マラソン後に自家製弁当を食べる場面に統合。1-3のdone / gotten / I’ve / eaten / suggest / reduce / been / never / ever等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};

window.V10_PASSAGES_G3_SS['PROGRAM 1-3']={
id:'V10-SS-G3-P1-3-001',textbook:'サンシャイン',grade:'3',section:'PROGRAM 1-3',level:'HOP',title:'Bentos I Have Eaten',
sentences:["I've eaten a homemade bento twice.","I've never eaten eel in a bento.",'Have you ever eaten a colorful bento?','My friend has eaten a few kinds of bento.','I have heard of a variety of Japanese bentos.','A normal bento has a few portions of food.','I suggest a small portion for lunch.','A small portion can reduce the size of a bento.','Popular bentos can sell out at noon.','I have gotten a bento at school before.','I have done this twice.','Bentos have been an interesting part of lunch for me.'],
fullTranslation:'「私は自家製のお弁当を2回食べたことがあります。お弁当でウナギを食べたことは一度もありません。あなたは今までに色彩豊かなお弁当を食べたことがありますか。友達はいくつかの種類のお弁当を食べたことがあります。私はさまざまな日本のお弁当について聞いたことがあります。普通のお弁当には食べ物がいくつかの部分に分けて入っています。私は昼食には少量を勧めます。少量にするとお弁当の大きさを減らすことができます。人気のお弁当は正午には売り切れることがあります。私は以前、学校でお弁当を手に入れたことがあります。私はこれを2回したことがあります。私にとって、お弁当は昼食のおもしろい一部であり続けています。」',
slashRows:[{en:"I've eaten / a homemade bento / twice.",jp:'私は食べたことがあります / 自家製のお弁当を / 2回'},{en:"I've never eaten / eel / in a bento.",jp:'私は一度も食べたことがありません / ウナギを / お弁当で'},{en:'Have you ever eaten / a colorful bento?',jp:'あなたは今までに食べたことがありますか / 色彩豊かなお弁当を'},{en:'My friend has eaten / a few kinds / of bento.',jp:'友達は食べたことがあります / いくつかの種類を / お弁当の'},{en:'I have heard of / a variety of Japanese bentos.',jp:'私は聞いたことがあります / さまざまな日本のお弁当について'},{en:'A normal bento has / a few portions / of food.',jp:'普通のお弁当にはあります / いくつかの部分が / 食べ物の'},{en:'I suggest / a small portion / for lunch.',jp:'私は勧めます / 少量を / 昼食に'},{en:'A small portion / can reduce / the size / of a bento.',jp:'少量にすると / 減らすことができます / 大きさを / お弁当の'},{en:'Popular bentos / can sell out / at noon.',jp:'人気のお弁当は / 売り切れることがあります / 正午に'},{en:'I have gotten / a bento / at school / before.',jp:'私は手に入れたことがあります / お弁当を / 学校で / 以前に'},{en:'I have done / this / twice.',jp:'私はしたことがあります / これを / 2回'},{en:'Bentos have been / an interesting part / of lunch / for me.',jp:'お弁当は〜であり続けています / おもしろい一部 / 昼食の / 私にとって'}],
questions:[{prompt:'1. 自家製のお弁当を何回食べたことがありますか。本文から英語で答えなさい。',answer:'twice',evidence:"I've eaten a homemade bento twice.",evidenceJp:'私は自家製のお弁当を2回食べたことがあります。',reason:'回数を表す語が twice です。'},{prompt:'2. お弁当でウナギを食べたことがありますか。本文に合うように Yes / No で答えなさい。',answer:'No',evidence:"I've never eaten eel in a bento.",evidenceJp:'お弁当でウナギを食べたことは一度もありません。',reason:'never eaten とあるので No です。'},{prompt:'3. 友達はどのくらいの種類のお弁当を食べたことがありますか。本文から英語で答えなさい。',answer:'a few kinds',evidence:'My friend has eaten a few kinds of bento.',evidenceJp:'友達はいくつかの種類のお弁当を食べたことがあります。',reason:'eaten の目的語が a few kinds of bento です。'},{prompt:'4. 昼食には何を勧めますか。本文から英語で答えなさい。',answer:'a small portion',evidence:'I suggest a small portion for lunch.',evidenceJp:'私は昼食には少量を勧めます。',reason:'suggest の目的語が a small portion です。'},{prompt:'5. 人気のお弁当はいつ売り切れることがありますか。本文から英語で答えなさい。',answer:'at noon',evidence:'Popular bentos can sell out at noon.',evidenceJp:'人気のお弁当は正午には売り切れることがあります。',reason:'時を表す部分が at noon です。'}],
allowedWords:[["do-did-done / a few / get-got-gotten / I've / eat-ate-eaten / suggest / read-read-read / reduce / been / portion / never / cause / ever / normal / twice / sell out / hear of ~ / a variety of ~",'PROGRAM1 1-3: v7 canonical Sheet IDs 3567-3584'],['homemade / bento / eel / colorful / friend / Japanese / kind / food / small / lunch / can / size / popular / noon / school / before / this / interesting / part','PROGRAM1 1-1/1-2 and G1-G2 cumulative']],
auditNote:'最新v7正本PROGRAM1 1-3（Sheet ID3567〜3584）を直接照合。I’ve / eaten / never / ever / twice / gotten / done / beenを現在完了の経験として、a few / portion / suggest / reduce / sell out / hear of / a variety ofを弁当の説明に統合。PROGRAM2のjust / already / yet / health / regular等は先取りしていない。',vocabAudit:true,manualSlashAudit:true,manualMeaningAudit:true,manualQuestionAudit:true};
